#encoding: utf-8
Comune.create(:description => "Issogne", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 1346)
Comune.create(:description => "Allein", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 242)
Comune.create(:description => "Aosta", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 34062)
Comune.create(:description => "Arnad", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 1273)
Comune.create(:description => "Arvier", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 838)
Comune.create(:description => "Avise", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 307)
Comune.create(:description => "Ayas", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 1268)
Comune.create(:description => "Aymavilles", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 1850)
Comune.create(:description => "Bard", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 139)
Comune.create(:description => "Bionaz", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 239)
Comune.create(:description => "Brissogne", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 904)
Comune.create(:description => "Brusson", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 893)
Comune.create(:description => "Challand Saint Anselme", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Challand Saint Victor", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Chambave", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 945)
Comune.create(:description => "Chamois", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 93)
Comune.create(:description => "Champdepraz", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 640)
Comune.create(:description => "Champorcher", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 423)
Comune.create(:description => "Charvensod", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 2266)
Comune.create(:description => "Chatillon", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 4712)
Comune.create(:description => "Cogne", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 1467)
Comune.create(:description => "Courmayeur", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 2790)
Comune.create(:description => "Donnas", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 2645)
Comune.create(:description => "Doues", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 375)
Comune.create(:description => "Emarese", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 202)
Comune.create(:description => "Etroubles", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 439)
Comune.create(:description => "Fenis", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 1618)
Comune.create(:description => "Fontainemore", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 412)
Comune.create(:description => "Gaby", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 461)
Comune.create(:description => "Gignod", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 1256)
Comune.create(:description => "Gressan", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 2731)
Comune.create(:description => "Gressoney Saint Jean", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Hone", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 1146)
Comune.create(:description => "Introd", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 550)
Comune.create(:description => "Issime", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 403)
Comune.create(:description => "Jovencan", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 595)
Comune.create(:description => "La Magdeleine", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 91)
Comune.create(:description => "La Salle", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 1880)
Comune.create(:description => "La Thuile", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 716)
Comune.create(:description => "Lillianes", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 473)
Comune.create(:description => "Montjovet", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 1742)
Comune.create(:description => "Morgex", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 1907)
Comune.create(:description => "Nus", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 2577)
Comune.create(:description => "Ollomont", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 159)
Comune.create(:description => "Oyace", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 220)
Comune.create(:description => "Perloz", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 484)
Comune.create(:description => "Pollein", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 1397)
Comune.create(:description => "Pont Saint Martin", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Pontboset", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 201)
Comune.create(:description => "Pontey", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 708)
Comune.create(:description => "Quart", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 3103)
Comune.create(:description => "Rhemes Notre Dame", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Rhemes Saint Georges", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Roisan", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 852)
Comune.create(:description => "Saint Christophe", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Saint Denis", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Saint Marcel", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Saint Nicolas", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Saint Oyen", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Saint Pierre", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Saint Rhemy En Bosses", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Saint Vincent", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Sarre", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 4179)
Comune.create(:description => "Torgnon", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 497)
Comune.create(:description => "Valgrisenche", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 192)
Comune.create(:description => "Valpelline", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 600)
Comune.create(:description => "Valsavarenche", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 180)
Comune.create(:description => "Valtournenche", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 2198)
Comune.create(:description => "Verrayes", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 1266)
Comune.create(:description => "Verres", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 2624)
Comune.create(:description => "Villeneuve", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 , :population => 1082)
Comune.create(:description => "Antey Saint Andre'", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Gressoney La Trinite'", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Pre' Saint Didier", :provincia_id => 77, :regione_id => 16, stato_id: 1, continente_id: 1 )
