Municipality.create(description: "Dro", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Ala", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Albiano", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Aldeno", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Amblar", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Andalo", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Arco", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Avio", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Bedollo", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Bersone", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Besenello", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Bezzecca", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Bleggio Inferiore", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Bleggio Superiore", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Bocenago", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Bolbeno", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Bondo", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Bondone", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Borgo Valsugana", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Bosentino", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Breguzzo", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Brentonico", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Bresimo", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Brez", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Brione", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 546)
Municipality.create(description: "Caderzone", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Calavino", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Calceranica Al Lago", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Caldes", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Caldonazzo", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Calliano", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Campitello Di Fassa", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Campodenno", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Canal San Bovo", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Canazei", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Capriana", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Carano", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Carisolo", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Carzano", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Castel Condino", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Castelfondo", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Castello Molina Di Fiemme", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 )
Municipality.create(description: "Castello Tesino", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Castelnuovo", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Cavalese", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Cavareno", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Cavedago", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Cavedine", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Cavizzana", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Cembra", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Cimego", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Cimone", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Cinte Tesino", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Cis", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Civezzano", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Cles", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Cloz", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Commezzadura", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Concei", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Condino", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Coredo", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Croviana", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Cunevo", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Daiano", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Dambel", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Daone", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Denno", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Dimaro", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Don", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Dorsino", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Drena", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Faedo", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Fai Della Paganella", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Faver", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Fiera Di Primiero", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Fierozzo", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Flavon", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Folgaria", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Fondo", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Fornace", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Frassilongo", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Garniga", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 )
Municipality.create(description: "Giovo", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Giustino", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Grauno", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Grigno", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Grumes", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Imer", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Isera", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Ivano Fracena", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Lardaro", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Lasino", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Lavarone", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Lavis", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Levico Terme", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Lisignago", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Livo", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 208)
Municipality.create(description: "Lomaso", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Lona Lases", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Malosco", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Massimeno", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Mazzin", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Mezzana", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Mezzano", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Mezzocorona", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Mezzolombardo", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Moena", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Molina Di Ledro", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Molveno", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Monclassico", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Montagne", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Mori", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Nago Torbole", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 )
Municipality.create(description: "Nanno", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Nave San Rocco", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Nogaredo", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Nomi", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Novaledo", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Ospedaletto", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Ossana", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Padergnone", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Peio", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Pellizzano", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Pelugo", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Pergine Valsugana", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Pieve Di Bono", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Pieve Di Ledro", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Pieve Tesino", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Pinzolo", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Pomarolo", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Pozza Di Fassa", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Praso", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Predazzo", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Preore", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Prezzo", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Rabbi", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Ragoli", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Riva Del Garda", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Romallo", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Romeno", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Roncegno", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Ronchi Valsugana", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Roncone", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Ronzo-Chienis", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Ronzone", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Rumo", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Sagron Mis", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Samone", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 1473)
Municipality.create(description: "San Lorenzo In Banale", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Sanzeno", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Sarnonico", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Scurelle", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Segonzano", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Sfruz", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Siror", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Smarano", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Soraga", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Sover", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Spera", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Spiazzo", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Spormaggiore", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Sporminore", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Stenico", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Storo", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Strembo", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Strigno", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Taio", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Tassullo", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Telve", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Telve Di Sopra", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Tenna", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Tenno", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Terlago", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Terragnolo", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Terres", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Terzolas", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Tesero", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Tiarno Di Sopra", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Tiarno Di Sotto", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Tione Di Trento", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Ton", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Tonadico", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Torcegno", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Trambileno", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Transacqua", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Trento", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Tres", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Tuenno", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Valda", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Valfloriana", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Vallarsa", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Varena", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Vattaro", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Vermiglio", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Vezzano", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Vignola Falesina", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Vigo Di Fassa", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Vigo Rendena", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Vigolo Vattaro", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Villa Agnedo", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Villa Lagarina", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Villa Rendena", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Volano", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Zambana", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Ziano Di Fiemme", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Zuclo", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Baselga Di Pine'", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Cagno'", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Centa San Nicolo'", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Dare'", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Fiave'", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Male'", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Palu' Del Fersina", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Panchia'", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Revo'", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Rovere' Della Luna", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Ruffre'", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "San Michele All'Adige", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Sant'Orsola", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 )
Municipality.create(description: "Vervo'", province_id: 101, region_id:  5, country_id: 1, continent_id: 1 , population: 0)
