Municipality.create(description: "Cantagallo", province_id: 103, region_id:  12, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Carmignano", province_id: 103, region_id:  12, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Montemurlo", province_id: 103, region_id:  12, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Poggio A Caiano", province_id: 103, region_id:  12, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Prato", province_id: 103, region_id:  12, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Vaiano", province_id: 103, region_id:  12, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Vernio", province_id: 103, region_id:  12, country_id: 1, continent_id: 1 , population: 0)
