Comune.create(description: "Cantagallo", provincia_id: 103, regione_id: 12, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Carmignano", provincia_id: 103, regione_id: 12, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Montemurlo", provincia_id: 103, regione_id: 12, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Poggio A Caiano", provincia_id: 103, regione_id: 12, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Prato", provincia_id: 103, regione_id: 12, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Vaiano", provincia_id: 103, regione_id: 12, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Vernio", provincia_id: 103, regione_id: 12, country_id: 1, continent_id: 1 , population: 0)
