Comune.create(description: "Antrona Schieranco", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 544)
Comune.create(description: "Arola", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 279)
Comune.create(description: "Aurano", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 118)
Comune.create(description: "Baceno", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 961)
Comune.create(description: "Bannio Anzino", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 582)
Comune.create(description: "Baveno", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 4554)
Comune.create(description: "Bee", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 623)
Comune.create(description: "Belgirate", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 521)
Comune.create(description: "Beura-Cardezza", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 1372)
Comune.create(description: "Bognanco", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 319)
Comune.create(description: "Brovello Carpugnino", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 )
Comune.create(description: "Calasca Castiglione", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 )
Comune.create(description: "Cambiasca", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 1538)
Comune.create(description: "Cannero Riviera", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 1050)
Comune.create(description: "Cannobio", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 4977)
Comune.create(description: "Caprezzo", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 177)
Comune.create(description: "Casale Corte Cerro", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 3292)
Comune.create(description: "Cavaglio Spoccia", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 )
Comune.create(description: "Ceppo Morelli", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 396)
Comune.create(description: "Cesara", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 606)
Comune.create(description: "Cossogno", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 537)
Comune.create(description: "Craveggia", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 723)
Comune.create(description: "Crevoladossola", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 4695)
Comune.create(description: "Crodo", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 1483)
Comune.create(description: "Cursolo Orasso", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 )
Comune.create(description: "Domodossola", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 18466)
Comune.create(description: "Druogno", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 961)
Comune.create(description: "Falmenta", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 231)
Comune.create(description: "Formazza", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 448)
Comune.create(description: "Germagno", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 204)
Comune.create(description: "Ghiffa", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 2336)
Comune.create(description: "Gignese", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 789)
Comune.create(description: "Gravellona Toce", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 7539)
Comune.create(description: "Gurro", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 310)
Comune.create(description: "Intragna", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 125)
Comune.create(description: "Loreglia", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 283)
Comune.create(description: "Macugnaga", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 651)
Comune.create(description: "Madonna Del Sasso", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 446)
Comune.create(description: "Malesco", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 1473)
Comune.create(description: "Masera", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 1429)
Comune.create(description: "Massiola", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 173)
Comune.create(description: "Mergozzo", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 2038)
Comune.create(description: "Miazzina", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 391)
Comune.create(description: "Montecrestese", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 1209)
Comune.create(description: "Montescheno", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 441)
Comune.create(description: "Nonio", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 883)
Comune.create(description: "Oggebbio", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 836)
Comune.create(description: "Omegna", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 15373)
Comune.create(description: "Ornavasso", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 3231)
Comune.create(description: "Pallanzeno", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 1210)
Comune.create(description: "Piedimulera", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 1673)
Comune.create(description: "Pieve Vergonte", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 2692)
Comune.create(description: "Premeno", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 769)
Comune.create(description: "Premia", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 603)
Comune.create(description: "Premosello Chiovenda", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 )
Comune.create(description: "Quarna Sopra", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 318)
Comune.create(description: "Quarna Sotto", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 427)
Comune.create(description: "Re", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 830)
Comune.create(description: "San Bernardino Verbano", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 1152)
Comune.create(description: "Santa Maria Maggiore", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 1207)
Comune.create(description: "Seppiana", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 182)
Comune.create(description: "Stresa", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 4836)
Comune.create(description: "Toceno", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 758)
Comune.create(description: "Trarego Viggiona", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 379)
Comune.create(description: "Trasquera", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 279)
Comune.create(description: "Trontano", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 1710)
Comune.create(description: "Valstrona", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 1270)
Comune.create(description: "Vanzone Con San Carlo", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 512)
Comune.create(description: "Varzo", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 2218)
Comune.create(description: "Verbania", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 30128)
Comune.create(description: "Viganella", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 204)
Comune.create(description: "Vignone", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 1090)
Comune.create(description: "Villadossola", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 6908)
Comune.create(description: "Villette", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 244)
Comune.create(description: "Vogogna", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 1702)
Comune.create(description: "Anzola D'Ossola", province_id: 104, region_id:  13, country_id: 1, continent_id: 1 , population: 443)
