#encoding: utf-8
Comune.create(description: "Arbus", provincia_id: 106, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Barumini", provincia_id: 106, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Collinas", provincia_id: 106, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Furtei", provincia_id: 106, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Genuri", provincia_id: 106, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Gesturi", provincia_id: 106, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Gonnosfanadiga", provincia_id: 106, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Guspini", provincia_id: 106, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Las Plassas", provincia_id: 106, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Lunamatrona", provincia_id: 106, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Pabillonis", provincia_id: 106, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Pauli Arbarei", provincia_id: 106, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Samassi", provincia_id: 106, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "San Gavino Monreale", provincia_id: 106, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Sanluri", provincia_id: 106, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Sardara", provincia_id: 106, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Segariu", provincia_id: 106, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Serramanna", provincia_id: 106, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Serrenti", provincia_id: 106, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Setzu", provincia_id: 106, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Siddi", provincia_id: 106, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Tuili", provincia_id: 106, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Turri", provincia_id: 106, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Ussaramanna", provincia_id: 106, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Villacidro", provincia_id: 106, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Villamar", provincia_id: 106, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Villanovaforru", provincia_id: 106, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Villanovafranca", provincia_id: 106, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
