Municipality.create(description: "Arbus", province_id: 106, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Barumini", province_id: 106, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Collinas", province_id: 106, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Furtei", province_id: 106, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Genuri", province_id: 106, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Gesturi", province_id: 106, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Gonnosfanadiga", province_id: 106, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Guspini", province_id: 106, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Las Plassas", province_id: 106, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Lunamatrona", province_id: 106, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Pabillonis", province_id: 106, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Pauli Arbarei", province_id: 106, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Samassi", province_id: 106, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "San Gavino Monreale", province_id: 106, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Sanluri", province_id: 106, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Sardara", province_id: 106, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Segariu", province_id: 106, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Serramanna", province_id: 106, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Serrenti", province_id: 106, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Setzu", province_id: 106, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Siddi", province_id: 106, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Tuili", province_id: 106, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Turri", province_id: 106, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Ussaramanna", province_id: 106, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Villacidro", province_id: 106, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Villamar", province_id: 106, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Villanovaforru", province_id: 106, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Villanovafranca", province_id: 106, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
