Municipality.create(description: "Arzana", province_id: 107, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Bari Sardo", province_id: 107, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Baunei", province_id: 107, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Cardedu", province_id: 107, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Elini", province_id: 107, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Gairo", province_id: 107, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Girasole", province_id: 107, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Ilbono", province_id: 107, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Jerzu", province_id: 107, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Lanusei", province_id: 107, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Loceri", province_id: 107, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Lotzorai", province_id: 107, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Osini", province_id: 107, region_id:  10, country_id: 1, continent_id: 1 , population: 1199)
Municipality.create(description: "Perdasdefogu", province_id: 107, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Seui", province_id: 107, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Talana", province_id: 107, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Tertenia", province_id: 107, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Triei", province_id: 107, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Ulassai", province_id: 107, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Urzulei", province_id: 107, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Ussassai", province_id: 107, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Villagrande Strisaili", province_id: 107, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Tortoli'", province_id: 107, region_id:  10, country_id: 1, continent_id: 1 , population: 3021)
