#encoding: utf-8
Comune.create(description: "Aggius", provincia_id: 108, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Aglientu", provincia_id: 108, regione_id: 10, country_id: 1, continente_id: 1 , population: 847)
Comune.create(description: "Arzachena", provincia_id: 108, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Badesi", provincia_id: 108, regione_id: 10, country_id: 1, continente_id: 1 , population: 1022)
Comune.create(description: "Berchidda", provincia_id: 108, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Bortigiadas", provincia_id: 108, regione_id: 10, country_id: 1, continente_id: 1 , population: 1719)
Comune.create(description: "Budoni", provincia_id: 108, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Calangianus", provincia_id: 108, regione_id: 10, country_id: 1, continente_id: 1 , population: 5410)
Comune.create(description: "Golfo Aranci", provincia_id: 108, regione_id: 10, country_id: 1, continente_id: 1 , population: 2181)
Comune.create(description: "La Maddalena", provincia_id: 108, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Loiri Porto San Paolo", provincia_id: 108, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Luogosanto", provincia_id: 108, regione_id: 10, country_id: 1, continente_id: 1 , population: 1029)
Comune.create(description: "Luras", provincia_id: 108, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Monti", provincia_id: 108, regione_id: 10, country_id: 1, continente_id: 1 , population: 630)
Comune.create(description: "Olbia", provincia_id: 108, regione_id: 10, country_id: 1, continente_id: 1 , population: 120729)
Comune.create(description: "Oschiri", provincia_id: 108, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Padru", provincia_id: 108, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Palau", provincia_id: 108, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "San Teodoro", provincia_id: 108, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Santa Teresa Gallura", provincia_id: 108, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Telti", provincia_id: 108, regione_id: 10, country_id: 1, continente_id: 1 , population: 619)
Comune.create(description: "Tempio Pausania", provincia_id: 108, regione_id: 10, country_id: 1, continente_id: 1 , population: 501)
Comune.create(description: "Ala' Dei Sardi", provincia_id: 108, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Budduso'", provincia_id: 108, regione_id: 10, country_id: 1, continente_id: 1 , population: 3713)
Comune.create(description: "Sant'Antonio Di Gallura", provincia_id: 108, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Trinita' D'Agultu E Vignola", provincia_id: 108, regione_id: 10, country_id: 1, continente_id: 1 , population: 2588)
