Municipality.create(description: "Aggius", province_id: 108, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Aglientu", province_id: 108, region_id:  10, country_id: 1, continent_id: 1 , population: 847)
Municipality.create(description: "Arzachena", province_id: 108, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Badesi", province_id: 108, region_id:  10, country_id: 1, continent_id: 1 , population: 1022)
Municipality.create(description: "Berchidda", province_id: 108, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Bortigiadas", province_id: 108, region_id:  10, country_id: 1, continent_id: 1 , population: 1719)
Municipality.create(description: "Budoni", province_id: 108, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Calangianus", province_id: 108, region_id:  10, country_id: 1, continent_id: 1 , population: 5410)
Municipality.create(description: "Golfo Aranci", province_id: 108, region_id:  10, country_id: 1, continent_id: 1 , population: 2181)
Municipality.create(description: "La Maddalena", province_id: 108, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Loiri Porto San Paolo", province_id: 108, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Luogosanto", province_id: 108, region_id:  10, country_id: 1, continent_id: 1 , population: 1029)
Municipality.create(description: "Luras", province_id: 108, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Monti", province_id: 108, region_id:  10, country_id: 1, continent_id: 1 , population: 630)
Municipality.create(description: "Olbia", province_id: 108, region_id:  10, country_id: 1, continent_id: 1 , population: 120729)
Municipality.create(description: "Oschiri", province_id: 108, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Padru", province_id: 108, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Palau", province_id: 108, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "San Teodoro", province_id: 108, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Santa Teresa Gallura", province_id: 108, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Telti", province_id: 108, region_id:  10, country_id: 1, continent_id: 1 , population: 619)
Municipality.create(description: "Tempio Pausania", province_id: 108, region_id:  10, country_id: 1, continent_id: 1 , population: 501)
Municipality.create(description: "Ala' Dei Sardi", province_id: 108, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Budduso'", province_id: 108, region_id:  10, country_id: 1, continent_id: 1 , population: 3713)
Municipality.create(description: "Sant'Antonio Di Gallura", province_id: 108, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Trinita' D'Agultu E Vignola", province_id: 108, region_id:  10, country_id: 1, continent_id: 1 , population: 2588)
