#encoding: utf-8
 EventType.create( :description => "incontro"){ |c| c.id = 1}.save
 et1 = EventType.find(1)
 et1.translations.where(locale: "it").first_or_create.update_attributes(description: "incontro")
 et1.translations.where(locale: "eu").first_or_create.update_attributes(description: "meeting")
 et1.translations.where(locale: "en").first_or_create.update_attributes(description: "meeting")
 et1.translations.where(locale: "us").first_or_create.update_attributes(description: "meeting")
 et1.translations.where(locale: "pt").first_or_create.update_attributes(description: "encontro")
 et1.translations.where(locale: "de").first_or_create.update_attributes(description: "Treffen")
 et1.translations.where(locale: "es").first_or_create.update_attributes(description: "cita")
 et1.translations.where(locale: "fr").first_or_create.update_attributes(description: "rendez-vous")
 EventType.create( :description => "votazione"){ |c| c.id = 2}.save
 et2 = EventType.find(2)
 et2.translations.where(locale: "it").first_or_create.update_attributes(description: "votazione")
 et2.translations.where(locale: "eu").first_or_create.update_attributes(description: "vote")
 et2.translations.where(locale: "en").first_or_create.update_attributes(description: "vote")
 et2.translations.where(locale: "us").first_or_create.update_attributes(description: "vote")
 et2.translations.where(locale: "pt").first_or_create.update_attributes(description: "voto")
 et2.translations.where(locale: "de").first_or_create.update_attributes(description: "Abstimmungen")
 et2.translations.where(locale: "es").first_or_create.update_attributes(description: "voto")
 et2.translations.where(locale: "fr").first_or_create.update_attributes(description: "vote")
 EventType.create( :description => "riunione"){ |c| c.id = 3}.save
 et3 = EventType.find(3)
 et3.translations.where(locale: "it").first_or_create.update_attributes(description: "riunione")
 et3.translations.where(locale: "eu").first_or_create.update_attributes(description: "meeting")
 et3.translations.where(locale: "en").first_or_create.update_attributes(description: "meeting")
 et3.translations.where(locale: "us").first_or_create.update_attributes(description: "meeting")
 et3.translations.where(locale: "pt").first_or_create.update_attributes(description: "reunião")
 et3.translations.where(locale: "de").first_or_create.update_attributes(description: "Versammlungen")
 et3.translations.where(locale: "es").first_or_create.update_attributes(description: "reunión")
 et3.translations.where(locale: "fr").first_or_create.update_attributes(description: "réunion")
 EventType.create( :description => "elezioni"){ |c| c.id = 4}.save
 et4 = EventType.find(4)
 et4.translations.where(locale: "it").first_or_create.update_attributes(description: "elezioni")
 et4.translations.where(locale: "eu").first_or_create.update_attributes(description: "election")
 et4.translations.where(locale: "en").first_or_create.update_attributes(description: "election")
 et4.translations.where(locale: "us").first_or_create.update_attributes(description: "election")
 et4.translations.where(locale: "pt").first_or_create.update_attributes(description: "eleição")
 et4.translations.where(locale: "de").first_or_create.update_attributes(description: "Wahlen")
 et4.translations.where(locale: "es").first_or_create.update_attributes(description: "elección")
 et4.translations.where(locale: "fr").first_or_create.update_attributes(description: "élections")
 ga1 = GroupAction.create(name: "STREAM_POST", description: "Pubblicare nella Home Page del gruppo", seq: 1)
 ga1.translations.where(locale: "it").first_or_create.update_attributes(description: "Pubblicare nella Home Page del gruppo")
 ga1.translations.where(locale: "eu").first_or_create.update_attributes(description: "Post on the group home page")
 ga1.translations.where(locale: "en").first_or_create.update_attributes(description: "Post on the group home page")
 ga1.translations.where(locale: "us").first_or_create.update_attributes(description: "Post on the group home page")
 ga1.translations.where(locale: "pt").first_or_create.update_attributes(description: "Publicar na home page do grupo")
 ga1.translations.where(locale: "de").first_or_create.update_attributes(description: "Auf der Internetseite der Gruppe veröffentlichen")
 ga1.translations.where(locale: "es").first_or_create.update_attributes(description: "Publicar en la página principal del grupo")
 ga1.translations.where(locale: "fr").first_or_create.update_attributes(description: "Publier dans la page d'accueil du groupe")
 ga2 = GroupAction.create(name: "CREATE_EVENT", description: "Creare eventi e votazioni", seq: 2)
 ga2.translations.where(locale: "it").first_or_create.update_attributes(description: "Creare eventi e votazioni")
 ga2.translations.where(locale: "eu").first_or_create.update_attributes(description: "Create events and voting")
 ga2.translations.where(locale: "en").first_or_create.update_attributes(description: "Create events and voting")
 ga2.translations.where(locale: "us").first_or_create.update_attributes(description: "Create events and voting")
 ga2.translations.where(locale: "pt").first_or_create.update_attributes(description: "Criar eventos e voto")
 ga2.translations.where(locale: "de").first_or_create.update_attributes(description: "Veranstaltungen und Abstimmungen erstellen")
 ga2.translations.where(locale: "es").first_or_create.update_attributes(description: "Crear eventos y votaciones")
 ga2.translations.where(locale: "fr").first_or_create.update_attributes(description: "Créer des événements et des votes")
 ga3 = GroupAction.create(name: "PROPOSAL", description: "Sostenere proposte a nome del gruppo", seq: 3)
 ga3.translations.where(locale: "it").first_or_create.update_attributes(description: "Sostenere proposte a nome del gruppo")
 ga3.translations.where(locale: "eu").first_or_create.update_attributes(description: "Support proposals on behalf of the group")
 ga3.translations.where(locale: "en").first_or_create.update_attributes(description: "Support proposals on behalf of the group")
 ga3.translations.where(locale: "us").first_or_create.update_attributes(description: "Support proposals on behalf of the group")
 ga3.translations.where(locale: "pt").first_or_create.update_attributes(description: "Apoiar propostas em nome do grupo")
 ga3.translations.where(locale: "de").first_or_create.update_attributes(description: "Unterstützung der Vorschläge im Namen der Gruppe")
 ga3.translations.where(locale: "es").first_or_create.update_attributes(description: "Apoyar las propuestas en nombre del grupo")
 ga3.translations.where(locale: "fr").first_or_create.update_attributes(description: "Soutenir les propositions au nom du groupe")
 ga4 = GroupAction.create(name: "REQUEST_ACCEPT", description: "Aggiungere partecipanti nel gruppo", seq: 4)
 ga4.translations.where(locale: "it").first_or_create.update_attributes(description: "Aggiungere partecipanti nel gruppo")
 ga4.translations.where(locale: "eu").first_or_create.update_attributes(description: "Add new members to the group")
 ga4.translations.where(locale: "en").first_or_create.update_attributes(description: "Add new members to the group")
 ga4.translations.where(locale: "us").first_or_create.update_attributes(description: "Add new members to the group")
 ga4.translations.where(locale: "pt").first_or_create.update_attributes(description: "Adicionar participantes ao grupo")
 ga4.translations.where(locale: "de").first_or_create.update_attributes(description: "Neue Mitglieder in die Gruppe aufnehmen")
 ga4.translations.where(locale: "es").first_or_create.update_attributes(description: "Adición de participantes en el grupo")
 ga4.translations.where(locale: "fr").first_or_create.update_attributes(description: "Ajouter des nouveaux membres au groupe")
 ga5 = GroupAction.create(name: "SEND_CANDIDATES", description: "Candidare utenti alle elezioni", seq: 5)
 ga5.translations.where(locale: "it").first_or_create.update_attributes(description: "Candidare utenti alle elezioni")
 ga5.translations.where(locale: "eu").first_or_create.update_attributes(description: "Nominate members for election")
 ga5.translations.where(locale: "en").first_or_create.update_attributes(description: "Nominate members for election")
 ga5.translations.where(locale: "us").first_or_create.update_attributes(description: "Nominate members for election")
 ga5.translations.where(locale: "pt").first_or_create.update_attributes(description: "Nomear os membros para a eleição")
 ga5.translations.where(locale: "de").first_or_create.update_attributes(description: "Mitglieder für die Wahlen nominieren")
 ga5.translations.where(locale: "es").first_or_create.update_attributes(description: "Designar los miembros para su elección")
 ga5.translations.where(locale: "fr").first_or_create.update_attributes(description: "Nommer des membres pour l'élection")
 ga6 = GroupAction.create(name: "PROPOSAL_VIEW", description: "Visualizzare le proposte private", seq: 6)
 ga6.translations.where(locale: "it").first_or_create.update_attributes(description: "Visualizzare le proposte private")
 ga6.translations.where(locale: "eu").first_or_create.update_attributes(description: "View private proposals")
 ga6.translations.where(locale: "en").first_or_create.update_attributes(description: "View private proposals")
 ga6.translations.where(locale: "us").first_or_create.update_attributes(description: "View private proposals")
 ga6.translations.where(locale: "pt").first_or_create.update_attributes(description: "Ver propostas privadas")
 ga6.translations.where(locale: "de").first_or_create.update_attributes(description: "Private Vorschläge anzeigen")
 ga6.translations.where(locale: "es").first_or_create.update_attributes(description: "Ver las propuestas privadas")
 ga6.translations.where(locale: "fr").first_or_create.update_attributes(description: "Voir les propositions privées")
 ga7 = GroupAction.create(name: "PROPOSAL_PARTECIPATION", description: "Contribuire alle proposte", seq: 8)
 ga7.translations.where(locale: "it").first_or_create.update_attributes(description: "Contribuire alle proposte")
 ga7.translations.where(locale: "eu").first_or_create.update_attributes(description: "Contribute to proposals")
 ga7.translations.where(locale: "en").first_or_create.update_attributes(description: "Contribute to proposals")
 ga7.translations.where(locale: "us").first_or_create.update_attributes(description: "Contribute to proposals")
 ga7.translations.where(locale: "pt").first_or_create.update_attributes(description: "Contribuir as propostas")
 ga7.translations.where(locale: "de").first_or_create.update_attributes(description: "Zu den Vorschlägen beitragen")
 ga7.translations.where(locale: "es").first_or_create.update_attributes(description: "Contribuir a las propuestas")
 ga7.translations.where(locale: "fr").first_or_create.update_attributes(description: "Contribuer aux propositions")
 ga8 = GroupAction.create(name: "PROPOSAL_INSERT", description: "Inserire nuove proposte nel gruppo", seq: 7)
 ga8.translations.where(locale: "it").first_or_create.update_attributes(description: "Inserire nuove proposte nel gruppo")
 ga8.translations.where(locale: "eu").first_or_create.update_attributes(description: "Insert new proposals into the group")
 ga8.translations.where(locale: "en").first_or_create.update_attributes(description: "Insert new proposals into the group")
 ga8.translations.where(locale: "us").first_or_create.update_attributes(description: "Insert new proposals into the group")
 ga8.translations.where(locale: "pt").first_or_create.update_attributes(description: "Inserir novas propostas no grupo")
 ga8.translations.where(locale: "de").first_or_create.update_attributes(description: "Neue Vorschläge in die Gruppe eintragen")
 ga8.translations.where(locale: "es").first_or_create.update_attributes(description: "Inserir nuevas propuestas en el grupo")
 ga8.translations.where(locale: "fr").first_or_create.update_attributes(description: "Insérer des nouvelles propositions dans le groupe")
 ga9 = GroupAction.create(name: "DOCUMENT_VIEW", description: "Visualizzare i documenti", seq: 10)
 ga9.translations.where(locale: "it").first_or_create.update_attributes(description: "Visualizzare i documenti")
 ga9.translations.where(locale: "eu").first_or_create.update_attributes(description: "View documents")
 ga9.translations.where(locale: "en").first_or_create.update_attributes(description: "View documents")
 ga9.translations.where(locale: "us").first_or_create.update_attributes(description: "View documents")
 ga9.translations.where(locale: "pt").first_or_create.update_attributes(description: "visualizar os documentos")
 ga9.translations.where(locale: "de").first_or_create.update_attributes(description: "Dokumente anzeigen")
 ga9.translations.where(locale: "es").first_or_create.update_attributes(description: "Ver documentos")
 ga9.translations.where(locale: "fr").first_or_create.update_attributes(description: "voir les documents")
 ga10 = GroupAction.create(name: "DOCUMENT_MANAGE", description: "Gestire i documenti", seq: 11)
 ga10.translations.where(locale: "it").first_or_create.update_attributes(description: "Gestire i documenti")
 ga10.translations.where(locale: "eu").first_or_create.update_attributes(description: "Manage documents")
 ga10.translations.where(locale: "en").first_or_create.update_attributes(description: "Manage documents")
 ga10.translations.where(locale: "us").first_or_create.update_attributes(description: "Manage documents")
 ga10.translations.where(locale: "pt").first_or_create.update_attributes(description: "gerir os documentos")
 ga10.translations.where(locale: "de").first_or_create.update_attributes(description: "Dokumente verwalten")
 ga10.translations.where(locale: "es").first_or_create.update_attributes(description: "Gestionar los documentos")
 ga10.translations.where(locale: "fr").first_or_create.update_attributes(description: "Gérer les documents")
 ga11 = GroupAction.create(name: "PROPOSAL_VOTE", description: "Votare le proposte", seq: 9)
 ga11.translations.where(locale: "it").first_or_create.update_attributes(description: "Votare le proposte")
 ga11.translations.where(locale: "eu").first_or_create.update_attributes(description: "Vote proposals")
 ga11.translations.where(locale: "en").first_or_create.update_attributes(description: "Vote proposals")
 ga11.translations.where(locale: "us").first_or_create.update_attributes(description: "Vote proposals")
 ga11.translations.where(locale: "pt").first_or_create.update_attributes(description: "Votação das propostas")
 ga11.translations.where(locale: "de").first_or_create.update_attributes(description: "Abstimmung über die Vorschläge")
 ga11.translations.where(locale: "es").first_or_create.update_attributes(description: "Votación de las propuestas")
 ga11.translations.where(locale: "fr").first_or_create.update_attributes(description: "Vote sur les propositions")
GroupPartecipationRequestStatus.create( :description => "Inoltrata" ){ |c| c.id = 1}.save
GroupPartecipationRequestStatus.create( :description => "In votazione" ){ |c| c.id = 2}.save
GroupPartecipationRequestStatus.create( :description => "Accettata" ){ |c| c.id = 3}.save
GroupPartecipationRequestStatus.create( :description => "Negata" ){ |c| c.id = 4}.save
nc36 = NotificationCategory.create(description: "Proposte che redigo", seq: 1, short: "MYPROP")
 nc36.translations.where(locale: "it").first_or_create.update_attributes(description: "Proposte che redigo")
 nc36.translations.where(locale: "eu").first_or_create.update_attributes(description: "Proposals I write")
 nc36.translations.where(locale: "us").first_or_create.update_attributes(description: "Proposals I write")
 nc36.translations.where(locale: "en").first_or_create.update_attributes(description: "Proposals I write")
 NotificationType.create( :description => "Nuovi contributi alle mie proposte", :notification_category_id => nc36.id ){ |c| c.id = 5}.save
 nt5 = NotificationType.find(5)
 nt5.translations.where(locale: "it").first_or_create.update_attributes({description: "Nuovi contributi alle mie proposte", email_subject: "Nuovo contributo ad una mia proposta"})
 nt5.translations.where(locale: "eu").first_or_create.update_attributes({description: "There are new comments to my proposals", email_subject: "There are new comments to a proposal"})
 nt5.translations.where(locale: "us").first_or_create.update_attributes({description: "There are new comments to my proposals", email_subject: "There are new comments to a proposal"})
 nt5.translations.where(locale: "en").first_or_create.update_attributes({description: "There are new comments to my proposals", email_subject: "There are new comments to a proposal"})
 nt5.translations.where(locale: "de").first_or_create.update_attributes({description: "Es gibt neue Beiträge zu meinem Vorschlag.", email_subject: "Es gibt neue Beiträge zu einem Vorschlag."})
 nt5.translations.where(locale: "fr").first_or_create.update_attributes({description: "Nouveaux commentaires à mes propositions", email_subject: "Nouveaux commentaires à une proposition"})
 nt5.translations.where(locale: "es").first_or_create.update_attributes({description: "Hay nuevos comentarios a mis propuestas.", email_subject: "Nuevos comentarios a mi propuesta."})
 NotificationType.create( :description => "Cambio di stato delle mie proposte", :notification_category_id => nc36.id ){ |c| c.id = 6}.save
 nt6 = NotificationType.find(6)
 nt6.translations.where(locale: "it").first_or_create.update_attributes({description: "Cambio di stato delle mie proposte", email_subject: "Una tua proposta ha cambiato lo stato"})
 nt6.translations.where(locale: "eu").first_or_create.update_attributes({description: "The status of my proposals has changed", email_subject: "The status of one of your proposals has changed"})
 nt6.translations.where(locale: "us").first_or_create.update_attributes({description: "The status of my proposals has changed", email_subject: "The status of one of your proposals has changed"})
 nt6.translations.where(locale: "en").first_or_create.update_attributes({description: "The status of my proposals has changed", email_subject: "The status of one of your proposals has changed"})
 nt6.translations.where(locale: "de").first_or_create.update_attributes({description: "Der Status meines Vorschlags hat sich geändert.", email_subject: "Der Status eines Deiner Vorschläge hat sich geändert."})
 nt6.translations.where(locale: "fr").first_or_create.update_attributes({description: "Changement de statut de mes propositions", email_subject: "L'une de tes propositions a changé de statut"})
 nt6.translations.where(locale: "es").first_or_create.update_attributes({description: "El estado de mi propuesta ha cambiado.", email_subject: "El estado de una de sus propuestas ha cambiado."})
 NotificationType.create( :description => "Nuova valutazione ad una mia proposta", :notification_category_id => nc36.id ){ |c| c.id = 20}.save
 nt20 = NotificationType.find(20)
 nt20.translations.where(locale: "it").first_or_create.update_attributes({description: "Nuova valutazione ad una mia proposta", email_subject: "Nuova valutazione ad una tua proposta"})
 nt20.translations.where(locale: "eu").first_or_create.update_attributes({description: "There is a new evaluation for a proposal of mine", email_subject: "There is a new evaluation for a proposal of yours"})
 nt20.translations.where(locale: "us").first_or_create.update_attributes({description: "There is a new evaluation for a proposal of mine", email_subject: "There is a new evaluation for a proposal of yours"})
 nt20.translations.where(locale: "en").first_or_create.update_attributes({description: "There is a new evaluation for a proposal of mine", email_subject: "There is a new evaluation for a proposal of yours"})
 nt20.translations.where(locale: "de").first_or_create.update_attributes({description: "Es gibt eine neue Bewertung für einen meiner Vorschläge.", email_subject: "Es gibt einen neue Bewertung für einen Deiner Vorschläge."})
 nt20.translations.where(locale: "fr").first_or_create.update_attributes({description: "Nouvelle évaluation à l'une de mes propositions", email_subject: "Novelle évaluation à l'une de tes propositions"})
 nt20.translations.where(locale: "es").first_or_create.update_attributes({description: "Una nueva evaluación a mi propuesta. ", email_subject: "Nueva evaluación a tu propuesta."})
 NotificationType.create( :description => "Utente disponibile a redigere la sintesi di una proposta", :notification_category_id => nc36.id ){ |c| c.id = 22}.save
 nt22 = NotificationType.find(22)
 nt22.translations.where(locale: "it").first_or_create.update_attributes({description: "Utente disponibile a redigere la sintesi di una proposta", email_subject: "Un utente si è reso disponibile a redigere la sintesi di una proposta"})
 nt22.translations.where(locale: "eu").first_or_create.update_attributes({description: "User available to do a summary for a proposal", email_subject: "There is a user available to do a summary of a proposal"})
 nt22.translations.where(locale: "us").first_or_create.update_attributes({description: "User available to do a summary for a proposal", email_subject: "There is a user available to do a summary of a proposal"})
 nt22.translations.where(locale: "en").first_or_create.update_attributes({description: "User available to do a summary for a proposal", email_subject: "There is a user available to do a summary of a proposal"})
 nt22.translations.where(locale: "de").first_or_create.update_attributes({description: "Benutzer verfügbar für eine Zusammenfassung eines Vorschlags.", email_subject: "Benutzer verfügbar für eine Zusammenfassung eines Vorschlags."})
 nt22.translations.where(locale: "fr").first_or_create.update_attributes({description: "Utilisateur disponible à rédiger la synthèse d'une proposition", email_subject: "Un utilisateur est disponible à rédiger la synthèse d'une proposition"})
 nt22.translations.where(locale: "es").first_or_create.update_attributes({description: "Usuario disponible para un resumen de una propuesta.", email_subject: "Un usuario ha puesto a disposición de redactar el resumen de la propuesta"})
 NotificationType.create( :description => "Accettazione come redattore di una proposta", :notification_category_id => nc36.id ){ |c| c.id = 23}.save
 nt23 = NotificationType.find(23)
 nt23.translations.where(locale: "it").first_or_create.update_attributes({description: "Accettazione come redattore di una proposta", email_subject: "Sei stato scelto come redattore di una proposta"})
 nt23.translations.where(locale: "eu").first_or_create.update_attributes({description: "Acceptance as editor of a proposal", email_subject: "You have been chosen as editor of a proposal"})
 nt23.translations.where(locale: "us").first_or_create.update_attributes({description: "Acceptance as editor of a proposal", email_subject: "You have been chosen as editor of a proposal"})
 nt23.translations.where(locale: "en").first_or_create.update_attributes({description: "Acceptance as editor of a proposal", email_subject: "You have been chosen as editor of a proposal"})
 nt23.translations.where(locale: "es").first_or_create.update_attributes({description: "Aceptación como editor de una propuesta", email_subject: "Usted ha sido seleccionado como editor de una propuesta"})
 nt23.translations.where(locale: "de").first_or_create.update_attributes({description: "Akzeptanz als Redakteur eines Vorschlags", email_subject: "Du wurdest als Redakteur eines Vorschlags ausgesucht."})
 nt23.translations.where(locale: "fr").first_or_create.update_attributes({description: "Acceptation en tant que rédacteur d'une proposition", email_subject: "Tu as été choisi en tant que rédacteur d'une proposition"})
nc37 = NotificationCategory.create(description: "Proposte a cui partecipo", seq: 2, short: "PROP")
 nc37.translations.where(locale: "it").first_or_create.update_attributes(description: "Proposte a cui partecipo")
 nc37.translations.where(locale: "eu").first_or_create.update_attributes(description: "Proposals I take part")
 nc37.translations.where(locale: "us").first_or_create.update_attributes(description: "Proposals I take part")
 nc37.translations.where(locale: "en").first_or_create.update_attributes(description: "Proposals I take part")
 NotificationType.create( :description => "Nuovi contributi e suggerimenti alle proposte a cui partecipo", :notification_category_id => nc37.id ){ |c| c.id = 1}.save
 nt1 = NotificationType.find(1)
 nt1.translations.where(locale: "it").first_or_create.update_attributes({description: "Nuovi contributi e suggerimenti alle proposte a cui partecipo", email_subject: "Nuovo contributo ad una proposta"})
 nt1.translations.where(locale: "eu").first_or_create.update_attributes({description: "New contributions and ideas to proposals I am involved in", email_subject: "New comment to proposal"})
 nt1.translations.where(locale: "us").first_or_create.update_attributes({description: "New contributions and ideas to proposals I am involved in", email_subject: "New comment to proposal"})
 nt1.translations.where(locale: "en").first_or_create.update_attributes({description: "New contributions and ideas to proposals I am involved in", email_subject: "New comment to proposal"})
 nt1.translations.where(locale: "de").first_or_create.update_attributes({description: "Neue Beiträge und Ideen zu einem Vorschlag in den ich involviert bin.", email_subject: "Neuer Beitrag zu einem Vorschlag!"})
 nt1.translations.where(locale: "fr").first_or_create.update_attributes({description: "Nouvelles contributions et suggestions pour les propositions auxquelles je participe ", email_subject: "Nouveau commentaire à une proposition"})
 nt1.translations.where(locale: "es").first_or_create.update_attributes({description: "Nuevas ideas y sugerencias a las propuestas en la que estoy involucrado.", email_subject: "Nuevo comentario en una propuesta!"})
 NotificationType.create( :description => "Aggiornamento del testo di una proposta a cui partecipo", :notification_category_id => nc37.id ){ |c| c.id = 2}.save
 nt2 = NotificationType.find(2)
 nt2.translations.where(locale: "it").first_or_create.update_attributes({description: "Aggiornamento del testo di una proposta a cui partecipo", email_subject: "Una proposta è stata aggiornata"})
 nt2.translations.where(locale: "eu").first_or_create.update_attributes({description: "Text update about a proposal I am involved in", email_subject: "The proposal has been updated"})
 nt2.translations.where(locale: "us").first_or_create.update_attributes({description: "Text update about a proposal I am involved in", email_subject: "The proposal has been updated"})
 nt2.translations.where(locale: "en").first_or_create.update_attributes({description: "Text update about a proposal I am involved in", email_subject: "The proposal has been updated"})
 nt2.translations.where(locale: "de").first_or_create.update_attributes({description: "Textaktualisierung zu einem Vorschlag in den ich involviert bin", email_subject: "Der Vorschlag wurde aktualisiert."})
 nt2.translations.where(locale: "fr").first_or_create.update_attributes({description: "Mise à jour du texte d'une proposition à laquelle je participe", email_subject: "Une proposition a été mise à jour"})
 nt2.translations.where(locale: "es").first_or_create.update_attributes({description: "Actualización de texto de una propuesta en la que estoy involucrado", email_subject: "La propuesta se ha actualizado."})
 NotificationType.create( :description => "Cambio di stato di una proposta a cui partecipo", :notification_category_id => nc37.id ){ |c| c.id = 4}.save
 nt4 = NotificationType.find(4)
 nt4.translations.where(locale: "it").first_or_create.update_attributes({description: "Cambio di stato di una proposta a cui partecipo", email_subject: "Una proposta ha cambiato lo stato"})
 nt4.translations.where(locale: "eu").first_or_create.update_attributes({description: "The status of a proposal I am involved in has been changed", email_subject: "The status of the proposal has been changed"})
 nt4.translations.where(locale: "us").first_or_create.update_attributes({description: "The status of a proposal I am involved in has been changed", email_subject: "The status of the proposal has been changed"})
 nt4.translations.where(locale: "en").first_or_create.update_attributes({description: "The status of a proposal I am involved in has been changed", email_subject: "The status of the proposal has been changed"})
 nt4.translations.where(locale: "de").first_or_create.update_attributes({description: "Der Status eines Vorschlags in den ich involviert bin hat sich geändert.", email_subject: "Der Status des Vorschlags wurde verändert."})
 nt4.translations.where(locale: "fr").first_or_create.update_attributes({description: "Changement de statut d'une proposition à laquelle je participe", email_subject: "Une proposition a changé de statut"})
 nt4.translations.where(locale: "es").first_or_create.update_attributes({description: "El estado de una propuesta en la que estoy involucrado ha cambiado.", email_subject: "El estado de la propuesta se ha modificado."})
 NotificationType.create( :description => "Nuova valutazione ad una proposta a cui partecipo", :notification_category_id => nc37.id ){ |c| c.id = 21}.save
 nt21 = NotificationType.find(21)
 nt21.translations.where(locale: "it").first_or_create.update_attributes({description: "Nuova valutazione ad una proposta a cui partecipo", email_subject: "Nuova valutazione ad una proposta"})
 nt21.translations.where(locale: "eu").first_or_create.update_attributes({description: "There is a new evaluation for a proposal I am involved in", email_subject: "There is a new evaluation for a proposal of mine"})
 nt21.translations.where(locale: "us").first_or_create.update_attributes({description: "There is a new evaluation for a proposal I am involved in", email_subject: "There is a new evaluation for a proposal of mine"})
 nt21.translations.where(locale: "en").first_or_create.update_attributes({description: "There is a new evaluation for a proposal I am involved in", email_subject: "There is a new evaluation for a proposal of mine"})
 nt21.translations.where(locale: "de").first_or_create.update_attributes({description: "Es gibt eine neue Bewertung für einen Vorschlag in den ich involviert bin.", email_subject: "Es gibt eine neue Bewertung für einen Deiner Vorschläge."})
 nt21.translations.where(locale: "fr").first_or_create.update_attributes({description: "Nouvelle évaluation à une proposition à laquelle je participe", email_subject: "Nouvelle évaluation à une proposition"})
 nt21.translations.where(locale: "es").first_or_create.update_attributes({description: "Hay una nueva evaluación de una propuesta en la que estoy involucrado.", email_subject: "Nueva evaluación a una propuesta."})
 NotificationType.create( :description => "Nuovi redattori per le proposte", :notification_category_id => nc37.id ){ |c| c.id = 24}.save
 nt24 = NotificationType.find(24)
 nt24.translations.where(locale: "it").first_or_create.update_attributes({description: "Nuovi redattori per le proposte", email_subject: "Nuovi redattori per una proposta"})
 nt24.translations.where(locale: "eu").first_or_create.update_attributes({description: "New editors for proposals", email_subject: "New editors for a proposal"})
 nt24.translations.where(locale: "us").first_or_create.update_attributes({description: "New editors for proposals", email_subject: "New editors for a proposal"})
 nt24.translations.where(locale: "en").first_or_create.update_attributes({description: "New editors for proposals", email_subject: "New editors for a proposal"})
 nt24.translations.where(locale: "de").first_or_create.update_attributes({description: "Neue Redakteure für Vorschläge.", email_subject: "Neue Redakteure für Vorschläge."})
 nt24.translations.where(locale: "fr").first_or_create.update_attributes({description: "Nouveaux rédacteurs de propositions", email_subject: "Nouveaux rédacteurs pour une proposition "})
 nt24.translations.where(locale: "es").first_or_create.update_attributes({description: "Nuevos editores de propuestas", email_subject: "Nuevos editores por una propuesta."})
nc38 = NotificationCategory.create(description: "Nuove proposte", seq: 3, short: "NEWPROP")
 nc38.translations.where(locale: "it").first_or_create.update_attributes(description: "Nuove proposte")
 nc38.translations.where(locale: "eu").first_or_create.update_attributes(description: "New proposals")
 nc38.translations.where(locale: "us").first_or_create.update_attributes(description: "New proposals")
 nc38.translations.where(locale: "en").first_or_create.update_attributes(description: "New proposals")
 NotificationType.create( :description => "Nuove proposte inserite nello spazio comune", :notification_category_id => nc38.id ){ |c| c.id = 3}.save
 nt3 = NotificationType.find(3)
 nt3.translations.where(locale: "it").first_or_create.update_attributes({description: "Nuove proposte inserite nello spazio comune", email_subject: "Una nuova proposta è stata inserita"})
 nt3.translations.where(locale: "eu").first_or_create.update_attributes({description: "There are new proposals in the common space", email_subject: "There is a new proposal"})
 nt3.translations.where(locale: "us").first_or_create.update_attributes({description: "There are new proposals in the common space", email_subject: "There is a new proposal"})
 nt3.translations.where(locale: "en").first_or_create.update_attributes({description: "There are new proposals in the common space", email_subject: "There is a new proposal"})
 nt3.translations.where(locale: "de").first_or_create.update_attributes({description: "Es befinden sich neue Vorschläge im Freiraum.", email_subject: "Neuer Vorschlag vorhanden."})
 nt3.translations.where(locale: "fr").first_or_create.update_attributes({description: "Nouvelles propositions insérées dans l'espace commun", email_subject: "Une nouvelle proposition a été insérée"})
 nt3.translations.where(locale: "es").first_or_create.update_attributes({description: "Hay nuevas propuestas en el espacio comun.", email_subject: "Nueva propuesta disponible."})
 NotificationType.create( :description => "Nuove proposte interne al gruppo", :notification_category_id => nc38.id ){ |c| c.id = 10}.save
 nt10 = NotificationType.find(10)
 nt10.translations.where(locale: "it").first_or_create.update_attributes({description: "Nuove proposte interne al gruppo", email_subject: "Una nuova proposta è stata inserita"})
 nt10.translations.where(locale: "eu").first_or_create.update_attributes({description: "New proposals within the group", email_subject: "There is a new proposal"})
 nt10.translations.where(locale: "us").first_or_create.update_attributes({description: "New proposals within the group", email_subject: "There is a new proposal"})
 nt10.translations.where(locale: "en").first_or_create.update_attributes({description: "New proposals within the group", email_subject: "There is a new proposal"})
 nt10.translations.where(locale: "de").first_or_create.update_attributes({description: "Neue Vorschläge in der Gruppe.", email_subject: "Es gibt einen neuen Vorschlag."})
 nt10.translations.where(locale: "fr").first_or_create.update_attributes({description: "Nouvelles propositions du groupe", email_subject: "Une nouvelle proposition a été insérée"})
 nt10.translations.where(locale: "es").first_or_create.update_attributes({description: "Nuevas propuestas en el grupo.", email_subject: "Hay una nueva propuesta."})
nc39 = NotificationCategory.create(description: "Nuovi eventi", seq: 4, short: "NEWEVENT")
 nc39.translations.where(locale: "it").first_or_create.update_attributes(description: "Nuovi eventi")
 nc39.translations.where(locale: "eu").first_or_create.update_attributes(description: "New events")
 nc39.translations.where(locale: "us").first_or_create.update_attributes(description: "New events")
 nc39.translations.where(locale: "en").first_or_create.update_attributes(description: "New events")
 NotificationType.create( :description => "Nuovi eventi pubblici", :notification_category_id => nc39.id ){ |c| c.id = 13}.save
 nt13 = NotificationType.find(13)
 nt13.translations.where(locale: "it").first_or_create.update_attributes({description: "Nuovi eventi pubblici", email_subject: "Un nuovo evento è stato inserito"})
 nt13.translations.where(locale: "eu").first_or_create.update_attributes({description: "There are new public events", email_subject: "There is a new public event"})
 nt13.translations.where(locale: "us").first_or_create.update_attributes({description: "There are new public events", email_subject: "There is a new public event"})
 nt13.translations.where(locale: "en").first_or_create.update_attributes({description: "There are new public events", email_subject: "There is a new public event"})
 nt13.translations.where(locale: "de").first_or_create.update_attributes({description: "Es gibt eine neue öffentliche Veranstaltung.", email_subject: "Es gibt eine neue öffentliche Veranstaltung."})
 nt13.translations.where(locale: "fr").first_or_create.update_attributes({description: "Nouveaux évenements publiques", email_subject: "Un nouvel évenement a été inséré"})
 nt13.translations.where(locale: "es").first_or_create.update_attributes({description: "Nuevos eventos publicos", email_subject: "Un nuevo evento se ha añadido"})
 NotificationType.create( :description => "Nuovi eventi dei gruppi a cui partecipo", :notification_category_id => nc39.id ){ |c| c.id = 14}.save
 nt14 = NotificationType.find(14)
 nt14.translations.where(locale: "it").first_or_create.update_attributes({description: "Nuovi eventi dei gruppi a cui partecipo", email_subject: "Un nuovo evento è stato inserito"})
 nt14.translations.where(locale: "eu").first_or_create.update_attributes({description: "There is a new event within a group I am involved in", email_subject: "There is a new event"})
 nt14.translations.where(locale: "us").first_or_create.update_attributes({description: "There is a new event within a group I am involved in", email_subject: "There is a new event"})
 nt14.translations.where(locale: "en").first_or_create.update_attributes({description: "There is a new event within a group I am involved in", email_subject: "There is a new event"})
 nt14.translations.where(locale: "de").first_or_create.update_attributes({description: "Es gibt eine neue Veranstaltung in einer Gruppe in die ich involviert bin.", email_subject: "Es gibt eine neue Veranstaltung."})
 nt14.translations.where(locale: "fr").first_or_create.update_attributes({description: "Nouveaux évenements des groupes auxquels je participe", email_subject: "Un nouvel évenement a été inséré"})
 nt14.translations.where(locale: "es").first_or_create.update_attributes({description: "Hay un nuevo evento en un grupo en el que estoy involucrado.", email_subject: "Hay un nuevo evento."})
nc40 = NotificationCategory.create(description: "Gruppi", seq: 5, short: "GROUPS")
 nc40.translations.where(locale: "it").first_or_create.update_attributes(description: "Gruppi")
 nc40.translations.where(locale: "eu").first_or_create.update_attributes(description: "Groups")
 nc40.translations.where(locale: "us").first_or_create.update_attributes(description: "Groups")
 nc40.translations.where(locale: "en").first_or_create.update_attributes(description: "Groups")
 NotificationType.create( :description => "Nuovi post sulle pagine dei gruppi che seguo", :notification_category_id => nc40.id ){ |c| c.id = 8}.save
 nt8 = NotificationType.find(8)
 nt8.translations.where(locale: "it").first_or_create.update_attributes({description: "Nuovi post sulle pagine dei gruppi che seguo", email_subject: "E' presente un nuovo post"})
 nt8.translations.where(locale: "eu").first_or_create.update_attributes({description: "There are new posts in the pages of the groups I am following", email_subject: "There is a new post"})
 nt8.translations.where(locale: "us").first_or_create.update_attributes({description: "There are new posts in the pages of the groups I am following", email_subject: "There is a new post"})
 nt8.translations.where(locale: "en").first_or_create.update_attributes({description: "There are new posts in the pages of the groups I am following", email_subject: "There is a new post"})
 nt8.translations.where(locale: "de").first_or_create.update_attributes({description: "Es gibt eine neues Posting auf der Seite der Gruppen denen ich folge.", email_subject: "Es gibt ein neues Posting."})
 nt8.translations.where(locale: "fr").first_or_create.update_attributes({description: "Nouveaux commentaires dans les pages des groupes que je suis", email_subject: "Il y a un nouveau billet"})
 nt8.translations.where(locale: "es").first_or_create.update_attributes({description: "Hay nuevos comenatrios en las paginas de los grupos que sigo.", email_subject: "Hay un nuevo comentario."})
 NotificationType.create( :description => "Nuovi post sulle pagine dei gruppi a cui partecipo", :notification_category_id => nc40.id ){ |c| c.id = 9}.save
 nt9 = NotificationType.find(9)
 nt9.translations.where(locale: "it").first_or_create.update_attributes({description: "Nuovi post sulle pagine dei gruppi a cui partecipo", email_subject: "E' presente un nuovo post"})
 nt9.translations.where(locale: "eu").first_or_create.update_attributes({description: "There are new posts in the pages of the groups I am involved in", email_subject: "There is a new post"})
 nt9.translations.where(locale: "us").first_or_create.update_attributes({description: "There are new posts in the pages of the groups I am involved in", email_subject: "There is a new post"})
 nt9.translations.where(locale: "en").first_or_create.update_attributes({description: "There are new posts in the pages of the groups I am involved in", email_subject: "There is a new post"})
 nt9.translations.where(locale: "de").first_or_create.update_attributes({description: "Es gibt neue Postings auf den Seiten der Gruppen in denen ich involviert bin.", email_subject: "Es gibt neue Postings."})
 nt9.translations.where(locale: "fr").first_or_create.update_attributes({description: "Nouveaux commentaires dans les pages des groupes auxquels je participe", email_subject: "il y a un nouveau billet"})
 nt9.translations.where(locale: "es").first_or_create.update_attributes({description: "Hay nuevos comenatrios en las paginas de los grupos de que participo.", email_subject: "Hay un nuevo comentario."})
 NotificationType.create( :description => "Nuova richiesta di partecipazione", :notification_category_id => nc40.id ){ |c| c.id = 12}.save
 nt12 = NotificationType.find(12)
 nt12.translations.where(locale: "it").first_or_create.update_attributes({description: "Nuova richiesta di partecipazione", email_subject: "Nuova richiesta di partecipazione"})
 nt12.translations.where(locale: "eu").first_or_create.update_attributes({description: "There is a new participation request", email_subject: "There is a new participation request"})
 nt12.translations.where(locale: "us").first_or_create.update_attributes({description: "There is a new participation request", email_subject: "There is a new participation request"})
 nt12.translations.where(locale: "en").first_or_create.update_attributes({description: "There is a new participation request", email_subject: "There is a new participation request"})
 nt12.translations.where(locale: "de").first_or_create.update_attributes({description: "Es gibt eine neue Teilnahme-Anfrage.", email_subject: "Es gibt eine neue Teilnahme-Anfrage."})
 nt12.translations.where(locale: "fr").first_or_create.update_attributes({description: "Nouvelle demande de participation", email_subject: "Nouvelle demande de participation"})
 nt12.translations.where(locale: "es").first_or_create.update_attributes({description: "Hay una nueva solicitud de partecipación.", email_subject: "Hay una nueva solicitud de partecipación."})
 NotificationType.create( :description => "Nuovo post di un utente che seguo", :notification_category_id => nc40.id ){ |c| c.id = 15}.save
 nt15 = NotificationType.find(15)
 nt15.translations.where(locale: "it").first_or_create.update_attributes({description: "Nuovo post di un utente che seguo", email_subject: "Un nuovo post è stato inserito"})
 nt15.translations.where(locale: "eu").first_or_create.update_attributes({description: "There is a new post from a user I am following", email_subject: "There is a new post"})
 nt15.translations.where(locale: "us").first_or_create.update_attributes({description: "There is a new post from a user I am following", email_subject: "There is a new post"})
 nt15.translations.where(locale: "en").first_or_create.update_attributes({description: "There is a new post from a user I am following", email_subject: "There is a new post"})
 nt15.translations.where(locale: "de").first_or_create.update_attributes({description: "Es gibt ein neues Posting eines Benutzers dem ich folge.", email_subject: "Es gibt ein neues Posting."})
 nt15.translations.where(locale: "fr").first_or_create.update_attributes({description: "Nouveau billet d'un utilisateur que je suis", email_subject: "Un nouveau billet a été inséré"})
 nt15.translations.where(locale: "es").first_or_create.update_attributes({description: "Hay un nuevo posting de un usuario que sigo.", email_subject: "Hay un nuevo posting."})
 pc5 = ProposalCategory.create(:description => "Nessuna categoria" ){ |c| c.id = 5 }.save
 pc5 = ProposalCategory.find(5)
 pc5.translations.where(locale: "it").first_or_create.update_attributes(description: "Nessuna categoria")
 pc5.translations.where(locale: "eu").first_or_create.update_attributes(description: "Uncategorized")
 pc5.translations.where(locale: "en").first_or_create.update_attributes(description: "Uncategorized")
 pc5.translations.where(locale: "pt").first_or_create.update_attributes(description: "Sem categoria")
 pc5.translations.where(locale: "fr").first_or_create.update_attributes(description: "Aucune catégorie")
 pc5.translations.where(locale: "de").first_or_create.update_attributes(description: "Keine Kategorie")
 pc5.translations.where(locale: "es").first_or_create.update_attributes(description: "Ninguna Categoría")
 pc7 = ProposalCategory.create(:description => "Educazione, Ricerca" ){ |c| c.id = 7 }.save
 pc7 = ProposalCategory.find(7)
 pc7.translations.where(locale: "it").first_or_create.update_attributes(description: "Educazione, Ricerca")
 pc7.translations.where(locale: "eu").first_or_create.update_attributes(description: "Education, Research")
 pc7.translations.where(locale: "en").first_or_create.update_attributes(description: "Education, Research")
 pc7.translations.where(locale: "pt").first_or_create.update_attributes(description: "Educação, Pesquisa")
 pc7.translations.where(locale: "fr").first_or_create.update_attributes(description: "Education, Recherche")
 pc7.translations.where(locale: "de").first_or_create.update_attributes(description: "Bildung, Forschung")
 pc7.translations.where(locale: "es").first_or_create.update_attributes(description: "Educación, Investigación")
 pc8 = ProposalCategory.create(:description => "Salute, Igiene" ){ |c| c.id = 8 }.save
 pc8 = ProposalCategory.find(8)
 pc8.translations.where(locale: "it").first_or_create.update_attributes(description: "Salute, Igiene")
 pc8.translations.where(locale: "eu").first_or_create.update_attributes(description: "Health, Hygiene")
 pc8.translations.where(locale: "en").first_or_create.update_attributes(description: "Health, Hygiene")
 pc8.translations.where(locale: "pt").first_or_create.update_attributes(description: "Saúde, Higiene")
 pc8.translations.where(locale: "fr").first_or_create.update_attributes(description: "Santé, Hygiène")
 pc8.translations.where(locale: "de").first_or_create.update_attributes(description: "Gesundheit, Hygiene")
 pc8.translations.where(locale: "es").first_or_create.update_attributes(description: "Salud, Higiene")
 pc9 = ProposalCategory.create(:description => "Informazione, Comunicazione" ){ |c| c.id = 9 }.save
 pc9 = ProposalCategory.find(9)
 pc9.translations.where(locale: "it").first_or_create.update_attributes(description: "Informazione, Comunicazione")
 pc9.translations.where(locale: "eu").first_or_create.update_attributes(description: "Information, Communication")
 pc9.translations.where(locale: "en").first_or_create.update_attributes(description: "Information, Communication")
 pc9.translations.where(locale: "pt").first_or_create.update_attributes(description: "Informação, Comunicação")
 pc9.translations.where(locale: "fr").first_or_create.update_attributes(description: "Information, Communication")
 pc9.translations.where(locale: "de").first_or_create.update_attributes(description: "Information, Kommunikation")
 pc9.translations.where(locale: "es").first_or_create.update_attributes(description: "Información, Comunicación")
 pc10 = ProposalCategory.create(:description => "Commercio, Finanza, Fisco" ){ |c| c.id = 10 }.save
 pc10 = ProposalCategory.find(10)
 pc10.translations.where(locale: "it").first_or_create.update_attributes(description: "Commercio, Finanza, Fisco")
 pc10.translations.where(locale: "eu").first_or_create.update_attributes(description: "Commerce, Finance, Taxes")
 pc10.translations.where(locale: "en").first_or_create.update_attributes(description: "Commerce, Finance, Taxes")
 pc10.translations.where(locale: "pt").first_or_create.update_attributes(description: "Comércio, Finanças, Tributos")
 pc10.translations.where(locale: "fr").first_or_create.update_attributes(description: "Commerce, Finance, Fisc")
 pc10.translations.where(locale: "de").first_or_create.update_attributes(description: "Commerce, Finanzen, Steuern")
 pc10.translations.where(locale: "es").first_or_create.update_attributes(description: "Comercio, Finanzas, Impuestos")
 pc11 = ProposalCategory.create(:description => "Lavoro e Auto-realizzazione" ){ |c| c.id = 11 }.save
 pc11 = ProposalCategory.find(11)
 pc11.translations.where(locale: "it").first_or_create.update_attributes(description: "Lavoro e Auto-realizzazione")
 pc11.translations.where(locale: "eu").first_or_create.update_attributes(description: "Work and Self-realization")
 pc11.translations.where(locale: "en").first_or_create.update_attributes(description: "Work and Self-realization")
 pc11.translations.where(locale: "pt").first_or_create.update_attributes(description: "Trabalho e Auto-realização")
 pc11.translations.where(locale: "fr").first_or_create.update_attributes(description: "Travail et Auto-réalisation")
 pc11.translations.where(locale: "de").first_or_create.update_attributes(description: "Arbeit und Selbstverwirklichung")
 pc11.translations.where(locale: "es").first_or_create.update_attributes(description: "Trabajo y Realización Personal")
 pc12 = ProposalCategory.create(:description => "Sicurezza e Giustizia" ){ |c| c.id = 12 }.save
 pc12 = ProposalCategory.find(12)
 pc12.translations.where(locale: "it").first_or_create.update_attributes(description: "Sicurezza e Giustizia")
 pc12.translations.where(locale: "eu").first_or_create.update_attributes(description: "Security and Justice")
 pc12.translations.where(locale: "en").first_or_create.update_attributes(description: "Security and Justice")
 pc12.translations.where(locale: "pt").first_or_create.update_attributes(description: "Segurança e Justiça")
 pc12.translations.where(locale: "fr").first_or_create.update_attributes(description: "Sécurité et Justice")
 pc12.translations.where(locale: "de").first_or_create.update_attributes(description: "Sicherheit und Justiz")
 pc12.translations.where(locale: "es").first_or_create.update_attributes(description: "Seguridad y Justicia")
 pc13 = ProposalCategory.create(:description => "Mondo, Migrazione" ){ |c| c.id = 13 }.save
 pc13 = ProposalCategory.find(13)
 pc13.translations.where(locale: "it").first_or_create.update_attributes(description: "Mondo, Migrazione")
 pc13.translations.where(locale: "eu").first_or_create.update_attributes(description: "World, Migration")
 pc13.translations.where(locale: "en").first_or_create.update_attributes(description: "World, Migration")
 pc13.translations.where(locale: "pt").first_or_create.update_attributes(description: "Mundial, Migração")
 pc13.translations.where(locale: "fr").first_or_create.update_attributes(description: "Monde, Migration")
 pc13.translations.where(locale: "de").first_or_create.update_attributes(description: "Welt, Migration")
 pc13.translations.where(locale: "es").first_or_create.update_attributes(description: "Mundo, Migraciones")
 pc14 = ProposalCategory.create(:description => "Minoranze, Handicap" ){ |c| c.id = 14 }.save
 pc14 = ProposalCategory.find(14)
 pc14.translations.where(locale: "it").first_or_create.update_attributes(description: "Minoranze, Handicap")
 pc14.translations.where(locale: "eu").first_or_create.update_attributes(description: "Minorities, Handicap")
 pc14.translations.where(locale: "en").first_or_create.update_attributes(description: "Minorities, Handicap")
 pc14.translations.where(locale: "pt").first_or_create.update_attributes(description: "Minorias. Deficientes Físicos,")
 pc14.translations.where(locale: "fr").first_or_create.update_attributes(description: "Minorités, Handicap")
 pc14.translations.where(locale: "de").first_or_create.update_attributes(description: "Minderheiten, Handicap")
 pc14.translations.where(locale: "es").first_or_create.update_attributes(description: "Minorías, Handicap")
 pc15 = ProposalCategory.create(:description => "Etica, Solidarietà, Spiritualità" ){ |c| c.id = 15 }.save
 pc15 = ProposalCategory.find(15)
 pc15.translations.where(locale: "it").first_or_create.update_attributes(description: "Etica, Solidarietà, Spiritualità")
 pc15.translations.where(locale: "eu").first_or_create.update_attributes(description: "Ethics, Solidarity, Spirituality")
 pc15.translations.where(locale: "en").first_or_create.update_attributes(description: "Ethics, Solidarity, Spirituality")
 pc15.translations.where(locale: "pt").first_or_create.update_attributes(description: "Ética, Solidariedade, Espiritualidade")
 pc15.translations.where(locale: "fr").first_or_create.update_attributes(description: "Etique, Solidarité,Spiritualité")
 pc15.translations.where(locale: "de").first_or_create.update_attributes(description: "Ethik, Solidarität, Spiritualität")
 pc15.translations.where(locale: "es").first_or_create.update_attributes(description: "Ètica, Solidaridad, Espiritualidad")
 pc16 = ProposalCategory.create(:description => "Sessualità, Famiglia, Bambini" ){ |c| c.id = 16 }.save
 pc16 = ProposalCategory.find(16)
 pc16.translations.where(locale: "it").first_or_create.update_attributes(description: "Sessualità, Famiglia, Bambini")
 pc16.translations.where(locale: "eu").first_or_create.update_attributes(description: "Sexuality, Family, Children")
 pc16.translations.where(locale: "en").first_or_create.update_attributes(description: "Sexuality, Family, Children")
 pc16.translations.where(locale: "pt").first_or_create.update_attributes(description: "Sexualidade, Família, Infância")
 pc16.translations.where(locale: "fr").first_or_create.update_attributes(description: "Sexualité, Famille, Enfants")
 pc16.translations.where(locale: "de").first_or_create.update_attributes(description: "Sexualität, Familie, Kinder")
 pc16.translations.where(locale: "es").first_or_create.update_attributes(description: "Sexualidad, Familia, Niños")
 pc17 = ProposalCategory.create(:description => "Arte e Cultura" ){ |c| c.id = 17 }.save
 pc17 = ProposalCategory.find(17)
 pc17.translations.where(locale: "it").first_or_create.update_attributes(description: "Arte e Cultura")
 pc17.translations.where(locale: "eu").first_or_create.update_attributes(description: "Art and Culture")
 pc17.translations.where(locale: "en").first_or_create.update_attributes(description: "Art and Culture")
 pc17.translations.where(locale: "pt").first_or_create.update_attributes(description: "Arte e Cultura")
 pc17.translations.where(locale: "fr").first_or_create.update_attributes(description: "Art et Culture")
 pc17.translations.where(locale: "de").first_or_create.update_attributes(description: "Kunst und Kultur")
 pc17.translations.where(locale: "es").first_or_create.update_attributes(description: "Arte y Cultura")
 pc18 = ProposalCategory.create(:description => "Socialità, Sport, Divertimento" ){ |c| c.id = 18 }.save
 pc18 = ProposalCategory.find(18)
 pc18.translations.where(locale: "it").first_or_create.update_attributes(description: "Socialità, Sport, Divertimento")
 pc18.translations.where(locale: "eu").first_or_create.update_attributes(description: "Social, Sport, Entertainment")
 pc18.translations.where(locale: "en").first_or_create.update_attributes(description: "Social, Sport, Entertainment")
 pc18.translations.where(locale: "pt").first_or_create.update_attributes(description: "Social, Desporto, Entretenimento")
 pc18.translations.where(locale: "fr").first_or_create.update_attributes(description: "Vie sociale, Sport, Loisirs")
 pc18.translations.where(locale: "de").first_or_create.update_attributes(description: "Social, Sport, Unterhaltung")
 pc18.translations.where(locale: "es").first_or_create.update_attributes(description: "Social, Deporte, Entretenimiento")
 pc19 = ProposalCategory.create(:description => "Organizzazione interna" ){ |c| c.id = 19 }.save
 pc19 = ProposalCategory.find(19)
 pc19.translations.where(locale: "it").first_or_create.update_attributes(description: "Organizzazione interna")
 pc19.translations.where(locale: "eu").first_or_create.update_attributes(description: "Internal organization")
 pc19.translations.where(locale: "en").first_or_create.update_attributes(description: "Internal organization")
 pc19.translations.where(locale: "pt").first_or_create.update_attributes(description: "Organização interna")
 pc19.translations.where(locale: "fr").first_or_create.update_attributes(description: "Organisation interne")
 pc19.translations.where(locale: "de").first_or_create.update_attributes(description: "Interne Organisation")
 pc19.translations.where(locale: "es").first_or_create.update_attributes(description: "Organización interna")
 pc23 = ProposalCategory.create(:description => "Energia, Clima" ){ |c| c.id = 23 }.save
 pc23 = ProposalCategory.find(23)
 pc23.translations.where(locale: "it").first_or_create.update_attributes(description: "Energia, Clima")
 pc23.translations.where(locale: "eu").first_or_create.update_attributes(description: "Energy, Climate")
 pc23.translations.where(locale: "en").first_or_create.update_attributes(description: "Energy, Climate")
 pc23.translations.where(locale: "pt").first_or_create.update_attributes(description: "Energia, Clima")
 pc23.translations.where(locale: "fr").first_or_create.update_attributes(description: "Energie, Climat")
 pc23.translations.where(locale: "de").first_or_create.update_attributes(description: "Energie, Klima")
 pc23.translations.where(locale: "es").first_or_create.update_attributes(description: "Energía, Clima")
 pc20 = ProposalCategory.create(:description => "Acqua, Cibo, Agricoltura" ){ |c| c.id = 20 }.save
 pc20 = ProposalCategory.find(20)
 pc20.translations.where(locale: "it").first_or_create.update_attributes(description: "Acqua, Cibo, Agricoltura")
 pc20.translations.where(locale: "eu").first_or_create.update_attributes(description: "Water, Food, Agriculture")
 pc20.translations.where(locale: "en").first_or_create.update_attributes(description: "Water, Food, Agriculture")
 pc20.translations.where(locale: "pt").first_or_create.update_attributes(description: " Àgua, Alimentos, Agricultura")
 pc20.translations.where(locale: "fr").first_or_create.update_attributes(description: "Eau, Nourriture, Agriculture")
 pc20.translations.where(locale: "de").first_or_create.update_attributes(description: "Wasser, Ernährung, Landwirtschaft")
 pc20.translations.where(locale: "es").first_or_create.update_attributes(description: "Agua, Alimentos, Agricultura")
 pc21 = ProposalCategory.create(:description => "Territorio, Natura, Animali" ){ |c| c.id = 21 }.save
 pc21 = ProposalCategory.find(21)
 pc21.translations.where(locale: "it").first_or_create.update_attributes(description: "Territorio, Natura, Animali")
 pc21.translations.where(locale: "eu").first_or_create.update_attributes(description: "Territory, Nature, Animals")
 pc21.translations.where(locale: "en").first_or_create.update_attributes(description: "Territory, Nature, Animals")
 pc21.translations.where(locale: "pt").first_or_create.update_attributes(description: "Território, Natureza, Animais")
 pc21.translations.where(locale: "fr").first_or_create.update_attributes(description: "Territoire, Nature, Animaux")
 pc21.translations.where(locale: "de").first_or_create.update_attributes(description: "Territory, Natur, Tiere")
 pc21.translations.where(locale: "es").first_or_create.update_attributes(description: "Territorio, Naturaleza, Animales")
 pc22 = ProposalCategory.create(:description => "Urbanistica, Mobilità, Edilizia" ){ |c| c.id = 22 }.save
 pc22 = ProposalCategory.find(22)
 pc22.translations.where(locale: "it").first_or_create.update_attributes(description: "Urbanistica, Mobilità, Edilizia")
 pc22.translations.where(locale: "eu").first_or_create.update_attributes(description: "Urbanism, Mobility, Construction")
 pc22.translations.where(locale: "en").first_or_create.update_attributes(description: "Urbanism, Mobility, Construction")
 pc22.translations.where(locale: "pt").first_or_create.update_attributes(description: "Urbanismo, Mobilidade, Construção")
 pc22.translations.where(locale: "fr").first_or_create.update_attributes(description: "Urbanisme, Mobilité, Batiment")
 pc22.translations.where(locale: "de").first_or_create.update_attributes(description: "Städtebau, Mobilität, Bau")
 pc22.translations.where(locale: "es").first_or_create.update_attributes(description: "Urbanismo, Movilidad, Obras")
 pc24 = ProposalCategory.create(:description => "Industria, Materiali e Rifiuti" ){ |c| c.id = 24 }.save
 pc24 = ProposalCategory.find(24)
 pc24.translations.where(locale: "it").first_or_create.update_attributes(description: "Industria, Materiali e Rifiuti")
 pc24.translations.where(locale: "eu").first_or_create.update_attributes(description: "Industry, Materials and Waste")
 pc24.translations.where(locale: "en").first_or_create.update_attributes(description: "Industry, Materials and Waste")
 pc24.translations.where(locale: "pt").first_or_create.update_attributes(description: "Indústria, Materiais e Resíduos")
 pc24.translations.where(locale: "fr").first_or_create.update_attributes(description: "Industrie, Matériaux et Déchets")
 pc24.translations.where(locale: "de").first_or_create.update_attributes(description: "Industrie-und Abfallwirtschaft")
 pc24.translations.where(locale: "es").first_or_create.update_attributes(description: "Industria, Materiales y Residuos")
 pc25 = ProposalCategory.create(:description => "Democrazia, Istituzioni" ){ |c| c.id = 25 }.save
 pc25 = ProposalCategory.find(25)
 pc25.translations.where(locale: "it").first_or_create.update_attributes(description: "Democrazia, Istituzioni")
 pc25.translations.where(locale: "eu").first_or_create.update_attributes(description: "Democracy, Institutions")
 pc25.translations.where(locale: "en").first_or_create.update_attributes(description: "Democracy, Institutions")
 pc25.translations.where(locale: "pt").first_or_create.update_attributes(description: "Democracia, Instituições")
 pc25.translations.where(locale: "fr").first_or_create.update_attributes(description: "Démocratie, Institutions")
 pc25.translations.where(locale: "de").first_or_create.update_attributes(description: "Demokratie, Institutionen")
 pc25.translations.where(locale: "es").first_or_create.update_attributes(description: "Democracia, Instituciones")
ProposalState.create( :description => "in valutazione" ){ |c| c.id = 1 }.save
ProposalState.create( :description => "in attesa di data" ){ |c| c.id = 2 }.save
ProposalState.create( :description => "in attesa" ){ |c| c.id = 3 }.save
ProposalState.create( :description => "in votazione" ){ |c| c.id = 4 }.save
ProposalState.create( :description => "respinta" ){ |c| c.id = 5 }.save
ProposalState.create( :description => "accettata" ){ |c| c.id = 6 }.save
ProposalState.create( :description => "revisione e feedback" ){ |c| c.id = 7 }.save
RankingType.create( :description => "Positivo" ){ |c| c.id = 1 }.save
RankingType.create( :description => "Neutro" ){ |c| c.id = 2 }.save
RankingType.create( :description => "Negativo" ){ |c| c.id = 3 }.save
tut1 = Tutorial.create( :action => "show", :controller => "home", :name => "Welcome Tutorial", :description => "Tutorial di benvenuto")
Step.create( :tutorial_id => tut1.id, :index => 0, :title => "Messaggio di benvenuto", :content => "", :required => "false", :fragment => "welcome")
Step.create( :tutorial_id => tut1.id, :index => 1, :title => "Confini geografici di interesse", :content => "", :required => "false", :fragment => "interest_borders")
Step.create( :tutorial_id => tut1.id, :index => 2, :title => "Scegli i gruppi", :content => "", :required => "false", :fragment => "choose_follow")
Step.create( :tutorial_id => tut1.id, :index => 3, :title => "Prima proposta", :content => "", :required => "false", :fragment => "first_proposal")
Step.create( :tutorial_id => tut1.id, :index => 4, :title => "Immagine", :content => "", :required => "false", :fragment => "choose_image")
tut2 = Tutorial.create( :action => "new", :controller => "proposals", :name => "First Proposal", :description => "Tutorial di spiegazione su come inserire la prima proposta")
Step.create( :tutorial_id => tut2.id, :index => 0, :title => "Breve spiegazione", :content => "", :required => "false", :fragment => "proposal_instructions")
tut3 = Tutorial.create( :action => "show", :controller => "proposals", :name => "Rank Bar", :description => "Tutorial di spiegazione del funzionamento della ranking bar")
Step.create( :tutorial_id => tut3.id, :index => 0, :title => "Spiegazione Rank Bar", :content => "", :required => "false", :fragment => "rank_bar_explain")
Step.create( :tutorial_id => tut3.id, :index => 0, :title => "L'anonimato nella discussione", :content => "", :required => "false", :fragment => "proposals_show")
tut4 = Tutorial.create( :action => "index", :controller => "candidates", :name => "Area candidature", :description => "Tutorial di spiegazione sulla pagina delle candidature")
Step.create( :tutorial_id => tut4.id, :index => 0, :title => "La pagina delle candidature del gruppo", :content => "", :required => "false", :fragment => "candidates_index")
UserType.create( description: "Administrator", :short_name => "admin" ){ |c| c.id = 1}.save
UserType.create( description: "Moderator", :short_name => "mod" ){ |c| c.id = 2}.save
UserType.create( description: "Authenticated User", :short_name => "authuser" ){ |c| c.id = 3}.save
UserType.create( description: "User", :short_name => "user" ){ |c| c.id = 4}.save
Quorum.create(name: "1 giorno", percentage: nil, minutes: 1440, condition: "AND", good_score: 50, bad_score: 50, public: true, seq: 1)
Quorum.create(name: "3 giorni", percentage: nil, minutes: 4320, condition: "AND", good_score: 50, bad_score: 50, public: true, seq: 2)
Quorum.create(name: "7 giorni", percentage: nil, minutes: 10080, condition: "AND", good_score: 50, bad_score: 50, public: true, seq: 3)
Quorum.create(name: "15 giorni", percentage: nil, minutes: 21600, condition: "AND", good_score: 50, bad_score: 50, public: true, seq: 4)
Quorum.create(name: "30 giorni", percentage: nil, minutes: 43200, condition: "AND", good_score: 50, bad_score: 50, public: true, seq: 5)
Quorum.create(name: "Veloce", percentage: 20, minutes: 2880, condition: "AND", good_score: 50, bad_score: 50, public: true, seq: 6)
Quorum.create(name: "Normale", percentage: 30, minutes: 21600, condition: "AND", good_score: 60, bad_score: 60, public: true, seq: 7)
Quorum.create(name: "Lunga", percentage: 50, minutes: 86400, condition: "AND", good_score: 60, bad_score: 60, public: true, seq: nil)
Quorum.create(name: "Buon punteggio", percentage: 30, minutes: 21600, condition: "AND", good_score: 70, bad_score: 30, public: true, seq: nil)
PartecipationRole.create(:name => "amministratore", :description => "Amministratore"){ |c| c.id = 2 }.save
VoteType.create( :description => "Favorevole"){ |c| c.id = 1 }.save
VoteType.create( :description => "Neutrale"){ |c| c.id = 2 }.save
VoteType.create( :description => "Contrario"){ |c| c.id = 3 }.save
Configuration.create(name: "democracy", value: 1)
Configuration.create(name: "default_user_type", value: 1)
Configuration.create(name: "groups_active", value: 1)
Configuration.create(name: "open_space_calendar", value: 1)
Configuration.create(name: "open_space_proposals", value: 1)
Configuration.create(name: "blog", value: 1)
Configuration.create(name: "phases_active", value: 1)
Configuration.create(name: "elections_active", value: 1)
Configuration.create(name: "user_messages", value: 1)
Configuration.create(name: "groups_calendar", value: 1)
Configuration.create(name: "documents_active", value: 1)
Configuration.create(name: "proposal_categories", value: 1)
Configuration.create(name: "folksonomy", value: 1)
Configuration.create(name: "group_areas", value: 1)
Configuration.create(name: "proposal_support", value: 1)
Configuration.create(name: "invites_active", value: 1)
Configuration.create(name: "socialnetwork_active", value: 1)
Configuration.create(name: "rotp", value: 1)
