Comune.create(description: "Atacames", province_id: 110, region_id:  1, country_id: 53, continent_id: 2 , population: 15463)
Comune.create(description: "Esmeraldas", province_id: 110, region_id:  1, country_id: 53, continent_id: 2 , population: 154035)
Comune.create(description: "La Concordia", province_id: 110, region_id:  1, country_id: 53, continent_id: 2 , population: 29003)
Comune.create(description: "Rosa Zárate (Quinindé)", province_id: 110, region_id:  1, country_id: 53, continent_id: 2 , population: 28928)
Comune.create(description: "San Lorenzo", province_id: 110, region_id:  1, country_id: 53, continent_id: 2 , population: 23265)
