#encoding: utf-8
Comune.create(:description => "Cassolnovo", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 5820)
Comune.create(:description => "Alagna", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 755)
Comune.create(:description => "Albaredo Arnaboldi", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 205)
Comune.create(:description => "Albonese", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 504)
Comune.create(:description => "Albuzzano", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 2256)
Comune.create(:description => "Arena Po", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 1572)
Comune.create(:description => "Badia Pavese", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 394)
Comune.create(:description => "Bagnaria", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 639)
Comune.create(:description => "Barbianello", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 816)
Comune.create(:description => "Bastida Pancarana", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 894)
Comune.create(:description => "Battuda", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 352)
Comune.create(:description => "Belgioioso", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 5357)
Comune.create(:description => "Bereguardo", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 2390)
Comune.create(:description => "Borgarello", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 1609)
Comune.create(:description => "Borgo Priolo", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 1405)
Comune.create(:description => "Borgo San Siro", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 1023)
Comune.create(:description => "Borgoratto Mormorolo", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 434)
Comune.create(:description => "Bornasco", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 1677)
Comune.create(:description => "Bosnasco", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 600)
Comune.create(:description => "Brallo Di Pregola", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 930)
Comune.create(:description => "Breme", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 936)
Comune.create(:description => "Bressana Bottarone", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 3143)
Comune.create(:description => "Broni", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 9347)
Comune.create(:description => "Calvignano", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 130)
Comune.create(:description => "Campospinoso", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 772)
Comune.create(:description => "Candia Lomellina", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 1646)
Comune.create(:description => "Canevino", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 131)
Comune.create(:description => "Canneto Pavese", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 1338)
Comune.create(:description => "Carbonara Al Ticino", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 1289)
Comune.create(:description => "Casanova Lonati", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 427)
Comune.create(:description => "Casatisma", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 856)
Comune.create(:description => "Casei Gerola", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 2536)
Comune.create(:description => "Casorate Primo", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 7028)
Comune.create(:description => "Castana", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 754)
Comune.create(:description => "Casteggio", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 6337)
Comune.create(:description => "Castelletto Di Branduzzo", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 1023)
Comune.create(:description => "Castelnovetto", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 643)
Comune.create(:description => "Cava Manara", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 5321)
Comune.create(:description => "Cecima", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 276)
Comune.create(:description => "Ceranova", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 1151)
Comune.create(:description => "Ceretto Lomellina", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 211)
Comune.create(:description => "Cergnago", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 764)
Comune.create(:description => "Certosa Di Pavia", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 3320)
Comune.create(:description => "Cervesina", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 1200)
Comune.create(:description => "Chignolo Po", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 3234)
Comune.create(:description => "Cigognola", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 1367)
Comune.create(:description => "Cilavegna", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 4979)
Comune.create(:description => "Codevilla", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 917)
Comune.create(:description => "Confienza", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 1636)
Comune.create(:description => "Copiano", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 1364)
Comune.create(:description => "Corana", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 790)
Comune.create(:description => "Cornale", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 734)
Comune.create(:description => "Corteolona", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 1906)
Comune.create(:description => "Corvino San Quirico", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 1092)
Comune.create(:description => "Cozzo", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 432)
Comune.create(:description => "Cura Carpignano", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 2145)
Comune.create(:description => "Dorno", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 4184)
Comune.create(:description => "Ferrera Erbognone", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 1103)
Comune.create(:description => "Filighera", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 843)
Comune.create(:description => "Fortunago", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 420)
Comune.create(:description => "Frascarolo", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 1321)
Comune.create(:description => "Galliavola", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 232)
Comune.create(:description => "Gambarana", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 281)
Comune.create(:description => "Garlasco", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Genzone", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 345)
Comune.create(:description => "Gerenzago", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 913)
Comune.create(:description => "Giussago", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 3915)
Comune.create(:description => "Godiasco", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 2806)
Comune.create(:description => "Golferenzo", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 233)
Comune.create(:description => "Gravellona Lomellina", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 2173)
Comune.create(:description => "Gropello Cairoli", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 4105)
Comune.create(:description => "Inverno E Monteleone", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 1069)
Comune.create(:description => "Landriano", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 4171)
Comune.create(:description => "Langosco", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 458)
Comune.create(:description => "Lardirago", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 1163)
Comune.create(:description => "Linarolo", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 2172)
Comune.create(:description => "Lirio", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 147)
Comune.create(:description => "Lomello", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 2378)
Comune.create(:description => "Lungavilla", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 2154)
Comune.create(:description => "Magherno", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 1380)
Comune.create(:description => "Marcignago", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 1923)
Comune.create(:description => "Marzano", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 1025)
Comune.create(:description => "Mede", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 6924)
Comune.create(:description => "Menconico", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 494)
Comune.create(:description => "Mezzana Bigli", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 1168)
Comune.create(:description => "Mezzana Rabattone", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 532)
Comune.create(:description => "Mezzanino", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 1468)
Comune.create(:description => "Miradolo Terme", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 3177)
Comune.create(:description => "Montalto Pavese", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 963)
Comune.create(:description => "Montebello Della Battaglia", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 1647)
Comune.create(:description => "Montecalvo Versiggia", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 555)
Comune.create(:description => "Montescano", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 379)
Comune.create(:description => "Montesegale", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 319)
Comune.create(:description => "Monticelli Pavese", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 667)
Comune.create(:description => "Mornico Losana", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 728)
Comune.create(:description => "Mortara", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 14244)
Comune.create(:description => "Nicorvo", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 386)
Comune.create(:description => "Olevano Di Lomellina", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 771)
Comune.create(:description => "Oliva Gessi", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 200)
Comune.create(:description => "Ottobiano", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 1131)
Comune.create(:description => "Palestro", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 2014)
Comune.create(:description => "Pancarana", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 322)
Comune.create(:description => "Parona", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 1698)
Comune.create(:description => "Pavia", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 71214)
Comune.create(:description => "Pieve Albignola", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 922)
Comune.create(:description => "Pieve Del Cairo", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 2166)
Comune.create(:description => "Pieve Porto Morone", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 2598)
Comune.create(:description => "Pinarolo Po", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 1568)
Comune.create(:description => "Pizzale", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 640)
Comune.create(:description => "Ponte Nizza", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 864)
Comune.create(:description => "Portalbera", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 1343)
Comune.create(:description => "Rea", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 498)
Comune.create(:description => "Redavalle", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 1008)
Comune.create(:description => "Retorbido", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 1170)
Comune.create(:description => "Rivanazzano", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Robbio", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 6159)
Comune.create(:description => "Robecco Pavese", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 547)
Comune.create(:description => "Rocca Susella", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 229)
Comune.create(:description => "Rognano", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 194)
Comune.create(:description => "Romagnese", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 909)
Comune.create(:description => "Roncaro", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 626)
Comune.create(:description => "Rosasco", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 712)
Comune.create(:description => "Rovescala", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 933)
Comune.create(:description => "Ruino", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 811)
Comune.create(:description => "San Cipriano Po", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 417)
Comune.create(:description => "San Damiano Al Colle", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 738)
Comune.create(:description => "San Genesio Ed Uniti", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 3396)
Comune.create(:description => "San Giorgio Di Lomellina", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 1202)
Comune.create(:description => "San Martino Siccomario", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 5055)
Comune.create(:description => "San Zenone Al Po", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 521)
Comune.create(:description => "Santa Cristina E Bissone", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 1853)
Comune.create(:description => "Santa Giuletta", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 1615)
Comune.create(:description => "Santa Margherita Di Staffora", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 617)
Comune.create(:description => "Santa Maria Della Versa", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 2584)
Comune.create(:description => "Sartirana Lomellina", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 1900)
Comune.create(:description => "Scaldasole", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 885)
Comune.create(:description => "Semiana", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 256)
Comune.create(:description => "Silvano Pietra", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 703)
Comune.create(:description => "Siziano", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 5226)
Comune.create(:description => "Sommo", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 1034)
Comune.create(:description => "Spessa", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 525)
Comune.create(:description => "Stradella", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 10763)
Comune.create(:description => "Suardi", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 703)
Comune.create(:description => "Torrazza Coste", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 1518)
Comune.create(:description => "Torre Beretti Castellaro", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Torrevecchia Pia", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 2515)
Comune.create(:description => "Torricella Verzate", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 802)
Comune.create(:description => "Trivolzio", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 1204)
Comune.create(:description => "Tromello", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 3409)
Comune.create(:description => "Trovo", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 647)
Comune.create(:description => "Val Di Nizza", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 688)
Comune.create(:description => "Valeggio", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 226)
Comune.create(:description => "Valle Lomellina", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 2229)
Comune.create(:description => "Valle Salimbene", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 1353)
Comune.create(:description => "Valverde", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 341)
Comune.create(:description => "Varzi", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 3539)
Comune.create(:description => "Velezzo Lomellina", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 103)
Comune.create(:description => "Vellezzo Bellini", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 2251)
Comune.create(:description => "Verretto", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 324)
Comune.create(:description => "Verrua Po", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 1323)
Comune.create(:description => "Vidigulfo", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 4231)
Comune.create(:description => "Vigevano", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 57450)
Comune.create(:description => "Villa Biscossi", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 73)
Comune.create(:description => "Villanterio", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 2657)
Comune.create(:description => "Vistarino", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 1118)
Comune.create(:description => "Voghera", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 38183)
Comune.create(:description => "Volpara", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 132)
Comune.create(:description => "Zavattarello", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 1129)
Comune.create(:description => "Zeccone", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 1158)
Comune.create(:description => "Zeme", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 1197)
Comune.create(:description => "Zenevredo", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 453)
Comune.create(:description => "Zerbo", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 466)
Comune.create(:description => "Zinasco", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 2950)
Comune.create(:description => "Bascape'", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 1504)
Comune.create(:description => "Bastida De' Dossi", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 199)
Comune.create(:description => "Castello D'Agogna", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 969)
Comune.create(:description => "Costa De' Nobili", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 370)
Comune.create(:description => "Gambolo'", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 8323)
Comune.create(:description => "Montu' Beccaria", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 1683)
Comune.create(:description => "Pietra De' Giorgi", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 875)
Comune.create(:description => "Rocca De' Giorgi", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 98)
Comune.create(:description => "Sannazzaro De' Burgondi", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 5802)
Comune.create(:description => "Sant'Alessio Con Vialone", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 372)
Comune.create(:description => "Sant'Angelo Lomellina", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 828)
Comune.create(:description => "Torre D'Arese", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 550)
Comune.create(:description => "Torre De' Negri", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 365)
Comune.create(:description => "Torre D'Isola", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 1857)
Comune.create(:description => "Travaco' Siccomario", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 3580)
Comune.create(:description => "Villanova D'Ardenghi", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 687)
Comune.create(:description => "Zerbolo'", :provincia_id => 98, :regione_id => 19, stato_id: 1, continente_id: 1 , :population => 1216)
