#encoding: utf-8
Comune.create(:description => "Ala", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Albiano", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Aldeno", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Amblar", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Andalo", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Arco", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Avio", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Bedollo", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Bersone", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Besenello", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Bezzecca", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Bleggio Inferiore", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Bleggio Superiore", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Bocenago", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Bolbeno", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Bondo", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Bondone", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Borgo Valsugana", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Bosentino", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Breguzzo", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Brentonico", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Bresimo", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Brez", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Brione", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 546)
Comune.create(:description => "Caderzone", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Calavino", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Calceranica Al Lago", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Caldes", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Caldonazzo", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Calliano", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Campitello Di Fassa", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Campodenno", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Canal San Bovo", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Canazei", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Capriana", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Carano", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Carisolo", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Carzano", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Castel Condino", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Castelfondo", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Castello Molina Di Fiemme", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Castello Tesino", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Castelnuovo", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Cavalese", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Cavareno", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Cavedago", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Cavedine", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Cavizzana", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Cembra", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Cimego", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Cimone", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Cinte Tesino", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Cis", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Civezzano", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Cles", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Cloz", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Commezzadura", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Concei", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Condino", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Coredo", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Croviana", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Cunevo", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Daiano", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Dambel", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Daone", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Denno", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Dimaro", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Don", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Dorsino", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Drena", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Dro", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Faedo", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Fai Della Paganella", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Faver", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Fiera Di Primiero", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Fierozzo", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Flavon", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Folgaria", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Fondo", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Fornace", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Frassilongo", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Garniga", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Giovo", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Giustino", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Grauno", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Grigno", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Grumes", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Imer", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Isera", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Ivano Fracena", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Lardaro", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Lasino", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Lavarone", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Lavis", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Levico Terme", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Lisignago", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Livo", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 208)
Comune.create(:description => "Lomaso", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Lona Lases", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Malosco", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Massimeno", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Mazzin", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Mezzana", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Mezzano", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Mezzocorona", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Mezzolombardo", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Moena", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Molina Di Ledro", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Molveno", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Monclassico", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Montagne", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Mori", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Nago Torbole", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Nanno", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Nave San Rocco", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Nogaredo", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Nomi", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Novaledo", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Ospedaletto", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Ossana", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Padergnone", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Peio", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Pellizzano", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Pelugo", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Pergine Valsugana", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Pieve Di Bono", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Pieve Di Ledro", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Pieve Tesino", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Pinzolo", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Pomarolo", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Pozza Di Fassa", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Praso", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Predazzo", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Preore", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Prezzo", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Rabbi", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Ragoli", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Riva Del Garda", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Romallo", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Romeno", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Roncegno", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Ronchi Valsugana", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Roncone", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Ronzo-Chienis", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Ronzone", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Rumo", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Sagron Mis", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Samone", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 1473)
Comune.create(:description => "San Lorenzo In Banale", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Sanzeno", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Sarnonico", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Scurelle", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Segonzano", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Sfruz", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Siror", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Smarano", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Soraga", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Sover", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Spera", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Spiazzo", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Spormaggiore", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Sporminore", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Stenico", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Storo", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Strembo", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Strigno", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Taio", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Tassullo", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Telve", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Telve Di Sopra", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Tenna", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Tenno", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Terlago", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Terragnolo", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Terres", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Terzolas", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Tesero", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Tiarno Di Sopra", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Tiarno Di Sotto", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Tione Di Trento", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Ton", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Tonadico", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Torcegno", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Trambileno", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Transacqua", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Trento", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Tres", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Tuenno", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Valda", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Valfloriana", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Vallarsa", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Varena", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Vattaro", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Vermiglio", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Vezzano", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Vignola Falesina", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Vigo Di Fassa", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Vigo Rendena", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Vigolo Vattaro", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Villa Agnedo", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Villa Lagarina", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Villa Rendena", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Volano", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Zambana", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Ziano Di Fiemme", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Zuclo", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Baselga Di Pine'", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Cagno'", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Centa San Nicolo'", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Dare'", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Fiave'", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Male'", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Palu' Del Fersina", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Panchia'", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Revo'", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Rovere' Della Luna", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Ruffre'", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "San Michele All'Adige", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Sant'Orsola", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Vervo'", :provincia_id => 101, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
