Comune.create(description: "Balzar", provincia_id: 127, region_id:  1, country_id: 53, continent_id: 2 , population: 28794)
Comune.create(description: "Daule", provincia_id: 127, region_id:  1, country_id: 53, continent_id: 2 , population: 65145)
Comune.create(description: "Eloy Alfaro (Durán)", provincia_id: 127, region_id:  1, country_id: 53, continent_id: 2 , population: 230839)
Comune.create(description: "El Triunfo", provincia_id: 127, region_id:  1, country_id: 53, continent_id: 2 , population: 34863)
Comune.create(description: "Guayaquil", provincia_id: 127, region_id:  1, country_id: 53, continent_id: 2 , population: 2278691)
Comune.create(description: "Lomas de Sargentillo", provincia_id: 127, region_id:  1, country_id: 53, continent_id: 2 , population: 13775)
Comune.create(description: "Milagro", provincia_id: 127, region_id:  1, country_id: 53, continent_id: 2 , population: 133508)
Comune.create(description: "Naranjal", provincia_id: 127, region_id:  1, country_id: 53, continent_id: 2 , population: 28487)
Comune.create(description: "Naranjito", provincia_id: 127, region_id:  1, country_id: 53, continent_id: 2 , population: 28546)
Comune.create(description: "Pedro Carbo", provincia_id: 127, region_id:  1, country_id: 53, continent_id: 2 , population: 20220)
Comune.create(description: "Playas (General Villamil)", provincia_id: 127, region_id:  1, country_id: 53, continent_id: 2 , population: 34409)
Comune.create(description: "Samborondón", provincia_id: 127, region_id:  1, country_id: 53, continent_id: 2 , population: 42637)
Comune.create(description: "Velasco Ibarra (El Empalme)", provincia_id: 127, region_id:  1, country_id: 53, continent_id: 2 , population: 35686)
Comune.create(description: "Yaguachi Nuevo (San Jacinto de Yaguachi)", provincia_id: 127, region_id:  1, country_id: 53, continent_id: 2 , population: 17806)
