Comune.create(description: "Agrigento", provincia_id: 12, region_id:  11, country_id: 1, continent_id: 1 , population: 54619)
Comune.create(description: "Alessandria Della Rocca", provincia_id: 12, region_id:  11, country_id: 1, continent_id: 1 , population: 3787)
Comune.create(description: "Aragona", provincia_id: 12, region_id:  11, country_id: 1, continent_id: 1 , population: 10065)
Comune.create(description: "Bivona", provincia_id: 12, region_id:  11, country_id: 1, continent_id: 1 , population: 4225)
Comune.create(description: "Burgio", provincia_id: 12, region_id:  11, country_id: 1, continent_id: 1 , population: 3157)
Comune.create(description: "Calamonaci", provincia_id: 12, region_id:  11, country_id: 1, continent_id: 1 , population: 1522)
Comune.create(description: "Caltabellotta", provincia_id: 12, region_id:  11, country_id: 1, continent_id: 1 , population: 4448)
Comune.create(description: "Camastra", provincia_id: 12, region_id:  11, country_id: 1, continent_id: 1 , population: 2185)
Comune.create(description: "Cammarata", provincia_id: 12, region_id:  11, country_id: 1, continent_id: 1 , population: 6403)
Comune.create(description: "Campobello Di Licata", provincia_id: 12, region_id:  11, country_id: 1, continent_id: 1 , population: 11075)
Comune.create(description: "Casteltermini", provincia_id: 12, region_id:  11, country_id: 1, continent_id: 1 , population: 8782)
Comune.create(description: "Castrofilippo", provincia_id: 12, region_id:  11, country_id: 1, continent_id: 1 , population: 3247)
Comune.create(description: "Cattolica Eraclea", provincia_id: 12, region_id:  11, country_id: 1, continent_id: 1 , population: 4959)
Comune.create(description: "Cianciana", provincia_id: 12, region_id:  11, country_id: 1, continent_id: 1 , population: 4073)
Comune.create(description: "Comitini", provincia_id: 12, region_id:  11, country_id: 1, continent_id: 1 , population: 955)
Comune.create(description: "Favara", provincia_id: 12, region_id:  11, country_id: 1, continent_id: 1 , population: 31098)
Comune.create(description: "Grotte", provincia_id: 12, region_id:  11, country_id: 1, continent_id: 1 , population: 6208)
Comune.create(description: "Joppolo Giancaxio", provincia_id: 12, region_id:  11, country_id: 1, continent_id: 1 , population: 1286)
Comune.create(description: "Lampedusa E Linosa", provincia_id: 12, region_id:  11, country_id: 1, continent_id: 1 , population: 5725)
Comune.create(description: "Licata", provincia_id: 12, region_id:  11, country_id: 1, continent_id: 1 , population: 37976)
Comune.create(description: "Lucca Sicula", provincia_id: 12, region_id:  11, country_id: 1, continent_id: 1 , population: 2090)
Comune.create(description: "Menfi", provincia_id: 12, region_id:  11, country_id: 1, continent_id: 1 , population: 12783)
Comune.create(description: "Montallegro", provincia_id: 12, region_id:  11, country_id: 1, continent_id: 1 , population: 2732)
Comune.create(description: "Montevago", provincia_id: 12, region_id:  11, country_id: 1, continent_id: 1 , population: 3108)
Comune.create(description: "Naro", provincia_id: 12, region_id:  11, country_id: 1, continent_id: 1 , population: 8770)
Comune.create(description: "Palma Di Montechiaro", provincia_id: 12, region_id:  11, country_id: 1, continent_id: 1 , population: 21563)
Comune.create(description: "Porto Empedocle", provincia_id: 12, region_id:  11, country_id: 1, continent_id: 1 , population: 15957)
Comune.create(description: "Racalmuto", provincia_id: 12, region_id:  11, country_id: 1, continent_id: 1 , population: 10051)
Comune.create(description: "Raffadali", provincia_id: 12, region_id:  11, country_id: 1, continent_id: 1 , population: 13336)
Comune.create(description: "Ravanusa", provincia_id: 12, region_id:  11, country_id: 1, continent_id: 1 , population: 14115)
Comune.create(description: "Realmonte", provincia_id: 12, region_id:  11, country_id: 1, continent_id: 1 , population: 4435)
Comune.create(description: "Ribera", provincia_id: 12, region_id:  11, country_id: 1, continent_id: 1 , population: 20186)
Comune.create(description: "Sambuca Di Sicilia", provincia_id: 12, region_id:  11, country_id: 1, continent_id: 1 , population: 6158)
Comune.create(description: "San Biagio Platani", provincia_id: 12, region_id:  11, country_id: 1, continent_id: 1 , population: 3785)
Comune.create(description: "San Giovanni Gemini", provincia_id: 12, region_id:  11, country_id: 1, continent_id: 1 , population: 8169)
Comune.create(description: "Santa Elisabetta", provincia_id: 12, region_id:  11, country_id: 1, continent_id: 1 , population: 3073)
Comune.create(description: "Santa Margherita Di Belice", provincia_id: 12, region_id:  11, country_id: 1, continent_id: 1 , population: 6564)
Comune.create(description: "Santo Stefano Quisquina", provincia_id: 12, region_id:  11, country_id: 1, continent_id: 1 , population: 5405)
Comune.create(description: "Sciacca", provincia_id: 12, region_id:  11, country_id: 1, continent_id: 1 , population: 40240)
Comune.create(description: "Siculiana", provincia_id: 12, region_id:  11, country_id: 1, continent_id: 1 , population: 4786)
Comune.create(description: "Villafranca Sicula", provincia_id: 12, region_id:  11, country_id: 1, continent_id: 1 , population: 1509)
Comune.create(description: "Canicatti'", provincia_id: 12, region_id:  11, country_id: 1, continent_id: 1 , population: 31713)
Comune.create(description: "Sant'Angelo Muxaro", provincia_id: 12, region_id:  11, country_id: 1, continent_id: 1 , population: 1730)
