#encoding: utf-8
Comune.create(:description => "Arzana", :provincia_id => 107, :regione_id => 10, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Bari Sardo", :provincia_id => 107, :regione_id => 10, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Baunei", :provincia_id => 107, :regione_id => 10, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Cardedu", :provincia_id => 107, :regione_id => 10, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Elini", :provincia_id => 107, :regione_id => 10, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Gairo", :provincia_id => 107, :regione_id => 10, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Girasole", :provincia_id => 107, :regione_id => 10, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Ilbono", :provincia_id => 107, :regione_id => 10, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Jerzu", :provincia_id => 107, :regione_id => 10, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Lanusei", :provincia_id => 107, :regione_id => 10, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Loceri", :provincia_id => 107, :regione_id => 10, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Lotzorai", :provincia_id => 107, :regione_id => 10, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Osini", :provincia_id => 107, :regione_id => 10, stato_id: 1, continente_id: 1 , :population => 1199)
Comune.create(:description => "Perdasdefogu", :provincia_id => 107, :regione_id => 10, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Seui", :provincia_id => 107, :regione_id => 10, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Talana", :provincia_id => 107, :regione_id => 10, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Tertenia", :provincia_id => 107, :regione_id => 10, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Triei", :provincia_id => 107, :regione_id => 10, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Ulassai", :provincia_id => 107, :regione_id => 10, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Urzulei", :provincia_id => 107, :regione_id => 10, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Ussassai", :provincia_id => 107, :regione_id => 10, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Villagrande Strisaili", :provincia_id => 107, :regione_id => 10, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Tortoli'", :provincia_id => 107, :regione_id => 10, stato_id: 1, continente_id: 1 , :population => 3021)
