Comune.create(description: "Acquaviva Platani", province_id: 13, region_id:  11, country_id: 1, continent_id: 1 , population: 1231)
Comune.create(description: "Bompensiere", province_id: 13, region_id:  11, country_id: 1, continent_id: 1 , population: 677)
Comune.create(description: "Butera", province_id: 13, region_id:  11, country_id: 1, continent_id: 1 , population: 5376)
Comune.create(description: "Caltanissetta", province_id: 13, region_id:  11, country_id: 1, continent_id: 1 , population: 61438)
Comune.create(description: "Campofranco", province_id: 13, region_id:  11, country_id: 1, continent_id: 1 , population: 3632)
Comune.create(description: "Delia", province_id: 13, region_id:  11, country_id: 1, continent_id: 1 , population: 4350)
Comune.create(description: "Gela", province_id: 13, region_id:  11, country_id: 1, continent_id: 1 , population: 72774)
Comune.create(description: "Marianopoli", province_id: 13, region_id:  11, country_id: 1, continent_id: 1 , population: 2362)
Comune.create(description: "Mazzarino", province_id: 13, region_id:  11, country_id: 1, continent_id: 1 , population: 12627)
Comune.create(description: "Milena", province_id: 13, region_id:  11, country_id: 1, continent_id: 1 , population: 3446)
Comune.create(description: "Montedoro", province_id: 13, region_id:  11, country_id: 1, continent_id: 1 , population: 1780)
Comune.create(description: "Mussomeli", province_id: 13, region_id:  11, country_id: 1, continent_id: 1 , population: 11547)
Comune.create(description: "Niscemi", province_id: 13, region_id:  11, country_id: 1, continent_id: 1 , population: 27641)
Comune.create(description: "Resuttano", province_id: 13, region_id:  11, country_id: 1, continent_id: 1 , population: 2467)
Comune.create(description: "Riesi", province_id: 13, region_id:  11, country_id: 1, continent_id: 1 , population: 11746)
Comune.create(description: "San Cataldo", province_id: 13, region_id:  11, country_id: 1, continent_id: 1 , population: 23154)
Comune.create(description: "Santa Caterina Villarmosa", province_id: 13, region_id:  11, country_id: 1, continent_id: 1 , population: 6087)
Comune.create(description: "Serradifalco", province_id: 13, region_id:  11, country_id: 1, continent_id: 1 , population: 6423)
Comune.create(description: "Sommatino", province_id: 13, region_id:  11, country_id: 1, continent_id: 1 , population: 7875)
Comune.create(description: "Sutera", province_id: 13, region_id:  11, country_id: 1, continent_id: 1 , population: 1641)
Comune.create(description: "Vallelunga Pratameno", province_id: 13, region_id:  11, country_id: 1, continent_id: 1 , population: 3845)
Comune.create(description: "Villalba", province_id: 13, region_id:  11, country_id: 1, continent_id: 1 , population: 1916)
