Comune.create(description: "Acquaviva Platani", provincia_id: 13, region_id:  11, country_id: 1, continent_id: 1 , population: 1231)
Comune.create(description: "Bompensiere", provincia_id: 13, region_id:  11, country_id: 1, continent_id: 1 , population: 677)
Comune.create(description: "Butera", provincia_id: 13, region_id:  11, country_id: 1, continent_id: 1 , population: 5376)
Comune.create(description: "Caltanissetta", provincia_id: 13, region_id:  11, country_id: 1, continent_id: 1 , population: 61438)
Comune.create(description: "Campofranco", provincia_id: 13, region_id:  11, country_id: 1, continent_id: 1 , population: 3632)
Comune.create(description: "Delia", provincia_id: 13, region_id:  11, country_id: 1, continent_id: 1 , population: 4350)
Comune.create(description: "Gela", provincia_id: 13, region_id:  11, country_id: 1, continent_id: 1 , population: 72774)
Comune.create(description: "Marianopoli", provincia_id: 13, region_id:  11, country_id: 1, continent_id: 1 , population: 2362)
Comune.create(description: "Mazzarino", provincia_id: 13, region_id:  11, country_id: 1, continent_id: 1 , population: 12627)
Comune.create(description: "Milena", provincia_id: 13, region_id:  11, country_id: 1, continent_id: 1 , population: 3446)
Comune.create(description: "Montedoro", provincia_id: 13, region_id:  11, country_id: 1, continent_id: 1 , population: 1780)
Comune.create(description: "Mussomeli", provincia_id: 13, region_id:  11, country_id: 1, continent_id: 1 , population: 11547)
Comune.create(description: "Niscemi", provincia_id: 13, region_id:  11, country_id: 1, continent_id: 1 , population: 27641)
Comune.create(description: "Resuttano", provincia_id: 13, region_id:  11, country_id: 1, continent_id: 1 , population: 2467)
Comune.create(description: "Riesi", provincia_id: 13, region_id:  11, country_id: 1, continent_id: 1 , population: 11746)
Comune.create(description: "San Cataldo", provincia_id: 13, region_id:  11, country_id: 1, continent_id: 1 , population: 23154)
Comune.create(description: "Santa Caterina Villarmosa", provincia_id: 13, region_id:  11, country_id: 1, continent_id: 1 , population: 6087)
Comune.create(description: "Serradifalco", provincia_id: 13, region_id:  11, country_id: 1, continent_id: 1 , population: 6423)
Comune.create(description: "Sommatino", provincia_id: 13, region_id:  11, country_id: 1, continent_id: 1 , population: 7875)
Comune.create(description: "Sutera", provincia_id: 13, region_id:  11, country_id: 1, continent_id: 1 , population: 1641)
Comune.create(description: "Vallelunga Pratameno", provincia_id: 13, region_id:  11, country_id: 1, continent_id: 1 , population: 3845)
Comune.create(description: "Villalba", provincia_id: 13, region_id:  11, country_id: 1, continent_id: 1 , population: 1916)
