Municipality.create(description: "Aci Bonaccorsi", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 2549)
Municipality.create(description: "Aci Castello", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 18272)
Municipality.create(description: "Aci Catena", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 27058)
Municipality.create(description: "Acireale", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 50190)
Municipality.create(description: "Adrano", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 34490)
Municipality.create(description: "Belpasso", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 20358)
Municipality.create(description: "Biancavilla", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 22477)
Municipality.create(description: "Bronte", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 18512)
Municipality.create(description: "Calatabiano", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 5215)
Municipality.create(description: "Caltagirone", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 37373)
Municipality.create(description: "Camporotondo Etneo", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 3007)
Municipality.create(description: "Castel Di Iudica", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 4694)
Municipality.create(description: "Castiglione Di Sicilia", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 3746)
Municipality.create(description: "Catania", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 313110)
Municipality.create(description: "Fiumefreddo Di Sicilia", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 9602)
Municipality.create(description: "Giarre", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 26357)
Municipality.create(description: "Grammichele", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 13395)
Municipality.create(description: "Gravina Di Catania", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 27343)
Municipality.create(description: "Licodia Eubea", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 3161)
Municipality.create(description: "Linguaglossa", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 5432)
Municipality.create(description: "Maletto", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 4032)
Municipality.create(description: "Maniace", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 3543)
Municipality.create(description: "Mascali", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 11122)
Municipality.create(description: "Mascalucia", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 24483)
Municipality.create(description: "Mazzarrone", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 3685)
Municipality.create(description: "Militello In Val Di Catania", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 8204)
Municipality.create(description: "Milo", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 1104)
Municipality.create(description: "Mineo", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 5586)
Municipality.create(description: "Mirabella Imbaccari", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 6331)
Municipality.create(description: "Misterbianco", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 43995)
Municipality.create(description: "Nicolosi", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 6197)
Municipality.create(description: "Palagonia", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 16568)
Municipality.create(description: "Pedara", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 10062)
Municipality.create(description: "Piedimonte Etneo", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 3664)
Municipality.create(description: "Raddusa", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 3535)
Municipality.create(description: "Ragalna", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 3691)
Municipality.create(description: "Ramacca", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 10459)
Municipality.create(description: "Randazzo", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 11223)
Municipality.create(description: "Riposto", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 13951)
Municipality.create(description: "San Cono", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 2961)
Municipality.create(description: "San Giovanni La Punta", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 20850)
Municipality.create(description: "San Gregorio Di Catania", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 10366)
Municipality.create(description: "San Michele Di Ganzaria", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 4749)
Municipality.create(description: "San Pietro Clarenza", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 5863)
Municipality.create(description: "Santa Maria Di Licodia", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 6760)
Municipality.create(description: "Santa Venerina", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 7901)
Municipality.create(description: "Scordia", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 17022)
Municipality.create(description: "Trecastagni", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 8212)
Municipality.create(description: "Tremestieri Etneo", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 20442)
Municipality.create(description: "Valverde", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 341)
Municipality.create(description: "Viagrande", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 6591)
Municipality.create(description: "Vizzini", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 7105)
Municipality.create(description: "Zafferana Etnea", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 8139)
Municipality.create(description: "Aci Sant'Antonio", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 15389)
Municipality.create(description: "Motta Sant'Anastasia", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 10244)
Municipality.create(description: "Paterno'", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 45725)
Municipality.create(description: "Sant'Agata Li Battiati", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 10378)
Municipality.create(description: "Sant'Alfio", province_id: 14, region_id:  11, country_id: 1, continent_id: 1 , population: 1647)
