Comune.create(description: "Aci Bonaccorsi", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 2549)
Comune.create(description: "Aci Castello", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 18272)
Comune.create(description: "Aci Catena", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 27058)
Comune.create(description: "Acireale", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 50190)
Comune.create(description: "Adrano", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 34490)
Comune.create(description: "Belpasso", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 20358)
Comune.create(description: "Biancavilla", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 22477)
Comune.create(description: "Bronte", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 18512)
Comune.create(description: "Calatabiano", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 5215)
Comune.create(description: "Caltagirone", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 37373)
Comune.create(description: "Camporotondo Etneo", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 3007)
Comune.create(description: "Castel Di Iudica", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 4694)
Comune.create(description: "Castiglione Di Sicilia", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 3746)
Comune.create(description: "Catania", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 313110)
Comune.create(description: "Fiumefreddo Di Sicilia", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 9602)
Comune.create(description: "Giarre", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 26357)
Comune.create(description: "Grammichele", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 13395)
Comune.create(description: "Gravina Di Catania", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 27343)
Comune.create(description: "Licodia Eubea", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 3161)
Comune.create(description: "Linguaglossa", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 5432)
Comune.create(description: "Maletto", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 4032)
Comune.create(description: "Maniace", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 3543)
Comune.create(description: "Mascali", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 11122)
Comune.create(description: "Mascalucia", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 24483)
Comune.create(description: "Mazzarrone", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 3685)
Comune.create(description: "Militello In Val Di Catania", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 8204)
Comune.create(description: "Milo", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 1104)
Comune.create(description: "Mineo", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 5586)
Comune.create(description: "Mirabella Imbaccari", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 6331)
Comune.create(description: "Misterbianco", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 43995)
Comune.create(description: "Nicolosi", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 6197)
Comune.create(description: "Palagonia", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 16568)
Comune.create(description: "Pedara", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 10062)
Comune.create(description: "Piedimonte Etneo", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 3664)
Comune.create(description: "Raddusa", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 3535)
Comune.create(description: "Ragalna", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 3691)
Comune.create(description: "Ramacca", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 10459)
Comune.create(description: "Randazzo", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 11223)
Comune.create(description: "Riposto", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 13951)
Comune.create(description: "San Cono", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 2961)
Comune.create(description: "San Giovanni La Punta", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 20850)
Comune.create(description: "San Gregorio Di Catania", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 10366)
Comune.create(description: "San Michele Di Ganzaria", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 4749)
Comune.create(description: "San Pietro Clarenza", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 5863)
Comune.create(description: "Santa Maria Di Licodia", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 6760)
Comune.create(description: "Santa Venerina", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 7901)
Comune.create(description: "Scordia", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 17022)
Comune.create(description: "Trecastagni", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 8212)
Comune.create(description: "Tremestieri Etneo", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 20442)
Comune.create(description: "Valverde", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 341)
Comune.create(description: "Viagrande", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 6591)
Comune.create(description: "Vizzini", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 7105)
Comune.create(description: "Zafferana Etnea", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 8139)
Comune.create(description: "Aci Sant'Antonio", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 15389)
Comune.create(description: "Motta Sant'Anastasia", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 10244)
Comune.create(description: "Paterno'", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 45725)
Comune.create(description: "Sant'Agata Li Battiati", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 10378)
Comune.create(description: "Sant'Alfio", provincia_id: 14, regione_id: 11, country_id: 1, continent_id: 1 , population: 1647)
