#encoding: utf-8
Comune.create(:description => "Parcines", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Perca", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Plaus", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Aldino", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Andriano", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Anterivo", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Appiano Sulla Strada Del Vino", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Avelengo", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Badia", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Barbiano", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Bolzano", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Braies", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Brennero", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Bressanone", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Bronzolo", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Brunico", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Caines", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Caldaro Strada Del Vino", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Campo Di Trens", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Campo Tures", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Castelbello Ciardes", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Castelrotto", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Cermes", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Chienes", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Chiusa", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Cortaccia Sulla Strada Del Vino", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Cortina Sulla Strada Del Vino", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Corvara In Badia", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Curon Venosta", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Dobbiaco", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Egna", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Falzes", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Fortezza", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Funes", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Gais", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Gargazzone", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Glorenza", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "La Valle", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Laces", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Lagundo", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Laion", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Laives", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Lana", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Lasa", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Lauregno", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Luson", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Malles Venosta", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Marebbe", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Marlengo", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Martello", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Meltina", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Merano", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Monguelfo", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Montagna", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Moso In Passiria", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Nalles", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Naturno", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Naz Sciaves", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Nova Levante", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Nova Ponente", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Ora", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Ortisei", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Ponte Gardena", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Postal", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Prato Allo Stelvio", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Predoi", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Proves", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Racines", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Rasun Anterselva", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Renon", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Rifiano", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Rio Di Pusteria", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Salorno", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "San Candido", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "San Genesio Atesino", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "San Leonardo In Passiria", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "San Lorenzo Di Sebato", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "San Martino In Badia", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "San Martino In Passiria", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "San Pancrazio", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Santa Cristina Valgardena", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Sarentino", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Scena", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Selva Dei Molini", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Selva Di Val Gardena", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Senale San Felice", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Senales", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Sesto", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Silandro", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Sluderno", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Stelvio", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Terento", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Terlano", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Termeno Sulla Strada Del Vino", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Tesimo", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Tires", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Tirolo", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Trodena", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Tubre", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Ultimo", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Vadena", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Val Di Vizze", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Valdaora", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Valle Aurina", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Valle Di Casies", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Vandoies", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Varna", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Velturno", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Verano", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Villabassa", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Villandro", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Vipiteno", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Cornedo All'Isarco", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Fie' Allo Sciliar", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Magre' Sulla Strada Del Vino", :provincia_id => 102, :regione_id => 5, stato_id: 1, continente_id: 1 )
