Municipality.create(description: "Agira", province_id: 15, region_id:  11, country_id: 1, continent_id: 1 , population: 8348)
Municipality.create(description: "Aidone", province_id: 15, region_id:  11, country_id: 1, continent_id: 1 , population: 6057)
Municipality.create(description: "Assoro", province_id: 15, region_id:  11, country_id: 1, continent_id: 1 , population: 5393)
Municipality.create(description: "Barrafranca", province_id: 15, region_id:  11, country_id: 1, continent_id: 1 , population: 13115)
Municipality.create(description: "Calascibetta", province_id: 15, region_id:  11, country_id: 1, continent_id: 1 , population: 4829)
Municipality.create(description: "Catenanuova", province_id: 15, region_id:  11, country_id: 1, continent_id: 1 , population: 4876)
Municipality.create(description: "Centuripe", province_id: 15, region_id:  11, country_id: 1, continent_id: 1 , population: 5903)
Municipality.create(description: "Cerami", province_id: 15, region_id:  11, country_id: 1, continent_id: 1 , population: 2462)
Municipality.create(description: "Enna", province_id: 15, region_id:  11, country_id: 1, continent_id: 1 , population: 28983)
Municipality.create(description: "Gagliano Castelferrato", province_id: 15, region_id:  11, country_id: 1, continent_id: 1 , population: 3772)
Municipality.create(description: "Leonforte", province_id: 15, region_id:  11, country_id: 1, continent_id: 1 , population: 14145)
Municipality.create(description: "Nicosia", province_id: 15, region_id:  11, country_id: 1, continent_id: 1 , population: 14812)
Municipality.create(description: "Nissoria", province_id: 15, region_id:  11, country_id: 1, continent_id: 1 , population: 3014)
Municipality.create(description: "Piazza Armerina", province_id: 15, region_id:  11, country_id: 1, continent_id: 1 , population: 21038)
Municipality.create(description: "Pietraperzia", province_id: 15, region_id:  11, country_id: 1, continent_id: 1 , population: 7340)
Municipality.create(description: "Regalbuto", province_id: 15, region_id:  11, country_id: 1, continent_id: 1 , population: 7744)
Municipality.create(description: "Sperlinga", province_id: 15, region_id:  11, country_id: 1, continent_id: 1 , population: 963)
Municipality.create(description: "Troina", province_id: 15, region_id:  11, country_id: 1, continent_id: 1 , population: 10061)
Municipality.create(description: "Valguarnera Caropepe", province_id: 15, region_id:  11, country_id: 1, continent_id: 1 , population: 8649)
Municipality.create(description: "Villarosa", province_id: 15, region_id:  11, country_id: 1, continent_id: 1 , population: 5696)
