Municipality.create(description: "Acquedolci", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 5373)
Municipality.create(description: "Alcara Li Fusi", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 2473)
Municipality.create(description: "Antillo", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1128)
Municipality.create(description: "Barcellona Pozzo Di Gotto", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 41258)
Municipality.create(description: "Brolo", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 5495)
Municipality.create(description: "Capizzi", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 3564)
Municipality.create(description: "Capri Leone", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 4016)
Municipality.create(description: "Caronia", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 3589)
Municipality.create(description: "Casalvecchio Siculo", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1152)
Municipality.create(description: "Castel Di Lucio", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1561)
Municipality.create(description: "Castelmola", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1092)
Municipality.create(description: "Castroreale", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 2910)
Municipality.create(description: "Falcone", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 2858)
Municipality.create(description: "Ficarra", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1803)
Municipality.create(description: "Fiumedinisi", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1679)
Municipality.create(description: "Floresta", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 637)
Municipality.create(description: "Fondachelli Fantina", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 )
Municipality.create(description: "Francavilla Di Sicilia", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 4347)
Municipality.create(description: "Furci Siculo", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 3285)
Municipality.create(description: "Furnari", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 3394)
Municipality.create(description: "Gaggi", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 2693)
Municipality.create(description: "Galati Mamertino", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 3127)
Municipality.create(description: "Gallodoro", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 409)
Municipality.create(description: "Giardini Naxos", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 )
Municipality.create(description: "Gioiosa Marea", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 7245)
Municipality.create(description: "Graniti", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1587)
Municipality.create(description: "Itala", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1692)
Municipality.create(description: "Leni", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 641)
Municipality.create(description: "Letojanni", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 2480)
Municipality.create(description: "Librizzi", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1908)
Municipality.create(description: "Limina", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1006)
Municipality.create(description: "Lipari", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 10554)
Municipality.create(description: "Longi", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1653)
Municipality.create(description: "Malfa", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 851)
Municipality.create(description: "Malvagna", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 973)
Municipality.create(description: "Mandanici", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 761)
Municipality.create(description: "Messina", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 252026)
Municipality.create(description: "Milazzo", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 32108)
Municipality.create(description: "Militello Rosmarino", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1445)
Municipality.create(description: "Mirto", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1104)
Municipality.create(description: "Mistretta", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 5541)
Municipality.create(description: "Moio Alcantara", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 805)
Municipality.create(description: "Monforte San Giorgio", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 3088)
Municipality.create(description: "Mongiuffi Melia", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 783)
Municipality.create(description: "Montagnareale", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1787)
Municipality.create(description: "Montalbano Elicona", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 2838)
Municipality.create(description: "Motta Camastra", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 867)
Municipality.create(description: "Naso", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 4512)
Municipality.create(description: "Nizza Di Sicilia", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 3586)
Municipality.create(description: "Novara Di Sicilia", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1731)
Municipality.create(description: "Oliveri", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 2099)
Municipality.create(description: "Pace Del Mela", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 6117)
Municipality.create(description: "Pagliara", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1237)
Municipality.create(description: "Patti", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 13108)
Municipality.create(description: "Pettineo", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1547)
Municipality.create(description: "Piraino", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 3803)
Municipality.create(description: "Raccuja", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1389)
Municipality.create(description: "Reitano", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 951)
Municipality.create(description: "Roccafiorita", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 254)
Municipality.create(description: "Roccalumera", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 4029)
Municipality.create(description: "Roccavaldina", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1172)
Municipality.create(description: "Roccella Valdemone", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 841)
Municipality.create(description: "Rometta", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 6307)
Municipality.create(description: "San Filippo Del Mela", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 6952)
Municipality.create(description: "San Fratello", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 4561)
Municipality.create(description: "San Pier Niceto", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 3085)
Municipality.create(description: "San Piero Patti", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 3511)
Municipality.create(description: "San Salvatore Di Fitalia", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1679)
Municipality.create(description: "San Teodoro", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Santa Domenica Vittoria", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1173)
Municipality.create(description: "Santa Lucia Del Mela", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 4701)
Municipality.create(description: "Santa Marina Salina", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 808)
Municipality.create(description: "Santa Teresa Di Riva", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 8925)
Municipality.create(description: "Santo Stefano Di Camastra", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 4653)
Municipality.create(description: "Saponara", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 4131)
Municipality.create(description: "Savoca", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1675)
Municipality.create(description: "Scaletta Zanclea", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 2578)
Municipality.create(description: "Sinagra", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 3041)
Municipality.create(description: "Spadafora", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 5234)
Municipality.create(description: "Taormina", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 10780)
Municipality.create(description: "Terme Vigliatore", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 6561)
Municipality.create(description: "Torregrotta", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 6542)
Municipality.create(description: "Torrenova", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 3103)
Municipality.create(description: "Tortorici", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 7535)
Municipality.create(description: "Tripi", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1044)
Municipality.create(description: "Tusa", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 3358)
Municipality.create(description: "Ucria", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1370)
Municipality.create(description: "Valdina", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1209)
Municipality.create(description: "Venetico", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 3691)
Municipality.create(description: "Villafranca Tirrena", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 8517)
Municipality.create(description: "Ali'", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 933)
Municipality.create(description: "Ali' Terme", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 2569)
Municipality.create(description: "Basico'", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 746)
Municipality.create(description: "Capo D'Orlando", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 12710)
Municipality.create(description: "Castell'Umberto", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 3564)
Municipality.create(description: "Cesaro'", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 2815)
Municipality.create(description: "Condro'", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 523)
Municipality.create(description: "Forza D'Agro'", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 864)
Municipality.create(description: "Frazzano'", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 959)
Municipality.create(description: "Gualtieri Sicamino'", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 2018)
Municipality.create(description: "Mazzarra' Sant'Andrea", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1755)
Municipality.create(description: "Meri'", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 2186)
Municipality.create(description: "Motta D'Affermo", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 954)
Municipality.create(description: "Rodi' Milici", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 2335)
Municipality.create(description: "San Marco D'Alunzio", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 2202)
Municipality.create(description: "Sant'Agata Di Militello", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 12876)
Municipality.create(description: "Sant'Alessio Siculo", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1346)
Municipality.create(description: "Sant'Angelo Di Brolo", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 3856)
