Comune.create(description: "Acquedolci", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 5373)
Comune.create(description: "Alcara Li Fusi", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 2473)
Comune.create(description: "Antillo", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1128)
Comune.create(description: "Barcellona Pozzo Di Gotto", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 41258)
Comune.create(description: "Brolo", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 5495)
Comune.create(description: "Capizzi", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 3564)
Comune.create(description: "Capri Leone", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 4016)
Comune.create(description: "Caronia", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 3589)
Comune.create(description: "Casalvecchio Siculo", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1152)
Comune.create(description: "Castel Di Lucio", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1561)
Comune.create(description: "Castelmola", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1092)
Comune.create(description: "Castroreale", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 2910)
Comune.create(description: "Falcone", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 2858)
Comune.create(description: "Ficarra", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1803)
Comune.create(description: "Fiumedinisi", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1679)
Comune.create(description: "Floresta", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 637)
Comune.create(description: "Fondachelli Fantina", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 )
Comune.create(description: "Francavilla Di Sicilia", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 4347)
Comune.create(description: "Furci Siculo", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 3285)
Comune.create(description: "Furnari", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 3394)
Comune.create(description: "Gaggi", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 2693)
Comune.create(description: "Galati Mamertino", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 3127)
Comune.create(description: "Gallodoro", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 409)
Comune.create(description: "Giardini Naxos", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 )
Comune.create(description: "Gioiosa Marea", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 7245)
Comune.create(description: "Graniti", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1587)
Comune.create(description: "Itala", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1692)
Comune.create(description: "Leni", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 641)
Comune.create(description: "Letojanni", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 2480)
Comune.create(description: "Librizzi", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1908)
Comune.create(description: "Limina", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1006)
Comune.create(description: "Lipari", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 10554)
Comune.create(description: "Longi", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1653)
Comune.create(description: "Malfa", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 851)
Comune.create(description: "Malvagna", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 973)
Comune.create(description: "Mandanici", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 761)
Comune.create(description: "Messina", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 252026)
Comune.create(description: "Milazzo", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 32108)
Comune.create(description: "Militello Rosmarino", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1445)
Comune.create(description: "Mirto", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1104)
Comune.create(description: "Mistretta", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 5541)
Comune.create(description: "Moio Alcantara", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 805)
Comune.create(description: "Monforte San Giorgio", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 3088)
Comune.create(description: "Mongiuffi Melia", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 783)
Comune.create(description: "Montagnareale", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1787)
Comune.create(description: "Montalbano Elicona", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 2838)
Comune.create(description: "Motta Camastra", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 867)
Comune.create(description: "Naso", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 4512)
Comune.create(description: "Nizza Di Sicilia", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 3586)
Comune.create(description: "Novara Di Sicilia", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1731)
Comune.create(description: "Oliveri", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 2099)
Comune.create(description: "Pace Del Mela", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 6117)
Comune.create(description: "Pagliara", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1237)
Comune.create(description: "Patti", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 13108)
Comune.create(description: "Pettineo", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1547)
Comune.create(description: "Piraino", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 3803)
Comune.create(description: "Raccuja", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1389)
Comune.create(description: "Reitano", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 951)
Comune.create(description: "Roccafiorita", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 254)
Comune.create(description: "Roccalumera", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 4029)
Comune.create(description: "Roccavaldina", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1172)
Comune.create(description: "Roccella Valdemone", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 841)
Comune.create(description: "Rometta", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 6307)
Comune.create(description: "San Filippo Del Mela", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 6952)
Comune.create(description: "San Fratello", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 4561)
Comune.create(description: "San Pier Niceto", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 3085)
Comune.create(description: "San Piero Patti", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 3511)
Comune.create(description: "San Salvatore Di Fitalia", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1679)
Comune.create(description: "San Teodoro", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Santa Domenica Vittoria", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1173)
Comune.create(description: "Santa Lucia Del Mela", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 4701)
Comune.create(description: "Santa Marina Salina", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 808)
Comune.create(description: "Santa Teresa Di Riva", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 8925)
Comune.create(description: "Santo Stefano Di Camastra", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 4653)
Comune.create(description: "Saponara", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 4131)
Comune.create(description: "Savoca", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1675)
Comune.create(description: "Scaletta Zanclea", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 2578)
Comune.create(description: "Sinagra", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 3041)
Comune.create(description: "Spadafora", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 5234)
Comune.create(description: "Taormina", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 10780)
Comune.create(description: "Terme Vigliatore", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 6561)
Comune.create(description: "Torregrotta", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 6542)
Comune.create(description: "Torrenova", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 3103)
Comune.create(description: "Tortorici", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 7535)
Comune.create(description: "Tripi", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1044)
Comune.create(description: "Tusa", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 3358)
Comune.create(description: "Ucria", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1370)
Comune.create(description: "Valdina", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1209)
Comune.create(description: "Venetico", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 3691)
Comune.create(description: "Villafranca Tirrena", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 8517)
Comune.create(description: "Ali'", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 933)
Comune.create(description: "Ali' Terme", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 2569)
Comune.create(description: "Basico'", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 746)
Comune.create(description: "Capo D'Orlando", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 12710)
Comune.create(description: "Castell'Umberto", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 3564)
Comune.create(description: "Cesaro'", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 2815)
Comune.create(description: "Condro'", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 523)
Comune.create(description: "Forza D'Agro'", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 864)
Comune.create(description: "Frazzano'", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 959)
Comune.create(description: "Gualtieri Sicamino'", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 2018)
Comune.create(description: "Mazzarra' Sant'Andrea", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1755)
Comune.create(description: "Meri'", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 2186)
Comune.create(description: "Motta D'Affermo", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 954)
Comune.create(description: "Rodi' Milici", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 2335)
Comune.create(description: "San Marco D'Alunzio", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 2202)
Comune.create(description: "Sant'Agata Di Militello", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 12876)
Comune.create(description: "Sant'Alessio Siculo", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 1346)
Comune.create(description: "Sant'Angelo Di Brolo", province_id: 16, region_id:  11, country_id: 1, continent_id: 1 , population: 3856)
