Comune.create(description: "Alia", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 4184)
Comune.create(description: "Alimena", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 2494)
Comune.create(description: "Aliminusa", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 1363)
Comune.create(description: "Altavilla Milicia", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 5252)
Comune.create(description: "Altofonte", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 9193)
Comune.create(description: "Bagheria", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 50854)
Comune.create(description: "Balestrate", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 5693)
Comune.create(description: "Baucina", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 2031)
Comune.create(description: "Belmonte Mezzagno", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 10322)
Comune.create(description: "Bisacquino", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 5205)
Comune.create(description: "Blufi", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 1208)
Comune.create(description: "Bolognetta", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 3472)
Comune.create(description: "Bompietro", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 1754)
Comune.create(description: "Borgetto", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 6242)
Comune.create(description: "Caccamo", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 8524)
Comune.create(description: "Caltavuturo", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 4570)
Comune.create(description: "Campofelice Di Fitalia", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 609)
Comune.create(description: "Campofelice Di Roccella", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 5748)
Comune.create(description: "Campofiorito", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 1401)
Comune.create(description: "Camporeale", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 3716)
Comune.create(description: "Capaci", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 10164)
Comune.create(description: "Carini", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 25730)
Comune.create(description: "Castelbuono", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 9648)
Comune.create(description: "Casteldaccia", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 9022)
Comune.create(description: "Castellana Sicula", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 3833)
Comune.create(description: "Castronuovo Di Sicilia", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 )
Comune.create(description: "Cerda", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 5377)
Comune.create(description: "Chiusa Sclafani", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 3302)
Comune.create(description: "Ciminna", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 3986)
Comune.create(description: "Cinisi", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 10253)
Comune.create(description: "Collesano", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 4253)
Comune.create(description: "Contessa Entellina", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 1985)
Comune.create(description: "Corleone", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 11393)
Comune.create(description: "Ficarazzi", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 9418)
Comune.create(description: "Gangi", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 7614)
Comune.create(description: "Geraci Siculo", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 2105)
Comune.create(description: "Giardinello", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 1900)
Comune.create(description: "Giuliana", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 2305)
Comune.create(description: "Godrano", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 1147)
Comune.create(description: "Gratteri", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 1079)
Comune.create(description: "Isnello", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 1923)
Comune.create(description: "Isola Delle Femmine", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 6208)
Comune.create(description: "Lascari", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 3132)
Comune.create(description: "Lercara Friddi", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 7392)
Comune.create(description: "Marineo", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 6956)
Comune.create(description: "Mezzojuso", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 3058)
Comune.create(description: "Misilmeri", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 23109)
Comune.create(description: "Monreale", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 31964)
Comune.create(description: "Montelepre", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 6168)
Comune.create(description: "Montemaggiore Belsito", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 3866)
Comune.create(description: "Palazzo Adriano", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 2530)
Comune.create(description: "Palermo", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 686722)
Comune.create(description: "Partinico", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 31003)
Comune.create(description: "Petralia Soprana", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 3688)
Comune.create(description: "Petralia Sottana", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 3311)
Comune.create(description: "Piana Degli Albanesi", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 6227)
Comune.create(description: "Polizzi Generosa", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 4169)
Comune.create(description: "Pollina", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 3120)
Comune.create(description: "Prizzi", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 5711)
Comune.create(description: "Roccamena", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 1793)
Comune.create(description: "Roccapalumba", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 2842)
Comune.create(description: "San Cipirello", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 5016)
Comune.create(description: "San Giuseppe Jato", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 8349)
Comune.create(description: "San Mauro Castelverde", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 2166)
Comune.create(description: "Santa Cristina Gela", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 865)
Comune.create(description: "Santa Flavia", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 9535)
Comune.create(description: "Sciara", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 2718)
Comune.create(description: "Scillato", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 706)
Comune.create(description: "Sclafani Bagni", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 506)
Comune.create(description: "Termini Imerese", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 26958)
Comune.create(description: "Terrasini", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 10686)
Comune.create(description: "Torretta", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 3468)
Comune.create(description: "Trabia", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 8252)
Comune.create(description: "Trappeto", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 2770)
Comune.create(description: "Ustica", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 1335)
Comune.create(description: "Valledolmo", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 4147)
Comune.create(description: "Ventimiglia Di Sicilia", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 2192)
Comune.create(description: "Vicari", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 3077)
Comune.create(description: "Villabate", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 18371)
Comune.create(description: "Villafrati", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 3365)
Comune.create(description: "Cefala' Diana", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 992)
Comune.create(description: "Cefalu'", provincia_id: 17, regione_id: 11, country_id: 1, continent_id: 1 , population: 13789)
