Municipality.create(description: "Alia", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 4184)
Municipality.create(description: "Alimena", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 2494)
Municipality.create(description: "Aliminusa", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 1363)
Municipality.create(description: "Altavilla Milicia", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 5252)
Municipality.create(description: "Altofonte", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 9193)
Municipality.create(description: "Bagheria", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 50854)
Municipality.create(description: "Balestrate", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 5693)
Municipality.create(description: "Baucina", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 2031)
Municipality.create(description: "Belmonte Mezzagno", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 10322)
Municipality.create(description: "Bisacquino", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 5205)
Municipality.create(description: "Blufi", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 1208)
Municipality.create(description: "Bolognetta", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 3472)
Municipality.create(description: "Bompietro", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 1754)
Municipality.create(description: "Borgetto", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 6242)
Municipality.create(description: "Caccamo", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 8524)
Municipality.create(description: "Caltavuturo", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 4570)
Municipality.create(description: "Campofelice Di Fitalia", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 609)
Municipality.create(description: "Campofelice Di Roccella", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 5748)
Municipality.create(description: "Campofiorito", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 1401)
Municipality.create(description: "Camporeale", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 3716)
Municipality.create(description: "Capaci", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 10164)
Municipality.create(description: "Carini", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 25730)
Municipality.create(description: "Castelbuono", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 9648)
Municipality.create(description: "Casteldaccia", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 9022)
Municipality.create(description: "Castellana Sicula", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 3833)
Municipality.create(description: "Castronuovo Di Sicilia", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 )
Municipality.create(description: "Cerda", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 5377)
Municipality.create(description: "Chiusa Sclafani", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 3302)
Municipality.create(description: "Ciminna", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 3986)
Municipality.create(description: "Cinisi", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 10253)
Municipality.create(description: "Collesano", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 4253)
Municipality.create(description: "Contessa Entellina", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 1985)
Municipality.create(description: "Corleone", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 11393)
Municipality.create(description: "Ficarazzi", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 9418)
Municipality.create(description: "Gangi", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 7614)
Municipality.create(description: "Geraci Siculo", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 2105)
Municipality.create(description: "Giardinello", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 1900)
Municipality.create(description: "Giuliana", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 2305)
Municipality.create(description: "Godrano", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 1147)
Municipality.create(description: "Gratteri", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 1079)
Municipality.create(description: "Isnello", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 1923)
Municipality.create(description: "Isola Delle Femmine", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 6208)
Municipality.create(description: "Lascari", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 3132)
Municipality.create(description: "Lercara Friddi", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 7392)
Municipality.create(description: "Marineo", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 6956)
Municipality.create(description: "Mezzojuso", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 3058)
Municipality.create(description: "Misilmeri", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 23109)
Municipality.create(description: "Monreale", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 31964)
Municipality.create(description: "Montelepre", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 6168)
Municipality.create(description: "Montemaggiore Belsito", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 3866)
Municipality.create(description: "Palazzo Adriano", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 2530)
Municipality.create(description: "Palermo", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 686722)
Municipality.create(description: "Partinico", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 31003)
Municipality.create(description: "Petralia Soprana", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 3688)
Municipality.create(description: "Petralia Sottana", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 3311)
Municipality.create(description: "Piana Degli Albanesi", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 6227)
Municipality.create(description: "Polizzi Generosa", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 4169)
Municipality.create(description: "Pollina", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 3120)
Municipality.create(description: "Prizzi", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 5711)
Municipality.create(description: "Roccamena", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 1793)
Municipality.create(description: "Roccapalumba", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 2842)
Municipality.create(description: "San Cipirello", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 5016)
Municipality.create(description: "San Giuseppe Jato", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 8349)
Municipality.create(description: "San Mauro Castelverde", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 2166)
Municipality.create(description: "Santa Cristina Gela", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 865)
Municipality.create(description: "Santa Flavia", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 9535)
Municipality.create(description: "Sciara", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 2718)
Municipality.create(description: "Scillato", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 706)
Municipality.create(description: "Sclafani Bagni", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 506)
Municipality.create(description: "Termini Imerese", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 26958)
Municipality.create(description: "Terrasini", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 10686)
Municipality.create(description: "Torretta", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 3468)
Municipality.create(description: "Trabia", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 8252)
Municipality.create(description: "Trappeto", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 2770)
Municipality.create(description: "Ustica", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 1335)
Municipality.create(description: "Valledolmo", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 4147)
Municipality.create(description: "Ventimiglia Di Sicilia", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 2192)
Municipality.create(description: "Vicari", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 3077)
Municipality.create(description: "Villabate", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 18371)
Municipality.create(description: "Villafrati", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 3365)
Municipality.create(description: "Cefala' Diana", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 992)
Municipality.create(description: "Cefalu'", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 13789)
