Comune.create(description: "Alia", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 4184)
Comune.create(description: "Alimena", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 2494)
Comune.create(description: "Aliminusa", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 1363)
Comune.create(description: "Altavilla Milicia", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 5252)
Comune.create(description: "Altofonte", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 9193)
Comune.create(description: "Bagheria", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 50854)
Comune.create(description: "Balestrate", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 5693)
Comune.create(description: "Baucina", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 2031)
Comune.create(description: "Belmonte Mezzagno", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 10322)
Comune.create(description: "Bisacquino", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 5205)
Comune.create(description: "Blufi", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 1208)
Comune.create(description: "Bolognetta", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 3472)
Comune.create(description: "Bompietro", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 1754)
Comune.create(description: "Borgetto", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 6242)
Comune.create(description: "Caccamo", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 8524)
Comune.create(description: "Caltavuturo", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 4570)
Comune.create(description: "Campofelice Di Fitalia", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 609)
Comune.create(description: "Campofelice Di Roccella", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 5748)
Comune.create(description: "Campofiorito", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 1401)
Comune.create(description: "Camporeale", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 3716)
Comune.create(description: "Capaci", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 10164)
Comune.create(description: "Carini", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 25730)
Comune.create(description: "Castelbuono", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 9648)
Comune.create(description: "Casteldaccia", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 9022)
Comune.create(description: "Castellana Sicula", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 3833)
Comune.create(description: "Castronuovo Di Sicilia", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 )
Comune.create(description: "Cerda", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 5377)
Comune.create(description: "Chiusa Sclafani", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 3302)
Comune.create(description: "Ciminna", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 3986)
Comune.create(description: "Cinisi", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 10253)
Comune.create(description: "Collesano", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 4253)
Comune.create(description: "Contessa Entellina", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 1985)
Comune.create(description: "Corleone", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 11393)
Comune.create(description: "Ficarazzi", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 9418)
Comune.create(description: "Gangi", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 7614)
Comune.create(description: "Geraci Siculo", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 2105)
Comune.create(description: "Giardinello", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 1900)
Comune.create(description: "Giuliana", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 2305)
Comune.create(description: "Godrano", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 1147)
Comune.create(description: "Gratteri", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 1079)
Comune.create(description: "Isnello", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 1923)
Comune.create(description: "Isola Delle Femmine", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 6208)
Comune.create(description: "Lascari", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 3132)
Comune.create(description: "Lercara Friddi", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 7392)
Comune.create(description: "Marineo", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 6956)
Comune.create(description: "Mezzojuso", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 3058)
Comune.create(description: "Misilmeri", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 23109)
Comune.create(description: "Monreale", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 31964)
Comune.create(description: "Montelepre", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 6168)
Comune.create(description: "Montemaggiore Belsito", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 3866)
Comune.create(description: "Palazzo Adriano", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 2530)
Comune.create(description: "Palermo", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 686722)
Comune.create(description: "Partinico", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 31003)
Comune.create(description: "Petralia Soprana", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 3688)
Comune.create(description: "Petralia Sottana", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 3311)
Comune.create(description: "Piana Degli Albanesi", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 6227)
Comune.create(description: "Polizzi Generosa", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 4169)
Comune.create(description: "Pollina", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 3120)
Comune.create(description: "Prizzi", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 5711)
Comune.create(description: "Roccamena", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 1793)
Comune.create(description: "Roccapalumba", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 2842)
Comune.create(description: "San Cipirello", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 5016)
Comune.create(description: "San Giuseppe Jato", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 8349)
Comune.create(description: "San Mauro Castelverde", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 2166)
Comune.create(description: "Santa Cristina Gela", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 865)
Comune.create(description: "Santa Flavia", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 9535)
Comune.create(description: "Sciara", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 2718)
Comune.create(description: "Scillato", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 706)
Comune.create(description: "Sclafani Bagni", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 506)
Comune.create(description: "Termini Imerese", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 26958)
Comune.create(description: "Terrasini", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 10686)
Comune.create(description: "Torretta", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 3468)
Comune.create(description: "Trabia", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 8252)
Comune.create(description: "Trappeto", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 2770)
Comune.create(description: "Ustica", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 1335)
Comune.create(description: "Valledolmo", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 4147)
Comune.create(description: "Ventimiglia Di Sicilia", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 2192)
Comune.create(description: "Vicari", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 3077)
Comune.create(description: "Villabate", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 18371)
Comune.create(description: "Villafrati", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 3365)
Comune.create(description: "Cefala' Diana", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 992)
Comune.create(description: "Cefalu'", province_id: 17, region_id:  11, country_id: 1, continent_id: 1 , population: 13789)
