Municipality.create(description: "Vicuña", province_id: 186, region_id:  42, country_id: 90, continent_id: 2 , population: 24010)
Municipality.create(description: "Paiguano", province_id: 186, region_id:  42, country_id: 90, continent_id: 2 , population: 4168)
Municipality.create(description: "La Serena", province_id: 186, region_id:  42, country_id: 90, continent_id: 2 , population: 160148)
Municipality.create(description: "La Higuera", province_id: 186, region_id:  42, country_id: 90, continent_id: 2 , population: 3721)
Municipality.create(description: "Coquimbo", province_id: 186, region_id:  42, country_id: 90, continent_id: 2 , population: 163036)
Municipality.create(description: "Andacollo", province_id: 186, region_id:  42, country_id: 90, continent_id: 2 , population: 10288)
