Comune.create(description: "Acate", provincia_id: 18, region_id:  11, country_id: 1, continent_id: 1 , population: 8000)
Comune.create(description: "Chiaramonte Gulfi", provincia_id: 18, region_id:  11, country_id: 1, continent_id: 1 , population: 8099)
Comune.create(description: "Comiso", provincia_id: 18, region_id:  11, country_id: 1, continent_id: 1 , population: 29076)
Comune.create(description: "Giarratana", provincia_id: 18, region_id:  11, country_id: 1, continent_id: 1 , population: 3343)
Comune.create(description: "Ispica", provincia_id: 18, region_id:  11, country_id: 1, continent_id: 1 , population: 14457)
Comune.create(description: "Modica", provincia_id: 18, region_id:  11, country_id: 1, continent_id: 1 , population: 52639)
Comune.create(description: "Monterosso Almo", provincia_id: 18, region_id:  11, country_id: 1, continent_id: 1 , population: 3346)
Comune.create(description: "Pozzallo", provincia_id: 18, region_id:  11, country_id: 1, continent_id: 1 , population: 17936)
Comune.create(description: "Ragusa", provincia_id: 18, region_id:  11, country_id: 1, continent_id: 1 , population: 68956)
Comune.create(description: "Santa Croce Camerina", provincia_id: 18, region_id:  11, country_id: 1, continent_id: 1 , population: 8481)
Comune.create(description: "Scicli", provincia_id: 18, region_id:  11, country_id: 1, continent_id: 1 , population: 25614)
Comune.create(description: "Vittoria", provincia_id: 18, region_id:  11, country_id: 1, continent_id: 1 , population: 55317)
