Comune.create(description: "Santo Domingo", province_id: 193, region_id:  43, country_id: 90, continent_id: 2 , population: 7418)
Comune.create(description: "San Antonio", province_id: 193, region_id:  43, country_id: 90, continent_id: 2 , population: 87205)
Comune.create(description: "El Tabo", province_id: 193, region_id:  43, country_id: 90, continent_id: 2 , population: 7028)
Comune.create(description: "El Quisco", province_id: 193, region_id:  43, country_id: 90, continent_id: 2 , population: 9467)
Comune.create(description: "Cartagena", province_id: 193, region_id:  43, country_id: 90, continent_id: 2 , population: 16875)
Comune.create(description: "Algarrobo", province_id: 193, region_id:  43, country_id: 90, continent_id: 2 , population: 8601)
