Municipality.create(description: "Viña del Mar", province_id: 195, region_id:  43, country_id: 90, continent_id: 2 , population: 286931)
Municipality.create(description: "Valparaíso", province_id: 195, region_id:  43, country_id: 90, continent_id: 2 , population: 275982)
Municipality.create(description: "Quintero", province_id: 195, region_id:  43, country_id: 90, continent_id: 2 , population: 21174)
Municipality.create(description: "Puchuncaví", province_id: 195, region_id:  43, country_id: 90, continent_id: 2 , population: 12954)
Municipality.create(description: "Concón", province_id: 195, region_id:  43, country_id: 90, continent_id: 2 , population: 32273)
Municipality.create(description: "Casablanca", province_id: 195, region_id:  43, country_id: 90, continent_id: 2 , population: 21874)
