Comune.create(description: "Augusta", provincia_id: 19, region_id:  11, country_id: 1, continent_id: 1 , population: 33820)
Comune.create(description: "Avola", provincia_id: 19, region_id:  11, country_id: 1, continent_id: 1 , population: 31289)
Comune.create(description: "Buccheri", provincia_id: 19, region_id:  11, country_id: 1, continent_id: 1 , population: 2320)
Comune.create(description: "Buscemi", provincia_id: 19, region_id:  11, country_id: 1, continent_id: 1 , population: 1200)
Comune.create(description: "Canicattini Bagni", provincia_id: 19, region_id:  11, country_id: 1, continent_id: 1 , population: 7519)
Comune.create(description: "Carlentini", provincia_id: 19, region_id:  11, country_id: 1, continent_id: 1 , population: 16879)
Comune.create(description: "Cassaro", provincia_id: 19, region_id:  11, country_id: 1, continent_id: 1 , population: 909)
Comune.create(description: "Ferla", provincia_id: 19, region_id:  11, country_id: 1, continent_id: 1 , population: 2760)
Comune.create(description: "Floridia", provincia_id: 19, region_id:  11, country_id: 1, continent_id: 1 , population: 20675)
Comune.create(description: "Francofonte", provincia_id: 19, region_id:  11, country_id: 1, continent_id: 1 , population: 12949)
Comune.create(description: "Lentini", provincia_id: 19, region_id:  11, country_id: 1, continent_id: 1 , population: 24748)
Comune.create(description: "Melilli", provincia_id: 19, region_id:  11, country_id: 1, continent_id: 1 , population: 12216)
Comune.create(description: "Noto", provincia_id: 19, region_id:  11, country_id: 1, continent_id: 1 , population: 23065)
Comune.create(description: "Pachino", provincia_id: 19, region_id:  11, country_id: 1, continent_id: 1 , population: 21324)
Comune.create(description: "Palazzolo Acreide", provincia_id: 19, region_id:  11, country_id: 1, continent_id: 1 , population: 9109)
Comune.create(description: "Portopalo Di Capo Passero", provincia_id: 19, region_id:  11, country_id: 1, continent_id: 1 , population: 3500)
Comune.create(description: "Priolo Gargallo", provincia_id: 19, region_id:  11, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Rosolini", provincia_id: 19, region_id:  11, country_id: 1, continent_id: 1 , population: 20152)
Comune.create(description: "Siracusa", provincia_id: 19, region_id:  11, country_id: 1, continent_id: 1 , population: 123657)
Comune.create(description: "Solarino", provincia_id: 19, region_id:  11, country_id: 1, continent_id: 1 , population: 7199)
Comune.create(description: "Sortino", provincia_id: 19, region_id:  11, country_id: 1, continent_id: 1 , population: 9092)
