Municipality.create(description: "Agugliano", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 4163)
Municipality.create(description: "Ancona", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 100507)
Municipality.create(description: "Arcevia", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 5300)
Municipality.create(description: "Barbara", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 1455)
Municipality.create(description: "Belvedere Ostrense", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 2179)
Municipality.create(description: "Camerano", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 6523)
Municipality.create(description: "Camerata Picena", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 1700)
Municipality.create(description: "Castel Colonna", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 961)
Municipality.create(description: "Castelbellino", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 3618)
Municipality.create(description: "Castelfidardo", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 16917)
Municipality.create(description: "Castelleone Di Suasa", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 1689)
Municipality.create(description: "Castelplanio", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 3223)
Municipality.create(description: "Chiaravalle", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 14040)
Municipality.create(description: "Corinaldo", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 5170)
Municipality.create(description: "Cupramontana", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 4736)
Municipality.create(description: "Fabriano", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 30019)
Municipality.create(description: "Falconara Marittima", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 28349)
Municipality.create(description: "Filottrano", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 9278)
Municipality.create(description: "Genga", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 1981)
Municipality.create(description: "Jesi", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 39224)
Municipality.create(description: "Loreto", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 11280)
Municipality.create(description: "Maiolati Spontini", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 5733)
Municipality.create(description: "Mergo", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 970)
Municipality.create(description: "Monsano", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 2760)
Municipality.create(description: "Monte Roberto", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 2446)
Municipality.create(description: "Montecarotto", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 2176)
Municipality.create(description: "Montemarciano", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 9173)
Municipality.create(description: "Monterado", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 1569)
Municipality.create(description: "Numana", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 3293)
Municipality.create(description: "Offagna", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 1692)
Municipality.create(description: "Osimo", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 29431)
Municipality.create(description: "Ostra", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 6028)
Municipality.create(description: "Ostra Vetere", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 3536)
Municipality.create(description: "Poggio San Marcello", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 737)
Municipality.create(description: "Polverigi", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 3015)
Municipality.create(description: "Ripe", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 3575)
Municipality.create(description: "Rosora", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 1748)
Municipality.create(description: "San Marcello", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 1931)
Municipality.create(description: "San Paolo Di Jesi", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 841)
Municipality.create(description: "Santa Maria Nuova", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 3914)
Municipality.create(description: "Sassoferrato", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 7419)
Municipality.create(description: "Senigallia", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 41550)
Municipality.create(description: "Serra San Quirico", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 3016)
Municipality.create(description: "Sirolo", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 3313)
Municipality.create(description: "Staffolo", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 2217)
Municipality.create(description: "Cerreto D'Esi", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 3308)
Municipality.create(description: "Morro D'Alba", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 1776)
Municipality.create(description: "Serra De' Conti", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 3464)
Municipality.create(description: "București", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 188343)
Municipality.create(description: "Abrud", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 5072)
Municipality.create(description: "Aiud", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 22876)
Municipality.create(description: "Alba Iulia", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 63536)
Municipality.create(description: "Baia de Arieș", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 3461)
Municipality.create(description: "Blaj", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 2063)
Municipality.create(description: "Câmpeni", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 7221)
Municipality.create(description: "Cugir", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 21376)
Municipality.create(description: "Ocna Mureș", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 13036)
Municipality.create(description: "Sebeș", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 27019)
Municipality.create(description: "Teiuș", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 6695)
Municipality.create(description: "Zlatna", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 749)
Municipality.create(description: "Arad", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 159074)
Municipality.create(description: "Chișineu-Criș", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 7987)
Municipality.create(description: "Curtici", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 7453)
Municipality.create(description: "Ineu", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 9078)
Municipality.create(description: "Lipova", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 9648)
Municipality.create(description: "Nădlac", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 7398)
Municipality.create(description: "Pâncota", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 6946)
Municipality.create(description: "Pecica", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 12762)
Municipality.create(description: "Sântana", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 11428)
Municipality.create(description: "Sebiș", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 5979)
Municipality.create(description: "Câmpulung", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 31767)
Municipality.create(description: "Costești", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 10375)
Municipality.create(description: "Curtea de Argeș", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 27359)
Municipality.create(description: "Mioveni", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 31998)
Municipality.create(description: "Pitești", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 155383)
Municipality.create(description: "Ștefănești", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 14541)
Municipality.create(description: "Topoloveni", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 10219)
Municipality.create(description: "Bacău", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 144307)
Municipality.create(description: "Buhuși", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 14562)
Municipality.create(description: "Comănești", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 19568)
Municipality.create(description: "Dărmănești", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 12247)
Municipality.create(description: "Moinești", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 21787)
Municipality.create(description: "Onești", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 39172)
Municipality.create(description: "Slănic Moldova", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 4198)
Municipality.create(description: "Târgu Ocna", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 113)
Municipality.create(description: "Aleșd", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 9619)
Municipality.create(description: "Beiuș", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 10667)
Municipality.create(description: "Marghita", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 1577)
Municipality.create(description: "Nucet", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 2165)
Municipality.create(description: "Oradea", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 196367)
Municipality.create(description: "Salonta", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 17735)
Municipality.create(description: "Săcueni", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 11526)
Municipality.create(description: "Ștei", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 6529)
Municipality.create(description: "Valea lui Mihai", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 9902)
Municipality.create(description: "Vașcău", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 2315)
Municipality.create(description: "Beclean", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 10628)
Municipality.create(description: "Bistrița", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 75076)
Municipality.create(description: "Năsăud", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 9077)
Municipality.create(description: "Sângeorz-Băi", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 9413)
Municipality.create(description: "Botoșani", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 106847)
Municipality.create(description: "Bucecea", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 4274)
Municipality.create(description: "Darabani", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 9523)
Municipality.create(description: "Dorohoi", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 24309)
Municipality.create(description: "Flămânzi", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 9456)
Municipality.create(description: "Săveni", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 6999)
Municipality.create(description: "Ștefănești", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 5314)
Municipality.create(description: "Brașov", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 2532)
Municipality.create(description: "Codlea", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 21708)
Municipality.create(description: "Făgăraș", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 30714)
Municipality.create(description: "Ghimbav", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 4698)
Municipality.create(description: "Predeal", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 4755)
Municipality.create(description: "Râșnov", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 15022)
Municipality.create(description: "Rupea", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 5269)
Municipality.create(description: "Săcele", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 30798)
Municipality.create(description: "Victoria", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 7386)
Municipality.create(description: "Zărnești", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 23476)
Municipality.create(description: "Brăila", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 180302)
Municipality.create(description: "Făurei", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 3592)
Municipality.create(description: "Ianca", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 10343)
Municipality.create(description: "Însurăței", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 6528)
Municipality.create(description: "Buzău", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 115494)
Municipality.create(description: "Nehoiu", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 10211)
Municipality.create(description: "Pătârlagele", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 7304)
Municipality.create(description: "Pogoanele", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 7275)
Municipality.create(description: "Râmnicu Sărat", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 33843)
Municipality.create(description: "Anina", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 7485)
Municipality.create(description: "Băile Herculane", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 5008)
Municipality.create(description: "Bocșa", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 15842)
Municipality.create(description: "Caransebeș", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 24689)
Municipality.create(description: "Moldova Nouă", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 1235)
Municipality.create(description: "Oravița", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 11382)
Municipality.create(description: "Oțelu Roșu", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 926)
Municipality.create(description: "Reșița", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 73282)
Municipality.create(description: "Budești", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 7725)
Municipality.create(description: "Călărași", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 65181)
Municipality.create(description: "Fundulea", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 6851)
Municipality.create(description: "Lehliu Gară", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 6502)
Municipality.create(description: "Oltenița", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 24822)
Municipality.create(description: "Câmpia Turzii", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 22223)
Municipality.create(description: "Cluj-Napoca", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 324576)
Municipality.create(description: "Dej", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 33497)
Municipality.create(description: "Gherla", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 20892)
Municipality.create(description: "Huedin", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 9346)
Municipality.create(description: "Turda", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 47744)
Municipality.create(description: "Băneasa", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 5384)
Municipality.create(description: "Cernavodă", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 17022)
Municipality.create(description: "Constanța", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 283872)
Municipality.create(description: "Eforie", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 9473)
Municipality.create(description: "Hârșova", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 9642)
Municipality.create(description: "Mangalia", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 36364)
Municipality.create(description: "Medgidia", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 3978)
Municipality.create(description: "Murfatlar", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 9634)
Municipality.create(description: "Năvodari", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 32981)
Municipality.create(description: "Negru Vodă", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 5088)
Municipality.create(description: "Ovidiu", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 13847)
Municipality.create(description: "Techirghiol", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 7292)
Municipality.create(description: "Baraolt", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 8672)
Municipality.create(description: "Covasna", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 10114)
Municipality.create(description: "Întorsura Buzăului", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 7528)
Municipality.create(description: "Sfântu Gheorghe", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 56006)
Municipality.create(description: "Târgu Secuiesc", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 18491)
Municipality.create(description: "Fieni", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 7587)
Municipality.create(description: "Găești", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 13317)
Municipality.create(description: "Moreni", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 18687)
Municipality.create(description: "Pucioasa", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 14254)
Municipality.create(description: "Răcari", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 693)
Municipality.create(description: "Târgoviște", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 7961)
Municipality.create(description: "Titu", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 9355)
Municipality.create(description: "Băilești", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 17437)
Municipality.create(description: "Bechet", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 3657)
Municipality.create(description: "Calafat", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 17336)
Municipality.create(description: "Craiova", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 269506)
Municipality.create(description: "Dăbuleni", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 12182)
Municipality.create(description: "Filiași", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 169)
Municipality.create(description: "Segarcea", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 7019)
Municipality.create(description: "Berești", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 2916)
Municipality.create(description: "Galați", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 249432)
Municipality.create(description: "Târgu Bujor", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 6299)
Municipality.create(description: "Tecuci", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 34871)
Municipality.create(description: "Bolintin-Vale", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 12929)
Municipality.create(description: "Giurgiu", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 61353)
Municipality.create(description: "Mihăilești", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 7923)
Municipality.create(description: "Bumbești-Jiu", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 8932)
Municipality.create(description: "Motru", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 19079)
Municipality.create(description: "Novaci", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 5431)
Municipality.create(description: "Rovinari", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 11816)
Municipality.create(description: "Târgu Cărbunești", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 8034)
Municipality.create(description: "Târgu Jiu", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 82504)
Municipality.create(description: "Tismana", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 7035)
Municipality.create(description: "Țicleni", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 4414)
Municipality.create(description: "Băile Tușnad", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 1641)
Municipality.create(description: "Bălan", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 6115)
Municipality.create(description: "Borsec", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 2585)
Municipality.create(description: "Cristuru Secuiesc", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 9491)
Municipality.create(description: "Gheorgheni", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 18377)
Municipality.create(description: "Miercurea Ciuc", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 38966)
Municipality.create(description: "Odorheiu Secuiesc", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 32935)
Municipality.create(description: "Toplița", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 13929)
Municipality.create(description: "Vlăhița", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 6898)
Municipality.create(description: "Aninoasa", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 436)
Municipality.create(description: "Brad", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 14495)
Municipality.create(description: "Călan", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 11279)
Municipality.create(description: "Deva", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 61123)
Municipality.create(description: "Geoagiu", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 5294)
Municipality.create(description: "Hațeg", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 934)
Municipality.create(description: "Hunedoara", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 60525)
Municipality.create(description: "Lupeni", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 2339)
Municipality.create(description: "Orăștie", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 18227)
Municipality.create(description: "Petrila", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 22692)
Municipality.create(description: "Petroșani", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 3716)
Municipality.create(description: "Simeria", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 12556)
Municipality.create(description: "Uricani", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 8972)
Municipality.create(description: "Vulcan", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 2416)
Municipality.create(description: "Amara", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 7345)
Municipality.create(description: "Căzănești", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 3271)
Municipality.create(description: "Fetești", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 30217)
Municipality.create(description: "Fierbinți-Târg", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 4969)
Municipality.create(description: "Slobozia", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 48241)
Municipality.create(description: "Țăndărei", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 13219)
Municipality.create(description: "Urziceni", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 15308)
Municipality.create(description: "Hârlău", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 10905)
Municipality.create(description: "Iași", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 290422)
Municipality.create(description: "Pașcani", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 33745)
Municipality.create(description: "Podu Iloaiei", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 9573)
Municipality.create(description: "Târgu Frumos", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 9386)
Municipality.create(description: "Bragadiru", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 15329)
Municipality.create(description: "Buftea", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 22178)
Municipality.create(description: "Chitila", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 14184)
Municipality.create(description: "Măgurele", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 11041)
Municipality.create(description: "Otopeni", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 13861)
Municipality.create(description: "Pantelimon", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 25596)
Municipality.create(description: "Popești-Leordeni", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 21895)
Municipality.create(description: "Voluntari", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 42944)
Municipality.create(description: "Baia Mare", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 123738)
Municipality.create(description: "Baia Sprie", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 15476)
Municipality.create(description: "Borșa", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 27611)
Municipality.create(description: "Cavnic", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 4976)
Municipality.create(description: "Dragomirești", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 3213)
Municipality.create(description: "Săliștea de Sus", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 4893)
Municipality.create(description: "Seini", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 8987)
Municipality.create(description: "Sighetu Marmației", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 3764)
Municipality.create(description: "Șomcuta Mare", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 7565)
Municipality.create(description: "Tăuții-Măgherăuș", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 7136)
Municipality.create(description: "Târgu Lăpuș", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 11744)
Municipality.create(description: "Ulmeni", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 727)
Municipality.create(description: "Vișeu de Sus", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 15037)
Municipality.create(description: "Baia de Aramă", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 5349)
Municipality.create(description: "Drobeta-Turnu Severin", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 92617)
Municipality.create(description: "Orșova", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 10441)
Municipality.create(description: "Strehaia", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 10506)
Municipality.create(description: "Vânju Mare", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 5311)
Municipality.create(description: "Iernut", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 8705)
Municipality.create(description: "Luduș", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 15328)
Municipality.create(description: "Miercurea Nirajului", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 5554)
Municipality.create(description: "Reghin", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 33281)
Municipality.create(description: "Sărmașu", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 6942)
Municipality.create(description: "Sângeorgiu de Pădure", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 5166)
Municipality.create(description: "Sighișoara", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 28102)
Municipality.create(description: "Sovata", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 10385)
Municipality.create(description: "Târgu Mureș", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 13429)
Municipality.create(description: "Târnăveni", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 22075)
Municipality.create(description: "Ungheni", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 6945)
Municipality.create(description: "Bicaz", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 6543)
Municipality.create(description: "Piatra Neamț", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 85055)
Municipality.create(description: "Roman", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 50713)
Municipality.create(description: "Roznov", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 8593)
Municipality.create(description: "Târgu Neamț", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 18695)
Municipality.create(description: "Balș", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 18164)
Municipality.create(description: "Caracal", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 30954)
Municipality.create(description: "Corabia", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 16441)
Municipality.create(description: "Drăgănești-Olt", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 10894)
Municipality.create(description: "Piatra-Olt", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 6299)
Municipality.create(description: "Potcoava", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 5743)
Municipality.create(description: "Scornicești", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 11766)
Municipality.create(description: "Slatina", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 70293)
Municipality.create(description: "Azuga", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 444)
Municipality.create(description: "Băicoi", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 17981)
Municipality.create(description: "Boldești-Scăeni", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 11137)
Municipality.create(description: "Breaza", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 15928)
Municipality.create(description: "Bușteni", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 8894)
Municipality.create(description: "Câmpina", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 32935)
Municipality.create(description: "Comarnic", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 1197)
Municipality.create(description: "Mizil", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 14312)
Municipality.create(description: "Ploiești", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 209945)
Municipality.create(description: "Plopeni", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 7718)
Municipality.create(description: "Sinaia", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 10419)
Municipality.create(description: "Slănic", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 6034)
Municipality.create(description: "Urlați", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 10541)
Municipality.create(description: "Vălenii de Munte", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 12257)
Municipality.create(description: "Ardud", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 6231)
Municipality.create(description: "Carei", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 21112)
Municipality.create(description: "Livada", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 6773)
Municipality.create(description: "Negrești-Oaș", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 11867)
Municipality.create(description: "Satu Mare", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 102411)
Municipality.create(description: "Tășnad", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 8631)
Municipality.create(description: "Cehu Silvaniei", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 7214)
Municipality.create(description: "Jibou", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 10407)
Municipality.create(description: "Șimleu Silvaniei", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 14436)
Municipality.create(description: "Zalău", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 56202)
Municipality.create(description: "Agnita", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 8732)
Municipality.create(description: "Avrig", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 12815)
Municipality.create(description: "Cisnădie", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 14282)
Municipality.create(description: "Copșa Mică", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 5404)
Municipality.create(description: "Dumbrăveni", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 7388)
Municipality.create(description: "Mediaș", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 47204)
Municipality.create(description: "Miercurea Sibiului", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 391)
Municipality.create(description: "Ocna Sibiului", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 3562)
Municipality.create(description: "Săliște", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 5421)
Municipality.create(description: "Sibiu", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 147245)
Municipality.create(description: "Tălmaciu", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 6905)
Municipality.create(description: "Broșteni", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 5506)
Municipality.create(description: "Cajvana", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 6901)
Municipality.create(description: "Câmpulung Moldovenesc", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 16722)
Municipality.create(description: "Dolhasca", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 10298)
Municipality.create(description: "Fălticeni", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 25723)
Municipality.create(description: "Frasin", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 5876)
Municipality.create(description: "Gura Humorului", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 13667)
Municipality.create(description: "Liteni", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 9398)
Municipality.create(description: "Milișăuți", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 5005)
Municipality.create(description: "Rădăuți", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 23822)
Municipality.create(description: "Salcea", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 9015)
Municipality.create(description: "Siret", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 7976)
Municipality.create(description: "Solca", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 2188)
Municipality.create(description: "Suceava", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 92121)
Municipality.create(description: "Vatra Dornei", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 14429)
Municipality.create(description: "Vicovu de Sus", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 13308)
Municipality.create(description: "Alexandria", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 45434)
Municipality.create(description: "Roșiorii de Vede", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 27416)
Municipality.create(description: "Turnu Măgurele", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 24772)
Municipality.create(description: "Videle", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 11508)
Municipality.create(description: "Zimnicea", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 14058)
Municipality.create(description: "Buziaș", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 7023)
Municipality.create(description: "Ciacova", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 5348)
Municipality.create(description: "Deta", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 626)
Municipality.create(description: "Făget", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 6761)
Municipality.create(description: "Gătaia", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 5861)
Municipality.create(description: "Jimbolia", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 10808)
Municipality.create(description: "Lugoj", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 40361)
Municipality.create(description: "Recaș", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 8336)
Municipality.create(description: "Sânnicolau Mare", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 12312)
Municipality.create(description: "Timișoara", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 319279)
Municipality.create(description: "Babadag", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 894)
Municipality.create(description: "Isaccea", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 5026)
Municipality.create(description: "Măcin", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 8245)
Municipality.create(description: "Sulina", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 3663)
Municipality.create(description: "Tulcea", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 73707)
Municipality.create(description: "Bârlad", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 55837)
Municipality.create(description: "Huși", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 26266)
Municipality.create(description: "Murgeni", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 7119)
Municipality.create(description: "Negrești", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 838)
Municipality.create(description: "Vaslui", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 55407)
Municipality.create(description: "Băbeni", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 8451)
Municipality.create(description: "Băile Govora", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 2449)
Municipality.create(description: "Băile Olănești", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 4186)
Municipality.create(description: "Bălcești", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 4864)
Municipality.create(description: "Berbești", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 4836)
Municipality.create(description: "Brezoi", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 6022)
Municipality.create(description: "Călimănești", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 7622)
Municipality.create(description: "Drăgășani", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 17871)
Municipality.create(description: "Horezu", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 6263)
Municipality.create(description: "Ocnele Mari", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 3309)
Municipality.create(description: "Râmnicu Vâlcea", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 98776)
Municipality.create(description: "Adjud", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 16045)
Municipality.create(description: "Focșani", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 79315)
Municipality.create(description: "Mărășești", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 944)
Municipality.create(description: "Odobești", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 9364)
Municipality.create(description: "Panciu", province_id: 1, region_id:  1, country_id: 1, continent_id: 1 , population: 7664)
