#encoding: utf-8
Comune.create(:description => "Agugliano", :provincia_id => 1, :regione_id => 1, :population => 4163)
Comune.create(:description => "Ancona", :provincia_id => 1, :regione_id => 1, :population => 100507)
Comune.create(:description => "Arcevia", :provincia_id => 1, :regione_id => 1, :population => 5300)
Comune.create(:description => "Barbara", :provincia_id => 1, :regione_id => 1, :population => 1455)
Comune.create(:description => "Belvedere Ostrense", :provincia_id => 1, :regione_id => 1, :population => 2179)
Comune.create(:description => "Camerano", :provincia_id => 1, :regione_id => 1, :population => 6523)
Comune.create(:description => "Camerata Picena", :provincia_id => 1, :regione_id => 1, :population => 1700)
Comune.create(:description => "Castel Colonna", :provincia_id => 1, :regione_id => 1, :population => 961)
Comune.create(:description => "Castelbellino", :provincia_id => 1, :regione_id => 1, :population => 3618)
Comune.create(:description => "Castelfidardo", :provincia_id => 1, :regione_id => 1, :population => 16917)
Comune.create(:description => "Castelleone Di Suasa", :provincia_id => 1, :regione_id => 1, :population => 1689)
Comune.create(:description => "Castelplanio", :provincia_id => 1, :regione_id => 1, :population => 3223)
Comune.create(:description => "Chiaravalle", :provincia_id => 1, :regione_id => 1, :population => 14040)
Comune.create(:description => "Corinaldo", :provincia_id => 1, :regione_id => 1, :population => 5170)
Comune.create(:description => "Cupramontana", :provincia_id => 1, :regione_id => 1, :population => 4736)
Comune.create(:description => "Fabriano", :provincia_id => 1, :regione_id => 1, :population => 30019)
Comune.create(:description => "Falconara Marittima", :provincia_id => 1, :regione_id => 1, :population => 28349)
Comune.create(:description => "Filottrano", :provincia_id => 1, :regione_id => 1, :population => 9278)
Comune.create(:description => "Genga", :provincia_id => 1, :regione_id => 1, :population => 1981)
Comune.create(:description => "Jesi", :provincia_id => 1, :regione_id => 1, :population => 39224)
Comune.create(:description => "Loreto", :provincia_id => 1, :regione_id => 1, :population => 11280)
Comune.create(:description => "Maiolati Spontini", :provincia_id => 1, :regione_id => 1, :population => 5733)
Comune.create(:description => "Mergo", :provincia_id => 1, :regione_id => 1, :population => 970)
Comune.create(:description => "Monsano", :provincia_id => 1, :regione_id => 1, :population => 2760)
Comune.create(:description => "Monte Roberto", :provincia_id => 1, :regione_id => 1, :population => 2446)
Comune.create(:description => "Montecarotto", :provincia_id => 1, :regione_id => 1, :population => 2176)
Comune.create(:description => "Montemarciano", :provincia_id => 1, :regione_id => 1, :population => 9173)
Comune.create(:description => "Monterado", :provincia_id => 1, :regione_id => 1, :population => 1569)
Comune.create(:description => "Numana", :provincia_id => 1, :regione_id => 1, :population => 3293)
Comune.create(:description => "Offagna", :provincia_id => 1, :regione_id => 1, :population => 1692)
Comune.create(:description => "Osimo", :provincia_id => 1, :regione_id => 1, :population => 29431)
Comune.create(:description => "Ostra", :provincia_id => 1, :regione_id => 1, :population => 6028)
Comune.create(:description => "Ostra Vetere", :provincia_id => 1, :regione_id => 1, :population => 3536)
Comune.create(:description => "Poggio San Marcello", :provincia_id => 1, :regione_id => 1, :population => 737)
Comune.create(:description => "Polverigi", :provincia_id => 1, :regione_id => 1, :population => 3015)
Comune.create(:description => "Ripe", :provincia_id => 1, :regione_id => 1, :population => 3575)
Comune.create(:description => "Rosora", :provincia_id => 1, :regione_id => 1, :population => 1748)
Comune.create(:description => "San Marcello", :provincia_id => 1, :regione_id => 1, :population => 1931)
Comune.create(:description => "San Paolo Di Jesi", :provincia_id => 1, :regione_id => 1, :population => 841)
Comune.create(:description => "Santa Maria Nuova", :provincia_id => 1, :regione_id => 1, :population => 3914)
Comune.create(:description => "Sassoferrato", :provincia_id => 1, :regione_id => 1, :population => 7419)
Comune.create(:description => "Senigallia", :provincia_id => 1, :regione_id => 1, :population => 41550)
Comune.create(:description => "Serra San Quirico", :provincia_id => 1, :regione_id => 1, :population => 3016)
Comune.create(:description => "Sirolo", :provincia_id => 1, :regione_id => 1, :population => 3313)
Comune.create(:description => "Staffolo", :provincia_id => 1, :regione_id => 1, :population => 2217)
Comune.create(:description => "Cerreto D'Esi", :provincia_id => 1, :regione_id => 1, :population => 3308)
Comune.create(:description => "Morro D'Alba", :provincia_id => 1, :regione_id => 1, :population => 1776)
Comune.create(:description => "Serra De' Conti", :provincia_id => 1, :regione_id => 1, :population => 3464)
