Municipality.create(description: "Talagante", province_id: 201, region_id:  44, country_id: 90, continent_id: 2 , population: 59805)
Municipality.create(description: "Peñaflor", province_id: 201, region_id:  44, country_id: 90, continent_id: 2 , population: 66619)
Municipality.create(description: "Padre Hurtado", province_id: 201, region_id:  44, country_id: 90, continent_id: 2 , population: 38768)
Municipality.create(description: "Isla de Maipo", province_id: 201, region_id:  44, country_id: 90, continent_id: 2 , population: 25798)
Municipality.create(description: "El Monte", province_id: 201, region_id:  44, country_id: 90, continent_id: 2 , population: 26459)
