Comune.create(description: "Santa Cruz", provincia_id: 204, regione_id: 45, country_id: 90, continent_id: 2 , population: 32387)
Comune.create(description: "San Fernando", provincia_id: 204, regione_id: 45, country_id: 90, continent_id: 2 , population: 63732)
Comune.create(description: "Pumanque", provincia_id: 204, regione_id: 45, country_id: 90, continent_id: 2 , population: 3442)
Comune.create(description: "Placilla", provincia_id: 204, regione_id: 45, country_id: 90, continent_id: 2 , population: 8078)
Comune.create(description: "Peralillo", provincia_id: 204, regione_id: 45, country_id: 90, continent_id: 2 , population: 9729)
Comune.create(description: "Palmilla", provincia_id: 204, regione_id: 45, country_id: 90, continent_id: 2 , population: 11200)
Comune.create(description: "Nancagua", provincia_id: 204, regione_id: 45, country_id: 90, continent_id: 2 , population: 15634)
Comune.create(description: "Lolol", provincia_id: 204, regione_id: 45, country_id: 90, continent_id: 2 , population: 6191)
Comune.create(description: "Chimbarongo", provincia_id: 204, regione_id: 45, country_id: 90, continent_id: 2 , population: 32316)
Comune.create(description: "Chépica", provincia_id: 204, regione_id: 45, country_id: 90, continent_id: 2 , population: 13857)
