Municipality.create(description: "Santa Cruz", province_id: 204, region_id:  45, country_id: 90, continent_id: 2 , population: 32387)
Municipality.create(description: "San Fernando", province_id: 204, region_id:  45, country_id: 90, continent_id: 2 , population: 63732)
Municipality.create(description: "Pumanque", province_id: 204, region_id:  45, country_id: 90, continent_id: 2 , population: 3442)
Municipality.create(description: "Placilla", province_id: 204, region_id:  45, country_id: 90, continent_id: 2 , population: 8078)
Municipality.create(description: "Peralillo", province_id: 204, region_id:  45, country_id: 90, continent_id: 2 , population: 9729)
Municipality.create(description: "Palmilla", province_id: 204, region_id:  45, country_id: 90, continent_id: 2 , population: 11200)
Municipality.create(description: "Nancagua", province_id: 204, region_id:  45, country_id: 90, continent_id: 2 , population: 15634)
Municipality.create(description: "Lolol", province_id: 204, region_id:  45, country_id: 90, continent_id: 2 , population: 6191)
Municipality.create(description: "Chimbarongo", province_id: 204, region_id:  45, country_id: 90, continent_id: 2 , population: 32316)
Municipality.create(description: "Chépica", province_id: 204, region_id:  45, country_id: 90, continent_id: 2 , population: 13857)
