Municipality.create(description: "Yerbas Buenas", province_id: 207, region_id:  46, country_id: 90, continent_id: 2 , population: 16134)
Municipality.create(description: "Villa Alegre", province_id: 207, region_id:  46, country_id: 90, continent_id: 2 , population: 14725)
Municipality.create(description: "San Javier", province_id: 207, region_id:  46, country_id: 90, continent_id: 2 , population: 37793)
Municipality.create(description: "Retiro", province_id: 207, region_id:  46, country_id: 90, continent_id: 2 , population: 18487)
Municipality.create(description: "Parral", province_id: 207, region_id:  46, country_id: 90, continent_id: 2 , population: 37822)
Municipality.create(description: "Longaví", province_id: 207, region_id:  46, country_id: 90, continent_id: 2 , population: 28161)
Municipality.create(description: "Linares", province_id: 207, region_id:  46, country_id: 90, continent_id: 2 , population: 83249)
Municipality.create(description: "Colbún", province_id: 207, region_id:  46, country_id: 90, continent_id: 2 , population: 17619)
