#encoding: utf-8
Comune.create(description: "Talca", provincia_id: 208, regione_id: 46, country_id: 90, continente_id: 2 , population: 201797)
Comune.create(description: "San Rafael", provincia_id: 208, regione_id: 46, country_id: 90, continente_id: 2 , population: 7674)
Comune.create(description: "San Clemente", provincia_id: 208, regione_id: 46, country_id: 90, continente_id: 2 , population: 37261)
Comune.create(description: "Río Claro", provincia_id: 208, regione_id: 46, country_id: 90, continente_id: 2 , population: 12698)
Comune.create(description: "Pencahue", provincia_id: 208, regione_id: 46, country_id: 90, continente_id: 2 , population: 8315)
Comune.create(description: "Pelarco", provincia_id: 208, regione_id: 46, country_id: 90, continente_id: 2 , population: 7266)
Comune.create(description: "Maule", provincia_id: 208, regione_id: 46, country_id: 90, continente_id: 2 , population: 16837)
Comune.create(description: "Empedrado", provincia_id: 208, regione_id: 46, country_id: 90, continente_id: 2 , population: 4225)
Comune.create(description: "Curepto", provincia_id: 208, regione_id: 46, country_id: 90, continente_id: 2 , population: 10812)
Comune.create(description: "Constitución", provincia_id: 208, regione_id: 46, country_id: 90, continente_id: 2 , population: 46081)
