#encoding: utf-8
Comune.create(description: "Yumbel", provincia_id: 210, regione_id: 47, country_id: 90, continent_id: 2 , population: 20498)
Comune.create(description: "Tucapel", provincia_id: 210, regione_id: 47, country_id: 90, continent_id: 2 , population: 12777)
Comune.create(description: "Santa Bárbara", provincia_id: 210, regione_id: 47, country_id: 90, continent_id: 2 , population: 19970)
Comune.create(description: "San Rosendo", provincia_id: 210, regione_id: 47, country_id: 90, continent_id: 2 , population: 3918)
Comune.create(description: "Quilleco", provincia_id: 210, regione_id: 47, country_id: 90, continent_id: 2 , population: 10428)
Comune.create(description: "Quilaco", provincia_id: 210, regione_id: 47, country_id: 90, continent_id: 2 , population: 4021)
Comune.create(description: "Negrete", provincia_id: 210, regione_id: 47, country_id: 90, continent_id: 2 , population: 8579)
Comune.create(description: "Nacimiento", provincia_id: 210, regione_id: 47, country_id: 90, continent_id: 2 , population: 25971)
Comune.create(description: "Mulchén", provincia_id: 210, regione_id: 47, country_id: 90, continent_id: 2 , population: 29003)
Comune.create(description: "Los Ángeles", provincia_id: 210, regione_id: 47, country_id: 90, continent_id: 2 , population: 166556)
Comune.create(description: "Laja", provincia_id: 210, regione_id: 47, country_id: 90, continent_id: 2 , population: 22404)
Comune.create(description: "Cabrero", provincia_id: 210, regione_id: 47, country_id: 90, continent_id: 2 , population: 25282)
Comune.create(description: "Antuco", provincia_id: 210, regione_id: 47, country_id: 90, continent_id: 2 , population: 3908)
Comune.create(description: "Alto Biobío", provincia_id: 210, regione_id: 47, country_id: 90, continent_id: 2 , population: 7027)
