Municipality.create(description: "Yumbel", province_id: 210, region_id:  47, country_id: 90, continent_id: 2 , population: 20498)
Municipality.create(description: "Tucapel", province_id: 210, region_id:  47, country_id: 90, continent_id: 2 , population: 12777)
Municipality.create(description: "Santa Bárbara", province_id: 210, region_id:  47, country_id: 90, continent_id: 2 , population: 19970)
Municipality.create(description: "San Rosendo", province_id: 210, region_id:  47, country_id: 90, continent_id: 2 , population: 3918)
Municipality.create(description: "Quilleco", province_id: 210, region_id:  47, country_id: 90, continent_id: 2 , population: 10428)
Municipality.create(description: "Quilaco", province_id: 210, region_id:  47, country_id: 90, continent_id: 2 , population: 4021)
Municipality.create(description: "Negrete", province_id: 210, region_id:  47, country_id: 90, continent_id: 2 , population: 8579)
Municipality.create(description: "Nacimiento", province_id: 210, region_id:  47, country_id: 90, continent_id: 2 , population: 25971)
Municipality.create(description: "Mulchén", province_id: 210, region_id:  47, country_id: 90, continent_id: 2 , population: 29003)
Municipality.create(description: "Los Ángeles", province_id: 210, region_id:  47, country_id: 90, continent_id: 2 , population: 166556)
Municipality.create(description: "Laja", province_id: 210, region_id:  47, country_id: 90, continent_id: 2 , population: 22404)
Municipality.create(description: "Cabrero", province_id: 210, region_id:  47, country_id: 90, continent_id: 2 , population: 25282)
Municipality.create(description: "Antuco", province_id: 210, region_id:  47, country_id: 90, continent_id: 2 , population: 3908)
Municipality.create(description: "Alto Biobío", province_id: 210, region_id:  47, country_id: 90, continent_id: 2 , population: 7027)
