Municipality.create(description: "Alcamo", province_id: 20, region_id:  11, country_id: 1, continent_id: 1 , population: 43890)
Municipality.create(description: "Buseto Palizzolo", province_id: 20, region_id:  11, country_id: 1, continent_id: 1 , population: 3197)
Municipality.create(description: "Calatafimi", province_id: 20, region_id:  11, country_id: 1, continent_id: 1 )
Municipality.create(description: "Campobello Di Mazara", province_id: 20, region_id:  11, country_id: 1, continent_id: 1 , population: 11270)
Municipality.create(description: "Castellammare Del Golfo", province_id: 20, region_id:  11, country_id: 1, continent_id: 1 , population: 14573)
Municipality.create(description: "Castelvetrano", province_id: 20, region_id:  11, country_id: 1, continent_id: 1 , population: 30518)
Municipality.create(description: "Custonaci", province_id: 20, region_id:  11, country_id: 1, continent_id: 1 , population: 4814)
Municipality.create(description: "Erice", province_id: 20, region_id:  11, country_id: 1, continent_id: 1 , population: 29338)
Municipality.create(description: "Favignana", province_id: 20, region_id:  11, country_id: 1, continent_id: 1 , population: 4137)
Municipality.create(description: "Gibellina", province_id: 20, region_id:  11, country_id: 1, continent_id: 1 , population: 4677)
Municipality.create(description: "Marsala", province_id: 20, region_id:  11, country_id: 1, continent_id: 1 , population: 77784)
Municipality.create(description: "Mazara Del Vallo", province_id: 20, region_id:  11, country_id: 1, continent_id: 1 , population: 50377)
Municipality.create(description: "Paceco", province_id: 20, region_id:  11, country_id: 1, continent_id: 1 , population: 10949)
Municipality.create(description: "Pantelleria", province_id: 20, region_id:  11, country_id: 1, continent_id: 1 , population: 7224)
Municipality.create(description: "Partanna", province_id: 20, region_id:  11, country_id: 1, continent_id: 1 , population: 11379)
Municipality.create(description: "Petrosino", province_id: 20, region_id:  11, country_id: 1, continent_id: 1 , population: 7330)
Municipality.create(description: "Poggioreale", province_id: 20, region_id:  11, country_id: 1, continent_id: 1 , population: 1715)
Municipality.create(description: "Salaparuta", province_id: 20, region_id:  11, country_id: 1, continent_id: 1 , population: 1835)
Municipality.create(description: "Salemi", province_id: 20, region_id:  11, country_id: 1, continent_id: 1 , population: 11578)
Municipality.create(description: "San Vito Lo Capo", province_id: 20, region_id:  11, country_id: 1, continent_id: 1 , population: 3798)
Municipality.create(description: "Santa Ninfa", province_id: 20, region_id:  11, country_id: 1, continent_id: 1 , population: 5087)
Municipality.create(description: "Trapani", province_id: 20, region_id:  11, country_id: 1, continent_id: 1 , population: 68346)
Municipality.create(description: "Valderice", province_id: 20, region_id:  11, country_id: 1, continent_id: 1 , population: 11374)
Municipality.create(description: "Vita", province_id: 20, region_id:  11, country_id: 1, continent_id: 1 , population: 2435)
