#encoding: utf-8
Comune.create(description: "Alcamo", provincia_id: 20, regione_id: 11, country_id: 1, continente_id: 1 , population: 43890)
Comune.create(description: "Buseto Palizzolo", provincia_id: 20, regione_id: 11, country_id: 1, continente_id: 1 , population: 3197)
Comune.create(description: "Calatafimi", provincia_id: 20, regione_id: 11, country_id: 1, continente_id: 1 )
Comune.create(description: "Campobello Di Mazara", provincia_id: 20, regione_id: 11, country_id: 1, continente_id: 1 , population: 11270)
Comune.create(description: "Castellammare Del Golfo", provincia_id: 20, regione_id: 11, country_id: 1, continente_id: 1 , population: 14573)
Comune.create(description: "Castelvetrano", provincia_id: 20, regione_id: 11, country_id: 1, continente_id: 1 , population: 30518)
Comune.create(description: "Custonaci", provincia_id: 20, regione_id: 11, country_id: 1, continente_id: 1 , population: 4814)
Comune.create(description: "Erice", provincia_id: 20, regione_id: 11, country_id: 1, continente_id: 1 , population: 29338)
Comune.create(description: "Favignana", provincia_id: 20, regione_id: 11, country_id: 1, continente_id: 1 , population: 4137)
Comune.create(description: "Gibellina", provincia_id: 20, regione_id: 11, country_id: 1, continente_id: 1 , population: 4677)
Comune.create(description: "Marsala", provincia_id: 20, regione_id: 11, country_id: 1, continente_id: 1 , population: 77784)
Comune.create(description: "Mazara Del Vallo", provincia_id: 20, regione_id: 11, country_id: 1, continente_id: 1 , population: 50377)
Comune.create(description: "Paceco", provincia_id: 20, regione_id: 11, country_id: 1, continente_id: 1 , population: 10949)
Comune.create(description: "Pantelleria", provincia_id: 20, regione_id: 11, country_id: 1, continente_id: 1 , population: 7224)
Comune.create(description: "Partanna", provincia_id: 20, regione_id: 11, country_id: 1, continente_id: 1 , population: 11379)
Comune.create(description: "Petrosino", provincia_id: 20, regione_id: 11, country_id: 1, continente_id: 1 , population: 7330)
Comune.create(description: "Poggioreale", provincia_id: 20, regione_id: 11, country_id: 1, continente_id: 1 , population: 1715)
Comune.create(description: "Salaparuta", provincia_id: 20, regione_id: 11, country_id: 1, continente_id: 1 , population: 1835)
Comune.create(description: "Salemi", provincia_id: 20, regione_id: 11, country_id: 1, continente_id: 1 , population: 11578)
Comune.create(description: "San Vito Lo Capo", provincia_id: 20, regione_id: 11, country_id: 1, continente_id: 1 , population: 3798)
Comune.create(description: "Santa Ninfa", provincia_id: 20, regione_id: 11, country_id: 1, continente_id: 1 , population: 5087)
Comune.create(description: "Trapani", provincia_id: 20, regione_id: 11, country_id: 1, continente_id: 1 , population: 68346)
Comune.create(description: "Valderice", provincia_id: 20, regione_id: 11, country_id: 1, continente_id: 1 , population: 11374)
Comune.create(description: "Vita", provincia_id: 20, regione_id: 11, country_id: 1, continente_id: 1 , population: 2435)
