Comune.create(description: "Yungay", provincia_id: 212, regione_id: 47, country_id: 90, continent_id: 2 , population: 16814)
Comune.create(description: "Treguaco", provincia_id: 212, regione_id: 47, country_id: 90, continent_id: 2 , population: 5296)
Comune.create(description: "San Nicolás", provincia_id: 212, regione_id: 47, country_id: 90, continent_id: 2 , population: 9741)
Comune.create(description: "San Ignacio", provincia_id: 212, regione_id: 47, country_id: 90, continent_id: 2 , population: 16106)
Comune.create(description: "San Fabián", provincia_id: 212, regione_id: 47, country_id: 90, continent_id: 2 , population: 3646)
Comune.create(description: "San Carlos", provincia_id: 212, regione_id: 47, country_id: 90, continent_id: 2 , population: 50088)
Comune.create(description: "Ránquil", provincia_id: 212, regione_id: 47, country_id: 90, continent_id: 2 , population: 5683)
Comune.create(description: "Quirihue", provincia_id: 212, regione_id: 47, country_id: 90, continent_id: 2 , population: 11429)
Comune.create(description: "Quillón", provincia_id: 212, regione_id: 47, country_id: 90, continent_id: 2 , population: 15146)
Comune.create(description: "Portezuelo", provincia_id: 212, regione_id: 47, country_id: 90, continent_id: 2 , population: 5470)
Comune.create(description: "Pinto", provincia_id: 212, regione_id: 47, country_id: 90, continent_id: 2 , population: 9875)
Comune.create(description: "Pemuco", provincia_id: 212, regione_id: 47, country_id: 90, continent_id: 2 , population: 8821)
Comune.create(description: "Ñiquén", provincia_id: 212, regione_id: 47, country_id: 90, continent_id: 2 , population: 11421)
Comune.create(description: "Ninhue", provincia_id: 212, regione_id: 47, country_id: 90, continent_id: 2 , population: 5738)
Comune.create(description: "El Carmen", provincia_id: 212, regione_id: 47, country_id: 90, continent_id: 2 , population: 12845)
Comune.create(description: "Coihueco", provincia_id: 212, regione_id: 47, country_id: 90, continent_id: 2 , population: 23583)
Comune.create(description: "Coelemu", provincia_id: 212, regione_id: 47, country_id: 90, continent_id: 2 , population: 16082)
Comune.create(description: "Cobquecura", provincia_id: 212, regione_id: 47, country_id: 90, continent_id: 2 , population: 5687)
Comune.create(description: "Chillán Viejo", provincia_id: 212, regione_id: 47, country_id: 90, continent_id: 2 , population: 22084)
Comune.create(description: "Chillán", provincia_id: 212, regione_id: 47, country_id: 90, continent_id: 2 , population: 161953)
Comune.create(description: "Bulnes", provincia_id: 212, regione_id: 47, country_id: 90, continent_id: 2 , population: 20595)
