Municipality.create(description: "Victoria", province_id: 214, region_id:  48, country_id: 90, continent_id: 2 , population: 33501)
Municipality.create(description: "Traiguén", province_id: 214, region_id:  48, country_id: 90, continent_id: 2 , population: 19534)
Municipality.create(description: "Renaico", province_id: 214, region_id:  48, country_id: 90, continent_id: 2 , population: 9128)
Municipality.create(description: "Purén", province_id: 214, region_id:  48, country_id: 90, continent_id: 2 , population: 12868)
Municipality.create(description: "Lumaco", province_id: 214, region_id:  48, country_id: 90, continent_id: 2 , population: 11405)
Municipality.create(description: "Los Sauces", province_id: 214, region_id:  48, country_id: 90, continent_id: 2 , population: 7581)
Municipality.create(description: "Lonquimay", province_id: 214, region_id:  48, country_id: 90, continent_id: 2 , population: 10237)
Municipality.create(description: "Ercilla", province_id: 214, region_id:  48, country_id: 90, continent_id: 2 , population: 9041)
Municipality.create(description: "Curacautín", province_id: 214, region_id:  48, country_id: 90, continent_id: 2 , population: 16970)
Municipality.create(description: "Collipulli", province_id: 214, region_id:  48, country_id: 90, continent_id: 2 , population: 22354)
Municipality.create(description: "Angol", province_id: 214, region_id:  48, country_id: 90, continent_id: 2 , population: 48996)
