Municipality.create(description: "Valdivia", province_id: 216, region_id:  49, country_id: 90, continent_id: 2 , population: 140559)
Municipality.create(description: "Panguipulli", province_id: 216, region_id:  49, country_id: 90, continent_id: 2 , population: 33273)
Municipality.create(description: "Paillaco", province_id: 216, region_id:  49, country_id: 90, continent_id: 2 , population: 19237)
Municipality.create(description: "San José de la Mariquina", province_id: 216, region_id:  49, country_id: 90, continent_id: 2 , population: 18223)
Municipality.create(description: "Máfil", province_id: 216, region_id:  49, country_id: 90, continent_id: 2 , population: 7213)
Municipality.create(description: "Los Lagos", province_id: 216, region_id:  49, country_id: 90, continent_id: 2 , population: 20168)
Municipality.create(description: "Lanco", province_id: 216, region_id:  49, country_id: 90, continent_id: 2 , population: 15107)
Municipality.create(description: "Corral", province_id: 216, region_id:  49, country_id: 90, continent_id: 2 , population: 5463)
