Municipality.create(description: "Quinchao", province_id: 217, region_id:  50, country_id: 90, continent_id: 2 , population: 8976)
Municipality.create(description: "Quemchi", province_id: 217, region_id:  50, country_id: 90, continent_id: 2 , population: 8689)
Municipality.create(description: "Quellón", province_id: 217, region_id:  50, country_id: 90, continent_id: 2 , population: 21823)
Municipality.create(description: "Queilén", province_id: 217, region_id:  50, country_id: 90, continent_id: 2 , population: 5138)
Municipality.create(description: "Puqueldón", province_id: 217, region_id:  50, country_id: 90, continent_id: 2 , population: 4160)
Municipality.create(description: "Dalcahue", province_id: 217, region_id:  50, country_id: 90, continent_id: 2 , population: 10693)
Municipality.create(description: "Curaco de Vélez", province_id: 217, region_id:  50, country_id: 90, continent_id: 2 , population: 3403)
Municipality.create(description: "Chonchi", province_id: 217, region_id:  50, country_id: 90, continent_id: 2 , population: 12572)
Municipality.create(description: "Castro", province_id: 217, region_id:  50, country_id: 90, continent_id: 2 , population: 39366)
Municipality.create(description: "Ancud", province_id: 217, region_id:  50, country_id: 90, continent_id: 2 , population: 39946)
