Comune.create(description: "Quinchao", provincia_id: 217, regione_id: 50, country_id: 90, continent_id: 2 , population: 8976)
Comune.create(description: "Quemchi", provincia_id: 217, regione_id: 50, country_id: 90, continent_id: 2 , population: 8689)
Comune.create(description: "Quellón", provincia_id: 217, regione_id: 50, country_id: 90, continent_id: 2 , population: 21823)
Comune.create(description: "Queilén", provincia_id: 217, regione_id: 50, country_id: 90, continent_id: 2 , population: 5138)
Comune.create(description: "Puqueldón", provincia_id: 217, regione_id: 50, country_id: 90, continent_id: 2 , population: 4160)
Comune.create(description: "Dalcahue", provincia_id: 217, regione_id: 50, country_id: 90, continent_id: 2 , population: 10693)
Comune.create(description: "Curaco de Vélez", provincia_id: 217, regione_id: 50, country_id: 90, continent_id: 2 , population: 3403)
Comune.create(description: "Chonchi", provincia_id: 217, regione_id: 50, country_id: 90, continent_id: 2 , population: 12572)
Comune.create(description: "Castro", provincia_id: 217, regione_id: 50, country_id: 90, continent_id: 2 , population: 39366)
Comune.create(description: "Ancud", provincia_id: 217, regione_id: 50, country_id: 90, continent_id: 2 , population: 39946)
