#encoding: utf-8
Comune.create(:description => "Isca Sullo Jonio", :provincia_id => 21, :regione_id => 7)
Comune.create(:description => "Albi", :provincia_id => 21, :regione_id => 7, :population => 1105)
Comune.create(:description => "Amaroni", :provincia_id => 21, :regione_id => 7, :population => 2007)
Comune.create(:description => "Amato", :provincia_id => 21, :regione_id => 7, :population => 874)
Comune.create(:description => "Andali", :provincia_id => 21, :regione_id => 7, :population => 954)
Comune.create(:description => "Argusto", :provincia_id => 21, :regione_id => 7, :population => 568)
Comune.create(:description => "Badolato", :provincia_id => 21, :regione_id => 7, :population => 3436)
Comune.create(:description => "Belcastro", :provincia_id => 21, :regione_id => 7, :population => 1400)
Comune.create(:description => "Borgia", :provincia_id => 21, :regione_id => 7, :population => 7049)
Comune.create(:description => "Botricello", :provincia_id => 21, :regione_id => 7, :population => 4586)
Comune.create(:description => "Caraffa Di Catanzaro", :provincia_id => 21, :regione_id => 7, :population => 2084)
Comune.create(:description => "Cardinale", :provincia_id => 21, :regione_id => 7, :population => 2613)
Comune.create(:description => "Carlopoli", :provincia_id => 21, :regione_id => 7, :population => 1787)
Comune.create(:description => "Catanzaro", :provincia_id => 21, :regione_id => 7, :population => 95251)
Comune.create(:description => "Cenadi", :provincia_id => 21, :regione_id => 7, :population => 649)
Comune.create(:description => "Centrache", :provincia_id => 21, :regione_id => 7, :population => 494)
Comune.create(:description => "Cerva", :provincia_id => 21, :regione_id => 7, :population => 1342)
Comune.create(:description => "Chiaravalle Centrale", :provincia_id => 21, :regione_id => 7, :population => 7120)
Comune.create(:description => "Cicala", :provincia_id => 21, :regione_id => 7, :population => 1033)
Comune.create(:description => "Conflenti", :provincia_id => 21, :regione_id => 7, :population => 1681)
Comune.create(:description => "Cortale", :provincia_id => 21, :regione_id => 7, :population => 2436)
Comune.create(:description => "Cropani", :provincia_id => 21, :regione_id => 7, :population => 3286)
Comune.create(:description => "Curinga", :provincia_id => 21, :regione_id => 7, :population => 6648)
Comune.create(:description => "Davoli", :provincia_id => 21, :regione_id => 7, :population => 5238)
Comune.create(:description => "Decollatura", :provincia_id => 21, :regione_id => 7, :population => 3489)
Comune.create(:description => "Falerna", :provincia_id => 21, :regione_id => 7, :population => 3602)
Comune.create(:description => "Feroleto Antico", :provincia_id => 21, :regione_id => 7, :population => 2114)
Comune.create(:description => "Fossato Serralta", :provincia_id => 21, :regione_id => 7, :population => 660)
Comune.create(:description => "Gagliato", :provincia_id => 21, :regione_id => 7, :population => 563)
Comune.create(:description => "Gasperina", :provincia_id => 21, :regione_id => 7, :population => 2203)
Comune.create(:description => "Gimigliano", :provincia_id => 21, :regione_id => 7, :population => 3612)
Comune.create(:description => "Girifalco", :provincia_id => 21, :regione_id => 7, :population => 6452)
Comune.create(:description => "Gizzeria", :provincia_id => 21, :regione_id => 7, :population => 3833)
Comune.create(:description => "Guardavalle", :provincia_id => 21, :regione_id => 7, :population => 5315)
Comune.create(:description => "Jacurso", :provincia_id => 21, :regione_id => 7, :population => 839)
Comune.create(:description => "Lamezia Terme", :provincia_id => 21, :regione_id => 7, :population => 70501)
Comune.create(:description => "Magisano", :provincia_id => 21, :regione_id => 7, :population => 1318)
Comune.create(:description => "Maida", :provincia_id => 21, :regione_id => 7, :population => 4337)
Comune.create(:description => "Marcedusa", :provincia_id => 21, :regione_id => 7, :population => 556)
Comune.create(:description => "Marcellinara", :provincia_id => 21, :regione_id => 7, :population => 2198)
Comune.create(:description => "Martirano", :provincia_id => 21, :regione_id => 7, :population => 1036)
Comune.create(:description => "Martirano Lombardo", :provincia_id => 21, :regione_id => 7, :population => 1402)
Comune.create(:description => "Miglierina", :provincia_id => 21, :regione_id => 7, :population => 912)
Comune.create(:description => "Montauro", :provincia_id => 21, :regione_id => 7, :population => 1315)
Comune.create(:description => "Montepaone", :provincia_id => 21, :regione_id => 7, :population => 4442)
Comune.create(:description => "Motta Santa Lucia", :provincia_id => 21, :regione_id => 7, :population => 848)
Comune.create(:description => "Nocera Tirinese", :provincia_id => 21, :regione_id => 7)
Comune.create(:description => "Olivadi", :provincia_id => 21, :regione_id => 7, :population => 643)
Comune.create(:description => "Palermiti", :provincia_id => 21, :regione_id => 7, :population => 1436)
Comune.create(:description => "Pentone", :provincia_id => 21, :regione_id => 7, :population => 2197)
Comune.create(:description => "Petrizzi", :provincia_id => 21, :regione_id => 7, :population => 1298)
Comune.create(:description => "Pianopoli", :provincia_id => 21, :regione_id => 7, :population => 2315)
Comune.create(:description => "Platania", :provincia_id => 21, :regione_id => 7, :population => 2423)
Comune.create(:description => "San Floro", :provincia_id => 21, :regione_id => 7, :population => 594)
Comune.create(:description => "San Pietro A Maida", :provincia_id => 21, :regione_id => 7, :population => 4282)
Comune.create(:description => "San Pietro Apostolo", :provincia_id => 21, :regione_id => 7, :population => 1925)
Comune.create(:description => "San Sostene", :provincia_id => 21, :regione_id => 7, :population => 1134)
Comune.create(:description => "San Vito Sullo Ionio", :provincia_id => 21, :regione_id => 7, :population => 2012)
Comune.create(:description => "Santa Caterina Dello Ionio", :provincia_id => 21, :regione_id => 7, :population => 2280)
Comune.create(:description => "Satriano", :provincia_id => 21, :regione_id => 7, :population => 3102)
Comune.create(:description => "Sellia", :provincia_id => 21, :regione_id => 7, :population => 596)
Comune.create(:description => "Sellia Marina", :provincia_id => 21, :regione_id => 7, :population => 5764)
Comune.create(:description => "Serrastretta", :provincia_id => 21, :regione_id => 7, :population => 3588)
Comune.create(:description => "Sersale", :provincia_id => 21, :regione_id => 7, :population => 5166)
Comune.create(:description => "Settingiano", :provincia_id => 21, :regione_id => 7, :population => 2319)
Comune.create(:description => "Simeri Crichi", :provincia_id => 21, :regione_id => 7, :population => 3836)
Comune.create(:description => "Sorbo San Basile", :provincia_id => 21, :regione_id => 7, :population => 932)
Comune.create(:description => "Soverato", :provincia_id => 21, :regione_id => 7, :population => 10034)
Comune.create(:description => "Soveria Mannelli", :provincia_id => 21, :regione_id => 7, :population => 3511)
Comune.create(:description => "Soveria Simeri", :provincia_id => 21, :regione_id => 7, :population => 1632)
Comune.create(:description => "Squillace", :provincia_id => 21, :regione_id => 7, :population => 3189)
Comune.create(:description => "Staletti", :provincia_id => 21, :regione_id => 7, :population => 2264)
Comune.create(:description => "Taverna", :provincia_id => 21, :regione_id => 7, :population => 2668)
Comune.create(:description => "Tiriolo", :provincia_id => 21, :regione_id => 7, :population => 4073)
Comune.create(:description => "Torre Di Ruggiero", :provincia_id => 21, :regione_id => 7, :population => 1346)
Comune.create(:description => "Vallefiorita", :provincia_id => 21, :regione_id => 7, :population => 2434)
Comune.create(:description => "Zagarise", :provincia_id => 21, :regione_id => 7, :population => 1889)
Comune.create(:description => "Petrona'", :provincia_id => 21, :regione_id => 7, :population => 3010)
Comune.create(:description => "San Mango D'Aquino", :provincia_id => 21, :regione_id => 7, :population => 1877)
Comune.create(:description => "Sant'Andrea Apostolo Dello Jonio", :provincia_id => 21, :regione_id => 7)
