Comune.create(description: "Isca Sullo Jonio", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 )
Comune.create(description: "Albi", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 1105)
Comune.create(description: "Amaroni", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 2007)
Comune.create(description: "Amato", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 874)
Comune.create(description: "Andali", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 954)
Comune.create(description: "Argusto", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 568)
Comune.create(description: "Badolato", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 3436)
Comune.create(description: "Belcastro", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 1400)
Comune.create(description: "Borgia", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 7049)
Comune.create(description: "Botricello", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 4586)
Comune.create(description: "Caraffa Di Catanzaro", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 2084)
Comune.create(description: "Cardinale", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 2613)
Comune.create(description: "Carlopoli", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 1787)
Comune.create(description: "Catanzaro", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 95251)
Comune.create(description: "Cenadi", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 649)
Comune.create(description: "Centrache", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 494)
Comune.create(description: "Cerva", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 1342)
Comune.create(description: "Chiaravalle Centrale", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 7120)
Comune.create(description: "Cicala", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 1033)
Comune.create(description: "Conflenti", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 1681)
Comune.create(description: "Cortale", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 2436)
Comune.create(description: "Cropani", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 3286)
Comune.create(description: "Curinga", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 6648)
Comune.create(description: "Davoli", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 5238)
Comune.create(description: "Decollatura", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 3489)
Comune.create(description: "Falerna", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 3602)
Comune.create(description: "Feroleto Antico", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 2114)
Comune.create(description: "Fossato Serralta", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 660)
Comune.create(description: "Gagliato", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 563)
Comune.create(description: "Gasperina", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 2203)
Comune.create(description: "Gimigliano", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 3612)
Comune.create(description: "Girifalco", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 6452)
Comune.create(description: "Gizzeria", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 3833)
Comune.create(description: "Guardavalle", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 5315)
Comune.create(description: "Jacurso", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 839)
Comune.create(description: "Lamezia Terme", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 70501)
Comune.create(description: "Magisano", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 1318)
Comune.create(description: "Maida", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 4337)
Comune.create(description: "Marcedusa", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 556)
Comune.create(description: "Marcellinara", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 2198)
Comune.create(description: "Martirano", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 1036)
Comune.create(description: "Martirano Lombardo", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 1402)
Comune.create(description: "Miglierina", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 912)
Comune.create(description: "Montauro", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 1315)
Comune.create(description: "Montepaone", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 4442)
Comune.create(description: "Motta Santa Lucia", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 848)
Comune.create(description: "Nocera Tirinese", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 )
Comune.create(description: "Olivadi", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 643)
Comune.create(description: "Palermiti", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 1436)
Comune.create(description: "Pentone", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 2197)
Comune.create(description: "Petrizzi", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 1298)
Comune.create(description: "Pianopoli", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 2315)
Comune.create(description: "Platania", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 2423)
Comune.create(description: "San Floro", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 594)
Comune.create(description: "San Pietro A Maida", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 4282)
Comune.create(description: "San Pietro Apostolo", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 1925)
Comune.create(description: "San Sostene", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 1134)
Comune.create(description: "San Vito Sullo Ionio", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 2012)
Comune.create(description: "Santa Caterina Dello Ionio", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 2280)
Comune.create(description: "Satriano", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 3102)
Comune.create(description: "Sellia", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 596)
Comune.create(description: "Sellia Marina", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 5764)
Comune.create(description: "Serrastretta", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 3588)
Comune.create(description: "Sersale", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 5166)
Comune.create(description: "Settingiano", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 2319)
Comune.create(description: "Simeri Crichi", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 3836)
Comune.create(description: "Sorbo San Basile", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 932)
Comune.create(description: "Soverato", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 10034)
Comune.create(description: "Soveria Mannelli", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 3511)
Comune.create(description: "Soveria Simeri", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 1632)
Comune.create(description: "Squillace", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 3189)
Comune.create(description: "Staletti", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 2264)
Comune.create(description: "Taverna", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 2668)
Comune.create(description: "Tiriolo", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 4073)
Comune.create(description: "Torre Di Ruggiero", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 1346)
Comune.create(description: "Vallefiorita", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 2434)
Comune.create(description: "Zagarise", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 1889)
Comune.create(description: "Petrona'", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 3010)
Comune.create(description: "San Mango D'Aquino", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 , population: 1877)
Comune.create(description: "Sant'Andrea Apostolo Dello Jonio", province_id: 21, region_id:  7, country_id: 1, continent_id: 1 )
