continent = Continente.find_by(description: 'Europe')
state = Country.find_by(description: 'Greece')
region = Regione.create(description: "Ήπειρος", country: state, continente: continent, geoname_id: 6697804)
provincia = region.provincias.create(description: "Άρτα", country: state, continente: continent,  geoname_id: 264545, population: 0)
provincia.comunes.create(description: "Αρταίων", regione: region, country: state, continente: continent, geoname_id: 6943434, population: 0)
provincia.comunes.create(description: "Γεωργίου Καραϊσκάκη", regione: region, country: state, continente: continent, geoname_id: 8133717, population: 7131)
provincia.comunes.create(description: "Κεντρικών Τζουμέρκων", regione: region, country: state, continente: continent, geoname_id: 8133816, population: 7862)
provincia.comunes.create(description: "Νικολάου Σκουφά", regione: region, country: state, continente: continent, geoname_id: 8133727, population: 14491)
provincia = region.provincias.create(description: "Θεσπρωτία", country: state, continente: continent,  geoname_id: 252941, population: 0)
provincia.comunes.create(description: "Ηγουμενίτσας", regione: region, country: state, continente: continent, geoname_id: 8133725, population: 24130)
provincia.comunes.create(description: "Σουλίου", regione: region, country: state, continente: continent, geoname_id: 8133726, population: 10379)
provincia.comunes.create(description: "Φιλιατών", regione: region, country: state, continente: continent, geoname_id: 8133728, population: 9092)
provincia = region.provincias.create(description: "Ιωάννινα", country: state, continente: continent,  geoname_id: 261777, population: 0)
provincia.comunes.create(description: "Βορείων Τζουμέρκων", regione: region, country: state, continente: continent, geoname_id: 8133719, population: 4361)
provincia.comunes.create(description: "Δωδώνης", regione: region, country: state, continente: continent, geoname_id: 8133720, population: 10482)
provincia.comunes.create(description: "Ζίτσας", regione: region, country: state, continente: continent, geoname_id: 8133722, population: 14923)
provincia.comunes.create(description: "Ζαγορίου", regione: region, country: state, continente: continent, geoname_id: 8133721, population: 4348)
provincia.comunes.create(description: "Ιωαννιτών", regione: region, country: state, continente: continent, geoname_id: 7303595, population: 0)
provincia.comunes.create(description: "Κόνιτσας", regione: region, country: state, continente: continent, geoname_id: 8133734, population: 7648)
provincia.comunes.create(description: "Μετσόβου", regione: region, country: state, continente: continent, geoname_id: 8133735, population: 7177)
provincia.comunes.create(description: "Πωγωνίου", regione: region, country: state, continente: continent, geoname_id: 8133736, population: 8987)
provincia = region.provincias.create(description: "Πρέβεζα", country: state, continente: continent,  geoname_id: 254695, population: 0)
provincia.comunes.create(description: "Ζηρού", regione: region, country: state, continente: continent, geoname_id: 8133741, population: 15410)
provincia.comunes.create(description: "Πάργας", regione: region, country: state, continente: continent, geoname_id: 8133742, population: 12597)
provincia.comunes.create(description: "Πρέβεζας", regione: region, country: state, continente: continent, geoname_id: 8133743, population: 30137)
region = Regione.create(description: "Ανατολική Μακεδονία και Θράκη", country: state, continente: continent, geoname_id: 6697803)
provincia = region.provincias.create(description: "Έβρος", country: state, continente: continent,  geoname_id: 736287, population: 0)
provincia.comunes.create(description: "Αλεξανδρούπολης", regione: region, country: state, continente: continent, geoname_id: 8133779, population: 66125)
provincia.comunes.create(description: "Διδυμοτείχου", regione: region, country: state, continente: continent, geoname_id: 8133778, population: 23380)
provincia.comunes.create(description: "Ορεστιάδας", regione: region, country: state, continente: continent, geoname_id: 8133900, population: 39375)
provincia.comunes.create(description: "Σαμοθράκης", regione: region, country: state, continente: continent, geoname_id: 8133889, population: 2712)
provincia.comunes.create(description: "Σουφλίου", regione: region, country: state, continente: continent, geoname_id: 8133890, population: 17961)
provincia = region.provincias.create(description: "Δράμα", country: state, continente: continent,  geoname_id: 736363, population: 0)
provincia.comunes.create(description: "Δοξάτου", regione: region, country: state, continente: continent, geoname_id: 8133891, population: 16883)
provincia.comunes.create(description: "Δράμας", regione: region, country: state, continente: continent, geoname_id: 8133892, population: 75367)
provincia.comunes.create(description: "Κάτω Νευροκοπίου", regione: region, country: state, continente: continent, geoname_id: 8133895, population: 7289)
provincia.comunes.create(description: "Παρανεστίου", regione: region, country: state, continente: continent, geoname_id: 8133896, population: 5114)
provincia.comunes.create(description: "Προσοτσάνης", regione: region, country: state, continente: continent, geoname_id: 8133897, population: 15531)
provincia = region.provincias.create(description: "Καβάλα", country: state, continente: continent,  geoname_id: 735857, population: 0)
provincia.comunes.create(description: "Θάσος", regione: region, country: state, continente: continent, geoname_id: 8133898, population: 13451)
provincia.comunes.create(description: "Καβάλας", regione: region, country: state, continente: continent, geoname_id: 8133899, population: 74186)
provincia.comunes.create(description: "Νέστου", regione: region, country: state, continente: continent, geoname_id: 8133878, population: 22218)
provincia.comunes.create(description: "Παγγαίου", regione: region, country: state, continente: continent, geoname_id: 8133879, population: 31644)
provincia = region.provincias.create(description: "Ξάνθη", country: state, continente: continent,  geoname_id: 733839, population: 0)
provincia.comunes.create(description: "Αβδήρων", regione: region, country: state, continente: continent, geoname_id: 8133835, population: 18262)
provincia.comunes.create(description: "Μύκης", regione: region, country: state, continente: continent, geoname_id: 8133836, population: 16091)
provincia.comunes.create(description: "Ξάνθης", regione: region, country: state, continente: continent, geoname_id: 8133837, population: 56383)
provincia.comunes.create(description: "Τοπείρου", regione: region, country: state, continente: continent, geoname_id: 8133838, population: 12223)
provincia = region.provincias.create(description: "Ροδόπη", country: state, continente: continent,  geoname_id: 734375, population: 0)
provincia.comunes.create(description: "Αρριανών", regione: region, country: state, continente: continent, geoname_id: 8133825, population: 18259)
provincia.comunes.create(description: "Ιάσμου", regione: region, country: state, continente: continent, geoname_id: 8133826, population: 14851)
provincia.comunes.create(description: "Κομοτηνής", regione: region, country: state, continente: continent, geoname_id: 8133827, population: 51501)
provincia.comunes.create(description: "Μαρωνείας - Σαπών", regione: region, country: state, continente: continent, geoname_id: 8133834, population: 16626)
region = Regione.create(description: "Αττική", country: state, continente: continent, geoname_id: 6692632)
provincia = region.provincias.create(description: "Nomarchía Anatolikís Attikís", country: state, continente: continent,  geoname_id: 445406, population: 0)
provincia.comunes.create(description: "Αχαρνών", regione: region, country: state, continente: continent, geoname_id: 8133704, population: 100743)
provincia.comunes.create(description: "Βάρης - Βούλας - Βουλιαγμένης", regione: region, country: state, continente: continent, geoname_id: 8133946, population: 48399)
provincia.comunes.create(description: "Διονύσου", regione: region, country: state, continente: continent, geoname_id: 8133921, population: 40193)
provincia.comunes.create(description: "Κρωπίας", regione: region, country: state, continente: continent, geoname_id: 8133922, population: 30307)
provincia.comunes.create(description: "Λαυρεωτικής", regione: region, country: state, continente: continent, geoname_id: 8133923, population: 25102)
provincia.comunes.create(description: "Μαραθώνος", regione: region, country: state, continente: continent, geoname_id: 8133924, population: 33423)
provincia.comunes.create(description: "Μαρκοπούλου Μεσογαίας", regione: region, country: state, continente: continent, geoname_id: 8133947, population: 20040)
provincia.comunes.create(description: "Παιανίας", regione: region, country: state, continente: continent, geoname_id: 8133684, population: 26668)
provincia.comunes.create(description: "Παλλήνης", regione: region, country: state, continente: continent, geoname_id: 8133685, population: 54415)
provincia.comunes.create(description: "Ραφήνας - Πικερμίου", regione: region, country: state, continente: continent, geoname_id: 8133686, population: 20266)
provincia.comunes.create(description: "Σαρωνικού", regione: region, country: state, continente: continent, geoname_id: 8133687, population: 29002)
provincia.comunes.create(description: "Σπάτων - Αρτέμιδος", regione: region, country: state, continente: continent, geoname_id: 8133772, population: 33821)
provincia.comunes.create(description: "Ωρωπού", regione: region, country: state, continente: continent, geoname_id: 8133773, population: 33769)
provincia = region.provincias.create(description: "Nomarchía Dytikís Attikís", country: state, continente: continent,  geoname_id: 445407, population: 0)
provincia.comunes.create(description: "Ασπροπύργου", regione: region, country: state, continente: continent, geoname_id: 8133961, population: 30251)
provincia.comunes.create(description: "Ελευσίνας", regione: region, country: state, continente: continent, geoname_id: 8133883, population: 29902)
provincia.comunes.create(description: "Μάνδρας - Ειδυλλίας", regione: region, country: state, continente: continent, geoname_id: 8133884, population: 17885)
provincia.comunes.create(description: "Μεγαρέων", regione: region, country: state, continente: continent, geoname_id: 8133885, population: 36924)
provincia.comunes.create(description: "Φυλής", regione: region, country: state, continente: continent, geoname_id: 8133808, population: 45965)
provincia = region.provincias.create(description: "Nomós Piraiós", country: state, continente: continent,  geoname_id: 406101, population: 0)
provincia.comunes.create(description: "Ύδρα", regione: region, country: state, continente: continent, geoname_id: 8133769, population: 1966)
provincia.comunes.create(description: "Αίγινας", regione: region, country: state, continente: continent, geoname_id: 8133696, population: 13056)
provincia.comunes.create(description: "Αγκιστρίου", regione: region, country: state, continente: continent, geoname_id: 8133874, population: 1142)
provincia.comunes.create(description: "Κερατσινίου - Δραπετσώνας", regione: region, country: state, continente: continent, geoname_id: 8133965, population: 91045)
provincia.comunes.create(description: "Κορυδαλλού", regione: region, country: state, continente: continent, geoname_id: 8133688, population: 63445)
provincia.comunes.create(description: "Κυθήρων", regione: region, country: state, continente: continent, geoname_id: 8133702, population: 4041)
provincia.comunes.create(description: "Νίκαιας - Αγίου Ι. Ρέντη", regione: region, country: state, continente: continent, geoname_id: 8133809, population: 105430)
provincia.comunes.create(description: "Πειραιώς", regione: region, country: state, continente: continent, geoname_id: 8133777, population: 163688)
provincia.comunes.create(description: "Περάματος", regione: region, country: state, continente: continent, geoname_id: 8133974, population: 25389)
provincia.comunes.create(description: "Πόρου", regione: region, country: state, continente: continent, geoname_id: 8133709, population: 4282)
provincia.comunes.create(description: "Σαλαμίνας", regione: region, country: state, continente: continent, geoname_id: 8133766, population: 39283)
provincia.comunes.create(description: "Σπετσών", regione: region, country: state, continente: continent, geoname_id: 8133767, population: 4027)
provincia.comunes.create(description: "Τροιζηνίας-Μεθάνων", regione: region, country: state, continente: continent, geoname_id: 8133768, population: 7143)
provincia = region.provincias.create(description: "Αττική", country: state, continente: continent,  geoname_id: 264353, population: 0)
provincia.comunes.create(description: "Kastélli", regione: region, country: state, continente: continent, geoname_id: 260809, population: 0)
provincia.comunes.create(description: "Khlóï", regione: region, country: state, continente: continent, geoname_id: 259961, population: 0)
provincia.comunes.create(description: "Áyios Spirídhon", regione: region, country: state, continente: continent, geoname_id: 263733, population: 0)
provincia.comunes.create(description: "Ζωγράφος", regione: region, country: state, continente: continent, geoname_id: 8358544, population: 71026)
provincia.comunes.create(description: "Πειραιάς", regione: region, country: state, continente: continent, geoname_id: 255274, population: 163688)
provincia = region.provincias.create(description: "Νομαρχία Αθήνας", country: state, continente: continent,  geoname_id: 445408, population: 0)
provincia.comunes.create(description: "Αγίας Βαρβάρας", regione: region, country: state, continente: continent, geoname_id: 8133771, population: 26550)
provincia.comunes.create(description: "Αγίας Παρασκευής", regione: region, country: state, continente: continent, geoname_id: 8133828, population: 59704)
provincia.comunes.create(description: "Αγίου Δημητρίου", regione: region, country: state, continente: continent, geoname_id: 8133667, population: 71294)
provincia.comunes.create(description: "Αγίων Αναργύρων - Καματερού", regione: region, country: state, continente: continent, geoname_id: 8133819, population: 62529)
provincia.comunes.create(description: "Αθήναι", regione: region, country: state, continente: continent, geoname_id: 8133876, population: 664046)
provincia.comunes.create(description: "Αιγάλεω", regione: region, country: state, continente: continent, geoname_id: 8133973, population: 69946)
provincia.comunes.create(description: "Αλίμου", regione: region, country: state, continente: continent, geoname_id: 8133951, population: 41720)
provincia.comunes.create(description: "Αμαρουσίου", regione: region, country: state, continente: continent, geoname_id: 8133770, population: 72333)
provincia.comunes.create(description: "Βριλησσίων", regione: region, country: state, continente: continent, geoname_id: 8133807, population: 30741)
provincia.comunes.create(description: "Βύρωνος", regione: region, country: state, continente: continent, geoname_id: 8133859, population: 61308)
provincia.comunes.create(description: "Γαλατσίου", regione: region, country: state, continente: continent, geoname_id: 8133798, population: 59345)
provincia.comunes.create(description: "Γλυφάδας", regione: region, country: state, continente: continent, geoname_id: 8133886, population: 87305)
provincia.comunes.create(description: "Δάφνης - Υμηττού", regione: region, country: state, continente: continent, geoname_id: 8133710, population: 33628)
provincia.comunes.create(description: "Ελληνικού - Αργυρούπολης", regione: region, country: state, continente: continent, geoname_id: 8133982, population: 51356)
provincia.comunes.create(description: "Ζωγράφου", regione: region, country: state, continente: continent, geoname_id: 8133877, population: 71026)
provincia.comunes.create(description: "Ηλιούπολης", regione: region, country: state, continente: continent, geoname_id: 8133815, population: 78153)
provincia.comunes.create(description: "Ηρακλείου", regione: region, country: state, continente: continent, geoname_id: 8133693, population: 49642)
provincia.comunes.create(description: "Ιλίου", regione: region, country: state, continente: continent, geoname_id: 8133919, population: 84793)
provincia.comunes.create(description: "Καισαριανής", regione: region, country: state, continente: continent, geoname_id: 8133881, population: 26458)
provincia.comunes.create(description: "Καλλιθέας", regione: region, country: state, continente: continent, geoname_id: 8133880, population: 100641)
provincia.comunes.create(description: "Κηφισιάς", regione: region, country: state, continente: continent, geoname_id: 8133694, population: 70600)
provincia.comunes.create(description: "Λυκόβρυσης - Πεύκης", regione: region, country: state, continente: continent, geoname_id: 8133776, population: 31002)
provincia.comunes.create(description: "Μεταμόρφωση", regione: region, country: state, continente: continent, geoname_id: 8133888, population: 29891)
provincia.comunes.create(description: "Μοσχάτου - Ταύρου", regione: region, country: state, continente: continent, geoname_id: 8133676, population: 40413)
provincia.comunes.create(description: "Νέας Ιωνίας", regione: region, country: state, continente: continent, geoname_id: 8133780, population: 67134)
provincia.comunes.create(description: "Νέας Σμύρνης", regione: region, country: state, continente: continent, geoname_id: 8133665, population: 73076)
provincia.comunes.create(description: "Παλαιού Φαλήρου", regione: region, country: state, continente: continent, geoname_id: 8133960, population: 64021)
provincia.comunes.create(description: "Παπάγου - Χολαργού", regione: region, country: state, continente: continent, geoname_id: 8133839, population: 44539)
provincia.comunes.create(description: "Πεντέλης", regione: region, country: state, continente: continent, geoname_id: 8133840, population: 34934)
provincia.comunes.create(description: "Περιστερίου", regione: region, country: state, continente: continent, geoname_id: 8133783, population: 139981)
provincia.comunes.create(description: "Πετρούπολης", regione: region, country: state, continente: continent, geoname_id: 8133926, population: 58979)
provincia.comunes.create(description: "Φιλαδελφείας - Χαλκηδόνος", regione: region, country: state, continente: continent, geoname_id: 8133680, population: 35556)
provincia.comunes.create(description: "Φιλοθέης - Ψυχικού", regione: region, country: state, continente: continent, geoname_id: 8133782, population: 26968)
provincia.comunes.create(description: "Χαλανδρίου", regione: region, country: state, continente: continent, geoname_id: 8133842, population: 74192)
provincia.comunes.create(description: "Χαϊδαρίου", regione: region, country: state, continente: continent, geoname_id: 8133972, population: 46897)
region = Regione.create(description: "Αυτόνομη Μοναστική Πολιτεία Αγίου Όρους", country: state, continente: continent, geoname_id: 736572)
provincia = region.provincias.create(description: "Dáfni", country: state, continente: continent,  geoname_id: 736482, population: 0)
provincia = region.provincias.create(description: "Monoxilítai", country: state, continente: continent,  geoname_id: 735047, population: 0)
provincia = region.provincias.create(description: "Ελιά", country: state, continente: continent,  geoname_id: 736329, population: 0)
provincia = region.provincias.create(description: "Θηβαΐς", country: state, continente: continent,  geoname_id: 734068, population: 0)
provincia = region.provincias.create(description: "Καρυές", country: state, continente: continent,  geoname_id: 735972, population: 237)
region = Regione.create(description: "Βόρειο Αιγαίο", country: state, continente: continent, geoname_id: 6697806)
provincia = region.provincias.create(description: "Λέσβος", country: state, continente: continent,  geoname_id: 258465, population: 0)
provincia.comunes.create(description: "Άγιος Ευστράτιος", regione: region, country: state, continente: continent, geoname_id: 8133756, population: 307)
provincia.comunes.create(description: "Λέσβος", regione: region, country: state, continente: continent, geoname_id: 8133755, population: 90436)
provincia.comunes.create(description: "Λήμνος", regione: region, country: state, continente: continent, geoname_id: 8133757, population: 17545)
provincia = region.provincias.create(description: "Σάμος", country: state, continente: continent,  geoname_id: 254112, population: 0)
provincia.comunes.create(description: "Ικαρία", regione: region, country: state, continente: continent, geoname_id: 8133747, population: 8354)
provincia.comunes.create(description: "Σάμος", regione: region, country: state, continente: continent, geoname_id: 8133749, population: 34000)
provincia.comunes.create(description: "Φούρνων Κορσεών", regione: region, country: state, continente: continent, geoname_id: 8133748, population: 1487)
provincia = region.provincias.create(description: "Χίος", country: state, continente: continent,  geoname_id: 259970, population: 0)
provincia.comunes.create(description: "Οινουσσών", regione: region, country: state, continente: continent, geoname_id: 8133820, population: 855)
provincia.comunes.create(description: "Χίου", regione: region, country: state, continente: continent, geoname_id: 8133821, population: 51773)
provincia.comunes.create(description: "Ψαρών", regione: region, country: state, continente: continent, geoname_id: 8133829, population: 478)
region = Regione.create(description: "Δυτική Ελλάδα", country: state, continente: continent, geoname_id: 6697810)
provincia = region.provincias.create(description: "Αιτωλοακαρνανία", country: state, continente: continent,  geoname_id: 265508, population: 210802)
provincia.comunes.create(description: "Άκτιου - Βόνιτσας", regione: region, country: state, continente: continent, geoname_id: 8133701, population: 17872)
provincia.comunes.create(description: "Αγρινίου", regione: region, country: state, continente: continent, geoname_id: 8133845, population: 96889)
provincia.comunes.create(description: "Αμφιλοχίας", regione: region, country: state, continente: continent, geoname_id: 8133705, population: 20491)
provincia.comunes.create(description: "Θέρμου", regione: region, country: state, continente: continent, geoname_id: 8133703, population: 7837)
provincia.comunes.create(description: "Ιεράς Πόλης Μεσολογγίου", regione: region, country: state, continente: continent, geoname_id: 8133706, population: 35805)
provincia.comunes.create(description: "Ναυπακτίας", regione: region, country: state, continente: continent, geoname_id: 8133707, population: 26840)
provincia.comunes.create(description: "Ξηρομέρου", regione: region, country: state, continente: continent, geoname_id: 8133708, population: 13358)
provincia = region.provincias.create(description: "Αχαΐα", country: state, continente: continent,  geoname_id: 265491, population: 331316)
provincia.comunes.create(description: "Αιγιαλείας", regione: region, country: state, continente: continent, geoname_id: 8133669, population: 53585)
provincia.comunes.create(description: "Δυτικής Αχαΐας", regione: region, country: state, continente: continent, geoname_id: 8133671, population: 29608)
provincia.comunes.create(description: "Ερυμάνθου", regione: region, country: state, continente: continent, geoname_id: 8133672, population: 11329)
provincia.comunes.create(description: "Καλαβρύτων", regione: region, country: state, continente: continent, geoname_id: 8133670, population: 13912)
provincia.comunes.create(description: "Πατρέων", regione: region, country: state, continente: continent, geoname_id: 8133690, population: 210494)
provincia = region.provincias.create(description: "Ηλεία", country: state, continente: continent,  geoname_id: 261797, population: 198763)
provincia.comunes.create(description: "Ήλιδας", regione: region, country: state, continente: continent, geoname_id: 8133712, population: 36275)
provincia.comunes.create(description: "Ανδρίτσαινας - Κρεστένων", regione: region, country: state, continente: continent, geoname_id: 8133677, population: 21139)
provincia.comunes.create(description: "Ανδραβίδας - Κυλλήνης", regione: region, country: state, continente: continent, geoname_id: 8133691, population: 24668)
provincia.comunes.create(description: "Αρχαίας Ολυμπίας", regione: region, country: state, continente: continent, geoname_id: 8133692, population: 16431)
provincia.comunes.create(description: "Ζαχάρως", regione: region, country: state, continente: continent, geoname_id: 8133711, population: 13716)
provincia.comunes.create(description: "Πηνειού", regione: region, country: state, continente: continent, geoname_id: 8133689, population: 19658)
provincia.comunes.create(description: "Πύργου", regione: region, country: state, continente: continent, geoname_id: 8133887, population: 51634)
region = Regione.create(description: "Δυτική Μακεδονία", country: state, continente: continent, geoname_id: 6697811)
provincia = region.provincias.create(description: "Γρεβενά", country: state, continente: continent,  geoname_id: 736149, population: 0)
provincia.comunes.create(description: "Γρεβενών", regione: region, country: state, continente: continent, geoname_id: 8133976, population: 25522)
provincia.comunes.create(description: "Δεσκάτης", regione: region, country: state, continente: continent, geoname_id: 8133858, population: 7045)
provincia = region.provincias.create(description: "Καστοριά", country: state, continente: continent,  geoname_id: 735925, population: 0)
provincia.comunes.create(description: "Άργους Ορεστικού", regione: region, country: state, continente: continent, geoname_id: 8133860, population: 13479)
provincia.comunes.create(description: "Καστοριάς", regione: region, country: state, continente: continent, geoname_id: 8133966, population: 37094)
provincia.comunes.create(description: "Νεστορίου", regione: region, country: state, continente: continent, geoname_id: 8133967, population: 3129)
provincia = region.provincias.create(description: "Κοζάνη", country: state, continente: continent,  geoname_id: 735562, population: 0)
provincia.comunes.create(description: "Βοϊου", regione: region, country: state, continente: continent, geoname_id: 8133797, population: 20430)
provincia.comunes.create(description: "Εορδαίας", regione: region, country: state, continente: continent, geoname_id: 8133857, population: 46555)
provincia.comunes.create(description: "Κοζάνης", regione: region, country: state, continente: continent, geoname_id: 8133764, population: 70220)
provincia.comunes.create(description: "Σερβίων - Βελβεντού", regione: region, country: state, continente: continent, geoname_id: 8133872, population: 16734)
provincia = region.provincias.create(description: "Φλώρινα", country: state, continente: continent,  geoname_id: 736228, population: 0)
provincia.comunes.create(description: "Αμυνταίου", regione: region, country: state, continente: continent, geoname_id: 8133871, population: 18357)
provincia.comunes.create(description: "Πρεσπών", regione: region, country: state, continente: continent, geoname_id: 8133873, population: 2164)
provincia.comunes.create(description: "Φλώρινας", regione: region, country: state, continente: continent, geoname_id: 8133716, population: 33588)
region = Regione.create(description: "Θεσσαλία", country: state, continente: continent, geoname_id: 6697809)
provincia = region.provincias.create(description: "Καρδίτσα", country: state, continente: continent,  geoname_id: 260988, population: 0)
provincia.comunes.create(description: "Αργιθέας", regione: region, country: state, continente: continent, geoname_id: 8133980, population: 2488)
provincia.comunes.create(description: "Καρδίτσας", regione: region, country: state, continente: continent, geoname_id: 8133984, population: 57089)
provincia.comunes.create(description: "Λίμνης Πλαστήρα", regione: region, country: state, continente: continent, geoname_id: 8133733, population: 4022)
provincia.comunes.create(description: "Μουζακίου", regione: region, country: state, continente: continent, geoname_id: 8133792, population: 16407)
provincia.comunes.create(description: "Παλαμά", regione: region, country: state, continente: continent, geoname_id: 8133793, population: 18500)
provincia.comunes.create(description: "Σοφάδων", regione: region, country: state, continente: continent, geoname_id: 8133794, population: 21759)
provincia = region.provincias.create(description: "Λάρισα", country: state, continente: continent,  geoname_id: 258575, population: 0)
provincia.comunes.create(description: "Αγιάς", regione: region, country: state, continente: continent, geoname_id: 8133788, population: 13120)
provincia.comunes.create(description: "Ελασσόνας", regione: region, country: state, continente: continent, geoname_id: 8133784, population: 35358)
provincia.comunes.create(description: "Κιλελέρ", regione: region, country: state, continente: continent, geoname_id: 8133785, population: 22719)
provincia.comunes.create(description: "Λαρισαίων", regione: region, country: state, continente: continent, geoname_id: 8133786, population: 145981)
provincia.comunes.create(description: "Τεμπών", regione: region, country: state, continente: continent, geoname_id: 8133789, population: 15439)
provincia.comunes.create(description: "Τυρνάβου", regione: region, country: state, continente: continent, geoname_id: 8133787, population: 25864)
provincia.comunes.create(description: "Φαρσάλων", regione: region, country: state, continente: continent, geoname_id: 8133790, population: 23675)
provincia = region.provincias.create(description: "Μαγνησία", country: state, continente: continent,  geoname_id: 258013, population: 0)
provincia.comunes.create(description: "Αλμυρού", regione: region, country: state, continente: continent, geoname_id: 8133791, population: 20139)
provincia.comunes.create(description: "Αλοννήσου", regione: region, country: state, continente: continent, geoname_id: 8133938, population: 2425)
provincia.comunes.create(description: "Βόλου", regione: region, country: state, continente: continent, geoname_id: 8133894, population: 142923)
provincia.comunes.create(description: "Ζαγοράς - Μουρεσίου", regione: region, country: state, continente: continent, geoname_id: 8133935, population: 6449)
provincia.comunes.create(description: "Νοτίου Πηλίου", regione: region, country: state, continente: continent, geoname_id: 8133936, population: 10745)
provincia.comunes.create(description: "Ρήγα Φερραίου", regione: region, country: state, continente: continent, geoname_id: 8133937, population: 11830)
provincia.comunes.create(description: "Σκιάθου", regione: region, country: state, continente: continent, geoname_id: 8133939, population: 5788)
provincia.comunes.create(description: "Σκοπέλου", regione: region, country: state, continente: continent, geoname_id: 8133893, population: 4706)
provincia = region.provincias.create(description: "Τρίκαλα", country: state, continente: continent,  geoname_id: 252661, population: 0)
provincia.comunes.create(description: "Καλαμπάκας", regione: region, country: state, continente: continent, geoname_id: 8133942, population: 22853)
provincia.comunes.create(description: "Πύλης", regione: region, country: state, continente: continent, geoname_id: 8133843, population: 15886)
provincia.comunes.create(description: "Τρικκαίων", regione: region, country: state, continente: continent, geoname_id: 8133844, population: 78817)
provincia.comunes.create(description: "Φαρκαδόνας", regione: region, country: state, continente: continent, geoname_id: 8133853, population: 15133)
region = Regione.create(description: "Ιόνια Νησιά", country: state, continente: continent, geoname_id: 6697805)
provincia = region.provincias.create(description: "Ζάκυνθος", country: state, continente: continent,  geoname_id: 251276, population: 41472)
provincia.comunes.create(description: "Ζακύνθου", regione: region, country: state, continente: continent, geoname_id: 8133854, population: 38883)
provincia = region.provincias.create(description: "Κέρκυρα", country: state, continente: continent,  geoname_id: 2463676, population: 113658)
provincia.comunes.create(description: "Κέρκυρα", regione: region, country: state, continente: continent, geoname_id: 8133855, population: 108652)
provincia.comunes.create(description: "Παξών", regione: region, country: state, continente: continent, geoname_id: 8133911, population: 2429)
provincia = region.provincias.create(description: "Κεφαλονιά", country: state, continente: continent,  geoname_id: 260310, population: 0)
provincia.comunes.create(description: "Ιθάκης", regione: region, country: state, continente: continent, geoname_id: 8133849, population: 3212)
provincia.comunes.create(description: "Κεφαλονιάς", regione: region, country: state, continente: continent, geoname_id: 8133850, population: 34544)
provincia = region.provincias.create(description: "Λευκάδα", country: state, continente: continent,  geoname_id: 258445, population: 22879)
provincia.comunes.create(description: "Λευκάδας", regione: region, country: state, continente: continent, geoname_id: 8133851, population: 20894)
provincia.comunes.create(description: "Μεγανησίου", regione: region, country: state, continente: continent, geoname_id: 8133852, population: 994)
region = Regione.create(description: "Κεντρική Ελλάδα", country: state, continente: continent, geoname_id: 6697800)
provincia = region.provincias.create(description: "Βοιωτία", country: state, continente: continent,  geoname_id: 251851, population: 0)
provincia.comunes.create(description: "Αλιάρτου", regione: region, country: state, continente: continent, geoname_id: 8133875, population: 11686)
provincia.comunes.create(description: "Διστόμου-Αράχοβας - Αντίκυρας", regione: region, country: state, continente: continent, geoname_id: 8133907, population: 9802)
provincia.comunes.create(description: "Θηβαίων", regione: region, country: state, continente: continent, geoname_id: 8133908, population: 36086)
provincia.comunes.create(description: "Λεβαδέων", regione: region, country: state, continente: continent, geoname_id: 8133909, population: 36086)
provincia.comunes.create(description: "Ορχομενού", regione: region, country: state, continente: continent, geoname_id: 8133910, population: 13032)
provincia.comunes.create(description: "Τανάγρας", regione: region, country: state, continente: continent, geoname_id: 8133914, population: 21156)
provincia = region.provincias.create(description: "Ευρυτανία", country: state, continente: continent,  geoname_id: 262572, population: 34855)
provincia.comunes.create(description: "Αγράφων", regione: region, country: state, continente: continent, geoname_id: 8133730, population: 7190)
provincia.comunes.create(description: "Καρπενησίου", regione: region, country: state, continente: continent, geoname_id: 8133731, population: 12328)
provincia = region.provincias.create(description: "Εύβοια", country: state, continente: continent,  geoname_id: 262564, population: 0)
provincia.comunes.create(description: "Διρφύων - Μεσσαπίων", regione: region, country: state, continente: continent, geoname_id: 8133901, population: 19443)
provincia.comunes.create(description: "Ερέτριας", regione: region, country: state, continente: continent, geoname_id: 8133902, population: 12218)
provincia.comunes.create(description: "Ιστιαίας - Αιδηψού", regione: region, country: state, continente: continent, geoname_id: 8133903, population: 22132)
provincia.comunes.create(description: "Καρύστου", regione: region, country: state, continente: continent, geoname_id: 8133904, population: 13602)
provincia.comunes.create(description: "Κύμης - Αλιβερίου", regione: region, country: state, continente: continent, geoname_id: 8133905, population: 30717)
provincia.comunes.create(description: "Μαντουδίου - Λίμνης - Αγίας Άννας", regione: region, country: state, continente: continent, geoname_id: 8133906, population: 13673)
provincia.comunes.create(description: "Σκύρου", regione: region, country: state, continente: continent, geoname_id: 8133975, population: 2711)
provincia.comunes.create(description: "Χαλκιδέων", regione: region, country: state, continente: continent, geoname_id: 8133729, population: 92809)
provincia = region.provincias.create(description: "Φθιώτιδα", country: state, continente: continent,  geoname_id: 262187, population: 0)
provincia.comunes.create(description: "Αμφίκλειας - Ελάτειας", regione: region, country: state, continente: continent, geoname_id: 8133732, population: 10922)
provincia.comunes.create(description: "Δομοκού", regione: region, country: state, continente: continent, geoname_id: 8133737, population: 11495)
provincia.comunes.create(description: "Λαμιέων", regione: region, country: state, continente: continent, geoname_id: 8133738, population: 75315)
provincia.comunes.create(description: "Λοκρών", regione: region, country: state, continente: continent, geoname_id: 8133739, population: 19623)
provincia.comunes.create(description: "Μακρακώμης", regione: region, country: state, continente: continent, geoname_id: 8133740, population: 16036)
provincia.comunes.create(description: "Μώλου - Αγ. Κωνσταντίνου", regione: region, country: state, continente: continent, geoname_id: 8133746, population: 13932)
provincia.comunes.create(description: "Στυλίδας", regione: region, country: state, continente: continent, geoname_id: 8133765, population: 14118)
provincia = region.provincias.create(description: "Φωκίδα", country: state, continente: continent,  geoname_id: 262322, population: 49576)
provincia.comunes.create(description: "Δελφών", regione: region, country: state, continente: continent, geoname_id: 8133744, population: 26992)
provincia.comunes.create(description: "Δωρίδος", regione: region, country: state, continente: continent, geoname_id: 8133745, population: 10874)
region = Regione.create(description: "Κεντρική Μακεδονία", country: state, continente: continent, geoname_id: 6697801)
provincia = region.provincias.create(description: "Ημαθία", country: state, continente: continent,  geoname_id: 736120, population: 0)
provincia.comunes.create(description: "Αλεξάνδρειας", regione: region, country: state, continente: continent, geoname_id: 8133931, population: 42777)
provincia.comunes.create(description: "Βέροιας", regione: region, country: state, continente: continent, geoname_id: 8133932, population: 65530)
provincia.comunes.create(description: "Νάουσας", regione: region, country: state, continente: continent, geoname_id: 8133882, population: 34164)
provincia = region.provincias.create(description: "Θεσσαλονίκη", country: state, continente: continent,  geoname_id: 734075, population: 0)
provincia.comunes.create(description: "Αμπελοκήπων - Μενεμένης", regione: region, country: state, continente: continent, geoname_id: 8133985, population: 58149)
provincia.comunes.create(description: "Βόλβης", regione: region, country: state, continente: continent, geoname_id: 8133915, population: 24454)
provincia.comunes.create(description: "Δέλτα", regione: region, country: state, continente: continent, geoname_id: 8133916, population: 40206)
provincia.comunes.create(description: "Θέρμης", regione: region, country: state, continente: continent, geoname_id: 8133763, population: 34436)
provincia.comunes.create(description: "Θερμαϊκού", regione: region, country: state, continente: continent, geoname_id: 8133917, population: 37126)
provincia.comunes.create(description: "Θεσσαλονίκης", regione: region, country: state, continente: continent, geoname_id: 8133841, population: 397156)
provincia.comunes.create(description: "Καλαμαριάς", regione: region, country: state, continente: continent, geoname_id: 8133959, population: 90096)
provincia.comunes.create(description: "Κορδελιού - Ευόσμου", regione: region, country: state, continente: continent, geoname_id: 8133918, population: 77174)
provincia.comunes.create(description: "Λαγκαδά", regione: region, country: state, continente: continent, geoname_id: 8133981, population: 39160)
provincia.comunes.create(description: "Νέαπολης - Συκεών", regione: region, country: state, continente: continent, geoname_id: 8133678, population: 89274)
provincia.comunes.create(description: "Παύλου Μελά", regione: region, country: state, continente: continent, geoname_id: 8133666, population: 87587)
provincia.comunes.create(description: "Πυλαίας - Χορτιάτη", regione: region, country: state, continente: continent, geoname_id: 8133774, population: 49922)
provincia.comunes.create(description: "Χαλκηδόνος", regione: region, country: state, continente: continent, geoname_id: 8133775, population: 34299)
provincia.comunes.create(description: "Ωραιοκάστρου", regione: region, country: state, continente: continent, geoname_id: 8133795, population: 24962)
provincia = region.provincias.create(description: "Κιλκίς", country: state, continente: continent,  geoname_id: 735735, population: 0)
provincia.comunes.create(description: "Κιλκίς", regione: region, country: state, continente: continent, geoname_id: 8133969, population: 54750)
provincia.comunes.create(description: "Παιονίας", regione: region, country: state, continente: continent, geoname_id: 8133970, population: 31674)
provincia = region.provincias.create(description: "Πέλλα", country: state, continente: continent,  geoname_id: 734725, population: 0)
provincia.comunes.create(description: "Έδεσσας", regione: region, country: state, continente: continent, geoname_id: 8133912, population: 29568)
provincia.comunes.create(description: "Αλμωπίας", regione: region, country: state, continente: continent, geoname_id: 8133796, population: 28822)
provincia.comunes.create(description: "Πέλλας", regione: region, country: state, continente: continent, geoname_id: 8133848, population: 64847)
provincia.comunes.create(description: "Σκύδρας", regione: region, country: state, continente: continent, geoname_id: 8133913, population: 20720)
provincia = region.provincias.create(description: "Πιερία", country: state, continente: continent,  geoname_id: 734649, population: 0)
provincia.comunes.create(description: "Δίου - Ολύμπου", regione: region, country: state, continente: continent, geoname_id: 8133846, population: 25872)
provincia.comunes.create(description: "Κατερίνης", regione: region, country: state, continente: continent, geoname_id: 8133847, population: 83387)
provincia.comunes.create(description: "Πύδνας - Κολινδρού", regione: region, country: state, continente: continent, geoname_id: 8133861, population: 17153)
provincia = region.provincias.create(description: "Σέρρες", country: state, continente: continent,  geoname_id: 734329, population: 0)
provincia.comunes.create(description: "Αμφίπολης", regione: region, country: state, continente: continent, geoname_id: 8133862, population: 11860)
provincia.comunes.create(description: "Βισαλτίας", regione: region, country: state, continente: continent, geoname_id: 8133863, population: 23158)
provincia.comunes.create(description: "Εμμανουήλ Παππά", regione: region, country: state, continente: continent, geoname_id: 8133856, population: 19053)
provincia.comunes.create(description: "Ηρακλείας", regione: region, country: state, continente: continent, geoname_id: 8133864, population: 22695)
provincia.comunes.create(description: "Νέας Ζίχνης", regione: region, country: state, continente: continent, geoname_id: 8133865, population: 13813)
provincia.comunes.create(description: "Σερρών", regione: region, country: state, continente: continent, geoname_id: 8133866, population: 76472)
provincia.comunes.create(description: "Σιντικής", regione: region, country: state, continente: continent, geoname_id: 8133867, population: 27432)
provincia = region.provincias.create(description: "Χαλκιδική", country: state, continente: continent,  geoname_id: 735804, population: 109587)
provincia.comunes.create(description: "Αριστοτέλη", regione: region, country: state, continente: continent, geoname_id: 8133868, population: 17752)
provincia.comunes.create(description: "Κασσάνδρας", regione: region, country: state, continente: continent, geoname_id: 8133869, population: 14971)
provincia.comunes.create(description: "Νέας Προποντίδας", regione: region, country: state, continente: continent, geoname_id: 8133870, population: 30397)
provincia.comunes.create(description: "Πολυγύρου", regione: region, country: state, continente: continent, geoname_id: 8133962, population: 21931)
provincia.comunes.create(description: "Σιθωνίας", regione: region, country: state, continente: continent, geoname_id: 8133963, population: 11798)
region = Regione.create(description: "Κρήτη", country: state, continente: continent, geoname_id: 6697802)
provincia = region.provincias.create(description: "Ηράκλειο", country: state, continente: continent,  geoname_id: 261741, population: 302846)
provincia.comunes.create(description: "Αρχανών - Αστερουσίων", regione: region, country: state, continente: continent, geoname_id: 8133817, population: 17531)
provincia.comunes.create(description: "Βιάννου", regione: region, country: state, continente: continent, geoname_id: 8133818, population: 5983)
provincia.comunes.create(description: "Γόρτυνας", regione: region, country: state, continente: continent, geoname_id: 8133944, population: 17423)
provincia.comunes.create(description: "Ηρακλείου", regione: region, country: state, continente: continent, geoname_id: 8133920, population: 163115)
provincia.comunes.create(description: "Μαλεβιζίου", regione: region, country: state, continente: continent, geoname_id: 8133945, population: 20735)
provincia.comunes.create(description: "Μινώα Πεδιάδας", regione: region, country: state, continente: continent, geoname_id: 8133810, population: 18692)
provincia.comunes.create(description: "Φαιστού", regione: region, country: state, continente: continent, geoname_id: 8133968, population: 23882)
provincia.comunes.create(description: "Χερσονήσου", regione: region, country: state, continente: continent, geoname_id: 8133695, population: 23864)
provincia = region.provincias.create(description: "Λασίθι", country: state, continente: continent,  geoname_id: 258569, population: 0)
provincia.comunes.create(description: "Αγίου Νικολάου", regione: region, country: state, continente: continent, geoname_id: 8133929, population: 26069)
provincia.comunes.create(description: "Ιεράπετρας", regione: region, country: state, continente: continent, geoname_id: 8133930, population: 27744)
provincia.comunes.create(description: "Οροπεδίου Λασιθίου", regione: region, country: state, continente: continent, geoname_id: 8133925, population: 3067)
provincia.comunes.create(description: "Σητείας", regione: region, country: state, continente: continent, geoname_id: 8133948, population: 27744)
provincia = region.provincias.create(description: "Ρέθυμνο", country: state, continente: continent,  geoname_id: 254353, population: 86532)
provincia.comunes.create(description: "Αγίου Βασιλείου", regione: region, country: state, continente: continent, geoname_id: 8133949, population: 8648)
provincia.comunes.create(description: "Αμάριου", regione: region, country: state, continente: continent, geoname_id: 8133983, population: 5633)
provincia.comunes.create(description: "Ανωγείων", regione: region, country: state, continente: continent, geoname_id: 8133943, population: 4054)
provincia.comunes.create(description: "Μυλοποτάμου", regione: region, country: state, continente: continent, geoname_id: 8133758, population: 13350)
provincia.comunes.create(description: "Ρεθύμνης", regione: region, country: state, continente: continent, geoname_id: 8133759, population: 47272)
provincia = region.provincias.create(description: "Χανιά", country: state, continente: continent,  geoname_id: 260096, population: 0)
provincia.comunes.create(description: "Αποκορώνου", regione: region, country: state, continente: continent, geoname_id: 8133750, population: 12112)
provincia.comunes.create(description: "Γαύδου", regione: region, country: state, continente: continent, geoname_id: 8133751, population: 81)
provincia.comunes.create(description: "Κίσσαμος", regione: region, country: state, continente: continent, geoname_id: 8133753, population: 11470)
provincia.comunes.create(description: "Καντάνου - Σέλινου", regione: region, country: state, continente: continent, geoname_id: 8133752, population: 6302)
provincia.comunes.create(description: "Πλατανιά", regione: region, country: state, continente: continent, geoname_id: 8133754, population: 17864)
provincia.comunes.create(description: "Σφακίων", regione: region, country: state, continente: continent, geoname_id: 8133761, population: 2419)
provincia.comunes.create(description: "Χανιά", regione: region, country: state, continente: continent, geoname_id: 8133762, population: 98202)
region = Regione.create(description: "Νότιο Αιγαίο", country: state, continente: continent, geoname_id: 6697808)
provincia = region.provincias.create(description: "Δωδεκάνησα", country: state, continente: continent,  geoname_id: 263021, population: 0)
provincia.comunes.create(description: "Αγαθονήσι", regione: region, country: state, continente: continent, geoname_id: 8133824, population: 152)
provincia.comunes.create(description: "Αστυπαλαίας", regione: region, country: state, continente: continent, geoname_id: 8133811, population: 1385)
provincia.comunes.create(description: "Κάσου", regione: region, country: state, continente: continent, geoname_id: 8133956, population: 1013)
provincia.comunes.create(description: "Καλυμνίων", regione: region, country: state, continente: continent, geoname_id: 8133812, population: 16576)
provincia.comunes.create(description: "Καρπάθου", regione: region, country: state, continente: continent, geoname_id: 8133955, population: 6565)
provincia.comunes.create(description: "Κω", regione: region, country: state, continente: continent, geoname_id: 8133957, population: 30828)
provincia.comunes.create(description: "Λέρου", regione: region, country: state, continente: continent, geoname_id: 8133814, population: 8172)
provincia.comunes.create(description: "Λειψών", regione: region, country: state, continente: continent, geoname_id: 8133813, population: 687)
provincia.comunes.create(description: "Μεγίστης", regione: region, country: state, continente: continent, geoname_id: 8133700, population: 403)
provincia.comunes.create(description: "Νισύρου", regione: region, country: state, continente: continent, geoname_id: 8133958, population: 928)
provincia.comunes.create(description: "Πάτμου", regione: region, country: state, continente: continent, geoname_id: 8133954, population: 3053)
provincia.comunes.create(description: "Ρόδου", regione: region, country: state, continente: continent, geoname_id: 8133781, population: 115334)
provincia.comunes.create(description: "Σύμης", regione: region, country: state, continente: continent, geoname_id: 8133940, population: 2594)
provincia.comunes.create(description: "Τήλου", regione: region, country: state, continente: continent, geoname_id: 8133941, population: 521)
provincia.comunes.create(description: "Χάλκης", regione: region, country: state, continente: continent, geoname_id: 8133964, population: 295)
provincia = region.provincias.create(description: "Κυκλάδες", country: state, continente: continent,  geoname_id: 259819, population: 119549)
provincia.comunes.create(description: "Άνδρου", regione: region, country: state, continente: continent, geoname_id: 8133830, population: 9285)
provincia.comunes.create(description: "Αμοργού", regione: region, country: state, continente: continent, geoname_id: 8133934, population: 1852)
provincia.comunes.create(description: "Ανάφης", regione: region, country: state, continente: continent, geoname_id: 8133831, population: 272)
provincia.comunes.create(description: "Αντιπάρου", regione: region, country: state, continente: continent, geoname_id: 8133698, population: 1011)
provincia.comunes.create(description: "Ιητών", regione: region, country: state, continente: continent, geoname_id: 8133833, population: 1862)
provincia.comunes.create(description: "Κέας", regione: region, country: state, continente: continent, geoname_id: 8133952, population: 2162)
provincia.comunes.create(description: "Κίμωλος", regione: region, country: state, continente: continent, geoname_id: 8133679, population: 910)
provincia.comunes.create(description: "Κύθνου", regione: region, country: state, continente: continent, geoname_id: 8133953, population: 1538)
provincia.comunes.create(description: "Μήλος", regione: region, country: state, continente: continent, geoname_id: 8133681, population: 4977)
provincia.comunes.create(description: "Μύκονος", regione: region, country: state, continente: continent, geoname_id: 8133933, population: 9274)
provincia.comunes.create(description: "Νάξου & Μικρών Κυκλάδων", regione: region, country: state, continente: continent, geoname_id: 8133697, population: 18229)
provincia.comunes.create(description: "Πάρου", regione: region, country: state, continente: continent, geoname_id: 8133699, population: 12514)
provincia.comunes.create(description: "Σίφνου", regione: region, country: state, continente: continent, geoname_id: 8133683, population: 2574)
provincia.comunes.create(description: "Σαντορίνη", regione: region, country: state, continente: continent, geoname_id: 8133832, population: 13725)
provincia.comunes.create(description: "Σερίφου", regione: region, country: state, continente: continent, geoname_id: 8133682, population: 1262)
provincia.comunes.create(description: "Σικίνου", regione: region, country: state, continente: continent, geoname_id: 8133822, population: 238)
provincia.comunes.create(description: "Σύρος", regione: region, country: state, continente: continent, geoname_id: 8133927, population: 19793)
provincia.comunes.create(description: "Τήνος", regione: region, country: state, continente: continent, geoname_id: 8133928, population: 8115)
provincia.comunes.create(description: "Φολεγάνδρου", regione: region, country: state, continente: continent, geoname_id: 8133823, population: 676)
region = Regione.create(description: "Πελοπόννησος", country: state, continente: continent, geoname_id: 6697807)
provincia = region.provincias.create(description: "Αργολίδα", country: state, continente: continent,  geoname_id: 264673, population: 0)
provincia.comunes.create(description: "Άργους - Μυκηνών", regione: region, country: state, continente: continent, geoname_id: 8133979, population: 47745)
provincia.comunes.create(description: "Επιδαύρου", regione: region, country: state, continente: continent, geoname_id: 8133804, population: 8710)
provincia.comunes.create(description: "Ερμιονίδας", regione: region, country: state, continente: continent, geoname_id: 8133805, population: 14330)
provincia.comunes.create(description: "Ναυπλιέων", regione: region, country: state, continente: continent, geoname_id: 8133806, population: 31607)
provincia = region.provincias.create(description: "Αρκαδία", country: state, continente: continent,  geoname_id: 264644, population: 0)
provincia.comunes.create(description: "Βόρειας Κυνουρίας", regione: region, country: state, continente: continent, geoname_id: 8133800, population: 11589)
provincia.comunes.create(description: "Γορτυνίας", regione: region, country: state, continente: continent, geoname_id: 8133801, population: 12492)
provincia.comunes.create(description: "Μεγαλόπολης", regione: region, country: state, continente: continent, geoname_id: 8133802, population: 11044)
provincia.comunes.create(description: "Νότιας Κυνουρίας", regione: region, country: state, continente: continent, geoname_id: 8133803, population: 7633)
provincia.comunes.create(description: "Τρίπολης", regione: region, country: state, continente: continent, geoname_id: 8133668, population: 48568)
provincia = region.provincias.create(description: "Κορινθία", country: state, continente: continent,  geoname_id: 259290, population: 0)
provincia.comunes.create(description: "Βέλου - Βόχας", regione: region, country: state, continente: continent, geoname_id: 8133799, population: 17251)
provincia.comunes.create(description: "Κορινθίων", regione: region, country: state, continente: continent, geoname_id: 8133673, population: 58523)
provincia.comunes.create(description: "Λουτρακίου-Περαχώρας-Αγίων Θεοδώρων", regione: region, country: state, continente: continent, geoname_id: 8133977, population: 20040)
provincia.comunes.create(description: "Νεμέας", regione: region, country: state, continente: continent, geoname_id: 8133674, population: 7286)
provincia.comunes.create(description: "Ξυλοκάστρου - Ευρωστίνης", regione: region, country: state, continente: continent, geoname_id: 8133978, population: 18224)
provincia.comunes.create(description: "Σικυωνίων", regione: region, country: state, continente: continent, geoname_id: 8133675, population: 23203)
provincia = region.provincias.create(description: "Λακωνία", country: state, continente: continent,  geoname_id: 258657, population: 0)
provincia.comunes.create(description: "Ανατολικής Μάνης", regione: region, country: state, continente: continent, geoname_id: 8133713, population: 14308)
provincia.comunes.create(description: "Ελαφονήσου", regione: region, country: state, continente: continent, geoname_id: 8133714, population: 746)
provincia.comunes.create(description: "Ευρώτα", regione: region, country: state, continente: continent, geoname_id: 8133715, population: 19319)
provincia.comunes.create(description: "Μονεμβασιάς", regione: region, country: state, continente: continent, geoname_id: 8133723, population: 21898)
provincia.comunes.create(description: "Σπάρτης", regione: region, country: state, continente: continent, geoname_id: 8133718, population: 36540)
provincia = region.provincias.create(description: "Μεσσηνία", country: state, continente: continent,  geoname_id: 257149, population: 0)
provincia.comunes.create(description: "Δυτικής Μάνης", regione: region, country: state, continente: continent, geoname_id: 8133724, population: 6658)
provincia.comunes.create(description: "Καλαμάτας", regione: region, country: state, continente: continent, geoname_id: 8133971, population: 70006)
provincia.comunes.create(description: "Μεσσήνης", regione: region, country: state, continente: continent, geoname_id: 8133986, population: 25859)
provincia.comunes.create(description: "Οιχαλίας", regione: region, country: state, continente: continent, geoname_id: 8133987, population: 11681)
provincia.comunes.create(description: "Πύλου - Νέστορος", regione: region, country: state, continente: continent, geoname_id: 8133988, population: 21172)
provincia.comunes.create(description: "Τριφυλίας", regione: region, country: state, continente: continent, geoname_id: 8133760, population: 31190)
