continent = Continent.find_by(description: 'Europe')
state = Country.find_by(description: 'Greece')
region = Region.create(description: "Ήπειρος", country: state, continent: continent, geoname_id: 6697804)
province = region.provinces.create(description: "Άρτα", country: state, continent: continent,  geoname_id: 264545, population: 0)
province.comunes.create(description: "Αρταίων", region: region, country: state, continent: continent, geoname_id: 6943434, population: 0)
province.comunes.create(description: "Γεωργίου Καραϊσκάκη", region: region, country: state, continent: continent, geoname_id: 8133717, population: 7131)
province.comunes.create(description: "Κεντρικών Τζουμέρκων", region: region, country: state, continent: continent, geoname_id: 8133816, population: 7862)
province.comunes.create(description: "Νικολάου Σκουφά", region: region, country: state, continent: continent, geoname_id: 8133727, population: 14491)
province = region.provinces.create(description: "Θεσπρωτία", country: state, continent: continent,  geoname_id: 252941, population: 0)
province.comunes.create(description: "Ηγουμενίτσας", region: region, country: state, continent: continent, geoname_id: 8133725, population: 24130)
province.comunes.create(description: "Σουλίου", region: region, country: state, continent: continent, geoname_id: 8133726, population: 10379)
province.comunes.create(description: "Φιλιατών", region: region, country: state, continent: continent, geoname_id: 8133728, population: 9092)
province = region.provinces.create(description: "Ιωάννινα", country: state, continent: continent,  geoname_id: 261777, population: 0)
province.comunes.create(description: "Βορείων Τζουμέρκων", region: region, country: state, continent: continent, geoname_id: 8133719, population: 4361)
province.comunes.create(description: "Δωδώνης", region: region, country: state, continent: continent, geoname_id: 8133720, population: 10482)
province.comunes.create(description: "Ζίτσας", region: region, country: state, continent: continent, geoname_id: 8133722, population: 14923)
province.comunes.create(description: "Ζαγορίου", region: region, country: state, continent: continent, geoname_id: 8133721, population: 4348)
province.comunes.create(description: "Ιωαννιτών", region: region, country: state, continent: continent, geoname_id: 7303595, population: 0)
province.comunes.create(description: "Κόνιτσας", region: region, country: state, continent: continent, geoname_id: 8133734, population: 7648)
province.comunes.create(description: "Μετσόβου", region: region, country: state, continent: continent, geoname_id: 8133735, population: 7177)
province.comunes.create(description: "Πωγωνίου", region: region, country: state, continent: continent, geoname_id: 8133736, population: 8987)
province = region.provinces.create(description: "Πρέβεζα", country: state, continent: continent,  geoname_id: 254695, population: 0)
province.comunes.create(description: "Ζηρού", region: region, country: state, continent: continent, geoname_id: 8133741, population: 15410)
province.comunes.create(description: "Πάργας", region: region, country: state, continent: continent, geoname_id: 8133742, population: 12597)
province.comunes.create(description: "Πρέβεζας", region: region, country: state, continent: continent, geoname_id: 8133743, population: 30137)
region = Region.create(description: "Ανατολική Μακεδονία και Θράκη", country: state, continent: continent, geoname_id: 6697803)
province = region.provinces.create(description: "Έβρος", country: state, continent: continent,  geoname_id: 736287, population: 0)
province.comunes.create(description: "Αλεξανδρούπολης", region: region, country: state, continent: continent, geoname_id: 8133779, population: 66125)
province.comunes.create(description: "Διδυμοτείχου", region: region, country: state, continent: continent, geoname_id: 8133778, population: 23380)
province.comunes.create(description: "Ορεστιάδας", region: region, country: state, continent: continent, geoname_id: 8133900, population: 39375)
province.comunes.create(description: "Σαμοθράκης", region: region, country: state, continent: continent, geoname_id: 8133889, population: 2712)
province.comunes.create(description: "Σουφλίου", region: region, country: state, continent: continent, geoname_id: 8133890, population: 17961)
province = region.provinces.create(description: "Δράμα", country: state, continent: continent,  geoname_id: 736363, population: 0)
province.comunes.create(description: "Δοξάτου", region: region, country: state, continent: continent, geoname_id: 8133891, population: 16883)
province.comunes.create(description: "Δράμας", region: region, country: state, continent: continent, geoname_id: 8133892, population: 75367)
province.comunes.create(description: "Κάτω Νευροκοπίου", region: region, country: state, continent: continent, geoname_id: 8133895, population: 7289)
province.comunes.create(description: "Παρανεστίου", region: region, country: state, continent: continent, geoname_id: 8133896, population: 5114)
province.comunes.create(description: "Προσοτσάνης", region: region, country: state, continent: continent, geoname_id: 8133897, population: 15531)
province = region.provinces.create(description: "Καβάλα", country: state, continent: continent,  geoname_id: 735857, population: 0)
province.comunes.create(description: "Θάσος", region: region, country: state, continent: continent, geoname_id: 8133898, population: 13451)
province.comunes.create(description: "Καβάλας", region: region, country: state, continent: continent, geoname_id: 8133899, population: 74186)
province.comunes.create(description: "Νέστου", region: region, country: state, continent: continent, geoname_id: 8133878, population: 22218)
province.comunes.create(description: "Παγγαίου", region: region, country: state, continent: continent, geoname_id: 8133879, population: 31644)
province = region.provinces.create(description: "Ξάνθη", country: state, continent: continent,  geoname_id: 733839, population: 0)
province.comunes.create(description: "Αβδήρων", region: region, country: state, continent: continent, geoname_id: 8133835, population: 18262)
province.comunes.create(description: "Μύκης", region: region, country: state, continent: continent, geoname_id: 8133836, population: 16091)
province.comunes.create(description: "Ξάνθης", region: region, country: state, continent: continent, geoname_id: 8133837, population: 56383)
province.comunes.create(description: "Τοπείρου", region: region, country: state, continent: continent, geoname_id: 8133838, population: 12223)
province = region.provinces.create(description: "Ροδόπη", country: state, continent: continent,  geoname_id: 734375, population: 0)
province.comunes.create(description: "Αρριανών", region: region, country: state, continent: continent, geoname_id: 8133825, population: 18259)
province.comunes.create(description: "Ιάσμου", region: region, country: state, continent: continent, geoname_id: 8133826, population: 14851)
province.comunes.create(description: "Κομοτηνής", region: region, country: state, continent: continent, geoname_id: 8133827, population: 51501)
province.comunes.create(description: "Μαρωνείας - Σαπών", region: region, country: state, continent: continent, geoname_id: 8133834, population: 16626)
region = Region.create(description: "Αττική", country: state, continent: continent, geoname_id: 6692632)
province = region.provinces.create(description: "Nomarchía Anatolikís Attikís", country: state, continent: continent,  geoname_id: 445406, population: 0)
province.comunes.create(description: "Αχαρνών", region: region, country: state, continent: continent, geoname_id: 8133704, population: 100743)
province.comunes.create(description: "Βάρης - Βούλας - Βουλιαγμένης", region: region, country: state, continent: continent, geoname_id: 8133946, population: 48399)
province.comunes.create(description: "Διονύσου", region: region, country: state, continent: continent, geoname_id: 8133921, population: 40193)
province.comunes.create(description: "Κρωπίας", region: region, country: state, continent: continent, geoname_id: 8133922, population: 30307)
province.comunes.create(description: "Λαυρεωτικής", region: region, country: state, continent: continent, geoname_id: 8133923, population: 25102)
province.comunes.create(description: "Μαραθώνος", region: region, country: state, continent: continent, geoname_id: 8133924, population: 33423)
province.comunes.create(description: "Μαρκοπούλου Μεσογαίας", region: region, country: state, continent: continent, geoname_id: 8133947, population: 20040)
province.comunes.create(description: "Παιανίας", region: region, country: state, continent: continent, geoname_id: 8133684, population: 26668)
province.comunes.create(description: "Παλλήνης", region: region, country: state, continent: continent, geoname_id: 8133685, population: 54415)
province.comunes.create(description: "Ραφήνας - Πικερμίου", region: region, country: state, continent: continent, geoname_id: 8133686, population: 20266)
province.comunes.create(description: "Σαρωνικού", region: region, country: state, continent: continent, geoname_id: 8133687, population: 29002)
province.comunes.create(description: "Σπάτων - Αρτέμιδος", region: region, country: state, continent: continent, geoname_id: 8133772, population: 33821)
province.comunes.create(description: "Ωρωπού", region: region, country: state, continent: continent, geoname_id: 8133773, population: 33769)
province = region.provinces.create(description: "Nomarchía Dytikís Attikís", country: state, continent: continent,  geoname_id: 445407, population: 0)
province.comunes.create(description: "Ασπροπύργου", region: region, country: state, continent: continent, geoname_id: 8133961, population: 30251)
province.comunes.create(description: "Ελευσίνας", region: region, country: state, continent: continent, geoname_id: 8133883, population: 29902)
province.comunes.create(description: "Μάνδρας - Ειδυλλίας", region: region, country: state, continent: continent, geoname_id: 8133884, population: 17885)
province.comunes.create(description: "Μεγαρέων", region: region, country: state, continent: continent, geoname_id: 8133885, population: 36924)
province.comunes.create(description: "Φυλής", region: region, country: state, continent: continent, geoname_id: 8133808, population: 45965)
province = region.provinces.create(description: "Nomós Piraiós", country: state, continent: continent,  geoname_id: 406101, population: 0)
province.comunes.create(description: "Ύδρα", region: region, country: state, continent: continent, geoname_id: 8133769, population: 1966)
province.comunes.create(description: "Αίγινας", region: region, country: state, continent: continent, geoname_id: 8133696, population: 13056)
province.comunes.create(description: "Αγκιστρίου", region: region, country: state, continent: continent, geoname_id: 8133874, population: 1142)
province.comunes.create(description: "Κερατσινίου - Δραπετσώνας", region: region, country: state, continent: continent, geoname_id: 8133965, population: 91045)
province.comunes.create(description: "Κορυδαλλού", region: region, country: state, continent: continent, geoname_id: 8133688, population: 63445)
province.comunes.create(description: "Κυθήρων", region: region, country: state, continent: continent, geoname_id: 8133702, population: 4041)
province.comunes.create(description: "Νίκαιας - Αγίου Ι. Ρέντη", region: region, country: state, continent: continent, geoname_id: 8133809, population: 105430)
province.comunes.create(description: "Πειραιώς", region: region, country: state, continent: continent, geoname_id: 8133777, population: 163688)
province.comunes.create(description: "Περάματος", region: region, country: state, continent: continent, geoname_id: 8133974, population: 25389)
province.comunes.create(description: "Πόρου", region: region, country: state, continent: continent, geoname_id: 8133709, population: 4282)
province.comunes.create(description: "Σαλαμίνας", region: region, country: state, continent: continent, geoname_id: 8133766, population: 39283)
province.comunes.create(description: "Σπετσών", region: region, country: state, continent: continent, geoname_id: 8133767, population: 4027)
province.comunes.create(description: "Τροιζηνίας-Μεθάνων", region: region, country: state, continent: continent, geoname_id: 8133768, population: 7143)
province = region.provinces.create(description: "Αττική", country: state, continent: continent,  geoname_id: 264353, population: 0)
province.comunes.create(description: "Kastélli", region: region, country: state, continent: continent, geoname_id: 260809, population: 0)
province.comunes.create(description: "Khlóï", region: region, country: state, continent: continent, geoname_id: 259961, population: 0)
province.comunes.create(description: "Áyios Spirídhon", region: region, country: state, continent: continent, geoname_id: 263733, population: 0)
province.comunes.create(description: "Ζωγράφος", region: region, country: state, continent: continent, geoname_id: 8358544, population: 71026)
province.comunes.create(description: "Πειραιάς", region: region, country: state, continent: continent, geoname_id: 255274, population: 163688)
province = region.provinces.create(description: "Νομαρχία Αθήνας", country: state, continent: continent,  geoname_id: 445408, population: 0)
province.comunes.create(description: "Αγίας Βαρβάρας", region: region, country: state, continent: continent, geoname_id: 8133771, population: 26550)
province.comunes.create(description: "Αγίας Παρασκευής", region: region, country: state, continent: continent, geoname_id: 8133828, population: 59704)
province.comunes.create(description: "Αγίου Δημητρίου", region: region, country: state, continent: continent, geoname_id: 8133667, population: 71294)
province.comunes.create(description: "Αγίων Αναργύρων - Καματερού", region: region, country: state, continent: continent, geoname_id: 8133819, population: 62529)
province.comunes.create(description: "Αθήναι", region: region, country: state, continent: continent, geoname_id: 8133876, population: 664046)
province.comunes.create(description: "Αιγάλεω", region: region, country: state, continent: continent, geoname_id: 8133973, population: 69946)
province.comunes.create(description: "Αλίμου", region: region, country: state, continent: continent, geoname_id: 8133951, population: 41720)
province.comunes.create(description: "Αμαρουσίου", region: region, country: state, continent: continent, geoname_id: 8133770, population: 72333)
province.comunes.create(description: "Βριλησσίων", region: region, country: state, continent: continent, geoname_id: 8133807, population: 30741)
province.comunes.create(description: "Βύρωνος", region: region, country: state, continent: continent, geoname_id: 8133859, population: 61308)
province.comunes.create(description: "Γαλατσίου", region: region, country: state, continent: continent, geoname_id: 8133798, population: 59345)
province.comunes.create(description: "Γλυφάδας", region: region, country: state, continent: continent, geoname_id: 8133886, population: 87305)
province.comunes.create(description: "Δάφνης - Υμηττού", region: region, country: state, continent: continent, geoname_id: 8133710, population: 33628)
province.comunes.create(description: "Ελληνικού - Αργυρούπολης", region: region, country: state, continent: continent, geoname_id: 8133982, population: 51356)
province.comunes.create(description: "Ζωγράφου", region: region, country: state, continent: continent, geoname_id: 8133877, population: 71026)
province.comunes.create(description: "Ηλιούπολης", region: region, country: state, continent: continent, geoname_id: 8133815, population: 78153)
province.comunes.create(description: "Ηρακλείου", region: region, country: state, continent: continent, geoname_id: 8133693, population: 49642)
province.comunes.create(description: "Ιλίου", region: region, country: state, continent: continent, geoname_id: 8133919, population: 84793)
province.comunes.create(description: "Καισαριανής", region: region, country: state, continent: continent, geoname_id: 8133881, population: 26458)
province.comunes.create(description: "Καλλιθέας", region: region, country: state, continent: continent, geoname_id: 8133880, population: 100641)
province.comunes.create(description: "Κηφισιάς", region: region, country: state, continent: continent, geoname_id: 8133694, population: 70600)
province.comunes.create(description: "Λυκόβρυσης - Πεύκης", region: region, country: state, continent: continent, geoname_id: 8133776, population: 31002)
province.comunes.create(description: "Μεταμόρφωση", region: region, country: state, continent: continent, geoname_id: 8133888, population: 29891)
province.comunes.create(description: "Μοσχάτου - Ταύρου", region: region, country: state, continent: continent, geoname_id: 8133676, population: 40413)
province.comunes.create(description: "Νέας Ιωνίας", region: region, country: state, continent: continent, geoname_id: 8133780, population: 67134)
province.comunes.create(description: "Νέας Σμύρνης", region: region, country: state, continent: continent, geoname_id: 8133665, population: 73076)
province.comunes.create(description: "Παλαιού Φαλήρου", region: region, country: state, continent: continent, geoname_id: 8133960, population: 64021)
province.comunes.create(description: "Παπάγου - Χολαργού", region: region, country: state, continent: continent, geoname_id: 8133839, population: 44539)
province.comunes.create(description: "Πεντέλης", region: region, country: state, continent: continent, geoname_id: 8133840, population: 34934)
province.comunes.create(description: "Περιστερίου", region: region, country: state, continent: continent, geoname_id: 8133783, population: 139981)
province.comunes.create(description: "Πετρούπολης", region: region, country: state, continent: continent, geoname_id: 8133926, population: 58979)
province.comunes.create(description: "Φιλαδελφείας - Χαλκηδόνος", region: region, country: state, continent: continent, geoname_id: 8133680, population: 35556)
province.comunes.create(description: "Φιλοθέης - Ψυχικού", region: region, country: state, continent: continent, geoname_id: 8133782, population: 26968)
province.comunes.create(description: "Χαλανδρίου", region: region, country: state, continent: continent, geoname_id: 8133842, population: 74192)
province.comunes.create(description: "Χαϊδαρίου", region: region, country: state, continent: continent, geoname_id: 8133972, population: 46897)
region = Region.create(description: "Αυτόνομη Μοναστική Πολιτεία Αγίου Όρους", country: state, continent: continent, geoname_id: 736572)
province = region.provinces.create(description: "Dáfni", country: state, continent: continent,  geoname_id: 736482, population: 0)
province = region.provinces.create(description: "Monoxilítai", country: state, continent: continent,  geoname_id: 735047, population: 0)
province = region.provinces.create(description: "Ελιά", country: state, continent: continent,  geoname_id: 736329, population: 0)
province = region.provinces.create(description: "Θηβαΐς", country: state, continent: continent,  geoname_id: 734068, population: 0)
province = region.provinces.create(description: "Καρυές", country: state, continent: continent,  geoname_id: 735972, population: 237)
region = Region.create(description: "Βόρειο Αιγαίο", country: state, continent: continent, geoname_id: 6697806)
province = region.provinces.create(description: "Λέσβος", country: state, continent: continent,  geoname_id: 258465, population: 0)
province.comunes.create(description: "Άγιος Ευστράτιος", region: region, country: state, continent: continent, geoname_id: 8133756, population: 307)
province.comunes.create(description: "Λέσβος", region: region, country: state, continent: continent, geoname_id: 8133755, population: 90436)
province.comunes.create(description: "Λήμνος", region: region, country: state, continent: continent, geoname_id: 8133757, population: 17545)
province = region.provinces.create(description: "Σάμος", country: state, continent: continent,  geoname_id: 254112, population: 0)
province.comunes.create(description: "Ικαρία", region: region, country: state, continent: continent, geoname_id: 8133747, population: 8354)
province.comunes.create(description: "Σάμος", region: region, country: state, continent: continent, geoname_id: 8133749, population: 34000)
province.comunes.create(description: "Φούρνων Κορσεών", region: region, country: state, continent: continent, geoname_id: 8133748, population: 1487)
province = region.provinces.create(description: "Χίος", country: state, continent: continent,  geoname_id: 259970, population: 0)
province.comunes.create(description: "Οινουσσών", region: region, country: state, continent: continent, geoname_id: 8133820, population: 855)
province.comunes.create(description: "Χίου", region: region, country: state, continent: continent, geoname_id: 8133821, population: 51773)
province.comunes.create(description: "Ψαρών", region: region, country: state, continent: continent, geoname_id: 8133829, population: 478)
region = Region.create(description: "Δυτική Ελλάδα", country: state, continent: continent, geoname_id: 6697810)
province = region.provinces.create(description: "Αιτωλοακαρνανία", country: state, continent: continent,  geoname_id: 265508, population: 210802)
province.comunes.create(description: "Άκτιου - Βόνιτσας", region: region, country: state, continent: continent, geoname_id: 8133701, population: 17872)
province.comunes.create(description: "Αγρινίου", region: region, country: state, continent: continent, geoname_id: 8133845, population: 96889)
province.comunes.create(description: "Αμφιλοχίας", region: region, country: state, continent: continent, geoname_id: 8133705, population: 20491)
province.comunes.create(description: "Θέρμου", region: region, country: state, continent: continent, geoname_id: 8133703, population: 7837)
province.comunes.create(description: "Ιεράς Πόλης Μεσολογγίου", region: region, country: state, continent: continent, geoname_id: 8133706, population: 35805)
province.comunes.create(description: "Ναυπακτίας", region: region, country: state, continent: continent, geoname_id: 8133707, population: 26840)
province.comunes.create(description: "Ξηρομέρου", region: region, country: state, continent: continent, geoname_id: 8133708, population: 13358)
province = region.provinces.create(description: "Αχαΐα", country: state, continent: continent,  geoname_id: 265491, population: 331316)
province.comunes.create(description: "Αιγιαλείας", region: region, country: state, continent: continent, geoname_id: 8133669, population: 53585)
province.comunes.create(description: "Δυτικής Αχαΐας", region: region, country: state, continent: continent, geoname_id: 8133671, population: 29608)
province.comunes.create(description: "Ερυμάνθου", region: region, country: state, continent: continent, geoname_id: 8133672, population: 11329)
province.comunes.create(description: "Καλαβρύτων", region: region, country: state, continent: continent, geoname_id: 8133670, population: 13912)
province.comunes.create(description: "Πατρέων", region: region, country: state, continent: continent, geoname_id: 8133690, population: 210494)
province = region.provinces.create(description: "Ηλεία", country: state, continent: continent,  geoname_id: 261797, population: 198763)
province.comunes.create(description: "Ήλιδας", region: region, country: state, continent: continent, geoname_id: 8133712, population: 36275)
province.comunes.create(description: "Ανδρίτσαινας - Κρεστένων", region: region, country: state, continent: continent, geoname_id: 8133677, population: 21139)
province.comunes.create(description: "Ανδραβίδας - Κυλλήνης", region: region, country: state, continent: continent, geoname_id: 8133691, population: 24668)
province.comunes.create(description: "Αρχαίας Ολυμπίας", region: region, country: state, continent: continent, geoname_id: 8133692, population: 16431)
province.comunes.create(description: "Ζαχάρως", region: region, country: state, continent: continent, geoname_id: 8133711, population: 13716)
province.comunes.create(description: "Πηνειού", region: region, country: state, continent: continent, geoname_id: 8133689, population: 19658)
province.comunes.create(description: "Πύργου", region: region, country: state, continent: continent, geoname_id: 8133887, population: 51634)
region = Region.create(description: "Δυτική Μακεδονία", country: state, continent: continent, geoname_id: 6697811)
province = region.provinces.create(description: "Γρεβενά", country: state, continent: continent,  geoname_id: 736149, population: 0)
province.comunes.create(description: "Γρεβενών", region: region, country: state, continent: continent, geoname_id: 8133976, population: 25522)
province.comunes.create(description: "Δεσκάτης", region: region, country: state, continent: continent, geoname_id: 8133858, population: 7045)
province = region.provinces.create(description: "Καστοριά", country: state, continent: continent,  geoname_id: 735925, population: 0)
province.comunes.create(description: "Άργους Ορεστικού", region: region, country: state, continent: continent, geoname_id: 8133860, population: 13479)
province.comunes.create(description: "Καστοριάς", region: region, country: state, continent: continent, geoname_id: 8133966, population: 37094)
province.comunes.create(description: "Νεστορίου", region: region, country: state, continent: continent, geoname_id: 8133967, population: 3129)
province = region.provinces.create(description: "Κοζάνη", country: state, continent: continent,  geoname_id: 735562, population: 0)
province.comunes.create(description: "Βοϊου", region: region, country: state, continent: continent, geoname_id: 8133797, population: 20430)
province.comunes.create(description: "Εορδαίας", region: region, country: state, continent: continent, geoname_id: 8133857, population: 46555)
province.comunes.create(description: "Κοζάνης", region: region, country: state, continent: continent, geoname_id: 8133764, population: 70220)
province.comunes.create(description: "Σερβίων - Βελβεντού", region: region, country: state, continent: continent, geoname_id: 8133872, population: 16734)
province = region.provinces.create(description: "Φλώρινα", country: state, continent: continent,  geoname_id: 736228, population: 0)
province.comunes.create(description: "Αμυνταίου", region: region, country: state, continent: continent, geoname_id: 8133871, population: 18357)
province.comunes.create(description: "Πρεσπών", region: region, country: state, continent: continent, geoname_id: 8133873, population: 2164)
province.comunes.create(description: "Φλώρινας", region: region, country: state, continent: continent, geoname_id: 8133716, population: 33588)
region = Region.create(description: "Θεσσαλία", country: state, continent: continent, geoname_id: 6697809)
province = region.provinces.create(description: "Καρδίτσα", country: state, continent: continent,  geoname_id: 260988, population: 0)
province.comunes.create(description: "Αργιθέας", region: region, country: state, continent: continent, geoname_id: 8133980, population: 2488)
province.comunes.create(description: "Καρδίτσας", region: region, country: state, continent: continent, geoname_id: 8133984, population: 57089)
province.comunes.create(description: "Λίμνης Πλαστήρα", region: region, country: state, continent: continent, geoname_id: 8133733, population: 4022)
province.comunes.create(description: "Μουζακίου", region: region, country: state, continent: continent, geoname_id: 8133792, population: 16407)
province.comunes.create(description: "Παλαμά", region: region, country: state, continent: continent, geoname_id: 8133793, population: 18500)
province.comunes.create(description: "Σοφάδων", region: region, country: state, continent: continent, geoname_id: 8133794, population: 21759)
province = region.provinces.create(description: "Λάρισα", country: state, continent: continent,  geoname_id: 258575, population: 0)
province.comunes.create(description: "Αγιάς", region: region, country: state, continent: continent, geoname_id: 8133788, population: 13120)
province.comunes.create(description: "Ελασσόνας", region: region, country: state, continent: continent, geoname_id: 8133784, population: 35358)
province.comunes.create(description: "Κιλελέρ", region: region, country: state, continent: continent, geoname_id: 8133785, population: 22719)
province.comunes.create(description: "Λαρισαίων", region: region, country: state, continent: continent, geoname_id: 8133786, population: 145981)
province.comunes.create(description: "Τεμπών", region: region, country: state, continent: continent, geoname_id: 8133789, population: 15439)
province.comunes.create(description: "Τυρνάβου", region: region, country: state, continent: continent, geoname_id: 8133787, population: 25864)
province.comunes.create(description: "Φαρσάλων", region: region, country: state, continent: continent, geoname_id: 8133790, population: 23675)
province = region.provinces.create(description: "Μαγνησία", country: state, continent: continent,  geoname_id: 258013, population: 0)
province.comunes.create(description: "Αλμυρού", region: region, country: state, continent: continent, geoname_id: 8133791, population: 20139)
province.comunes.create(description: "Αλοννήσου", region: region, country: state, continent: continent, geoname_id: 8133938, population: 2425)
province.comunes.create(description: "Βόλου", region: region, country: state, continent: continent, geoname_id: 8133894, population: 142923)
province.comunes.create(description: "Ζαγοράς - Μουρεσίου", region: region, country: state, continent: continent, geoname_id: 8133935, population: 6449)
province.comunes.create(description: "Νοτίου Πηλίου", region: region, country: state, continent: continent, geoname_id: 8133936, population: 10745)
province.comunes.create(description: "Ρήγα Φερραίου", region: region, country: state, continent: continent, geoname_id: 8133937, population: 11830)
province.comunes.create(description: "Σκιάθου", region: region, country: state, continent: continent, geoname_id: 8133939, population: 5788)
province.comunes.create(description: "Σκοπέλου", region: region, country: state, continent: continent, geoname_id: 8133893, population: 4706)
province = region.provinces.create(description: "Τρίκαλα", country: state, continent: continent,  geoname_id: 252661, population: 0)
province.comunes.create(description: "Καλαμπάκας", region: region, country: state, continent: continent, geoname_id: 8133942, population: 22853)
province.comunes.create(description: "Πύλης", region: region, country: state, continent: continent, geoname_id: 8133843, population: 15886)
province.comunes.create(description: "Τρικκαίων", region: region, country: state, continent: continent, geoname_id: 8133844, population: 78817)
province.comunes.create(description: "Φαρκαδόνας", region: region, country: state, continent: continent, geoname_id: 8133853, population: 15133)
region = Region.create(description: "Ιόνια Νησιά", country: state, continent: continent, geoname_id: 6697805)
province = region.provinces.create(description: "Ζάκυνθος", country: state, continent: continent,  geoname_id: 251276, population: 41472)
province.comunes.create(description: "Ζακύνθου", region: region, country: state, continent: continent, geoname_id: 8133854, population: 38883)
province = region.provinces.create(description: "Κέρκυρα", country: state, continent: continent,  geoname_id: 2463676, population: 113658)
province.comunes.create(description: "Κέρκυρα", region: region, country: state, continent: continent, geoname_id: 8133855, population: 108652)
province.comunes.create(description: "Παξών", region: region, country: state, continent: continent, geoname_id: 8133911, population: 2429)
province = region.provinces.create(description: "Κεφαλονιά", country: state, continent: continent,  geoname_id: 260310, population: 0)
province.comunes.create(description: "Ιθάκης", region: region, country: state, continent: continent, geoname_id: 8133849, population: 3212)
province.comunes.create(description: "Κεφαλονιάς", region: region, country: state, continent: continent, geoname_id: 8133850, population: 34544)
province = region.provinces.create(description: "Λευκάδα", country: state, continent: continent,  geoname_id: 258445, population: 22879)
province.comunes.create(description: "Λευκάδας", region: region, country: state, continent: continent, geoname_id: 8133851, population: 20894)
province.comunes.create(description: "Μεγανησίου", region: region, country: state, continent: continent, geoname_id: 8133852, population: 994)
region = Region.create(description: "Κεντρική Ελλάδα", country: state, continent: continent, geoname_id: 6697800)
province = region.provinces.create(description: "Βοιωτία", country: state, continent: continent,  geoname_id: 251851, population: 0)
province.comunes.create(description: "Αλιάρτου", region: region, country: state, continent: continent, geoname_id: 8133875, population: 11686)
province.comunes.create(description: "Διστόμου-Αράχοβας - Αντίκυρας", region: region, country: state, continent: continent, geoname_id: 8133907, population: 9802)
province.comunes.create(description: "Θηβαίων", region: region, country: state, continent: continent, geoname_id: 8133908, population: 36086)
province.comunes.create(description: "Λεβαδέων", region: region, country: state, continent: continent, geoname_id: 8133909, population: 36086)
province.comunes.create(description: "Ορχομενού", region: region, country: state, continent: continent, geoname_id: 8133910, population: 13032)
province.comunes.create(description: "Τανάγρας", region: region, country: state, continent: continent, geoname_id: 8133914, population: 21156)
province = region.provinces.create(description: "Ευρυτανία", country: state, continent: continent,  geoname_id: 262572, population: 34855)
province.comunes.create(description: "Αγράφων", region: region, country: state, continent: continent, geoname_id: 8133730, population: 7190)
province.comunes.create(description: "Καρπενησίου", region: region, country: state, continent: continent, geoname_id: 8133731, population: 12328)
province = region.provinces.create(description: "Εύβοια", country: state, continent: continent,  geoname_id: 262564, population: 0)
province.comunes.create(description: "Διρφύων - Μεσσαπίων", region: region, country: state, continent: continent, geoname_id: 8133901, population: 19443)
province.comunes.create(description: "Ερέτριας", region: region, country: state, continent: continent, geoname_id: 8133902, population: 12218)
province.comunes.create(description: "Ιστιαίας - Αιδηψού", region: region, country: state, continent: continent, geoname_id: 8133903, population: 22132)
province.comunes.create(description: "Καρύστου", region: region, country: state, continent: continent, geoname_id: 8133904, population: 13602)
province.comunes.create(description: "Κύμης - Αλιβερίου", region: region, country: state, continent: continent, geoname_id: 8133905, population: 30717)
province.comunes.create(description: "Μαντουδίου - Λίμνης - Αγίας Άννας", region: region, country: state, continent: continent, geoname_id: 8133906, population: 13673)
province.comunes.create(description: "Σκύρου", region: region, country: state, continent: continent, geoname_id: 8133975, population: 2711)
province.comunes.create(description: "Χαλκιδέων", region: region, country: state, continent: continent, geoname_id: 8133729, population: 92809)
province = region.provinces.create(description: "Φθιώτιδα", country: state, continent: continent,  geoname_id: 262187, population: 0)
province.comunes.create(description: "Αμφίκλειας - Ελάτειας", region: region, country: state, continent: continent, geoname_id: 8133732, population: 10922)
province.comunes.create(description: "Δομοκού", region: region, country: state, continent: continent, geoname_id: 8133737, population: 11495)
province.comunes.create(description: "Λαμιέων", region: region, country: state, continent: continent, geoname_id: 8133738, population: 75315)
province.comunes.create(description: "Λοκρών", region: region, country: state, continent: continent, geoname_id: 8133739, population: 19623)
province.comunes.create(description: "Μακρακώμης", region: region, country: state, continent: continent, geoname_id: 8133740, population: 16036)
province.comunes.create(description: "Μώλου - Αγ. Κωνσταντίνου", region: region, country: state, continent: continent, geoname_id: 8133746, population: 13932)
province.comunes.create(description: "Στυλίδας", region: region, country: state, continent: continent, geoname_id: 8133765, population: 14118)
province = region.provinces.create(description: "Φωκίδα", country: state, continent: continent,  geoname_id: 262322, population: 49576)
province.comunes.create(description: "Δελφών", region: region, country: state, continent: continent, geoname_id: 8133744, population: 26992)
province.comunes.create(description: "Δωρίδος", region: region, country: state, continent: continent, geoname_id: 8133745, population: 10874)
region = Region.create(description: "Κεντρική Μακεδονία", country: state, continent: continent, geoname_id: 6697801)
province = region.provinces.create(description: "Ημαθία", country: state, continent: continent,  geoname_id: 736120, population: 0)
province.comunes.create(description: "Αλεξάνδρειας", region: region, country: state, continent: continent, geoname_id: 8133931, population: 42777)
province.comunes.create(description: "Βέροιας", region: region, country: state, continent: continent, geoname_id: 8133932, population: 65530)
province.comunes.create(description: "Νάουσας", region: region, country: state, continent: continent, geoname_id: 8133882, population: 34164)
province = region.provinces.create(description: "Θεσσαλονίκη", country: state, continent: continent,  geoname_id: 734075, population: 0)
province.comunes.create(description: "Αμπελοκήπων - Μενεμένης", region: region, country: state, continent: continent, geoname_id: 8133985, population: 58149)
province.comunes.create(description: "Βόλβης", region: region, country: state, continent: continent, geoname_id: 8133915, population: 24454)
province.comunes.create(description: "Δέλτα", region: region, country: state, continent: continent, geoname_id: 8133916, population: 40206)
province.comunes.create(description: "Θέρμης", region: region, country: state, continent: continent, geoname_id: 8133763, population: 34436)
province.comunes.create(description: "Θερμαϊκού", region: region, country: state, continent: continent, geoname_id: 8133917, population: 37126)
province.comunes.create(description: "Θεσσαλονίκης", region: region, country: state, continent: continent, geoname_id: 8133841, population: 397156)
province.comunes.create(description: "Καλαμαριάς", region: region, country: state, continent: continent, geoname_id: 8133959, population: 90096)
province.comunes.create(description: "Κορδελιού - Ευόσμου", region: region, country: state, continent: continent, geoname_id: 8133918, population: 77174)
province.comunes.create(description: "Λαγκαδά", region: region, country: state, continent: continent, geoname_id: 8133981, population: 39160)
province.comunes.create(description: "Νέαπολης - Συκεών", region: region, country: state, continent: continent, geoname_id: 8133678, population: 89274)
province.comunes.create(description: "Παύλου Μελά", region: region, country: state, continent: continent, geoname_id: 8133666, population: 87587)
province.comunes.create(description: "Πυλαίας - Χορτιάτη", region: region, country: state, continent: continent, geoname_id: 8133774, population: 49922)
province.comunes.create(description: "Χαλκηδόνος", region: region, country: state, continent: continent, geoname_id: 8133775, population: 34299)
province.comunes.create(description: "Ωραιοκάστρου", region: region, country: state, continent: continent, geoname_id: 8133795, population: 24962)
province = region.provinces.create(description: "Κιλκίς", country: state, continent: continent,  geoname_id: 735735, population: 0)
province.comunes.create(description: "Κιλκίς", region: region, country: state, continent: continent, geoname_id: 8133969, population: 54750)
province.comunes.create(description: "Παιονίας", region: region, country: state, continent: continent, geoname_id: 8133970, population: 31674)
province = region.provinces.create(description: "Πέλλα", country: state, continent: continent,  geoname_id: 734725, population: 0)
province.comunes.create(description: "Έδεσσας", region: region, country: state, continent: continent, geoname_id: 8133912, population: 29568)
province.comunes.create(description: "Αλμωπίας", region: region, country: state, continent: continent, geoname_id: 8133796, population: 28822)
province.comunes.create(description: "Πέλλας", region: region, country: state, continent: continent, geoname_id: 8133848, population: 64847)
province.comunes.create(description: "Σκύδρας", region: region, country: state, continent: continent, geoname_id: 8133913, population: 20720)
province = region.provinces.create(description: "Πιερία", country: state, continent: continent,  geoname_id: 734649, population: 0)
province.comunes.create(description: "Δίου - Ολύμπου", region: region, country: state, continent: continent, geoname_id: 8133846, population: 25872)
province.comunes.create(description: "Κατερίνης", region: region, country: state, continent: continent, geoname_id: 8133847, population: 83387)
province.comunes.create(description: "Πύδνας - Κολινδρού", region: region, country: state, continent: continent, geoname_id: 8133861, population: 17153)
province = region.provinces.create(description: "Σέρρες", country: state, continent: continent,  geoname_id: 734329, population: 0)
province.comunes.create(description: "Αμφίπολης", region: region, country: state, continent: continent, geoname_id: 8133862, population: 11860)
province.comunes.create(description: "Βισαλτίας", region: region, country: state, continent: continent, geoname_id: 8133863, population: 23158)
province.comunes.create(description: "Εμμανουήλ Παππά", region: region, country: state, continent: continent, geoname_id: 8133856, population: 19053)
province.comunes.create(description: "Ηρακλείας", region: region, country: state, continent: continent, geoname_id: 8133864, population: 22695)
province.comunes.create(description: "Νέας Ζίχνης", region: region, country: state, continent: continent, geoname_id: 8133865, population: 13813)
province.comunes.create(description: "Σερρών", region: region, country: state, continent: continent, geoname_id: 8133866, population: 76472)
province.comunes.create(description: "Σιντικής", region: region, country: state, continent: continent, geoname_id: 8133867, population: 27432)
province = region.provinces.create(description: "Χαλκιδική", country: state, continent: continent,  geoname_id: 735804, population: 109587)
province.comunes.create(description: "Αριστοτέλη", region: region, country: state, continent: continent, geoname_id: 8133868, population: 17752)
province.comunes.create(description: "Κασσάνδρας", region: region, country: state, continent: continent, geoname_id: 8133869, population: 14971)
province.comunes.create(description: "Νέας Προποντίδας", region: region, country: state, continent: continent, geoname_id: 8133870, population: 30397)
province.comunes.create(description: "Πολυγύρου", region: region, country: state, continent: continent, geoname_id: 8133962, population: 21931)
province.comunes.create(description: "Σιθωνίας", region: region, country: state, continent: continent, geoname_id: 8133963, population: 11798)
region = Region.create(description: "Κρήτη", country: state, continent: continent, geoname_id: 6697802)
province = region.provinces.create(description: "Ηράκλειο", country: state, continent: continent,  geoname_id: 261741, population: 302846)
province.comunes.create(description: "Αρχανών - Αστερουσίων", region: region, country: state, continent: continent, geoname_id: 8133817, population: 17531)
province.comunes.create(description: "Βιάννου", region: region, country: state, continent: continent, geoname_id: 8133818, population: 5983)
province.comunes.create(description: "Γόρτυνας", region: region, country: state, continent: continent, geoname_id: 8133944, population: 17423)
province.comunes.create(description: "Ηρακλείου", region: region, country: state, continent: continent, geoname_id: 8133920, population: 163115)
province.comunes.create(description: "Μαλεβιζίου", region: region, country: state, continent: continent, geoname_id: 8133945, population: 20735)
province.comunes.create(description: "Μινώα Πεδιάδας", region: region, country: state, continent: continent, geoname_id: 8133810, population: 18692)
province.comunes.create(description: "Φαιστού", region: region, country: state, continent: continent, geoname_id: 8133968, population: 23882)
province.comunes.create(description: "Χερσονήσου", region: region, country: state, continent: continent, geoname_id: 8133695, population: 23864)
province = region.provinces.create(description: "Λασίθι", country: state, continent: continent,  geoname_id: 258569, population: 0)
province.comunes.create(description: "Αγίου Νικολάου", region: region, country: state, continent: continent, geoname_id: 8133929, population: 26069)
province.comunes.create(description: "Ιεράπετρας", region: region, country: state, continent: continent, geoname_id: 8133930, population: 27744)
province.comunes.create(description: "Οροπεδίου Λασιθίου", region: region, country: state, continent: continent, geoname_id: 8133925, population: 3067)
province.comunes.create(description: "Σητείας", region: region, country: state, continent: continent, geoname_id: 8133948, population: 27744)
province = region.provinces.create(description: "Ρέθυμνο", country: state, continent: continent,  geoname_id: 254353, population: 86532)
province.comunes.create(description: "Αγίου Βασιλείου", region: region, country: state, continent: continent, geoname_id: 8133949, population: 8648)
province.comunes.create(description: "Αμάριου", region: region, country: state, continent: continent, geoname_id: 8133983, population: 5633)
province.comunes.create(description: "Ανωγείων", region: region, country: state, continent: continent, geoname_id: 8133943, population: 4054)
province.comunes.create(description: "Μυλοποτάμου", region: region, country: state, continent: continent, geoname_id: 8133758, population: 13350)
province.comunes.create(description: "Ρεθύμνης", region: region, country: state, continent: continent, geoname_id: 8133759, population: 47272)
province = region.provinces.create(description: "Χανιά", country: state, continent: continent,  geoname_id: 260096, population: 0)
province.comunes.create(description: "Αποκορώνου", region: region, country: state, continent: continent, geoname_id: 8133750, population: 12112)
province.comunes.create(description: "Γαύδου", region: region, country: state, continent: continent, geoname_id: 8133751, population: 81)
province.comunes.create(description: "Κίσσαμος", region: region, country: state, continent: continent, geoname_id: 8133753, population: 11470)
province.comunes.create(description: "Καντάνου - Σέλινου", region: region, country: state, continent: continent, geoname_id: 8133752, population: 6302)
province.comunes.create(description: "Πλατανιά", region: region, country: state, continent: continent, geoname_id: 8133754, population: 17864)
province.comunes.create(description: "Σφακίων", region: region, country: state, continent: continent, geoname_id: 8133761, population: 2419)
province.comunes.create(description: "Χανιά", region: region, country: state, continent: continent, geoname_id: 8133762, population: 98202)
region = Region.create(description: "Νότιο Αιγαίο", country: state, continent: continent, geoname_id: 6697808)
province = region.provinces.create(description: "Δωδεκάνησα", country: state, continent: continent,  geoname_id: 263021, population: 0)
province.comunes.create(description: "Αγαθονήσι", region: region, country: state, continent: continent, geoname_id: 8133824, population: 152)
province.comunes.create(description: "Αστυπαλαίας", region: region, country: state, continent: continent, geoname_id: 8133811, population: 1385)
province.comunes.create(description: "Κάσου", region: region, country: state, continent: continent, geoname_id: 8133956, population: 1013)
province.comunes.create(description: "Καλυμνίων", region: region, country: state, continent: continent, geoname_id: 8133812, population: 16576)
province.comunes.create(description: "Καρπάθου", region: region, country: state, continent: continent, geoname_id: 8133955, population: 6565)
province.comunes.create(description: "Κω", region: region, country: state, continent: continent, geoname_id: 8133957, population: 30828)
province.comunes.create(description: "Λέρου", region: region, country: state, continent: continent, geoname_id: 8133814, population: 8172)
province.comunes.create(description: "Λειψών", region: region, country: state, continent: continent, geoname_id: 8133813, population: 687)
province.comunes.create(description: "Μεγίστης", region: region, country: state, continent: continent, geoname_id: 8133700, population: 403)
province.comunes.create(description: "Νισύρου", region: region, country: state, continent: continent, geoname_id: 8133958, population: 928)
province.comunes.create(description: "Πάτμου", region: region, country: state, continent: continent, geoname_id: 8133954, population: 3053)
province.comunes.create(description: "Ρόδου", region: region, country: state, continent: continent, geoname_id: 8133781, population: 115334)
province.comunes.create(description: "Σύμης", region: region, country: state, continent: continent, geoname_id: 8133940, population: 2594)
province.comunes.create(description: "Τήλου", region: region, country: state, continent: continent, geoname_id: 8133941, population: 521)
province.comunes.create(description: "Χάλκης", region: region, country: state, continent: continent, geoname_id: 8133964, population: 295)
province = region.provinces.create(description: "Κυκλάδες", country: state, continent: continent,  geoname_id: 259819, population: 119549)
province.comunes.create(description: "Άνδρου", region: region, country: state, continent: continent, geoname_id: 8133830, population: 9285)
province.comunes.create(description: "Αμοργού", region: region, country: state, continent: continent, geoname_id: 8133934, population: 1852)
province.comunes.create(description: "Ανάφης", region: region, country: state, continent: continent, geoname_id: 8133831, population: 272)
province.comunes.create(description: "Αντιπάρου", region: region, country: state, continent: continent, geoname_id: 8133698, population: 1011)
province.comunes.create(description: "Ιητών", region: region, country: state, continent: continent, geoname_id: 8133833, population: 1862)
province.comunes.create(description: "Κέας", region: region, country: state, continent: continent, geoname_id: 8133952, population: 2162)
province.comunes.create(description: "Κίμωλος", region: region, country: state, continent: continent, geoname_id: 8133679, population: 910)
province.comunes.create(description: "Κύθνου", region: region, country: state, continent: continent, geoname_id: 8133953, population: 1538)
province.comunes.create(description: "Μήλος", region: region, country: state, continent: continent, geoname_id: 8133681, population: 4977)
province.comunes.create(description: "Μύκονος", region: region, country: state, continent: continent, geoname_id: 8133933, population: 9274)
province.comunes.create(description: "Νάξου & Μικρών Κυκλάδων", region: region, country: state, continent: continent, geoname_id: 8133697, population: 18229)
province.comunes.create(description: "Πάρου", region: region, country: state, continent: continent, geoname_id: 8133699, population: 12514)
province.comunes.create(description: "Σίφνου", region: region, country: state, continent: continent, geoname_id: 8133683, population: 2574)
province.comunes.create(description: "Σαντορίνη", region: region, country: state, continent: continent, geoname_id: 8133832, population: 13725)
province.comunes.create(description: "Σερίφου", region: region, country: state, continent: continent, geoname_id: 8133682, population: 1262)
province.comunes.create(description: "Σικίνου", region: region, country: state, continent: continent, geoname_id: 8133822, population: 238)
province.comunes.create(description: "Σύρος", region: region, country: state, continent: continent, geoname_id: 8133927, population: 19793)
province.comunes.create(description: "Τήνος", region: region, country: state, continent: continent, geoname_id: 8133928, population: 8115)
province.comunes.create(description: "Φολεγάνδρου", region: region, country: state, continent: continent, geoname_id: 8133823, population: 676)
region = Region.create(description: "Πελοπόννησος", country: state, continent: continent, geoname_id: 6697807)
province = region.provinces.create(description: "Αργολίδα", country: state, continent: continent,  geoname_id: 264673, population: 0)
province.comunes.create(description: "Άργους - Μυκηνών", region: region, country: state, continent: continent, geoname_id: 8133979, population: 47745)
province.comunes.create(description: "Επιδαύρου", region: region, country: state, continent: continent, geoname_id: 8133804, population: 8710)
province.comunes.create(description: "Ερμιονίδας", region: region, country: state, continent: continent, geoname_id: 8133805, population: 14330)
province.comunes.create(description: "Ναυπλιέων", region: region, country: state, continent: continent, geoname_id: 8133806, population: 31607)
province = region.provinces.create(description: "Αρκαδία", country: state, continent: continent,  geoname_id: 264644, population: 0)
province.comunes.create(description: "Βόρειας Κυνουρίας", region: region, country: state, continent: continent, geoname_id: 8133800, population: 11589)
province.comunes.create(description: "Γορτυνίας", region: region, country: state, continent: continent, geoname_id: 8133801, population: 12492)
province.comunes.create(description: "Μεγαλόπολης", region: region, country: state, continent: continent, geoname_id: 8133802, population: 11044)
province.comunes.create(description: "Νότιας Κυνουρίας", region: region, country: state, continent: continent, geoname_id: 8133803, population: 7633)
province.comunes.create(description: "Τρίπολης", region: region, country: state, continent: continent, geoname_id: 8133668, population: 48568)
province = region.provinces.create(description: "Κορινθία", country: state, continent: continent,  geoname_id: 259290, population: 0)
province.comunes.create(description: "Βέλου - Βόχας", region: region, country: state, continent: continent, geoname_id: 8133799, population: 17251)
province.comunes.create(description: "Κορινθίων", region: region, country: state, continent: continent, geoname_id: 8133673, population: 58523)
province.comunes.create(description: "Λουτρακίου-Περαχώρας-Αγίων Θεοδώρων", region: region, country: state, continent: continent, geoname_id: 8133977, population: 20040)
province.comunes.create(description: "Νεμέας", region: region, country: state, continent: continent, geoname_id: 8133674, population: 7286)
province.comunes.create(description: "Ξυλοκάστρου - Ευρωστίνης", region: region, country: state, continent: continent, geoname_id: 8133978, population: 18224)
province.comunes.create(description: "Σικυωνίων", region: region, country: state, continent: continent, geoname_id: 8133675, population: 23203)
province = region.provinces.create(description: "Λακωνία", country: state, continent: continent,  geoname_id: 258657, population: 0)
province.comunes.create(description: "Ανατολικής Μάνης", region: region, country: state, continent: continent, geoname_id: 8133713, population: 14308)
province.comunes.create(description: "Ελαφονήσου", region: region, country: state, continent: continent, geoname_id: 8133714, population: 746)
province.comunes.create(description: "Ευρώτα", region: region, country: state, continent: continent, geoname_id: 8133715, population: 19319)
province.comunes.create(description: "Μονεμβασιάς", region: region, country: state, continent: continent, geoname_id: 8133723, population: 21898)
province.comunes.create(description: "Σπάρτης", region: region, country: state, continent: continent, geoname_id: 8133718, population: 36540)
province = region.provinces.create(description: "Μεσσηνία", country: state, continent: continent,  geoname_id: 257149, population: 0)
province.comunes.create(description: "Δυτικής Μάνης", region: region, country: state, continent: continent, geoname_id: 8133724, population: 6658)
province.comunes.create(description: "Καλαμάτας", region: region, country: state, continent: continent, geoname_id: 8133971, population: 70006)
province.comunes.create(description: "Μεσσήνης", region: region, country: state, continent: continent, geoname_id: 8133986, population: 25859)
province.comunes.create(description: "Οιχαλίας", region: region, country: state, continent: continent, geoname_id: 8133987, population: 11681)
province.comunes.create(description: "Πύλου - Νέστορος", region: region, country: state, continent: continent, geoname_id: 8133988, population: 21172)
province.comunes.create(description: "Τριφυλίας", region: region, country: state, continent: continent, geoname_id: 8133760, population: 31190)
