#encoding: utf-8
Comune.create(:description => "Bahía de Caráquez (Sucre)", :provincia_id => 130, :regione_id => 1, stato_id: 54, continente_id: 2 , :population => 20921)
Comune.create(:description => "Calceta (Bolivar)", :provincia_id => 130, :regione_id => 1, stato_id: 54, continente_id: 2 , :population => 17632)
Comune.create(:description => "Chone", :provincia_id => 130, :regione_id => 1, stato_id: 54, continente_id: 2 , :population => 52810)
Comune.create(:description => "El Carmen", :provincia_id => 130, :regione_id => 1, stato_id: 54, continente_id: 2 , :population => 46358)
Comune.create(:description => "Jaramijó", :provincia_id => 130, :regione_id => 1, stato_id: 54, continente_id: 2 , :population => 17208)
Comune.create(:description => "Jipijapa", :provincia_id => 130, :regione_id => 1, stato_id: 54, continente_id: 2 , :population => 40232)
Comune.create(:description => "Manta", :provincia_id => 130, :regione_id => 1, stato_id: 54, continente_id: 2 , :population => 217553)
Comune.create(:description => "Montecristi", :provincia_id => 130, :regione_id => 1, stato_id: 54, continente_id: 2 , :population => 46312)
Comune.create(:description => "Pedernales", :provincia_id => 130, :regione_id => 1, stato_id: 54, continente_id: 2 , :population => 21910)
Comune.create(:description => "Portoviejo", :provincia_id => 130, :regione_id => 1, stato_id: 54, continente_id: 2 , :population => 206682)
