#encoding: utf-8
Comune.create(description: "Acquaformosa", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 1295)
Comune.create(description: "Acquappesa", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 2068)
Comune.create(description: "Acri", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 21891)
Comune.create(description: "Aiello Calabro", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 2446)
Comune.create(description: "Aieta", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 892)
Comune.create(description: "Albidona", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 1784)
Comune.create(description: "Alessandria Del Carretto", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 745)
Comune.create(description: "Altilia", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 775)
Comune.create(description: "Altomonte", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 4494)
Comune.create(description: "Amantea", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 13268)
Comune.create(description: "Amendolara", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 3147)
Comune.create(description: "Aprigliano", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 2816)
Comune.create(description: "Belmonte Calabro", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 3022)
Comune.create(description: "Belsito", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 930)
Comune.create(description: "Belvedere Marittimo", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 8881)
Comune.create(description: "Bianchi", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 1543)
Comune.create(description: "Bisignano", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 10924)
Comune.create(description: "Bocchigliero", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 1897)
Comune.create(description: "Bonifati", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 3402)
Comune.create(description: "Buonvicino", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 2540)
Comune.create(description: "Calopezzati", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 1206)
Comune.create(description: "Caloveto", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 1432)
Comune.create(description: "Campana", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 2643)
Comune.create(description: "Canna", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 869)
Comune.create(description: "Cariati", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 8289)
Comune.create(description: "Carolei", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 3543)
Comune.create(description: "Carpanzano", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 378)
Comune.create(description: "Casole Bruzio", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 2480)
Comune.create(description: "Cassano Allo Ionio", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 17565)
Comune.create(description: "Castiglione Cosentino", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 3070)
Comune.create(description: "Castrolibero", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 10042)
Comune.create(description: "Castroregio", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 480)
Comune.create(description: "Castrovillari", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 22389)
Comune.create(description: "Celico", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 3185)
Comune.create(description: "Cellara", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 526)
Comune.create(description: "Cerchiara Di Calabria", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 2942)
Comune.create(description: "Cerisano", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 3238)
Comune.create(description: "Cervicati", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 1018)
Comune.create(description: "Cerzeto", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 1467)
Comune.create(description: "Cetraro", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 10333)
Comune.create(description: "Civita", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 1125)
Comune.create(description: "Cleto", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 1389)
Comune.create(description: "Colosimi", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 1416)
Comune.create(description: "Corigliano Calabro", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 38241)
Comune.create(description: "Cosenza", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 72998)
Comune.create(description: "Cropalati", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 1263)
Comune.create(description: "Crosia", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 8671)
Comune.create(description: "Diamante", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 5091)
Comune.create(description: "Dipignano", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 4192)
Comune.create(description: "Domanico", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 926)
Comune.create(description: "Fagnano Castello", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 4198)
Comune.create(description: "Falconara Albanese", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 1416)
Comune.create(description: "Figline Vegliaturo", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 1026)
Comune.create(description: "Firmo", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 2460)
Comune.create(description: "Fiumefreddo Bruzio", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 3363)
Comune.create(description: "Francavilla Marittima", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 3088)
Comune.create(description: "Frascineto", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 2503)
Comune.create(description: "Fuscaldo", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 8323)
Comune.create(description: "Grimaldi", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 1870)
Comune.create(description: "Grisolia", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 2395)
Comune.create(description: "Guardia Piemontese", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 1525)
Comune.create(description: "Lago", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 3096)
Comune.create(description: "Laino Borgo", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 2275)
Comune.create(description: "Laino Castello", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 901)
Comune.create(description: "Lappano", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 1000)
Comune.create(description: "Lattarico", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 4184)
Comune.create(description: "Longobardi", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 2340)
Comune.create(description: "Longobucco", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 4351)
Comune.create(description: "Lungro", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 3145)
Comune.create(description: "Luzzi", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 10455)
Comune.create(description: "Malito", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 896)
Comune.create(description: "Malvito", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 2078)
Comune.create(description: "Mandatoriccio", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 3045)
Comune.create(description: "Mangone", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 1730)
Comune.create(description: "Marano Marchesato", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 2561)
Comune.create(description: "Marano Principato", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 2337)
Comune.create(description: "Marzi", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 1018)
Comune.create(description: "Mendicino", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 8084)
Comune.create(description: "Mongrassano", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 1764)
Comune.create(description: "Montalto Uffugo", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 17382)
Comune.create(description: "Montegiordano", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 2144)
Comune.create(description: "Morano Calabro", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 4966)
Comune.create(description: "Mormanno", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 3729)
Comune.create(description: "Mottafollone", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 1516)
Comune.create(description: "Nocara", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 556)
Comune.create(description: "Oriolo", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 2964)
Comune.create(description: "Orsomarso", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 1498)
Comune.create(description: "Paludi", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 1929)
Comune.create(description: "Panettieri", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 375)
Comune.create(description: "Paola", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 17195)
Comune.create(description: "Papasidero", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 1019)
Comune.create(description: "Parenti", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 2328)
Comune.create(description: "Paterno Calabro", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 1383)
Comune.create(description: "Pedace", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 2136)
Comune.create(description: "Pedivigliano", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 983)
Comune.create(description: "Piane Crati", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 1397)
Comune.create(description: "Pietrafitta", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 1479)
Comune.create(description: "Pietrapaola", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 1238)
Comune.create(description: "Plataci", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 920)
Comune.create(description: "Praia A Mare", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 6282)
Comune.create(description: "Rende", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 34421)
Comune.create(description: "Rocca Imperiale", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 3352)
Comune.create(description: "Roggiano Gravina", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 7739)
Comune.create(description: "Rogliano", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 5892)
Comune.create(description: "Rose", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 4413)
Comune.create(description: "Roseto Capo Spulico", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 1759)
Comune.create(description: "Rossano", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 35835)
Comune.create(description: "Rota Greca", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 1293)
Comune.create(description: "Rovito", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 2817)
Comune.create(description: "San Basile", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 1285)
Comune.create(description: "San Benedetto Ullano", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 1649)
Comune.create(description: "San Cosmo Albanese", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 702)
Comune.create(description: "San Demetrio Corone", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 3944)
Comune.create(description: "San Donato Di Ninea", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 1778)
Comune.create(description: "San Fili", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 2568)
Comune.create(description: "San Giorgio Albanese", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 1709)
Comune.create(description: "San Giovanni In Fiore", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 18566)
Comune.create(description: "San Lorenzo Bellizzi", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 904)
Comune.create(description: "San Lorenzo Del Vallo", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 3428)
Comune.create(description: "San Lucido", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 5906)
Comune.create(description: "San Marco Argentano", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 7635)
Comune.create(description: "San Martino Di Finita", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 1294)
Comune.create(description: "San Nicola Arcella", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 1393)
Comune.create(description: "San Pietro In Amantea", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 611)
Comune.create(description: "San Pietro In Guarano", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 3712)
Comune.create(description: "San Sosti", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 2299)
Comune.create(description: "San Vincenzo La Costa", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 2034)
Comune.create(description: "Sangineto", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 1410)
Comune.create(description: "Santa Caterina Albanese", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 1383)
Comune.create(description: "Santa Domenica Talao", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 1314)
Comune.create(description: "Santa Maria Del Cedro", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 4831)
Comune.create(description: "Santo Stefano Di Rogliano", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 1412)
Comune.create(description: "Saracena", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 4309)
Comune.create(description: "Scala Coeli", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 1393)
Comune.create(description: "Scalea", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 10027)
Comune.create(description: "Scigliano", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 1601)
Comune.create(description: "Serra Pedace", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 1045)
Comune.create(description: "Spezzano Albanese", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 7036)
Comune.create(description: "Spezzano Della Sila", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 4851)
Comune.create(description: "Spezzano Piccolo", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 2034)
Comune.create(description: "Tarsia", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 2383)
Comune.create(description: "Terranova Da Sibari", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 5216)
Comune.create(description: "Terravecchia", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 1135)
Comune.create(description: "Torano Castello", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 4915)
Comune.create(description: "Tortora", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 5823)
Comune.create(description: "Trebisacce", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 9023)
Comune.create(description: "Trenta", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 2695)
Comune.create(description: "Vaccarizzo Albanese", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 1326)
Comune.create(description: "Verbicaro", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 3507)
Comune.create(description: "Villapiana", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 4752)
Comune.create(description: "Zumpano", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 1860)
Comune.create(description: "Maiera'", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 1333)
Comune.create(description: "Santa Sofia D'Epiro", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 3131)
Comune.create(description: "Sant'Agata Di Esaro", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 2223)
Comune.create(description: "Serra D'Aiello", provincia_id: 22, regione_id: 7, country_id: 1, continent_id: 1 , population: 878)
