continent = Continent.find_by(description: 'Africa')
state = Country.find_by(description: 'South Africa')
region = Region.create(description: "Eastern Cape", country: state, continent: continent, geoname_id: 1085593)
province = region.provinces.create(description: "Alfred Nzo District Municipality", country: state, continent: continent,  geoname_id: 8347351, population: 479390)
province.comunes.create(description: "Matatiele", region: region, country: state, continent: continent, geoname_id: 8347483, population: 258758)
province.comunes.create(description: "Mbizana", region: region, country: state, continent: continent, geoname_id: 8347606, population: 279739)
province.comunes.create(description: "Ntabankulu", region: region, country: state, continent: continent, geoname_id: 8347622, population: 141358)
province.comunes.create(description: "Umzimvubu", region: region, country: state, continent: continent, geoname_id: 8347534, population: 220631)
province = region.provinces.create(description: "Amathole District Municipality", country: state, continent: continent,  geoname_id: 8347342, population: 940441)
province.comunes.create(description: "Amahlathi", region: region, country: state, continent: continent, geoname_id: 8347618, population: 112735)
province.comunes.create(description: "Great Kei", region: region, country: state, continent: continent, geoname_id: 8347402, population: 33382)
province.comunes.create(description: "Mbhashe", region: region, country: state, continent: continent, geoname_id: 8347480, population: 262008)
province.comunes.create(description: "Mnquma", region: region, country: state, continent: continent, geoname_id: 8347531, population: 297663)
province.comunes.create(description: "Ngqushwa", region: region, country: state, continent: continent, geoname_id: 8347509, population: 83086)
province.comunes.create(description: "Nkonkobe", region: region, country: state, continent: continent, geoname_id: 8347609, population: 130100)
province.comunes.create(description: "Nxuba", region: region, country: state, continent: continent, geoname_id: 8347420, population: 21467)
province = region.provinces.create(description: "Buffalo City Metropolitan Municipality", country: state, continent: continent,  geoname_id: 8347340, population: 755200)
province.comunes.create(description: "Buffalo City", region: region, country: state, continent: continent, geoname_id: 8347472, population: 724312)
province = region.provinces.create(description: "Cacadu District Municipality", country: state, continent: continent,  geoname_id: 8347341, population: 363496)
province.comunes.create(description: "Baviaans", region: region, country: state, continent: continent, geoname_id: 8347615, population: 13950)
province.comunes.create(description: "Blue Crane Route", region: region, country: state, continent: continent, geoname_id: 8347503, population: 25573)
province.comunes.create(description: "Camdeboo", region: region, country: state, continent: continent, geoname_id: 8347550, population: 41758)
province.comunes.create(description: "Ikwezi", region: region, country: state, continent: continent, geoname_id: 8347619, population: 11523)
province.comunes.create(description: "Kou-Kamma", region: region, country: state, continent: continent, geoname_id: 8347577, population: 40780)
province.comunes.create(description: "Kouga", region: region, country: state, continent: continent, geoname_id: 8347575, population: 73274)
province.comunes.create(description: "Makana", region: region, country: state, continent: continent, geoname_id: 8347456, population: 70059)
province.comunes.create(description: "Ndlambe", region: region, country: state, continent: continent, geoname_id: 8347507, population: 46359)
province.comunes.create(description: "Sundays River Valley", region: region, country: state, continent: continent, geoname_id: 8347608, population: 34935)
province = region.provinces.create(description: "Chris Hani District Municipality", country: state, continent: continent,  geoname_id: 8347343, population: 798597)
province.comunes.create(description: "Emalahleni", region: region, country: state, continent: continent, geoname_id: 8347610, population: 125293)
province.comunes.create(description: "Engcobo", region: region, country: state, continent: continent, geoname_id: 8347421, population: 135979)
province.comunes.create(description: "Inkwanca", region: region, country: state, continent: continent, geoname_id: 8347543, population: 14283)
province.comunes.create(description: "Intsika Yethu", region: region, country: state, continent: continent, geoname_id: 8347510, population: 185342)
province.comunes.create(description: "Inxuba Yethemba", region: region, country: state, continent: continent, geoname_id: 8347443, population: 48399)
province.comunes.create(description: "Lukanji", region: region, country: state, continent: continent, geoname_id: 8347505, population: 208081)
province.comunes.create(description: "Sakhisizwe", region: region, country: state, continent: continent, geoname_id: 8347576, population: 53472)
province.comunes.create(description: "Tsolwana", region: region, country: state, continent: continent, geoname_id: 8347526, population: 27660)
province = region.provinces.create(description: "Nelson Mandela Bay Metropolitan Municipality", country: state, continent: continent,  geoname_id: 8347387, population: 1050930)
province.comunes.create(description: "Nelson Mandela Bay", region: region, country: state, continent: continent, geoname_id: 8347444, population: 1050930)
province = region.provinces.create(description: "OR Tambo District Municipality", country: state, continent: continent,  geoname_id: 8347358, population: 1862218)
province.comunes.create(description: "King Sabata Dalindyebo", region: region, country: state, continent: continent, geoname_id: 8347512, population: 444830)
province.comunes.create(description: "Mhlontlo", region: region, country: state, continent: continent, geoname_id: 8347462, population: 237138)
province.comunes.create(description: "Ngquza Hill", region: region, country: state, continent: continent, geoname_id: 8347557, population: 279795)
province.comunes.create(description: "Nyandeni", region: region, country: state, continent: continent, geoname_id: 8347407, population: 314273)
province.comunes.create(description: "Port St Johns", region: region, country: state, continent: continent, geoname_id: 8347598, population: 165084)
province = region.provinces.create(description: "Ukhahlamba District Municipality", country: state, continent: continent,  geoname_id: 8347357, population: 308365)
province.comunes.create(description: "Elundini", region: region, country: state, continent: continent, geoname_id: 8347479, population: 123636)
province.comunes.create(description: "Gariep", region: region, country: state, continent: continent, geoname_id: 8347453, population: 23708)
province.comunes.create(description: "Maletswai", region: region, country: state, continent: continent, geoname_id: 8347546, population: 42843)
province.comunes.create(description: "Senqu", region: region, country: state, continent: continent, geoname_id: 8347401, population: 118177)
region = Region.create(description: "Gauteng", country: state, continent: continent, geoname_id: 1085594)
province = region.provinces.create(description: "City of Johannesburg Metropolitan Municipality", country: state, continent: continent,  geoname_id: 8347354, population: 3888180)
province.comunes.create(description: "City of Johannesburg", region: region, country: state, continent: continent, geoname_id: 8347476, population: 3888180)
province = region.provinces.create(description: "City of Tshwane Metropolitan Municipality", country: state, continent: continent,  geoname_id: 8347355, population: 2499447)
province.comunes.create(description: "City of Tshwane", region: region, country: state, continent: continent, geoname_id: 8347478, population: 2499447)
province = region.provinces.create(description: "Ekurhuleni Metropolitan Municipality", country: state, continent: continent,  geoname_id: 8347353, population: 2724229)
province.comunes.create(description: "Ekurhuleni", region: region, country: state, continent: continent, geoname_id: 8347481, population: 2724229)
province = region.provinces.create(description: "Sedibeng District Municipality", country: state, continent: continent,  geoname_id: 8347377, population: 800819)
province.comunes.create(description: "Emfuleni", region: region, country: state, continent: continent, geoname_id: 8347474, population: 650867)
province.comunes.create(description: "Lesedi", region: region, country: state, continent: continent, geoname_id: 8347405, population: 66507)
province.comunes.create(description: "Midvaal", region: region, country: state, continent: continent, geoname_id: 8347533, population: 83445)
province = region.provinces.create(description: "West Rand District Municipality", country: state, continent: continent,  geoname_id: 8347381, population: 754903)
province.comunes.create(description: "Merafong City", region: region, country: state, continent: continent, geoname_id: 8347459, population: 215865)
province.comunes.create(description: "Mogale City", region: region, country: state, continent: continent, geoname_id: 8347473, population: 319641)
province.comunes.create(description: "Randfontein", region: region, country: state, continent: continent, geoname_id: 8347593, population: 117261)
province.comunes.create(description: "Westonaria", region: region, country: state, continent: continent, geoname_id: 8347560, population: 99218)
region = Region.create(description: "KwaZulu-Natal", country: state, continent: continent, geoname_id: 972062)
province = region.provinces.create(description: "Amajuba District Municipality", country: state, continent: continent,  geoname_id: 8347345, population: 442266)
province.comunes.create(description: "Dannhauser", region: region, country: state, continent: continent, geoname_id: 8347579, population: 91366)
province.comunes.create(description: "Emadlangeni", region: region, country: state, continent: continent, geoname_id: 8347601, population: 23263)
province.comunes.create(description: "Newcastle", region: region, country: state, continent: continent, geoname_id: 8347426, population: 327637)
province = region.provinces.create(description: "Sisonke District Municipality", country: state, continent: continent,  geoname_id: 8347378, population: 500082)
province.comunes.create(description: "Greater Kokstad", region: region, country: state, continent: continent, geoname_id: 8347561, population: 46724)
province.comunes.create(description: "Ingwe", region: region, country: state, continent: continent, geoname_id: 8347485, population: 114116)
province.comunes.create(description: "Kwa Sani", region: region, country: state, continent: continent, geoname_id: 8347597, population: 14281)
province.comunes.create(description: "Ubuhlebezwe", region: region, country: state, continent: continent, geoname_id: 8347411, population: 80905)
province.comunes.create(description: "Umzimkhulu", region: region, country: state, continent: continent, geoname_id: 8347518, population: 243242)
province = region.provinces.create(description: "Ugu District Municipality", country: state, continent: continent,  geoname_id: 8347363, population: 709918)
province.comunes.create(description: "Ezingoleni", region: region, country: state, continent: continent, geoname_id: 8347520, population: 56369)
province.comunes.create(description: "Hibiscus Coast", region: region, country: state, continent: continent, geoname_id: 8347570, population: 224281)
province.comunes.create(description: "UMuziwabantu", region: region, country: state, continent: continent, geoname_id: 8347627, population: 104527)
province.comunes.create(description: "Umdoni", region: region, country: state, continent: continent, geoname_id: 8347430, population: 74437)
province.comunes.create(description: "Umzumbe", region: region, country: state, continent: continent, geoname_id: 8347582, population: 176287)
province.comunes.create(description: "Vulamehlo", region: region, country: state, continent: continent, geoname_id: 8347489, population: 74017)
province = region.provinces.create(description: "Zululand District Municipality", country: state, continent: continent,  geoname_id: 8347367, population: 902890)
province.comunes.create(description: "Abaqulusi", region: region, country: state, continent: continent, geoname_id: 8347586, population: 247628)
province.comunes.create(description: "Nongoma", region: region, country: state, continent: continent, geoname_id: 8347417, population: 244501)
province.comunes.create(description: "UPhongolo", region: region, country: state, continent: continent, geoname_id: 8347431, population: 137756)
province.comunes.create(description: "Ulundi", region: region, country: state, continent: continent, geoname_id: 8347563, population: 197908)
province.comunes.create(description: "eDumbe", region: region, country: state, continent: continent, geoname_id: 8347490, population: 75096)
province = region.provinces.create(description: "eThekwini Metropolitan Municipality", country: state, continent: continent,  geoname_id: 8299474, population: 3442361)
province.comunes.create(description: "Ethekwini", region: region, country: state, continent: continent, geoname_id: 8347491, population: 3468086)
province = region.provinces.create(description: "iLembe District Municipality", country: state, continent: continent,  geoname_id: 8347369, population: 528198)
province.comunes.create(description: "KwaDukuza", region: region, country: state, continent: continent, geoname_id: 8347432, population: 162055)
province.comunes.create(description: "Mandeni", region: region, country: state, continent: continent, geoname_id: 8347492, population: 122665)
province.comunes.create(description: "Maphumulo", region: region, country: state, continent: continent, geoname_id: 8347414, population: 109157)
province.comunes.create(description: "Ndwedwe", region: region, country: state, continent: continent, geoname_id: 8347587, population: 134322)
province = region.provinces.create(description: "uMgungundlovu District Municipality", country: state, continent: continent,  geoname_id: 8347364, population: 1017763)
province.comunes.create(description: "Impendle", region: region, country: state, continent: continent, geoname_id: 8347625, population: 39401)
province.comunes.create(description: "Mkhambathini", region: region, country: state, continent: continent, geoname_id: 8347522, population: 46570)
province.comunes.create(description: "Mooi Mpofana", region: region, country: state, continent: continent, geoname_id: 8347562, population: 31518)
province.comunes.create(description: "Richmond", region: region, country: state, continent: continent, geoname_id: 8347569, population: 56772)
province.comunes.create(description: "The Msunduzi", region: region, country: state, continent: continent, geoname_id: 8347470, population: 616730)
province.comunes.create(description: "uMngeni", region: region, country: state, continent: continent, geoname_id: 8347600, population: 84781)
province.comunes.create(description: "uMshwathi", region: region, country: state, continent: continent, geoname_id: 8347487, population: 113054)
province = region.provinces.create(description: "uMkhanyakude District Municipality", country: state, continent: continent,  geoname_id: 8347388, population: 625846)
province.comunes.create(description: "Hlabisa", region: region, country: state, continent: continent, geoname_id: 8347418, population: 150557)
province.comunes.create(description: "Jozini", region: region, country: state, continent: continent, geoname_id: 8347448, population: 207250)
province.comunes.create(description: "Mtubatuba", region: region, country: state, continent: continent, geoname_id: 8347565, population: 46596)
province.comunes.create(description: "The Big 5 False Bay", region: region, country: state, continent: continent, geoname_id: 8347590, population: 34991)
province.comunes.create(description: "Umhlabuyalingana", region: region, country: state, continent: continent, geoname_id: 8347494, population: 163694)
province = region.provinces.create(description: "uMzinyathi District Municipality", country: state, continent: continent,  geoname_id: 8347366, population: 510838)
province.comunes.create(description: "Endumeni", region: region, country: state, continent: continent, geoname_id: 8347558, population: 54447)
province.comunes.create(description: "Msinga", region: region, country: state, continent: continent, geoname_id: 8347584, population: 161894)
province.comunes.create(description: "Nqutu", region: region, country: state, continent: continent, geoname_id: 8347429, population: 164887)
province.comunes.create(description: "Umvoti", region: region, country: state, continent: continent, geoname_id: 8347412, population: 114509)
province = region.provinces.create(description: "uThukela District Municipality", country: state, continent: continent,  geoname_id: 8347365, population: 714908)
province.comunes.create(description: "Emnambithi/Ladysmith", region: region, country: state, continent: continent, geoname_id: 8347484, population: 236748)
province.comunes.create(description: "Imbabazane", region: region, country: state, continent: continent, geoname_id: 8347517, population: 140745)
province.comunes.create(description: "Indaka", region: region, country: state, continent: continent, geoname_id: 8347535, population: 101557)
province.comunes.create(description: "Okhahlamba", region: region, country: state, continent: continent, geoname_id: 8347621, population: 151441)
province.comunes.create(description: "Umtshezi", region: region, country: state, continent: continent, geoname_id: 8347580, population: 83906)
province = region.provinces.create(description: "uThungulu District Municipality", country: state, continent: continent,  geoname_id: 8347368, population: 907519)
province.comunes.create(description: "Mfolozi", region: region, country: state, continent: continent, geoname_id: 8347493, population: 118081)
province.comunes.create(description: "Mthonjaneni", region: region, country: state, continent: continent, geoname_id: 8347564, population: 47010)
province.comunes.create(description: "Nkandla", region: region, country: state, continent: continent, geoname_id: 8347571, population: 127451)
province.comunes.create(description: "Ntambanana", region: region, country: state, continent: continent, geoname_id: 8347589, population: 94190)
province.comunes.create(description: "uMhlathuze", region: region, country: state, continent: continent, geoname_id: 8347433, population: 332156)
province.comunes.create(description: "uMlalazi", region: region, country: state, continent: continent, geoname_id: 8347415, population: 175372)
region = Region.create(description: "Limpopo", country: state, continent: continent, geoname_id: 1085597)
province = region.provinces.create(description: "Capricorn District Municipality", country: state, continent: continent,  geoname_id: 8347346, population: 1261463)
province.comunes.create(description: "Aganang", region: region, country: state, continent: continent, geoname_id: 8347594, population: 145454)
province.comunes.create(description: "Blouberg", region: region, country: state, continent: continent, geoname_id: 8347482, population: 194119)
province.comunes.create(description: "Lepele-Nkumpi", region: region, country: state, continent: continent, geoname_id: 8347516, population: 241414)
province.comunes.create(description: "Molemole", region: region, country: state, continent: continent, geoname_id: 8347603, population: 100408)
province.comunes.create(description: "Polokwane", region: region, country: state, continent: continent, geoname_id: 8347623, population: 561772)
province = region.provinces.create(description: "Mopani District Municipality", country: state, continent: continent,  geoname_id: 8347373, population: 1068568)
province.comunes.create(description: "Ba-Phalaborwa", region: region, country: state, continent: continent, geoname_id: 8347413, population: 127308)
province.comunes.create(description: "Greater Giyani", region: region, country: state, continent: continent, geoname_id: 8347488, population: 247657)
province.comunes.create(description: "Greater Letaba", region: region, country: state, continent: continent, geoname_id: 8347602, population: 247739)
province.comunes.create(description: "Greater Tzaneen", region: region, country: state, continent: continent, geoname_id: 8347581, population: 349087)
province.comunes.create(description: "Maruleng", region: region, country: state, continent: continent, geoname_id: 8347521, population: 95779)
province = region.provinces.create(description: "Sekhukhune District Municipality", country: state, continent: continent,  geoname_id: 8347380, population: 1090424)
province.comunes.create(description: "Elias Motsoaledi", region: region, country: state, continent: continent, geoname_id: 8347596, population: 247488)
province.comunes.create(description: "Ephraim Mogale", region: region, country: state, continent: continent, geoname_id: 8347555, population: 124510)
province.comunes.create(description: "Fetakgomo", region: region, country: state, continent: continent, geoname_id: 8347410, population: 112232)
province.comunes.create(description: "Greater Tubatse", region: region, country: state, continent: continent, geoname_id: 8347519, population: 343468)
province.comunes.create(description: "Makhuduthamaga", region: region, country: state, continent: continent, geoname_id: 8347605, population: 262726)
province = region.provinces.create(description: "Vhembe District Municipality", country: state, continent: continent,  geoname_id: 8347374, population: 1240035)
province.comunes.create(description: "Makhado", region: region, country: state, continent: continent, geoname_id: 8347624, population: 471805)
province.comunes.create(description: "Musina", region: region, country: state, continent: continent, geoname_id: 8347556, population: 57195)
province.comunes.create(description: "Mutale", region: region, country: state, continent: continent, geoname_id: 8347427, population: 108215)
province.comunes.create(description: "Thulamela", region: region, country: state, continent: continent, geoname_id: 8347583, population: 602819)
province = region.provinces.create(description: "Waterberg District Municipality", country: state, continent: continent,  geoname_id: 8347375, population: 596092)
province.comunes.create(description: "Bela-Bela", region: region, country: state, continent: continent, geoname_id: 8347511, population: 55844)
province.comunes.create(description: "Lephalale", region: region, country: state, continent: continent, geoname_id: 8347528, population: 80141)
province.comunes.create(description: "Modimolle", region: region, country: state, continent: continent, geoname_id: 8347460, population: 52602)
province.comunes.create(description: "Mogalakwena", region: region, country: state, continent: continent, geoname_id: 8347612, population: 330649)
province.comunes.create(description: "Mookgopong", region: region, country: state, continent: continent, geoname_id: 8347406, population: 16818)
province.comunes.create(description: "Thabazimbi", region: region, country: state, continent: continent, geoname_id: 8347447, population: 60039)
region = Region.create(description: "Mpumalanga", country: state, continent: continent, geoname_id: 1085595)
province = region.provinces.create(description: "Eastvaal District Municipality", country: state, continent: continent,  geoname_id: 8347371, population: 1043194)
province.comunes.create(description: "Albert Luthuli", region: region, country: state, continent: continent, geoname_id: 8347486, population: 194083)
province.comunes.create(description: "Dipaleseng", region: region, country: state, continent: continent, geoname_id: 8347613, population: 37873)
province.comunes.create(description: "Govan Mbeki", region: region, country: state, continent: continent, geoname_id: 8347422, population: 268954)
province.comunes.create(description: "Lekwa", region: region, country: state, continent: continent, geoname_id: 8347515, population: 91136)
province.comunes.create(description: "Mkhondo", region: region, country: state, continent: continent, geoname_id: 8347585, population: 106452)
province.comunes.create(description: "Msukaligwa", region: region, country: state, continent: continent, geoname_id: 8347599, population: 126268)
province.comunes.create(description: "Pixley Ka Seme", region: region, country: state, continent: continent, geoname_id: 8347626, population: 65932)
province = region.provinces.create(description: "Ehlanzeni District", country: state, continent: continent,  geoname_id: 8299316, population: 0)
province.comunes.create(description: "Bushbuckridge", region: region, country: state, continent: continent, geoname_id: 8347523, population: 509970)
province.comunes.create(description: "Mbombela", region: region, country: state, continent: continent, geoname_id: 8347428, population: 527203)
province.comunes.create(description: "Nkomazi", region: region, country: state, continent: continent, geoname_id: 8347416, population: 338095)
province.comunes.create(description: "Thaba Chweu", region: region, country: state, continent: continent, geoname_id: 8347559, population: 87545)
province.comunes.create(description: "Umjindi", region: region, country: state, continent: continent, geoname_id: 8347588, population: 60475)
province = region.provinces.create(description: "Nkangala District Municipality", country: state, continent: continent,  geoname_id: 8347372, population: 1226500)
province.comunes.create(description: "Dr JS Moroka", region: region, country: state, continent: continent, geoname_id: 8347614, population: 246969)
province.comunes.create(description: "Emakhazeni", region: region, country: state, continent: continent, geoname_id: 8347506, population: 32840)
province.comunes.create(description: "Emalahleni", region: region, country: state, continent: continent, geoname_id: 8347595, population: 435217)
province.comunes.create(description: "Steve Tshwete", region: region, country: state, continent: continent, geoname_id: 8347604, population: 182503)
province.comunes.create(description: "Thembisile", region: region, country: state, continent: continent, geoname_id: 8347513, population: 278517)
province.comunes.create(description: "Victor Khanye", region: region, country: state, continent: continent, geoname_id: 8347554, population: 50455)
region = Region.create(description: "Northern Cape", country: state, continent: continent, geoname_id: 1085596)
province = region.provinces.create(description: "Frances Baard District Municipality", country: state, continent: continent,  geoname_id: 8347385, population: 353200)
province.comunes.create(description: "Dikgatlong", region: region, country: state, continent: continent, geoname_id: 8347502, population: 40752)
province.comunes.create(description: "Magareng", region: region, country: state, continent: continent, geoname_id: 8347620, population: 20433)
province.comunes.create(description: "Phokwane", region: region, country: state, continent: continent, geoname_id: 8347451, population: 46409)
province.comunes.create(description: "Sol Plaatjie", region: region, country: state, continent: continent, geoname_id: 8347551, population: 243018)
province = region.provinces.create(description: "John Taolo Gaetsewe District Municipality", country: state, continent: continent,  geoname_id: 8347379, population: 173454)
province.comunes.create(description: "Ga-Segonyana", region: region, country: state, continent: continent, geoname_id: 8347409, population: 69791)
province.comunes.create(description: "Gamagara", region: region, country: state, continent: continent, geoname_id: 8347434, population: 28054)
province.comunes.create(description: "Joe Morolong", region: region, country: state, continent: continent, geoname_id: 8347408, population: 70012)
province = region.provinces.create(description: "Namakwa District Municipality", country: state, continent: continent,  geoname_id: 8347382, population: 126494)
province.comunes.create(description: "Hantam", region: region, country: state, continent: continent, geoname_id: 8347592, population: 21234)
province.comunes.create(description: "Kamiesberg", region: region, country: state, continent: continent, geoname_id: 8347449, population: 12117)
province.comunes.create(description: "Karoo Hoogland", region: region, country: state, continent: continent, geoname_id: 8347633, population: 10420)
province.comunes.create(description: "Khâi-Ma", region: region, country: state, continent: continent, geoname_id: 8347566, population: 12571)
province.comunes.create(description: "Nama Khoi", region: region, country: state, continent: continent, geoname_id: 8347495, population: 54644)
province.comunes.create(description: "Richtersveld", region: region, country: state, continent: continent, geoname_id: 8347435, population: 14613)
province = region.provinces.create(description: "Pixley ka Seme District Municipality", country: state, continent: continent,  geoname_id: 8347383, population: 166849)
province.comunes.create(description: "Emthanjeni", region: region, country: state, continent: continent, geoname_id: 8347540, population: 38228)
province.comunes.create(description: "Kareeberg", region: region, country: state, continent: continent, geoname_id: 8347630, population: 9866)
province.comunes.create(description: "Renosterberg", region: region, country: state, continent: continent, geoname_id: 8347466, population: 9185)
province.comunes.create(description: "Siyancuma", region: region, country: state, continent: continent, geoname_id: 8347574, population: 35970)
province.comunes.create(description: "Siyathemba", region: region, country: state, continent: continent, geoname_id: 8347572, population: 20120)
province.comunes.create(description: "Thembelihle", region: region, country: state, continent: continent, geoname_id: 8347568, population: 13218)
province.comunes.create(description: "Ubuntu", region: region, country: state, continent: continent, geoname_id: 8347549, population: 16153)
province.comunes.create(description: "Umsobomvu", region: region, country: state, continent: continent, geoname_id: 8347504, population: 21992)
province = region.provinces.create(description: "Siyanda District Municipality", country: state, continent: continent,  geoname_id: 8347384, population: 236783)
province.comunes.create(description: "!Kheis", region: region, country: state, continent: continent, geoname_id: 8347616, population: 18920)
province.comunes.create(description: "//Khara Hais", region: region, country: state, continent: continent, geoname_id: 8347537, population: 100920)
province.comunes.create(description: "Kai !Garib", region: region, country: state, continent: continent, geoname_id: 8347499, population: 56501)
province.comunes.create(description: "Kgatelopele", region: region, country: state, continent: continent, geoname_id: 8347607, population: 21498)
province.comunes.create(description: "Mier", region: region, country: state, continent: continent, geoname_id: 8347440, population: 7337)
province.comunes.create(description: "Tsantsabane", region: region, country: state, continent: continent, geoname_id: 8347635, population: 28005)
region = Region.create(description: "Orange Free State", country: state, continent: continent, geoname_id: 967573)
province = region.provinces.create(description: "Fezile Dabi District Municipality", country: state, continent: continent,  geoname_id: 8347362, population: 474089)
province.comunes.create(description: "Mafube", region: region, country: state, continent: continent, geoname_id: 8347461, population: 53722)
province.comunes.create(description: "Metsimaholo", region: region, country: state, continent: continent, geoname_id: 8347403, population: 154658)
province.comunes.create(description: "Moqhaka", region: region, country: state, continent: continent, geoname_id: 8347424, population: 170522)
province.comunes.create(description: "Ngwathe", region: region, country: state, continent: continent, geoname_id: 8347529, population: 95187)
province = region.provinces.create(description: "Lejweleputswa District Municipality", country: state, continent: continent,  geoname_id: 8347360, population: 639651)
province.comunes.create(description: "Masilonyana", region: region, country: state, continent: continent, geoname_id: 8347446, population: 80094)
province.comunes.create(description: "Matjhabeng", region: region, country: state, continent: continent, geoname_id: 8347458, population: 405031)
province.comunes.create(description: "Nala", region: region, country: state, continent: continent, geoname_id: 8347468, population: 92586)
province.comunes.create(description: "Tokologo", region: region, country: state, continent: continent, geoname_id: 8347524, population: 21323)
province.comunes.create(description: "Tswelopele", region: region, country: state, continent: continent, geoname_id: 8347578, population: 40617)
province = region.provinces.create(description: "Mangaung Metropolitan Municipality", country: state, continent: continent,  geoname_id: 8347386, population: 752906)
province.comunes.create(description: "Mangaung", region: region, country: state, continent: continent, geoname_id: 8347445, population: 752906)
province = region.provinces.create(description: "Thabo Mofutsanyana District Municipality", country: state, continent: continent,  geoname_id: 8347361, population: 753344)
province.comunes.create(description: "Dihlabeng", region: region, country: state, continent: continent, geoname_id: 8347532, population: 108449)
province.comunes.create(description: "Maluti a Phofung", region: region, country: state, continent: continent, geoname_id: 8347463, population: 385413)
province.comunes.create(description: "Mantsopa", region: region, country: state, continent: continent, geoname_id: 8347611, population: 59028)
province.comunes.create(description: "Nketoana", region: region, country: state, continent: continent, geoname_id: 8347404, population: 62367)
province.comunes.create(description: "Phumelela", region: region, country: state, continent: continent, geoname_id: 8347514, population: 35090)
province.comunes.create(description: "Setsoto", region: region, country: state, continent: continent, geoname_id: 8347425, population: 102826)
province = region.provinces.create(description: "Xhariep District Municipality", country: state, continent: continent,  geoname_id: 8347359, population: 153069)
province.comunes.create(description: "Kopanong", region: region, country: state, continent: continent, geoname_id: 8347553, population: 49422)
province.comunes.create(description: "Letsemeng", region: region, country: state, continent: continent, geoname_id: 8347471, population: 36337)
province.comunes.create(description: "Mohokare", region: region, country: state, continent: continent, geoname_id: 8347545, population: 41867)
province.comunes.create(description: "Naledi", region: region, country: state, continent: continent, geoname_id: 8347457, population: 25442)
region = Region.create(description: "Province of North West", country: state, continent: continent, geoname_id: 1085598)
province = region.provinces.create(description: "Bojanala Platinum", country: state, continent: continent,  geoname_id: 8347347, population: 1268618)
province.comunes.create(description: "Kgetlengrivier", region: region, country: state, continent: continent, geoname_id: 8347632, population: 37806)
province.comunes.create(description: "Local Municipality of Madibeng", region: region, country: state, continent: continent, geoname_id: 8347530, population: 371197)
province.comunes.create(description: "Moretele", region: region, country: state, continent: continent, geoname_id: 8347477, population: 182414)
province.comunes.create(description: "Moses Kotane", region: region, country: state, continent: continent, geoname_id: 8347508, population: 227426)
province.comunes.create(description: "Rustenburg", region: region, country: state, continent: continent, geoname_id: 8347547, population: 449776)
province = region.provinces.create(description: "Dr Kenneth Kaunda District Municipality", country: state, continent: continent,  geoname_id: 8347350, population: 634127)
province.comunes.create(description: "City of Matlosana", region: region, country: state, continent: continent, geoname_id: 8347544, population: 385782)
province.comunes.create(description: "Maquassi Hills", region: region, country: state, continent: continent, geoname_id: 8347454, population: 87465)
province.comunes.create(description: "Tlokwe City Council", region: region, country: state, continent: continent, geoname_id: 8347527, population: 124351)
province.comunes.create(description: "Ventersdorp", region: region, country: state, continent: continent, geoname_id: 8347423, population: 36528)
province = region.provinces.create(description: "Dr Ruth Segomotsi Mompati District Municipality", country: state, continent: continent,  geoname_id: 8347348, population: 354554)
province.comunes.create(description: "Greater Taung", region: region, country: state, continent: continent, geoname_id: 8347541, population: 144817)
province.comunes.create(description: "Kagisano/Molopo", region: region, country: state, continent: continent, geoname_id: 8347464, population: 82462)
province.comunes.create(description: "Lekwa-Teemane", region: region, country: state, continent: continent, geoname_id: 8347452, population: 32809)
province.comunes.create(description: "Mamusa", region: region, country: state, continent: continent, geoname_id: 8347552, population: 36533)
province.comunes.create(description: "Naledi", region: region, country: state, continent: continent, geoname_id: 8347469, population: 57934)
province = region.provinces.create(description: "Ngaka Modiri Molema District Municipality", country: state, continent: continent,  geoname_id: 8347376, population: 798783)
province.comunes.create(description: "Ditsobotla", region: region, country: state, continent: continent, geoname_id: 8347455, population: 200141)
province.comunes.create(description: "Mafikeng", region: region, country: state, continent: continent, geoname_id: 8347542, population: 290229)
province.comunes.create(description: "Ramotshere Moiloa", region: region, country: state, continent: continent, geoname_id: 8347467, population: 129304)
province.comunes.create(description: "Ratlou", region: region, country: state, continent: continent, geoname_id: 8347442, population: 98104)
province.comunes.create(description: "Tswaing", region: region, country: state, continent: continent, geoname_id: 8347525, population: 81005)
region = Region.create(description: "Province of the Western Cape", country: state, continent: continent, geoname_id: 1085599)
province = region.provinces.create(description: "Cape Winelands District Municipality", country: state, continent: continent,  geoname_id: 8347344, population: 712413)
province.comunes.create(description: "Breede Valley", region: region, country: state, continent: continent, geoname_id: 8347628, population: 134271)
province.comunes.create(description: "Drakenstein", region: region, country: state, continent: continent, geoname_id: 8347497, population: 217089)
province.comunes.create(description: "Langeberg", region: region, country: state, continent: continent, geoname_id: 8347631, population: 80121)
province.comunes.create(description: "Stellenbosch", region: region, country: state, continent: continent, geoname_id: 8347475, population: 200524)
province.comunes.create(description: "Witzenberg", region: region, country: state, continent: continent, geoname_id: 8347439, population: 75148)
province = region.provinces.create(description: "Central Karoo District Municipality", country: state, continent: continent,  geoname_id: 8347352, population: 56230)
province.comunes.create(description: "Beaufort West", region: region, country: state, continent: continent, geoname_id: 8347538, population: 37090)
province.comunes.create(description: "Laingsburg", region: region, country: state, continent: continent, geoname_id: 8347441, population: 5156)
province.comunes.create(description: "Prince Albert", region: region, country: state, continent: continent, geoname_id: 8347501, population: 8374)
province = region.provinces.create(description: "City of Cape Town", country: state, continent: continent,  geoname_id: 8334583, population: 0)
province.comunes.create(description: "City of Cape Town", region: region, country: state, continent: continent, geoname_id: 8347437, population: 3497097)
province = region.provinces.create(description: "Eden District Municipality", country: state, continent: continent,  geoname_id: 8347349, population: 513307)
province.comunes.create(description: "Bitou", region: region, country: state, continent: continent, geoname_id: 8347567, population: 39002)
province.comunes.create(description: "George", region: region, country: state, continent: continent, geoname_id: 8347617, population: 136542)
province.comunes.create(description: "Hessequa", region: region, country: state, continent: continent, geoname_id: 8347500, population: 39081)
province.comunes.create(description: "Kannaland", region: region, country: state, continent: continent, geoname_id: 8347548, population: 24715)
province.comunes.create(description: "Knysna", region: region, country: state, continent: continent, geoname_id: 8347573, population: 65045)
province.comunes.create(description: "Mossel Bay", region: region, country: state, continent: continent, geoname_id: 8347539, population: 117838)
province.comunes.create(description: "Oudtshoorn", region: region, country: state, continent: continent, geoname_id: 8347634, population: 79606)
province = region.provinces.create(description: "Overberg District Municipality", country: state, continent: continent,  geoname_id: 8347370, population: 212787)
province.comunes.create(description: "Cape Agulhas", region: region, country: state, continent: continent, geoname_id: 8347536, population: 28444)
province.comunes.create(description: "Overstrand", region: region, country: state, continent: continent, geoname_id: 8347498, population: 74547)
province.comunes.create(description: "Swellendam", region: region, country: state, continent: continent, geoname_id: 8347629, population: 22833)
province.comunes.create(description: "Theewaterskloof", region: region, country: state, continent: continent, geoname_id: 8347438, population: 86719)
province = region.provinces.create(description: "West Coast District Municipality", country: state, continent: continent,  geoname_id: 8347356, population: 286751)
province.comunes.create(description: "Bergrivier", region: region, country: state, continent: continent, geoname_id: 8347450, population: 44741)
province.comunes.create(description: "Cederberg", region: region, country: state, continent: continent, geoname_id: 8347496, population: 31942)
province.comunes.create(description: "Matzikama", region: region, country: state, continent: continent, geoname_id: 8347436, population: 46362)
province.comunes.create(description: "Saldanha Bay", region: region, country: state, continent: continent, geoname_id: 8347591, population: 78982)
province.comunes.create(description: "Swartland", region: region, country: state, continent: continent, geoname_id: 8347419, population: 77524)
