continent = Continent.find_by(description: 'Europe')
state = Country.find_by(description: 'Bosnia and Herzegovina')
region = Region.create(description: "Brčko distrikt", country: state, continent: continent, geoname_id: 3294903)
province = region.provinces.create(description: "Anići", country: state, continent: continent,  geoname_id: 3255322, population: 0)
province = region.provinces.create(description: "Antići", country: state, continent: continent,  geoname_id: 3255355, population: 0)
province = region.provinces.create(description: "Antići", country: state, continent: continent,  geoname_id: 3255455, population: 0)
province = region.provinces.create(description: "Babići", country: state, continent: continent,  geoname_id: 3256126, population: 0)
province = region.provinces.create(description: "Bajići", country: state, continent: continent,  geoname_id: 3256140, population: 0)
province = region.provinces.create(description: "Baltići", country: state, continent: continent,  geoname_id: 3255441, population: 0)
province = region.provinces.create(description: "Bare", country: state, continent: continent,  geoname_id: 3256096, population: 0)
province = region.provinces.create(description: "Bijeli Potok", country: state, continent: continent,  geoname_id: 3211091, population: 0)
province = region.provinces.create(description: "Blagojevića Han", country: state, continent: continent,  geoname_id: 3255375, population: 0)
province = region.provinces.create(description: "Boderište", country: state, continent: continent,  geoname_id: 3203854, population: 0)
province = region.provinces.create(description: "Bojići", country: state, continent: continent,  geoname_id: 3256319, population: 0)
province = region.provinces.create(description: "Bosanska Bijela", country: state, continent: continent,  geoname_id: 3204212, population: 4)
province = region.provinces.create(description: "Bosutka", country: state, continent: continent,  geoname_id: 3255291, population: 0)
province = region.provinces.create(description: "Božići", country: state, continent: continent,  geoname_id: 3255409, population: 0)
province = region.provinces.create(description: "Bradonjići", country: state, continent: continent,  geoname_id: 3255324, population: 0)
province = region.provinces.create(description: "Brdo", country: state, continent: continent,  geoname_id: 3256317, population: 0)
province = region.provinces.create(description: "Brezik", country: state, continent: continent,  geoname_id: 3203405, population: 0)
province = region.provinces.create(description: "Brezje", country: state, continent: continent,  geoname_id: 3256128, population: 0)
province = region.provinces.create(description: "Brezovo Polje", country: state, continent: continent,  geoname_id: 3254467, population: 0)
province = region.provinces.create(description: "Brezovo Polje", country: state, continent: continent,  geoname_id: 3255110, population: 0)
province = region.provinces.create(description: "Brka", country: state, continent: continent,  geoname_id: 3203280, population: 2800)
province = region.provinces.create(description: "Brka", country: state, continent: continent,  geoname_id: 3256373, population: 0)
province = region.provinces.create(description: "Brod", country: state, continent: continent,  geoname_id: 3203244, population: 0)
province = region.provinces.create(description: "Brčko", country: state, continent: continent,  geoname_id: 3203521, population: 38968)
province.municipalities.create(description: "Ivići", region: region, country: state, continent: continent, geoname_id: 3256026, population: 0)
province.municipalities.create(description: "Novo Brčko", region: region, country: state, continent: continent, geoname_id: 3256015, population: 0)
province = region.provinces.create(description: "Brđani", country: state, continent: continent,  geoname_id: 3252848, population: 0)
province = region.provinces.create(description: "Budeči", country: state, continent: continent,  geoname_id: 3255042, population: 0)
province = region.provinces.create(description: "Bukovac", country: state, continent: continent,  geoname_id: 3203079, population: 0)
province = region.provinces.create(description: "Bukvik Donji", country: state, continent: continent,  geoname_id: 3203009, population: 0)
province = region.provinces.create(description: "Bukvik Gornji", country: state, continent: continent,  geoname_id: 3203008, population: 0)
province = region.provinces.create(description: "Bunarić", country: state, continent: continent,  geoname_id: 3256141, population: 0)
province = region.provinces.create(description: "Buzekara", country: state, continent: continent,  geoname_id: 3202943, population: 0)
province = region.provinces.create(description: "Cerik", country: state, continent: continent,  geoname_id: 3202723, population: 0)
province = region.provinces.create(description: "Cvijanovići", country: state, continent: continent,  geoname_id: 3252859, population: 0)
province = region.provinces.create(description: "Damjanovići", country: state, continent: continent,  geoname_id: 3255035, population: 0)
province = region.provinces.create(description: "Damjanovići", country: state, continent: continent,  geoname_id: 3255439, population: 0)
province = region.provinces.create(description: "Delina Ravan", country: state, continent: continent,  geoname_id: 3211495, population: 0)
province = region.provinces.create(description: "Dizdaruša", country: state, continent: continent,  geoname_id: 3202002, population: 0)
province = region.provinces.create(description: "Doljani", country: state, continent: continent,  geoname_id: 3255290, population: 0)
province = region.provinces.create(description: "Donja Grbavica", country: state, continent: continent,  geoname_id: 3256038, population: 0)
province = region.provinces.create(description: "Donja Mahala", country: state, continent: continent,  geoname_id: 3254484, population: 0)
province = region.provinces.create(description: "Donja Mahala", country: state, continent: continent,  geoname_id: 3254488, population: 0)
province = region.provinces.create(description: "Donje Boće", country: state, continent: continent,  geoname_id: 3203863, population: 0)
province = region.provinces.create(description: "Donji Rahić", country: state, continent: continent,  geoname_id: 3201411, population: 0)
province = region.provinces.create(description: "Donji Rašljani", country: state, continent: continent,  geoname_id: 3255103, population: 0)
province = region.provinces.create(description: "Donji Zovik", country: state, continent: continent,  geoname_id: 3201361, population: 0)
province = region.provinces.create(description: "Drenova", country: state, continent: continent,  geoname_id: 3256091, population: 0)
province = region.provinces.create(description: "Dubrave", country: state, continent: continent,  geoname_id: 3201064, population: 0)
province = region.provinces.create(description: "Dubravice Donje", country: state, continent: continent,  geoname_id: 3201053, population: 0)
province = region.provinces.create(description: "Dubravice Gornje", country: state, continent: continent,  geoname_id: 3201052, population: 0)
province = region.provinces.create(description: "Džigure", country: state, continent: continent,  geoname_id: 3255277, population: 0)
province = region.provinces.create(description: "Endek", country: state, continent: continent,  geoname_id: 3255727, population: 0)
province = region.provinces.create(description: "Gabela", country: state, continent: continent,  geoname_id: 3255359, population: 0)
province = region.provinces.create(description: "Gajevi", country: state, continent: continent,  geoname_id: 3200752, population: 0)
province = region.provinces.create(description: "Gajići", country: state, continent: continent,  geoname_id: 3255454, population: 0)
province = region.provinces.create(description: "Gavrilovići", country: state, continent: continent,  geoname_id: 3255368, population: 0)
province = region.provinces.create(description: "Gligorovići", country: state, continent: continent,  geoname_id: 3255048, population: 0)
province = region.provinces.create(description: "Gluhakovac", country: state, continent: continent,  geoname_id: 3256036, population: 0)
province = region.provinces.create(description: "Gorice", country: state, continent: continent,  geoname_id: 3200321, population: 0)
province = region.provinces.create(description: "Goričkići", country: state, continent: continent,  geoname_id: 3256349, population: 0)
province = region.provinces.create(description: "Gornja Grbavica", country: state, continent: continent,  geoname_id: 3256024, population: 0)
province = region.provinces.create(description: "Gornja Mahala", country: state, continent: continent,  geoname_id: 3211505, population: 0)
province = region.provinces.create(description: "Gornja Mahala", country: state, continent: continent,  geoname_id: 3252984, population: 0)
province = region.provinces.create(description: "Gornja Mahala", country: state, continent: continent,  geoname_id: 3254472, population: 0)
province = region.provinces.create(description: "Gornje Boće", country: state, continent: continent,  geoname_id: 3256320, population: 0)
province = region.provinces.create(description: "Gornji Islamovac", country: state, continent: continent,  geoname_id: 3211137, population: 0)
province = region.provinces.create(description: "Gornji Rahić", country: state, continent: continent,  geoname_id: 3199940, population: 4)
province = region.provinces.create(description: "Gornji Zovik", country: state, continent: continent,  geoname_id: 3199889, population: 0)
province = region.provinces.create(description: "Grbavica", country: state, continent: continent,  geoname_id: 3256040, population: 0)
province = region.provinces.create(description: "Gredice", country: state, continent: continent,  geoname_id: 3211492, population: 0)
province = region.provinces.create(description: "Grgići", country: state, continent: continent,  geoname_id: 3256133, population: 0)
province = region.provinces.create(description: "Grujići", country: state, continent: continent,  geoname_id: 3255407, population: 0)
province = region.provinces.create(description: "Guderevica", country: state, continent: continent,  geoname_id: 3253044, population: 0)
province = region.provinces.create(description: "Gutići", country: state, continent: continent,  geoname_id: 3256072, population: 0)
province = region.provinces.create(description: "Hrgovi Donji", country: state, continent: continent,  geoname_id: 3199271, population: 0)
province = region.provinces.create(description: "Janjići", country: state, continent: continent,  geoname_id: 3255541, population: 0)
province = region.provinces.create(description: "Joveljići", country: state, continent: continent,  geoname_id: 3255416, population: 0)
province = region.provinces.create(description: "Kablinovići", country: state, continent: continent,  geoname_id: 3254981, population: 0)
province = region.provinces.create(description: "Kalanac", country: state, continent: continent,  geoname_id: 3256023, population: 0)
province = region.provinces.create(description: "Kerepi", country: state, continent: continent,  geoname_id: 3210900, population: 0)
province = region.provinces.create(description: "Kojići", country: state, continent: continent,  geoname_id: 3255350, population: 0)
province = region.provinces.create(description: "Kolibe", country: state, continent: continent,  geoname_id: 3257334, population: 0)
province = region.provinces.create(description: "Kolonija", country: state, continent: continent,  geoname_id: 3256019, population: 0)
province = region.provinces.create(description: "Kraljevići", country: state, continent: continent,  geoname_id: 3255036, population: 0)
province = region.provinces.create(description: "Krbeta", country: state, continent: continent,  geoname_id: 3255437, population: 0)
province = region.provinces.create(description: "Krepšić", country: state, continent: continent,  geoname_id: 3197299, population: 0)
province = region.provinces.create(description: "Krpići", country: state, continent: continent,  geoname_id: 3255351, population: 0)
province = region.provinces.create(description: "Kurjakovići", country: state, continent: continent,  geoname_id: 3254338, population: 0)
province = region.provinces.create(description: "Laništa", country: state, continent: continent,  geoname_id: 3196775, population: 0)
province = region.provinces.create(description: "Lipovac", country: state, continent: continent,  geoname_id: 3252710, population: 0)
province = region.provinces.create(description: "Lugonjići", country: state, continent: continent,  geoname_id: 3255550, population: 0)
province = region.provinces.create(description: "Luići", country: state, continent: continent,  geoname_id: 3255408, population: 0)
province = region.provinces.create(description: "Lukavac", country: state, continent: continent,  geoname_id: 3211081, population: 0)
province = region.provinces.create(description: "Lukići", country: state, continent: continent,  geoname_id: 3256099, population: 0)
province = region.provinces.create(description: "Lućići", country: state, continent: continent,  geoname_id: 3256046, population: 0)
province = region.provinces.create(description: "Maholjaši", country: state, continent: continent,  geoname_id: 3256328, population: 0)
province = region.provinces.create(description: "Maksimovići", country: state, continent: continent,  geoname_id: 3255456, population: 0)
province = region.provinces.create(description: "Maljani", country: state, continent: continent,  geoname_id: 3255073, population: 0)
province = region.provinces.create(description: "Maoča", country: state, continent: continent,  geoname_id: 3195528, population: 4)
province = region.provinces.create(description: "Marići", country: state, continent: continent,  geoname_id: 3255319, population: 0)
province = region.provinces.create(description: "Maričani", country: state, continent: continent,  geoname_id: 3255293, population: 0)
province = region.provinces.create(description: "Markanovići", country: state, continent: continent,  geoname_id: 3256146, population: 0)
province = region.provinces.create(description: "Marković Polje", country: state, continent: continent,  geoname_id: 3211068, population: 0)
province = region.provinces.create(description: "Markovići", country: state, continent: continent,  geoname_id: 3255440, population: 0)
province = region.provinces.create(description: "Martinovići", country: state, continent: continent,  geoname_id: 3255733, population: 0)
province = region.provinces.create(description: "Mateljići", country: state, continent: continent,  geoname_id: 3256169, population: 0)
province = region.provinces.create(description: "Medići", country: state, continent: continent,  geoname_id: 3255371, population: 0)
province = region.provinces.create(description: "Mehukići", country: state, continent: continent,  geoname_id: 3252580, population: 0)
province = region.provinces.create(description: "Međaci", country: state, continent: continent,  geoname_id: 3252891, population: 0)
province = region.provinces.create(description: "Mijići", country: state, continent: continent,  geoname_id: 3255360, population: 0)
province = region.provinces.create(description: "Mitrovići", country: state, continent: continent,  geoname_id: 3255029, population: 0)
province = region.provinces.create(description: "Mujkići", country: state, continent: continent,  geoname_id: 3256035, population: 0)
province = region.provinces.create(description: "Nezirovac", country: state, continent: continent,  geoname_id: 3252586, population: 0)
province = region.provinces.create(description: "Nikolići", country: state, continent: continent,  geoname_id: 3255334, population: 0)
province = region.provinces.create(description: "Nikolići", country: state, continent: continent,  geoname_id: 3255369, population: 0)
province = region.provinces.create(description: "Ninići", country: state, continent: continent,  geoname_id: 3256324, population: 0)
province = region.provinces.create(description: "Njiverice", country: state, continent: continent,  geoname_id: 3256342, population: 0)
province = region.provinces.create(description: "Njivice", country: state, continent: continent,  geoname_id: 3256083, population: 0)
province = region.provinces.create(description: "Ograđenovac", country: state, continent: continent,  geoname_id: 3211087, population: 0)
province = region.provinces.create(description: "Omerbegovača", country: state, continent: continent,  geoname_id: 3194118, population: 0)
province = region.provinces.create(description: "Pajići", country: state, continent: continent,  geoname_id: 3256488, population: 0)
province = region.provinces.create(description: "Panići", country: state, continent: continent,  geoname_id: 3255405, population: 0)
province = region.provinces.create(description: "Panići", country: state, continent: continent,  geoname_id: 3255415, population: 0)
province = region.provinces.create(description: "Panjik", country: state, continent: continent,  geoname_id: 3253041, population: 0)
province = region.provinces.create(description: "Pavličani", country: state, continent: continent,  geoname_id: 3255292, population: 0)
province = region.provinces.create(description: "Pejini", country: state, continent: continent,  geoname_id: 3256139, population: 0)
province = region.provinces.create(description: "Pejići", country: state, continent: continent,  geoname_id: 3256123, population: 0)
province = region.provinces.create(description: "Pejkovići", country: state, continent: continent,  geoname_id: 3255314, population: 0)
province = region.provinces.create(description: "Pekići", country: state, continent: continent,  geoname_id: 3256100, population: 0)
province = region.provinces.create(description: "Petrići", country: state, continent: continent,  geoname_id: 3255366, population: 0)
province = region.provinces.create(description: "Plazulja", country: state, continent: continent,  geoname_id: 3211490, population: 0)
province = region.provinces.create(description: "Poljani", country: state, continent: continent,  geoname_id: 3256120, population: 0)
province = region.provinces.create(description: "Poljačani", country: state, continent: continent,  geoname_id: 3255040, population: 0)
province = region.provinces.create(description: "Popovo Polje", country: state, continent: continent,  geoname_id: 3192708, population: 0)
province = region.provinces.create(description: "Purići", country: state, continent: continent,  geoname_id: 3256101, population: 0)
province = region.provinces.create(description: "Purići", country: state, continent: continent,  geoname_id: 3256136, population: 0)
province = region.provinces.create(description: "Radići", country: state, continent: continent,  geoname_id: 3255459, population: 0)
province = region.provinces.create(description: "Radoševići", country: state, continent: continent,  geoname_id: 3256142, population: 0)
province = region.provinces.create(description: "Rakovčani", country: state, continent: continent,  geoname_id: 3256983, population: 0)
province = region.provinces.create(description: "Rašljani", country: state, continent: continent,  geoname_id: 3191936, population: 0)
province = region.provinces.create(description: "Ražljevo", country: state, continent: continent,  geoname_id: 3211502, population: 0)
province = region.provinces.create(description: "Redak", country: state, continent: continent,  geoname_id: 3256318, population: 0)
province = region.provinces.create(description: "Repino Brdo", country: state, continent: continent,  geoname_id: 3211498, population: 0)
province = region.provinces.create(description: "Ribić", country: state, continent: continent,  geoname_id: 3256326, population: 0)
province = region.provinces.create(description: "Rijeka", country: state, continent: continent,  geoname_id: 3255463, population: 0)
province = region.provinces.create(description: "Rijeka", country: state, continent: continent,  geoname_id: 3256017, population: 0)
province = region.provinces.create(description: "Ristići", country: state, continent: continent,  geoname_id: 3255330, population: 0)
province = region.provinces.create(description: "Sandići", country: state, continent: continent,  geoname_id: 3191306, population: 0)
province = region.provinces.create(description: "Sarcevići", country: state, continent: continent,  geoname_id: 3256384, population: 0)
province = region.provinces.create(description: "Savići", country: state, continent: continent,  geoname_id: 3256438, population: 0)
province = region.provinces.create(description: "Sekulići", country: state, continent: continent,  geoname_id: 3256055, population: 0)
province = region.provinces.create(description: "Seonjaci", country: state, continent: continent,  geoname_id: 3255089, population: 0)
province = region.provinces.create(description: "Simikići", country: state, continent: continent,  geoname_id: 3211496, population: 0)
province = region.provinces.create(description: "Simići", country: state, continent: continent,  geoname_id: 3256062, population: 0)
province = region.provinces.create(description: "Skakava Donja", country: state, continent: continent,  geoname_id: 3190754, population: 4)
province = region.provinces.create(description: "Skakava Gornja", country: state, continent: continent,  geoname_id: 3190753, population: 0)
province = region.provinces.create(description: "Slijepčevići", country: state, continent: continent,  geoname_id: 3190575, population: 0)
province = region.provinces.create(description: "Sljivići", country: state, continent: continent,  geoname_id: 3252951, population: 0)
province = region.provinces.create(description: "Sombići", country: state, continent: continent,  geoname_id: 3255372, population: 0)
province = region.provinces.create(description: "Srednja Mahala", country: state, continent: continent,  geoname_id: 3254478, population: 0)
province = region.provinces.create(description: "Stanišići", country: state, continent: continent,  geoname_id: 3255356, population: 0)
province = region.provinces.create(description: "Stanovi", country: state, continent: continent,  geoname_id: 3190032, population: 0)
province = region.provinces.create(description: "Staro Brezovo Polje", country: state, continent: continent,  geoname_id: 3255111, population: 0)
province = region.provinces.create(description: "Stuđenča", country: state, continent: continent,  geoname_id: 3255294, population: 0)
province = region.provinces.create(description: "Sukani", country: state, continent: continent,  geoname_id: 3252589, population: 0)
province = region.provinces.create(description: "Suljagića Sokak", country: state, continent: continent,  geoname_id: 3256022, population: 0)
province = region.provinces.create(description: "Sutica", country: state, continent: continent,  geoname_id: 3255100, population: 0)
province = region.provinces.create(description: "Tadići", country: state, continent: continent,  geoname_id: 3255987, population: 0)
province = region.provinces.create(description: "Tinjasi", country: state, continent: continent,  geoname_id: 3255778, population: 0)
province = region.provinces.create(description: "Tinjasi", country: state, continent: continent,  geoname_id: 3256086, population: 0)
province = region.provinces.create(description: "Tokići", country: state, continent: continent,  geoname_id: 3257333, population: 0)
province = region.provinces.create(description: "Tomići", country: state, continent: continent,  geoname_id: 3255443, population: 0)
province = region.provinces.create(description: "Tomići", country: state, continent: continent,  geoname_id: 3255745, population: 0)
province = region.provinces.create(description: "Trnjaci", country: state, continent: continent,  geoname_id: 3188803, population: 0)
province = region.provinces.create(description: "Tufekdžići", country: state, continent: continent,  geoname_id: 3256132, population: 0)
province = region.provinces.create(description: "Ugara", country: state, continent: continent,  geoname_id: 3256098, population: 0)
province = region.provinces.create(description: "Ukelji", country: state, continent: continent,  geoname_id: 3211086, population: 0)
province = region.provinces.create(description: "Ulice", country: state, continent: continent,  geoname_id: 3188512, population: 0)
province = region.provinces.create(description: "Ulović", country: state, continent: continent,  geoname_id: 3188503, population: 0)
province = region.provinces.create(description: "Vasiljevići", country: state, continent: continent,  geoname_id: 3256130, population: 0)
province = region.provinces.create(description: "Velino Selo", country: state, continent: continent,  geoname_id: 3187907, population: 0)
province = region.provinces.create(description: "Vitanovići Donji", country: state, continent: continent,  geoname_id: 3187597, population: 0)
province = region.provinces.create(description: "Vitanovići Gornji", country: state, continent: continent,  geoname_id: 3187596, population: 0)
province = region.provinces.create(description: "Vujićići", country: state, continent: continent,  geoname_id: 3187074, population: 0)
province = region.provinces.create(description: "Vukšić Donji", country: state, continent: continent,  geoname_id: 3187030, population: 0)
province = region.provinces.create(description: "Vukšić Gornji", country: state, continent: continent,  geoname_id: 3187029, population: 0)
province = region.provinces.create(description: "Vučilovac", country: state, continent: continent,  geoname_id: 3187098, population: 0)
province = region.provinces.create(description: "Zarići", country: state, continent: continent,  geoname_id: 3255953, population: 0)
province = region.provinces.create(description: "Ðukići", country: state, continent: continent,  geoname_id: 3256143, population: 0)
province = region.provinces.create(description: "Ðurići", country: state, continent: continent,  geoname_id: 3255107, population: 0)
province = region.provinces.create(description: "Ðurđevik", country: state, continent: continent,  geoname_id: 3252585, population: 0)
province = region.provinces.create(description: "Ćirkovići", country: state, continent: continent,  geoname_id: 3255414, population: 0)
province = region.provinces.create(description: "Čande", country: state, continent: continent,  geoname_id: 3211089, population: 0)
province = region.provinces.create(description: "Čerkezovići", country: state, continent: continent,  geoname_id: 3256144, population: 0)
province = region.provinces.create(description: "Čoseti", country: state, continent: continent,  geoname_id: 3211088, population: 0)
province = region.provinces.create(description: "Šatorovići", country: state, continent: continent,  geoname_id: 3191243, population: 0)
province = region.provinces.create(description: "Šokčevići", country: state, continent: continent,  geoname_id: 3255316, population: 0)
province = region.provinces.create(description: "Špionica", country: state, continent: continent,  geoname_id: 3255194, population: 0)
province = region.provinces.create(description: "Štrepci", country: state, continent: continent,  geoname_id: 3189734, population: 0)
province = region.provinces.create(description: "Šumari", country: state, continent: continent,  geoname_id: 3255323, population: 0)
province = region.provinces.create(description: "Šumari", country: state, continent: continent,  geoname_id: 3255331, population: 0)
region = Region.create(description: "Federacija Bosne i Hercegovine", country: state, continent: continent, geoname_id: 3229999)
province = region.provinces.create(description: "Bosansko-Podrinjski Kanton", country: state, continent: continent,  geoname_id: 3343726, population: 0)
province.municipalities.create(description: "Foca-Ustikolina", region: region, country: state, continent: continent, geoname_id: 7648080, population: 0)
province.municipalities.create(description: "Pale-Prača", region: region, country: state, continent: continent, geoname_id: 7648081, population: 0)
province = region.provinces.create(description: "Hercegovačko-Bosanski Kanton", country: state, continent: continent,  geoname_id: 3343740, population: 0)
province.municipalities.create(description: "Međugorje", region: region, country: state, continent: continent, geoname_id: 3195308, population: 0)
province.municipalities.create(description: "Međugorje", region: region, country: state, continent: continent, geoname_id: 3264817, population: 0)
province.municipalities.create(description: "Mostar", region: region, country: state, continent: continent, geoname_id: 3194828, population: 104518)
province.municipalities.create(description: "Neum", region: region, country: state, continent: continent, geoname_id: 3194514, population: 4200)
province.municipalities.create(description: "Čapljina", region: region, country: state, continent: continent, geoname_id: 3261342, population: 0)
province = region.provinces.create(description: "Hercegovačko-neretvanski kanton", country: state, continent: continent,  geoname_id: 3343733, population: 0)
province = region.provinces.create(description: "Neretvljanski", country: state, continent: continent,  geoname_id: 7648659, population: 0)
province = region.provinces.create(description: "Posavski kanton", country: state, continent: continent,  geoname_id: 3343706, population: 0)
province.municipalities.create(description: "Vukosavlje", region: region, country: state, continent: continent, geoname_id: 7648083, population: 0)
province = region.provinces.create(description: "Sarajevo kanton", country: state, continent: continent,  geoname_id: 3343737, population: 0)
province.municipalities.create(description: "Sarajevo", region: region, country: state, continent: continent, geoname_id: 3191281, population: 696731)
province = region.provinces.create(description: "Srednjobosanski kanton", country: state, continent: continent,  geoname_id: 3343731, population: 0)
province = region.provinces.create(description: "Tuzlanski kanton", country: state, continent: continent,  geoname_id: 3343716, population: 0)
province.municipalities.create(description: "Općina Kalesija", region: region, country: state, continent: continent, geoname_id: 3343708, population: 0)
province = region.provinces.create(description: "Unsko-Sanski Kanton", country: state, continent: continent,  geoname_id: 3343704, population: 0)
province = region.provinces.create(description: "Zapadnohercegovački kanton", country: state, continent: continent,  geoname_id: 3343736, population: 0)
province = region.provinces.create(description: "Zeničko-dobojski kanton", country: state, continent: continent,  geoname_id: 3343722, population: 0)
region = Region.create(description: "Republika Srpska", country: state, continent: continent, geoname_id: 3230000)
province = region.provinces.create(description: "Istočna Ilidža", country: state, continent: continent,  geoname_id: 3344108, population: 0)
province = region.provinces.create(description: "Istočni Drvar", country: state, continent: continent,  geoname_id: 3344097, population: 0)
province = region.provinces.create(description: "Istočni Mostar", country: state, continent: continent,  geoname_id: 3344111, population: 0)
province = region.provinces.create(description: "Istočni Stari Grad", country: state, continent: continent,  geoname_id: 3344106, population: 0)
province = region.provinces.create(description: "Istočno Novo Sarajevo", country: state, continent: continent,  geoname_id: 3344107, population: 0)
province = region.provinces.create(description: "Modriča", country: state, continent: continent,  geoname_id: 3194943, population: 5136)
province = region.provinces.create(description: "Mrkonjic Grad Jug Opcina", country: state, continent: continent,  geoname_id: 3344099, population: 0)
province = region.provinces.create(description: "Novo Goražde", country: state, continent: continent,  geoname_id: 3344105, population: 0)
province = region.provinces.create(description: "Opstina Brod", country: state, continent: continent,  geoname_id: 3294918, population: 0)
province = region.provinces.create(description: "Općina Donji Žabar", country: state, continent: continent,  geoname_id: 3344091, population: 0)
province = region.provinces.create(description: "Općina Jajce", country: state, continent: continent,  geoname_id: 3344112, population: 0)
province = region.provinces.create(description: "Općina Kneževo", country: state, continent: continent,  geoname_id: 3344093, population: 0)
province = region.provinces.create(description: "Opština Banja Luka", country: state, continent: continent,  geoname_id: 3294893, population: 0)
province = region.provinces.create(description: "Opština Berkovići", country: state, continent: continent,  geoname_id: 3344110, population: 0)
province = region.provinces.create(description: "Opština Bijeljina", country: state, continent: continent,  geoname_id: 3294896, population: 0)
province.municipalities.create(description: "Vasilići", region: region, country: state, continent: continent, geoname_id: 3253657, population: 0)
province = region.provinces.create(description: "Opština Bileća", country: state, continent: continent,  geoname_id: 3294539, population: 0)
province.municipalities.create(description: "Bileća", region: region, country: state, continent: continent, geoname_id: 3204161, population: 13257)
province = region.provinces.create(description: "Opština Bratunac", country: state, continent: continent,  geoname_id: 3344103, population: 0)
province = region.provinces.create(description: "Opština Derventa", country: state, continent: continent,  geoname_id: 3294910, population: 0)
province = region.provinces.create(description: "Opština Doboj", country: state, continent: continent,  geoname_id: 3294894, population: 0)
province.municipalities.create(description: "Tutnjevici", region: region, country: state, continent: continent, geoname_id: 3252014, population: 0)
province = region.provinces.create(description: "Opština Gacko", country: state, continent: continent,  geoname_id: 3294558, population: 0)
province = region.provinces.create(description: "Opština Gradiška", country: state, continent: continent,  geoname_id: 3294917, population: 0)
province = region.provinces.create(description: "Opština Han Pijesak", country: state, continent: continent,  geoname_id: 3294830, population: 0)
province = region.provinces.create(description: "Opština Kalinovik", country: state, continent: continent,  geoname_id: 3294564, population: 0)
province = region.provinces.create(description: "Opština Kostajnica", country: state, continent: continent,  geoname_id: 3344114, population: 0)
province = region.provinces.create(description: "Opština Kotor-Varoš", country: state, continent: continent,  geoname_id: 3294871, population: 0)
province = region.provinces.create(description: "Opština Kozarska Dubica", country: state, continent: continent,  geoname_id: 3344088, population: 0)
province = region.provinces.create(description: "Opština Krupa na Uni", country: state, continent: continent,  geoname_id: 3344087, population: 0)
province = region.provinces.create(description: "Opština Kupres", country: state, continent: continent,  geoname_id: 3344113, population: 0)
province = region.provinces.create(description: "Opština Laktaši", country: state, continent: continent,  geoname_id: 3294906, population: 0)
province = region.provinces.create(description: "Opština Ljubinje", country: state, continent: continent,  geoname_id: 3294540, population: 0)
province = region.provinces.create(description: "Opština Lopare", country: state, continent: continent,  geoname_id: 3294873, population: 0)
province = region.provinces.create(description: "Opština Milići", country: state, continent: continent,  geoname_id: 3344118, population: 0)
province = region.provinces.create(description: "Opština Modriča", country: state, continent: continent,  geoname_id: 3294911, population: 0)
province = region.provinces.create(description: "Opština Mrkonjić-Grad", country: state, continent: continent,  geoname_id: 3344094, population: 0)
province = region.provinces.create(description: "Opština Nevesinje", country: state, continent: continent,  geoname_id: 3294561, population: 0)
province = region.provinces.create(description: "Opština Novi Grad", country: state, continent: continent,  geoname_id: 3294915, population: 0)
province = region.provinces.create(description: "Opština Osmaci", country: state, continent: continent,  geoname_id: 3344101, population: 0)
province = region.provinces.create(description: "Opština Oštra Luka", country: state, continent: continent,  geoname_id: 3344089, population: 0)
province = region.provinces.create(description: "Opština Pale", country: state, continent: continent,  geoname_id: 3294773, population: 0)
province = region.provinces.create(description: "Opština Pelagićevo", country: state, continent: continent,  geoname_id: 3344092, population: 0)
province = region.provinces.create(description: "Opština Petrovac", country: state, continent: continent,  geoname_id: 3344096, population: 0)
province = region.provinces.create(description: "Opština Petrovo", country: state, continent: continent,  geoname_id: 3344115, population: 0)
province = region.provinces.create(description: "Opština Prijedor", country: state, continent: continent,  geoname_id: 3294909, population: 0)
province = region.provinces.create(description: "Opština Prnjavor", country: state, continent: continent,  geoname_id: 3294904, population: 0)
province = region.provinces.create(description: "Opština Ribnik", country: state, continent: continent,  geoname_id: 3344098, population: 0)
province = region.provinces.create(description: "Opština Rogatica", country: state, continent: continent,  geoname_id: 3294774, population: 0)
province = region.provinces.create(description: "Opština Rudo", country: state, continent: continent,  geoname_id: 3294770, population: 0)
province.municipalities.create(description: "Mioče (Rudo)", region: region, country: state, continent: continent, geoname_id: 3298614, population: 469)
province = region.provinces.create(description: "Opština Sokolac", country: state, continent: continent,  geoname_id: 3344104, population: 0)
province = region.provinces.create(description: "Opština Srbac", country: state, continent: continent,  geoname_id: 3294912, population: 0)
province = region.provinces.create(description: "Opština Srbinje", country: state, continent: continent,  geoname_id: 3294565, population: 0)
province = region.provinces.create(description: "Opština Srebrenica", country: state, continent: continent,  geoname_id: 3294829, population: 0)
province.municipalities.create(description: "Srebrenica", region: region, country: state, continent: continent, geoname_id: 3190159, population: 2862)
province = region.provinces.create(description: "Opština Teslić", country: state, continent: continent,  geoname_id: 3294865, population: 0)
province = region.provinces.create(description: "Opština Trebinje", country: state, continent: continent,  geoname_id: 3344117, population: 0)
province = region.provinces.create(description: "Opština Trnovo", country: state, continent: continent,  geoname_id: 3344109, population: 0)
province = region.provinces.create(description: "Opština Ugljevik", country: state, continent: continent,  geoname_id: 3294874, population: 0)
province.municipalities.create(description: "Atmačići", region: region, country: state, continent: continent, geoname_id: 3204759, population: 0)
province.municipalities.create(description: "Baljak", region: region, country: state, continent: continent, geoname_id: 3253913, population: 0)
province.municipalities.create(description: "Bogutovo Selo", region: region, country: state, continent: continent, geoname_id: 3203812, population: 4)
province.municipalities.create(description: "Brđani", region: region, country: state, continent: continent, geoname_id: 3211455, population: 0)
province.municipalities.create(description: "Donja Krčina", region: region, country: state, continent: continent, geoname_id: 3211576, population: 0)
province.municipalities.create(description: "Donja Trnova", region: region, country: state, continent: continent, geoname_id: 3201607, population: 0)
province.municipalities.create(description: "Gajići", region: region, country: state, continent: continent, geoname_id: 3253902, population: 0)
province.municipalities.create(description: "Glinje", region: region, country: state, continent: continent, geoname_id: 3200591, population: 0)
province.municipalities.create(description: "Gornja Krčina", region: region, country: state, continent: continent, geoname_id: 3197319, population: 0)
province.municipalities.create(description: "Gornja Trnova", region: region, country: state, continent: continent, geoname_id: 3253975, population: 0)
province.municipalities.create(description: "Janjari", region: region, country: state, continent: continent, geoname_id: 3211565, population: 0)
province.municipalities.create(description: "Mezgraja", region: region, country: state, continent: continent, geoname_id: 3195203, population: 0)
province.municipalities.create(description: "Mukat", region: region, country: state, continent: continent, geoname_id: 3254065, population: 0)
province.municipalities.create(description: "Ravno Polje", region: region, country: state, continent: continent, geoname_id: 3211562, population: 0)
province.municipalities.create(description: "Srednja Trnova", region: region, country: state, continent: continent, geoname_id: 3190137, population: 0)
province.municipalities.create(description: "Ugljevik", region: region, country: state, continent: continent, geoname_id: 3188532, population: 3452)
province.municipalities.create(description: "Ugljevik", region: region, country: state, continent: continent, geoname_id: 3253930, population: 0)
province.municipalities.create(description: "Ugljevička Obrijež", region: region, country: state, continent: continent, geoname_id: 3194251, population: 0)
province.municipalities.create(description: "Zabrđe", region: region, country: state, continent: continent, geoname_id: 3186967, population: 0)
province = region.provinces.create(description: "Opština Višegrad", country: state, continent: continent,  geoname_id: 3294772, population: 0)
province = region.provinces.create(description: "Opština Vlasenica", country: state, continent: continent,  geoname_id: 3294839, population: 0)
province = region.provinces.create(description: "Opština Vukosavlje", country: state, continent: continent,  geoname_id: 3344090, population: 0)
province = region.provinces.create(description: "Opština Zvornik", country: state, continent: continent,  geoname_id: 3344100, population: 0)
province = region.provinces.create(description: "Opština Čajniče", country: state, continent: continent,  geoname_id: 3294566, population: 0)
province = region.provinces.create(description: "Opština Čelinac", country: state, continent: continent,  geoname_id: 3294889, population: 0)
province = region.provinces.create(description: "Opština Šamac", country: state, continent: continent,  geoname_id: 3294916, population: 0)
province = region.provinces.create(description: "Opština Šekovići", country: state, continent: continent,  geoname_id: 3344102, population: 0)
province = region.provinces.create(description: "Opština Šipovo", country: state, continent: continent,  geoname_id: 3344095, population: 0)
province = region.provinces.create(description: "Skelani Opština", country: state, continent: continent,  geoname_id: 3344119, population: 0)
