Comune.create(description: "Belvedere Di Spinello", province_id: 23, region_id:  7, country_id: 1, continent_id: 1 , population: 2470)
Comune.create(description: "Caccuri", province_id: 23, region_id:  7, country_id: 1, continent_id: 1 , population: 1780)
Comune.create(description: "Carfizzi", province_id: 23, region_id:  7, country_id: 1, continent_id: 1 , population: 868)
Comune.create(description: "Casabona", province_id: 23, region_id:  7, country_id: 1, continent_id: 1 , population: 3160)
Comune.create(description: "Castelsilano", province_id: 23, region_id:  7, country_id: 1, continent_id: 1 , population: 1273)
Comune.create(description: "Cerenzia", province_id: 23, region_id:  7, country_id: 1, continent_id: 1 , population: 1371)
Comune.create(description: "Cotronei", province_id: 23, region_id:  7, country_id: 1, continent_id: 1 , population: 5500)
Comune.create(description: "Crotone", province_id: 23, region_id:  7, country_id: 1, continent_id: 1 , population: 60010)
Comune.create(description: "Crucoli", province_id: 23, region_id:  7, country_id: 1, continent_id: 1 , population: 3377)
Comune.create(description: "Cutro", province_id: 23, region_id:  7, country_id: 1, continent_id: 1 , population: 10829)
Comune.create(description: "Isola Di Capo Rizzuto", province_id: 23, region_id:  7, country_id: 1, continent_id: 1 , population: 14233)
Comune.create(description: "Melissa", province_id: 23, region_id:  7, country_id: 1, continent_id: 1 , population: 3245)
Comune.create(description: "Mesoraca", province_id: 23, region_id:  7, country_id: 1, continent_id: 1 , population: 7125)
Comune.create(description: "Pallagorio", province_id: 23, region_id:  7, country_id: 1, continent_id: 1 , population: 1627)
Comune.create(description: "Petilia Policastro", province_id: 23, region_id:  7, country_id: 1, continent_id: 1 , population: 9594)
Comune.create(description: "Rocca Di Neto", province_id: 23, region_id:  7, country_id: 1, continent_id: 1 , population: 5614)
Comune.create(description: "Roccabernarda", province_id: 23, region_id:  7, country_id: 1, continent_id: 1 , population: 3385)
Comune.create(description: "San Mauro Marchesato", province_id: 23, region_id:  7, country_id: 1, continent_id: 1 , population: 2415)
Comune.create(description: "Santa Severina", province_id: 23, region_id:  7, country_id: 1, continent_id: 1 , population: 2327)
Comune.create(description: "Savelli", province_id: 23, region_id:  7, country_id: 1, continent_id: 1 , population: 1583)
Comune.create(description: "Scandale", province_id: 23, region_id:  7, country_id: 1, continent_id: 1 , population: 3177)
Comune.create(description: "Strongoli", province_id: 23, region_id:  7, country_id: 1, continent_id: 1 , population: 6107)
Comune.create(description: "Umbriatico", province_id: 23, region_id:  7, country_id: 1, continent_id: 1 , population: 973)
Comune.create(description: "Verzino", province_id: 23, region_id:  7, country_id: 1, continent_id: 1 , population: 2373)
Comune.create(description: "Ciro'", province_id: 23, region_id:  7, country_id: 1, continent_id: 1 , population: 3614)
Comune.create(description: "Ciro' Marina", province_id: 23, region_id:  7, country_id: 1, continent_id: 1 , population: 13987)
Comune.create(description: "San Nicola Dell'Alto", province_id: 23, region_id:  7, country_id: 1, continent_id: 1 , population: 1105)
