#encoding: utf-8
Comune.create(:description => "Belvedere Di Spinello", :provincia_id => 23, :regione_id => 7, :population => 2470)
Comune.create(:description => "Caccuri", :provincia_id => 23, :regione_id => 7, :population => 1780)
Comune.create(:description => "Carfizzi", :provincia_id => 23, :regione_id => 7, :population => 868)
Comune.create(:description => "Casabona", :provincia_id => 23, :regione_id => 7, :population => 3160)
Comune.create(:description => "Castelsilano", :provincia_id => 23, :regione_id => 7, :population => 1273)
Comune.create(:description => "Cerenzia", :provincia_id => 23, :regione_id => 7, :population => 1371)
Comune.create(:description => "Cotronei", :provincia_id => 23, :regione_id => 7, :population => 5500)
Comune.create(:description => "Crotone", :provincia_id => 23, :regione_id => 7, :population => 60010)
Comune.create(:description => "Crucoli", :provincia_id => 23, :regione_id => 7, :population => 3377)
Comune.create(:description => "Cutro", :provincia_id => 23, :regione_id => 7, :population => 10829)
Comune.create(:description => "Isola Di Capo Rizzuto", :provincia_id => 23, :regione_id => 7, :population => 14233)
Comune.create(:description => "Melissa", :provincia_id => 23, :regione_id => 7, :population => 3245)
Comune.create(:description => "Mesoraca", :provincia_id => 23, :regione_id => 7, :population => 7125)
Comune.create(:description => "Pallagorio", :provincia_id => 23, :regione_id => 7, :population => 1627)
Comune.create(:description => "Petilia Policastro", :provincia_id => 23, :regione_id => 7, :population => 9594)
Comune.create(:description => "Rocca Di Neto", :provincia_id => 23, :regione_id => 7, :population => 5614)
Comune.create(:description => "Roccabernarda", :provincia_id => 23, :regione_id => 7, :population => 3385)
Comune.create(:description => "San Mauro Marchesato", :provincia_id => 23, :regione_id => 7, :population => 2415)
Comune.create(:description => "Santa Severina", :provincia_id => 23, :regione_id => 7, :population => 2327)
Comune.create(:description => "Savelli", :provincia_id => 23, :regione_id => 7, :population => 1583)
Comune.create(:description => "Scandale", :provincia_id => 23, :regione_id => 7, :population => 3177)
Comune.create(:description => "Strongoli", :provincia_id => 23, :regione_id => 7, :population => 6107)
Comune.create(:description => "Umbriatico", :provincia_id => 23, :regione_id => 7, :population => 973)
Comune.create(:description => "Verzino", :provincia_id => 23, :regione_id => 7, :population => 2373)
Comune.create(:description => "Ciro'", :provincia_id => 23, :regione_id => 7, :population => 3614)
Comune.create(:description => "Ciro' Marina", :provincia_id => 23, :regione_id => 7, :population => 13987)
Comune.create(:description => "San Nicola Dell'Alto", :provincia_id => 23, :regione_id => 7, :population => 1105)
