continent = Continent.find_by(description: 'Europe')
state = Country.find_by(description: 'Montenegro')
region = Region.create(description: "Andrijevica", country: state, continent: continent, geoname_id: 3343959)
province = region.provinces.create(description: "Andrijevica", country: state, continent: continent,  geoname_id: 3204816, population: 1073)
region = Region.create(description: "Bar", country: state, continent: continent, geoname_id: 3204508)
province = region.provinces.create(description: "Bar", country: state, continent: continent,  geoname_id: 3204509, population: 17727)
province.municipalities.create(description: "Bjeliši", region: region, country: state, continent: continent, geoname_id: 3203999, population: 0)
province.municipalities.create(description: "Popovići", region: region, country: state, continent: continent, geoname_id: 3317689, population: 5)
province.municipalities.create(description: "Topolica", region: region, country: state, continent: continent, geoname_id: 3317691, population: 5)
province = region.provinces.create(description: "Sutomore", country: state, continent: continent,  geoname_id: 3189429, population: 1827)
province = region.provinces.create(description: "Utjeha", country: state, continent: continent,  geoname_id: 7287834, population: 0)
province = region.provinces.create(description: "Šušanj", country: state, continent: continent,  geoname_id: 3318488, population: 2521)
region = Region.create(description: "Berane", country: state, continent: continent, geoname_id: 3199070)
province = region.provinces.create(description: "Berane", country: state, continent: continent,  geoname_id: 3199071, population: 11073)
province = region.provinces.create(description: "Tripkovići", country: state, continent: continent,  geoname_id: 3318240, population: 5)
region = Region.create(description: "Bijelo Polje", country: state, continent: continent, geoname_id: 3204173)
province = region.provinces.create(description: "Bijelo Polje", country: state, continent: continent,  geoname_id: 3204176, population: 15400)
province = region.provinces.create(description: "Dobre Vode", country: state, continent: continent,  geoname_id: 3339421, population: 0)
region = Region.create(description: "Budva", country: state, continent: continent, geoname_id: 3203104)
province = region.provinces.create(description: "Budva", country: state, continent: continent,  geoname_id: 3203106, population: 18000)
province = region.provinces.create(description: "Pržno", country: state, continent: continent,  geoname_id: 3318402, population: 5)
region = Region.create(description: "Cetinje", country: state, continent: continent, geoname_id: 3202640)
province = region.provinces.create(description: "Cetinje", country: state, continent: continent,  geoname_id: 3202641, population: 15137)
region = Region.create(description: "Danilovgrad", country: state, continent: continent, geoname_id: 3202193)
province = region.provinces.create(description: "Danilovgrad", country: state, continent: continent,  geoname_id: 3202194, population: 5208)
region = Region.create(description: "Herceg Novi", country: state, continent: continent, geoname_id: 3199393)
province = region.provinces.create(description: "Herceg Novi", country: state, continent: continent,  geoname_id: 3199394, population: 19536)
region = Region.create(description: "Kotor", country: state, continent: continent, geoname_id: 3197537)
province = region.provinces.create(description: "Kotor", country: state, continent: continent,  geoname_id: 3197538, population: 5345)
province = region.provinces.create(description: "Perast", country: state, continent: continent,  geoname_id: 3193504, population: 551)
province = region.provinces.create(description: "Risan", country: state, continent: continent,  geoname_id: 3191631, population: 2083)
region = Region.create(description: "Mojkovac", country: state, continent: continent, geoname_id: 3194925)
province = region.provinces.create(description: "Mojkovac", country: state, continent: continent,  geoname_id: 3194926, population: 4120)
region = Region.create(description: "Opština Kolašin", country: state, continent: continent, geoname_id: 3197895)
province = region.provinces.create(description: "Kolašin", country: state, continent: continent,  geoname_id: 3197896, population: 2989)
region = Region.create(description: "Opština Nikšić", country: state, continent: continent, geoname_id: 3194493)
province = region.provinces.create(description: "Nikšić", country: state, continent: continent,  geoname_id: 3194494, population: 58212)
region = Region.create(description: "Opština Plav", country: state, continent: continent, geoname_id: 3193227)
province = region.provinces.create(description: "Plav", country: state, continent: continent,  geoname_id: 3193228, population: 3615)
region = Region.create(description: "Opština Plužine", country: state, continent: continent, geoname_id: 3193129)
province = region.provinces.create(description: "Plužine", country: state, continent: continent,  geoname_id: 3193131, population: 1494)
region = Region.create(description: "Opština Rožaje", country: state, continent: continent, geoname_id: 786233)
province = region.provinces.create(description: "Rožaje", country: state, continent: continent,  geoname_id: 786234, population: 9121)
region = Region.create(description: "Opština Šavnik", country: state, continent: continent, geoname_id: 3191221)
province = region.provinces.create(description: "Šavnik", country: state, continent: continent,  geoname_id: 3191222, population: 633)
region = Region.create(description: "Opština Žabljak", country: state, continent: continent, geoname_id: 3186995)
province = region.provinces.create(description: "Žabljak", country: state, continent: continent,  geoname_id: 3186999, population: 1937)
region = Region.create(description: "Pljevlja", country: state, continent: continent, geoname_id: 3193160)
province = region.provinces.create(description: "Pljevlja", country: state, continent: continent,  geoname_id: 3193161, population: 19489)
region = Region.create(description: "Podgorica", country: state, continent: continent, geoname_id: 3189077)
province = region.provinces.create(description: "Mitrovići", country: state, continent: continent,  geoname_id: 3342186, population: 0)
province = region.provinces.create(description: "Podgorica", country: state, continent: continent,  geoname_id: 3193044, population: 136473)
province.municipalities.create(description: "Drač", region: region, country: state, continent: continent, geoname_id: 3343002, population: 0)
province.municipalities.create(description: "Drpe Mandića", region: region, country: state, continent: continent, geoname_id: 3343001, population: 0)
province.municipalities.create(description: "Ibričevina", region: region, country: state, continent: continent, geoname_id: 3343004, population: 0)
province.municipalities.create(description: "Kruševac", region: region, country: state, continent: continent, geoname_id: 3342728, population: 0)
province.municipalities.create(description: "Masline", region: region, country: state, continent: continent, geoname_id: 3220475, population: 0)
province.municipalities.create(description: "Momišići", region: region, country: state, continent: continent, geoname_id: 3316515, population: 0)
province.municipalities.create(description: "Nova Varoš", region: region, country: state, continent: continent, geoname_id: 3342997, population: 0)
province.municipalities.create(description: "Pobrežje", region: region, country: state, continent: continent, geoname_id: 3342735, population: 0)
province.municipalities.create(description: "Ribnička Vrela", region: region, country: state, continent: continent, geoname_id: 3343007, population: 0)
province.municipalities.create(description: "Stara Varoš", region: region, country: state, continent: continent, geoname_id: 3342998, population: 0)
province.municipalities.create(description: "Svijetin Brijeg", region: region, country: state, continent: continent, geoname_id: 3343003, population: 0)
region = Region.create(description: "Tivat", country: state, continent: continent, geoname_id: 3189071)
province = region.provinces.create(description: "Radovići", country: state, continent: continent,  geoname_id: 3192068, population: 0)
province = region.provinces.create(description: "Tivat", country: state, continent: continent,  geoname_id: 3189073, population: 6280)
region = Region.create(description: "Ulcinj", country: state, continent: continent, geoname_id: 3188514)
province = region.provinces.create(description: "Ulcinj", country: state, continent: continent,  geoname_id: 3188516, population: 10828)
