Municipality.create(description: "Africo", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 3465)
Municipality.create(description: "Agnana Calabra", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 673)
Municipality.create(description: "Anoia", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 2378)
Municipality.create(description: "Antonimina", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 1442)
Municipality.create(description: "Ardore", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 4820)
Municipality.create(description: "Bagaladi", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 1286)
Municipality.create(description: "Bagnara Calabra", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 11230)
Municipality.create(description: "Benestare", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 2426)
Municipality.create(description: "Bianco", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 4047)
Municipality.create(description: "Bivongi", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 1596)
Municipality.create(description: "Bova", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 474)
Municipality.create(description: "Bova Marina", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 3967)
Municipality.create(description: "Bovalino", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 8358)
Municipality.create(description: "Brancaleone", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 3882)
Municipality.create(description: "Bruzzano Zeffirio", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 1401)
Municipality.create(description: "Calanna", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 1183)
Municipality.create(description: "Camini", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 736)
Municipality.create(description: "Campo Calabro", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 4074)
Municipality.create(description: "Candidoni", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 410)
Municipality.create(description: "Canolo", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 957)
Municipality.create(description: "Caraffa Del Bianco", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 622)
Municipality.create(description: "Cardeto", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 2325)
Municipality.create(description: "Careri", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 2443)
Municipality.create(description: "Casignana", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 775)
Municipality.create(description: "Caulonia", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 7756)
Municipality.create(description: "Cinquefrondi", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 6461)
Municipality.create(description: "Cittanova", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 10675)
Municipality.create(description: "Condofuri", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 5055)
Municipality.create(description: "Cosoleto", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 976)
Municipality.create(description: "Delianuova", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 3584)
Municipality.create(description: "Feroleto Della Chiesa", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 1872)
Municipality.create(description: "Ferruzzano", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 852)
Municipality.create(description: "Fiumara", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 1201)
Municipality.create(description: "Galatro", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 2307)
Municipality.create(description: "Gerace", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 2973)
Municipality.create(description: "Giffone", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 2182)
Municipality.create(description: "Gioia Tauro", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 17762)
Municipality.create(description: "Gioiosa Ionica", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 7044)
Municipality.create(description: "Grotteria", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 3611)
Municipality.create(description: "Laganadi", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 498)
Municipality.create(description: "Laureana Di Borrello", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 5709)
Municipality.create(description: "Locri", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 12997)
Municipality.create(description: "Mammola", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 3389)
Municipality.create(description: "Marina Di Gioiosa Ionica", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 6440)
Municipality.create(description: "Maropati", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 1736)
Municipality.create(description: "Martone", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 597)
Municipality.create(description: "Melicucco", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 4996)
Municipality.create(description: "Melito Di Porto Salvo", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 10506)
Municipality.create(description: "Molochio", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 2803)
Municipality.create(description: "Monasterace", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 3426)
Municipality.create(description: "Montebello Ionico", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 6922)
Municipality.create(description: "Motta San Giovanni", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 6449)
Municipality.create(description: "Oppido Mamertina", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 5559)
Municipality.create(description: "Palizzi", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 2709)
Municipality.create(description: "Palmi", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 19435)
Municipality.create(description: "Pazzano", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 799)
Municipality.create(description: "Placanica", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 1507)
Municipality.create(description: "Polistena", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 11591)
Municipality.create(description: "Portigliola", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 1343)
Municipality.create(description: "Reggio Calabria", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 )
Municipality.create(description: "Riace", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 1605)
Municipality.create(description: "Rizziconi", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 7650)
Municipality.create(description: "Roccaforte Del Greco", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 802)
Municipality.create(description: "Roccella Ionica", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 6762)
Municipality.create(description: "Roghudi", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 1365)
Municipality.create(description: "Rosarno", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 15051)
Municipality.create(description: "Samo", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 1097)
Municipality.create(description: "San Ferdinando", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 4339)
Municipality.create(description: "San Giorgio Morgeto", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 3384)
Municipality.create(description: "San Giovanni Di Gerace", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 609)
Municipality.create(description: "San Lorenzo", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 3357)
Municipality.create(description: "San Luca", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 4106)
Municipality.create(description: "San Procopio", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 617)
Municipality.create(description: "San Roberto", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 1985)
Municipality.create(description: "Santo Stefano In Aspromonte", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 1470)
Municipality.create(description: "Scido", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 1047)
Municipality.create(description: "Scilla", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 5176)
Municipality.create(description: "Seminara", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 3352)
Municipality.create(description: "Serrata", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 964)
Municipality.create(description: "Siderno", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 16734)
Municipality.create(description: "Sinopoli", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 2329)
Municipality.create(description: "Staiti", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 395)
Municipality.create(description: "Stignano", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 1373)
Municipality.create(description: "Stilo", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 2816)
Municipality.create(description: "Taurianova", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 15799)
Municipality.create(description: "Terranova Sappo Minulio", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 537)
Municipality.create(description: "Varapodio", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 2329)
Municipality.create(description: "Villa San Giovanni", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 13119)
Municipality.create(description: "Cimina'", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 683)
Municipality.create(description: "Melicucca'", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 1079)
Municipality.create(description: "Plati'", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 3823)
Municipality.create(description: "San Pietro Di Carida'", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 1715)
Municipality.create(description: "Santa Cristina D'Aspromonte", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 1095)
Municipality.create(description: "Sant'Agata Del Bianco", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 715)
Municipality.create(description: "Sant'Alessio In Aspromonte", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 436)
Municipality.create(description: "Sant'Eufemia D'Aspromonte", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 4074)
Municipality.create(description: "Sant'Ilario Dello Ionio", province_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 1389)
