Comune.create(description: "Africo", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 3465)
Comune.create(description: "Agnana Calabra", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 673)
Comune.create(description: "Anoia", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 2378)
Comune.create(description: "Antonimina", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 1442)
Comune.create(description: "Ardore", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 4820)
Comune.create(description: "Bagaladi", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 1286)
Comune.create(description: "Bagnara Calabra", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 11230)
Comune.create(description: "Benestare", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 2426)
Comune.create(description: "Bianco", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 4047)
Comune.create(description: "Bivongi", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 1596)
Comune.create(description: "Bova", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 474)
Comune.create(description: "Bova Marina", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 3967)
Comune.create(description: "Bovalino", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 8358)
Comune.create(description: "Brancaleone", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 3882)
Comune.create(description: "Bruzzano Zeffirio", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 1401)
Comune.create(description: "Calanna", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 1183)
Comune.create(description: "Camini", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 736)
Comune.create(description: "Campo Calabro", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 4074)
Comune.create(description: "Candidoni", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 410)
Comune.create(description: "Canolo", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 957)
Comune.create(description: "Caraffa Del Bianco", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 622)
Comune.create(description: "Cardeto", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 2325)
Comune.create(description: "Careri", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 2443)
Comune.create(description: "Casignana", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 775)
Comune.create(description: "Caulonia", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 7756)
Comune.create(description: "Cinquefrondi", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 6461)
Comune.create(description: "Cittanova", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 10675)
Comune.create(description: "Condofuri", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 5055)
Comune.create(description: "Cosoleto", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 976)
Comune.create(description: "Delianuova", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 3584)
Comune.create(description: "Feroleto Della Chiesa", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 1872)
Comune.create(description: "Ferruzzano", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 852)
Comune.create(description: "Fiumara", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 1201)
Comune.create(description: "Galatro", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 2307)
Comune.create(description: "Gerace", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 2973)
Comune.create(description: "Giffone", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 2182)
Comune.create(description: "Gioia Tauro", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 17762)
Comune.create(description: "Gioiosa Ionica", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 7044)
Comune.create(description: "Grotteria", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 3611)
Comune.create(description: "Laganadi", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 498)
Comune.create(description: "Laureana Di Borrello", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 5709)
Comune.create(description: "Locri", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 12997)
Comune.create(description: "Mammola", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 3389)
Comune.create(description: "Marina Di Gioiosa Ionica", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 6440)
Comune.create(description: "Maropati", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 1736)
Comune.create(description: "Martone", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 597)
Comune.create(description: "Melicucco", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 4996)
Comune.create(description: "Melito Di Porto Salvo", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 10506)
Comune.create(description: "Molochio", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 2803)
Comune.create(description: "Monasterace", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 3426)
Comune.create(description: "Montebello Ionico", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 6922)
Comune.create(description: "Motta San Giovanni", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 6449)
Comune.create(description: "Oppido Mamertina", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 5559)
Comune.create(description: "Palizzi", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 2709)
Comune.create(description: "Palmi", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 19435)
Comune.create(description: "Pazzano", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 799)
Comune.create(description: "Placanica", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 1507)
Comune.create(description: "Polistena", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 11591)
Comune.create(description: "Portigliola", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 1343)
Comune.create(description: "Reggio Calabria", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 )
Comune.create(description: "Riace", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 1605)
Comune.create(description: "Rizziconi", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 7650)
Comune.create(description: "Roccaforte Del Greco", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 802)
Comune.create(description: "Roccella Ionica", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 6762)
Comune.create(description: "Roghudi", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 1365)
Comune.create(description: "Rosarno", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 15051)
Comune.create(description: "Samo", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 1097)
Comune.create(description: "San Ferdinando", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 4339)
Comune.create(description: "San Giorgio Morgeto", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 3384)
Comune.create(description: "San Giovanni Di Gerace", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 609)
Comune.create(description: "San Lorenzo", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 3357)
Comune.create(description: "San Luca", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 4106)
Comune.create(description: "San Procopio", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 617)
Comune.create(description: "San Roberto", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 1985)
Comune.create(description: "Santo Stefano In Aspromonte", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 1470)
Comune.create(description: "Scido", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 1047)
Comune.create(description: "Scilla", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 5176)
Comune.create(description: "Seminara", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 3352)
Comune.create(description: "Serrata", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 964)
Comune.create(description: "Siderno", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 16734)
Comune.create(description: "Sinopoli", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 2329)
Comune.create(description: "Staiti", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 395)
Comune.create(description: "Stignano", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 1373)
Comune.create(description: "Stilo", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 2816)
Comune.create(description: "Taurianova", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 15799)
Comune.create(description: "Terranova Sappo Minulio", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 537)
Comune.create(description: "Varapodio", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 2329)
Comune.create(description: "Villa San Giovanni", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 13119)
Comune.create(description: "Cimina'", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 683)
Comune.create(description: "Melicucca'", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 1079)
Comune.create(description: "Plati'", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 3823)
Comune.create(description: "San Pietro Di Carida'", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 1715)
Comune.create(description: "Santa Cristina D'Aspromonte", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 1095)
Comune.create(description: "Sant'Agata Del Bianco", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 715)
Comune.create(description: "Sant'Alessio In Aspromonte", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 436)
Comune.create(description: "Sant'Eufemia D'Aspromonte", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 4074)
Comune.create(description: "Sant'Ilario Dello Ionio", provincia_id: 24, region_id:  7, country_id: 1, continent_id: 1 , population: 1389)
