Comune.create(description: "Acquaro", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 3046)
Comune.create(description: "Arena", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 1799)
Comune.create(description: "Briatico", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 4106)
Comune.create(description: "Brognaturo", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 766)
Comune.create(description: "Capistrano", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 1205)
Comune.create(description: "Cessaniti", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 3647)
Comune.create(description: "Dinami", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 3544)
Comune.create(description: "Drapia", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 2193)
Comune.create(description: "Fabrizia", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 2698)
Comune.create(description: "Filadelfia", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 6283)
Comune.create(description: "Filandari", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 1839)
Comune.create(description: "Filogaso", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 1377)
Comune.create(description: "Francavilla Angitola", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 2354)
Comune.create(description: "Francica", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 1670)
Comune.create(description: "Gerocarne", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 2498)
Comune.create(description: "Ionadi", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 2662)
Comune.create(description: "Joppolo", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 2274)
Comune.create(description: "Limbadi", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 3630)
Comune.create(description: "Maierato", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 2256)
Comune.create(description: "Mileto", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 7157)
Comune.create(description: "Mongiana", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 881)
Comune.create(description: "Monterosso Calabro", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 2017)
Comune.create(description: "Nardodipace", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 1477)
Comune.create(description: "Nicotera", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 6778)
Comune.create(description: "Parghelia", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 1377)
Comune.create(description: "Pizzo", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 8602)
Comune.create(description: "Pizzoni", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 1364)
Comune.create(description: "Polia", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 1319)
Comune.create(description: "Ricadi", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 4429)
Comune.create(description: "Rombiolo", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 4730)
Comune.create(description: "San Calogero", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 4649)
Comune.create(description: "San Costantino Calabro", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 2308)
Comune.create(description: "San Nicola Da Crissa", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 1599)
Comune.create(description: "Serra San Bruno", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 7068)
Comune.create(description: "Simbario", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 1082)
Comune.create(description: "Sorianello", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 1589)
Comune.create(description: "Soriano Calabro", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 3068)
Comune.create(description: "Spadola", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 819)
Comune.create(description: "Spilinga", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 1609)
Comune.create(description: "Stefanaconi", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 2497)
Comune.create(description: "Tropea", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 6836)
Comune.create(description: "Vallelonga", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 759)
Comune.create(description: "Vazzano", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 1231)
Comune.create(description: "Vibo Valentia", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 33957)
Comune.create(description: "Zaccanopoli", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 888)
Comune.create(description: "Zambrone", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 1743)
Comune.create(description: "Zungri", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 2182)
Comune.create(description: "Dasa'", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 1308)
Comune.create(description: "San Gregorio D'Ippona", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 2338)
Comune.create(description: "Sant'Onofrio", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 3238)
