Municipality.create(description: "Acquaro", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 3046)
Municipality.create(description: "Arena", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 1799)
Municipality.create(description: "Briatico", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 4106)
Municipality.create(description: "Brognaturo", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 766)
Municipality.create(description: "Capistrano", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 1205)
Municipality.create(description: "Cessaniti", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 3647)
Municipality.create(description: "Dinami", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 3544)
Municipality.create(description: "Drapia", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 2193)
Municipality.create(description: "Fabrizia", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 2698)
Municipality.create(description: "Filadelfia", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 6283)
Municipality.create(description: "Filandari", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 1839)
Municipality.create(description: "Filogaso", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 1377)
Municipality.create(description: "Francavilla Angitola", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 2354)
Municipality.create(description: "Francica", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 1670)
Municipality.create(description: "Gerocarne", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 2498)
Municipality.create(description: "Ionadi", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 2662)
Municipality.create(description: "Joppolo", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 2274)
Municipality.create(description: "Limbadi", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 3630)
Municipality.create(description: "Maierato", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 2256)
Municipality.create(description: "Mileto", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 7157)
Municipality.create(description: "Mongiana", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 881)
Municipality.create(description: "Monterosso Calabro", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 2017)
Municipality.create(description: "Nardodipace", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 1477)
Municipality.create(description: "Nicotera", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 6778)
Municipality.create(description: "Parghelia", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 1377)
Municipality.create(description: "Pizzo", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 8602)
Municipality.create(description: "Pizzoni", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 1364)
Municipality.create(description: "Polia", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 1319)
Municipality.create(description: "Ricadi", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 4429)
Municipality.create(description: "Rombiolo", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 4730)
Municipality.create(description: "San Calogero", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 4649)
Municipality.create(description: "San Costantino Calabro", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 2308)
Municipality.create(description: "San Nicola Da Crissa", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 1599)
Municipality.create(description: "Serra San Bruno", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 7068)
Municipality.create(description: "Simbario", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 1082)
Municipality.create(description: "Sorianello", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 1589)
Municipality.create(description: "Soriano Calabro", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 3068)
Municipality.create(description: "Spadola", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 819)
Municipality.create(description: "Spilinga", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 1609)
Municipality.create(description: "Stefanaconi", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 2497)
Municipality.create(description: "Tropea", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 6836)
Municipality.create(description: "Vallelonga", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 759)
Municipality.create(description: "Vazzano", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 1231)
Municipality.create(description: "Vibo Valentia", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 33957)
Municipality.create(description: "Zaccanopoli", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 888)
Municipality.create(description: "Zambrone", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 1743)
Municipality.create(description: "Zungri", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 2182)
Municipality.create(description: "Dasa'", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 1308)
Municipality.create(description: "San Gregorio D'Ippona", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 2338)
Municipality.create(description: "Sant'Onofrio", province_id: 25, region_id:  7, country_id: 1, continent_id: 1 , population: 3238)
