Municipality.create(description: "Accettura", province_id: 27, region_id:  3, country_id: 1, continent_id: 1 , population: 2436)
Municipality.create(description: "Aliano", province_id: 27, region_id:  3, country_id: 1, continent_id: 1 , population: 1284)
Municipality.create(description: "Bernalda", province_id: 27, region_id:  3, country_id: 1, continent_id: 1 , population: 11958)
Municipality.create(description: "Calciano", province_id: 27, region_id:  3, country_id: 1, continent_id: 1 , population: 893)
Municipality.create(description: "Cirigliano", province_id: 27, region_id:  3, country_id: 1, continent_id: 1 , population: 445)
Municipality.create(description: "Colobraro", province_id: 27, region_id:  3, country_id: 1, continent_id: 1 , population: 1535)
Municipality.create(description: "Craco", province_id: 27, region_id:  3, country_id: 1, continent_id: 1 , population: 796)
Municipality.create(description: "Ferrandina", province_id: 27, region_id:  3, country_id: 1, continent_id: 1 , population: 9358)
Municipality.create(description: "Garaguso", province_id: 27, region_id:  3, country_id: 1, continent_id: 1 , population: 1193)
Municipality.create(description: "Gorgoglione", province_id: 27, region_id:  3, country_id: 1, continent_id: 1 , population: 1179)
Municipality.create(description: "Grassano", province_id: 27, region_id:  3, country_id: 1, continent_id: 1 , population: 5792)
Municipality.create(description: "Grottole", province_id: 27, region_id:  3, country_id: 1, continent_id: 1 , population: 2607)
Municipality.create(description: "Irsina", province_id: 27, region_id:  3, country_id: 1, continent_id: 1 , population: 5732)
Municipality.create(description: "Matera", province_id: 27, region_id:  3, country_id: 1, continent_id: 1 , population: 57785)
Municipality.create(description: "Miglionico", province_id: 27, region_id:  3, country_id: 1, continent_id: 1 , population: 2630)
Municipality.create(description: "Montalbano Jonico", province_id: 27, region_id:  3, country_id: 1, continent_id: 1 , population: 7991)
Municipality.create(description: "Montescaglioso", province_id: 27, region_id:  3, country_id: 1, continent_id: 1 , population: 10121)
Municipality.create(description: "Nova Siri", province_id: 27, region_id:  3, country_id: 1, continent_id: 1 , population: 6418)
Municipality.create(description: "Oliveto Lucano", province_id: 27, region_id:  3, country_id: 1, continent_id: 1 , population: 587)
Municipality.create(description: "Pisticci", province_id: 27, region_id:  3, country_id: 1, continent_id: 1 , population: 17811)
Municipality.create(description: "Policoro", province_id: 27, region_id:  3, country_id: 1, continent_id: 1 , population: 15096)
Municipality.create(description: "Pomarico", province_id: 27, region_id:  3, country_id: 1, continent_id: 1 , population: 4482)
Municipality.create(description: "Rotondella", province_id: 27, region_id:  3, country_id: 1, continent_id: 1 , population: 3233)
Municipality.create(description: "Salandra", province_id: 27, region_id:  3, country_id: 1, continent_id: 1 , population: 3109)
Municipality.create(description: "San Giorgio Lucano", province_id: 27, region_id:  3, country_id: 1, continent_id: 1 , population: 1510)
Municipality.create(description: "San Mauro Forte", province_id: 27, region_id:  3, country_id: 1, continent_id: 1 , population: 2306)
Municipality.create(description: "Scanzano Jonico", province_id: 27, region_id:  3, country_id: 1, continent_id: 1 , population: 6711)
Municipality.create(description: "Stigliano", province_id: 27, region_id:  3, country_id: 1, continent_id: 1 , population: 5616)
Municipality.create(description: "Tricarico", province_id: 27, region_id:  3, country_id: 1, continent_id: 1 , population: 6318)
Municipality.create(description: "Tursi", province_id: 27, region_id:  3, country_id: 1, continent_id: 1 , population: 5510)
Municipality.create(description: "Valsinni", province_id: 27, region_id:  3, country_id: 1, continent_id: 1 , population: 1797)
