#encoding: utf-8
Comune.create(:description => "Accettura", :provincia_id => 27, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 2436)
Comune.create(:description => "Aliano", :provincia_id => 27, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 1284)
Comune.create(:description => "Bernalda", :provincia_id => 27, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 11958)
Comune.create(:description => "Calciano", :provincia_id => 27, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 893)
Comune.create(:description => "Cirigliano", :provincia_id => 27, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 445)
Comune.create(:description => "Colobraro", :provincia_id => 27, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 1535)
Comune.create(:description => "Craco", :provincia_id => 27, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 796)
Comune.create(:description => "Ferrandina", :provincia_id => 27, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 9358)
Comune.create(:description => "Garaguso", :provincia_id => 27, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 1193)
Comune.create(:description => "Gorgoglione", :provincia_id => 27, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 1179)
Comune.create(:description => "Grassano", :provincia_id => 27, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 5792)
Comune.create(:description => "Grottole", :provincia_id => 27, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 2607)
Comune.create(:description => "Irsina", :provincia_id => 27, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 5732)
Comune.create(:description => "Matera", :provincia_id => 27, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 57785)
Comune.create(:description => "Miglionico", :provincia_id => 27, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 2630)
Comune.create(:description => "Montalbano Jonico", :provincia_id => 27, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 7991)
Comune.create(:description => "Montescaglioso", :provincia_id => 27, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 10121)
Comune.create(:description => "Nova Siri", :provincia_id => 27, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 6418)
Comune.create(:description => "Oliveto Lucano", :provincia_id => 27, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 587)
Comune.create(:description => "Pisticci", :provincia_id => 27, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 17811)
Comune.create(:description => "Policoro", :provincia_id => 27, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 15096)
Comune.create(:description => "Pomarico", :provincia_id => 27, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 4482)
Comune.create(:description => "Rotondella", :provincia_id => 27, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 3233)
Comune.create(:description => "Salandra", :provincia_id => 27, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 3109)
Comune.create(:description => "San Giorgio Lucano", :provincia_id => 27, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 1510)
Comune.create(:description => "San Mauro Forte", :provincia_id => 27, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 2306)
Comune.create(:description => "Scanzano Jonico", :provincia_id => 27, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 6711)
Comune.create(:description => "Stigliano", :provincia_id => 27, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 5616)
Comune.create(:description => "Tricarico", :provincia_id => 27, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 6318)
Comune.create(:description => "Tursi", :provincia_id => 27, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 5510)
Comune.create(:description => "Valsinni", :provincia_id => 27, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 1797)
