Municipality.create(description: "Abriola", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 1808)
Municipality.create(description: "Acerenza", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 3010)
Municipality.create(description: "Albano Di Lucania", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 1612)
Municipality.create(description: "Anzi", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 1949)
Municipality.create(description: "Armento", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 800)
Municipality.create(description: "Atella", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 3726)
Municipality.create(description: "Avigliano", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 12025)
Municipality.create(description: "Balvano", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 2007)
Municipality.create(description: "Banzi", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 1514)
Municipality.create(description: "Baragiano", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 2751)
Municipality.create(description: "Barile", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 3229)
Municipality.create(description: "Bella", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 5440)
Municipality.create(description: "Brienza", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 4067)
Municipality.create(description: "Brindisi Di Montagna", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 )
Municipality.create(description: "Calvello", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 2212)
Municipality.create(description: "Calvera", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 584)
Municipality.create(description: "Campomaggiore", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 980)
Municipality.create(description: "Cancellara", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 1598)
Municipality.create(description: "Carbone", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 853)
Municipality.create(description: "Castelgrande", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 1231)
Municipality.create(description: "Castelluccio Inferiore", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 2344)
Municipality.create(description: "Castelluccio Superiore", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 987)
Municipality.create(description: "Castelmezzano", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 970)
Municipality.create(description: "Castelsaraceno", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 1730)
Municipality.create(description: "Cersosimo", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 847)
Municipality.create(description: "Chiaromonte", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 2148)
Municipality.create(description: "Corleto Perticara", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 3018)
Municipality.create(description: "Episcopia", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 1625)
Municipality.create(description: "Fardella", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 765)
Municipality.create(description: "Filiano", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 3298)
Municipality.create(description: "Forenza", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 2546)
Municipality.create(description: "Francavilla In Sinni", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 4367)
Municipality.create(description: "Gallicchio", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 1018)
Municipality.create(description: "Genzano Di Lucania", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 6115)
Municipality.create(description: "Ginestra", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 726)
Municipality.create(description: "Grumento Nova", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 1839)
Municipality.create(description: "Guardia Perticara", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 758)
Municipality.create(description: "Lagonegro", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 6146)
Municipality.create(description: "Latronico", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 5279)
Municipality.create(description: "Laurenzana", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 2250)
Municipality.create(description: "Lauria", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 13801)
Municipality.create(description: "Lavello", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 13247)
Municipality.create(description: "Maratea", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 5261)
Municipality.create(description: "Marsico Nuovo", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 5134)
Municipality.create(description: "Marsicovetere", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 4703)
Municipality.create(description: "Maschito", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 1864)
Municipality.create(description: "Melfi", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 16110)
Municipality.create(description: "Missanello", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 604)
Municipality.create(description: "Moliterno", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 4592)
Municipality.create(description: "Montemilone", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 2000)
Municipality.create(description: "Montemurro", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 1555)
Municipality.create(description: "Muro Lucano", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 6110)
Municipality.create(description: "Nemoli", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 1561)
Municipality.create(description: "Noepoli", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 1189)
Municipality.create(description: "Oppido Lucano", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 3968)
Municipality.create(description: "Palazzo San Gervasio", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 5184)
Municipality.create(description: "Paterno", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 3994)
Municipality.create(description: "Pescopagano", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 2147)
Municipality.create(description: "Picerno", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 6186)
Municipality.create(description: "Pietragalla", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 4534)
Municipality.create(description: "Pietrapertosa", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 1312)
Municipality.create(description: "Pignola", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 5483)
Municipality.create(description: "Potenza", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 69060)
Municipality.create(description: "Rapolla", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 4648)
Municipality.create(description: "Rapone", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 1203)
Municipality.create(description: "Rionero In Vulture", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 13441)
Municipality.create(description: "Ripacandida", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 1767)
Municipality.create(description: "Rivello", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 3010)
Municipality.create(description: "Roccanova", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 1759)
Municipality.create(description: "Rotonda", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 3888)
Municipality.create(description: "Ruoti", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 3687)
Municipality.create(description: "Ruvo Del Monte", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 1262)
Municipality.create(description: "San Chirico Nuovo", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 1632)
Municipality.create(description: "San Chirico Raparo", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 1304)
Municipality.create(description: "San Costantino Albanese", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 884)
Municipality.create(description: "San Fele", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 3832)
Municipality.create(description: "San Paolo Albanese", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 416)
Municipality.create(description: "San Severino Lucano", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 1923)
Municipality.create(description: "Sarconi", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 1351)
Municipality.create(description: "Sasso Di Castalda", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 871)
Municipality.create(description: "Satriano Di Lucania", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 2353)
Municipality.create(description: "Savoia Di Lucania", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 1236)
Municipality.create(description: "Senise", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 7182)
Municipality.create(description: "Spinoso", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 1778)
Municipality.create(description: "Teana", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 750)
Municipality.create(description: "Terranova Di Pollino", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 1534)
Municipality.create(description: "Tito", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 6387)
Municipality.create(description: "Tolve", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 3620)
Municipality.create(description: "Tramutola", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 3251)
Municipality.create(description: "Trecchina", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 2404)
Municipality.create(description: "Trivigno", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 794)
Municipality.create(description: "Vaglio Basilicata", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 2217)
Municipality.create(description: "Venosa", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 12148)
Municipality.create(description: "Vietri Di Potenza", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 3096)
Municipality.create(description: "Viggianello", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 3500)
Municipality.create(description: "Viggiano", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 3208)
Municipality.create(description: "Castronuovo Di Sant'Andrea", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 1439)
Municipality.create(description: "San Martino D'Agri", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 969)
Municipality.create(description: "Sant'Angelo Le Fratte", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 1472)
Municipality.create(description: "Sant'Arcangelo", province_id: 28, region_id:  3, country_id: 1, continent_id: 1 , population: 6637)
