#encoding: utf-8
Comune.create(:description => "Abriola", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 1808)
Comune.create(:description => "Acerenza", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 3010)
Comune.create(:description => "Albano Di Lucania", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 1612)
Comune.create(:description => "Anzi", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 1949)
Comune.create(:description => "Armento", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 800)
Comune.create(:description => "Atella", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 3726)
Comune.create(:description => "Avigliano", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 12025)
Comune.create(:description => "Balvano", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 2007)
Comune.create(:description => "Banzi", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 1514)
Comune.create(:description => "Baragiano", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 2751)
Comune.create(:description => "Barile", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 3229)
Comune.create(:description => "Bella", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 5440)
Comune.create(:description => "Brienza", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 4067)
Comune.create(:description => "Brindisi Di Montagna", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 )
Comune.create(:description => "Calvello", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 2212)
Comune.create(:description => "Calvera", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 584)
Comune.create(:description => "Campomaggiore", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 980)
Comune.create(:description => "Cancellara", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 1598)
Comune.create(:description => "Carbone", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 853)
Comune.create(:description => "Castelgrande", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 1231)
Comune.create(:description => "Castelluccio Inferiore", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 2344)
Comune.create(:description => "Castelluccio Superiore", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 987)
Comune.create(:description => "Castelmezzano", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 970)
Comune.create(:description => "Castelsaraceno", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 1730)
Comune.create(:description => "Cersosimo", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 847)
Comune.create(:description => "Chiaromonte", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 2148)
Comune.create(:description => "Corleto Perticara", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 3018)
Comune.create(:description => "Episcopia", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 1625)
Comune.create(:description => "Fardella", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 765)
Comune.create(:description => "Filiano", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 3298)
Comune.create(:description => "Forenza", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 2546)
Comune.create(:description => "Francavilla In Sinni", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 4367)
Comune.create(:description => "Gallicchio", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 1018)
Comune.create(:description => "Genzano Di Lucania", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 6115)
Comune.create(:description => "Ginestra", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 726)
Comune.create(:description => "Grumento Nova", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 1839)
Comune.create(:description => "Guardia Perticara", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 758)
Comune.create(:description => "Lagonegro", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 6146)
Comune.create(:description => "Latronico", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 5279)
Comune.create(:description => "Laurenzana", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 2250)
Comune.create(:description => "Lauria", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 13801)
Comune.create(:description => "Lavello", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 13247)
Comune.create(:description => "Maratea", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 5261)
Comune.create(:description => "Marsico Nuovo", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 5134)
Comune.create(:description => "Marsicovetere", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 4703)
Comune.create(:description => "Maschito", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 1864)
Comune.create(:description => "Melfi", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 16110)
Comune.create(:description => "Missanello", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 604)
Comune.create(:description => "Moliterno", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 4592)
Comune.create(:description => "Montemilone", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 2000)
Comune.create(:description => "Montemurro", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 1555)
Comune.create(:description => "Muro Lucano", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 6110)
Comune.create(:description => "Nemoli", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 1561)
Comune.create(:description => "Noepoli", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 1189)
Comune.create(:description => "Oppido Lucano", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 3968)
Comune.create(:description => "Palazzo San Gervasio", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 5184)
Comune.create(:description => "Paterno", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 3994)
Comune.create(:description => "Pescopagano", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 2147)
Comune.create(:description => "Picerno", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 6186)
Comune.create(:description => "Pietragalla", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 4534)
Comune.create(:description => "Pietrapertosa", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 1312)
Comune.create(:description => "Pignola", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 5483)
Comune.create(:description => "Potenza", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 69060)
Comune.create(:description => "Rapolla", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 4648)
Comune.create(:description => "Rapone", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 1203)
Comune.create(:description => "Rionero In Vulture", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 13441)
Comune.create(:description => "Ripacandida", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 1767)
Comune.create(:description => "Rivello", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 3010)
Comune.create(:description => "Roccanova", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 1759)
Comune.create(:description => "Rotonda", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 3888)
Comune.create(:description => "Ruoti", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 3687)
Comune.create(:description => "Ruvo Del Monte", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 1262)
Comune.create(:description => "San Chirico Nuovo", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 1632)
Comune.create(:description => "San Chirico Raparo", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 1304)
Comune.create(:description => "San Costantino Albanese", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 884)
Comune.create(:description => "San Fele", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 3832)
Comune.create(:description => "San Paolo Albanese", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 416)
Comune.create(:description => "San Severino Lucano", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 1923)
Comune.create(:description => "Sarconi", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 1351)
Comune.create(:description => "Sasso Di Castalda", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 871)
Comune.create(:description => "Satriano Di Lucania", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 2353)
Comune.create(:description => "Savoia Di Lucania", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 1236)
Comune.create(:description => "Senise", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 7182)
Comune.create(:description => "Spinoso", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 1778)
Comune.create(:description => "Teana", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 750)
Comune.create(:description => "Terranova Di Pollino", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 1534)
Comune.create(:description => "Tito", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 6387)
Comune.create(:description => "Tolve", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 3620)
Comune.create(:description => "Tramutola", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 3251)
Comune.create(:description => "Trecchina", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 2404)
Comune.create(:description => "Trivigno", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 794)
Comune.create(:description => "Vaglio Basilicata", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 2217)
Comune.create(:description => "Venosa", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 12148)
Comune.create(:description => "Vietri Di Potenza", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 3096)
Comune.create(:description => "Viggianello", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 3500)
Comune.create(:description => "Viggiano", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 3208)
Comune.create(:description => "Castronuovo Di Sant'Andrea", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 1439)
Comune.create(:description => "San Martino D'Agri", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 969)
Comune.create(:description => "Sant'Angelo Le Fratte", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 1472)
Comune.create(:description => "Sant'Arcangelo", :provincia_id => 28, :regione_id => 3, stato_id: 1, continente_id: 1 , :population => 6637)
