Municipality.create(description: "Acquaviva Delle Fonti", province_id: 29, region_id:  6, country_id: 1, continent_id: 1 , population: 21613)
Municipality.create(description: "Adelfia", province_id: 29, region_id:  6, country_id: 1, continent_id: 1 , population: 16245)
Municipality.create(description: "Alberobello", province_id: 29, region_id:  6, country_id: 1, continent_id: 1 , population: 10859)
Municipality.create(description: "Altamura", province_id: 29, region_id:  6, country_id: 1, continent_id: 1 , population: 64167)
Municipality.create(description: "Andria", province_id: 29, region_id:  6, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Bari", province_id: 29, region_id:  6, country_id: 1, continent_id: 1 , population: 316532)
Municipality.create(description: "Barletta", province_id: 29, region_id:  6, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Binetto", province_id: 29, region_id:  6, country_id: 1, continent_id: 1 , population: 1934)
Municipality.create(description: "Bisceglie", province_id: 29, region_id:  6, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Bitetto", province_id: 29, region_id:  6, country_id: 1, continent_id: 1 , population: 10153)
Municipality.create(description: "Bitonto", province_id: 29, region_id:  6, country_id: 1, continent_id: 1 , population: 56929)
Municipality.create(description: "Bitritto", province_id: 29, region_id:  6, country_id: 1, continent_id: 1 , population: 9827)
Municipality.create(description: "Canosa Di Puglia", province_id: 29, region_id:  6, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Capurso", province_id: 29, region_id:  6, country_id: 1, continent_id: 1 , population: 14376)
Municipality.create(description: "Casamassima", province_id: 29, region_id:  6, country_id: 1, continent_id: 1 , population: 16734)
Municipality.create(description: "Cassano Delle Murge", province_id: 29, region_id:  6, country_id: 1, continent_id: 1 , population: 11958)
Municipality.create(description: "Castellana Grotte", province_id: 29, region_id:  6, country_id: 1, continent_id: 1 , population: 18276)
Municipality.create(description: "Cellamare", province_id: 29, region_id:  6, country_id: 1, continent_id: 1 , population: 4683)
Municipality.create(description: "Conversano", province_id: 29, region_id:  6, country_id: 1, continent_id: 1 , population: 24071)
Municipality.create(description: "Corato", province_id: 29, region_id:  6, country_id: 1, continent_id: 1 , population: 44971)
Municipality.create(description: "Gioia Del Colle", province_id: 29, region_id:  6, country_id: 1, continent_id: 1 , population: 27655)
Municipality.create(description: "Giovinazzo", province_id: 29, region_id:  6, country_id: 1, continent_id: 1 , population: 20300)
Municipality.create(description: "Gravina In Puglia", province_id: 29, region_id:  6, country_id: 1, continent_id: 1 , population: 42154)
Municipality.create(description: "Grumo Appula", province_id: 29, region_id:  6, country_id: 1, continent_id: 1 , population: 12431)
Municipality.create(description: "Locorotondo", province_id: 29, region_id:  6, country_id: 1, continent_id: 1 , population: 13928)
Municipality.create(description: "Minervino Murge", province_id: 29, region_id:  6, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Modugno", province_id: 29, region_id:  6, country_id: 1, continent_id: 1 , population: 35980)
Municipality.create(description: "Mola Di Bari", province_id: 29, region_id:  6, country_id: 1, continent_id: 1 , population: 25919)
Municipality.create(description: "Molfetta", province_id: 29, region_id:  6, country_id: 1, continent_id: 1 , population: 62546)
Municipality.create(description: "Monopoli", province_id: 29, region_id:  6, country_id: 1, continent_id: 1 , population: 46708)
Municipality.create(description: "Noci", province_id: 29, region_id:  6, country_id: 1, continent_id: 1 , population: 19564)
Municipality.create(description: "Noicattaro", province_id: 29, region_id:  6, country_id: 1, continent_id: 1 , population: 23686)
Municipality.create(description: "Palo Del Colle", province_id: 29, region_id:  6, country_id: 1, continent_id: 1 , population: 20852)
Municipality.create(description: "Poggiorsini", province_id: 29, region_id:  6, country_id: 1, continent_id: 1 , population: 1517)
Municipality.create(description: "Polignano A Mare", province_id: 29, region_id:  6, country_id: 1, continent_id: 1 , population: 16367)
Municipality.create(description: "Putignano", province_id: 29, region_id:  6, country_id: 1, continent_id: 1 , population: 28176)
Municipality.create(description: "Rutigliano", province_id: 29, region_id:  6, country_id: 1, continent_id: 1 , population: 17559)
Municipality.create(description: "Ruvo Di Puglia", province_id: 29, region_id:  6, country_id: 1, continent_id: 1 , population: 25741)
Municipality.create(description: "Sammichele Di Bari", province_id: 29, region_id:  6, country_id: 1, continent_id: 1 , population: 6965)
Municipality.create(description: "Sannicandro Di Bari", province_id: 29, region_id:  6, country_id: 1, continent_id: 1 , population: 9369)
Municipality.create(description: "Santeramo In Colle", province_id: 29, region_id:  6, country_id: 1, continent_id: 1 , population: 26050)
Municipality.create(description: "Spinazzola", province_id: 29, region_id:  6, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Terlizzi", province_id: 29, region_id:  6, country_id: 1, continent_id: 1 , population: 27532)
Municipality.create(description: "Toritto", province_id: 29, region_id:  6, country_id: 1, continent_id: 1 , population: 8916)
Municipality.create(description: "Trani", province_id: 29, region_id:  6, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Triggiano", province_id: 29, region_id:  6, country_id: 1, continent_id: 1 , population: 26312)
Municipality.create(description: "Turi", province_id: 29, region_id:  6, country_id: 1, continent_id: 1 , population: 11319)
Municipality.create(description: "Valenzano", province_id: 29, region_id:  6, country_id: 1, continent_id: 1 , population: 17164)
