Comune.create(description: "Brindisi", province_id: 30, region_id:  6, country_id: 1, continent_id: 1 , population: 89081)
Comune.create(description: "Carovigno", province_id: 30, region_id:  6, country_id: 1, continent_id: 1 , population: 14960)
Comune.create(description: "Ceglie Messapica", province_id: 30, region_id:  6, country_id: 1, continent_id: 1 , population: 21370)
Comune.create(description: "Cellino San Marco", province_id: 30, region_id:  6, country_id: 1, continent_id: 1 , population: 6818)
Comune.create(description: "Cisternino", province_id: 30, region_id:  6, country_id: 1, continent_id: 1 , population: 12078)
Comune.create(description: "Erchie", province_id: 30, region_id:  6, country_id: 1, continent_id: 1 , population: 8740)
Comune.create(description: "Fasano", province_id: 30, region_id:  6, country_id: 1, continent_id: 1 , population: 38667)
Comune.create(description: "Francavilla Fontana", province_id: 30, region_id:  6, country_id: 1, continent_id: 1 , population: 36274)
Comune.create(description: "Latiano", province_id: 30, region_id:  6, country_id: 1, continent_id: 1 , population: 15371)
Comune.create(description: "Mesagne", province_id: 30, region_id:  6, country_id: 1, continent_id: 1 , population: 27587)
Comune.create(description: "Oria", province_id: 30, region_id:  6, country_id: 1, continent_id: 1 , population: 15209)
Comune.create(description: "Ostuni", province_id: 30, region_id:  6, country_id: 1, continent_id: 1 , population: 32901)
Comune.create(description: "San Donaci", province_id: 30, region_id:  6, country_id: 1, continent_id: 1 , population: 7117)
Comune.create(description: "San Michele Salentino", province_id: 30, region_id:  6, country_id: 1, continent_id: 1 , population: 6248)
Comune.create(description: "San Pancrazio Salentino", province_id: 30, region_id:  6, country_id: 1, continent_id: 1 , population: 10551)
Comune.create(description: "San Pietro Vernotico", province_id: 30, region_id:  6, country_id: 1, continent_id: 1 , population: 15004)
Comune.create(description: "San Vito Dei Normanni", province_id: 30, region_id:  6, country_id: 1, continent_id: 1 , population: 20070)
Comune.create(description: "Torchiarolo", province_id: 30, region_id:  6, country_id: 1, continent_id: 1 , population: 5127)
Comune.create(description: "Torre Santa Susanna", province_id: 30, region_id:  6, country_id: 1, continent_id: 1 , population: 10614)
Comune.create(description: "Villa Castelli", province_id: 30, region_id:  6, country_id: 1, continent_id: 1 , population: 8635)
