#encoding: utf-8
Comune.create(:description => "Brindisi", :provincia_id => 30, :regione_id => 6, :population => 89081)
Comune.create(:description => "Carovigno", :provincia_id => 30, :regione_id => 6, :population => 14960)
Comune.create(:description => "Ceglie Messapica", :provincia_id => 30, :regione_id => 6, :population => 21370)
Comune.create(:description => "Cellino San Marco", :provincia_id => 30, :regione_id => 6, :population => 6818)
Comune.create(:description => "Cisternino", :provincia_id => 30, :regione_id => 6, :population => 12078)
Comune.create(:description => "Erchie", :provincia_id => 30, :regione_id => 6, :population => 8740)
Comune.create(:description => "Fasano", :provincia_id => 30, :regione_id => 6, :population => 38667)
Comune.create(:description => "Francavilla Fontana", :provincia_id => 30, :regione_id => 6, :population => 36274)
Comune.create(:description => "Latiano", :provincia_id => 30, :regione_id => 6, :population => 15371)
Comune.create(:description => "Mesagne", :provincia_id => 30, :regione_id => 6, :population => 27587)
Comune.create(:description => "Oria", :provincia_id => 30, :regione_id => 6, :population => 15209)
Comune.create(:description => "Ostuni", :provincia_id => 30, :regione_id => 6, :population => 32901)
Comune.create(:description => "San Donaci", :provincia_id => 30, :regione_id => 6, :population => 7117)
Comune.create(:description => "San Michele Salentino", :provincia_id => 30, :regione_id => 6, :population => 6248)
Comune.create(:description => "San Pancrazio Salentino", :provincia_id => 30, :regione_id => 6, :population => 10551)
Comune.create(:description => "San Pietro Vernotico", :provincia_id => 30, :regione_id => 6, :population => 15004)
Comune.create(:description => "San Vito Dei Normanni", :provincia_id => 30, :regione_id => 6, :population => 20070)
Comune.create(:description => "Torchiarolo", :provincia_id => 30, :regione_id => 6, :population => 5127)
Comune.create(:description => "Torre Santa Susanna", :provincia_id => 30, :regione_id => 6, :population => 10614)
Comune.create(:description => "Villa Castelli", :provincia_id => 30, :regione_id => 6, :population => 8635)
