#encoding: utf-8
Comune.create(:description => "Acquacanina", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 139)
Comune.create(:description => "Apiro", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 2431)
Comune.create(:description => "Appignano", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 3904)
Comune.create(:description => "Belforte Del Chienti", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 1634)
Comune.create(:description => "Bolognola", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 155)
Comune.create(:description => "Caldarola", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 1706)
Comune.create(:description => "Camerino", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 6858)
Comune.create(:description => "Camporotondo Di Fiastrone", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 583)
Comune.create(:description => "Castelraimondo", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 4544)
Comune.create(:description => "Castelsantangelo Sul Nera", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 370)
Comune.create(:description => "Cessapalombo", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 585)
Comune.create(:description => "Cingoli", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 10118)
Comune.create(:description => "Civitanova Marche", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 38299)
Comune.create(:description => "Colmurano", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 1221)
Comune.create(:description => "Corridonia", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 13696)
Comune.create(:description => "Esanatoglia", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 2099)
Comune.create(:description => "Fiastra", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 613)
Comune.create(:description => "Fiordimonte", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 239)
Comune.create(:description => "Fiuminata", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 1604)
Comune.create(:description => "Gagliole", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 670)
Comune.create(:description => "Gualdo", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 920)
Comune.create(:description => "Loro Piceno", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 2485)
Comune.create(:description => "Macerata", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 40875)
Comune.create(:description => "Matelica", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 10155)
Comune.create(:description => "Mogliano", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 4831)
Comune.create(:description => "Monte Cavallo", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 171)
Comune.create(:description => "Monte San Giusto", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 7324)
Comune.create(:description => "Monte San Martino", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 820)
Comune.create(:description => "Montecassiano", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 6577)
Comune.create(:description => "Montecosaro", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 5198)
Comune.create(:description => "Montefano", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 3228)
Comune.create(:description => "Montelupone", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 3221)
Comune.create(:description => "Morrovalle", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 9226)
Comune.create(:description => "Muccia", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 907)
Comune.create(:description => "Penna San Giovanni", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 1302)
Comune.create(:description => "Petriolo", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 2049)
Comune.create(:description => "Pieve Torina", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 1379)
Comune.create(:description => "Pievebovigliana", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 879)
Comune.create(:description => "Pioraco", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 1231)
Comune.create(:description => "Poggio San Vicino", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 303)
Comune.create(:description => "Pollenza", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 5823)
Comune.create(:description => "Porto Recanati", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 9414)
Comune.create(:description => "Potenza Picena", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 14524)
Comune.create(:description => "Recanati", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 20050)
Comune.create(:description => "Ripe San Ginesio", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 758)
Comune.create(:description => "San Ginesio", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 3799)
Comune.create(:description => "San Severino Marche", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 12794)
Comune.create(:description => "Sarnano", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 3375)
Comune.create(:description => "Sefro", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 433)
Comune.create(:description => "Serrapetrona", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 894)
Comune.create(:description => "Serravalle Di Chienti", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 1153)
Comune.create(:description => "Tolentino", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 18649)
Comune.create(:description => "Treia", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 9449)
Comune.create(:description => "Urbisaglia", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 2760)
Comune.create(:description => "Ussita", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 426)
Comune.create(:description => "Visso", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 1177)
Comune.create(:description => "Sant'Angelo In Pontano", :provincia_id => 2, :regione_id => 1, stato_id: 1, continente_id: 1 , :population => 1496)
