Municipality.create(description: "Celle Di San Vito", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 )
Municipality.create(description: "Accadia", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 2702)
Municipality.create(description: "Alberona", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 1134)
Municipality.create(description: "Anzano Di Puglia", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 2239)
Municipality.create(description: "Apricena", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 13647)
Municipality.create(description: "Ascoli Satriano", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 6373)
Municipality.create(description: "Biccari", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 3070)
Municipality.create(description: "Bovino", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 3991)
Municipality.create(description: "Cagnano Varano", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 8617)
Municipality.create(description: "Candela", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 2823)
Municipality.create(description: "Carapelle", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 5905)
Municipality.create(description: "Carlantino", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 1294)
Municipality.create(description: "Carpino", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 4704)
Municipality.create(description: "Casalnuovo Monterotaro", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 1954)
Municipality.create(description: "Casalvecchio Di Puglia", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 2167)
Municipality.create(description: "Castelluccio Dei Sauri", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 1951)
Municipality.create(description: "Castelluccio Valmaggiore", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 1469)
Municipality.create(description: "Castelnuovo Della Daunia", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 1763)
Municipality.create(description: "Celenza Valfortore", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 1990)
Municipality.create(description: "Cerignola", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 57366)
Municipality.create(description: "Chieuti", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 1788)
Municipality.create(description: "Deliceto", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 4117)
Municipality.create(description: "Faeto", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 758)
Municipality.create(description: "Foggia", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 155203)
Municipality.create(description: "Ischitella", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 4562)
Municipality.create(description: "Isole Tremiti", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 367)
Municipality.create(description: "Lesina", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 6286)
Municipality.create(description: "Lucera", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 35162)
Municipality.create(description: "Manfredonia", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 57704)
Municipality.create(description: "Margherita Di Savoia", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Mattinata", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 6333)
Municipality.create(description: "Monteleone Di Puglia", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 1413)
Municipality.create(description: "Motta Montecorvino", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 951)
Municipality.create(description: "Ordona", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 2584)
Municipality.create(description: "Orsara Di Puglia", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 3313)
Municipality.create(description: "Orta Nova", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 17665)
Municipality.create(description: "Panni", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 976)
Municipality.create(description: "Peschici", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 4339)
Municipality.create(description: "Pietramontecorvino", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 2972)
Municipality.create(description: "Poggio Imperiale", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 2891)
Municipality.create(description: "Rignano Garganico", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 2309)
Municipality.create(description: "Rodi Garganico", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 3778)
Municipality.create(description: "Roseto Valfortore", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 1316)
Municipality.create(description: "San Ferdinando Di Puglia", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "San Giovanni Rotondo", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 26106)
Municipality.create(description: "San Marco In Lamis", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 15739)
Municipality.create(description: "San Marco La Catola", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 1515)
Municipality.create(description: "San Paolo Di Civitate", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 6119)
Municipality.create(description: "San Severo", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 55861)
Municipality.create(description: "Sannicandro Garganico", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 18074)
Municipality.create(description: "Serracapriola", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 4356)
Municipality.create(description: "Stornara", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 4739)
Municipality.create(description: "Stornarella", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 5032)
Municipality.create(description: "Torremaggiore", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 17021)
Municipality.create(description: "Trinitapoli", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Troia", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 7495)
Municipality.create(description: "Vico Del Gargano", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 8107)
Municipality.create(description: "Vieste", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 13430)
Municipality.create(description: "Volturara Appula", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 595)
Municipality.create(description: "Volturino", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 1992)
Municipality.create(description: "Zapponeta", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 3013)
Municipality.create(description: "Monte Sant'Angelo", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 13917)
Municipality.create(description: "Rocchetta Sant'Antonio", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 2034)
Municipality.create(description: "Sant'Agata Di Puglia", province_id: 31, region_id:  6, country_id: 1, continent_id: 1 , population: 2321)
