#encoding: utf-8
Comune.create(:description => "Celle Di San Vito", :provincia_id => 31, :regione_id => 6)
Comune.create(:description => "Accadia", :provincia_id => 31, :regione_id => 6, :population => 2702)
Comune.create(:description => "Alberona", :provincia_id => 31, :regione_id => 6, :population => 1134)
Comune.create(:description => "Anzano Di Puglia", :provincia_id => 31, :regione_id => 6, :population => 2239)
Comune.create(:description => "Apricena", :provincia_id => 31, :regione_id => 6, :population => 13647)
Comune.create(:description => "Ascoli Satriano", :provincia_id => 31, :regione_id => 6, :population => 6373)
Comune.create(:description => "Biccari", :provincia_id => 31, :regione_id => 6, :population => 3070)
Comune.create(:description => "Bovino", :provincia_id => 31, :regione_id => 6, :population => 3991)
Comune.create(:description => "Cagnano Varano", :provincia_id => 31, :regione_id => 6, :population => 8617)
Comune.create(:description => "Candela", :provincia_id => 31, :regione_id => 6, :population => 2823)
Comune.create(:description => "Carapelle", :provincia_id => 31, :regione_id => 6, :population => 5905)
Comune.create(:description => "Carlantino", :provincia_id => 31, :regione_id => 6, :population => 1294)
Comune.create(:description => "Carpino", :provincia_id => 31, :regione_id => 6, :population => 4704)
Comune.create(:description => "Casalnuovo Monterotaro", :provincia_id => 31, :regione_id => 6, :population => 1954)
Comune.create(:description => "Casalvecchio Di Puglia", :provincia_id => 31, :regione_id => 6, :population => 2167)
Comune.create(:description => "Castelluccio Dei Sauri", :provincia_id => 31, :regione_id => 6, :population => 1951)
Comune.create(:description => "Castelluccio Valmaggiore", :provincia_id => 31, :regione_id => 6, :population => 1469)
Comune.create(:description => "Castelnuovo Della Daunia", :provincia_id => 31, :regione_id => 6, :population => 1763)
Comune.create(:description => "Celenza Valfortore", :provincia_id => 31, :regione_id => 6, :population => 1990)
Comune.create(:description => "Cerignola", :provincia_id => 31, :regione_id => 6, :population => 57366)
Comune.create(:description => "Chieuti", :provincia_id => 31, :regione_id => 6, :population => 1788)
Comune.create(:description => "Deliceto", :provincia_id => 31, :regione_id => 6, :population => 4117)
Comune.create(:description => "Faeto", :provincia_id => 31, :regione_id => 6, :population => 758)
Comune.create(:description => "Foggia", :provincia_id => 31, :regione_id => 6, :population => 155203)
Comune.create(:description => "Ischitella", :provincia_id => 31, :regione_id => 6, :population => 4562)
Comune.create(:description => "Isole Tremiti", :provincia_id => 31, :regione_id => 6, :population => 367)
Comune.create(:description => "Lesina", :provincia_id => 31, :regione_id => 6, :population => 6286)
Comune.create(:description => "Lucera", :provincia_id => 31, :regione_id => 6, :population => 35162)
Comune.create(:description => "Manfredonia", :provincia_id => 31, :regione_id => 6, :population => 57704)
Comune.create(:description => "Margherita Di Savoia", :provincia_id => 31, :regione_id => 6, :population => 0)
Comune.create(:description => "Mattinata", :provincia_id => 31, :regione_id => 6, :population => 6333)
Comune.create(:description => "Monteleone Di Puglia", :provincia_id => 31, :regione_id => 6, :population => 1413)
Comune.create(:description => "Motta Montecorvino", :provincia_id => 31, :regione_id => 6, :population => 951)
Comune.create(:description => "Ordona", :provincia_id => 31, :regione_id => 6, :population => 2584)
Comune.create(:description => "Orsara Di Puglia", :provincia_id => 31, :regione_id => 6, :population => 3313)
Comune.create(:description => "Orta Nova", :provincia_id => 31, :regione_id => 6, :population => 17665)
Comune.create(:description => "Panni", :provincia_id => 31, :regione_id => 6, :population => 976)
Comune.create(:description => "Peschici", :provincia_id => 31, :regione_id => 6, :population => 4339)
Comune.create(:description => "Pietramontecorvino", :provincia_id => 31, :regione_id => 6, :population => 2972)
Comune.create(:description => "Poggio Imperiale", :provincia_id => 31, :regione_id => 6, :population => 2891)
Comune.create(:description => "Rignano Garganico", :provincia_id => 31, :regione_id => 6, :population => 2309)
Comune.create(:description => "Rodi Garganico", :provincia_id => 31, :regione_id => 6, :population => 3778)
Comune.create(:description => "Roseto Valfortore", :provincia_id => 31, :regione_id => 6, :population => 1316)
Comune.create(:description => "San Ferdinando Di Puglia", :provincia_id => 31, :regione_id => 6, :population => 0)
Comune.create(:description => "San Giovanni Rotondo", :provincia_id => 31, :regione_id => 6, :population => 26106)
Comune.create(:description => "San Marco In Lamis", :provincia_id => 31, :regione_id => 6, :population => 15739)
Comune.create(:description => "San Marco La Catola", :provincia_id => 31, :regione_id => 6, :population => 1515)
Comune.create(:description => "San Paolo Di Civitate", :provincia_id => 31, :regione_id => 6, :population => 6119)
Comune.create(:description => "San Severo", :provincia_id => 31, :regione_id => 6, :population => 55861)
Comune.create(:description => "Sannicandro Garganico", :provincia_id => 31, :regione_id => 6, :population => 18074)
Comune.create(:description => "Serracapriola", :provincia_id => 31, :regione_id => 6, :population => 4356)
Comune.create(:description => "Stornara", :provincia_id => 31, :regione_id => 6, :population => 4739)
Comune.create(:description => "Stornarella", :provincia_id => 31, :regione_id => 6, :population => 5032)
Comune.create(:description => "Torremaggiore", :provincia_id => 31, :regione_id => 6, :population => 17021)
Comune.create(:description => "Trinitapoli", :provincia_id => 31, :regione_id => 6, :population => 0)
Comune.create(:description => "Troia", :provincia_id => 31, :regione_id => 6, :population => 7495)
Comune.create(:description => "Vico Del Gargano", :provincia_id => 31, :regione_id => 6, :population => 8107)
Comune.create(:description => "Vieste", :provincia_id => 31, :regione_id => 6, :population => 13430)
Comune.create(:description => "Volturara Appula", :provincia_id => 31, :regione_id => 6, :population => 595)
Comune.create(:description => "Volturino", :provincia_id => 31, :regione_id => 6, :population => 1992)
Comune.create(:description => "Zapponeta", :provincia_id => 31, :regione_id => 6, :population => 3013)
Comune.create(:description => "Monte Sant'Angelo", :provincia_id => 31, :regione_id => 6, :population => 13917)
Comune.create(:description => "Rocchetta Sant'Antonio", :provincia_id => 31, :regione_id => 6, :population => 2034)
Comune.create(:description => "Sant'Agata Di Puglia", :provincia_id => 31, :regione_id => 6, :population => 2321)
