#encoding: utf-8
Comune.create(:description => "Agliano Terme", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 1697)
Comune.create(:description => "Albugnano", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 462)
Comune.create(:description => "Antignano", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 1007)
Comune.create(:description => "Aramengo", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 604)
Comune.create(:description => "Asti", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 71276)
Comune.create(:description => "Belveglio", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 320)
Comune.create(:description => "Berzano Di San Pietro", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 406)
Comune.create(:description => "Bruno", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 375)
Comune.create(:description => "Bubbio", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 935)
Comune.create(:description => "Calamandrana", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 1563)
Comune.create(:description => "Calliano", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Calosso", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 1264)
Comune.create(:description => "Camerano Casasco", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 494)
Comune.create(:description => "Canelli", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 10230)
Comune.create(:description => "Cantarana", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 839)
Comune.create(:description => "Capriglio", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 309)
Comune.create(:description => "Casorzo", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 687)
Comune.create(:description => "Cassinasco", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 592)
Comune.create(:description => "Castagnole Delle Lanze", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 3641)
Comune.create(:description => "Castagnole Monferrato", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 1234)
Comune.create(:description => "Castel Boglione", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 645)
Comune.create(:description => "Castel Rocchero", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 396)
Comune.create(:description => "Castellero", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 291)
Comune.create(:description => "Castelletto Molina", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 169)
Comune.create(:description => "Castello Di Annone", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 1767)
Comune.create(:description => "Castelnuovo Belbo", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 930)
Comune.create(:description => "Castelnuovo Calcea", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 779)
Comune.create(:description => "Castelnuovo Don Bosco", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 3038)
Comune.create(:description => "Cellarengo", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 605)
Comune.create(:description => "Celle Enomondo", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 460)
Comune.create(:description => "Cerro Tanaro", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 592)
Comune.create(:description => "Cessole", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 456)
Comune.create(:description => "Cinaglio", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 459)
Comune.create(:description => "Coazzolo", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 300)
Comune.create(:description => "Cocconato", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 1540)
Comune.create(:description => "Corsione", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 169)
Comune.create(:description => "Cortandone", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 290)
Comune.create(:description => "Cortanze", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 289)
Comune.create(:description => "Cortazzone", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 626)
Comune.create(:description => "Cortiglione", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 568)
Comune.create(:description => "Cossombrato", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 488)
Comune.create(:description => "Cunico", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 497)
Comune.create(:description => "Dusino San Michele", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 938)
Comune.create(:description => "Ferrere", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 1473)
Comune.create(:description => "Fontanile", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 542)
Comune.create(:description => "Frinco", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 690)
Comune.create(:description => "Grana", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 611)
Comune.create(:description => "Grazzano Badoglio", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 639)
Comune.create(:description => "Incisa Scapaccino", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 2031)
Comune.create(:description => "Loazzolo", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 380)
Comune.create(:description => "Maranzana", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 307)
Comune.create(:description => "Maretto", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 358)
Comune.create(:description => "Moasca", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 401)
Comune.create(:description => "Mombaldone", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 269)
Comune.create(:description => "Mombaruzzo", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 1163)
Comune.create(:description => "Mombercelli", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 2214)
Comune.create(:description => "Monale", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 892)
Comune.create(:description => "Monastero Bormida", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 970)
Comune.create(:description => "Moncalvo", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 3320)
Comune.create(:description => "Moncucco Torinese", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 811)
Comune.create(:description => "Mongardino", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 986)
Comune.create(:description => "Montabone", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 357)
Comune.create(:description => "Montafia", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 934)
Comune.create(:description => "Montaldo Scarampi", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 688)
Comune.create(:description => "Montemagno", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 1205)
Comune.create(:description => "Montiglio Monferrato", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Moransengo", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 230)
Comune.create(:description => "Nizza Monferrato", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 10019)
Comune.create(:description => "Olmo Gentile", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 104)
Comune.create(:description => "Passerano Marmorito", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 450)
Comune.create(:description => "Penango", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 538)
Comune.create(:description => "Piea", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 568)
Comune.create(:description => "Portacomaro", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 1992)
Comune.create(:description => "Quaranti", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 199)
Comune.create(:description => "Refrancore", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 1560)
Comune.create(:description => "Roatto", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 373)
Comune.create(:description => "Robella", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 562)
Comune.create(:description => "Roccaverano", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 529)
Comune.create(:description => "Rocchetta Palafea", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 406)
Comune.create(:description => "Rocchetta Tanaro", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 1410)
Comune.create(:description => "San Giorgio Scarampi", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 140)
Comune.create(:description => "San Martino Alfieri", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 704)
Comune.create(:description => "San Marzano Oliveto", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 1012)
Comune.create(:description => "San Paolo Solbrito", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 1059)
Comune.create(:description => "Scurzolengo", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 637)
Comune.create(:description => "Serole", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 163)
Comune.create(:description => "Sessame", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 285)
Comune.create(:description => "Settime", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 537)
Comune.create(:description => "Soglio", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 135)
Comune.create(:description => "Tigliole", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 1605)
Comune.create(:description => "Tonco", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 891)
Comune.create(:description => "Tonengo", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 192)
Comune.create(:description => "Vaglio Serra", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 298)
Comune.create(:description => "Valfenera", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 2128)
Comune.create(:description => "Vesime", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 678)
Comune.create(:description => "Viarigi", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 1003)
Comune.create(:description => "Villa San Secondo", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 384)
Comune.create(:description => "Vinchio", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 698)
Comune.create(:description => "Azzano D'Asti", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 371)
Comune.create(:description => "Baldichieri D'Asti", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 1009)
Comune.create(:description => "Buttigliera D'Asti", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 1996)
Comune.create(:description => "Castell'Alfero", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 2691)
Comune.create(:description => "Cerreto D'Asti", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 241)
Comune.create(:description => "Chiusano D'Asti", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 254)
Comune.create(:description => "Cisterna D'Asti", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 1241)
Comune.create(:description => "Costigliole D'Asti", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 5882)
Comune.create(:description => "Isola D'Asti", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 2041)
Comune.create(:description => "Montechiaro D'Asti", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 1382)
Comune.create(:description => "Montegrosso D'Asti", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 2084)
Comune.create(:description => "Pino D'Asti", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 226)
Comune.create(:description => "Piova' Massaia", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 640)
Comune.create(:description => "Revigliasco D'Asti", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 859)
Comune.create(:description => "Rocca D'Arazzo", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 941)
Comune.create(:description => "San Damiano D'Asti", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 7622)
Comune.create(:description => "Viale D'Asti", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 267)
Comune.create(:description => "Vigliano D'Asti", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 823)
Comune.create(:description => "Villafranca D'Asti", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 2942)
Comune.create(:description => "Villanova D'Asti", :provincia_id => 6, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 4717)
