Comune.create(description: "Airola", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 7622)
Comune.create(description: "Amorosi", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 2761)
Comune.create(description: "Apice", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 5666)
Comune.create(description: "Apollosa", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 2750)
Comune.create(description: "Arpaia", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 1880)
Comune.create(description: "Arpaise", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 863)
Comune.create(description: "Baselice", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 2843)
Comune.create(description: "Benevento", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 61791)
Comune.create(description: "Bonea", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 1510)
Comune.create(description: "Bucciano", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 1894)
Comune.create(description: "Buonalbergo", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 1938)
Comune.create(description: "Calvi", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 2348)
Comune.create(description: "Campolattaro", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 1135)
Comune.create(description: "Campoli Del Monte Taburno", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 1515)
Comune.create(description: "Casalduni", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 1602)
Comune.create(description: "Castelfranco In Miscano", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 1065)
Comune.create(description: "Castelpagano", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 1699)
Comune.create(description: "Castelpoto", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 1476)
Comune.create(description: "Castelvenere", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 2632)
Comune.create(description: "Castelvetere In Val Fortore", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 1810)
Comune.create(description: "Cautano", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 2213)
Comune.create(description: "Ceppaloni", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 3402)
Comune.create(description: "Cerreto Sannita", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 4197)
Comune.create(description: "Circello", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 2673)
Comune.create(description: "Colle Sannita", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 3056)
Comune.create(description: "Cusano Mutri", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 4396)
Comune.create(description: "Dugenta", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 2646)
Comune.create(description: "Durazzano", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 2070)
Comune.create(description: "Faicchio", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 3879)
Comune.create(description: "Foglianise", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 3423)
Comune.create(description: "Foiano Di Val Fortore", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 1551)
Comune.create(description: "Forchia", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 1116)
Comune.create(description: "Fragneto Monforte", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 1962)
Comune.create(description: "Frasso Telesino", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 2708)
Comune.create(description: "Ginestra Degli Schiavoni", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 611)
Comune.create(description: "Guardia Sanframondi", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 5592)
Comune.create(description: "Limatola", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 3623)
Comune.create(description: "Melizzano", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 1865)
Comune.create(description: "Moiano", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 4106)
Comune.create(description: "Molinara", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 1946)
Comune.create(description: "Montefalcone Di Val Fortore", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 1837)
Comune.create(description: "Montesarchio", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 12878)
Comune.create(description: "Morcone", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 5122)
Comune.create(description: "Paduli", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 4262)
Comune.create(description: "Pago Veiano", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 2657)
Comune.create(description: "Pannarano", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 2011)
Comune.create(description: "Paolisi", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 1758)
Comune.create(description: "Paupisi", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 1521)
Comune.create(description: "Pesco Sannita", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 2185)
Comune.create(description: "Pietraroja", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 667)
Comune.create(description: "Pietrelcina", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 3031)
Comune.create(description: "Pontelandolfo", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 2520)
Comune.create(description: "Puglianello", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 1411)
Comune.create(description: "Reino", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 1360)
Comune.create(description: "San Bartolomeo In Galdo", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 5841)
Comune.create(description: "San Giorgio Del Sannio", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 9505)
Comune.create(description: "San Giorgio La Molara", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 3297)
Comune.create(description: "San Leucio Del Sannio", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 3159)
Comune.create(description: "San Lorenzello", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 2350)
Comune.create(description: "San Lorenzo Maggiore", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 2280)
Comune.create(description: "San Lupo", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 877)
Comune.create(description: "San Marco Dei Cavoti", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 3752)
Comune.create(description: "San Martino Sannita", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 1180)
Comune.create(description: "San Nazzaro", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 805)
Comune.create(description: "San Nicola Manfredi", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 3226)
Comune.create(description: "San Salvatore Telesino", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 3706)
Comune.create(description: "Santa Croce Del Sannio", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 1067)
Comune.create(description: "Sassinoro", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 646)
Comune.create(description: "Solopaca", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 4163)
Comune.create(description: "Telese", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 )
Comune.create(description: "Tocco Caudio", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 1605)
Comune.create(description: "Torrecuso", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 3522)
Comune.create(description: "Vitulano", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 3029)
Comune.create(description: "Fragneto L'Abate", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 1215)
Comune.create(description: "Sant'Agata De' Goti", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 11558)
Comune.create(description: "Sant'Angelo A Cupolo", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 4185)
Comune.create(description: "Sant'Arcangelo Trimonte", province_id: 35, region_id:  8, country_id: 1, continent_id: 1 , population: 691)
