Comune.create(description: "Ailano", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 1466)
Comune.create(description: "Alife", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 7164)
Comune.create(description: "Alvignano", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 4950)
Comune.create(description: "Arienzo", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 5198)
Comune.create(description: "Aversa", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 53369)
Comune.create(description: "Baia E Latina", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 2275)
Comune.create(description: "Bellona", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 5103)
Comune.create(description: "Caianello", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 1758)
Comune.create(description: "Caiazzo", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 2523)
Comune.create(description: "Calvi Risorta", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 5856)
Comune.create(description: "Camigliano", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 1739)
Comune.create(description: "Cancello Ed Arnone", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 5153)
Comune.create(description: "Capodrise", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 7508)
Comune.create(description: "Capriati A Volturno", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 1647)
Comune.create(description: "Capua", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 19041)
Comune.create(description: "Carinaro", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 6356)
Comune.create(description: "Carinola", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 8171)
Comune.create(description: "Casagiove", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 14821)
Comune.create(description: "Casal Di Principe", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 19859)
Comune.create(description: "Casaluce", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 9567)
Comune.create(description: "Casapesenna", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 6629)
Comune.create(description: "Casapulla", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 7866)
Comune.create(description: "Caserta", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 75208)
Comune.create(description: "Castel Campagnano", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 1632)
Comune.create(description: "Castel Di Sasso", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 1199)
Comune.create(description: "Castel Morrone", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 3988)
Comune.create(description: "Castel Volturno", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 18639)
Comune.create(description: "Castello Del Matese", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 1476)
Comune.create(description: "Cellole", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 7149)
Comune.create(description: "Cervino", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 5016)
Comune.create(description: "Cesa", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 7460)
Comune.create(description: "Ciorlano", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 524)
Comune.create(description: "Conca Della Campania", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 1392)
Comune.create(description: "Curti", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 6998)
Comune.create(description: "Dragoni", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 2108)
Comune.create(description: "Falciano Del Massico", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 3866)
Comune.create(description: "Fontegreca", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 857)
Comune.create(description: "Formicola", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 1467)
Comune.create(description: "Francolise", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 4905)
Comune.create(description: "Gallo Matese", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 761)
Comune.create(description: "Galluccio", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 2385)
Comune.create(description: "Giano Vetusto", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 653)
Comune.create(description: "Gioia Sannitica", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 3697)
Comune.create(description: "Grazzanise", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 6830)
Comune.create(description: "Gricignano Di Aversa", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 8903)
Comune.create(description: "Letino", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 783)
Comune.create(description: "Liberi", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 1222)
Comune.create(description: "Lusciano", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 13078)
Comune.create(description: "Macerata Campania", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 10136)
Comune.create(description: "Maddaloni", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 37546)
Comune.create(description: "Marcianise", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 39876)
Comune.create(description: "Marzano Appio", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 3087)
Comune.create(description: "Mignano Monte Lungo", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 3314)
Comune.create(description: "Mondragone", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 24155)
Comune.create(description: "Orta Di Atella", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 13070)
Comune.create(description: "Parete", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 10325)
Comune.create(description: "Pastorano", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 2454)
Comune.create(description: "Piana Di Monte Verna", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Piedimonte Matese", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 11462)
Comune.create(description: "Pietramelara", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 4464)
Comune.create(description: "Pietravairano", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 3022)
Comune.create(description: "Pignataro Maggiore", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 6485)
Comune.create(description: "Pontelatone", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 1881)
Comune.create(description: "Portico Di Caserta", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 6733)
Comune.create(description: "Prata Sannita", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 1699)
Comune.create(description: "Pratella", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 1695)
Comune.create(description: "Presenzano", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 1741)
Comune.create(description: "Raviscanina", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 1352)
Comune.create(description: "Recale", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 7147)
Comune.create(description: "Riardo", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 2509)
Comune.create(description: "Roccamonfina", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 3807)
Comune.create(description: "Roccaromana", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 1035)
Comune.create(description: "Rocchetta E Croce", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 524)
Comune.create(description: "Ruviano", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 1914)
Comune.create(description: "San Felice A Cancello", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 16769)
Comune.create(description: "San Gregorio Matese", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 1057)
Comune.create(description: "San Marcellino", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 11644)
Comune.create(description: "San Marco Evangelista", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 5828)
Comune.create(description: "San Nicola La Strada", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 18724)
Comune.create(description: "San Pietro Infine", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 1011)
Comune.create(description: "San Potito Sannitico", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 1897)
Comune.create(description: "San Prisco", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 10015)
Comune.create(description: "San Tammaro", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 4400)
Comune.create(description: "Santa Maria A Vico", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 13502)
Comune.create(description: "Santa Maria Capua Vetere", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 30745)
Comune.create(description: "Santa Maria La Fossa", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 2647)
Comune.create(description: "Sessa Aurunca", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 22825)
Comune.create(description: "Sparanise", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 7269)
Comune.create(description: "Succivo", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 6850)
Comune.create(description: "Teano", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 13042)
Comune.create(description: "Teverola", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 9831)
Comune.create(description: "Tora E Piccilli", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 1068)
Comune.create(description: "Trentola Ducenta", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 14126)
Comune.create(description: "Vairano Patenora", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 6259)
Comune.create(description: "Valle Agricola", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 1121)
Comune.create(description: "Valle Di Maddaloni", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 2556)
Comune.create(description: "Villa Di Briano", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 5703)
Comune.create(description: "Villa Literno", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 10364)
Comune.create(description: "Vitulazio", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 5443)
Comune.create(description: "Rocca D'Evandro", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 3720)
Comune.create(description: "San Cipriano D'Aversa", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 12530)
Comune.create(description: "Sant'Angelo D'Alife", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 2406)
Comune.create(description: "Sant'Arpino", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 13394)
