Municipality.create(description: "Ailano", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 1466)
Municipality.create(description: "Alife", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 7164)
Municipality.create(description: "Alvignano", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 4950)
Municipality.create(description: "Arienzo", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 5198)
Municipality.create(description: "Aversa", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 53369)
Municipality.create(description: "Baia E Latina", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 2275)
Municipality.create(description: "Bellona", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 5103)
Municipality.create(description: "Caianello", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 1758)
Municipality.create(description: "Caiazzo", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 2523)
Municipality.create(description: "Calvi Risorta", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 5856)
Municipality.create(description: "Camigliano", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 1739)
Municipality.create(description: "Cancello Ed Arnone", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 5153)
Municipality.create(description: "Capodrise", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 7508)
Municipality.create(description: "Capriati A Volturno", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 1647)
Municipality.create(description: "Capua", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 19041)
Municipality.create(description: "Carinaro", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 6356)
Municipality.create(description: "Carinola", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 8171)
Municipality.create(description: "Casagiove", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 14821)
Municipality.create(description: "Casal Di Principe", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 19859)
Municipality.create(description: "Casaluce", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 9567)
Municipality.create(description: "Casapesenna", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 6629)
Municipality.create(description: "Casapulla", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 7866)
Municipality.create(description: "Caserta", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 75208)
Municipality.create(description: "Castel Campagnano", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 1632)
Municipality.create(description: "Castel Di Sasso", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 1199)
Municipality.create(description: "Castel Morrone", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 3988)
Municipality.create(description: "Castel Volturno", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 18639)
Municipality.create(description: "Castello Del Matese", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 1476)
Municipality.create(description: "Cellole", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 7149)
Municipality.create(description: "Cervino", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 5016)
Municipality.create(description: "Cesa", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 7460)
Municipality.create(description: "Ciorlano", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 524)
Municipality.create(description: "Conca Della Campania", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 1392)
Municipality.create(description: "Curti", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 6998)
Municipality.create(description: "Dragoni", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 2108)
Municipality.create(description: "Falciano Del Massico", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 3866)
Municipality.create(description: "Fontegreca", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 857)
Municipality.create(description: "Formicola", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 1467)
Municipality.create(description: "Francolise", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 4905)
Municipality.create(description: "Gallo Matese", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 761)
Municipality.create(description: "Galluccio", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 2385)
Municipality.create(description: "Giano Vetusto", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 653)
Municipality.create(description: "Gioia Sannitica", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 3697)
Municipality.create(description: "Grazzanise", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 6830)
Municipality.create(description: "Gricignano Di Aversa", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 8903)
Municipality.create(description: "Letino", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 783)
Municipality.create(description: "Liberi", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 1222)
Municipality.create(description: "Lusciano", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 13078)
Municipality.create(description: "Macerata Campania", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 10136)
Municipality.create(description: "Maddaloni", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 37546)
Municipality.create(description: "Marcianise", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 39876)
Municipality.create(description: "Marzano Appio", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 3087)
Municipality.create(description: "Mignano Monte Lungo", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 3314)
Municipality.create(description: "Mondragone", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 24155)
Municipality.create(description: "Orta Di Atella", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 13070)
Municipality.create(description: "Parete", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 10325)
Municipality.create(description: "Pastorano", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 2454)
Municipality.create(description: "Piana Di Monte Verna", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Piedimonte Matese", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 11462)
Municipality.create(description: "Pietramelara", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 4464)
Municipality.create(description: "Pietravairano", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 3022)
Municipality.create(description: "Pignataro Maggiore", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 6485)
Municipality.create(description: "Pontelatone", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 1881)
Municipality.create(description: "Portico Di Caserta", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 6733)
Municipality.create(description: "Prata Sannita", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 1699)
Municipality.create(description: "Pratella", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 1695)
Municipality.create(description: "Presenzano", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 1741)
Municipality.create(description: "Raviscanina", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 1352)
Municipality.create(description: "Recale", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 7147)
Municipality.create(description: "Riardo", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 2509)
Municipality.create(description: "Roccamonfina", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 3807)
Municipality.create(description: "Roccaromana", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 1035)
Municipality.create(description: "Rocchetta E Croce", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 524)
Municipality.create(description: "Ruviano", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 1914)
Municipality.create(description: "San Felice A Cancello", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 16769)
Municipality.create(description: "San Gregorio Matese", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 1057)
Municipality.create(description: "San Marcellino", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 11644)
Municipality.create(description: "San Marco Evangelista", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 5828)
Municipality.create(description: "San Nicola La Strada", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 18724)
Municipality.create(description: "San Pietro Infine", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 1011)
Municipality.create(description: "San Potito Sannitico", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 1897)
Municipality.create(description: "San Prisco", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 10015)
Municipality.create(description: "San Tammaro", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 4400)
Municipality.create(description: "Santa Maria A Vico", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 13502)
Municipality.create(description: "Santa Maria Capua Vetere", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 30745)
Municipality.create(description: "Santa Maria La Fossa", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 2647)
Municipality.create(description: "Sessa Aurunca", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 22825)
Municipality.create(description: "Sparanise", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 7269)
Municipality.create(description: "Succivo", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 6850)
Municipality.create(description: "Teano", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 13042)
Municipality.create(description: "Teverola", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 9831)
Municipality.create(description: "Tora E Piccilli", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 1068)
Municipality.create(description: "Trentola Ducenta", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 14126)
Municipality.create(description: "Vairano Patenora", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 6259)
Municipality.create(description: "Valle Agricola", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 1121)
Municipality.create(description: "Valle Di Maddaloni", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 2556)
Municipality.create(description: "Villa Di Briano", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 5703)
Municipality.create(description: "Villa Literno", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 10364)
Municipality.create(description: "Vitulazio", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 5443)
Municipality.create(description: "Rocca D'Evandro", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 3720)
Municipality.create(description: "San Cipriano D'Aversa", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 12530)
Municipality.create(description: "Sant'Angelo D'Alife", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 2406)
Municipality.create(description: "Sant'Arpino", province_id: 36, region_id:  8, country_id: 1, continent_id: 1 , population: 13394)
