Municipality.create(description: "Acerra", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 45688)
Municipality.create(description: "Afragola", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 62319)
Municipality.create(description: "Agerola", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 7348)
Municipality.create(description: "Anacapri", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 5855)
Municipality.create(description: "Arzano", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 38510)
Municipality.create(description: "Bacoli", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 26507)
Municipality.create(description: "Boscoreale", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 27618)
Municipality.create(description: "Boscotrecase", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 10638)
Municipality.create(description: "Brusciano", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 15309)
Municipality.create(description: "Caivano", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 36966)
Municipality.create(description: "Calvizzano", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 12133)
Municipality.create(description: "Camposano", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 5303)
Municipality.create(description: "Capri", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 7064)
Municipality.create(description: "Carbonara Di Nola", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 2025)
Municipality.create(description: "Cardito", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 20683)
Municipality.create(description: "Casalnuovo Di Napoli", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 47940)
Municipality.create(description: "Casamarciano", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 3283)
Municipality.create(description: "Casamicciola Terme", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 7374)
Municipality.create(description: "Casandrino", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 13245)
Municipality.create(description: "Casavatore", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 20087)
Municipality.create(description: "Casola Di Napoli", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 3660)
Municipality.create(description: "Casoria", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 81888)
Municipality.create(description: "Castellammare Di Stabia", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 66929)
Municipality.create(description: "Castello Di Cisterna", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 6716)
Municipality.create(description: "Cercola", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 18876)
Municipality.create(description: "Cicciano", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 12573)
Municipality.create(description: "Cimitile", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 6840)
Municipality.create(description: "Comiziano", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 1769)
Municipality.create(description: "Crispano", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 12072)
Municipality.create(description: "Ercolano", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 56738)
Municipality.create(description: "Forio", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 14554)
Municipality.create(description: "Frattamaggiore", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 32731)
Municipality.create(description: "Frattaminore", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 15072)
Municipality.create(description: "Giugliano In Campania", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 97999)
Municipality.create(description: "Gragnano", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 29553)
Municipality.create(description: "Grumo Nevano", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 18644)
Municipality.create(description: "Lacco Ameno", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 4273)
Municipality.create(description: "Lettere", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 5605)
Municipality.create(description: "Liveri", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 1815)
Municipality.create(description: "Marano Di Napoli", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 57448)
Municipality.create(description: "Mariglianella", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 6199)
Municipality.create(description: "Marigliano", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 30083)
Municipality.create(description: "Massa Di Somma", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Massa Lubrense", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 12880)
Municipality.create(description: "Melito Di Napoli", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 34208)
Municipality.create(description: "Meta", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 7696)
Municipality.create(description: "Monte Di Procida", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 12838)
Municipality.create(description: "Mugnano Di Napoli", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 30069)
Municipality.create(description: "Napoli", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 1004500)
Municipality.create(description: "Nola", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 32730)
Municipality.create(description: "Ottaviano", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 22670)
Municipality.create(description: "Palma Campania", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 14613)
Municipality.create(description: "Piano Di Sorrento", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 12833)
Municipality.create(description: "Pimonte", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 5884)
Municipality.create(description: "Poggiomarino", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 19653)
Municipality.create(description: "Pollena Trocchia", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 13326)
Municipality.create(description: "Pompei", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 25751)
Municipality.create(description: "Portici", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 60218)
Municipality.create(description: "Pozzuoli", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 78754)
Municipality.create(description: "Procida", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 10575)
Municipality.create(description: "Qualiano", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 24542)
Municipality.create(description: "Quarto", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 36543)
Municipality.create(description: "Roccarainola", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 7182)
Municipality.create(description: "San Gennaro Vesuviano", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 10035)
Municipality.create(description: "San Giorgio A Cremano", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 50763)
Municipality.create(description: "San Giuseppe Vesuviano", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 24531)
Municipality.create(description: "San Paolo Bel Sito", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 3356)
Municipality.create(description: "San Sebastiano Al Vesuvio", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 9849)
Municipality.create(description: "San Vitaliano", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 5562)
Municipality.create(description: "Saviano", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 14755)
Municipality.create(description: "Scisciano", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 4881)
Municipality.create(description: "Serrara Fontana", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 3060)
Municipality.create(description: "Somma Vesuviana", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 33261)
Municipality.create(description: "Sorrento", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 16536)
Municipality.create(description: "Striano", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 7507)
Municipality.create(description: "Terzigno", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 15870)
Municipality.create(description: "Torre Annunziata", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 48011)
Municipality.create(description: "Torre Del Greco", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 90607)
Municipality.create(description: "Trecase", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 9179)
Municipality.create(description: "Tufino", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 3247)
Municipality.create(description: "Vico Equense", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 20048)
Municipality.create(description: "Villaricca", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 26175)
Municipality.create(description: "Visciano", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 4621)
Municipality.create(description: "Volla", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 21574)
Municipality.create(description: "Barano D'Ischia", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 8591)
Municipality.create(description: "Pomigliano D'Arco", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 40519)
Municipality.create(description: "Santa Maria La Carita'", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 10860)
Municipality.create(description: "Sant'Agnello", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 8421)
Municipality.create(description: "Sant'Anastasia", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 28023)
Municipality.create(description: "Sant'Antimo", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 31672)
Municipality.create(description: "Sant'Antonio Abate", province_id: 37, region_id:  8, country_id: 1, continent_id: 1 , population: 18124)
