Comune.create(description: "Acerno", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 3013)
Comune.create(description: "Agropoli", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 19949)
Comune.create(description: "Albanella", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 6317)
Comune.create(description: "Alfano", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1308)
Comune.create(description: "Altavilla Silentina", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 6751)
Comune.create(description: "Amalfi", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 5428)
Comune.create(description: "Angri", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 29761)
Comune.create(description: "Aquara", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1799)
Comune.create(description: "Ascea", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 5392)
Comune.create(description: "Atena Lucana", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 2231)
Comune.create(description: "Atrani", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 965)
Comune.create(description: "Auletta", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 2476)
Comune.create(description: "Baronissi", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 15226)
Comune.create(description: "Battipaglia", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 50359)
Comune.create(description: "Bellizzi", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Bellosguardo", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1009)
Comune.create(description: "Bracigliano", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 5230)
Comune.create(description: "Buccino", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 5659)
Comune.create(description: "Buonabitacolo", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 2581)
Comune.create(description: "Caggiano", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 3011)
Comune.create(description: "Calvanico", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1365)
Comune.create(description: "Camerota", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 6846)
Comune.create(description: "Campagna", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 15311)
Comune.create(description: "Campora", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 563)
Comune.create(description: "Cannalonga", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1146)
Comune.create(description: "Capaccio", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 20238)
Comune.create(description: "Casal Velino", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 4598)
Comune.create(description: "Casalbuono", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1303)
Comune.create(description: "Casaletto Spartano", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1680)
Comune.create(description: "Caselle In Pittari", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 2026)
Comune.create(description: "Castel San Giorgio", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 12879)
Comune.create(description: "Castel San Lorenzo", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 3034)
Comune.create(description: "Castelcivita", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 2152)
Comune.create(description: "Castellabate", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 7775)
Comune.create(description: "Castelnuovo Cilento", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 2253)
Comune.create(description: "Castelnuovo Di Conza", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 966)
Comune.create(description: "Castiglione Del Genovesi", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1270)
Comune.create(description: "Celle Di Bulgheria", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 2061)
Comune.create(description: "Centola", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 4828)
Comune.create(description: "Ceraso", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 2510)
Comune.create(description: "Cetara", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 2357)
Comune.create(description: "Cicerale", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1351)
Comune.create(description: "Colliano", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 3830)
Comune.create(description: "Conca Dei Marini", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 697)
Comune.create(description: "Controne", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 943)
Comune.create(description: "Contursi Terme", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 3182)
Comune.create(description: "Corbara", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 2455)
Comune.create(description: "Corleto Monforte", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 764)
Comune.create(description: "Cuccaro Vetere", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 622)
Comune.create(description: "Eboli", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 35842)
Comune.create(description: "Felitto", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1393)
Comune.create(description: "Fisciano", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 12275)
Comune.create(description: "Furore", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 810)
Comune.create(description: "Futani", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1280)
Comune.create(description: "Giffoni Sei Casali", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 4172)
Comune.create(description: "Giffoni Valle Piana", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 10992)
Comune.create(description: "Gioi", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1465)
Comune.create(description: "Giungano", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1116)
Comune.create(description: "Ispani", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1015)
Comune.create(description: "Laureana Cilento", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1093)
Comune.create(description: "Laurino", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1950)
Comune.create(description: "Laurito", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 943)
Comune.create(description: "Laviano", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1591)
Comune.create(description: "Lustra", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1115)
Comune.create(description: "Magliano Vetere", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 889)
Comune.create(description: "Maiori", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 5740)
Comune.create(description: "Mercato San Severino", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 20362)
Comune.create(description: "Minori", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 3023)
Comune.create(description: "Moio Della Civitella", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1823)
Comune.create(description: "Montano Antilia", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 2191)
Comune.create(description: "Monte San Giacomo", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1682)
Comune.create(description: "Montecorice", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 2474)
Comune.create(description: "Montecorvino Pugliano", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 7811)
Comune.create(description: "Montecorvino Rovella", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 11558)
Comune.create(description: "Monteforte Cilento", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 625)
Comune.create(description: "Montesano Sulla Marcellana", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 7220)
Comune.create(description: "Morigerati", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 780)
Comune.create(description: "Nocera Inferiore", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 46540)
Comune.create(description: "Nocera Superiore", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 23837)
Comune.create(description: "Novi Velia", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 2052)
Comune.create(description: "Ogliastro Cilento", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 2202)
Comune.create(description: "Olevano Sul Tusciano", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 6399)
Comune.create(description: "Oliveto Citra", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 4005)
Comune.create(description: "Omignano", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1536)
Comune.create(description: "Orria", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1293)
Comune.create(description: "Ottati", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 809)
Comune.create(description: "Padula", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 5403)
Comune.create(description: "Pagani", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 32349)
Comune.create(description: "Palomonte", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 4115)
Comune.create(description: "Pellezzano", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 10202)
Comune.create(description: "Perdifumo", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1866)
Comune.create(description: "Perito", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1101)
Comune.create(description: "Pertosa", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 727)
Comune.create(description: "Petina", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1238)
Comune.create(description: "Piaggine", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1775)
Comune.create(description: "Pisciotta", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 3038)
Comune.create(description: "Polla", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 5347)
Comune.create(description: "Pollica", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 2516)
Comune.create(description: "Pontecagnano Faiano", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 22730)
Comune.create(description: "Positano", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 3882)
Comune.create(description: "Postiglione", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 2334)
Comune.create(description: "Praiano", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1915)
Comune.create(description: "Prignano Cilento", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 870)
Comune.create(description: "Ravello", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 2508)
Comune.create(description: "Ricigliano", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1339)
Comune.create(description: "Roccadaspide", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 7461)
Comune.create(description: "Roccagloriosa", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1734)
Comune.create(description: "Roccapiemonte", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 9113)
Comune.create(description: "Rofrano", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 2193)
Comune.create(description: "Romagnano Al Monte", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 415)
Comune.create(description: "Roscigno", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 993)
Comune.create(description: "Rutino", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 920)
Comune.create(description: "Sacco", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Sala Consilina", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 12716)
Comune.create(description: "Salento", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 2022)
Comune.create(description: "Salerno", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 138188)
Comune.create(description: "Salvitelle", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 702)
Comune.create(description: "San Cipriano Picentino", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 5978)
Comune.create(description: "San Giovanni A Piro", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 3753)
Comune.create(description: "San Gregorio Magno", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 4616)
Comune.create(description: "San Mango Piemonte", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 2166)
Comune.create(description: "San Marzano Sul Sarno", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 9472)
Comune.create(description: "San Mauro Cilento", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1011)
Comune.create(description: "San Mauro La Bruca", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 768)
Comune.create(description: "San Pietro Al Tanagro", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1640)
Comune.create(description: "San Rufo", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1853)
Comune.create(description: "San Valentino Torio", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 9285)
Comune.create(description: "Santa Marina", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 3303)
Comune.create(description: "Santomenna", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 580)
Comune.create(description: "Sanza", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 3006)
Comune.create(description: "Sapri", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 7022)
Comune.create(description: "Sarno", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 31059)
Comune.create(description: "Sassano", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 5190)
Comune.create(description: "Scafati", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 47082)
Comune.create(description: "Scala", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1488)
Comune.create(description: "Serramezzana", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 403)
Comune.create(description: "Serre", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 3818)
Comune.create(description: "Sessa Cilento", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1466)
Comune.create(description: "Siano", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 10104)
Comune.create(description: "Sicignano Degli Alburni", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 3466)
Comune.create(description: "Stella Cilento", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 850)
Comune.create(description: "Stio", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1088)
Comune.create(description: "Teggiano", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 8241)
Comune.create(description: "Torchiara", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1525)
Comune.create(description: "Torraca", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1232)
Comune.create(description: "Torre Orsaia", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 2392)
Comune.create(description: "Tortorella", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 603)
Comune.create(description: "Tramonti", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 3935)
Comune.create(description: "Trentinara", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1769)
Comune.create(description: "Vallo Della Lucania", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 8818)
Comune.create(description: "Valva", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1772)
Comune.create(description: "Vibonati", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 3019)
Comune.create(description: "Vietri Sul Mare", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 8543)
Comune.create(description: "Cava De' Tirreni", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 52616)
Comune.create(description: "Sant'Angelo A Fasanella", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 818)
Comune.create(description: "Sant'Arsenio", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 2752)
Comune.create(description: "Sant'Egidio Del Monte Albino", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 8394)
Comune.create(description: "Valle Dell'Angelo", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 406)
