Municipality.create(description: "Acerno", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 3013)
Municipality.create(description: "Agropoli", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 19949)
Municipality.create(description: "Albanella", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 6317)
Municipality.create(description: "Alfano", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1308)
Municipality.create(description: "Altavilla Silentina", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 6751)
Municipality.create(description: "Amalfi", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 5428)
Municipality.create(description: "Angri", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 29761)
Municipality.create(description: "Aquara", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1799)
Municipality.create(description: "Ascea", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 5392)
Municipality.create(description: "Atena Lucana", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 2231)
Municipality.create(description: "Atrani", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 965)
Municipality.create(description: "Auletta", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 2476)
Municipality.create(description: "Baronissi", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 15226)
Municipality.create(description: "Battipaglia", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 50359)
Municipality.create(description: "Bellizzi", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Bellosguardo", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1009)
Municipality.create(description: "Bracigliano", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 5230)
Municipality.create(description: "Buccino", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 5659)
Municipality.create(description: "Buonabitacolo", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 2581)
Municipality.create(description: "Caggiano", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 3011)
Municipality.create(description: "Calvanico", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1365)
Municipality.create(description: "Camerota", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 6846)
Municipality.create(description: "Campagna", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 15311)
Municipality.create(description: "Campora", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 563)
Municipality.create(description: "Cannalonga", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1146)
Municipality.create(description: "Capaccio", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 20238)
Municipality.create(description: "Casal Velino", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 4598)
Municipality.create(description: "Casalbuono", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1303)
Municipality.create(description: "Casaletto Spartano", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1680)
Municipality.create(description: "Caselle In Pittari", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 2026)
Municipality.create(description: "Castel San Giorgio", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 12879)
Municipality.create(description: "Castel San Lorenzo", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 3034)
Municipality.create(description: "Castelcivita", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 2152)
Municipality.create(description: "Castellabate", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 7775)
Municipality.create(description: "Castelnuovo Cilento", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 2253)
Municipality.create(description: "Castelnuovo Di Conza", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 966)
Municipality.create(description: "Castiglione Del Genovesi", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1270)
Municipality.create(description: "Celle Di Bulgheria", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 2061)
Municipality.create(description: "Centola", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 4828)
Municipality.create(description: "Ceraso", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 2510)
Municipality.create(description: "Cetara", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 2357)
Municipality.create(description: "Cicerale", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1351)
Municipality.create(description: "Colliano", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 3830)
Municipality.create(description: "Conca Dei Marini", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 697)
Municipality.create(description: "Controne", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 943)
Municipality.create(description: "Contursi Terme", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 3182)
Municipality.create(description: "Corbara", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 2455)
Municipality.create(description: "Corleto Monforte", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 764)
Municipality.create(description: "Cuccaro Vetere", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 622)
Municipality.create(description: "Eboli", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 35842)
Municipality.create(description: "Felitto", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1393)
Municipality.create(description: "Fisciano", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 12275)
Municipality.create(description: "Furore", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 810)
Municipality.create(description: "Futani", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1280)
Municipality.create(description: "Giffoni Sei Casali", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 4172)
Municipality.create(description: "Giffoni Valle Piana", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 10992)
Municipality.create(description: "Gioi", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1465)
Municipality.create(description: "Giungano", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1116)
Municipality.create(description: "Ispani", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1015)
Municipality.create(description: "Laureana Cilento", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1093)
Municipality.create(description: "Laurino", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1950)
Municipality.create(description: "Laurito", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 943)
Municipality.create(description: "Laviano", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1591)
Municipality.create(description: "Lustra", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1115)
Municipality.create(description: "Magliano Vetere", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 889)
Municipality.create(description: "Maiori", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 5740)
Municipality.create(description: "Mercato San Severino", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 20362)
Municipality.create(description: "Minori", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 3023)
Municipality.create(description: "Moio Della Civitella", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1823)
Municipality.create(description: "Montano Antilia", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 2191)
Municipality.create(description: "Monte San Giacomo", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1682)
Municipality.create(description: "Montecorice", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 2474)
Municipality.create(description: "Montecorvino Pugliano", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 7811)
Municipality.create(description: "Montecorvino Rovella", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 11558)
Municipality.create(description: "Monteforte Cilento", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 625)
Municipality.create(description: "Montesano Sulla Marcellana", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 7220)
Municipality.create(description: "Morigerati", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 780)
Municipality.create(description: "Nocera Inferiore", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 46540)
Municipality.create(description: "Nocera Superiore", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 23837)
Municipality.create(description: "Novi Velia", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 2052)
Municipality.create(description: "Ogliastro Cilento", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 2202)
Municipality.create(description: "Olevano Sul Tusciano", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 6399)
Municipality.create(description: "Oliveto Citra", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 4005)
Municipality.create(description: "Omignano", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1536)
Municipality.create(description: "Orria", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1293)
Municipality.create(description: "Ottati", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 809)
Municipality.create(description: "Padula", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 5403)
Municipality.create(description: "Pagani", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 32349)
Municipality.create(description: "Palomonte", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 4115)
Municipality.create(description: "Pellezzano", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 10202)
Municipality.create(description: "Perdifumo", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1866)
Municipality.create(description: "Perito", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1101)
Municipality.create(description: "Pertosa", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 727)
Municipality.create(description: "Petina", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1238)
Municipality.create(description: "Piaggine", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1775)
Municipality.create(description: "Pisciotta", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 3038)
Municipality.create(description: "Polla", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 5347)
Municipality.create(description: "Pollica", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 2516)
Municipality.create(description: "Pontecagnano Faiano", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 22730)
Municipality.create(description: "Positano", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 3882)
Municipality.create(description: "Postiglione", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 2334)
Municipality.create(description: "Praiano", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1915)
Municipality.create(description: "Prignano Cilento", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 870)
Municipality.create(description: "Ravello", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 2508)
Municipality.create(description: "Ricigliano", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1339)
Municipality.create(description: "Roccadaspide", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 7461)
Municipality.create(description: "Roccagloriosa", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1734)
Municipality.create(description: "Roccapiemonte", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 9113)
Municipality.create(description: "Rofrano", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 2193)
Municipality.create(description: "Romagnano Al Monte", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 415)
Municipality.create(description: "Roscigno", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 993)
Municipality.create(description: "Rutino", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 920)
Municipality.create(description: "Sacco", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Sala Consilina", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 12716)
Municipality.create(description: "Salento", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 2022)
Municipality.create(description: "Salerno", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 138188)
Municipality.create(description: "Salvitelle", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 702)
Municipality.create(description: "San Cipriano Picentino", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 5978)
Municipality.create(description: "San Giovanni A Piro", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 3753)
Municipality.create(description: "San Gregorio Magno", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 4616)
Municipality.create(description: "San Mango Piemonte", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 2166)
Municipality.create(description: "San Marzano Sul Sarno", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 9472)
Municipality.create(description: "San Mauro Cilento", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1011)
Municipality.create(description: "San Mauro La Bruca", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 768)
Municipality.create(description: "San Pietro Al Tanagro", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1640)
Municipality.create(description: "San Rufo", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1853)
Municipality.create(description: "San Valentino Torio", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 9285)
Municipality.create(description: "Santa Marina", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 3303)
Municipality.create(description: "Santomenna", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 580)
Municipality.create(description: "Sanza", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 3006)
Municipality.create(description: "Sapri", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 7022)
Municipality.create(description: "Sarno", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 31059)
Municipality.create(description: "Sassano", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 5190)
Municipality.create(description: "Scafati", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 47082)
Municipality.create(description: "Scala", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1488)
Municipality.create(description: "Serramezzana", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 403)
Municipality.create(description: "Serre", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 3818)
Municipality.create(description: "Sessa Cilento", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1466)
Municipality.create(description: "Siano", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 10104)
Municipality.create(description: "Sicignano Degli Alburni", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 3466)
Municipality.create(description: "Stella Cilento", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 850)
Municipality.create(description: "Stio", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1088)
Municipality.create(description: "Teggiano", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 8241)
Municipality.create(description: "Torchiara", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1525)
Municipality.create(description: "Torraca", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1232)
Municipality.create(description: "Torre Orsaia", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 2392)
Municipality.create(description: "Tortorella", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 603)
Municipality.create(description: "Tramonti", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 3935)
Municipality.create(description: "Trentinara", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1769)
Municipality.create(description: "Vallo Della Lucania", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 8818)
Municipality.create(description: "Valva", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 1772)
Municipality.create(description: "Vibonati", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 3019)
Municipality.create(description: "Vietri Sul Mare", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 8543)
Municipality.create(description: "Cava De' Tirreni", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 52616)
Municipality.create(description: "Sant'Angelo A Fasanella", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 818)
Municipality.create(description: "Sant'Arsenio", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 2752)
Municipality.create(description: "Sant'Egidio Del Monte Albino", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 8394)
Municipality.create(description: "Valle Dell'Angelo", province_id: 38, region_id:  8, country_id: 1, continent_id: 1 , population: 406)
