#encoding: utf-8
Comune.create(:description => "Acerno", :provincia_id => 38, :regione_id => 8, :population => 3013)
Comune.create(:description => "Agropoli", :provincia_id => 38, :regione_id => 8, :population => 19949)
Comune.create(:description => "Albanella", :provincia_id => 38, :regione_id => 8, :population => 6317)
Comune.create(:description => "Alfano", :provincia_id => 38, :regione_id => 8, :population => 1308)
Comune.create(:description => "Altavilla Silentina", :provincia_id => 38, :regione_id => 8, :population => 6751)
Comune.create(:description => "Amalfi", :provincia_id => 38, :regione_id => 8, :population => 5428)
Comune.create(:description => "Angri", :provincia_id => 38, :regione_id => 8, :population => 29761)
Comune.create(:description => "Aquara", :provincia_id => 38, :regione_id => 8, :population => 1799)
Comune.create(:description => "Ascea", :provincia_id => 38, :regione_id => 8, :population => 5392)
Comune.create(:description => "Atena Lucana", :provincia_id => 38, :regione_id => 8, :population => 2231)
Comune.create(:description => "Atrani", :provincia_id => 38, :regione_id => 8, :population => 965)
Comune.create(:description => "Auletta", :provincia_id => 38, :regione_id => 8, :population => 2476)
Comune.create(:description => "Baronissi", :provincia_id => 38, :regione_id => 8, :population => 15226)
Comune.create(:description => "Battipaglia", :provincia_id => 38, :regione_id => 8, :population => 50359)
Comune.create(:description => "Bellizzi", :provincia_id => 38, :regione_id => 8, :population => 0)
Comune.create(:description => "Bellosguardo", :provincia_id => 38, :regione_id => 8, :population => 1009)
Comune.create(:description => "Bracigliano", :provincia_id => 38, :regione_id => 8, :population => 5230)
Comune.create(:description => "Buccino", :provincia_id => 38, :regione_id => 8, :population => 5659)
Comune.create(:description => "Buonabitacolo", :provincia_id => 38, :regione_id => 8, :population => 2581)
Comune.create(:description => "Caggiano", :provincia_id => 38, :regione_id => 8, :population => 3011)
Comune.create(:description => "Calvanico", :provincia_id => 38, :regione_id => 8, :population => 1365)
Comune.create(:description => "Camerota", :provincia_id => 38, :regione_id => 8, :population => 6846)
Comune.create(:description => "Campagna", :provincia_id => 38, :regione_id => 8, :population => 15311)
Comune.create(:description => "Campora", :provincia_id => 38, :regione_id => 8, :population => 563)
Comune.create(:description => "Cannalonga", :provincia_id => 38, :regione_id => 8, :population => 1146)
Comune.create(:description => "Capaccio", :provincia_id => 38, :regione_id => 8, :population => 20238)
Comune.create(:description => "Casal Velino", :provincia_id => 38, :regione_id => 8, :population => 4598)
Comune.create(:description => "Casalbuono", :provincia_id => 38, :regione_id => 8, :population => 1303)
Comune.create(:description => "Casaletto Spartano", :provincia_id => 38, :regione_id => 8, :population => 1680)
Comune.create(:description => "Caselle In Pittari", :provincia_id => 38, :regione_id => 8, :population => 2026)
Comune.create(:description => "Castel San Giorgio", :provincia_id => 38, :regione_id => 8, :population => 12879)
Comune.create(:description => "Castel San Lorenzo", :provincia_id => 38, :regione_id => 8, :population => 3034)
Comune.create(:description => "Castelcivita", :provincia_id => 38, :regione_id => 8, :population => 2152)
Comune.create(:description => "Castellabate", :provincia_id => 38, :regione_id => 8, :population => 7775)
Comune.create(:description => "Castelnuovo Cilento", :provincia_id => 38, :regione_id => 8, :population => 2253)
Comune.create(:description => "Castelnuovo Di Conza", :provincia_id => 38, :regione_id => 8, :population => 966)
Comune.create(:description => "Castiglione Del Genovesi", :provincia_id => 38, :regione_id => 8, :population => 1270)
Comune.create(:description => "Celle Di Bulgheria", :provincia_id => 38, :regione_id => 8, :population => 2061)
Comune.create(:description => "Centola", :provincia_id => 38, :regione_id => 8, :population => 4828)
Comune.create(:description => "Ceraso", :provincia_id => 38, :regione_id => 8, :population => 2510)
Comune.create(:description => "Cetara", :provincia_id => 38, :regione_id => 8, :population => 2357)
Comune.create(:description => "Cicerale", :provincia_id => 38, :regione_id => 8, :population => 1351)
Comune.create(:description => "Colliano", :provincia_id => 38, :regione_id => 8, :population => 3830)
Comune.create(:description => "Conca Dei Marini", :provincia_id => 38, :regione_id => 8, :population => 697)
Comune.create(:description => "Controne", :provincia_id => 38, :regione_id => 8, :population => 943)
Comune.create(:description => "Contursi Terme", :provincia_id => 38, :regione_id => 8, :population => 3182)
Comune.create(:description => "Corbara", :provincia_id => 38, :regione_id => 8, :population => 2455)
Comune.create(:description => "Corleto Monforte", :provincia_id => 38, :regione_id => 8, :population => 764)
Comune.create(:description => "Cuccaro Vetere", :provincia_id => 38, :regione_id => 8, :population => 622)
Comune.create(:description => "Eboli", :provincia_id => 38, :regione_id => 8, :population => 35842)
Comune.create(:description => "Felitto", :provincia_id => 38, :regione_id => 8, :population => 1393)
Comune.create(:description => "Fisciano", :provincia_id => 38, :regione_id => 8, :population => 12275)
Comune.create(:description => "Furore", :provincia_id => 38, :regione_id => 8, :population => 810)
Comune.create(:description => "Futani", :provincia_id => 38, :regione_id => 8, :population => 1280)
Comune.create(:description => "Giffoni Sei Casali", :provincia_id => 38, :regione_id => 8, :population => 4172)
Comune.create(:description => "Giffoni Valle Piana", :provincia_id => 38, :regione_id => 8, :population => 10992)
Comune.create(:description => "Gioi", :provincia_id => 38, :regione_id => 8, :population => 1465)
Comune.create(:description => "Giungano", :provincia_id => 38, :regione_id => 8, :population => 1116)
Comune.create(:description => "Ispani", :provincia_id => 38, :regione_id => 8, :population => 1015)
Comune.create(:description => "Laureana Cilento", :provincia_id => 38, :regione_id => 8, :population => 1093)
Comune.create(:description => "Laurino", :provincia_id => 38, :regione_id => 8, :population => 1950)
Comune.create(:description => "Laurito", :provincia_id => 38, :regione_id => 8, :population => 943)
Comune.create(:description => "Laviano", :provincia_id => 38, :regione_id => 8, :population => 1591)
Comune.create(:description => "Lustra", :provincia_id => 38, :regione_id => 8, :population => 1115)
Comune.create(:description => "Magliano Vetere", :provincia_id => 38, :regione_id => 8, :population => 889)
Comune.create(:description => "Maiori", :provincia_id => 38, :regione_id => 8, :population => 5740)
Comune.create(:description => "Mercato San Severino", :provincia_id => 38, :regione_id => 8, :population => 20362)
Comune.create(:description => "Minori", :provincia_id => 38, :regione_id => 8, :population => 3023)
Comune.create(:description => "Moio Della Civitella", :provincia_id => 38, :regione_id => 8, :population => 1823)
Comune.create(:description => "Montano Antilia", :provincia_id => 38, :regione_id => 8, :population => 2191)
Comune.create(:description => "Monte San Giacomo", :provincia_id => 38, :regione_id => 8, :population => 1682)
Comune.create(:description => "Montecorice", :provincia_id => 38, :regione_id => 8, :population => 2474)
Comune.create(:description => "Montecorvino Pugliano", :provincia_id => 38, :regione_id => 8, :population => 7811)
Comune.create(:description => "Montecorvino Rovella", :provincia_id => 38, :regione_id => 8, :population => 11558)
Comune.create(:description => "Monteforte Cilento", :provincia_id => 38, :regione_id => 8, :population => 625)
Comune.create(:description => "Montesano Sulla Marcellana", :provincia_id => 38, :regione_id => 8, :population => 7220)
Comune.create(:description => "Morigerati", :provincia_id => 38, :regione_id => 8, :population => 780)
Comune.create(:description => "Nocera Inferiore", :provincia_id => 38, :regione_id => 8, :population => 46540)
Comune.create(:description => "Nocera Superiore", :provincia_id => 38, :regione_id => 8, :population => 23837)
Comune.create(:description => "Novi Velia", :provincia_id => 38, :regione_id => 8, :population => 2052)
Comune.create(:description => "Ogliastro Cilento", :provincia_id => 38, :regione_id => 8, :population => 2202)
Comune.create(:description => "Olevano Sul Tusciano", :provincia_id => 38, :regione_id => 8, :population => 6399)
Comune.create(:description => "Oliveto Citra", :provincia_id => 38, :regione_id => 8, :population => 4005)
Comune.create(:description => "Omignano", :provincia_id => 38, :regione_id => 8, :population => 1536)
Comune.create(:description => "Orria", :provincia_id => 38, :regione_id => 8, :population => 1293)
Comune.create(:description => "Ottati", :provincia_id => 38, :regione_id => 8, :population => 809)
Comune.create(:description => "Padula", :provincia_id => 38, :regione_id => 8, :population => 5403)
Comune.create(:description => "Pagani", :provincia_id => 38, :regione_id => 8, :population => 32349)
Comune.create(:description => "Palomonte", :provincia_id => 38, :regione_id => 8, :population => 4115)
Comune.create(:description => "Pellezzano", :provincia_id => 38, :regione_id => 8, :population => 10202)
Comune.create(:description => "Perdifumo", :provincia_id => 38, :regione_id => 8, :population => 1866)
Comune.create(:description => "Perito", :provincia_id => 38, :regione_id => 8, :population => 1101)
Comune.create(:description => "Pertosa", :provincia_id => 38, :regione_id => 8, :population => 727)
Comune.create(:description => "Petina", :provincia_id => 38, :regione_id => 8, :population => 1238)
Comune.create(:description => "Piaggine", :provincia_id => 38, :regione_id => 8, :population => 1775)
Comune.create(:description => "Pisciotta", :provincia_id => 38, :regione_id => 8, :population => 3038)
Comune.create(:description => "Polla", :provincia_id => 38, :regione_id => 8, :population => 5347)
Comune.create(:description => "Pollica", :provincia_id => 38, :regione_id => 8, :population => 2516)
Comune.create(:description => "Pontecagnano Faiano", :provincia_id => 38, :regione_id => 8, :population => 22730)
Comune.create(:description => "Positano", :provincia_id => 38, :regione_id => 8, :population => 3882)
Comune.create(:description => "Postiglione", :provincia_id => 38, :regione_id => 8, :population => 2334)
Comune.create(:description => "Praiano", :provincia_id => 38, :regione_id => 8, :population => 1915)
Comune.create(:description => "Prignano Cilento", :provincia_id => 38, :regione_id => 8, :population => 870)
Comune.create(:description => "Ravello", :provincia_id => 38, :regione_id => 8, :population => 2508)
Comune.create(:description => "Ricigliano", :provincia_id => 38, :regione_id => 8, :population => 1339)
Comune.create(:description => "Roccadaspide", :provincia_id => 38, :regione_id => 8, :population => 7461)
Comune.create(:description => "Roccagloriosa", :provincia_id => 38, :regione_id => 8, :population => 1734)
Comune.create(:description => "Roccapiemonte", :provincia_id => 38, :regione_id => 8, :population => 9113)
Comune.create(:description => "Rofrano", :provincia_id => 38, :regione_id => 8, :population => 2193)
Comune.create(:description => "Romagnano Al Monte", :provincia_id => 38, :regione_id => 8, :population => 415)
Comune.create(:description => "Roscigno", :provincia_id => 38, :regione_id => 8, :population => 993)
Comune.create(:description => "Rutino", :provincia_id => 38, :regione_id => 8, :population => 920)
Comune.create(:description => "Sacco", :provincia_id => 38, :regione_id => 8, :population => 0)
Comune.create(:description => "Sala Consilina", :provincia_id => 38, :regione_id => 8, :population => 12716)
Comune.create(:description => "Salento", :provincia_id => 38, :regione_id => 8, :population => 2022)
Comune.create(:description => "Salerno", :provincia_id => 38, :regione_id => 8, :population => 138188)
Comune.create(:description => "Salvitelle", :provincia_id => 38, :regione_id => 8, :population => 702)
Comune.create(:description => "San Cipriano Picentino", :provincia_id => 38, :regione_id => 8, :population => 5978)
Comune.create(:description => "San Giovanni A Piro", :provincia_id => 38, :regione_id => 8, :population => 3753)
Comune.create(:description => "San Gregorio Magno", :provincia_id => 38, :regione_id => 8, :population => 4616)
Comune.create(:description => "San Mango Piemonte", :provincia_id => 38, :regione_id => 8, :population => 2166)
Comune.create(:description => "San Marzano Sul Sarno", :provincia_id => 38, :regione_id => 8, :population => 9472)
Comune.create(:description => "San Mauro Cilento", :provincia_id => 38, :regione_id => 8, :population => 1011)
Comune.create(:description => "San Mauro La Bruca", :provincia_id => 38, :regione_id => 8, :population => 768)
Comune.create(:description => "San Pietro Al Tanagro", :provincia_id => 38, :regione_id => 8, :population => 1640)
Comune.create(:description => "San Rufo", :provincia_id => 38, :regione_id => 8, :population => 1853)
Comune.create(:description => "San Valentino Torio", :provincia_id => 38, :regione_id => 8, :population => 9285)
Comune.create(:description => "Santa Marina", :provincia_id => 38, :regione_id => 8, :population => 3303)
Comune.create(:description => "Santomenna", :provincia_id => 38, :regione_id => 8, :population => 580)
Comune.create(:description => "Sanza", :provincia_id => 38, :regione_id => 8, :population => 3006)
Comune.create(:description => "Sapri", :provincia_id => 38, :regione_id => 8, :population => 7022)
Comune.create(:description => "Sarno", :provincia_id => 38, :regione_id => 8, :population => 31059)
Comune.create(:description => "Sassano", :provincia_id => 38, :regione_id => 8, :population => 5190)
Comune.create(:description => "Scafati", :provincia_id => 38, :regione_id => 8, :population => 47082)
Comune.create(:description => "Scala", :provincia_id => 38, :regione_id => 8, :population => 1488)
Comune.create(:description => "Serramezzana", :provincia_id => 38, :regione_id => 8, :population => 403)
Comune.create(:description => "Serre", :provincia_id => 38, :regione_id => 8, :population => 3818)
Comune.create(:description => "Sessa Cilento", :provincia_id => 38, :regione_id => 8, :population => 1466)
Comune.create(:description => "Siano", :provincia_id => 38, :regione_id => 8, :population => 10104)
Comune.create(:description => "Sicignano Degli Alburni", :provincia_id => 38, :regione_id => 8, :population => 3466)
Comune.create(:description => "Stella Cilento", :provincia_id => 38, :regione_id => 8, :population => 850)
Comune.create(:description => "Stio", :provincia_id => 38, :regione_id => 8, :population => 1088)
Comune.create(:description => "Teggiano", :provincia_id => 38, :regione_id => 8, :population => 8241)
Comune.create(:description => "Torchiara", :provincia_id => 38, :regione_id => 8, :population => 1525)
Comune.create(:description => "Torraca", :provincia_id => 38, :regione_id => 8, :population => 1232)
Comune.create(:description => "Torre Orsaia", :provincia_id => 38, :regione_id => 8, :population => 2392)
Comune.create(:description => "Tortorella", :provincia_id => 38, :regione_id => 8, :population => 603)
Comune.create(:description => "Tramonti", :provincia_id => 38, :regione_id => 8, :population => 3935)
Comune.create(:description => "Trentinara", :provincia_id => 38, :regione_id => 8, :population => 1769)
Comune.create(:description => "Vallo Della Lucania", :provincia_id => 38, :regione_id => 8, :population => 8818)
Comune.create(:description => "Valva", :provincia_id => 38, :regione_id => 8, :population => 1772)
Comune.create(:description => "Vibonati", :provincia_id => 38, :regione_id => 8, :population => 3019)
Comune.create(:description => "Vietri Sul Mare", :provincia_id => 38, :regione_id => 8, :population => 8543)
Comune.create(:description => "Cava De' Tirreni", :provincia_id => 38, :regione_id => 8, :population => 52616)
Comune.create(:description => "Sant'Angelo A Fasanella", :provincia_id => 38, :regione_id => 8, :population => 818)
Comune.create(:description => "Sant'Arsenio", :provincia_id => 38, :regione_id => 8, :population => 2752)
Comune.create(:description => "Sant'Egidio Del Monte Albino", :provincia_id => 38, :regione_id => 8, :population => 8394)
Comune.create(:description => "Valle Dell'Angelo", :provincia_id => 38, :regione_id => 8, :population => 406)
