Comune.create(description: "Acquafondata", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 316)
Comune.create(description: "Acuto", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 1857)
Comune.create(description: "Alatri", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 27068)
Comune.create(description: "Alvito", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 3031)
Comune.create(description: "Amaseno", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 4228)
Comune.create(description: "Anagni", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 19134)
Comune.create(description: "Aquino", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 5337)
Comune.create(description: "Arce", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 6029)
Comune.create(description: "Arnara", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 2454)
Comune.create(description: "Arpino", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 7614)
Comune.create(description: "Atina", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 4484)
Comune.create(description: "Ausonia", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 2563)
Comune.create(description: "Belmonte Castello", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 765)
Comune.create(description: "Boville Ernica", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 8873)
Comune.create(description: "Broccostella", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 2646)
Comune.create(description: "Campoli Appennino", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 1804)
Comune.create(description: "Casalattico", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 675)
Comune.create(description: "Casalvieri", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 3211)
Comune.create(description: "Cassino", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 32762)
Comune.create(description: "Castelliri", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 3560)
Comune.create(description: "Castelnuovo Parano", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 876)
Comune.create(description: "Castro Dei Volsci", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 5039)
Comune.create(description: "Castrocielo", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 3750)
Comune.create(description: "Ceccano", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 22334)
Comune.create(description: "Ceprano", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 8246)
Comune.create(description: "Cervaro", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 7022)
Comune.create(description: "Colfelice", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 1853)
Comune.create(description: "Colle San Magno", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 819)
Comune.create(description: "Collepardo", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 928)
Comune.create(description: "Coreno Ausonio", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 1738)
Comune.create(description: "Esperia", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 4131)
Comune.create(description: "Falvaterra", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 630)
Comune.create(description: "Ferentino", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 20103)
Comune.create(description: "Filettino", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 550)
Comune.create(description: "Fiuggi", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 8763)
Comune.create(description: "Fontana Liri", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 3215)
Comune.create(description: "Fontechiari", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 1288)
Comune.create(description: "Frosinone", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 48636)
Comune.create(description: "Fumone", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 2153)
Comune.create(description: "Gallinaro", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 1221)
Comune.create(description: "Giuliano Di Roma", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 2228)
Comune.create(description: "Guarcino", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 1662)
Comune.create(description: "Isola Del Liri", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 12191)
Comune.create(description: "Monte San Giovanni Campano", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 12739)
Comune.create(description: "Morolo", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 3090)
Comune.create(description: "Paliano", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 7663)
Comune.create(description: "Pastena", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 1672)
Comune.create(description: "Patrica", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 2915)
Comune.create(description: "Pescosolido", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 1568)
Comune.create(description: "Picinisco", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 1206)
Comune.create(description: "Pico", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 3123)
Comune.create(description: "Piedimonte San Germano", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 4481)
Comune.create(description: "Piglio", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 4700)
Comune.create(description: "Pignataro Interamna", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 2447)
Comune.create(description: "Pofi", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 4463)
Comune.create(description: "Pontecorvo", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 13280)
Comune.create(description: "Posta Fibreno", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 1274)
Comune.create(description: "Ripi", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 5282)
Comune.create(description: "Roccasecca", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 7442)
Comune.create(description: "San Biagio Saracinisco", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 365)
Comune.create(description: "San Donato Val Di Comino", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 2192)
Comune.create(description: "San Giorgio A Liri", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 3067)
Comune.create(description: "San Giovanni Incarico", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 3587)
Comune.create(description: "San Vittore Del Lazio", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 2674)
Comune.create(description: "Santopadre", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 1649)
Comune.create(description: "Serrone", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 2943)
Comune.create(description: "Settefrati", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 855)
Comune.create(description: "Sgurgola", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 2556)
Comune.create(description: "Sora", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 26029)
Comune.create(description: "Strangolagalli", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 2503)
Comune.create(description: "Supino", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 4783)
Comune.create(description: "Terelle", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 603)
Comune.create(description: "Torre Cajetani", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 1279)
Comune.create(description: "Torrice", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 4356)
Comune.create(description: "Trevi Nel Lazio", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 1822)
Comune.create(description: "Trivigliano", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 1430)
Comune.create(description: "Vallecorsa", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 3115)
Comune.create(description: "Vallemaio", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 1052)
Comune.create(description: "Vallerotonda", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 1854)
Comune.create(description: "Veroli", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 19818)
Comune.create(description: "Vicalvi", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 801)
Comune.create(description: "Vico Nel Lazio", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 2161)
Comune.create(description: "Villa Latina", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 1247)
Comune.create(description: "Villa Santa Lucia", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 2622)
Comune.create(description: "Villa Santo Stefano", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 1763)
Comune.create(description: "Viticuso", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 428)
Comune.create(description: "Rocca D'Arce", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 )
Comune.create(description: "Sant'Ambrogio Sul Garigliano", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 984)
Comune.create(description: "Sant'Andrea Del Garigliano", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 1589)
Comune.create(description: "Sant'Apollinare", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 1950)
Comune.create(description: "Sant'Elia Fiumerapido", province_id: 39, region_id:  9, country_id: 1, continent_id: 1 , population: 6326)
