Municipality.create(description: "Aprilia", province_id: 40, region_id:  9, country_id: 1, continent_id: 1 , population: 56028)
Municipality.create(description: "Bassiano", province_id: 40, region_id:  9, country_id: 1, continent_id: 1 , population: 1617)
Municipality.create(description: "Campodimele", province_id: 40, region_id:  9, country_id: 1, continent_id: 1 , population: 733)
Municipality.create(description: "Castelforte", province_id: 40, region_id:  9, country_id: 1, continent_id: 1 , population: 4518)
Municipality.create(description: "Cisterna Di Latina", province_id: 40, region_id:  9, country_id: 1, continent_id: 1 , population: 32584)
Municipality.create(description: "Cori", province_id: 40, region_id:  9, country_id: 1, continent_id: 1 , population: 10529)
Municipality.create(description: "Fondi", province_id: 40, region_id:  9, country_id: 1, continent_id: 1 , population: 31023)
Municipality.create(description: "Formia", province_id: 40, region_id:  9, country_id: 1, continent_id: 1 , population: 34931)
Municipality.create(description: "Gaeta", province_id: 40, region_id:  9, country_id: 1, continent_id: 1 , population: 21179)
Municipality.create(description: "Itri", province_id: 40, region_id:  9, country_id: 1, continent_id: 1 , population: 8749)
Municipality.create(description: "Latina", province_id: 40, region_id:  9, country_id: 1, continent_id: 1 , population: 107898)
Municipality.create(description: "Lenola", province_id: 40, region_id:  9, country_id: 1, continent_id: 1 , population: 4131)
Municipality.create(description: "Maenza", province_id: 40, region_id:  9, country_id: 1, continent_id: 1 , population: 3017)
Municipality.create(description: "Minturno", province_id: 40, region_id:  9, country_id: 1, continent_id: 1 , population: 17814)
Municipality.create(description: "Monte San Biagio", province_id: 40, region_id:  9, country_id: 1, continent_id: 1 , population: 5996)
Municipality.create(description: "Norma", province_id: 40, region_id:  9, country_id: 1, continent_id: 1 , population: 3792)
Municipality.create(description: "Pontinia", province_id: 40, region_id:  9, country_id: 1, continent_id: 1 , population: 13027)
Municipality.create(description: "Ponza", province_id: 40, region_id:  9, country_id: 1, continent_id: 1 , population: 3110)
Municipality.create(description: "Priverno", province_id: 40, region_id:  9, country_id: 1, continent_id: 1 , population: 13133)
Municipality.create(description: "Prossedi", province_id: 40, region_id:  9, country_id: 1, continent_id: 1 , population: 1248)
Municipality.create(description: "Rocca Massima", province_id: 40, region_id:  9, country_id: 1, continent_id: 1 , population: 1104)
Municipality.create(description: "Roccagorga", province_id: 40, region_id:  9, country_id: 1, continent_id: 1 , population: 4386)
Municipality.create(description: "Roccasecca Dei Volsci", province_id: 40, region_id:  9, country_id: 1, continent_id: 1 , population: 1201)
Municipality.create(description: "Sabaudia", province_id: 40, region_id:  9, country_id: 1, continent_id: 1 , population: 16229)
Municipality.create(description: "San Felice Circeo", province_id: 40, region_id:  9, country_id: 1, continent_id: 1 , population: 8036)
Municipality.create(description: "Santi Cosma E Damiano", province_id: 40, region_id:  9, country_id: 1, continent_id: 1 , population: 6532)
Municipality.create(description: "Sermoneta", province_id: 40, region_id:  9, country_id: 1, continent_id: 1 , population: 6620)
Municipality.create(description: "Sezze", province_id: 40, region_id:  9, country_id: 1, continent_id: 1 , population: 21935)
Municipality.create(description: "Sonnino", province_id: 40, region_id:  9, country_id: 1, continent_id: 1 , population: 7043)
Municipality.create(description: "Sperlonga", province_id: 40, region_id:  9, country_id: 1, continent_id: 1 , population: 3102)
Municipality.create(description: "Spigno Saturnia", province_id: 40, region_id:  9, country_id: 1, continent_id: 1 , population: 2719)
Municipality.create(description: "Terracina", province_id: 40, region_id:  9, country_id: 1, continent_id: 1 , population: 36633)
Municipality.create(description: "Ventotene", province_id: 40, region_id:  9, country_id: 1, continent_id: 1 , population: 633)
