Municipality.create(description: "Acqualagna", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 4178)
Municipality.create(description: "Apecchio", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 2112)
Municipality.create(description: "Auditore", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 1425)
Municipality.create(description: "Barchi", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 985)
Municipality.create(description: "Borgo Pace", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 661)
Municipality.create(description: "Cagli", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 9076)
Municipality.create(description: "Cantiano", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 2547)
Municipality.create(description: "Carpegna", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 1605)
Municipality.create(description: "Cartoceto", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 6490)
Municipality.create(description: "Casteldelci", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Colbordolo", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 5087)
Municipality.create(description: "Fano", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 57529)
Municipality.create(description: "Fermignano", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 7598)
Municipality.create(description: "Fossombrone", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 9591)
Municipality.create(description: "Fratte Rosa", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 1034)
Municipality.create(description: "Frontino", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 369)
Municipality.create(description: "Frontone", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 1301)
Municipality.create(description: "Gabicce Mare", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 5356)
Municipality.create(description: "Gradara", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 3381)
Municipality.create(description: "Isola Del Piano", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 664)
Municipality.create(description: "Lunano", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 1232)
Municipality.create(description: "Macerata Feltria", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 2025)
Municipality.create(description: "Maiolo", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Mercatello Sul Metauro", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 1448)
Municipality.create(description: "Mercatino Conca", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 1029)
Municipality.create(description: "Mombaroccio", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 1755)
Municipality.create(description: "Mondavio", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 3851)
Municipality.create(description: "Mondolfo", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 11090)
Municipality.create(description: "Monte Cerignone", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 688)
Municipality.create(description: "Monte Porzio", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 2227)
Municipality.create(description: "Montecalvo In Foglia", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 2363)
Municipality.create(description: "Monteciccardo", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 1296)
Municipality.create(description: "Montecopiolo", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 1264)
Municipality.create(description: "Montefelcino", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 2569)
Municipality.create(description: "Montegrimano", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 )
Municipality.create(description: "Montelabbate", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 5345)
Municipality.create(description: "Montemaggiore Al Metauro", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 2123)
Municipality.create(description: "Novafeltria", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Orciano Di Pesaro", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 2268)
Municipality.create(description: "Peglio", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 727)
Municipality.create(description: "Pennabilli", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Pergola", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 6810)
Municipality.create(description: "Pesaro", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 91086)
Municipality.create(description: "Petriano", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 2457)
Municipality.create(description: "Piagge", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 970)
Municipality.create(description: "Piandimeleto", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 1962)
Municipality.create(description: "Pietrarubbia", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 708)
Municipality.create(description: "Piobbico", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 2046)
Municipality.create(description: "Saltara", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 5101)
Municipality.create(description: "San Costanzo", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 4120)
Municipality.create(description: "San Giorgio Di Pesaro", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 1307)
Municipality.create(description: "San Leo", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "San Lorenzo In Campo", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 3356)
Municipality.create(description: "Sassocorvaro", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 3457)
Municipality.create(description: "Sassofeltrio", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 1229)
Municipality.create(description: "Serrungarina", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 2200)
Municipality.create(description: "Talamello", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Tavoleto", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 816)
Municipality.create(description: "Tavullia", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 4800)
Municipality.create(description: "Urbania", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 6643)
Municipality.create(description: "Urbino", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 15270)
Municipality.create(description: "Belforte All'Isauro", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 697)
Municipality.create(description: "Sant'Agata Feltria", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Sant'Angelo In Lizzola", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 6810)
Municipality.create(description: "Sant'Angelo In Vado", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 3868)
Municipality.create(description: "Sant'Ippolito", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 1513)
Municipality.create(description: "Serra Sant'Abbondio", province_id: 3, region_id:  1, country_id: 1, continent_id: 1 , population: 1187)
