#encoding: utf-8
Comune.create(:description => "Acqualagna", :provincia_id => 3, :regione_id => 1, :population => 4178)
Comune.create(:description => "Apecchio", :provincia_id => 3, :regione_id => 1, :population => 2112)
Comune.create(:description => "Auditore", :provincia_id => 3, :regione_id => 1, :population => 1425)
Comune.create(:description => "Barchi", :provincia_id => 3, :regione_id => 1, :population => 985)
Comune.create(:description => "Borgo Pace", :provincia_id => 3, :regione_id => 1, :population => 661)
Comune.create(:description => "Cagli", :provincia_id => 3, :regione_id => 1, :population => 9076)
Comune.create(:description => "Cantiano", :provincia_id => 3, :regione_id => 1, :population => 2547)
Comune.create(:description => "Carpegna", :provincia_id => 3, :regione_id => 1, :population => 1605)
Comune.create(:description => "Cartoceto", :provincia_id => 3, :regione_id => 1, :population => 6490)
Comune.create(:description => "Casteldelci", :provincia_id => 3, :regione_id => 1, :population => 0)
Comune.create(:description => "Colbordolo", :provincia_id => 3, :regione_id => 1, :population => 5087)
Comune.create(:description => "Fano", :provincia_id => 3, :regione_id => 1, :population => 57529)
Comune.create(:description => "Fermignano", :provincia_id => 3, :regione_id => 1, :population => 7598)
Comune.create(:description => "Fossombrone", :provincia_id => 3, :regione_id => 1, :population => 9591)
Comune.create(:description => "Fratte Rosa", :provincia_id => 3, :regione_id => 1, :population => 1034)
Comune.create(:description => "Frontino", :provincia_id => 3, :regione_id => 1, :population => 369)
Comune.create(:description => "Frontone", :provincia_id => 3, :regione_id => 1, :population => 1301)
Comune.create(:description => "Gabicce Mare", :provincia_id => 3, :regione_id => 1, :population => 5356)
Comune.create(:description => "Gradara", :provincia_id => 3, :regione_id => 1, :population => 3381)
Comune.create(:description => "Isola Del Piano", :provincia_id => 3, :regione_id => 1, :population => 664)
Comune.create(:description => "Lunano", :provincia_id => 3, :regione_id => 1, :population => 1232)
Comune.create(:description => "Macerata Feltria", :provincia_id => 3, :regione_id => 1, :population => 2025)
Comune.create(:description => "Maiolo", :provincia_id => 3, :regione_id => 1, :population => 0)
Comune.create(:description => "Mercatello Sul Metauro", :provincia_id => 3, :regione_id => 1, :population => 1448)
Comune.create(:description => "Mercatino Conca", :provincia_id => 3, :regione_id => 1, :population => 1029)
Comune.create(:description => "Mombaroccio", :provincia_id => 3, :regione_id => 1, :population => 1755)
Comune.create(:description => "Mondavio", :provincia_id => 3, :regione_id => 1, :population => 3851)
Comune.create(:description => "Mondolfo", :provincia_id => 3, :regione_id => 1, :population => 11090)
Comune.create(:description => "Monte Cerignone", :provincia_id => 3, :regione_id => 1, :population => 688)
Comune.create(:description => "Monte Porzio", :provincia_id => 3, :regione_id => 1, :population => 2227)
Comune.create(:description => "Montecalvo In Foglia", :provincia_id => 3, :regione_id => 1, :population => 2363)
Comune.create(:description => "Monteciccardo", :provincia_id => 3, :regione_id => 1, :population => 1296)
Comune.create(:description => "Montecopiolo", :provincia_id => 3, :regione_id => 1, :population => 1264)
Comune.create(:description => "Montefelcino", :provincia_id => 3, :regione_id => 1, :population => 2569)
Comune.create(:description => "Montegrimano", :provincia_id => 3, :regione_id => 1)
Comune.create(:description => "Montelabbate", :provincia_id => 3, :regione_id => 1, :population => 5345)
Comune.create(:description => "Montemaggiore Al Metauro", :provincia_id => 3, :regione_id => 1, :population => 2123)
Comune.create(:description => "Novafeltria", :provincia_id => 3, :regione_id => 1, :population => 0)
Comune.create(:description => "Orciano Di Pesaro", :provincia_id => 3, :regione_id => 1, :population => 2268)
Comune.create(:description => "Peglio", :provincia_id => 3, :regione_id => 1, :population => 727)
Comune.create(:description => "Pennabilli", :provincia_id => 3, :regione_id => 1, :population => 0)
Comune.create(:description => "Pergola", :provincia_id => 3, :regione_id => 1, :population => 6810)
Comune.create(:description => "Pesaro", :provincia_id => 3, :regione_id => 1, :population => 91086)
Comune.create(:description => "Petriano", :provincia_id => 3, :regione_id => 1, :population => 2457)
Comune.create(:description => "Piagge", :provincia_id => 3, :regione_id => 1, :population => 970)
Comune.create(:description => "Piandimeleto", :provincia_id => 3, :regione_id => 1, :population => 1962)
Comune.create(:description => "Pietrarubbia", :provincia_id => 3, :regione_id => 1, :population => 708)
Comune.create(:description => "Piobbico", :provincia_id => 3, :regione_id => 1, :population => 2046)
Comune.create(:description => "Saltara", :provincia_id => 3, :regione_id => 1, :population => 5101)
Comune.create(:description => "San Costanzo", :provincia_id => 3, :regione_id => 1, :population => 4120)
Comune.create(:description => "San Giorgio Di Pesaro", :provincia_id => 3, :regione_id => 1, :population => 1307)
Comune.create(:description => "San Leo", :provincia_id => 3, :regione_id => 1, :population => 0)
Comune.create(:description => "San Lorenzo In Campo", :provincia_id => 3, :regione_id => 1, :population => 3356)
Comune.create(:description => "Sassocorvaro", :provincia_id => 3, :regione_id => 1, :population => 3457)
Comune.create(:description => "Sassofeltrio", :provincia_id => 3, :regione_id => 1, :population => 1229)
Comune.create(:description => "Serrungarina", :provincia_id => 3, :regione_id => 1, :population => 2200)
Comune.create(:description => "Talamello", :provincia_id => 3, :regione_id => 1, :population => 0)
Comune.create(:description => "Tavoleto", :provincia_id => 3, :regione_id => 1, :population => 816)
Comune.create(:description => "Tavullia", :provincia_id => 3, :regione_id => 1, :population => 4800)
Comune.create(:description => "Urbania", :provincia_id => 3, :regione_id => 1, :population => 6643)
Comune.create(:description => "Urbino", :provincia_id => 3, :regione_id => 1, :population => 15270)
Comune.create(:description => "Belforte All'Isauro", :provincia_id => 3, :regione_id => 1, :population => 697)
Comune.create(:description => "Sant'Agata Feltria", :provincia_id => 3, :regione_id => 1, :population => 0)
Comune.create(:description => "Sant'Angelo In Lizzola", :provincia_id => 3, :regione_id => 1, :population => 6810)
Comune.create(:description => "Sant'Angelo In Vado", :provincia_id => 3, :regione_id => 1, :population => 3868)
Comune.create(:description => "Sant'Ippolito", :provincia_id => 3, :regione_id => 1, :population => 1513)
Comune.create(:description => "Serra Sant'Abbondio", :provincia_id => 3, :regione_id => 1, :population => 1187)
