Comune.create(description: "Accumoli", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 724)
Comune.create(description: "Amatrice", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 2807)
Comune.create(description: "Antrodoco", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 2845)
Comune.create(description: "Ascrea", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 284)
Comune.create(description: "Belmonte In Sabina", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 617)
Comune.create(description: "Borbona", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 725)
Comune.create(description: "Borgo Velino", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 922)
Comune.create(description: "Borgorose", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 4524)
Comune.create(description: "Cantalice", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 2875)
Comune.create(description: "Cantalupo In Sabina", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 1621)
Comune.create(description: "Casaprota", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 686)
Comune.create(description: "Casperia", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 1081)
Comune.create(description: "Castel Di Tora", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 286)
Comune.create(description: "Castelnuovo Di Farfa", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 929)
Comune.create(description: "Cittaducale", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 6542)
Comune.create(description: "Cittareale", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 482)
Comune.create(description: "Collalto Sabino", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 497)
Comune.create(description: "Colle Di Tora", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 383)
Comune.create(description: "Collegiove", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 176)
Comune.create(description: "Collevecchio", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 1480)
Comune.create(description: "Colli Sul Velino", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 516)
Comune.create(description: "Concerviano", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 386)
Comune.create(description: "Configni", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 705)
Comune.create(description: "Contigliano", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 3408)
Comune.create(description: "Cottanello", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 572)
Comune.create(description: "Fara In Sabina", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 10810)
Comune.create(description: "Fiamignano", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 1603)
Comune.create(description: "Forano", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 2453)
Comune.create(description: "Frasso Sabino", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 632)
Comune.create(description: "Greccio", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 1464)
Comune.create(description: "Labro", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 352)
Comune.create(description: "Leonessa", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 2734)
Comune.create(description: "Longone Sabino", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 682)
Comune.create(description: "Magliano Sabina", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 3745)
Comune.create(description: "Marcetelli", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 126)
Comune.create(description: "Micigliano", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 140)
Comune.create(description: "Mompeo", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 563)
Comune.create(description: "Montasola", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 368)
Comune.create(description: "Monte San Giovanni In Sabina", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 728)
Comune.create(description: "Montebuono", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 913)
Comune.create(description: "Monteleone Sabino", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 1274)
Comune.create(description: "Montenero Sabino", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 345)
Comune.create(description: "Montopoli Di Sabina", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 3698)
Comune.create(description: "Morro Reatino", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 377)
Comune.create(description: "Nespolo", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 224)
Comune.create(description: "Orvinio", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 427)
Comune.create(description: "Paganico Sabino", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 180)
Comune.create(description: "Pescorocchiano", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 2553)
Comune.create(description: "Petrella Salto", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 1326)
Comune.create(description: "Poggio Bustone", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 2094)
Comune.create(description: "Poggio Catino", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 1220)
Comune.create(description: "Poggio Mirteto", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 5168)
Comune.create(description: "Poggio Moiano", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 2510)
Comune.create(description: "Poggio Nativo", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 2049)
Comune.create(description: "Poggio San Lorenzo", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 523)
Comune.create(description: "Posta", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 824)
Comune.create(description: "Pozzaglia Sabino", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 )
Comune.create(description: "Rieti", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 43785)
Comune.create(description: "Rivodutri", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 1278)
Comune.create(description: "Rocca Sinibalda", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 825)
Comune.create(description: "Roccantica", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 631)
Comune.create(description: "Salisano", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 552)
Comune.create(description: "Scandriglia", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 2426)
Comune.create(description: "Selci", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 1000)
Comune.create(description: "Stimigliano", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 1744)
Comune.create(description: "Tarano", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 1198)
Comune.create(description: "Toffia", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 905)
Comune.create(description: "Torri In Sabina", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 1197)
Comune.create(description: "Torricella In Sabina", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 1216)
Comune.create(description: "Turania", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 272)
Comune.create(description: "Vacone", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 247)
Comune.create(description: "Varco Sabino", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 263)
Comune.create(description: "Castel Sant'Angelo", province_id: 41, region_id:  9, country_id: 1, continent_id: 1 , population: 1282)
