Comune.create(description: "Acquapendente", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 5788)
Comune.create(description: "Arlena Di Castro", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 867)
Comune.create(description: "Bagnoregio", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 3639)
Comune.create(description: "Barbarano Romano", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 950)
Comune.create(description: "Bassano In Teverina", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 1134)
Comune.create(description: "Bassano Romano", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 4277)
Comune.create(description: "Blera", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 3208)
Comune.create(description: "Bolsena", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 4111)
Comune.create(description: "Bomarzo", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 1615)
Comune.create(description: "Calcata", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 846)
Comune.create(description: "Canepina", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 3095)
Comune.create(description: "Canino", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 5072)
Comune.create(description: "Capodimonte", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 1686)
Comune.create(description: "Capranica", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 5604)
Comune.create(description: "Caprarola", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 5197)
Comune.create(description: "Carbognano", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 1918)
Comune.create(description: "Castiglione In Teverina", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 2261)
Comune.create(description: "Celleno", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 1339)
Comune.create(description: "Cellere", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 1301)
Comune.create(description: "Civita Castellana", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 15219)
Comune.create(description: "Corchiano", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 3337)
Comune.create(description: "Fabrica Di Roma", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 6654)
Comune.create(description: "Faleria", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 1728)
Comune.create(description: "Farnese", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 1729)
Comune.create(description: "Gallese", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 2757)
Comune.create(description: "Gradoli", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 1496)
Comune.create(description: "Graffignano", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 2288)
Comune.create(description: "Grotte Di Castro", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 2967)
Comune.create(description: "Ischia Di Castro", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 2464)
Comune.create(description: "Latera", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 1023)
Comune.create(description: "Lubriano", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 918)
Comune.create(description: "Marta", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 3436)
Comune.create(description: "Montalto Di Castro", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 7653)
Comune.create(description: "Monte Romano", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 1939)
Comune.create(description: "Montefiascone", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 12653)
Comune.create(description: "Monterosi", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 2381)
Comune.create(description: "Nepi", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 7827)
Comune.create(description: "Onano", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 1169)
Comune.create(description: "Oriolo Romano", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 2920)
Comune.create(description: "Orte", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 7781)
Comune.create(description: "Piansano", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 2220)
Comune.create(description: "Proceno", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 632)
Comune.create(description: "Ronciglione", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 7470)
Comune.create(description: "San Lorenzo Nuovo", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 2067)
Comune.create(description: "Soriano Nel Cimino", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 8185)
Comune.create(description: "Sutri", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 5055)
Comune.create(description: "Tarquinia", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 15162)
Comune.create(description: "Tessennano", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 420)
Comune.create(description: "Tuscania", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 7717)
Comune.create(description: "Valentano", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 2935)
Comune.create(description: "Vallerano", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 2505)
Comune.create(description: "Vasanello", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 3890)
Comune.create(description: "Vejano", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 2085)
Comune.create(description: "Vetralla", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 11917)
Comune.create(description: "Vignanello", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 4705)
Comune.create(description: "Villa San Giovanni In Tuscia", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 1164)
Comune.create(description: "Viterbo", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 59308)
Comune.create(description: "Vitorchiano", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 3214)
Comune.create(description: "Castel Sant'Elia", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 2151)
Comune.create(description: "Civitella D'Agliano", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 1734)
