Comune.create(description: "Acquapendente", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 5788)
Comune.create(description: "Arlena Di Castro", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 867)
Comune.create(description: "Bagnoregio", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 3639)
Comune.create(description: "Barbarano Romano", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 950)
Comune.create(description: "Bassano In Teverina", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 1134)
Comune.create(description: "Bassano Romano", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 4277)
Comune.create(description: "Blera", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 3208)
Comune.create(description: "Bolsena", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 4111)
Comune.create(description: "Bomarzo", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 1615)
Comune.create(description: "Calcata", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 846)
Comune.create(description: "Canepina", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 3095)
Comune.create(description: "Canino", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 5072)
Comune.create(description: "Capodimonte", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 1686)
Comune.create(description: "Capranica", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 5604)
Comune.create(description: "Caprarola", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 5197)
Comune.create(description: "Carbognano", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 1918)
Comune.create(description: "Castiglione In Teverina", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 2261)
Comune.create(description: "Celleno", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 1339)
Comune.create(description: "Cellere", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 1301)
Comune.create(description: "Civita Castellana", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 15219)
Comune.create(description: "Corchiano", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 3337)
Comune.create(description: "Fabrica Di Roma", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 6654)
Comune.create(description: "Faleria", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 1728)
Comune.create(description: "Farnese", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 1729)
Comune.create(description: "Gallese", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 2757)
Comune.create(description: "Gradoli", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 1496)
Comune.create(description: "Graffignano", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 2288)
Comune.create(description: "Grotte Di Castro", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 2967)
Comune.create(description: "Ischia Di Castro", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 2464)
Comune.create(description: "Latera", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 1023)
Comune.create(description: "Lubriano", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 918)
Comune.create(description: "Marta", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 3436)
Comune.create(description: "Montalto Di Castro", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 7653)
Comune.create(description: "Monte Romano", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 1939)
Comune.create(description: "Montefiascone", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 12653)
Comune.create(description: "Monterosi", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 2381)
Comune.create(description: "Nepi", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 7827)
Comune.create(description: "Onano", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 1169)
Comune.create(description: "Oriolo Romano", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 2920)
Comune.create(description: "Orte", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 7781)
Comune.create(description: "Piansano", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 2220)
Comune.create(description: "Proceno", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 632)
Comune.create(description: "Ronciglione", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 7470)
Comune.create(description: "San Lorenzo Nuovo", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 2067)
Comune.create(description: "Soriano Nel Cimino", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 8185)
Comune.create(description: "Sutri", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 5055)
Comune.create(description: "Tarquinia", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 15162)
Comune.create(description: "Tessennano", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 420)
Comune.create(description: "Tuscania", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 7717)
Comune.create(description: "Valentano", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 2935)
Comune.create(description: "Vallerano", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 2505)
Comune.create(description: "Vasanello", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 3890)
Comune.create(description: "Vejano", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 2085)
Comune.create(description: "Vetralla", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 11917)
Comune.create(description: "Vignanello", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 4705)
Comune.create(description: "Villa San Giovanni In Tuscia", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 1164)
Comune.create(description: "Viterbo", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 59308)
Comune.create(description: "Vitorchiano", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 3214)
Comune.create(description: "Castel Sant'Elia", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 2151)
Comune.create(description: "Civitella D'Agliano", provincia_id: 43, regione_id: 9, country_id: 1, continent_id: 1 , population: 1734)
