Municipality.create(description: "Acquapendente", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 5788)
Municipality.create(description: "Arlena Di Castro", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 867)
Municipality.create(description: "Bagnoregio", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 3639)
Municipality.create(description: "Barbarano Romano", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 950)
Municipality.create(description: "Bassano In Teverina", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 1134)
Municipality.create(description: "Bassano Romano", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 4277)
Municipality.create(description: "Blera", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 3208)
Municipality.create(description: "Bolsena", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 4111)
Municipality.create(description: "Bomarzo", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 1615)
Municipality.create(description: "Calcata", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 846)
Municipality.create(description: "Canepina", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 3095)
Municipality.create(description: "Canino", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 5072)
Municipality.create(description: "Capodimonte", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 1686)
Municipality.create(description: "Capranica", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 5604)
Municipality.create(description: "Caprarola", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 5197)
Municipality.create(description: "Carbognano", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 1918)
Municipality.create(description: "Castiglione In Teverina", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 2261)
Municipality.create(description: "Celleno", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 1339)
Municipality.create(description: "Cellere", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 1301)
Municipality.create(description: "Civita Castellana", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 15219)
Municipality.create(description: "Corchiano", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 3337)
Municipality.create(description: "Fabrica Di Roma", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 6654)
Municipality.create(description: "Faleria", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 1728)
Municipality.create(description: "Farnese", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 1729)
Municipality.create(description: "Gallese", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 2757)
Municipality.create(description: "Gradoli", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 1496)
Municipality.create(description: "Graffignano", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 2288)
Municipality.create(description: "Grotte Di Castro", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 2967)
Municipality.create(description: "Ischia Di Castro", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 2464)
Municipality.create(description: "Latera", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 1023)
Municipality.create(description: "Lubriano", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 918)
Municipality.create(description: "Marta", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 3436)
Municipality.create(description: "Montalto Di Castro", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 7653)
Municipality.create(description: "Monte Romano", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 1939)
Municipality.create(description: "Montefiascone", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 12653)
Municipality.create(description: "Monterosi", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 2381)
Municipality.create(description: "Nepi", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 7827)
Municipality.create(description: "Onano", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 1169)
Municipality.create(description: "Oriolo Romano", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 2920)
Municipality.create(description: "Orte", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 7781)
Municipality.create(description: "Piansano", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 2220)
Municipality.create(description: "Proceno", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 632)
Municipality.create(description: "Ronciglione", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 7470)
Municipality.create(description: "San Lorenzo Nuovo", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 2067)
Municipality.create(description: "Soriano Nel Cimino", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 8185)
Municipality.create(description: "Sutri", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 5055)
Municipality.create(description: "Tarquinia", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 15162)
Municipality.create(description: "Tessennano", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 420)
Municipality.create(description: "Tuscania", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 7717)
Municipality.create(description: "Valentano", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 2935)
Municipality.create(description: "Vallerano", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 2505)
Municipality.create(description: "Vasanello", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 3890)
Municipality.create(description: "Vejano", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 2085)
Municipality.create(description: "Vetralla", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 11917)
Municipality.create(description: "Vignanello", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 4705)
Municipality.create(description: "Villa San Giovanni In Tuscia", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 1164)
Municipality.create(description: "Viterbo", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 59308)
Municipality.create(description: "Vitorchiano", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 3214)
Municipality.create(description: "Castel Sant'Elia", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 2151)
Municipality.create(description: "Civitella D'Agliano", province_id: 43, region_id:  9, country_id: 1, continent_id: 1 , population: 1734)
