Municipality.create(description: "Altino", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 2536)
Municipality.create(description: "Archi", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 2336)
Municipality.create(description: "Ari", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1328)
Municipality.create(description: "Arielli", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1250)
Municipality.create(description: "Atessa", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 10388)
Municipality.create(description: "Bomba", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 972)
Municipality.create(description: "Borrello", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 444)
Municipality.create(description: "Bucchianico", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 4941)
Municipality.create(description: "Canosa Sannita", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1510)
Municipality.create(description: "Carpineto Sinello", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 746)
Municipality.create(description: "Carunchio", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 781)
Municipality.create(description: "Casacanditella", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1397)
Municipality.create(description: "Casalanguida", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1096)
Municipality.create(description: "Casalbordino", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 6478)
Municipality.create(description: "Casalincontrada", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 2942)
Municipality.create(description: "Casoli", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 5971)
Municipality.create(description: "Castel Frentano", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 3913)
Municipality.create(description: "Castelguidone", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 482)
Municipality.create(description: "Castiglione Messer Marino", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 2225)
Municipality.create(description: "Celenza Sul Trigno", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1098)
Municipality.create(description: "Chieti", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 52486)
Municipality.create(description: "Civitaluparella", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 429)
Municipality.create(description: "Civitella Messer Raimondo", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 972)
Municipality.create(description: "Colledimacine", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 286)
Municipality.create(description: "Colledimezzo", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 592)
Municipality.create(description: "Crecchio", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 3052)
Municipality.create(description: "Cupello", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 4415)
Municipality.create(description: "Dogliola", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 415)
Municipality.create(description: "Fallo", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 162)
Municipality.create(description: "Fara Filiorum Petri", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1952)
Municipality.create(description: "Fara San Martino", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1626)
Municipality.create(description: "Filetto", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1119)
Municipality.create(description: "Fossacesia", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 5349)
Municipality.create(description: "Fraine", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 463)
Municipality.create(description: "Francavilla Al Mare", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 22883)
Municipality.create(description: "Fresagrandinaria", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1088)
Municipality.create(description: "Frisa", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1940)
Municipality.create(description: "Furci", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1275)
Municipality.create(description: "Gamberale", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 394)
Municipality.create(description: "Gessopalena", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1694)
Municipality.create(description: "Gissi", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 3088)
Municipality.create(description: "Giuliano Teatino", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1306)
Municipality.create(description: "Guardiagrele", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 9527)
Municipality.create(description: "Guilmi", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 520)
Municipality.create(description: "Lama Dei Peligni", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1486)
Municipality.create(description: "Lanciano", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 35798)
Municipality.create(description: "Lentella", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 768)
Municipality.create(description: "Lettopalena", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 409)
Municipality.create(description: "Liscia", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 813)
Municipality.create(description: "Miglianico", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 4503)
Municipality.create(description: "Montazzoli", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1116)
Municipality.create(description: "Montebello Sul Sangro", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 125)
Municipality.create(description: "Monteferrante", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 190)
Municipality.create(description: "Montelapiano", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 107)
Municipality.create(description: "Montenerodomo", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 936)
Municipality.create(description: "Monteodorisio", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 2402)
Municipality.create(description: "Mozzagrogna", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 2060)
Municipality.create(description: "Orsogna", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 4050)
Municipality.create(description: "Ortona", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 22694)
Municipality.create(description: "Paglieta", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 4401)
Municipality.create(description: "Palena", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1478)
Municipality.create(description: "Palmoli", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1162)
Municipality.create(description: "Palombaro", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1177)
Municipality.create(description: "Pennadomo", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 358)
Municipality.create(description: "Pennapiedimonte", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 556)
Municipality.create(description: "Perano", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1656)
Municipality.create(description: "Pietraferrazzana", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 152)
Municipality.create(description: "Pizzoferrato", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1189)
Municipality.create(description: "Poggiofiorito", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 951)
Municipality.create(description: "Pollutri", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 2345)
Municipality.create(description: "Pretoro", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1107)
Municipality.create(description: "Quadri", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 943)
Municipality.create(description: "Rapino", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1433)
Municipality.create(description: "Ripa Teatina", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 3834)
Municipality.create(description: "Rocca San Giovanni", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 2352)
Municipality.create(description: "Roccamontepiano", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1965)
Municipality.create(description: "Roccascalegna", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1423)
Municipality.create(description: "Roccaspinalveti", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1671)
Municipality.create(description: "Roio Del Sangro", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 159)
Municipality.create(description: "Rosello", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 342)
Municipality.create(description: "San Buono", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1202)
Municipality.create(description: "San Giovanni Lipioni", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 287)
Municipality.create(description: "San Giovanni Teatino", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 10048)
Municipality.create(description: "San Martino Sulla Marrucina", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 981)
Municipality.create(description: "San Salvo", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 17254)
Municipality.create(description: "San Vito Chietino", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 4901)
Municipality.create(description: "Santa Maria Imbaro", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1735)
Municipality.create(description: "Scerni", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 3704)
Municipality.create(description: "Schiavi Di Abruzzo", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1403)
Municipality.create(description: "Taranta Peligna", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 521)
Municipality.create(description: "Tollo", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 4171)
Municipality.create(description: "Torino Di Sangro", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 3079)
Municipality.create(description: "Tornareccio", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1948)
Municipality.create(description: "Torrebruna", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1173)
Municipality.create(description: "Torrevecchia Teatina", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 3746)
Municipality.create(description: "Torricella Peligna", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1587)
Municipality.create(description: "Treglio", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1236)
Municipality.create(description: "Tufillo", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 564)
Municipality.create(description: "Vacri", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1756)
Municipality.create(description: "Vasto", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 35362)
Municipality.create(description: "Villa Santa Maria", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1479)
Municipality.create(description: "Villalfonsina", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1062)
Municipality.create(description: "Villamagna", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 2448)
Municipality.create(description: "Sant'Eusanio Del Sangro", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 2451)
