Comune.create(description: "Altino", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 2536)
Comune.create(description: "Archi", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 2336)
Comune.create(description: "Ari", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1328)
Comune.create(description: "Arielli", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1250)
Comune.create(description: "Atessa", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 10388)
Comune.create(description: "Bomba", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 972)
Comune.create(description: "Borrello", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 444)
Comune.create(description: "Bucchianico", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 4941)
Comune.create(description: "Canosa Sannita", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1510)
Comune.create(description: "Carpineto Sinello", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 746)
Comune.create(description: "Carunchio", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 781)
Comune.create(description: "Casacanditella", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1397)
Comune.create(description: "Casalanguida", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1096)
Comune.create(description: "Casalbordino", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 6478)
Comune.create(description: "Casalincontrada", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 2942)
Comune.create(description: "Casoli", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 5971)
Comune.create(description: "Castel Frentano", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 3913)
Comune.create(description: "Castelguidone", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 482)
Comune.create(description: "Castiglione Messer Marino", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 2225)
Comune.create(description: "Celenza Sul Trigno", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1098)
Comune.create(description: "Chieti", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 52486)
Comune.create(description: "Civitaluparella", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 429)
Comune.create(description: "Civitella Messer Raimondo", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 972)
Comune.create(description: "Colledimacine", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 286)
Comune.create(description: "Colledimezzo", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 592)
Comune.create(description: "Crecchio", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 3052)
Comune.create(description: "Cupello", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 4415)
Comune.create(description: "Dogliola", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 415)
Comune.create(description: "Fallo", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 162)
Comune.create(description: "Fara Filiorum Petri", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1952)
Comune.create(description: "Fara San Martino", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1626)
Comune.create(description: "Filetto", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1119)
Comune.create(description: "Fossacesia", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 5349)
Comune.create(description: "Fraine", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 463)
Comune.create(description: "Francavilla Al Mare", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 22883)
Comune.create(description: "Fresagrandinaria", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1088)
Comune.create(description: "Frisa", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1940)
Comune.create(description: "Furci", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1275)
Comune.create(description: "Gamberale", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 394)
Comune.create(description: "Gessopalena", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1694)
Comune.create(description: "Gissi", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 3088)
Comune.create(description: "Giuliano Teatino", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1306)
Comune.create(description: "Guardiagrele", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 9527)
Comune.create(description: "Guilmi", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 520)
Comune.create(description: "Lama Dei Peligni", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1486)
Comune.create(description: "Lanciano", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 35798)
Comune.create(description: "Lentella", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 768)
Comune.create(description: "Lettopalena", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 409)
Comune.create(description: "Liscia", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 813)
Comune.create(description: "Miglianico", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 4503)
Comune.create(description: "Montazzoli", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1116)
Comune.create(description: "Montebello Sul Sangro", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 125)
Comune.create(description: "Monteferrante", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 190)
Comune.create(description: "Montelapiano", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 107)
Comune.create(description: "Montenerodomo", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 936)
Comune.create(description: "Monteodorisio", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 2402)
Comune.create(description: "Mozzagrogna", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 2060)
Comune.create(description: "Orsogna", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 4050)
Comune.create(description: "Ortona", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 22694)
Comune.create(description: "Paglieta", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 4401)
Comune.create(description: "Palena", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1478)
Comune.create(description: "Palmoli", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1162)
Comune.create(description: "Palombaro", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1177)
Comune.create(description: "Pennadomo", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 358)
Comune.create(description: "Pennapiedimonte", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 556)
Comune.create(description: "Perano", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1656)
Comune.create(description: "Pietraferrazzana", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 152)
Comune.create(description: "Pizzoferrato", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1189)
Comune.create(description: "Poggiofiorito", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 951)
Comune.create(description: "Pollutri", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 2345)
Comune.create(description: "Pretoro", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1107)
Comune.create(description: "Quadri", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 943)
Comune.create(description: "Rapino", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1433)
Comune.create(description: "Ripa Teatina", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 3834)
Comune.create(description: "Rocca San Giovanni", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 2352)
Comune.create(description: "Roccamontepiano", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1965)
Comune.create(description: "Roccascalegna", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1423)
Comune.create(description: "Roccaspinalveti", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1671)
Comune.create(description: "Roio Del Sangro", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 159)
Comune.create(description: "Rosello", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 342)
Comune.create(description: "San Buono", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1202)
Comune.create(description: "San Giovanni Lipioni", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 287)
Comune.create(description: "San Giovanni Teatino", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 10048)
Comune.create(description: "San Martino Sulla Marrucina", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 981)
Comune.create(description: "San Salvo", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 17254)
Comune.create(description: "San Vito Chietino", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 4901)
Comune.create(description: "Santa Maria Imbaro", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1735)
Comune.create(description: "Scerni", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 3704)
Comune.create(description: "Schiavi Di Abruzzo", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1403)
Comune.create(description: "Taranta Peligna", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 521)
Comune.create(description: "Tollo", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 4171)
Comune.create(description: "Torino Di Sangro", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 3079)
Comune.create(description: "Tornareccio", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1948)
Comune.create(description: "Torrebruna", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1173)
Comune.create(description: "Torrevecchia Teatina", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 3746)
Comune.create(description: "Torricella Peligna", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1587)
Comune.create(description: "Treglio", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1236)
Comune.create(description: "Tufillo", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 564)
Comune.create(description: "Vacri", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1756)
Comune.create(description: "Vasto", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 35362)
Comune.create(description: "Villa Santa Maria", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1479)
Comune.create(description: "Villalfonsina", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 1062)
Comune.create(description: "Villamagna", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 2448)
Comune.create(description: "Sant'Eusanio Del Sangro", province_id: 44, region_id:  2, country_id: 1, continent_id: 1 , population: 2451)
