Municipality.create(description: "Gagliano Aterno", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 314)
Municipality.create(description: "Gioia Dei Marsi", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 2284)
Municipality.create(description: "Goriano Sicoli", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 633)
Municipality.create(description: "Introdacqua", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1831)
Municipality.create(description: "Lecce Nei Marsi", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1752)
Municipality.create(description: "Luco Dei Marsi", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 5541)
Municipality.create(description: "Lucoli", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 944)
Municipality.create(description: "Molina Aterno", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 463)
Municipality.create(description: "Montereale", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 2930)
Municipality.create(description: "Morino", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1545)
Municipality.create(description: "Navelli", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 625)
Municipality.create(description: "Ocre", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1020)
Municipality.create(description: "Ofena", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 611)
Municipality.create(description: "Opi", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 462)
Municipality.create(description: "Oricola", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 950)
Municipality.create(description: "Ortona Dei Marsi", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 803)
Municipality.create(description: "Ortucchio", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1978)
Municipality.create(description: "Ovindoli", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1200)
Municipality.create(description: "Pacentro", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1279)
Municipality.create(description: "Pereto", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 704)
Municipality.create(description: "Pescasseroli", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 2130)
Municipality.create(description: "Pescina", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 4506)
Municipality.create(description: "Pescocostanzo", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1216)
Municipality.create(description: "Pettorano Sul Gizio", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1255)
Municipality.create(description: "Pizzoli", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 3047)
Municipality.create(description: "Poggio Picenze", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1011)
Municipality.create(description: "Pratola Peligna", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 7814)
Municipality.create(description: "Prezza", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1092)
Municipality.create(description: "Raiano", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 2973)
Municipality.create(description: "Rivisondoli", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 686)
Municipality.create(description: "Rocca Di Botte", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 522)
Municipality.create(description: "Rocca Di Cambio", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 447)
Municipality.create(description: "Rocca Di Mezzo", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1426)
Municipality.create(description: "Rocca Pia", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 189)
Municipality.create(description: "Roccacasale", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 754)
Municipality.create(description: "Roccaraso", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1604)
Municipality.create(description: "San Benedetto Dei Marsi", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 4006)
Municipality.create(description: "San Benedetto In Perillis", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 145)
Municipality.create(description: "San Pio Delle Camere", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 554)
Municipality.create(description: "San Vincenzo Valle Roveto", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 2577)
Municipality.create(description: "Sante Marie", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1342)
Municipality.create(description: "Santo Stefano Di Sessanio", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 118)
Municipality.create(description: "Scanno", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 2133)
Municipality.create(description: "Scontrone", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 595)
Municipality.create(description: "Scoppito", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 2757)
Municipality.create(description: "Scurcola Marsicana", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 2501)
Municipality.create(description: "Secinaro", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 480)
Municipality.create(description: "Sulmona", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 25304)
Municipality.create(description: "Tagliacozzo", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 6532)
Municipality.create(description: "Tione Degli Abruzzi", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 380)
Municipality.create(description: "Tornimparte", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 2958)
Municipality.create(description: "Trasacco", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 5998)
Municipality.create(description: "Villa Santa Lucia Degli Abruzzi", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 206)
Municipality.create(description: "Villalago", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 636)
Municipality.create(description: "Villavallelonga", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1004)
Municipality.create(description: "Villetta Barrea", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 595)
Municipality.create(description: "Vittorito", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1012)
Municipality.create(description: "Acciano", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 401)
Municipality.create(description: "Aielli", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1477)
Municipality.create(description: "Alfedena", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 716)
Municipality.create(description: "Anversa Degli Abruzzi", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 431)
Municipality.create(description: "Ateleta", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1232)
Municipality.create(description: "Avezzano", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 38337)
Municipality.create(description: "Balsorano", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 3705)
Municipality.create(description: "Barete", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 633)
Municipality.create(description: "Barisciano", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1798)
Municipality.create(description: "Barrea", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 776)
Municipality.create(description: "Bisegna", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 342)
Municipality.create(description: "Bugnara", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1035)
Municipality.create(description: "Cagnano Amiterno", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1509)
Municipality.create(description: "Calascio", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 150)
Municipality.create(description: "Campo Di Giove", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 907)
Municipality.create(description: "Campotosto", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 683)
Municipality.create(description: "Canistro", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1042)
Municipality.create(description: "Cansano", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 270)
Municipality.create(description: "Capestrano", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 960)
Municipality.create(description: "Capistrello", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 5429)
Municipality.create(description: "Capitignano", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 689)
Municipality.create(description: "Caporciano", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 265)
Municipality.create(description: "Cappadocia", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 519)
Municipality.create(description: "Carapelle Calvisio", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 95)
Municipality.create(description: "Carsoli", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 5086)
Municipality.create(description: "Castel Del Monte", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 527)
Municipality.create(description: "Castel Di Ieri", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 405)
Municipality.create(description: "Castel Di Sangro", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 5626)
Municipality.create(description: "Castellafiume", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1049)
Municipality.create(description: "Castelvecchio Calvisio", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 198)
Municipality.create(description: "Castelvecchio Subequo", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1241)
Municipality.create(description: "Celano", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 10975)
Municipality.create(description: "Cerchio", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1669)
Municipality.create(description: "Civitella Alfedena", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 280)
Municipality.create(description: "Civitella Roveto", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 3330)
Municipality.create(description: "Cocullo", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 317)
Municipality.create(description: "Collarmele", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1055)
Municipality.create(description: "Collelongo", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1514)
Municipality.create(description: "Collepietro", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 270)
Municipality.create(description: "Corfinio", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 997)
Municipality.create(description: "Fagnano Alto", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 446)
Municipality.create(description: "Fontecchio", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 422)
Municipality.create(description: "Fossa", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 661)
Municipality.create(description: "Civita D'Antino", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1076)
Municipality.create(description: "L'Aquila", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 68503)
Municipality.create(description: "Magliano De' Marsi", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 3540)
Municipality.create(description: "Massa D'Albe", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1436)
Municipality.create(description: "Prata D'Ansidonia", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 547)
Municipality.create(description: "San Demetrio Ne' Vestini", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1605)
Municipality.create(description: "Sant'Eusanio Forconese", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 443)
Municipality.create(description: "Villa Sant'Angelo", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 431)
