Comune.create(description: "Gagliano Aterno", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 314)
Comune.create(description: "Gioia Dei Marsi", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 2284)
Comune.create(description: "Goriano Sicoli", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 633)
Comune.create(description: "Introdacqua", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1831)
Comune.create(description: "Lecce Nei Marsi", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1752)
Comune.create(description: "Luco Dei Marsi", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 5541)
Comune.create(description: "Lucoli", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 944)
Comune.create(description: "Molina Aterno", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 463)
Comune.create(description: "Montereale", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 2930)
Comune.create(description: "Morino", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1545)
Comune.create(description: "Navelli", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 625)
Comune.create(description: "Ocre", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1020)
Comune.create(description: "Ofena", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 611)
Comune.create(description: "Opi", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 462)
Comune.create(description: "Oricola", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 950)
Comune.create(description: "Ortona Dei Marsi", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 803)
Comune.create(description: "Ortucchio", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1978)
Comune.create(description: "Ovindoli", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1200)
Comune.create(description: "Pacentro", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1279)
Comune.create(description: "Pereto", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 704)
Comune.create(description: "Pescasseroli", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 2130)
Comune.create(description: "Pescina", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 4506)
Comune.create(description: "Pescocostanzo", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1216)
Comune.create(description: "Pettorano Sul Gizio", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1255)
Comune.create(description: "Pizzoli", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 3047)
Comune.create(description: "Poggio Picenze", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1011)
Comune.create(description: "Pratola Peligna", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 7814)
Comune.create(description: "Prezza", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1092)
Comune.create(description: "Raiano", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 2973)
Comune.create(description: "Rivisondoli", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 686)
Comune.create(description: "Rocca Di Botte", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 522)
Comune.create(description: "Rocca Di Cambio", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 447)
Comune.create(description: "Rocca Di Mezzo", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1426)
Comune.create(description: "Rocca Pia", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 189)
Comune.create(description: "Roccacasale", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 754)
Comune.create(description: "Roccaraso", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1604)
Comune.create(description: "San Benedetto Dei Marsi", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 4006)
Comune.create(description: "San Benedetto In Perillis", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 145)
Comune.create(description: "San Pio Delle Camere", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 554)
Comune.create(description: "San Vincenzo Valle Roveto", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 2577)
Comune.create(description: "Sante Marie", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1342)
Comune.create(description: "Santo Stefano Di Sessanio", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 118)
Comune.create(description: "Scanno", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 2133)
Comune.create(description: "Scontrone", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 595)
Comune.create(description: "Scoppito", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 2757)
Comune.create(description: "Scurcola Marsicana", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 2501)
Comune.create(description: "Secinaro", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 480)
Comune.create(description: "Sulmona", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 25304)
Comune.create(description: "Tagliacozzo", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 6532)
Comune.create(description: "Tione Degli Abruzzi", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 380)
Comune.create(description: "Tornimparte", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 2958)
Comune.create(description: "Trasacco", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 5998)
Comune.create(description: "Villa Santa Lucia Degli Abruzzi", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 206)
Comune.create(description: "Villalago", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 636)
Comune.create(description: "Villavallelonga", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1004)
Comune.create(description: "Villetta Barrea", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 595)
Comune.create(description: "Vittorito", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1012)
Comune.create(description: "Acciano", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 401)
Comune.create(description: "Aielli", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1477)
Comune.create(description: "Alfedena", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 716)
Comune.create(description: "Anversa Degli Abruzzi", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 431)
Comune.create(description: "Ateleta", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1232)
Comune.create(description: "Avezzano", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 38337)
Comune.create(description: "Balsorano", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 3705)
Comune.create(description: "Barete", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 633)
Comune.create(description: "Barisciano", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1798)
Comune.create(description: "Barrea", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 776)
Comune.create(description: "Bisegna", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 342)
Comune.create(description: "Bugnara", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1035)
Comune.create(description: "Cagnano Amiterno", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1509)
Comune.create(description: "Calascio", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 150)
Comune.create(description: "Campo Di Giove", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 907)
Comune.create(description: "Campotosto", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 683)
Comune.create(description: "Canistro", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1042)
Comune.create(description: "Cansano", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 270)
Comune.create(description: "Capestrano", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 960)
Comune.create(description: "Capistrello", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 5429)
Comune.create(description: "Capitignano", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 689)
Comune.create(description: "Caporciano", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 265)
Comune.create(description: "Cappadocia", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 519)
Comune.create(description: "Carapelle Calvisio", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 95)
Comune.create(description: "Carsoli", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 5086)
Comune.create(description: "Castel Del Monte", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 527)
Comune.create(description: "Castel Di Ieri", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 405)
Comune.create(description: "Castel Di Sangro", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 5626)
Comune.create(description: "Castellafiume", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1049)
Comune.create(description: "Castelvecchio Calvisio", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 198)
Comune.create(description: "Castelvecchio Subequo", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1241)
Comune.create(description: "Celano", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 10975)
Comune.create(description: "Cerchio", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1669)
Comune.create(description: "Civitella Alfedena", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 280)
Comune.create(description: "Civitella Roveto", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 3330)
Comune.create(description: "Cocullo", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 317)
Comune.create(description: "Collarmele", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1055)
Comune.create(description: "Collelongo", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1514)
Comune.create(description: "Collepietro", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 270)
Comune.create(description: "Corfinio", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 997)
Comune.create(description: "Fagnano Alto", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 446)
Comune.create(description: "Fontecchio", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 422)
Comune.create(description: "Fossa", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 661)
Comune.create(description: "Civita D'Antino", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1076)
Comune.create(description: "L'Aquila", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 68503)
Comune.create(description: "Magliano De' Marsi", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 3540)
Comune.create(description: "Massa D'Albe", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1436)
Comune.create(description: "Prata D'Ansidonia", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 547)
Comune.create(description: "San Demetrio Ne' Vestini", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 1605)
Comune.create(description: "Sant'Eusanio Forconese", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 443)
Comune.create(description: "Villa Sant'Angelo", province_id: 45, region_id:  2, country_id: 1, continent_id: 1 , population: 431)
