Municipality.create(description: "Abbateggio", province_id: 46, region_id:  2, country_id: 1, continent_id: 1 , population: 420)
Municipality.create(description: "Alanno", province_id: 46, region_id:  2, country_id: 1, continent_id: 1 , population: 3742)
Municipality.create(description: "Bolognano", province_id: 46, region_id:  2, country_id: 1, continent_id: 1 , population: 1269)
Municipality.create(description: "Brittoli", province_id: 46, region_id:  2, country_id: 1, continent_id: 1 , population: 415)
Municipality.create(description: "Bussi Sul Tirino", province_id: 46, region_id:  2, country_id: 1, continent_id: 1 , population: 2977)
Municipality.create(description: "Cappelle Sul Tavo", province_id: 46, region_id:  2, country_id: 1, continent_id: 1 , population: 3714)
Municipality.create(description: "Caramanico Terme", province_id: 46, region_id:  2, country_id: 1, continent_id: 1 , population: 2119)
Municipality.create(description: "Carpineto Della Nora", province_id: 46, region_id:  2, country_id: 1, continent_id: 1 , population: 733)
Municipality.create(description: "Castiglione A Casauria", province_id: 46, region_id:  2, country_id: 1, continent_id: 1 , population: 892)
Municipality.create(description: "Catignano", province_id: 46, region_id:  2, country_id: 1, continent_id: 1 , population: 1540)
Municipality.create(description: "Cepagatti", province_id: 46, region_id:  2, country_id: 1, continent_id: 1 , population: 9097)
Municipality.create(description: "Civitaquana", province_id: 46, region_id:  2, country_id: 1, continent_id: 1 , population: 1395)
Municipality.create(description: "Civitella Casanova", province_id: 46, region_id:  2, country_id: 1, continent_id: 1 , population: 2057)
Municipality.create(description: "Collecorvino", province_id: 46, region_id:  2, country_id: 1, continent_id: 1 , population: 5399)
Municipality.create(description: "Corvara", province_id: 46, region_id:  2, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Cugnoli", province_id: 46, region_id:  2, country_id: 1, continent_id: 1 , population: 1669)
Municipality.create(description: "Elice", province_id: 46, region_id:  2, country_id: 1, continent_id: 1 , population: 1731)
Municipality.create(description: "Farindola", province_id: 46, region_id:  2, country_id: 1, continent_id: 1 , population: 1807)
Municipality.create(description: "Lettomanoppello", province_id: 46, region_id:  2, country_id: 1, continent_id: 1 , population: 3090)
Municipality.create(description: "Loreto Aprutino", province_id: 46, region_id:  2, country_id: 1, continent_id: 1 , population: 7615)
Municipality.create(description: "Manoppello", province_id: 46, region_id:  2, country_id: 1, continent_id: 1 , population: 5637)
Municipality.create(description: "Montebello Di Bertona", province_id: 46, region_id:  2, country_id: 1, continent_id: 1 , population: 1120)
Municipality.create(description: "Montesilvano", province_id: 46, region_id:  2, country_id: 1, continent_id: 1 , population: 40700)
Municipality.create(description: "Moscufo", province_id: 46, region_id:  2, country_id: 1, continent_id: 1 , population: 3163)
Municipality.create(description: "Nocciano", province_id: 46, region_id:  2, country_id: 1, continent_id: 1 , population: 1676)
Municipality.create(description: "Penne", province_id: 46, region_id:  2, country_id: 1, continent_id: 1 , population: 12495)
Municipality.create(description: "Pescara", province_id: 46, region_id:  2, country_id: 1, continent_id: 1 , population: 116286)
Municipality.create(description: "Pescosansonesco", province_id: 46, region_id:  2, country_id: 1, continent_id: 1 , population: 556)
Municipality.create(description: "Pianella", province_id: 46, region_id:  2, country_id: 1, continent_id: 1 , population: 7511)
Municipality.create(description: "Picciano", province_id: 46, region_id:  2, country_id: 1, continent_id: 1 , population: 1367)
Municipality.create(description: "Pietranico", province_id: 46, region_id:  2, country_id: 1, continent_id: 1 , population: 605)
Municipality.create(description: "Popoli", province_id: 46, region_id:  2, country_id: 1, continent_id: 1 , population: 5566)
Municipality.create(description: "Roccamorice", province_id: 46, region_id:  2, country_id: 1, continent_id: 1 , population: 1002)
Municipality.create(description: "Rosciano", province_id: 46, region_id:  2, country_id: 1, continent_id: 1 , population: 3095)
Municipality.create(description: "Salle", province_id: 46, region_id:  2, country_id: 1, continent_id: 1 , population: 312)
Municipality.create(description: "San Valentino In Abruzzo Citeriore", province_id: 46, region_id:  2, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Scafa", province_id: 46, region_id:  2, country_id: 1, continent_id: 1 , population: 3987)
Municipality.create(description: "Serramonacesca", province_id: 46, region_id:  2, country_id: 1, continent_id: 1 , population: 619)
Municipality.create(description: "Spoltore", province_id: 46, region_id:  2, country_id: 1, continent_id: 1 , population: 15417)
Municipality.create(description: "Tocco Da Casauria", province_id: 46, region_id:  2, country_id: 1, continent_id: 1 , population: 2767)
Municipality.create(description: "Turrivalignani", province_id: 46, region_id:  2, country_id: 1, continent_id: 1 , population: 858)
Municipality.create(description: "Vicoli", province_id: 46, region_id:  2, country_id: 1, continent_id: 1 , population: 445)
Municipality.create(description: "Villa Celiera", province_id: 46, region_id:  2, country_id: 1, continent_id: 1 , population: 890)
Municipality.create(description: "Citta' Sant'Angelo", province_id: 46, region_id:  2, country_id: 1, continent_id: 1 , population: 11952)
Municipality.create(description: "Sant'Eufemia A Maiella", province_id: 46, region_id:  2, country_id: 1, continent_id: 1 , population: 365)
Municipality.create(description: "Torre De' Passeri", province_id: 46, region_id:  2, country_id: 1, continent_id: 1 , population: 3161)
