Comune.create(description: "Alba Adriatica", province_id: 47, region_id:  2, country_id: 1, continent_id: 1 , population: 10389)
Comune.create(description: "Ancarano", province_id: 47, region_id:  2, country_id: 1, continent_id: 1 , population: 1774)
Comune.create(description: "Arsita", province_id: 47, region_id:  2, country_id: 1, continent_id: 1 , population: 969)
Comune.create(description: "Atri", province_id: 47, region_id:  2, country_id: 1, continent_id: 1 , population: 11260)
Comune.create(description: "Basciano", province_id: 47, region_id:  2, country_id: 1, continent_id: 1 , population: 2381)
Comune.create(description: "Bellante", province_id: 47, region_id:  2, country_id: 1, continent_id: 1 , population: 6935)
Comune.create(description: "Bisenti", province_id: 47, region_id:  2, country_id: 1, continent_id: 1 , population: 2205)
Comune.create(description: "Campli", province_id: 47, region_id:  2, country_id: 1, continent_id: 1 , population: 7266)
Comune.create(description: "Canzano", province_id: 47, region_id:  2, country_id: 1, continent_id: 1 , population: 1809)
Comune.create(description: "Castel Castagna", province_id: 47, region_id:  2, country_id: 1, continent_id: 1 , population: 539)
Comune.create(description: "Castellalto", province_id: 47, region_id:  2, country_id: 1, continent_id: 1 , population: 6637)
Comune.create(description: "Castelli", province_id: 47, region_id:  2, country_id: 1, continent_id: 1 , population: 1391)
Comune.create(description: "Castiglione Messer Raimondo", province_id: 47, region_id:  2, country_id: 1, continent_id: 1 , population: 2570)
Comune.create(description: "Castilenti", province_id: 47, region_id:  2, country_id: 1, continent_id: 1 , population: 1624)
Comune.create(description: "Cellino Attanasio", province_id: 47, region_id:  2, country_id: 1, continent_id: 1 , population: 2766)
Comune.create(description: "Cermignano", province_id: 47, region_id:  2, country_id: 1, continent_id: 1 , population: 1970)
Comune.create(description: "Civitella Del Tronto", province_id: 47, region_id:  2, country_id: 1, continent_id: 1 , population: 5244)
Comune.create(description: "Colledara", province_id: 47, region_id:  2, country_id: 1, continent_id: 1 , population: 2199)
Comune.create(description: "Colonnella", province_id: 47, region_id:  2, country_id: 1, continent_id: 1 , population: 3272)
Comune.create(description: "Controguerra", province_id: 47, region_id:  2, country_id: 1, continent_id: 1 , population: 2480)
Comune.create(description: "Corropoli", province_id: 47, region_id:  2, country_id: 1, continent_id: 1 , population: 3752)
Comune.create(description: "Cortino", province_id: 47, region_id:  2, country_id: 1, continent_id: 1 , population: 847)
Comune.create(description: "Crognaleto", province_id: 47, region_id:  2, country_id: 1, continent_id: 1 , population: 1549)
Comune.create(description: "Fano Adriano", province_id: 47, region_id:  2, country_id: 1, continent_id: 1 , population: 392)
Comune.create(description: "Giulianova", province_id: 47, region_id:  2, country_id: 1, continent_id: 1 , population: 21400)
Comune.create(description: "Martinsicuro", province_id: 47, region_id:  2, country_id: 1, continent_id: 1 , population: 13428)
Comune.create(description: "Montefino", province_id: 47, region_id:  2, country_id: 1, continent_id: 1 , population: 1184)
Comune.create(description: "Montorio Al Vomano", province_id: 47, region_id:  2, country_id: 1, continent_id: 1 , population: 8048)
Comune.create(description: "Nereto", province_id: 47, region_id:  2, country_id: 1, continent_id: 1 , population: 4425)
Comune.create(description: "Notaresco", province_id: 47, region_id:  2, country_id: 1, continent_id: 1 , population: 6770)
Comune.create(description: "Pietracamela", province_id: 47, region_id:  2, country_id: 1, continent_id: 1 , population: 312)
Comune.create(description: "Pineto", province_id: 47, region_id:  2, country_id: 1, continent_id: 1 , population: 13095)
Comune.create(description: "Rocca Santa Maria", province_id: 47, region_id:  2, country_id: 1, continent_id: 1 , population: 698)
Comune.create(description: "Roseto Degli Abruzzi", province_id: 47, region_id:  2, country_id: 1, continent_id: 1 , population: 22978)
Comune.create(description: "Silvi", province_id: 47, region_id:  2, country_id: 1, continent_id: 1 , population: 14478)
Comune.create(description: "Teramo", province_id: 47, region_id:  2, country_id: 1, continent_id: 1 , population: 51023)
Comune.create(description: "Torano Nuovo", province_id: 47, region_id:  2, country_id: 1, continent_id: 1 , population: 1684)
Comune.create(description: "Torricella Sicura", province_id: 47, region_id:  2, country_id: 1, continent_id: 1 , population: 2692)
Comune.create(description: "Tortoreto", province_id: 47, region_id:  2, country_id: 1, continent_id: 1 , population: 7836)
Comune.create(description: "Tossicia", province_id: 47, region_id:  2, country_id: 1, continent_id: 1 , population: 1497)
Comune.create(description: "Valle Castellana", province_id: 47, region_id:  2, country_id: 1, continent_id: 1 , population: 1278)
Comune.create(description: "Isola Del Gran Sasso D'Italia", province_id: 47, region_id:  2, country_id: 1, continent_id: 1 , population: 4883)
Comune.create(description: "Morro D'Oro", province_id: 47, region_id:  2, country_id: 1, continent_id: 1 , population: 3317)
Comune.create(description: "Mosciano Sant'Angelo", province_id: 47, region_id:  2, country_id: 1, continent_id: 1 , population: 8313)
Comune.create(description: "Penna Sant'Andrea", province_id: 47, region_id:  2, country_id: 1, continent_id: 1 , population: 1761)
Comune.create(description: "Sant'Egidio Alla Vibrata", province_id: 47, region_id:  2, country_id: 1, continent_id: 1 , population: 8817)
Comune.create(description: "Sant'Omero", province_id: 47, region_id:  2, country_id: 1, continent_id: 1 , population: 5274)
