Comune.create(description: "Anghiari", provincia_id: 48, regione_id: 12, country_id: 1, continent_id: 1 , population: 5860)
Comune.create(description: "Arezzo", provincia_id: 48, regione_id: 12, country_id: 1, continent_id: 1 , population: 91589)
Comune.create(description: "Badia Tedalda", provincia_id: 48, regione_id: 12, country_id: 1, continent_id: 1 , population: 1215)
Comune.create(description: "Bibbiena", provincia_id: 48, regione_id: 12, country_id: 1, continent_id: 1 , population: 11462)
Comune.create(description: "Bucine", provincia_id: 48, regione_id: 12, country_id: 1, continent_id: 1 , population: 9320)
Comune.create(description: "Capolona", provincia_id: 48, regione_id: 12, country_id: 1, continent_id: 1 , population: 4807)
Comune.create(description: "Caprese Michelangelo", provincia_id: 48, regione_id: 12, country_id: 1, continent_id: 1 , population: 1626)
Comune.create(description: "Castel Focognano", provincia_id: 48, regione_id: 12, country_id: 1, continent_id: 1 , population: 3331)
Comune.create(description: "Castelfranco Di Sopra", provincia_id: 48, regione_id: 12, country_id: 1, continent_id: 1 , population: 2731)
Comune.create(description: "Castiglion Fibocchi", provincia_id: 48, regione_id: 12, country_id: 1, continent_id: 1 , population: 1985)
Comune.create(description: "Castiglion Fiorentino", provincia_id: 48, regione_id: 12, country_id: 1, continent_id: 1 , population: 12031)
Comune.create(description: "Cavriglia", provincia_id: 48, regione_id: 12, country_id: 1, continent_id: 1 , population: 7808)
Comune.create(description: "Chitignano", provincia_id: 48, regione_id: 12, country_id: 1, continent_id: 1 , population: 954)
Comune.create(description: "Chiusi Della Verna", provincia_id: 48, regione_id: 12, country_id: 1, continent_id: 1 , population: 2225)
Comune.create(description: "Civitella In Val Di Chiana", provincia_id: 48, regione_id: 12, country_id: 1, continent_id: 1 , population: 8687)
Comune.create(description: "Cortona", provincia_id: 48, regione_id: 12, country_id: 1, continent_id: 1 , population: 22048)
Comune.create(description: "Foiano Della Chiana", provincia_id: 48, regione_id: 12, country_id: 1, continent_id: 1 , population: 8412)
Comune.create(description: "Laterina", provincia_id: 48, regione_id: 12, country_id: 1, continent_id: 1 , population: 3433)
Comune.create(description: "Loro Ciuffenna", provincia_id: 48, regione_id: 12, country_id: 1, continent_id: 1 , population: 5174)
Comune.create(description: "Lucignano", provincia_id: 48, regione_id: 12, country_id: 1, continent_id: 1 , population: 3468)
Comune.create(description: "Marciano Della Chiana", provincia_id: 48, regione_id: 12, country_id: 1, continent_id: 1 , population: 2757)
Comune.create(description: "Monte San Savino", provincia_id: 48, regione_id: 12, country_id: 1, continent_id: 1 , population: 8128)
Comune.create(description: "Montemignaio", provincia_id: 48, regione_id: 12, country_id: 1, continent_id: 1 , population: 589)
Comune.create(description: "Monterchi", provincia_id: 48, regione_id: 12, country_id: 1, continent_id: 1 , population: 1880)
Comune.create(description: "Montevarchi", provincia_id: 48, regione_id: 12, country_id: 1, continent_id: 1 , population: 22239)
Comune.create(description: "Ortignano Raggiolo", provincia_id: 48, regione_id: 12, country_id: 1, continent_id: 1 , population: 852)
Comune.create(description: "Pergine Valdarno", provincia_id: 48, regione_id: 12, country_id: 1, continent_id: 1 , population: 3111)
Comune.create(description: "Pian Di Sco", provincia_id: 48, regione_id: 12, country_id: 1, continent_id: 1 , population: 5441)
Comune.create(description: "Pieve Santo Stefano", provincia_id: 48, regione_id: 12, country_id: 1, continent_id: 1 , population: 3316)
Comune.create(description: "Poppi", provincia_id: 48, regione_id: 12, country_id: 1, continent_id: 1 , population: 5873)
Comune.create(description: "Pratovecchio", provincia_id: 48, regione_id: 12, country_id: 1, continent_id: 1 , population: 3090)
Comune.create(description: "San Giovanni Valdarno", provincia_id: 48, regione_id: 12, country_id: 1, continent_id: 1 , population: 16993)
Comune.create(description: "Sansepolcro", provincia_id: 48, regione_id: 12, country_id: 1, continent_id: 1 , population: 15693)
Comune.create(description: "Sestino", provincia_id: 48, regione_id: 12, country_id: 1, continent_id: 1 , population: 1454)
Comune.create(description: "Stia", provincia_id: 48, regione_id: 12, country_id: 1, continent_id: 1 , population: 3008)
Comune.create(description: "Subbiano", provincia_id: 48, regione_id: 12, country_id: 1, continent_id: 1 , population: 5485)
Comune.create(description: "Talla", provincia_id: 48, regione_id: 12, country_id: 1, continent_id: 1 , population: 1177)
Comune.create(description: "Terranuova Bracciolini", provincia_id: 48, regione_id: 12, country_id: 1, continent_id: 1 , population: 11181)
