Municipality.create(description: "Anghiari", province_id: 48, region_id:  12, country_id: 1, continent_id: 1 , population: 5860)
Municipality.create(description: "Arezzo", province_id: 48, region_id:  12, country_id: 1, continent_id: 1 , population: 91589)
Municipality.create(description: "Badia Tedalda", province_id: 48, region_id:  12, country_id: 1, continent_id: 1 , population: 1215)
Municipality.create(description: "Bibbiena", province_id: 48, region_id:  12, country_id: 1, continent_id: 1 , population: 11462)
Municipality.create(description: "Bucine", province_id: 48, region_id:  12, country_id: 1, continent_id: 1 , population: 9320)
Municipality.create(description: "Capolona", province_id: 48, region_id:  12, country_id: 1, continent_id: 1 , population: 4807)
Municipality.create(description: "Caprese Michelangelo", province_id: 48, region_id:  12, country_id: 1, continent_id: 1 , population: 1626)
Municipality.create(description: "Castel Focognano", province_id: 48, region_id:  12, country_id: 1, continent_id: 1 , population: 3331)
Municipality.create(description: "Castelfranco Di Sopra", province_id: 48, region_id:  12, country_id: 1, continent_id: 1 , population: 2731)
Municipality.create(description: "Castiglion Fibocchi", province_id: 48, region_id:  12, country_id: 1, continent_id: 1 , population: 1985)
Municipality.create(description: "Castiglion Fiorentino", province_id: 48, region_id:  12, country_id: 1, continent_id: 1 , population: 12031)
Municipality.create(description: "Cavriglia", province_id: 48, region_id:  12, country_id: 1, continent_id: 1 , population: 7808)
Municipality.create(description: "Chitignano", province_id: 48, region_id:  12, country_id: 1, continent_id: 1 , population: 954)
Municipality.create(description: "Chiusi Della Verna", province_id: 48, region_id:  12, country_id: 1, continent_id: 1 , population: 2225)
Municipality.create(description: "Civitella In Val Di Chiana", province_id: 48, region_id:  12, country_id: 1, continent_id: 1 , population: 8687)
Municipality.create(description: "Cortona", province_id: 48, region_id:  12, country_id: 1, continent_id: 1 , population: 22048)
Municipality.create(description: "Foiano Della Chiana", province_id: 48, region_id:  12, country_id: 1, continent_id: 1 , population: 8412)
Municipality.create(description: "Laterina", province_id: 48, region_id:  12, country_id: 1, continent_id: 1 , population: 3433)
Municipality.create(description: "Loro Ciuffenna", province_id: 48, region_id:  12, country_id: 1, continent_id: 1 , population: 5174)
Municipality.create(description: "Lucignano", province_id: 48, region_id:  12, country_id: 1, continent_id: 1 , population: 3468)
Municipality.create(description: "Marciano Della Chiana", province_id: 48, region_id:  12, country_id: 1, continent_id: 1 , population: 2757)
Municipality.create(description: "Monte San Savino", province_id: 48, region_id:  12, country_id: 1, continent_id: 1 , population: 8128)
Municipality.create(description: "Montemignaio", province_id: 48, region_id:  12, country_id: 1, continent_id: 1 , population: 589)
Municipality.create(description: "Monterchi", province_id: 48, region_id:  12, country_id: 1, continent_id: 1 , population: 1880)
Municipality.create(description: "Montevarchi", province_id: 48, region_id:  12, country_id: 1, continent_id: 1 , population: 22239)
Municipality.create(description: "Ortignano Raggiolo", province_id: 48, region_id:  12, country_id: 1, continent_id: 1 , population: 852)
Municipality.create(description: "Pergine Valdarno", province_id: 48, region_id:  12, country_id: 1, continent_id: 1 , population: 3111)
Municipality.create(description: "Pian Di Sco", province_id: 48, region_id:  12, country_id: 1, continent_id: 1 , population: 5441)
Municipality.create(description: "Pieve Santo Stefano", province_id: 48, region_id:  12, country_id: 1, continent_id: 1 , population: 3316)
Municipality.create(description: "Poppi", province_id: 48, region_id:  12, country_id: 1, continent_id: 1 , population: 5873)
Municipality.create(description: "Pratovecchio", province_id: 48, region_id:  12, country_id: 1, continent_id: 1 , population: 3090)
Municipality.create(description: "San Giovanni Valdarno", province_id: 48, region_id:  12, country_id: 1, continent_id: 1 , population: 16993)
Municipality.create(description: "Sansepolcro", province_id: 48, region_id:  12, country_id: 1, continent_id: 1 , population: 15693)
Municipality.create(description: "Sestino", province_id: 48, region_id:  12, country_id: 1, continent_id: 1 , population: 1454)
Municipality.create(description: "Stia", province_id: 48, region_id:  12, country_id: 1, continent_id: 1 , population: 3008)
Municipality.create(description: "Subbiano", province_id: 48, region_id:  12, country_id: 1, continent_id: 1 , population: 5485)
Municipality.create(description: "Talla", province_id: 48, region_id:  12, country_id: 1, continent_id: 1 , population: 1177)
Municipality.create(description: "Terranuova Bracciolini", province_id: 48, region_id:  12, country_id: 1, continent_id: 1 , population: 11181)
