Municipality.create(description: "Bagno A Ripoli", province_id: 49, region_id:  12, country_id: 1, continent_id: 1 , population: 25232)
Municipality.create(description: "Barberino Di Mugello", province_id: 49, region_id:  12, country_id: 1, continent_id: 1 , population: 9531)
Municipality.create(description: "Borgo San Lorenzo", province_id: 49, region_id:  12, country_id: 1, continent_id: 1 , population: 15825)
Municipality.create(description: "Calenzano", province_id: 49, region_id:  12, country_id: 1, continent_id: 1 , population: 15042)
Municipality.create(description: "Campi Bisenzio", province_id: 49, region_id:  12, country_id: 1, continent_id: 1 , population: 37249)
Municipality.create(description: "Capraia E Limite", province_id: 49, region_id:  12, country_id: 1, continent_id: 1 , population: 5920)
Municipality.create(description: "Castelfiorentino", province_id: 49, region_id:  12, country_id: 1, continent_id: 1 , population: 17012)
Municipality.create(description: "Cerreto Guidi", province_id: 49, region_id:  12, country_id: 1, continent_id: 1 , population: 9555)
Municipality.create(description: "Certaldo", province_id: 49, region_id:  12, country_id: 1, continent_id: 1 , population: 15670)
Municipality.create(description: "Dicomano", province_id: 49, region_id:  12, country_id: 1, continent_id: 1 , population: 4958)
Municipality.create(description: "Empoli", province_id: 49, region_id:  12, country_id: 1, continent_id: 1 , population: 44094)
Municipality.create(description: "Fiesole", province_id: 49, region_id:  12, country_id: 1, continent_id: 1 , population: 14085)
Municipality.create(description: "Figline Valdarno", province_id: 49, region_id:  12, country_id: 1, continent_id: 1 , population: 16301)
Municipality.create(description: "Firenze", province_id: 49, region_id:  12, country_id: 1, continent_id: 1 , population: 356118)
Municipality.create(description: "Firenzuola", province_id: 49, region_id:  12, country_id: 1, continent_id: 1 , population: 4812)
Municipality.create(description: "Fucecchio", province_id: 49, region_id:  12, country_id: 1, continent_id: 1 , population: 21139)
Municipality.create(description: "Gambassi Terme", province_id: 49, region_id:  12, country_id: 1, continent_id: 1 , population: 4709)
Municipality.create(description: "Greve In Chianti", province_id: 49, region_id:  12, country_id: 1, continent_id: 1 , population: 12855)
Municipality.create(description: "Impruneta", province_id: 49, region_id:  12, country_id: 1, continent_id: 1 , population: 14637)
Municipality.create(description: "Lastra A Signa", province_id: 49, region_id:  12, country_id: 1, continent_id: 1 , population: 17938)
Municipality.create(description: "Londa", province_id: 49, region_id:  12, country_id: 1, continent_id: 1 , population: 1669)
Municipality.create(description: "Marradi", province_id: 49, region_id:  12, country_id: 1, continent_id: 1 , population: 3617)
Municipality.create(description: "Montaione", province_id: 49, region_id:  12, country_id: 1, continent_id: 1 , population: 3439)
Municipality.create(description: "Montelupo Fiorentino", province_id: 49, region_id:  12, country_id: 1, continent_id: 1 , population: 11240)
Municipality.create(description: "Montespertoli", province_id: 49, region_id:  12, country_id: 1, continent_id: 1 , population: 11354)
Municipality.create(description: "Palazzuolo Sul Senio", province_id: 49, region_id:  12, country_id: 1, continent_id: 1 , population: 1301)
Municipality.create(description: "Pelago", province_id: 49, region_id:  12, country_id: 1, continent_id: 1 , population: 7270)
Municipality.create(description: "Pontassieve", province_id: 49, region_id:  12, country_id: 1, continent_id: 1 , population: 20610)
Municipality.create(description: "Reggello", province_id: 49, region_id:  12, country_id: 1, continent_id: 1 , population: 14167)
Municipality.create(description: "Rufina", province_id: 49, region_id:  12, country_id: 1, continent_id: 1 , population: 6693)
Municipality.create(description: "San Casciano In Val Di Pesa", province_id: 49, region_id:  12, country_id: 1, continent_id: 1 , population: 16615)
Municipality.create(description: "San Godenzo", province_id: 49, region_id:  12, country_id: 1, continent_id: 1 , population: 1187)
Municipality.create(description: "San Piero A Sieve", province_id: 49, region_id:  12, country_id: 1, continent_id: 1 , population: 3758)
Municipality.create(description: "Scandicci", province_id: 49, region_id:  12, country_id: 1, continent_id: 1 , population: 50136)
Municipality.create(description: "Scarperia", province_id: 49, region_id:  12, country_id: 1, continent_id: 1 , population: 6778)
Municipality.create(description: "Sesto Fiorentino", province_id: 49, region_id:  12, country_id: 1, continent_id: 1 , population: 46054)
Municipality.create(description: "Signa", province_id: 49, region_id:  12, country_id: 1, continent_id: 1 , population: 15433)
Municipality.create(description: "Tavarnelle Val Di Pesa", province_id: 49, region_id:  12, country_id: 1, continent_id: 1 , population: 7153)
Municipality.create(description: "Vaglia", province_id: 49, region_id:  12, country_id: 1, continent_id: 1 , population: 4865)
Municipality.create(description: "Vicchio", province_id: 49, region_id:  12, country_id: 1, continent_id: 1 , population: 7145)
Municipality.create(description: "Vinci", province_id: 49, region_id:  12, country_id: 1, continent_id: 1 , population: 13778)
Municipality.create(description: "Barberino Val D'Elsa", province_id: 49, region_id:  12, country_id: 1, continent_id: 1 , population: 3871)
Municipality.create(description: "Incisa In Val D'Arno", province_id: 49, region_id:  12, country_id: 1, continent_id: 1 , population: 5503)
Municipality.create(description: "Rignano Sull'Arno", province_id: 49, region_id:  12, country_id: 1, continent_id: 1 , population: 7542)
