Comune.create(description: "Bibbona", provincia_id: 51, region_id:  12, country_id: 1, continent_id: 1 , population: 3051)
Comune.create(description: "Campiglia Marittima", provincia_id: 51, region_id:  12, country_id: 1, continent_id: 1 , population: 12540)
Comune.create(description: "Capoliveri", provincia_id: 51, region_id:  12, country_id: 1, continent_id: 1 , population: 3105)
Comune.create(description: "Capraia Isola", provincia_id: 51, region_id:  12, country_id: 1, continent_id: 1 , population: 333)
Comune.create(description: "Castagneto Carducci", provincia_id: 51, region_id:  12, country_id: 1, continent_id: 1 , population: 8226)
Comune.create(description: "Cecina", provincia_id: 51, region_id:  12, country_id: 1, continent_id: 1 , population: 26515)
Comune.create(description: "Collesalvetti", provincia_id: 51, region_id:  12, country_id: 1, continent_id: 1 , population: 15871)
Comune.create(description: "Livorno", provincia_id: 51, region_id:  12, country_id: 1, continent_id: 1 , population: 156274)
Comune.create(description: "Marciana", provincia_id: 51, region_id:  12, country_id: 1, continent_id: 1 , population: 2162)
Comune.create(description: "Marciana Marina", provincia_id: 51, region_id:  12, country_id: 1, continent_id: 1 , population: 1891)
Comune.create(description: "Piombino", provincia_id: 51, region_id:  12, country_id: 1, continent_id: 1 , population: 33925)
Comune.create(description: "Porto Azzurro", provincia_id: 51, region_id:  12, country_id: 1, continent_id: 1 , population: 3220)
Comune.create(description: "Portoferraio", provincia_id: 51, region_id:  12, country_id: 1, continent_id: 1 , population: 11508)
Comune.create(description: "Rio Marina", provincia_id: 51, region_id:  12, country_id: 1, continent_id: 1 , population: 2150)
Comune.create(description: "Rosignano Marittimo", provincia_id: 51, region_id:  12, country_id: 1, continent_id: 1 , population: 30581)
Comune.create(description: "San Vincenzo", provincia_id: 51, region_id:  12, country_id: 1, continent_id: 1 , population: 6540)
Comune.create(description: "Sassetta", provincia_id: 51, region_id:  12, country_id: 1, continent_id: 1 , population: 548)
Comune.create(description: "Suvereto", provincia_id: 51, region_id:  12, country_id: 1, continent_id: 1 , population: 2897)
Comune.create(description: "Campo Nell'Elba", provincia_id: 51, region_id:  12, country_id: 1, continent_id: 1 , population: 4155)
Comune.create(description: "Rio Nell'Elba", provincia_id: 51, region_id:  12, country_id: 1, continent_id: 1 , population: 952)
