Municipality.create(description: "Bibbona", province_id: 51, region_id:  12, country_id: 1, continent_id: 1 , population: 3051)
Municipality.create(description: "Campiglia Marittima", province_id: 51, region_id:  12, country_id: 1, continent_id: 1 , population: 12540)
Municipality.create(description: "Capoliveri", province_id: 51, region_id:  12, country_id: 1, continent_id: 1 , population: 3105)
Municipality.create(description: "Capraia Isola", province_id: 51, region_id:  12, country_id: 1, continent_id: 1 , population: 333)
Municipality.create(description: "Castagneto Carducci", province_id: 51, region_id:  12, country_id: 1, continent_id: 1 , population: 8226)
Municipality.create(description: "Cecina", province_id: 51, region_id:  12, country_id: 1, continent_id: 1 , population: 26515)
Municipality.create(description: "Collesalvetti", province_id: 51, region_id:  12, country_id: 1, continent_id: 1 , population: 15871)
Municipality.create(description: "Livorno", province_id: 51, region_id:  12, country_id: 1, continent_id: 1 , population: 156274)
Municipality.create(description: "Marciana", province_id: 51, region_id:  12, country_id: 1, continent_id: 1 , population: 2162)
Municipality.create(description: "Marciana Marina", province_id: 51, region_id:  12, country_id: 1, continent_id: 1 , population: 1891)
Municipality.create(description: "Piombino", province_id: 51, region_id:  12, country_id: 1, continent_id: 1 , population: 33925)
Municipality.create(description: "Porto Azzurro", province_id: 51, region_id:  12, country_id: 1, continent_id: 1 , population: 3220)
Municipality.create(description: "Portoferraio", province_id: 51, region_id:  12, country_id: 1, continent_id: 1 , population: 11508)
Municipality.create(description: "Rio Marina", province_id: 51, region_id:  12, country_id: 1, continent_id: 1 , population: 2150)
Municipality.create(description: "Rosignano Marittimo", province_id: 51, region_id:  12, country_id: 1, continent_id: 1 , population: 30581)
Municipality.create(description: "San Vincenzo", province_id: 51, region_id:  12, country_id: 1, continent_id: 1 , population: 6540)
Municipality.create(description: "Sassetta", province_id: 51, region_id:  12, country_id: 1, continent_id: 1 , population: 548)
Municipality.create(description: "Suvereto", province_id: 51, region_id:  12, country_id: 1, continent_id: 1 , population: 2897)
Municipality.create(description: "Campo Nell'Elba", province_id: 51, region_id:  12, country_id: 1, continent_id: 1 , population: 4155)
Municipality.create(description: "Rio Nell'Elba", province_id: 51, region_id:  12, country_id: 1, continent_id: 1 , population: 952)
