Municipality.create(description: "Altopascio", province_id: 52, region_id:  12, country_id: 1, continent_id: 1 , population: 11152)
Municipality.create(description: "Bagni Di Lucca", province_id: 52, region_id:  12, country_id: 1, continent_id: 1 , population: 6550)
Municipality.create(description: "Barga", province_id: 52, region_id:  12, country_id: 1, continent_id: 1 , population: 10018)
Municipality.create(description: "Borgo A Mozzano", province_id: 52, region_id:  12, country_id: 1, continent_id: 1 , population: 7358)
Municipality.create(description: "Camaiore", province_id: 52, region_id:  12, country_id: 1, continent_id: 1 , population: 30206)
Municipality.create(description: "Camporgiano", province_id: 52, region_id:  12, country_id: 1, continent_id: 1 , population: 2394)
Municipality.create(description: "Capannori", province_id: 52, region_id:  12, country_id: 1, continent_id: 1 , population: 42454)
Municipality.create(description: "Careggine", province_id: 52, region_id:  12, country_id: 1, continent_id: 1 , population: 642)
Municipality.create(description: "Castelnuovo Di Garfagnana", province_id: 52, region_id:  12, country_id: 1, continent_id: 1 , population: 6073)
Municipality.create(description: "Castiglione Di Garfagnana", province_id: 52, region_id:  12, country_id: 1, continent_id: 1 , population: 1890)
Municipality.create(description: "Coreglia Antelminelli", province_id: 52, region_id:  12, country_id: 1, continent_id: 1 , population: 4813)
Municipality.create(description: "Fabbriche Di Vallico", province_id: 52, region_id:  12, country_id: 1, continent_id: 1 , population: 526)
Municipality.create(description: "Forte Dei Marmi", province_id: 52, region_id:  12, country_id: 1, continent_id: 1 , population: 8444)
Municipality.create(description: "Fosciandora", province_id: 52, region_id:  12, country_id: 1, continent_id: 1 , population: 670)
Municipality.create(description: "Gallicano", province_id: 52, region_id:  12, country_id: 1, continent_id: 1 , population: 3795)
Municipality.create(description: "Giuncugnano", province_id: 52, region_id:  12, country_id: 1, continent_id: 1 , population: 538)
Municipality.create(description: "Lucca", province_id: 52, region_id:  12, country_id: 1, continent_id: 1 , population: 81862)
Municipality.create(description: "Massarosa", province_id: 52, region_id:  12, country_id: 1, continent_id: 1 , population: 20548)
Municipality.create(description: "Minucciano", province_id: 52, region_id:  12, country_id: 1, continent_id: 1 , population: 2521)
Municipality.create(description: "Molazzana", province_id: 52, region_id:  12, country_id: 1, continent_id: 1 , population: 1188)
Municipality.create(description: "Montecarlo", province_id: 52, region_id:  12, country_id: 1, continent_id: 1 , population: 4345)
Municipality.create(description: "Pescaglia", province_id: 52, region_id:  12, country_id: 1, continent_id: 1 , population: 3718)
Municipality.create(description: "Piazza Al Serchio", province_id: 52, region_id:  12, country_id: 1, continent_id: 1 , population: 2556)
Municipality.create(description: "Pietrasanta", province_id: 52, region_id:  12, country_id: 1, continent_id: 1 , population: 24409)
Municipality.create(description: "Pieve Fosciana", province_id: 52, region_id:  12, country_id: 1, continent_id: 1 , population: 2367)
Municipality.create(description: "Porcari", province_id: 52, region_id:  12, country_id: 1, continent_id: 1 , population: 7109)
Municipality.create(description: "San Romano In Garfagnana", province_id: 52, region_id:  12, country_id: 1, continent_id: 1 , population: 1432)
Municipality.create(description: "Seravezza", province_id: 52, region_id:  12, country_id: 1, continent_id: 1 , population: 12706)
Municipality.create(description: "Sillano", province_id: 52, region_id:  12, country_id: 1, continent_id: 1 , population: 784)
Municipality.create(description: "Stazzema", province_id: 52, region_id:  12, country_id: 1, continent_id: 1 , population: 3367)
Municipality.create(description: "Vagli Sotto", province_id: 52, region_id:  12, country_id: 1, continent_id: 1 , population: 1123)
Municipality.create(description: "Vergemoli", province_id: 52, region_id:  12, country_id: 1, continent_id: 1 , population: 391)
Municipality.create(description: "Viareggio", province_id: 52, region_id:  12, country_id: 1, continent_id: 1 , population: 61103)
Municipality.create(description: "Villa Basilica", province_id: 52, region_id:  12, country_id: 1, continent_id: 1 , population: 1792)
Municipality.create(description: "Villa Collemandina", province_id: 52, region_id:  12, country_id: 1, continent_id: 1 , population: 1400)
