Comune.create(description: "Aulla", provincia_id: 53, region_id:  12, country_id: 1, continent_id: 1 , population: 10178)
Comune.create(description: "Bagnone", provincia_id: 53, region_id:  12, country_id: 1, continent_id: 1 , population: 2022)
Comune.create(description: "Carrara", provincia_id: 53, region_id:  12, country_id: 1, continent_id: 1 , population: 65034)
Comune.create(description: "Casola In Lunigiana", provincia_id: 53, region_id:  12, country_id: 1, continent_id: 1 , population: 1231)
Comune.create(description: "Filattiera", provincia_id: 53, region_id:  12, country_id: 1, continent_id: 1 , population: 2474)
Comune.create(description: "Fivizzano", provincia_id: 53, region_id:  12, country_id: 1, continent_id: 1 , population: 9174)
Comune.create(description: "Fosdinovo", provincia_id: 53, region_id:  12, country_id: 1, continent_id: 1 , population: 4379)
Comune.create(description: "Licciana Nardi", provincia_id: 53, region_id:  12, country_id: 1, continent_id: 1 , population: 4887)
Comune.create(description: "Massa", provincia_id: 53, region_id:  12, country_id: 1, continent_id: 1 , population: 66769)
Comune.create(description: "Montignoso", provincia_id: 53, region_id:  12, country_id: 1, continent_id: 1 , population: 10023)
Comune.create(description: "Mulazzo", provincia_id: 53, region_id:  12, country_id: 1, continent_id: 1 , population: 2565)
Comune.create(description: "Podenzana", provincia_id: 53, region_id:  12, country_id: 1, continent_id: 1 , population: 1819)
Comune.create(description: "Pontremoli", provincia_id: 53, region_id:  12, country_id: 1, continent_id: 1 , population: 8252)
Comune.create(description: "Tresana", provincia_id: 53, region_id:  12, country_id: 1, continent_id: 1 , population: 2055)
Comune.create(description: "Villafranca In Lunigiana", provincia_id: 53, region_id:  12, country_id: 1, continent_id: 1 , population: 4609)
Comune.create(description: "Zeri", provincia_id: 53, region_id:  12, country_id: 1, continent_id: 1 , population: 1382)
