Comune.create(description: "Bientina", provincia_id: 54, region_id:  12, country_id: 1, continent_id: 1 , population: 6115)
Comune.create(description: "Buti", provincia_id: 54, region_id:  12, country_id: 1, continent_id: 1 , population: 5431)
Comune.create(description: "Calci", provincia_id: 54, region_id:  12, country_id: 1, continent_id: 1 , population: 5838)
Comune.create(description: "Calcinaia", provincia_id: 54, region_id:  12, country_id: 1, continent_id: 1 , population: 8608)
Comune.create(description: "Capannoli", provincia_id: 54, region_id:  12, country_id: 1, continent_id: 1 , population: 5106)
Comune.create(description: "Casale Marittimo", provincia_id: 54, region_id:  12, country_id: 1, continent_id: 1 , population: 1007)
Comune.create(description: "Casciana Terme", provincia_id: 54, region_id:  12, country_id: 1, continent_id: 1 , population: 3538)
Comune.create(description: "Cascina", provincia_id: 54, region_id:  12, country_id: 1, continent_id: 1 , population: 38359)
Comune.create(description: "Castelfranco Di Sotto", provincia_id: 54, region_id:  12, country_id: 1, continent_id: 1 , population: 11415)
Comune.create(description: "Castellina Marittima", provincia_id: 54, region_id:  12, country_id: 1, continent_id: 1 , population: 1817)
Comune.create(description: "Castelnuovo Val Di Cecina", provincia_id: 54, region_id:  12, country_id: 1, continent_id: 1 , population: 2467)
Comune.create(description: "Chianni", provincia_id: 54, region_id:  12, country_id: 1, continent_id: 1 , population: 1563)
Comune.create(description: "Crespina", provincia_id: 54, region_id:  12, country_id: 1, continent_id: 1 , population: 3746)
Comune.create(description: "Fauglia", provincia_id: 54, region_id:  12, country_id: 1, continent_id: 1 , population: 3124)
Comune.create(description: "Guardistallo", provincia_id: 54, region_id:  12, country_id: 1, continent_id: 1 , population: 1026)
Comune.create(description: "Lajatico", provincia_id: 54, region_id:  12, country_id: 1, continent_id: 1 , population: 1389)
Comune.create(description: "Lari", provincia_id: 54, region_id:  12, country_id: 1, continent_id: 1 , population: 8083)
Comune.create(description: "Lorenzana", provincia_id: 54, region_id:  12, country_id: 1, continent_id: 1 , population: 1144)
Comune.create(description: "Montecatini Val Di Cecina", provincia_id: 54, region_id:  12, country_id: 1, continent_id: 1 , population: 2008)
Comune.create(description: "Montescudaio", provincia_id: 54, region_id:  12, country_id: 1, continent_id: 1 , population: 1436)
Comune.create(description: "Monteverdi Marittimo", provincia_id: 54, region_id:  12, country_id: 1, continent_id: 1 , population: 701)
Comune.create(description: "Orciano Pisano", provincia_id: 54, region_id:  12, country_id: 1, continent_id: 1 , population: 628)
Comune.create(description: "Palaia", provincia_id: 54, region_id:  12, country_id: 1, continent_id: 1 , population: 4536)
Comune.create(description: "Peccioli", provincia_id: 54, region_id:  12, country_id: 1, continent_id: 1 , population: 4833)
Comune.create(description: "Pisa", provincia_id: 54, region_id:  12, country_id: 1, continent_id: 1 , population: 89694)
Comune.create(description: "Pomarance", provincia_id: 54, region_id:  12, country_id: 1, continent_id: 1 , population: 6323)
Comune.create(description: "Ponsacco", provincia_id: 54, region_id:  12, country_id: 1, continent_id: 1 , population: 12576)
Comune.create(description: "Pontedera", provincia_id: 54, region_id:  12, country_id: 1, continent_id: 1 , population: 24971)
Comune.create(description: "Riparbella", provincia_id: 54, region_id:  12, country_id: 1, continent_id: 1 , population: 1327)
Comune.create(description: "San Giuliano Terme", provincia_id: 54, region_id:  12, country_id: 1, continent_id: 1 , population: 30392)
Comune.create(description: "San Miniato", provincia_id: 54, region_id:  12, country_id: 1, continent_id: 1 , population: 26365)
Comune.create(description: "Santa Luce", provincia_id: 54, region_id:  12, country_id: 1, continent_id: 1 , population: 1465)
Comune.create(description: "Santa Maria A Monte", provincia_id: 54, region_id:  12, country_id: 1, continent_id: 1 , population: 10841)
Comune.create(description: "Terricciola", provincia_id: 54, region_id:  12, country_id: 1, continent_id: 1 , population: 3939)
Comune.create(description: "Vecchiano", provincia_id: 54, region_id:  12, country_id: 1, continent_id: 1 , population: 11425)
Comune.create(description: "Vicopisano", provincia_id: 54, region_id:  12, country_id: 1, continent_id: 1 , population: 7907)
Comune.create(description: "Volterra", provincia_id: 54, region_id:  12, country_id: 1, continent_id: 1 , population: 11264)
Comune.create(description: "Montopoli In Val D'Arno", provincia_id: 54, region_id:  12, country_id: 1, continent_id: 1 , population: 9648)
Comune.create(description: "Santa Croce Sull'Arno", provincia_id: 54, region_id:  12, country_id: 1, continent_id: 1 , population: 12500)
