Municipality.create(description: "Abetone", province_id: 55, region_id:  12, country_id: 1, continent_id: 1 , population: 705)
Municipality.create(description: "Agliana", province_id: 55, region_id:  12, country_id: 1, continent_id: 1 , population: 14628)
Municipality.create(description: "Buggiano", province_id: 55, region_id:  12, country_id: 1, continent_id: 1 , population: 8043)
Municipality.create(description: "Chiesina Uzzanese", province_id: 55, region_id:  12, country_id: 1, continent_id: 1 , population: 3983)
Municipality.create(description: "Cutigliano", province_id: 55, region_id:  12, country_id: 1, continent_id: 1 , population: 1699)
Municipality.create(description: "Lamporecchio", province_id: 55, region_id:  12, country_id: 1, continent_id: 1 , population: 6777)
Municipality.create(description: "Larciano", province_id: 55, region_id:  12, country_id: 1, continent_id: 1 , population: 6018)
Municipality.create(description: "Marliana", province_id: 55, region_id:  12, country_id: 1, continent_id: 1 , population: 2917)
Municipality.create(description: "Massa E Cozzile", province_id: 55, region_id:  12, country_id: 1, continent_id: 1 , population: 7199)
Municipality.create(description: "Monsummano Terme", province_id: 55, region_id:  12, country_id: 1, continent_id: 1 , population: 19906)
Municipality.create(description: "Montale", province_id: 55, region_id:  12, country_id: 1, continent_id: 1 , population: 10143)
Municipality.create(description: "Montecatini Terme", province_id: 55, region_id:  12, country_id: 1, continent_id: 1 , population: 19900)
Municipality.create(description: "Pescia", province_id: 55, region_id:  12, country_id: 1, continent_id: 1 , population: 17428)
Municipality.create(description: "Pieve A Nievole", province_id: 55, region_id:  12, country_id: 1, continent_id: 1 , population: 9098)
Municipality.create(description: "Pistoia", province_id: 55, region_id:  12, country_id: 1, continent_id: 1 , population: 84274)
Municipality.create(description: "Piteglio", province_id: 55, region_id:  12, country_id: 1, continent_id: 1 , population: 1877)
Municipality.create(description: "Ponte Buggianese", province_id: 55, region_id:  12, country_id: 1, continent_id: 1 , population: 7618)
Municipality.create(description: "Quarrata", province_id: 55, region_id:  12, country_id: 1, continent_id: 1 , population: 22683)
Municipality.create(description: "Sambuca Pistoiese", province_id: 55, region_id:  12, country_id: 1, continent_id: 1 , population: 1604)
Municipality.create(description: "San Marcello Pistoiese", province_id: 55, region_id:  12, country_id: 1, continent_id: 1 , population: 7142)
Municipality.create(description: "Serravalle Pistoiese", province_id: 55, region_id:  12, country_id: 1, continent_id: 1 , population: 10150)
Municipality.create(description: "Uzzano", province_id: 55, region_id:  12, country_id: 1, continent_id: 1 , population: 4711)
