#encoding: utf-8
Comune.create(description: "Abbadia San Salvatore", provincia_id: 56, regione_id: 12, country_id: 1, continent_id: 1 , population: 6832)
Comune.create(description: "Asciano", provincia_id: 56, regione_id: 12, country_id: 1, continent_id: 1 , population: 6488)
Comune.create(description: "Buonconvento", provincia_id: 56, regione_id: 12, country_id: 1, continent_id: 1 , population: 3168)
Comune.create(description: "Castellina In Chianti", provincia_id: 56, regione_id: 12, country_id: 1, continent_id: 1 , population: 2673)
Comune.create(description: "Castelnuovo Berardenga", provincia_id: 56, regione_id: 12, country_id: 1, continent_id: 1 , population: 7470)
Comune.create(description: "Cetona", provincia_id: 56, regione_id: 12, country_id: 1, continent_id: 1 , population: 2854)
Comune.create(description: "Chianciano Terme", provincia_id: 56, regione_id: 12, country_id: 1, continent_id: 1 , population: 6955)
Comune.create(description: "Chiusdino", provincia_id: 56, regione_id: 12, country_id: 1, continent_id: 1 , population: 1918)
Comune.create(description: "Chiusi", provincia_id: 56, regione_id: 12, country_id: 1, continent_id: 1 , population: 8612)
Comune.create(description: "Gaiole In Chianti", provincia_id: 56, regione_id: 12, country_id: 1, continent_id: 1 , population: 2386)
Comune.create(description: "Montalcino", provincia_id: 56, regione_id: 12, country_id: 1, continent_id: 1 , population: 5118)
Comune.create(description: "Montepulciano", provincia_id: 56, regione_id: 12, country_id: 1, continent_id: 1 , population: 13883)
Comune.create(description: "Monteriggioni", provincia_id: 56, regione_id: 12, country_id: 1, continent_id: 1 , population: 7891)
Comune.create(description: "Monticiano", provincia_id: 56, regione_id: 12, country_id: 1, continent_id: 1 , population: 1408)
Comune.create(description: "Murlo", provincia_id: 56, regione_id: 12, country_id: 1, continent_id: 1 , population: 1932)
Comune.create(description: "Piancastagnaio", provincia_id: 56, regione_id: 12, country_id: 1, continent_id: 1 , population: 4196)
Comune.create(description: "Pienza", provincia_id: 56, regione_id: 12, country_id: 1, continent_id: 1 , population: 2233)
Comune.create(description: "Poggibonsi", provincia_id: 56, regione_id: 12, country_id: 1, continent_id: 1 , population: 27420)
Comune.create(description: "Radda In Chianti", provincia_id: 56, regione_id: 12, country_id: 1, continent_id: 1 , population: 1669)
Comune.create(description: "Radicofani", provincia_id: 56, regione_id: 12, country_id: 1, continent_id: 1 , population: 1219)
Comune.create(description: "Radicondoli", provincia_id: 56, regione_id: 12, country_id: 1, continent_id: 1 , population: 978)
Comune.create(description: "Rapolano Terme", provincia_id: 56, regione_id: 12, country_id: 1, continent_id: 1 , population: 4776)
Comune.create(description: "San Casciano Dei Bagni", provincia_id: 56, regione_id: 12, country_id: 1, continent_id: 1 , population: 1745)
Comune.create(description: "San Gimignano", provincia_id: 56, regione_id: 12, country_id: 1, continent_id: 1 , population: 7114)
Comune.create(description: "Sarteano", provincia_id: 56, regione_id: 12, country_id: 1, continent_id: 1 , population: 4535)
Comune.create(description: "Siena", provincia_id: 56, regione_id: 12, country_id: 1, continent_id: 1 , population: 52625)
Comune.create(description: "Sinalunga", provincia_id: 56, regione_id: 12, country_id: 1, continent_id: 1 , population: 11790)
Comune.create(description: "Sovicille", provincia_id: 56, regione_id: 12, country_id: 1, continent_id: 1 , population: 8366)
Comune.create(description: "Torrita Di Siena", provincia_id: 56, regione_id: 12, country_id: 1, continent_id: 1 , population: 7121)
Comune.create(description: "Trequanda", provincia_id: 56, regione_id: 12, country_id: 1, continent_id: 1 , population: 1417)
Comune.create(description: "Casole D'Elsa", provincia_id: 56, regione_id: 12, country_id: 1, continent_id: 1 , population: 2931)
Comune.create(description: "Castiglione D'Orcia", provincia_id: 56, regione_id: 12, country_id: 1, continent_id: 1 , population: 2508)
Comune.create(description: "Colle Di Val D'Elsa", provincia_id: 56, regione_id: 12, country_id: 1, continent_id: 1 , population: 19521)
Comune.create(description: "Monteroni D'Arbia", provincia_id: 56, regione_id: 12, country_id: 1, continent_id: 1 , population: 7170)
Comune.create(description: "San Giovanni D'Asso", provincia_id: 56, regione_id: 12, country_id: 1, continent_id: 1 , population: 903)
Comune.create(description: "San Quirico D'Orcia", provincia_id: 56, regione_id: 12, country_id: 1, continent_id: 1 , population: 2463)
