Municipality.create(description: "Abbadia San Salvatore", province_id: 56, region_id:  12, country_id: 1, continent_id: 1 , population: 6832)
Municipality.create(description: "Asciano", province_id: 56, region_id:  12, country_id: 1, continent_id: 1 , population: 6488)
Municipality.create(description: "Buonconvento", province_id: 56, region_id:  12, country_id: 1, continent_id: 1 , population: 3168)
Municipality.create(description: "Castellina In Chianti", province_id: 56, region_id:  12, country_id: 1, continent_id: 1 , population: 2673)
Municipality.create(description: "Castelnuovo Berardenga", province_id: 56, region_id:  12, country_id: 1, continent_id: 1 , population: 7470)
Municipality.create(description: "Cetona", province_id: 56, region_id:  12, country_id: 1, continent_id: 1 , population: 2854)
Municipality.create(description: "Chianciano Terme", province_id: 56, region_id:  12, country_id: 1, continent_id: 1 , population: 6955)
Municipality.create(description: "Chiusdino", province_id: 56, region_id:  12, country_id: 1, continent_id: 1 , population: 1918)
Municipality.create(description: "Chiusi", province_id: 56, region_id:  12, country_id: 1, continent_id: 1 , population: 8612)
Municipality.create(description: "Gaiole In Chianti", province_id: 56, region_id:  12, country_id: 1, continent_id: 1 , population: 2386)
Municipality.create(description: "Montalcino", province_id: 56, region_id:  12, country_id: 1, continent_id: 1 , population: 5118)
Municipality.create(description: "Montepulciano", province_id: 56, region_id:  12, country_id: 1, continent_id: 1 , population: 13883)
Municipality.create(description: "Monteriggioni", province_id: 56, region_id:  12, country_id: 1, continent_id: 1 , population: 7891)
Municipality.create(description: "Monticiano", province_id: 56, region_id:  12, country_id: 1, continent_id: 1 , population: 1408)
Municipality.create(description: "Murlo", province_id: 56, region_id:  12, country_id: 1, continent_id: 1 , population: 1932)
Municipality.create(description: "Piancastagnaio", province_id: 56, region_id:  12, country_id: 1, continent_id: 1 , population: 4196)
Municipality.create(description: "Pienza", province_id: 56, region_id:  12, country_id: 1, continent_id: 1 , population: 2233)
Municipality.create(description: "Poggibonsi", province_id: 56, region_id:  12, country_id: 1, continent_id: 1 , population: 27420)
Municipality.create(description: "Radda In Chianti", province_id: 56, region_id:  12, country_id: 1, continent_id: 1 , population: 1669)
Municipality.create(description: "Radicofani", province_id: 56, region_id:  12, country_id: 1, continent_id: 1 , population: 1219)
Municipality.create(description: "Radicondoli", province_id: 56, region_id:  12, country_id: 1, continent_id: 1 , population: 978)
Municipality.create(description: "Rapolano Terme", province_id: 56, region_id:  12, country_id: 1, continent_id: 1 , population: 4776)
Municipality.create(description: "San Casciano Dei Bagni", province_id: 56, region_id:  12, country_id: 1, continent_id: 1 , population: 1745)
Municipality.create(description: "San Gimignano", province_id: 56, region_id:  12, country_id: 1, continent_id: 1 , population: 7114)
Municipality.create(description: "Sarteano", province_id: 56, region_id:  12, country_id: 1, continent_id: 1 , population: 4535)
Municipality.create(description: "Siena", province_id: 56, region_id:  12, country_id: 1, continent_id: 1 , population: 52625)
Municipality.create(description: "Sinalunga", province_id: 56, region_id:  12, country_id: 1, continent_id: 1 , population: 11790)
Municipality.create(description: "Sovicille", province_id: 56, region_id:  12, country_id: 1, continent_id: 1 , population: 8366)
Municipality.create(description: "Torrita Di Siena", province_id: 56, region_id:  12, country_id: 1, continent_id: 1 , population: 7121)
Municipality.create(description: "Trequanda", province_id: 56, region_id:  12, country_id: 1, continent_id: 1 , population: 1417)
Municipality.create(description: "Casole D'Elsa", province_id: 56, region_id:  12, country_id: 1, continent_id: 1 , population: 2931)
Municipality.create(description: "Castiglione D'Orcia", province_id: 56, region_id:  12, country_id: 1, continent_id: 1 , population: 2508)
Municipality.create(description: "Colle Di Val D'Elsa", province_id: 56, region_id:  12, country_id: 1, continent_id: 1 , population: 19521)
Municipality.create(description: "Monteroni D'Arbia", province_id: 56, region_id:  12, country_id: 1, continent_id: 1 , population: 7170)
Municipality.create(description: "San Giovanni D'Asso", province_id: 56, region_id:  12, country_id: 1, continent_id: 1 , population: 903)
Municipality.create(description: "San Quirico D'Orcia", province_id: 56, region_id:  12, country_id: 1, continent_id: 1 , population: 2463)
