Municipality.create(description: "Bagno Di Romagna", province_id: 59, region_id:  14, country_id: 1, continent_id: 1 , population: 6108)
Municipality.create(description: "Bertinoro", province_id: 59, region_id:  14, country_id: 1, continent_id: 1 , population: 9307)
Municipality.create(description: "Borghi", province_id: 59, region_id:  14, country_id: 1, continent_id: 1 , population: 2034)
Municipality.create(description: "Castrocaro Terme", province_id: 59, region_id:  14, country_id: 1, continent_id: 1 )
Municipality.create(description: "Cesena", province_id: 59, region_id:  14, country_id: 1, continent_id: 1 , population: 90948)
Municipality.create(description: "Cesenatico", province_id: 59, region_id:  14, country_id: 1, continent_id: 1 , population: 21716)
Municipality.create(description: "Civitella Di Romagna", province_id: 59, region_id:  14, country_id: 1, continent_id: 1 , population: 3794)
Municipality.create(description: "Dovadola", province_id: 59, region_id:  14, country_id: 1, continent_id: 1 , population: 1583)
Municipality.create(description: "Forlimpopoli", province_id: 59, region_id:  14, country_id: 1, continent_id: 1 , population: 11442)
Municipality.create(description: "Galeata", province_id: 59, region_id:  14, country_id: 1, continent_id: 1 , population: 2291)
Municipality.create(description: "Gambettola", province_id: 59, region_id:  14, country_id: 1, continent_id: 1 , population: 9416)
Municipality.create(description: "Gatteo", province_id: 59, region_id:  14, country_id: 1, continent_id: 1 , population: 6799)
Municipality.create(description: "Longiano", province_id: 59, region_id:  14, country_id: 1, continent_id: 1 , population: 5587)
Municipality.create(description: "Meldola", province_id: 59, region_id:  14, country_id: 1, continent_id: 1 , population: 9377)
Municipality.create(description: "Mercato Saraceno", province_id: 59, region_id:  14, country_id: 1, continent_id: 1 , population: 6185)
Municipality.create(description: "Modigliana", province_id: 59, region_id:  14, country_id: 1, continent_id: 1 , population: 4744)
Municipality.create(description: "Montiano", province_id: 59, region_id:  14, country_id: 1, continent_id: 1 , population: 1591)
Municipality.create(description: "Portico E San Benedetto", province_id: 59, region_id:  14, country_id: 1, continent_id: 1 , population: 863)
Municipality.create(description: "Predappio", province_id: 59, region_id:  14, country_id: 1, continent_id: 1 , population: 6149)
Municipality.create(description: "Premilcuore", province_id: 59, region_id:  14, country_id: 1, continent_id: 1 , population: 889)
Municipality.create(description: "Rocca San Casciano", province_id: 59, region_id:  14, country_id: 1, continent_id: 1 , population: 2116)
Municipality.create(description: "Roncofreddo", province_id: 59, region_id:  14, country_id: 1, continent_id: 1 , population: 2819)
Municipality.create(description: "San Mauro Pascoli", province_id: 59, region_id:  14, country_id: 1, continent_id: 1 , population: 9435)
Municipality.create(description: "Santa Sofia", province_id: 59, region_id:  14, country_id: 1, continent_id: 1 , population: 4276)
Municipality.create(description: "Sarsina", province_id: 59, region_id:  14, country_id: 1, continent_id: 1 , population: 3693)
Municipality.create(description: "Savignano Sul Rubicone", province_id: 59, region_id:  14, country_id: 1, continent_id: 1 , population: 14786)
Municipality.create(description: "Sogliano Al Rubicone", province_id: 59, region_id:  14, country_id: 1, continent_id: 1 , population: 2890)
Municipality.create(description: "Tredozio", province_id: 59, region_id:  14, country_id: 1, continent_id: 1 , population: 1317)
Municipality.create(description: "Verghereto", province_id: 59, region_id:  14, country_id: 1, continent_id: 1 , population: 2027)
Municipality.create(description: "Forli' ", province_id: 59, region_id:  14, country_id: 1, continent_id: 1 )
