#encoding: utf-8
Comune.create(:description => "Bagno Di Romagna", :provincia_id => 59, :regione_id => 14, :population => 6108)
Comune.create(:description => "Bertinoro", :provincia_id => 59, :regione_id => 14, :population => 9307)
Comune.create(:description => "Borghi", :provincia_id => 59, :regione_id => 14, :population => 2034)
Comune.create(:description => "Castrocaro Terme", :provincia_id => 59, :regione_id => 14)
Comune.create(:description => "Cesena", :provincia_id => 59, :regione_id => 14, :population => 90948)
Comune.create(:description => "Cesenatico", :provincia_id => 59, :regione_id => 14, :population => 21716)
Comune.create(:description => "Civitella Di Romagna", :provincia_id => 59, :regione_id => 14, :population => 3794)
Comune.create(:description => "Dovadola", :provincia_id => 59, :regione_id => 14, :population => 1583)
Comune.create(:description => "Forlimpopoli", :provincia_id => 59, :regione_id => 14, :population => 11442)
Comune.create(:description => "Galeata", :provincia_id => 59, :regione_id => 14, :population => 2291)
Comune.create(:description => "Gambettola", :provincia_id => 59, :regione_id => 14, :population => 9416)
Comune.create(:description => "Gatteo", :provincia_id => 59, :regione_id => 14, :population => 6799)
Comune.create(:description => "Longiano", :provincia_id => 59, :regione_id => 14, :population => 5587)
Comune.create(:description => "Meldola", :provincia_id => 59, :regione_id => 14, :population => 9377)
Comune.create(:description => "Mercato Saraceno", :provincia_id => 59, :regione_id => 14, :population => 6185)
Comune.create(:description => "Modigliana", :provincia_id => 59, :regione_id => 14, :population => 4744)
Comune.create(:description => "Montiano", :provincia_id => 59, :regione_id => 14, :population => 1591)
Comune.create(:description => "Portico E San Benedetto", :provincia_id => 59, :regione_id => 14, :population => 863)
Comune.create(:description => "Predappio", :provincia_id => 59, :regione_id => 14, :population => 6149)
Comune.create(:description => "Premilcuore", :provincia_id => 59, :regione_id => 14, :population => 889)
Comune.create(:description => "Rocca San Casciano", :provincia_id => 59, :regione_id => 14, :population => 2116)
Comune.create(:description => "Roncofreddo", :provincia_id => 59, :regione_id => 14, :population => 2819)
Comune.create(:description => "San Mauro Pascoli", :provincia_id => 59, :regione_id => 14, :population => 9435)
Comune.create(:description => "Santa Sofia", :provincia_id => 59, :regione_id => 14, :population => 4276)
Comune.create(:description => "Sarsina", :provincia_id => 59, :regione_id => 14, :population => 3693)
Comune.create(:description => "Savignano Sul Rubicone", :provincia_id => 59, :regione_id => 14, :population => 14786)
Comune.create(:description => "Sogliano Al Rubicone", :provincia_id => 59, :regione_id => 14, :population => 2890)
Comune.create(:description => "Tredozio", :provincia_id => 59, :regione_id => 14, :population => 1317)
Comune.create(:description => "Verghereto", :provincia_id => 59, :regione_id => 14, :population => 2027)
Comune.create(:description => "Forli' ", :provincia_id => 59, :regione_id => 14)
