#encoding: utf-8
Comune.create(description: "Bastiglia", provincia_id: 60, regione_id: 14, country_id: 1, continente_id: 1 , population: 3359)
Comune.create(description: "Bomporto", provincia_id: 60, regione_id: 14, country_id: 1, continente_id: 1 , population: 7583)
Comune.create(description: "Campogalliano", provincia_id: 60, regione_id: 14, country_id: 1, continente_id: 1 , population: 7762)
Comune.create(description: "Camposanto", provincia_id: 60, regione_id: 14, country_id: 1, continente_id: 1 , population: 3051)
Comune.create(description: "Carpi", provincia_id: 60, regione_id: 14, country_id: 1, continente_id: 1 , population: 61476)
Comune.create(description: "Castelfranco Emilia", provincia_id: 60, regione_id: 14, country_id: 1, continente_id: 1 , population: 25096)
Comune.create(description: "Castelnuovo Rangone", provincia_id: 60, regione_id: 14, country_id: 1, continente_id: 1 , population: 12096)
Comune.create(description: "Castelvetro Di Modena", provincia_id: 60, regione_id: 14, country_id: 1, continente_id: 1 , population: 9589)
Comune.create(description: "Cavezzo", provincia_id: 60, regione_id: 14, country_id: 1, continente_id: 1 , population: 6722)
Comune.create(description: "Concordia Sulla Secchia", provincia_id: 60, regione_id: 14, country_id: 1, continente_id: 1 , population: 8337)
Comune.create(description: "Fanano", provincia_id: 60, regione_id: 14, country_id: 1, continente_id: 1 , population: 2910)
Comune.create(description: "Finale Emilia", provincia_id: 60, regione_id: 14, country_id: 1, continente_id: 1 , population: 15141)
Comune.create(description: "Fiorano Modenese", provincia_id: 60, regione_id: 14, country_id: 1, continente_id: 1 , population: 16137)
Comune.create(description: "Fiumalbo", provincia_id: 60, regione_id: 14, country_id: 1, continente_id: 1 , population: 1370)
Comune.create(description: "Formigine", provincia_id: 60, regione_id: 14, country_id: 1, continente_id: 1 , population: 30073)
Comune.create(description: "Frassinoro", provincia_id: 60, regione_id: 14, country_id: 1, continente_id: 1 , population: 2154)
Comune.create(description: "Guiglia", provincia_id: 60, regione_id: 14, country_id: 1, continente_id: 1 , population: 3739)
Comune.create(description: "Lama Mocogno", provincia_id: 60, regione_id: 14, country_id: 1, continente_id: 1 , population: 3032)
Comune.create(description: "Maranello", provincia_id: 60, regione_id: 14, country_id: 1, continente_id: 1 , population: 15912)
Comune.create(description: "Marano Sul Panaro", provincia_id: 60, regione_id: 14, country_id: 1, continente_id: 1 , population: 3750)
Comune.create(description: "Medolla", provincia_id: 60, regione_id: 14, country_id: 1, continente_id: 1 , population: 5573)
Comune.create(description: "Mirandola", provincia_id: 60, regione_id: 14, country_id: 1, continente_id: 1 , population: 22068)
Comune.create(description: "Modena", provincia_id: 60, regione_id: 14, country_id: 1, continente_id: 1 , population: 175502)
Comune.create(description: "Montecreto", provincia_id: 60, regione_id: 14, country_id: 1, continente_id: 1 , population: 929)
Comune.create(description: "Montefiorino", provincia_id: 60, regione_id: 14, country_id: 1, continente_id: 1 , population: 2317)
Comune.create(description: "Montese", provincia_id: 60, regione_id: 14, country_id: 1, continente_id: 1 , population: 3181)
Comune.create(description: "Nonantola", provincia_id: 60, regione_id: 14, country_id: 1, continente_id: 1 , population: 12530)
Comune.create(description: "Novi Di Modena", provincia_id: 60, regione_id: 14, country_id: 1, continente_id: 1 , population: 10427)
Comune.create(description: "Palagano", provincia_id: 60, regione_id: 14, country_id: 1, continente_id: 1 , population: 2466)
Comune.create(description: "Pavullo Nel Frignano", provincia_id: 60, regione_id: 14, country_id: 1, continente_id: 1 , population: 15119)
Comune.create(description: "Pievepelago", provincia_id: 60, regione_id: 14, country_id: 1, continente_id: 1 , population: 2120)
Comune.create(description: "Polinago", provincia_id: 60, regione_id: 14, country_id: 1, continente_id: 1 , population: 1867)
Comune.create(description: "Prignano Sulla Secchia", provincia_id: 60, regione_id: 14, country_id: 1, continente_id: 1 , population: 3551)
Comune.create(description: "Ravarino", provincia_id: 60, regione_id: 14, country_id: 1, continente_id: 1 , population: 5316)
Comune.create(description: "Riolunato", provincia_id: 60, regione_id: 14, country_id: 1, continente_id: 1 , population: 737)
Comune.create(description: "San Cesario Sul Panaro", provincia_id: 60, regione_id: 14, country_id: 1, continente_id: 1 , population: 5302)
Comune.create(description: "San Felice Sul Panaro", provincia_id: 60, regione_id: 14, country_id: 1, continente_id: 1 , population: 10055)
Comune.create(description: "San Possidonio", provincia_id: 60, regione_id: 14, country_id: 1, continente_id: 1 , population: 3500)
Comune.create(description: "San Prospero", provincia_id: 60, regione_id: 14, country_id: 1, continente_id: 1 , population: 4448)
Comune.create(description: "Sassuolo", provincia_id: 60, regione_id: 14, country_id: 1, continente_id: 1 , population: 39852)
Comune.create(description: "Savignano Sul Panaro", provincia_id: 60, regione_id: 14, country_id: 1, continente_id: 1 , population: 8325)
Comune.create(description: "Serramazzoni", provincia_id: 60, regione_id: 14, country_id: 1, continente_id: 1 , population: 6883)
Comune.create(description: "Sestola", provincia_id: 60, regione_id: 14, country_id: 1, continente_id: 1 , population: 2670)
Comune.create(description: "Soliera", provincia_id: 60, regione_id: 14, country_id: 1, continente_id: 1 , population: 13222)
Comune.create(description: "Spilamberto", provincia_id: 60, regione_id: 14, country_id: 1, continente_id: 1 , population: 10973)
Comune.create(description: "Zocca", provincia_id: 60, regione_id: 14, country_id: 1, continente_id: 1 , population: 4593)
