Comune.create(description: "Bastiglia", province_id: 60, region_id:  14, country_id: 1, continent_id: 1 , population: 3359)
Comune.create(description: "Bomporto", province_id: 60, region_id:  14, country_id: 1, continent_id: 1 , population: 7583)
Comune.create(description: "Campogalliano", province_id: 60, region_id:  14, country_id: 1, continent_id: 1 , population: 7762)
Comune.create(description: "Camposanto", province_id: 60, region_id:  14, country_id: 1, continent_id: 1 , population: 3051)
Comune.create(description: "Carpi", province_id: 60, region_id:  14, country_id: 1, continent_id: 1 , population: 61476)
Comune.create(description: "Castelfranco Emilia", province_id: 60, region_id:  14, country_id: 1, continent_id: 1 , population: 25096)
Comune.create(description: "Castelnuovo Rangone", province_id: 60, region_id:  14, country_id: 1, continent_id: 1 , population: 12096)
Comune.create(description: "Castelvetro Di Modena", province_id: 60, region_id:  14, country_id: 1, continent_id: 1 , population: 9589)
Comune.create(description: "Cavezzo", province_id: 60, region_id:  14, country_id: 1, continent_id: 1 , population: 6722)
Comune.create(description: "Concordia Sulla Secchia", province_id: 60, region_id:  14, country_id: 1, continent_id: 1 , population: 8337)
Comune.create(description: "Fanano", province_id: 60, region_id:  14, country_id: 1, continent_id: 1 , population: 2910)
Comune.create(description: "Finale Emilia", province_id: 60, region_id:  14, country_id: 1, continent_id: 1 , population: 15141)
Comune.create(description: "Fiorano Modenese", province_id: 60, region_id:  14, country_id: 1, continent_id: 1 , population: 16137)
Comune.create(description: "Fiumalbo", province_id: 60, region_id:  14, country_id: 1, continent_id: 1 , population: 1370)
Comune.create(description: "Formigine", province_id: 60, region_id:  14, country_id: 1, continent_id: 1 , population: 30073)
Comune.create(description: "Frassinoro", province_id: 60, region_id:  14, country_id: 1, continent_id: 1 , population: 2154)
Comune.create(description: "Guiglia", province_id: 60, region_id:  14, country_id: 1, continent_id: 1 , population: 3739)
Comune.create(description: "Lama Mocogno", province_id: 60, region_id:  14, country_id: 1, continent_id: 1 , population: 3032)
Comune.create(description: "Maranello", province_id: 60, region_id:  14, country_id: 1, continent_id: 1 , population: 15912)
Comune.create(description: "Marano Sul Panaro", province_id: 60, region_id:  14, country_id: 1, continent_id: 1 , population: 3750)
Comune.create(description: "Medolla", province_id: 60, region_id:  14, country_id: 1, continent_id: 1 , population: 5573)
Comune.create(description: "Mirandola", province_id: 60, region_id:  14, country_id: 1, continent_id: 1 , population: 22068)
Comune.create(description: "Modena", province_id: 60, region_id:  14, country_id: 1, continent_id: 1 , population: 175502)
Comune.create(description: "Montecreto", province_id: 60, region_id:  14, country_id: 1, continent_id: 1 , population: 929)
Comune.create(description: "Montefiorino", province_id: 60, region_id:  14, country_id: 1, continent_id: 1 , population: 2317)
Comune.create(description: "Montese", province_id: 60, region_id:  14, country_id: 1, continent_id: 1 , population: 3181)
Comune.create(description: "Nonantola", province_id: 60, region_id:  14, country_id: 1, continent_id: 1 , population: 12530)
Comune.create(description: "Novi Di Modena", province_id: 60, region_id:  14, country_id: 1, continent_id: 1 , population: 10427)
Comune.create(description: "Palagano", province_id: 60, region_id:  14, country_id: 1, continent_id: 1 , population: 2466)
Comune.create(description: "Pavullo Nel Frignano", province_id: 60, region_id:  14, country_id: 1, continent_id: 1 , population: 15119)
Comune.create(description: "Pievepelago", province_id: 60, region_id:  14, country_id: 1, continent_id: 1 , population: 2120)
Comune.create(description: "Polinago", province_id: 60, region_id:  14, country_id: 1, continent_id: 1 , population: 1867)
Comune.create(description: "Prignano Sulla Secchia", province_id: 60, region_id:  14, country_id: 1, continent_id: 1 , population: 3551)
Comune.create(description: "Ravarino", province_id: 60, region_id:  14, country_id: 1, continent_id: 1 , population: 5316)
Comune.create(description: "Riolunato", province_id: 60, region_id:  14, country_id: 1, continent_id: 1 , population: 737)
Comune.create(description: "San Cesario Sul Panaro", province_id: 60, region_id:  14, country_id: 1, continent_id: 1 , population: 5302)
Comune.create(description: "San Felice Sul Panaro", province_id: 60, region_id:  14, country_id: 1, continent_id: 1 , population: 10055)
Comune.create(description: "San Possidonio", province_id: 60, region_id:  14, country_id: 1, continent_id: 1 , population: 3500)
Comune.create(description: "San Prospero", province_id: 60, region_id:  14, country_id: 1, continent_id: 1 , population: 4448)
Comune.create(description: "Sassuolo", province_id: 60, region_id:  14, country_id: 1, continent_id: 1 , population: 39852)
Comune.create(description: "Savignano Sul Panaro", province_id: 60, region_id:  14, country_id: 1, continent_id: 1 , population: 8325)
Comune.create(description: "Serramazzoni", province_id: 60, region_id:  14, country_id: 1, continent_id: 1 , population: 6883)
Comune.create(description: "Sestola", province_id: 60, region_id:  14, country_id: 1, continent_id: 1 , population: 2670)
Comune.create(description: "Soliera", province_id: 60, region_id:  14, country_id: 1, continent_id: 1 , population: 13222)
Comune.create(description: "Spilamberto", province_id: 60, region_id:  14, country_id: 1, continent_id: 1 , population: 10973)
Comune.create(description: "Zocca", province_id: 60, region_id:  14, country_id: 1, continent_id: 1 , population: 4593)
