Municipality.create(description: "Acqui Terme", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 19184)
Municipality.create(description: "Albera Ligure", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 357)
Municipality.create(description: "Alessandria", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 85438)
Municipality.create(description: "Alfiano Natta", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 793)
Municipality.create(description: "Alice Bel Colle", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 786)
Municipality.create(description: "Altavilla Monferrato", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 480)
Municipality.create(description: "Alzano Scrivia", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 392)
Municipality.create(description: "Arquata Scrivia", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 5765)
Municipality.create(description: "Avolasca", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 280)
Municipality.create(description: "Balzola", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 1444)
Municipality.create(description: "Basaluzzo", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 1897)
Municipality.create(description: "Bassignana", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 1737)
Municipality.create(description: "Belforte Monferrato", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 448)
Municipality.create(description: "Bergamasco", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 765)
Municipality.create(description: "Berzano Di Tortona", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 132)
Municipality.create(description: "Bistagno", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 1733)
Municipality.create(description: "Borghetto Di Borbera", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 1963)
Municipality.create(description: "Borgo San Martino", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 1366)
Municipality.create(description: "Borgoratto Alessandrino", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 611)
Municipality.create(description: "Bosco Marengo", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 2494)
Municipality.create(description: "Bosio", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 1177)
Municipality.create(description: "Bozzole", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 293)
Municipality.create(description: "Brignano Frascata", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 )
Municipality.create(description: "Cabella Ligure", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 641)
Municipality.create(description: "Camagna Monferrato", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Camino", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 734)
Municipality.create(description: "Cantalupo Ligure", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 555)
Municipality.create(description: "Carbonara Scrivia", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 966)
Municipality.create(description: "Carentino", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 313)
Municipality.create(description: "Carezzano", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 449)
Municipality.create(description: "Carpeneto", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 913)
Municipality.create(description: "Carrega Ligure", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 119)
Municipality.create(description: "Carrosio", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 465)
Municipality.create(description: "Cartosio", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 805)
Municipality.create(description: "Casal Cermelli", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 1146)
Municipality.create(description: "Casale Monferrato", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 35244)
Municipality.create(description: "Casaleggio Boiro", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 377)
Municipality.create(description: "Casalnoceto", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 877)
Municipality.create(description: "Casasco", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 149)
Municipality.create(description: "Cassano Spinola", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 1852)
Municipality.create(description: "Cassine", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 3042)
Municipality.create(description: "Cassinelle", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 864)
Municipality.create(description: "Castellania", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 95)
Municipality.create(description: "Castellar Guidobono", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 402)
Municipality.create(description: "Castellazzo Bormida", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 4268)
Municipality.create(description: "Castelletto Merli", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 470)
Municipality.create(description: "Castelletto Monferrato", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 1428)
Municipality.create(description: "Castelnuovo Bormida", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 648)
Municipality.create(description: "Castelnuovo Scrivia", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 5624)
Municipality.create(description: "Castelspina", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 394)
Municipality.create(description: "Cavatore", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 310)
Municipality.create(description: "Cella Monte", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 509)
Municipality.create(description: "Cereseto", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 431)
Municipality.create(description: "Cerreto Grue", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 339)
Municipality.create(description: "Cerrina", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 1599)
Municipality.create(description: "Coniolo", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 422)
Municipality.create(description: "Conzano", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 1005)
Municipality.create(description: "Costa Vescovato", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 347)
Municipality.create(description: "Cremolino", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 959)
Municipality.create(description: "Cuccaro Monferrato", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 367)
Municipality.create(description: "Denice", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 204)
Municipality.create(description: "Dernice", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 249)
Municipality.create(description: "Fabbrica Curone", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 838)
Municipality.create(description: "Felizzano", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 2395)
Municipality.create(description: "Fraconalto", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 328)
Municipality.create(description: "Francavilla Bisio", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 459)
Municipality.create(description: "Frascaro", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 418)
Municipality.create(description: "Frassinello Monferrato", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 562)
Municipality.create(description: "Frassineto Po", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 1465)
Municipality.create(description: "Fresonara", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 694)
Municipality.create(description: "Frugarolo", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 1856)
Municipality.create(description: "Fubine", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 1683)
Municipality.create(description: "Gabiano", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 1259)
Municipality.create(description: "Gamalero", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 778)
Municipality.create(description: "Garbagna", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 681)
Municipality.create(description: "Gavazzana", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 127)
Municipality.create(description: "Gavi", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 4506)
Municipality.create(description: "Giarole", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 690)
Municipality.create(description: "Gremiasco", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 361)
Municipality.create(description: "Grognardo", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 321)
Municipality.create(description: "Grondona", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 538)
Municipality.create(description: "Guazzora", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 294)
Municipality.create(description: "Lerma", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 801)
Municipality.create(description: "Lu", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 1213)
Municipality.create(description: "Malvicino", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 121)
Municipality.create(description: "Masio", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 1440)
Municipality.create(description: "Melazzo", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 1185)
Municipality.create(description: "Merana", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 185)
Municipality.create(description: "Mirabello Monferrato", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 1361)
Municipality.create(description: "Molare", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 2044)
Municipality.create(description: "Molino Dei Torti", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 738)
Municipality.create(description: "Mombello Monferrato", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 1095)
Municipality.create(description: "Momperone", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 232)
Municipality.create(description: "Moncestino", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 226)
Municipality.create(description: "Mongiardino Ligure", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 204)
Municipality.create(description: "Monleale", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 634)
Municipality.create(description: "Montaldeo", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 318)
Municipality.create(description: "Montaldo Bormida", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 690)
Municipality.create(description: "Montecastello", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 340)
Municipality.create(description: "Montegioco", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 306)
Municipality.create(description: "Montemarzino", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 352)
Municipality.create(description: "Morano Sul Po", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 1569)
Municipality.create(description: "Morbello", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 459)
Municipality.create(description: "Mornese", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 706)
Municipality.create(description: "Morsasco", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 718)
Municipality.create(description: "Murisengo", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 1511)
Municipality.create(description: "Novi Ligure", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 27223)
Municipality.create(description: "Occimiano", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 1385)
Municipality.create(description: "Odalengo Grande", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 533)
Municipality.create(description: "Odalengo Piccolo", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 274)
Municipality.create(description: "Olivola", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 145)
Municipality.create(description: "Orsara Bormida", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 417)
Municipality.create(description: "Ottiglio", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 659)
Municipality.create(description: "Ovada", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 11677)
Municipality.create(description: "Oviglio", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 1294)
Municipality.create(description: "Ozzano Monferrato", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 1567)
Municipality.create(description: "Paderna", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 243)
Municipality.create(description: "Pareto", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 688)
Municipality.create(description: "Parodi Ligure", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 721)
Municipality.create(description: "Pasturana", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 1011)
Municipality.create(description: "Pecetto Di Valenza", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 1312)
Municipality.create(description: "Pietra Marazzi", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 932)
Municipality.create(description: "Piovera", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 736)
Municipality.create(description: "Pomaro Monferrato", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 423)
Municipality.create(description: "Pontecurone", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 3781)
Municipality.create(description: "Pontestura", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 1558)
Municipality.create(description: "Ponti", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 677)
Municipality.create(description: "Ponzano Monferrato", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 404)
Municipality.create(description: "Ponzone", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 1206)
Municipality.create(description: "Pozzol Groppo", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 397)
Municipality.create(description: "Pozzolo Formigaro", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 4771)
Municipality.create(description: "Prasco", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 534)
Municipality.create(description: "Predosa", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 2074)
Municipality.create(description: "Quargnento", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 1296)
Municipality.create(description: "Quattordio", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 1753)
Municipality.create(description: "Ricaldone", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 687)
Municipality.create(description: "Rivalta Bormida", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 1443)
Municipality.create(description: "Rivarone", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 372)
Municipality.create(description: "Rocca Grimalda", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 1346)
Municipality.create(description: "Roccaforte Ligure", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 167)
Municipality.create(description: "Rocchetta Ligure", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 220)
Municipality.create(description: "Rosignano Monferrato", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 1650)
Municipality.create(description: "Sala Monferrato", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 475)
Municipality.create(description: "Sale", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 4246)
Municipality.create(description: "San Cristoforo", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 575)
Municipality.create(description: "San Giorgio Monferrato", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 1279)
Municipality.create(description: "San Salvatore Monferrato", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 4623)
Municipality.create(description: "San Sebastiano Curone", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 543)
Municipality.create(description: "Sardigliano", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 441)
Municipality.create(description: "Sarezzano", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 1156)
Municipality.create(description: "Serralunga Di Crea", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 617)
Municipality.create(description: "Serravalle Scrivia", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 5820)
Municipality.create(description: "Sezzadio", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 1291)
Municipality.create(description: "Solero", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 1685)
Municipality.create(description: "Solonghello", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 245)
Municipality.create(description: "Spigno Monferrato", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 1216)
Municipality.create(description: "Spineto Scrivia", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 322)
Municipality.create(description: "Stazzano", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 2108)
Municipality.create(description: "Strevi", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 1972)
Municipality.create(description: "Tagliolo Monferrato", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 1457)
Municipality.create(description: "Tassarolo", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 611)
Municipality.create(description: "Terruggia", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 812)
Municipality.create(description: "Terzo", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 846)
Municipality.create(description: "Ticineto", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 1384)
Municipality.create(description: "Tortona", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 25227)
Municipality.create(description: "Treville", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 280)
Municipality.create(description: "Trisobbio", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 682)
Municipality.create(description: "Valenza", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 20339)
Municipality.create(description: "Valmacca", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 1099)
Municipality.create(description: "Vignale Monferrato", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 1141)
Municipality.create(description: "Vignole Borbera", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 2037)
Municipality.create(description: "Viguzzolo", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 2884)
Municipality.create(description: "Villadeati", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 521)
Municipality.create(description: "Villalvernia", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 932)
Municipality.create(description: "Villamiroglio", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 312)
Municipality.create(description: "Villanova Monferrato", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 1743)
Municipality.create(description: "Villaromagnano", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 758)
Municipality.create(description: "Visone", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 1160)
Municipality.create(description: "Volpedo", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 1191)
Municipality.create(description: "Volpeglino", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 160)
Municipality.create(description: "Voltaggio", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 770)
Municipality.create(description: "Alluvioni Cambio'", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 1019)
Municipality.create(description: "Capriata D'Orba", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 1845)
Municipality.create(description: "Castelletto D'Erro", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 153)
Municipality.create(description: "Castelletto D'Orba", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 1891)
Municipality.create(description: "Isola Sant'Antonio", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 766)
Municipality.create(description: "Montechiaro D'Acqui", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 585)
Municipality.create(description: "Sant'Agata Fossili", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 413)
Municipality.create(description: "Silvano D'Orba", province_id: 5, region_id:  13, country_id: 1, continent_id: 1 , population: 1830)
