#encoding: utf-8
Comune.create(:description => "Acqui Terme", :provincia_id => 5, :regione_id => 13, :population => 19184)
Comune.create(:description => "Albera Ligure", :provincia_id => 5, :regione_id => 13, :population => 357)
Comune.create(:description => "Alessandria", :provincia_id => 5, :regione_id => 13, :population => 85438)
Comune.create(:description => "Alfiano Natta", :provincia_id => 5, :regione_id => 13, :population => 793)
Comune.create(:description => "Alice Bel Colle", :provincia_id => 5, :regione_id => 13, :population => 786)
Comune.create(:description => "Altavilla Monferrato", :provincia_id => 5, :regione_id => 13, :population => 480)
Comune.create(:description => "Alzano Scrivia", :provincia_id => 5, :regione_id => 13, :population => 392)
Comune.create(:description => "Arquata Scrivia", :provincia_id => 5, :regione_id => 13, :population => 5765)
Comune.create(:description => "Avolasca", :provincia_id => 5, :regione_id => 13, :population => 280)
Comune.create(:description => "Balzola", :provincia_id => 5, :regione_id => 13, :population => 1444)
Comune.create(:description => "Basaluzzo", :provincia_id => 5, :regione_id => 13, :population => 1897)
Comune.create(:description => "Bassignana", :provincia_id => 5, :regione_id => 13, :population => 1737)
Comune.create(:description => "Belforte Monferrato", :provincia_id => 5, :regione_id => 13, :population => 448)
Comune.create(:description => "Bergamasco", :provincia_id => 5, :regione_id => 13, :population => 765)
Comune.create(:description => "Berzano Di Tortona", :provincia_id => 5, :regione_id => 13, :population => 132)
Comune.create(:description => "Bistagno", :provincia_id => 5, :regione_id => 13, :population => 1733)
Comune.create(:description => "Borghetto Di Borbera", :provincia_id => 5, :regione_id => 13, :population => 1963)
Comune.create(:description => "Borgo San Martino", :provincia_id => 5, :regione_id => 13, :population => 1366)
Comune.create(:description => "Borgoratto Alessandrino", :provincia_id => 5, :regione_id => 13, :population => 611)
Comune.create(:description => "Bosco Marengo", :provincia_id => 5, :regione_id => 13, :population => 2494)
Comune.create(:description => "Bosio", :provincia_id => 5, :regione_id => 13, :population => 1177)
Comune.create(:description => "Bozzole", :provincia_id => 5, :regione_id => 13, :population => 293)
Comune.create(:description => "Brignano Frascata", :provincia_id => 5, :regione_id => 13)
Comune.create(:description => "Cabella Ligure", :provincia_id => 5, :regione_id => 13, :population => 641)
Comune.create(:description => "Camagna Monferrato", :provincia_id => 5, :regione_id => 13, :population => 0)
Comune.create(:description => "Camino", :provincia_id => 5, :regione_id => 13, :population => 734)
Comune.create(:description => "Cantalupo Ligure", :provincia_id => 5, :regione_id => 13, :population => 555)
Comune.create(:description => "Carbonara Scrivia", :provincia_id => 5, :regione_id => 13, :population => 966)
Comune.create(:description => "Carentino", :provincia_id => 5, :regione_id => 13, :population => 313)
Comune.create(:description => "Carezzano", :provincia_id => 5, :regione_id => 13, :population => 449)
Comune.create(:description => "Carpeneto", :provincia_id => 5, :regione_id => 13, :population => 913)
Comune.create(:description => "Carrega Ligure", :provincia_id => 5, :regione_id => 13, :population => 119)
Comune.create(:description => "Carrosio", :provincia_id => 5, :regione_id => 13, :population => 465)
Comune.create(:description => "Cartosio", :provincia_id => 5, :regione_id => 13, :population => 805)
Comune.create(:description => "Casal Cermelli", :provincia_id => 5, :regione_id => 13, :population => 1146)
Comune.create(:description => "Casale Monferrato", :provincia_id => 5, :regione_id => 13, :population => 35244)
Comune.create(:description => "Casaleggio Boiro", :provincia_id => 5, :regione_id => 13, :population => 377)
Comune.create(:description => "Casalnoceto", :provincia_id => 5, :regione_id => 13, :population => 877)
Comune.create(:description => "Casasco", :provincia_id => 5, :regione_id => 13, :population => 149)
Comune.create(:description => "Cassano Spinola", :provincia_id => 5, :regione_id => 13, :population => 1852)
Comune.create(:description => "Cassine", :provincia_id => 5, :regione_id => 13, :population => 3042)
Comune.create(:description => "Cassinelle", :provincia_id => 5, :regione_id => 13, :population => 864)
Comune.create(:description => "Castellania", :provincia_id => 5, :regione_id => 13, :population => 95)
Comune.create(:description => "Castellar Guidobono", :provincia_id => 5, :regione_id => 13, :population => 402)
Comune.create(:description => "Castellazzo Bormida", :provincia_id => 5, :regione_id => 13, :population => 4268)
Comune.create(:description => "Castelletto Merli", :provincia_id => 5, :regione_id => 13, :population => 470)
Comune.create(:description => "Castelletto Monferrato", :provincia_id => 5, :regione_id => 13, :population => 1428)
Comune.create(:description => "Castelnuovo Bormida", :provincia_id => 5, :regione_id => 13, :population => 648)
Comune.create(:description => "Castelnuovo Scrivia", :provincia_id => 5, :regione_id => 13, :population => 5624)
Comune.create(:description => "Castelspina", :provincia_id => 5, :regione_id => 13, :population => 394)
Comune.create(:description => "Cavatore", :provincia_id => 5, :regione_id => 13, :population => 310)
Comune.create(:description => "Cella Monte", :provincia_id => 5, :regione_id => 13, :population => 509)
Comune.create(:description => "Cereseto", :provincia_id => 5, :regione_id => 13, :population => 431)
Comune.create(:description => "Cerreto Grue", :provincia_id => 5, :regione_id => 13, :population => 339)
Comune.create(:description => "Cerrina", :provincia_id => 5, :regione_id => 13, :population => 1599)
Comune.create(:description => "Coniolo", :provincia_id => 5, :regione_id => 13, :population => 422)
Comune.create(:description => "Conzano", :provincia_id => 5, :regione_id => 13, :population => 1005)
Comune.create(:description => "Costa Vescovato", :provincia_id => 5, :regione_id => 13, :population => 347)
Comune.create(:description => "Cremolino", :provincia_id => 5, :regione_id => 13, :population => 959)
Comune.create(:description => "Cuccaro Monferrato", :provincia_id => 5, :regione_id => 13, :population => 367)
Comune.create(:description => "Denice", :provincia_id => 5, :regione_id => 13, :population => 204)
Comune.create(:description => "Dernice", :provincia_id => 5, :regione_id => 13, :population => 249)
Comune.create(:description => "Fabbrica Curone", :provincia_id => 5, :regione_id => 13, :population => 838)
Comune.create(:description => "Felizzano", :provincia_id => 5, :regione_id => 13, :population => 2395)
Comune.create(:description => "Fraconalto", :provincia_id => 5, :regione_id => 13, :population => 328)
Comune.create(:description => "Francavilla Bisio", :provincia_id => 5, :regione_id => 13, :population => 459)
Comune.create(:description => "Frascaro", :provincia_id => 5, :regione_id => 13, :population => 418)
Comune.create(:description => "Frassinello Monferrato", :provincia_id => 5, :regione_id => 13, :population => 562)
Comune.create(:description => "Frassineto Po", :provincia_id => 5, :regione_id => 13, :population => 1465)
Comune.create(:description => "Fresonara", :provincia_id => 5, :regione_id => 13, :population => 694)
Comune.create(:description => "Frugarolo", :provincia_id => 5, :regione_id => 13, :population => 1856)
Comune.create(:description => "Fubine", :provincia_id => 5, :regione_id => 13, :population => 1683)
Comune.create(:description => "Gabiano", :provincia_id => 5, :regione_id => 13, :population => 1259)
Comune.create(:description => "Gamalero", :provincia_id => 5, :regione_id => 13, :population => 778)
Comune.create(:description => "Garbagna", :provincia_id => 5, :regione_id => 13, :population => 681)
Comune.create(:description => "Gavazzana", :provincia_id => 5, :regione_id => 13, :population => 127)
Comune.create(:description => "Gavi", :provincia_id => 5, :regione_id => 13, :population => 4506)
Comune.create(:description => "Giarole", :provincia_id => 5, :regione_id => 13, :population => 690)
Comune.create(:description => "Gremiasco", :provincia_id => 5, :regione_id => 13, :population => 361)
Comune.create(:description => "Grognardo", :provincia_id => 5, :regione_id => 13, :population => 321)
Comune.create(:description => "Grondona", :provincia_id => 5, :regione_id => 13, :population => 538)
Comune.create(:description => "Guazzora", :provincia_id => 5, :regione_id => 13, :population => 294)
Comune.create(:description => "Lerma", :provincia_id => 5, :regione_id => 13, :population => 801)
Comune.create(:description => "Lu", :provincia_id => 5, :regione_id => 13, :population => 1213)
Comune.create(:description => "Malvicino", :provincia_id => 5, :regione_id => 13, :population => 121)
Comune.create(:description => "Masio", :provincia_id => 5, :regione_id => 13, :population => 1440)
Comune.create(:description => "Melazzo", :provincia_id => 5, :regione_id => 13, :population => 1185)
Comune.create(:description => "Merana", :provincia_id => 5, :regione_id => 13, :population => 185)
Comune.create(:description => "Mirabello Monferrato", :provincia_id => 5, :regione_id => 13, :population => 1361)
Comune.create(:description => "Molare", :provincia_id => 5, :regione_id => 13, :population => 2044)
Comune.create(:description => "Molino Dei Torti", :provincia_id => 5, :regione_id => 13, :population => 738)
Comune.create(:description => "Mombello Monferrato", :provincia_id => 5, :regione_id => 13, :population => 1095)
Comune.create(:description => "Momperone", :provincia_id => 5, :regione_id => 13, :population => 232)
Comune.create(:description => "Moncestino", :provincia_id => 5, :regione_id => 13, :population => 226)
Comune.create(:description => "Mongiardino Ligure", :provincia_id => 5, :regione_id => 13, :population => 204)
Comune.create(:description => "Monleale", :provincia_id => 5, :regione_id => 13, :population => 634)
Comune.create(:description => "Montaldeo", :provincia_id => 5, :regione_id => 13, :population => 318)
Comune.create(:description => "Montaldo Bormida", :provincia_id => 5, :regione_id => 13, :population => 690)
Comune.create(:description => "Montecastello", :provincia_id => 5, :regione_id => 13, :population => 340)
Comune.create(:description => "Montegioco", :provincia_id => 5, :regione_id => 13, :population => 306)
Comune.create(:description => "Montemarzino", :provincia_id => 5, :regione_id => 13, :population => 352)
Comune.create(:description => "Morano Sul Po", :provincia_id => 5, :regione_id => 13, :population => 1569)
Comune.create(:description => "Morbello", :provincia_id => 5, :regione_id => 13, :population => 459)
Comune.create(:description => "Mornese", :provincia_id => 5, :regione_id => 13, :population => 706)
Comune.create(:description => "Morsasco", :provincia_id => 5, :regione_id => 13, :population => 718)
Comune.create(:description => "Murisengo", :provincia_id => 5, :regione_id => 13, :population => 1511)
Comune.create(:description => "Novi Ligure", :provincia_id => 5, :regione_id => 13, :population => 27223)
Comune.create(:description => "Occimiano", :provincia_id => 5, :regione_id => 13, :population => 1385)
Comune.create(:description => "Odalengo Grande", :provincia_id => 5, :regione_id => 13, :population => 533)
Comune.create(:description => "Odalengo Piccolo", :provincia_id => 5, :regione_id => 13, :population => 274)
Comune.create(:description => "Olivola", :provincia_id => 5, :regione_id => 13, :population => 145)
Comune.create(:description => "Orsara Bormida", :provincia_id => 5, :regione_id => 13, :population => 417)
Comune.create(:description => "Ottiglio", :provincia_id => 5, :regione_id => 13, :population => 659)
Comune.create(:description => "Ovada", :provincia_id => 5, :regione_id => 13, :population => 11677)
Comune.create(:description => "Oviglio", :provincia_id => 5, :regione_id => 13, :population => 1294)
Comune.create(:description => "Ozzano Monferrato", :provincia_id => 5, :regione_id => 13, :population => 1567)
Comune.create(:description => "Paderna", :provincia_id => 5, :regione_id => 13, :population => 243)
Comune.create(:description => "Pareto", :provincia_id => 5, :regione_id => 13, :population => 688)
Comune.create(:description => "Parodi Ligure", :provincia_id => 5, :regione_id => 13, :population => 721)
Comune.create(:description => "Pasturana", :provincia_id => 5, :regione_id => 13, :population => 1011)
Comune.create(:description => "Pecetto Di Valenza", :provincia_id => 5, :regione_id => 13, :population => 1312)
Comune.create(:description => "Pietra Marazzi", :provincia_id => 5, :regione_id => 13, :population => 932)
Comune.create(:description => "Piovera", :provincia_id => 5, :regione_id => 13, :population => 736)
Comune.create(:description => "Pomaro Monferrato", :provincia_id => 5, :regione_id => 13, :population => 423)
Comune.create(:description => "Pontecurone", :provincia_id => 5, :regione_id => 13, :population => 3781)
Comune.create(:description => "Pontestura", :provincia_id => 5, :regione_id => 13, :population => 1558)
Comune.create(:description => "Ponti", :provincia_id => 5, :regione_id => 13, :population => 677)
Comune.create(:description => "Ponzano Monferrato", :provincia_id => 5, :regione_id => 13, :population => 404)
Comune.create(:description => "Ponzone", :provincia_id => 5, :regione_id => 13, :population => 1206)
Comune.create(:description => "Pozzol Groppo", :provincia_id => 5, :regione_id => 13, :population => 397)
Comune.create(:description => "Pozzolo Formigaro", :provincia_id => 5, :regione_id => 13, :population => 4771)
Comune.create(:description => "Prasco", :provincia_id => 5, :regione_id => 13, :population => 534)
Comune.create(:description => "Predosa", :provincia_id => 5, :regione_id => 13, :population => 2074)
Comune.create(:description => "Quargnento", :provincia_id => 5, :regione_id => 13, :population => 1296)
Comune.create(:description => "Quattordio", :provincia_id => 5, :regione_id => 13, :population => 1753)
Comune.create(:description => "Ricaldone", :provincia_id => 5, :regione_id => 13, :population => 687)
Comune.create(:description => "Rivalta Bormida", :provincia_id => 5, :regione_id => 13, :population => 1443)
Comune.create(:description => "Rivarone", :provincia_id => 5, :regione_id => 13, :population => 372)
Comune.create(:description => "Rocca Grimalda", :provincia_id => 5, :regione_id => 13, :population => 1346)
Comune.create(:description => "Roccaforte Ligure", :provincia_id => 5, :regione_id => 13, :population => 167)
Comune.create(:description => "Rocchetta Ligure", :provincia_id => 5, :regione_id => 13, :population => 220)
Comune.create(:description => "Rosignano Monferrato", :provincia_id => 5, :regione_id => 13, :population => 1650)
Comune.create(:description => "Sala Monferrato", :provincia_id => 5, :regione_id => 13, :population => 475)
Comune.create(:description => "Sale", :provincia_id => 5, :regione_id => 13, :population => 4246)
Comune.create(:description => "San Cristoforo", :provincia_id => 5, :regione_id => 13, :population => 575)
Comune.create(:description => "San Giorgio Monferrato", :provincia_id => 5, :regione_id => 13, :population => 1279)
Comune.create(:description => "San Salvatore Monferrato", :provincia_id => 5, :regione_id => 13, :population => 4623)
Comune.create(:description => "San Sebastiano Curone", :provincia_id => 5, :regione_id => 13, :population => 543)
Comune.create(:description => "Sardigliano", :provincia_id => 5, :regione_id => 13, :population => 441)
Comune.create(:description => "Sarezzano", :provincia_id => 5, :regione_id => 13, :population => 1156)
Comune.create(:description => "Serralunga Di Crea", :provincia_id => 5, :regione_id => 13, :population => 617)
Comune.create(:description => "Serravalle Scrivia", :provincia_id => 5, :regione_id => 13, :population => 5820)
Comune.create(:description => "Sezzadio", :provincia_id => 5, :regione_id => 13, :population => 1291)
Comune.create(:description => "Solero", :provincia_id => 5, :regione_id => 13, :population => 1685)
Comune.create(:description => "Solonghello", :provincia_id => 5, :regione_id => 13, :population => 245)
Comune.create(:description => "Spigno Monferrato", :provincia_id => 5, :regione_id => 13, :population => 1216)
Comune.create(:description => "Spineto Scrivia", :provincia_id => 5, :regione_id => 13, :population => 322)
Comune.create(:description => "Stazzano", :provincia_id => 5, :regione_id => 13, :population => 2108)
Comune.create(:description => "Strevi", :provincia_id => 5, :regione_id => 13, :population => 1972)
Comune.create(:description => "Tagliolo Monferrato", :provincia_id => 5, :regione_id => 13, :population => 1457)
Comune.create(:description => "Tassarolo", :provincia_id => 5, :regione_id => 13, :population => 611)
Comune.create(:description => "Terruggia", :provincia_id => 5, :regione_id => 13, :population => 812)
Comune.create(:description => "Terzo", :provincia_id => 5, :regione_id => 13, :population => 846)
Comune.create(:description => "Ticineto", :provincia_id => 5, :regione_id => 13, :population => 1384)
Comune.create(:description => "Tortona", :provincia_id => 5, :regione_id => 13, :population => 25227)
Comune.create(:description => "Treville", :provincia_id => 5, :regione_id => 13, :population => 280)
Comune.create(:description => "Trisobbio", :provincia_id => 5, :regione_id => 13, :population => 682)
Comune.create(:description => "Valenza", :provincia_id => 5, :regione_id => 13, :population => 20339)
Comune.create(:description => "Valmacca", :provincia_id => 5, :regione_id => 13, :population => 1099)
Comune.create(:description => "Vignale Monferrato", :provincia_id => 5, :regione_id => 13, :population => 1141)
Comune.create(:description => "Vignole Borbera", :provincia_id => 5, :regione_id => 13, :population => 2037)
Comune.create(:description => "Viguzzolo", :provincia_id => 5, :regione_id => 13, :population => 2884)
Comune.create(:description => "Villadeati", :provincia_id => 5, :regione_id => 13, :population => 521)
Comune.create(:description => "Villalvernia", :provincia_id => 5, :regione_id => 13, :population => 932)
Comune.create(:description => "Villamiroglio", :provincia_id => 5, :regione_id => 13, :population => 312)
Comune.create(:description => "Villanova Monferrato", :provincia_id => 5, :regione_id => 13, :population => 1743)
Comune.create(:description => "Villaromagnano", :provincia_id => 5, :regione_id => 13, :population => 758)
Comune.create(:description => "Visone", :provincia_id => 5, :regione_id => 13, :population => 1160)
Comune.create(:description => "Volpedo", :provincia_id => 5, :regione_id => 13, :population => 1191)
Comune.create(:description => "Volpeglino", :provincia_id => 5, :regione_id => 13, :population => 160)
Comune.create(:description => "Voltaggio", :provincia_id => 5, :regione_id => 13, :population => 770)
Comune.create(:description => "Alluvioni Cambio'", :provincia_id => 5, :regione_id => 13, :population => 1019)
Comune.create(:description => "Capriata D'Orba", :provincia_id => 5, :regione_id => 13, :population => 1845)
Comune.create(:description => "Castelletto D'Erro", :provincia_id => 5, :regione_id => 13, :population => 153)
Comune.create(:description => "Castelletto D'Orba", :provincia_id => 5, :regione_id => 13, :population => 1891)
Comune.create(:description => "Isola Sant'Antonio", :provincia_id => 5, :regione_id => 13, :population => 766)
Comune.create(:description => "Montechiaro D'Acqui", :provincia_id => 5, :regione_id => 13, :population => 585)
Comune.create(:description => "Sant'Agata Fossili", :provincia_id => 5, :regione_id => 13, :population => 413)
Comune.create(:description => "Silvano D'Orba", :provincia_id => 5, :regione_id => 13, :population => 1830)
