Comune.create(description: "Albareto", province_id: 61, region_id:  14, country_id: 1, continent_id: 1 , population: 2181)
Comune.create(description: "Bardi", province_id: 61, region_id:  14, country_id: 1, continent_id: 1 , population: 2719)
Comune.create(description: "Bedonia", province_id: 61, region_id:  14, country_id: 1, continent_id: 1 , population: 3823)
Comune.create(description: "Berceto", province_id: 61, region_id:  14, country_id: 1, continent_id: 1 , population: 2434)
Comune.create(description: "Bore", province_id: 61, region_id:  14, country_id: 1, continent_id: 1 , population: 904)
Comune.create(description: "Borgo Val Di Taro", province_id: 61, region_id:  14, country_id: 1, continent_id: 1 , population: 7084)
Comune.create(description: "Busseto", province_id: 61, region_id:  14, country_id: 1, continent_id: 1 , population: 6841)
Comune.create(description: "Calestano", province_id: 61, region_id:  14, country_id: 1, continent_id: 1 , population: 1813)
Comune.create(description: "Collecchio", province_id: 61, region_id:  14, country_id: 1, continent_id: 1 , population: 11904)
Comune.create(description: "Colorno", province_id: 61, region_id:  14, country_id: 1, continent_id: 1 , population: 7971)
Comune.create(description: "Compiano", province_id: 61, region_id:  14, country_id: 1, continent_id: 1 , population: 1097)
Comune.create(description: "Corniglio", province_id: 61, region_id:  14, country_id: 1, continent_id: 1 , population: 2314)
Comune.create(description: "Felino", province_id: 61, region_id:  14, country_id: 1, continent_id: 1 , population: 7197)
Comune.create(description: "Fidenza", province_id: 61, region_id:  14, country_id: 1, continent_id: 1 , population: 23424)
Comune.create(description: "Fontanellato", province_id: 61, region_id:  14, country_id: 1, continent_id: 1 , population: 6338)
Comune.create(description: "Fontevivo", province_id: 61, region_id:  14, country_id: 1, continent_id: 1 , population: 4874)
Comune.create(description: "Fornovo Di Taro", province_id: 61, region_id:  14, country_id: 1, continent_id: 1 , population: 5984)
Comune.create(description: "Langhirano", province_id: 61, region_id:  14, country_id: 1, continent_id: 1 , population: 8388)
Comune.create(description: "Medesano", province_id: 61, region_id:  14, country_id: 1, continent_id: 1 , population: 9139)
Comune.create(description: "Mezzani", province_id: 61, region_id:  14, country_id: 1, continent_id: 1 , population: 2942)
Comune.create(description: "Monchio Delle Corti", province_id: 61, region_id:  14, country_id: 1, continent_id: 1 , population: 1254)
Comune.create(description: "Montechiarugolo", province_id: 61, region_id:  14, country_id: 1, continent_id: 1 , population: 8903)
Comune.create(description: "Neviano Degli Arduini", province_id: 61, region_id:  14, country_id: 1, continent_id: 1 , population: 3727)
Comune.create(description: "Noceto", province_id: 61, region_id:  14, country_id: 1, continent_id: 1 , population: 10631)
Comune.create(description: "Palanzano", province_id: 61, region_id:  14, country_id: 1, continent_id: 1 , population: 1352)
Comune.create(description: "Parma", province_id: 61, region_id:  14, country_id: 1, continent_id: 1 , population: 163457)
Comune.create(description: "Pellegrino Parmense", province_id: 61, region_id:  14, country_id: 1, continent_id: 1 , population: 1285)
Comune.create(description: "Polesine Parmense", province_id: 61, region_id:  14, country_id: 1, continent_id: 1 , population: 1509)
Comune.create(description: "Roccabianca", province_id: 61, region_id:  14, country_id: 1, continent_id: 1 , population: 3133)
Comune.create(description: "Sala Baganza", province_id: 61, region_id:  14, country_id: 1, continent_id: 1 , population: 4616)
Comune.create(description: "Salsomaggiore Terme", province_id: 61, region_id:  14, country_id: 1, continent_id: 1 , population: 17906)
Comune.create(description: "San Secondo Parmense", province_id: 61, region_id:  14, country_id: 1, continent_id: 1 , population: 5037)
Comune.create(description: "Sissa", province_id: 61, region_id:  14, country_id: 1, continent_id: 1 , population: 3946)
Comune.create(description: "Solignano", province_id: 61, region_id:  14, country_id: 1, continent_id: 1 , population: 1921)
Comune.create(description: "Soragna", province_id: 61, region_id:  14, country_id: 1, continent_id: 1 , population: 4358)
Comune.create(description: "Sorbolo", province_id: 61, region_id:  14, country_id: 1, continent_id: 1 , population: 8656)
Comune.create(description: "Terenzo", province_id: 61, region_id:  14, country_id: 1, continent_id: 1 , population: 1289)
Comune.create(description: "Tizzano Val Parma", province_id: 61, region_id:  14, country_id: 1, continent_id: 1 , population: 2126)
Comune.create(description: "Tornolo", province_id: 61, region_id:  14, country_id: 1, continent_id: 1 , population: 1291)
Comune.create(description: "Torrile", province_id: 61, region_id:  14, country_id: 1, continent_id: 1 , population: 5955)
Comune.create(description: "Traversetolo", province_id: 61, region_id:  14, country_id: 1, continent_id: 1 , population: 7931)
Comune.create(description: "Trecasali", province_id: 61, region_id:  14, country_id: 1, continent_id: 1 , population: 3054)
Comune.create(description: "Valmozzola", province_id: 61, region_id:  14, country_id: 1, continent_id: 1 , population: 677)
Comune.create(description: "Varsi", province_id: 61, region_id:  14, country_id: 1, continent_id: 1 , population: 1520)
Comune.create(description: "Zibello", province_id: 61, region_id:  14, country_id: 1, continent_id: 1 , population: 2010)
Comune.create(description: "Lesignano De' Bagni", province_id: 61, region_id:  14, country_id: 1, continent_id: 1 , population: 3825)
Comune.create(description: "Varano De' Melegari", province_id: 61, region_id:  14, country_id: 1, continent_id: 1 , population: 2236)
