#encoding: utf-8
Comune.create(:description => "Albareto", :provincia_id => 61, :regione_id => 14, :population => 2181)
Comune.create(:description => "Bardi", :provincia_id => 61, :regione_id => 14, :population => 2719)
Comune.create(:description => "Bedonia", :provincia_id => 61, :regione_id => 14, :population => 3823)
Comune.create(:description => "Berceto", :provincia_id => 61, :regione_id => 14, :population => 2434)
Comune.create(:description => "Bore", :provincia_id => 61, :regione_id => 14, :population => 904)
Comune.create(:description => "Borgo Val Di Taro", :provincia_id => 61, :regione_id => 14, :population => 7084)
Comune.create(:description => "Busseto", :provincia_id => 61, :regione_id => 14, :population => 6841)
Comune.create(:description => "Calestano", :provincia_id => 61, :regione_id => 14, :population => 1813)
Comune.create(:description => "Collecchio", :provincia_id => 61, :regione_id => 14, :population => 11904)
Comune.create(:description => "Colorno", :provincia_id => 61, :regione_id => 14, :population => 7971)
Comune.create(:description => "Compiano", :provincia_id => 61, :regione_id => 14, :population => 1097)
Comune.create(:description => "Corniglio", :provincia_id => 61, :regione_id => 14, :population => 2314)
Comune.create(:description => "Felino", :provincia_id => 61, :regione_id => 14, :population => 7197)
Comune.create(:description => "Fidenza", :provincia_id => 61, :regione_id => 14, :population => 23424)
Comune.create(:description => "Fontanellato", :provincia_id => 61, :regione_id => 14, :population => 6338)
Comune.create(:description => "Fontevivo", :provincia_id => 61, :regione_id => 14, :population => 4874)
Comune.create(:description => "Fornovo Di Taro", :provincia_id => 61, :regione_id => 14, :population => 5984)
Comune.create(:description => "Langhirano", :provincia_id => 61, :regione_id => 14, :population => 8388)
Comune.create(:description => "Medesano", :provincia_id => 61, :regione_id => 14, :population => 9139)
Comune.create(:description => "Mezzani", :provincia_id => 61, :regione_id => 14, :population => 2942)
Comune.create(:description => "Monchio Delle Corti", :provincia_id => 61, :regione_id => 14, :population => 1254)
Comune.create(:description => "Montechiarugolo", :provincia_id => 61, :regione_id => 14, :population => 8903)
Comune.create(:description => "Neviano Degli Arduini", :provincia_id => 61, :regione_id => 14, :population => 3727)
Comune.create(:description => "Noceto", :provincia_id => 61, :regione_id => 14, :population => 10631)
Comune.create(:description => "Palanzano", :provincia_id => 61, :regione_id => 14, :population => 1352)
Comune.create(:description => "Parma", :provincia_id => 61, :regione_id => 14, :population => 163457)
Comune.create(:description => "Pellegrino Parmense", :provincia_id => 61, :regione_id => 14, :population => 1285)
Comune.create(:description => "Polesine Parmense", :provincia_id => 61, :regione_id => 14, :population => 1509)
Comune.create(:description => "Roccabianca", :provincia_id => 61, :regione_id => 14, :population => 3133)
Comune.create(:description => "Sala Baganza", :provincia_id => 61, :regione_id => 14, :population => 4616)
Comune.create(:description => "Salsomaggiore Terme", :provincia_id => 61, :regione_id => 14, :population => 17906)
Comune.create(:description => "San Secondo Parmense", :provincia_id => 61, :regione_id => 14, :population => 5037)
Comune.create(:description => "Sissa", :provincia_id => 61, :regione_id => 14, :population => 3946)
Comune.create(:description => "Solignano", :provincia_id => 61, :regione_id => 14, :population => 1921)
Comune.create(:description => "Soragna", :provincia_id => 61, :regione_id => 14, :population => 4358)
Comune.create(:description => "Sorbolo", :provincia_id => 61, :regione_id => 14, :population => 8656)
Comune.create(:description => "Terenzo", :provincia_id => 61, :regione_id => 14, :population => 1289)
Comune.create(:description => "Tizzano Val Parma", :provincia_id => 61, :regione_id => 14, :population => 2126)
Comune.create(:description => "Tornolo", :provincia_id => 61, :regione_id => 14, :population => 1291)
Comune.create(:description => "Torrile", :provincia_id => 61, :regione_id => 14, :population => 5955)
Comune.create(:description => "Traversetolo", :provincia_id => 61, :regione_id => 14, :population => 7931)
Comune.create(:description => "Trecasali", :provincia_id => 61, :regione_id => 14, :population => 3054)
Comune.create(:description => "Valmozzola", :provincia_id => 61, :regione_id => 14, :population => 677)
Comune.create(:description => "Varsi", :provincia_id => 61, :regione_id => 14, :population => 1520)
Comune.create(:description => "Zibello", :provincia_id => 61, :regione_id => 14, :population => 2010)
Comune.create(:description => "Lesignano De' Bagni", :provincia_id => 61, :regione_id => 14, :population => 3825)
Comune.create(:description => "Varano De' Melegari", :provincia_id => 61, :regione_id => 14, :population => 2236)
