Comune.create(description: "Vigolzone", province_id: 62, region_id:  14, country_id: 1, continent_id: 1 , population: 3556)
Comune.create(description: "Agazzano", province_id: 62, region_id:  14, country_id: 1, continent_id: 1 , population: 2003)
Comune.create(description: "Alseno", province_id: 62, region_id:  14, country_id: 1, continent_id: 1 , population: 4661)
Comune.create(description: "Besenzone", province_id: 62, region_id:  14, country_id: 1, continent_id: 1 , population: 953)
Comune.create(description: "Bettola", province_id: 62, region_id:  14, country_id: 1, continent_id: 1 , population: 3187)
Comune.create(description: "Bobbio", province_id: 62, region_id:  14, country_id: 1, continent_id: 1 , population: 3816)
Comune.create(description: "Borgonovo Val Tidone", province_id: 62, region_id:  14, country_id: 1, continent_id: 1 , population: 6866)
Comune.create(description: "Cadeo", province_id: 62, region_id:  14, country_id: 1, continent_id: 1 , population: 5459)
Comune.create(description: "Calendasco", province_id: 62, region_id:  14, country_id: 1, continent_id: 1 , population: 2311)
Comune.create(description: "Caminata", province_id: 62, region_id:  14, country_id: 1, continent_id: 1 , population: 301)
Comune.create(description: "Caorso", province_id: 62, region_id:  14, country_id: 1, continent_id: 1 , population: 4511)
Comune.create(description: "Carpaneto Piacentino", province_id: 62, region_id:  14, country_id: 1, continent_id: 1 , population: 6881)
Comune.create(description: "Castel San Giovanni", province_id: 62, region_id:  14, country_id: 1, continent_id: 1 , population: 11962)
Comune.create(description: "Castelvetro Piacentino", province_id: 62, region_id:  14, country_id: 1, continent_id: 1 , population: 4839)
Comune.create(description: "Cerignale", province_id: 62, region_id:  14, country_id: 1, continent_id: 1 , population: 224)
Comune.create(description: "Coli", province_id: 62, region_id:  14, country_id: 1, continent_id: 1 , population: 1076)
Comune.create(description: "Corte Brugnatella", province_id: 62, region_id:  14, country_id: 1, continent_id: 1 , population: 818)
Comune.create(description: "Cortemaggiore", province_id: 62, region_id:  14, country_id: 1, continent_id: 1 , population: 4172)
Comune.create(description: "Farini", province_id: 62, region_id:  14, country_id: 1, continent_id: 1 , population: 1881)
Comune.create(description: "Ferriere", province_id: 62, region_id:  14, country_id: 1, continent_id: 1 , population: 2010)
Comune.create(description: "Gazzola", province_id: 62, region_id:  14, country_id: 1, continent_id: 1 , population: 1676)
Comune.create(description: "Gossolengo", province_id: 62, region_id:  14, country_id: 1, continent_id: 1 , population: 3763)
Comune.create(description: "Gragnano Trebbiense", province_id: 62, region_id:  14, country_id: 1, continent_id: 1 , population: 3470)
Comune.create(description: "Gropparello", province_id: 62, region_id:  14, country_id: 1, continent_id: 1 , population: 2369)
Comune.create(description: "Morfasso", province_id: 62, region_id:  14, country_id: 1, continent_id: 1 , population: 1371)
Comune.create(description: "Nibbiano", province_id: 62, region_id:  14, country_id: 1, continent_id: 1 , population: 2388)
Comune.create(description: "Ottone", province_id: 62, region_id:  14, country_id: 1, continent_id: 1 , population: 730)
Comune.create(description: "Pecorara", province_id: 62, region_id:  14, country_id: 1, continent_id: 1 , population: 915)
Comune.create(description: "Piacenza", province_id: 62, region_id:  14, country_id: 1, continent_id: 1 , population: 95594)
Comune.create(description: "Pianello Val Tidone", province_id: 62, region_id:  14, country_id: 1, continent_id: 1 , population: 2207)
Comune.create(description: "Piozzano", province_id: 62, region_id:  14, country_id: 1, continent_id: 1 , population: 696)
Comune.create(description: "Podenzano", province_id: 62, region_id:  14, country_id: 1, continent_id: 1 , population: 7491)
Comune.create(description: "Pontenure", province_id: 62, region_id:  14, country_id: 1, continent_id: 1 , population: 5230)
Comune.create(description: "Rivergaro", province_id: 62, region_id:  14, country_id: 1, continent_id: 1 , population: 5507)
Comune.create(description: "Rottofreno", province_id: 62, region_id:  14, country_id: 1, continent_id: 1 , population: 8844)
Comune.create(description: "San Giorgio Piacentino", province_id: 62, region_id:  14, country_id: 1, continent_id: 1 , population: 5238)
Comune.create(description: "San Pietro In Cerro", province_id: 62, region_id:  14, country_id: 1, continent_id: 1 , population: 957)
Comune.create(description: "Sarmato", province_id: 62, region_id:  14, country_id: 1, continent_id: 1 , population: 2589)
Comune.create(description: "Travo", province_id: 62, region_id:  14, country_id: 1, continent_id: 1 , population: 2002)
Comune.create(description: "Vernasca", province_id: 62, region_id:  14, country_id: 1, continent_id: 1 , population: 2458)
Comune.create(description: "Zerba", province_id: 62, region_id:  14, country_id: 1, continent_id: 1 , population: 140)
Comune.create(description: "Ziano Piacentino", province_id: 62, region_id:  14, country_id: 1, continent_id: 1 , population: 2645)
Comune.create(description: "Castell'Arquato", province_id: 62, region_id:  14, country_id: 1, continent_id: 1 , population: 4567)
Comune.create(description: "Fiorenzuola D'Arda", province_id: 62, region_id:  14, country_id: 1, continent_id: 1 , population: 13339)
Comune.create(description: "Lugagnano Val D'Arda", province_id: 62, region_id:  14, country_id: 1, continent_id: 1 , population: 4202)
Comune.create(description: "Monticelli D'Ongina", province_id: 62, region_id:  14, country_id: 1, continent_id: 1 , population: 5244)
Comune.create(description: "Ponte Dell'Olio", province_id: 62, region_id:  14, country_id: 1, continent_id: 1 , population: 4823)
Comune.create(description: "Villanova Sull'Arda", province_id: 62, region_id:  14, country_id: 1, continent_id: 1 , population: 1930)
