#encoding: utf-8
Comune.create(:description => "Aprilia", :provincia_id => 40, :regione_id => 9, stato_id: 1, continente_id: 1 , :population => 56028)
Comune.create(:description => "Bassiano", :provincia_id => 40, :regione_id => 9, stato_id: 1, continente_id: 1 , :population => 1617)
Comune.create(:description => "Campodimele", :provincia_id => 40, :regione_id => 9, stato_id: 1, continente_id: 1 , :population => 733)
Comune.create(:description => "Castelforte", :provincia_id => 40, :regione_id => 9, stato_id: 1, continente_id: 1 , :population => 4518)
Comune.create(:description => "Cisterna Di Latina", :provincia_id => 40, :regione_id => 9, stato_id: 1, continente_id: 1 , :population => 32584)
Comune.create(:description => "Cori", :provincia_id => 40, :regione_id => 9, stato_id: 1, continente_id: 1 , :population => 10529)
Comune.create(:description => "Fondi", :provincia_id => 40, :regione_id => 9, stato_id: 1, continente_id: 1 , :population => 31023)
Comune.create(:description => "Formia", :provincia_id => 40, :regione_id => 9, stato_id: 1, continente_id: 1 , :population => 34931)
Comune.create(:description => "Gaeta", :provincia_id => 40, :regione_id => 9, stato_id: 1, continente_id: 1 , :population => 21179)
Comune.create(:description => "Itri", :provincia_id => 40, :regione_id => 9, stato_id: 1, continente_id: 1 , :population => 8749)
Comune.create(:description => "Latina", :provincia_id => 40, :regione_id => 9, stato_id: 1, continente_id: 1 , :population => 107898)
Comune.create(:description => "Lenola", :provincia_id => 40, :regione_id => 9, stato_id: 1, continente_id: 1 , :population => 4131)
Comune.create(:description => "Maenza", :provincia_id => 40, :regione_id => 9, stato_id: 1, continente_id: 1 , :population => 3017)
Comune.create(:description => "Minturno", :provincia_id => 40, :regione_id => 9, stato_id: 1, continente_id: 1 , :population => 17814)
Comune.create(:description => "Monte San Biagio", :provincia_id => 40, :regione_id => 9, stato_id: 1, continente_id: 1 , :population => 5996)
Comune.create(:description => "Norma", :provincia_id => 40, :regione_id => 9, stato_id: 1, continente_id: 1 , :population => 3792)
Comune.create(:description => "Pontinia", :provincia_id => 40, :regione_id => 9, stato_id: 1, continente_id: 1 , :population => 13027)
Comune.create(:description => "Ponza", :provincia_id => 40, :regione_id => 9, stato_id: 1, continente_id: 1 , :population => 3110)
Comune.create(:description => "Priverno", :provincia_id => 40, :regione_id => 9, stato_id: 1, continente_id: 1 , :population => 13133)
Comune.create(:description => "Prossedi", :provincia_id => 40, :regione_id => 9, stato_id: 1, continente_id: 1 , :population => 1248)
Comune.create(:description => "Rocca Massima", :provincia_id => 40, :regione_id => 9, stato_id: 1, continente_id: 1 , :population => 1104)
Comune.create(:description => "Roccagorga", :provincia_id => 40, :regione_id => 9, stato_id: 1, continente_id: 1 , :population => 4386)
Comune.create(:description => "Roccasecca Dei Volsci", :provincia_id => 40, :regione_id => 9, stato_id: 1, continente_id: 1 , :population => 1201)
Comune.create(:description => "Sabaudia", :provincia_id => 40, :regione_id => 9, stato_id: 1, continente_id: 1 , :population => 16229)
Comune.create(:description => "San Felice Circeo", :provincia_id => 40, :regione_id => 9, stato_id: 1, continente_id: 1 , :population => 8036)
Comune.create(:description => "Santi Cosma E Damiano", :provincia_id => 40, :regione_id => 9, stato_id: 1, continente_id: 1 , :population => 6532)
Comune.create(:description => "Sermoneta", :provincia_id => 40, :regione_id => 9, stato_id: 1, continente_id: 1 , :population => 6620)
Comune.create(:description => "Sezze", :provincia_id => 40, :regione_id => 9, stato_id: 1, continente_id: 1 , :population => 21935)
Comune.create(:description => "Sonnino", :provincia_id => 40, :regione_id => 9, stato_id: 1, continente_id: 1 , :population => 7043)
Comune.create(:description => "Sperlonga", :provincia_id => 40, :regione_id => 9, stato_id: 1, continente_id: 1 , :population => 3102)
Comune.create(:description => "Spigno Saturnia", :provincia_id => 40, :regione_id => 9, stato_id: 1, continente_id: 1 , :population => 2719)
Comune.create(:description => "Terracina", :provincia_id => 40, :regione_id => 9, stato_id: 1, continente_id: 1 , :population => 36633)
Comune.create(:description => "Ventotene", :provincia_id => 40, :regione_id => 9, stato_id: 1, continente_id: 1 , :population => 633)
