Comune.create(description: "Albinea", province_id: 64, region_id:  14, country_id: 1, continent_id: 1 , population: 7750)
Comune.create(description: "Bagnolo In Piano", province_id: 64, region_id:  14, country_id: 1, continent_id: 1 , population: 8103)
Comune.create(description: "Baiso", province_id: 64, region_id:  14, country_id: 1, continent_id: 1 , population: 3261)
Comune.create(description: "Bibbiano", province_id: 64, region_id:  14, country_id: 1, continent_id: 1 , population: 7725)
Comune.create(description: "Boretto", province_id: 64, region_id:  14, country_id: 1, continent_id: 1 , population: 4636)
Comune.create(description: "Brescello", province_id: 64, region_id:  14, country_id: 1, continent_id: 1 , population: 4817)
Comune.create(description: "Busana", province_id: 64, region_id:  14, country_id: 1, continent_id: 1 , population: 1352)
Comune.create(description: "Cadelbosco Di Sopra", province_id: 64, region_id:  14, country_id: 1, continent_id: 1 , population: 7867)
Comune.create(description: "Campagnola Emilia", province_id: 64, region_id:  14, country_id: 1, continent_id: 1 , population: 4900)
Comune.create(description: "Campegine", province_id: 64, region_id:  14, country_id: 1, continent_id: 1 , population: 4551)
Comune.create(description: "Canossa", province_id: 64, region_id:  14, country_id: 1, continent_id: 1 , population: 3377)
Comune.create(description: "Carpineti", province_id: 64, region_id:  14, country_id: 1, continent_id: 1 , population: 4111)
Comune.create(description: "Casalgrande", province_id: 64, region_id:  14, country_id: 1, continent_id: 1 , population: 14226)
Comune.create(description: "Casina", province_id: 64, region_id:  14, country_id: 1, continent_id: 1 , population: 4392)
Comune.create(description: "Castellarano", province_id: 64, region_id:  14, country_id: 1, continent_id: 1 , population: 11774)
Comune.create(description: "Castelnovo Di Sotto", province_id: 64, region_id:  14, country_id: 1, continent_id: 1 , population: 7810)
Comune.create(description: "Cavriago", province_id: 64, region_id:  14, country_id: 1, continent_id: 1 , population: 8968)
Comune.create(description: "Collagna", province_id: 64, region_id:  14, country_id: 1, continent_id: 1 , population: 1005)
Comune.create(description: "Correggio", province_id: 64, region_id:  14, country_id: 1, continent_id: 1 , population: 20604)
Comune.create(description: "Fabbrico", province_id: 64, region_id:  14, country_id: 1, continent_id: 1 , population: 5517)
Comune.create(description: "Gattatico", province_id: 64, region_id:  14, country_id: 1, continent_id: 1 , population: 5389)
Comune.create(description: "Gualtieri", province_id: 64, region_id:  14, country_id: 1, continent_id: 1 , population: 6229)
Comune.create(description: "Guastalla", province_id: 64, region_id:  14, country_id: 1, continent_id: 1 , population: 13886)
Comune.create(description: "Ligonchio", province_id: 64, region_id:  14, country_id: 1, continent_id: 1 , population: 1005)
Comune.create(description: "Luzzara", province_id: 64, region_id:  14, country_id: 1, continent_id: 1 , population: 8517)
Comune.create(description: "Montecchio Emilia", province_id: 64, region_id:  14, country_id: 1, continent_id: 1 , population: 8742)
Comune.create(description: "Novellara", province_id: 64, region_id:  14, country_id: 1, continent_id: 1 , population: 11912)
Comune.create(description: "Poviglio", province_id: 64, region_id:  14, country_id: 1, continent_id: 1 , population: 6522)
Comune.create(description: "Quattro Castella", province_id: 64, region_id:  14, country_id: 1, continent_id: 1 , population: 11204)
Comune.create(description: "Ramiseto", province_id: 64, region_id:  14, country_id: 1, continent_id: 1 , population: 1468)
Comune.create(description: "Reggio Emilia", province_id: 64, region_id:  14, country_id: 1, continent_id: 1 )
Comune.create(description: "Reggiolo", province_id: 64, region_id:  14, country_id: 1, continent_id: 1 , population: 8559)
Comune.create(description: "Rio Saliceto", province_id: 64, region_id:  14, country_id: 1, continent_id: 1 , population: 5258)
Comune.create(description: "Rolo", province_id: 64, region_id:  14, country_id: 1, continent_id: 1 , population: 3631)
Comune.create(description: "Rubiera", province_id: 64, region_id:  14, country_id: 1, continent_id: 1 , population: 11458)
Comune.create(description: "San Martino In Rio", province_id: 64, region_id:  14, country_id: 1, continent_id: 1 , population: 6484)
Comune.create(description: "Scandiano", province_id: 64, region_id:  14, country_id: 1, continent_id: 1 , population: 22839)
Comune.create(description: "Toano", province_id: 64, region_id:  14, country_id: 1, continent_id: 1 , population: 4264)
Comune.create(description: "Vetto", province_id: 64, region_id:  14, country_id: 1, continent_id: 1 , population: 1972)
Comune.create(description: "Vezzano Sul Crostolo", province_id: 64, region_id:  14, country_id: 1, continent_id: 1 , population: 3797)
Comune.create(description: "Viano", province_id: 64, region_id:  14, country_id: 1, continent_id: 1 , population: 3017)
Comune.create(description: "Villa Minozzo", province_id: 64, region_id:  14, country_id: 1, continent_id: 1 , population: 4147)
Comune.create(description: "Castelnovo Ne' Monti", province_id: 64, region_id:  14, country_id: 1, continent_id: 1 , population: 10046)
Comune.create(description: "San Polo D'Enza", province_id: 64, region_id:  14, country_id: 1, continent_id: 1 , population: 5221)
Comune.create(description: "Sant'Ilario D'Enza", province_id: 64, region_id:  14, country_id: 1, continent_id: 1 , population: 9702)
