Comune.create(description: "Bellaria-Igea Marina", province_id: 65, region_id:  14, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Cattolica", province_id: 65, region_id:  14, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Coriano", province_id: 65, region_id:  14, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Gemmano", province_id: 65, region_id:  14, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Misano Adriatico", province_id: 65, region_id:  14, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Mondaino", province_id: 65, region_id:  14, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Monte Colombo", province_id: 65, region_id:  14, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Montefiore Conca", province_id: 65, region_id:  14, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Montegridolfo", province_id: 65, region_id:  14, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Montescudo", province_id: 65, region_id:  14, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Morciano Di Romagna", province_id: 65, region_id:  14, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Poggio Berni", province_id: 65, region_id:  14, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Riccione", province_id: 65, region_id:  14, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Rimini", province_id: 65, region_id:  14, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Saludecio", province_id: 65, region_id:  14, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "San Clemente", province_id: 65, region_id:  14, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "San Giovanni In Marignano", province_id: 65, region_id:  14, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Santarcangelo Di Romagna", province_id: 65, region_id:  14, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Torriana", province_id: 65, region_id:  14, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Verucchio", province_id: 65, region_id:  14, country_id: 1, continent_id: 1 , population: 0)
