#encoding: utf-8
Comune.create(description: "Bellaria-Igea Marina", provincia_id: 65, regione_id: 14, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Cattolica", provincia_id: 65, regione_id: 14, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Coriano", provincia_id: 65, regione_id: 14, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Gemmano", provincia_id: 65, regione_id: 14, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Misano Adriatico", provincia_id: 65, regione_id: 14, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Mondaino", provincia_id: 65, regione_id: 14, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Monte Colombo", provincia_id: 65, regione_id: 14, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Montefiore Conca", provincia_id: 65, regione_id: 14, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Montegridolfo", provincia_id: 65, regione_id: 14, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Montescudo", provincia_id: 65, regione_id: 14, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Morciano Di Romagna", provincia_id: 65, regione_id: 14, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Poggio Berni", provincia_id: 65, regione_id: 14, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Riccione", provincia_id: 65, regione_id: 14, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Rimini", provincia_id: 65, regione_id: 14, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Saludecio", provincia_id: 65, regione_id: 14, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "San Clemente", provincia_id: 65, regione_id: 14, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "San Giovanni In Marignano", provincia_id: 65, regione_id: 14, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Santarcangelo Di Romagna", provincia_id: 65, regione_id: 14, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Torriana", provincia_id: 65, regione_id: 14, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Verucchio", provincia_id: 65, regione_id: 14, stato_id: 1, continente_id: 1 , population: 0)
