Comune.create(description: "Agordo", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 4281)
Comune.create(description: "Alano Di Piave", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 2773)
Comune.create(description: "Alleghe", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 1408)
Comune.create(description: "Auronzo Di Cadore", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 3616)
Comune.create(description: "Belluno", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 35050)
Comune.create(description: "Borca Di Cadore", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 774)
Comune.create(description: "Calalzo Di Cadore", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 2419)
Comune.create(description: "Castello Lavazzo", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 )
Comune.create(description: "Cencenighe Agordino", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 1484)
Comune.create(description: "Cesiomaggiore", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 4084)
Comune.create(description: "Cibiana Di Cadore", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 483)
Comune.create(description: "Colle Santa Lucia", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 418)
Comune.create(description: "Comelico Superiore", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 2446)
Comune.create(description: "Danta Di Cadore", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 552)
Comune.create(description: "Domegge Di Cadore", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 2645)
Comune.create(description: "Falcade", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 2207)
Comune.create(description: "Feltre", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 19240)
Comune.create(description: "Fonzaso", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 3414)
Comune.create(description: "Forno Di Zoldo", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 2892)
Comune.create(description: "Gosaldo", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 884)
Comune.create(description: "La Valle Agordina", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 1208)
Comune.create(description: "Lamon", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 3412)
Comune.create(description: "Lentiai", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 2959)
Comune.create(description: "Limana", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 4509)
Comune.create(description: "Livinallongo Del Col Di Lana", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 1417)
Comune.create(description: "Longarone", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 4122)
Comune.create(description: "Lorenzago Di Cadore", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 578)
Comune.create(description: "Lozzo Di Cadore", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 1615)
Comune.create(description: "Mel", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 6248)
Comune.create(description: "Ospitale Di Cadore", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 365)
Comune.create(description: "Pedavena", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 4387)
Comune.create(description: "Perarolo Di Cadore", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 362)
Comune.create(description: "Pieve Di Cadore", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 3858)
Comune.create(description: "Ponte Nelle Alpi", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 7913)
Comune.create(description: "Quero", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 2312)
Comune.create(description: "Rivamonte Agordino", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 688)
Comune.create(description: "Rocca Pietore", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 1451)
Comune.create(description: "San Gregorio Nelle Alpi", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 1599)
Comune.create(description: "San Pietro Di Cadore", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 1839)
Comune.create(description: "San Tomaso Agordino", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 812)
Comune.create(description: "San Vito Di Cadore", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 1718)
Comune.create(description: "Santa Giustina", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 6428)
Comune.create(description: "Santo Stefano Di Cadore", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 2905)
Comune.create(description: "Sappada", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 1359)
Comune.create(description: "Sedico", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 8701)
Comune.create(description: "Selva Di Cadore", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 563)
Comune.create(description: "Seren Del Grappa", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 2607)
Comune.create(description: "Sospirolo", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 3193)
Comune.create(description: "Soverzene", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 422)
Comune.create(description: "Sovramonte", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 1697)
Comune.create(description: "Taibon Agordino", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 1772)
Comune.create(description: "Tambre", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 1529)
Comune.create(description: "Trichiana", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 4498)
Comune.create(description: "Vallada Agordina", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 556)
Comune.create(description: "Valle Di Cadore", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 2033)
Comune.create(description: "Vas", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 864)
Comune.create(description: "Vigo Di Cadore", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 1650)
Comune.create(description: "Vodo Cadore", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 )
Comune.create(description: "Voltago Agordino", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 991)
Comune.create(description: "Zoldo Alto", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 1184)
Comune.create(description: "Arsie'", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 2806)
Comune.create(description: "Canale D'Agordo", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 1236)
Comune.create(description: "Chies D'Alpago", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 1570)
Comune.create(description: "Cortina D'Ampezzo", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 6085)
Comune.create(description: "Farra D'Alpago", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 2703)
Comune.create(description: "Pieve D'Alpago", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 2028)
Comune.create(description: "Puos D'Alpago", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 2347)
Comune.create(description: "San Nicolo' Di Comelico", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 426)
Comune.create(description: "Zoppe' Di Cadore", provincia_id: 66, regione_id: 17, country_id: 1, continent_id: 1 , population: 303)
