Municipality.create(description: "Agordo", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 4281)
Municipality.create(description: "Alano Di Piave", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 2773)
Municipality.create(description: "Alleghe", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 1408)
Municipality.create(description: "Auronzo Di Cadore", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 3616)
Municipality.create(description: "Belluno", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 35050)
Municipality.create(description: "Borca Di Cadore", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 774)
Municipality.create(description: "Calalzo Di Cadore", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 2419)
Municipality.create(description: "Castello Lavazzo", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 )
Municipality.create(description: "Cencenighe Agordino", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 1484)
Municipality.create(description: "Cesiomaggiore", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 4084)
Municipality.create(description: "Cibiana Di Cadore", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 483)
Municipality.create(description: "Colle Santa Lucia", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 418)
Municipality.create(description: "Comelico Superiore", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 2446)
Municipality.create(description: "Danta Di Cadore", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 552)
Municipality.create(description: "Domegge Di Cadore", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 2645)
Municipality.create(description: "Falcade", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 2207)
Municipality.create(description: "Feltre", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 19240)
Municipality.create(description: "Fonzaso", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 3414)
Municipality.create(description: "Forno Di Zoldo", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 2892)
Municipality.create(description: "Gosaldo", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 884)
Municipality.create(description: "La Valle Agordina", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 1208)
Municipality.create(description: "Lamon", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 3412)
Municipality.create(description: "Lentiai", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 2959)
Municipality.create(description: "Limana", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 4509)
Municipality.create(description: "Livinallongo Del Col Di Lana", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 1417)
Municipality.create(description: "Longarone", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 4122)
Municipality.create(description: "Lorenzago Di Cadore", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 578)
Municipality.create(description: "Lozzo Di Cadore", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 1615)
Municipality.create(description: "Mel", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 6248)
Municipality.create(description: "Ospitale Di Cadore", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 365)
Municipality.create(description: "Pedavena", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 4387)
Municipality.create(description: "Perarolo Di Cadore", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 362)
Municipality.create(description: "Pieve Di Cadore", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 3858)
Municipality.create(description: "Ponte Nelle Alpi", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 7913)
Municipality.create(description: "Quero", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 2312)
Municipality.create(description: "Rivamonte Agordino", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 688)
Municipality.create(description: "Rocca Pietore", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 1451)
Municipality.create(description: "San Gregorio Nelle Alpi", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 1599)
Municipality.create(description: "San Pietro Di Cadore", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 1839)
Municipality.create(description: "San Tomaso Agordino", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 812)
Municipality.create(description: "San Vito Di Cadore", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 1718)
Municipality.create(description: "Santa Giustina", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 6428)
Municipality.create(description: "Santo Stefano Di Cadore", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 2905)
Municipality.create(description: "Sappada", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 1359)
Municipality.create(description: "Sedico", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 8701)
Municipality.create(description: "Selva Di Cadore", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 563)
Municipality.create(description: "Seren Del Grappa", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 2607)
Municipality.create(description: "Sospirolo", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 3193)
Municipality.create(description: "Soverzene", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 422)
Municipality.create(description: "Sovramonte", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 1697)
Municipality.create(description: "Taibon Agordino", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 1772)
Municipality.create(description: "Tambre", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 1529)
Municipality.create(description: "Trichiana", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 4498)
Municipality.create(description: "Vallada Agordina", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 556)
Municipality.create(description: "Valle Di Cadore", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 2033)
Municipality.create(description: "Vas", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 864)
Municipality.create(description: "Vigo Di Cadore", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 1650)
Municipality.create(description: "Vodo Cadore", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 )
Municipality.create(description: "Voltago Agordino", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 991)
Municipality.create(description: "Zoldo Alto", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 1184)
Municipality.create(description: "Arsie'", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 2806)
Municipality.create(description: "Canale D'Agordo", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 1236)
Municipality.create(description: "Chies D'Alpago", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 1570)
Municipality.create(description: "Cortina D'Ampezzo", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 6085)
Municipality.create(description: "Farra D'Alpago", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 2703)
Municipality.create(description: "Pieve D'Alpago", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 2028)
Municipality.create(description: "Puos D'Alpago", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 2347)
Municipality.create(description: "San Nicolo' Di Comelico", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 426)
Municipality.create(description: "Zoppe' Di Cadore", province_id: 66, region_id:  17, country_id: 1, continent_id: 1 , population: 303)
