Comune.create(description: "Abano Terme", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 18206)
Comune.create(description: "Agna", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 3158)
Comune.create(description: "Albignasego", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 19147)
Comune.create(description: "Anguillara Veneta", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 4739)
Comune.create(description: "Arre", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 2029)
Comune.create(description: "Arzergrande", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 4113)
Comune.create(description: "Bagnoli Di Sopra", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 3882)
Comune.create(description: "Baone", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 3138)
Comune.create(description: "Barbona", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 780)
Comune.create(description: "Battaglia Terme", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 4152)
Comune.create(description: "Boara Pisani", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 2507)
Comune.create(description: "Borgoricco", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 6939)
Comune.create(description: "Bovolenta", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 3144)
Comune.create(description: "Brugine", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 6107)
Comune.create(description: "Cadoneghe", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 14755)
Comune.create(description: "Campo San Martino", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 5371)
Comune.create(description: "Campodarsego", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 11474)
Comune.create(description: "Campodoro", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 2170)
Comune.create(description: "Camposampiero", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 10680)
Comune.create(description: "Candiana", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 2455)
Comune.create(description: "Carceri", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 1524)
Comune.create(description: "Carmignano Di Brenta", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 7027)
Comune.create(description: "Cartura", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 4075)
Comune.create(description: "Casale Di Scodosia", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 4856)
Comune.create(description: "Casalserugo", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 5519)
Comune.create(description: "Castelbaldo", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 1697)
Comune.create(description: "Cervarese Santa Croce", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 4725)
Comune.create(description: "Cinto Euganeo", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 2039)
Comune.create(description: "Cittadella", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 18743)
Comune.create(description: "Codevigo", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 5617)
Comune.create(description: "Conselve", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 8970)
Comune.create(description: "Correzzola", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 5310)
Comune.create(description: "Curtarolo", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 6294)
Comune.create(description: "Due Carrare", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Este", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 16704)
Comune.create(description: "Fontaniva", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 7460)
Comune.create(description: "Galliera Veneta", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 6614)
Comune.create(description: "Galzignano Terme", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 4225)
Comune.create(description: "Gazzo Padovano", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 3457)
Comune.create(description: "Grantorto", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 3778)
Comune.create(description: "Granze", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 1671)
Comune.create(description: "Legnaro", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 6895)
Comune.create(description: "Limena", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 6858)
Comune.create(description: "Loreggia", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 5754)
Comune.create(description: "Lozzo Atestino", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 3108)
Comune.create(description: "Masi", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 1802)
Comune.create(description: "Massanzago", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 4703)
Comune.create(description: "Megliadino San Fidenzio", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 1834)
Comune.create(description: "Megliadino San Vitale", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 1946)
Comune.create(description: "Merlara", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 2960)
Comune.create(description: "Mestrino", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 8442)
Comune.create(description: "Monselice", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 17458)
Comune.create(description: "Montagnana", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 9391)
Comune.create(description: "Montegrotto Terme", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 10405)
Comune.create(description: "Noventa Padovana", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 8083)
Comune.create(description: "Ospedaletto Euganeo", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 5401)
Comune.create(description: "Padova", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 204870)
Comune.create(description: "Pernumia", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 3717)
Comune.create(description: "Piazzola Sul Brenta", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 10682)
Comune.create(description: "Piombino Dese", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 8604)
Comune.create(description: "Piove Di Sacco", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 17517)
Comune.create(description: "Polverara", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 2345)
Comune.create(description: "Ponso", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 2365)
Comune.create(description: "Pontelongo", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 3759)
Comune.create(description: "Pozzonovo", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 3445)
Comune.create(description: "Rovolon", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 4171)
Comune.create(description: "Rubano", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 13671)
Comune.create(description: "Saccolongo", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 4477)
Comune.create(description: "Saletto", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 2577)
Comune.create(description: "San Giorgio Delle Pertiche", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 7846)
Comune.create(description: "San Giorgio In Bosco", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 5834)
Comune.create(description: "San Martino Di Lupari", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 11420)
Comune.create(description: "San Pietro In Gu", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 4367)
Comune.create(description: "San Pietro Viminario", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 2481)
Comune.create(description: "Santa Giustina In Colle", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 6397)
Comune.create(description: "Saonara", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 8946)
Comune.create(description: "Selvazzano Dentro", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 19753)
Comune.create(description: "Solesino", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 7071)
Comune.create(description: "Stanghella", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 4458)
Comune.create(description: "Teolo", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 8277)
Comune.create(description: "Terrassa Padovana", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 2128)
Comune.create(description: "Tombolo", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 6944)
Comune.create(description: "Torreglia", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 5880)
Comune.create(description: "Trebaseleghe", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 10998)
Comune.create(description: "Tribano", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 3992)
Comune.create(description: "Urbana", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 2235)
Comune.create(description: "Veggiano", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 2922)
Comune.create(description: "Vescovana", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 1568)
Comune.create(description: "Vigodarzere", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 11702)
Comune.create(description: "Vigonza", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 19458)
Comune.create(description: "Villa Del Conte", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 5030)
Comune.create(description: "Villa Estense", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 2423)
Comune.create(description: "Villafranca Padovana", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 7952)
Comune.create(description: "Villanova Di Camposampiero", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 4849)
Comune.create(description: "Vo", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 3432)
Comune.create(description: "Arqua' Petrarca", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 1876)
Comune.create(description: "Masera' Di Padova", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 7695)
Comune.create(description: "Piacenza D'Adige", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 1419)
Comune.create(description: "Ponte San Nicolo'", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 12059)
Comune.create(description: "Santa Margherita D'Adige", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 2243)
Comune.create(description: "Sant'Angelo Di Piove Di Sacco", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 6665)
Comune.create(description: "Sant'Elena", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 1764)
Comune.create(description: "Sant'Urbano", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 2253)
Comune.create(description: "Vighizzolo D'Este", province_id: 67, region_id:  17, country_id: 1, continent_id: 1 , population: 928)
