#encoding: utf-8
Comune.create(:description => "Altino", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 2536)
Comune.create(:description => "Archi", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 2336)
Comune.create(:description => "Ari", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1328)
Comune.create(:description => "Arielli", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1250)
Comune.create(:description => "Atessa", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 10388)
Comune.create(:description => "Bomba", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 972)
Comune.create(:description => "Borrello", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 444)
Comune.create(:description => "Bucchianico", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 4941)
Comune.create(:description => "Canosa Sannita", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1510)
Comune.create(:description => "Carpineto Sinello", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 746)
Comune.create(:description => "Carunchio", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 781)
Comune.create(:description => "Casacanditella", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1397)
Comune.create(:description => "Casalanguida", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1096)
Comune.create(:description => "Casalbordino", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 6478)
Comune.create(:description => "Casalincontrada", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 2942)
Comune.create(:description => "Casoli", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 5971)
Comune.create(:description => "Castel Frentano", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 3913)
Comune.create(:description => "Castelguidone", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 482)
Comune.create(:description => "Castiglione Messer Marino", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 2225)
Comune.create(:description => "Celenza Sul Trigno", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1098)
Comune.create(:description => "Chieti", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 52486)
Comune.create(:description => "Civitaluparella", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 429)
Comune.create(:description => "Civitella Messer Raimondo", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 972)
Comune.create(:description => "Colledimacine", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 286)
Comune.create(:description => "Colledimezzo", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 592)
Comune.create(:description => "Crecchio", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 3052)
Comune.create(:description => "Cupello", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 4415)
Comune.create(:description => "Dogliola", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 415)
Comune.create(:description => "Fallo", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 162)
Comune.create(:description => "Fara Filiorum Petri", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1952)
Comune.create(:description => "Fara San Martino", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1626)
Comune.create(:description => "Filetto", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1119)
Comune.create(:description => "Fossacesia", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 5349)
Comune.create(:description => "Fraine", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 463)
Comune.create(:description => "Francavilla Al Mare", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 22883)
Comune.create(:description => "Fresagrandinaria", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1088)
Comune.create(:description => "Frisa", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1940)
Comune.create(:description => "Furci", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1275)
Comune.create(:description => "Gamberale", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 394)
Comune.create(:description => "Gessopalena", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1694)
Comune.create(:description => "Gissi", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 3088)
Comune.create(:description => "Giuliano Teatino", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1306)
Comune.create(:description => "Guardiagrele", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 9527)
Comune.create(:description => "Guilmi", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 520)
Comune.create(:description => "Lama Dei Peligni", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1486)
Comune.create(:description => "Lanciano", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 35798)
Comune.create(:description => "Lentella", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 768)
Comune.create(:description => "Lettopalena", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 409)
Comune.create(:description => "Liscia", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 813)
Comune.create(:description => "Miglianico", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 4503)
Comune.create(:description => "Montazzoli", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1116)
Comune.create(:description => "Montebello Sul Sangro", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 125)
Comune.create(:description => "Monteferrante", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 190)
Comune.create(:description => "Montelapiano", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 107)
Comune.create(:description => "Montenerodomo", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 936)
Comune.create(:description => "Monteodorisio", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 2402)
Comune.create(:description => "Mozzagrogna", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 2060)
Comune.create(:description => "Orsogna", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 4050)
Comune.create(:description => "Ortona", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 22694)
Comune.create(:description => "Paglieta", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 4401)
Comune.create(:description => "Palena", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1478)
Comune.create(:description => "Palmoli", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1162)
Comune.create(:description => "Palombaro", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1177)
Comune.create(:description => "Pennadomo", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 358)
Comune.create(:description => "Pennapiedimonte", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 556)
Comune.create(:description => "Perano", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1656)
Comune.create(:description => "Pietraferrazzana", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 152)
Comune.create(:description => "Pizzoferrato", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1189)
Comune.create(:description => "Poggiofiorito", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 951)
Comune.create(:description => "Pollutri", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 2345)
Comune.create(:description => "Pretoro", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1107)
Comune.create(:description => "Quadri", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 943)
Comune.create(:description => "Rapino", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1433)
Comune.create(:description => "Ripa Teatina", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 3834)
Comune.create(:description => "Rocca San Giovanni", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 2352)
Comune.create(:description => "Roccamontepiano", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1965)
Comune.create(:description => "Roccascalegna", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1423)
Comune.create(:description => "Roccaspinalveti", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1671)
Comune.create(:description => "Roio Del Sangro", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 159)
Comune.create(:description => "Rosello", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 342)
Comune.create(:description => "San Buono", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1202)
Comune.create(:description => "San Giovanni Lipioni", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 287)
Comune.create(:description => "San Giovanni Teatino", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 10048)
Comune.create(:description => "San Martino Sulla Marrucina", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 981)
Comune.create(:description => "San Salvo", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 17254)
Comune.create(:description => "San Vito Chietino", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 4901)
Comune.create(:description => "Santa Maria Imbaro", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1735)
Comune.create(:description => "Scerni", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 3704)
Comune.create(:description => "Schiavi Di Abruzzo", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1403)
Comune.create(:description => "Taranta Peligna", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 521)
Comune.create(:description => "Tollo", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 4171)
Comune.create(:description => "Torino Di Sangro", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 3079)
Comune.create(:description => "Tornareccio", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1948)
Comune.create(:description => "Torrebruna", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1173)
Comune.create(:description => "Torrevecchia Teatina", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 3746)
Comune.create(:description => "Torricella Peligna", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1587)
Comune.create(:description => "Treglio", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1236)
Comune.create(:description => "Tufillo", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 564)
Comune.create(:description => "Vacri", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1756)
Comune.create(:description => "Vasto", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 35362)
Comune.create(:description => "Villa Santa Maria", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1479)
Comune.create(:description => "Villalfonsina", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1062)
Comune.create(:description => "Villamagna", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 2448)
Comune.create(:description => "Sant'Eusanio Del Sangro", :provincia_id => 44, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 2451)
