Comune.create(description: "Adria", provincia_id: 68, regione_id: 17, country_id: 1, continent_id: 1 , population: 20640)
Comune.create(description: "Ariano Nel Polesine", provincia_id: 68, regione_id: 17, country_id: 1, continent_id: 1 , population: 4882)
Comune.create(description: "Badia Polesine", provincia_id: 68, regione_id: 17, country_id: 1, continent_id: 1 , population: 10431)
Comune.create(description: "Bagnolo Di Po", provincia_id: 68, regione_id: 17, country_id: 1, continent_id: 1 , population: 1409)
Comune.create(description: "Bergantino", provincia_id: 68, regione_id: 17, country_id: 1, continent_id: 1 , population: 2627)
Comune.create(description: "Bosaro", provincia_id: 68, regione_id: 17, country_id: 1, continent_id: 1 , population: 1316)
Comune.create(description: "Calto", provincia_id: 68, regione_id: 17, country_id: 1, continent_id: 1 , population: 865)
Comune.create(description: "Canaro", provincia_id: 68, regione_id: 17, country_id: 1, continent_id: 1 , population: 2838)
Comune.create(description: "Canda", provincia_id: 68, regione_id: 17, country_id: 1, continent_id: 1 , population: 936)
Comune.create(description: "Castelguglielmo", provincia_id: 68, regione_id: 17, country_id: 1, continent_id: 1 , population: 1763)
Comune.create(description: "Castelmassa", provincia_id: 68, regione_id: 17, country_id: 1, continent_id: 1 , population: 4312)
Comune.create(description: "Castelnovo Bariano", provincia_id: 68, regione_id: 17, country_id: 1, continent_id: 1 , population: 3052)
Comune.create(description: "Ceneselli", provincia_id: 68, regione_id: 17, country_id: 1, continent_id: 1 , population: 1871)
Comune.create(description: "Ceregnano", provincia_id: 68, regione_id: 17, country_id: 1, continent_id: 1 , population: 3942)
Comune.create(description: "Corbola", provincia_id: 68, regione_id: 17, country_id: 1, continent_id: 1 , population: 2645)
Comune.create(description: "Costa Di Rovigo", provincia_id: 68, regione_id: 17, country_id: 1, continent_id: 1 , population: 2956)
Comune.create(description: "Crespino", provincia_id: 68, regione_id: 17, country_id: 1, continent_id: 1 , population: 2097)
Comune.create(description: "Ficarolo", provincia_id: 68, regione_id: 17, country_id: 1, continent_id: 1 , population: 2764)
Comune.create(description: "Fiesso Umbertiano", provincia_id: 68, regione_id: 17, country_id: 1, continent_id: 1 , population: 4177)
Comune.create(description: "Frassinelle Polesine", provincia_id: 68, regione_id: 17, country_id: 1, continent_id: 1 , population: 1626)
Comune.create(description: "Fratta Polesine", provincia_id: 68, regione_id: 17, country_id: 1, continent_id: 1 , population: 2746)
Comune.create(description: "Gaiba", provincia_id: 68, regione_id: 17, country_id: 1, continent_id: 1 , population: 1136)
Comune.create(description: "Gavello", provincia_id: 68, regione_id: 17, country_id: 1, continent_id: 1 , population: 1641)
Comune.create(description: "Giacciano Con Baruchella", provincia_id: 68, regione_id: 17, country_id: 1, continent_id: 1 , population: 2255)
Comune.create(description: "Guarda Veneta", provincia_id: 68, regione_id: 17, country_id: 1, continent_id: 1 , population: 1153)
Comune.create(description: "Lendinara", provincia_id: 68, regione_id: 17, country_id: 1, continent_id: 1 , population: 12173)
Comune.create(description: "Loreo", provincia_id: 68, regione_id: 17, country_id: 1, continent_id: 1 , population: 3718)
Comune.create(description: "Lusia", provincia_id: 68, regione_id: 17, country_id: 1, continent_id: 1 , population: 3587)
Comune.create(description: "Melara", provincia_id: 68, regione_id: 17, country_id: 1, continent_id: 1 , population: 1927)
Comune.create(description: "Occhiobello", provincia_id: 68, regione_id: 17, country_id: 1, continent_id: 1 , population: 9979)
Comune.create(description: "Papozze", provincia_id: 68, regione_id: 17, country_id: 1, continent_id: 1 , population: 1743)
Comune.create(description: "Pettorazza Grimani", provincia_id: 68, regione_id: 17, country_id: 1, continent_id: 1 , population: 1719)
Comune.create(description: "Pincara", provincia_id: 68, regione_id: 17, country_id: 1, continent_id: 1 , population: 1277)
Comune.create(description: "Polesella", provincia_id: 68, regione_id: 17, country_id: 1, continent_id: 1 , population: 3951)
Comune.create(description: "Pontecchio Polesine", provincia_id: 68, regione_id: 17, country_id: 1, continent_id: 1 , population: 1516)
Comune.create(description: "Porto Tolle", provincia_id: 68, regione_id: 17, country_id: 1, continent_id: 1 , population: 10666)
Comune.create(description: "Porto Viro", provincia_id: 68, regione_id: 17, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Rosolina", provincia_id: 68, regione_id: 17, country_id: 1, continent_id: 1 , population: 6144)
Comune.create(description: "Rovigo", provincia_id: 68, regione_id: 17, country_id: 1, continent_id: 1 , population: 50289)
Comune.create(description: "Salara", provincia_id: 68, regione_id: 17, country_id: 1, continent_id: 1 , population: 1265)
Comune.create(description: "San Bellino", provincia_id: 68, regione_id: 17, country_id: 1, continent_id: 1 , population: 1197)
Comune.create(description: "San Martino Di Venezze", provincia_id: 68, regione_id: 17, country_id: 1, continent_id: 1 , population: 3877)
Comune.create(description: "Stienta", provincia_id: 68, regione_id: 17, country_id: 1, continent_id: 1 , population: 3010)
Comune.create(description: "Taglio Di Po", provincia_id: 68, regione_id: 17, country_id: 1, continent_id: 1 , population: 8284)
Comune.create(description: "Trecenta", provincia_id: 68, regione_id: 17, country_id: 1, continent_id: 1 , population: 3146)
Comune.create(description: "Villadose", provincia_id: 68, regione_id: 17, country_id: 1, continent_id: 1 , population: 5248)
Comune.create(description: "Villamarzana", provincia_id: 68, regione_id: 17, country_id: 1, continent_id: 1 , population: 1213)
Comune.create(description: "Villanova Del Ghebbo", provincia_id: 68, regione_id: 17, country_id: 1, continent_id: 1 , population: 2196)
Comune.create(description: "Villanova Marchesana", provincia_id: 68, regione_id: 17, country_id: 1, continent_id: 1 , population: 1038)
Comune.create(description: "Arqua' Polesine", provincia_id: 68, regione_id: 17, country_id: 1, continent_id: 1 , population: 2896)
