Municipality.create(description: "Adria", province_id: 68, region_id:  17, country_id: 1, continent_id: 1 , population: 20640)
Municipality.create(description: "Ariano Nel Polesine", province_id: 68, region_id:  17, country_id: 1, continent_id: 1 , population: 4882)
Municipality.create(description: "Badia Polesine", province_id: 68, region_id:  17, country_id: 1, continent_id: 1 , population: 10431)
Municipality.create(description: "Bagnolo Di Po", province_id: 68, region_id:  17, country_id: 1, continent_id: 1 , population: 1409)
Municipality.create(description: "Bergantino", province_id: 68, region_id:  17, country_id: 1, continent_id: 1 , population: 2627)
Municipality.create(description: "Bosaro", province_id: 68, region_id:  17, country_id: 1, continent_id: 1 , population: 1316)
Municipality.create(description: "Calto", province_id: 68, region_id:  17, country_id: 1, continent_id: 1 , population: 865)
Municipality.create(description: "Canaro", province_id: 68, region_id:  17, country_id: 1, continent_id: 1 , population: 2838)
Municipality.create(description: "Canda", province_id: 68, region_id:  17, country_id: 1, continent_id: 1 , population: 936)
Municipality.create(description: "Castelguglielmo", province_id: 68, region_id:  17, country_id: 1, continent_id: 1 , population: 1763)
Municipality.create(description: "Castelmassa", province_id: 68, region_id:  17, country_id: 1, continent_id: 1 , population: 4312)
Municipality.create(description: "Castelnovo Bariano", province_id: 68, region_id:  17, country_id: 1, continent_id: 1 , population: 3052)
Municipality.create(description: "Ceneselli", province_id: 68, region_id:  17, country_id: 1, continent_id: 1 , population: 1871)
Municipality.create(description: "Ceregnano", province_id: 68, region_id:  17, country_id: 1, continent_id: 1 , population: 3942)
Municipality.create(description: "Corbola", province_id: 68, region_id:  17, country_id: 1, continent_id: 1 , population: 2645)
Municipality.create(description: "Costa Di Rovigo", province_id: 68, region_id:  17, country_id: 1, continent_id: 1 , population: 2956)
Municipality.create(description: "Crespino", province_id: 68, region_id:  17, country_id: 1, continent_id: 1 , population: 2097)
Municipality.create(description: "Ficarolo", province_id: 68, region_id:  17, country_id: 1, continent_id: 1 , population: 2764)
Municipality.create(description: "Fiesso Umbertiano", province_id: 68, region_id:  17, country_id: 1, continent_id: 1 , population: 4177)
Municipality.create(description: "Frassinelle Polesine", province_id: 68, region_id:  17, country_id: 1, continent_id: 1 , population: 1626)
Municipality.create(description: "Fratta Polesine", province_id: 68, region_id:  17, country_id: 1, continent_id: 1 , population: 2746)
Municipality.create(description: "Gaiba", province_id: 68, region_id:  17, country_id: 1, continent_id: 1 , population: 1136)
Municipality.create(description: "Gavello", province_id: 68, region_id:  17, country_id: 1, continent_id: 1 , population: 1641)
Municipality.create(description: "Giacciano Con Baruchella", province_id: 68, region_id:  17, country_id: 1, continent_id: 1 , population: 2255)
Municipality.create(description: "Guarda Veneta", province_id: 68, region_id:  17, country_id: 1, continent_id: 1 , population: 1153)
Municipality.create(description: "Lendinara", province_id: 68, region_id:  17, country_id: 1, continent_id: 1 , population: 12173)
Municipality.create(description: "Loreo", province_id: 68, region_id:  17, country_id: 1, continent_id: 1 , population: 3718)
Municipality.create(description: "Lusia", province_id: 68, region_id:  17, country_id: 1, continent_id: 1 , population: 3587)
Municipality.create(description: "Melara", province_id: 68, region_id:  17, country_id: 1, continent_id: 1 , population: 1927)
Municipality.create(description: "Occhiobello", province_id: 68, region_id:  17, country_id: 1, continent_id: 1 , population: 9979)
Municipality.create(description: "Papozze", province_id: 68, region_id:  17, country_id: 1, continent_id: 1 , population: 1743)
Municipality.create(description: "Pettorazza Grimani", province_id: 68, region_id:  17, country_id: 1, continent_id: 1 , population: 1719)
Municipality.create(description: "Pincara", province_id: 68, region_id:  17, country_id: 1, continent_id: 1 , population: 1277)
Municipality.create(description: "Polesella", province_id: 68, region_id:  17, country_id: 1, continent_id: 1 , population: 3951)
Municipality.create(description: "Pontecchio Polesine", province_id: 68, region_id:  17, country_id: 1, continent_id: 1 , population: 1516)
Municipality.create(description: "Porto Tolle", province_id: 68, region_id:  17, country_id: 1, continent_id: 1 , population: 10666)
Municipality.create(description: "Porto Viro", province_id: 68, region_id:  17, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Rosolina", province_id: 68, region_id:  17, country_id: 1, continent_id: 1 , population: 6144)
Municipality.create(description: "Rovigo", province_id: 68, region_id:  17, country_id: 1, continent_id: 1 , population: 50289)
Municipality.create(description: "Salara", province_id: 68, region_id:  17, country_id: 1, continent_id: 1 , population: 1265)
Municipality.create(description: "San Bellino", province_id: 68, region_id:  17, country_id: 1, continent_id: 1 , population: 1197)
Municipality.create(description: "San Martino Di Venezze", province_id: 68, region_id:  17, country_id: 1, continent_id: 1 , population: 3877)
Municipality.create(description: "Stienta", province_id: 68, region_id:  17, country_id: 1, continent_id: 1 , population: 3010)
Municipality.create(description: "Taglio Di Po", province_id: 68, region_id:  17, country_id: 1, continent_id: 1 , population: 8284)
Municipality.create(description: "Trecenta", province_id: 68, region_id:  17, country_id: 1, continent_id: 1 , population: 3146)
Municipality.create(description: "Villadose", province_id: 68, region_id:  17, country_id: 1, continent_id: 1 , population: 5248)
Municipality.create(description: "Villamarzana", province_id: 68, region_id:  17, country_id: 1, continent_id: 1 , population: 1213)
Municipality.create(description: "Villanova Del Ghebbo", province_id: 68, region_id:  17, country_id: 1, continent_id: 1 , population: 2196)
Municipality.create(description: "Villanova Marchesana", province_id: 68, region_id:  17, country_id: 1, continent_id: 1 , population: 1038)
Municipality.create(description: "Arqua' Polesine", province_id: 68, region_id:  17, country_id: 1, continent_id: 1 , population: 2896)
