Municipality.create(description: "Altivole", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 6122)
Municipality.create(description: "Arcade", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 3440)
Municipality.create(description: "Asolo", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 7605)
Municipality.create(description: "Borso Del Grappa", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 4935)
Municipality.create(description: "Breda Di Piave", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 6348)
Municipality.create(description: "Caerano Di San Marco", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 7027)
Municipality.create(description: "Cappella Maggiore", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 4412)
Municipality.create(description: "Carbonera", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 9804)
Municipality.create(description: "Casale Sul Sile", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 9461)
Municipality.create(description: "Casier", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 8935)
Municipality.create(description: "Castelcucco", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 1871)
Municipality.create(description: "Castelfranco Veneto", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 31486)
Municipality.create(description: "Castello Di Godego", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 6347)
Municipality.create(description: "Cavaso Del Tomba", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 2675)
Municipality.create(description: "Cessalto", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 3134)
Municipality.create(description: "Chiarano", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 3114)
Municipality.create(description: "Cimadolmo", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 3327)
Municipality.create(description: "Cison Di Valmarino", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 2553)
Municipality.create(description: "Colle Umberto", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 4572)
Municipality.create(description: "Conegliano", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 35100)
Municipality.create(description: "Cordignano", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 6374)
Municipality.create(description: "Cornuda", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 5730)
Municipality.create(description: "Crespano Del Grappa", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 4328)
Municipality.create(description: "Crocetta Del Montello", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 5709)
Municipality.create(description: "Farra Di Soligo", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 7892)
Municipality.create(description: "Follina", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 3646)
Municipality.create(description: "Fontanelle", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 5471)
Municipality.create(description: "Fonte", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 5479)
Municipality.create(description: "Fregona", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 2927)
Municipality.create(description: "Gaiarine", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 6161)
Municipality.create(description: "Giavera Del Montello", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 4318)
Municipality.create(description: "Gorgo Al Monticano", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 3977)
Municipality.create(description: "Istrana", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 7763)
Municipality.create(description: "Loria", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 7764)
Municipality.create(description: "Mareno Di Piave", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 7870)
Municipality.create(description: "Maser", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 4846)
Municipality.create(description: "Maserada Sul Piave", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 7575)
Municipality.create(description: "Meduna Di Livenza", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 2702)
Municipality.create(description: "Miane", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 3416)
Municipality.create(description: "Mogliano Veneto", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 26322)
Municipality.create(description: "Monastier Di Treviso", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 3554)
Municipality.create(description: "Monfumo", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 1428)
Municipality.create(description: "Montebelluna", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 27539)
Municipality.create(description: "Morgano", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 3754)
Municipality.create(description: "Moriago Della Battaglia", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 2627)
Municipality.create(description: "Motta Di Livenza", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 9657)
Municipality.create(description: "Nervesa Della Battaglia", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 6653)
Municipality.create(description: "Oderzo", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 17316)
Municipality.create(description: "Ormelle", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 4087)
Municipality.create(description: "Orsago", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 3598)
Municipality.create(description: "Paderno Del Grappa", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 2002)
Municipality.create(description: "Paese", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 18407)
Municipality.create(description: "Pederobba", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 7061)
Municipality.create(description: "Pieve Di Soligo", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 10673)
Municipality.create(description: "Ponte Di Piave", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 7128)
Municipality.create(description: "Ponzano Veneto", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 9783)
Municipality.create(description: "Possagno", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 2029)
Municipality.create(description: "Povegliano", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 4109)
Municipality.create(description: "Preganziol", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 14706)
Municipality.create(description: "Quinto Di Treviso", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 9288)
Municipality.create(description: "Refrontolo", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 1805)
Municipality.create(description: "Resana", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 7491)
Municipality.create(description: "Revine Lago", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 2119)
Municipality.create(description: "Riese Pio X", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 9627)
Municipality.create(description: "Roncade", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 11911)
Municipality.create(description: "Salgareda", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 5574)
Municipality.create(description: "San Biagio Di Callalta", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 11439)
Municipality.create(description: "San Fior", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 6153)
Municipality.create(description: "San Pietro Di Feletto", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 4890)
Municipality.create(description: "San Polo Di Piave", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 4536)
Municipality.create(description: "San Vendemiano", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 8776)
Municipality.create(description: "San Zenone Degli Ezzelini", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 6506)
Municipality.create(description: "Santa Lucia Di Piave", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 7226)
Municipality.create(description: "Sarmede", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 3004)
Municipality.create(description: "Segusino", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 1980)
Municipality.create(description: "Sernaglia Della Battaglia", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 5799)
Municipality.create(description: "Silea", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 9114)
Municipality.create(description: "Spresiano", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 9251)
Municipality.create(description: "Susegana", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 10754)
Municipality.create(description: "Tarzo", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 4537)
Municipality.create(description: "Trevignano", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 9074)
Municipality.create(description: "Treviso", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 80144)
Municipality.create(description: "Valdobbiadene", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 10624)
Municipality.create(description: "Vazzola", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 6405)
Municipality.create(description: "Vedelago", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 13826)
Municipality.create(description: "Vidor", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 3405)
Municipality.create(description: "Villorba", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 16921)
Municipality.create(description: "Vittorio Veneto", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 29184)
Municipality.create(description: "Volpago Del Montello", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 9084)
Municipality.create(description: "Zenson Di Piave", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 1694)
Municipality.create(description: "Zero Branco", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 8581)
Municipality.create(description: "Codogne'", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 5068)
Municipality.create(description: "Godega Di Sant'Urbano", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 5954)
Municipality.create(description: "Mansue'", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 4132)
Municipality.create(description: "Portobuffole'", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 739)
