Comune.create(description: "Altivole", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 6122)
Comune.create(description: "Arcade", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 3440)
Comune.create(description: "Asolo", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 7605)
Comune.create(description: "Borso Del Grappa", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 4935)
Comune.create(description: "Breda Di Piave", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 6348)
Comune.create(description: "Caerano Di San Marco", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 7027)
Comune.create(description: "Cappella Maggiore", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 4412)
Comune.create(description: "Carbonera", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 9804)
Comune.create(description: "Casale Sul Sile", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 9461)
Comune.create(description: "Casier", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 8935)
Comune.create(description: "Castelcucco", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 1871)
Comune.create(description: "Castelfranco Veneto", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 31486)
Comune.create(description: "Castello Di Godego", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 6347)
Comune.create(description: "Cavaso Del Tomba", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 2675)
Comune.create(description: "Cessalto", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 3134)
Comune.create(description: "Chiarano", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 3114)
Comune.create(description: "Cimadolmo", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 3327)
Comune.create(description: "Cison Di Valmarino", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 2553)
Comune.create(description: "Colle Umberto", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 4572)
Comune.create(description: "Conegliano", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 35100)
Comune.create(description: "Cordignano", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 6374)
Comune.create(description: "Cornuda", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 5730)
Comune.create(description: "Crespano Del Grappa", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 4328)
Comune.create(description: "Crocetta Del Montello", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 5709)
Comune.create(description: "Farra Di Soligo", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 7892)
Comune.create(description: "Follina", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 3646)
Comune.create(description: "Fontanelle", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 5471)
Comune.create(description: "Fonte", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 5479)
Comune.create(description: "Fregona", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 2927)
Comune.create(description: "Gaiarine", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 6161)
Comune.create(description: "Giavera Del Montello", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 4318)
Comune.create(description: "Gorgo Al Monticano", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 3977)
Comune.create(description: "Istrana", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 7763)
Comune.create(description: "Loria", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 7764)
Comune.create(description: "Mareno Di Piave", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 7870)
Comune.create(description: "Maser", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 4846)
Comune.create(description: "Maserada Sul Piave", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 7575)
Comune.create(description: "Meduna Di Livenza", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 2702)
Comune.create(description: "Miane", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 3416)
Comune.create(description: "Mogliano Veneto", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 26322)
Comune.create(description: "Monastier Di Treviso", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 3554)
Comune.create(description: "Monfumo", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 1428)
Comune.create(description: "Montebelluna", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 27539)
Comune.create(description: "Morgano", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 3754)
Comune.create(description: "Moriago Della Battaglia", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 2627)
Comune.create(description: "Motta Di Livenza", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 9657)
Comune.create(description: "Nervesa Della Battaglia", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 6653)
Comune.create(description: "Oderzo", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 17316)
Comune.create(description: "Ormelle", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 4087)
Comune.create(description: "Orsago", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 3598)
Comune.create(description: "Paderno Del Grappa", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 2002)
Comune.create(description: "Paese", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 18407)
Comune.create(description: "Pederobba", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 7061)
Comune.create(description: "Pieve Di Soligo", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 10673)
Comune.create(description: "Ponte Di Piave", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 7128)
Comune.create(description: "Ponzano Veneto", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 9783)
Comune.create(description: "Possagno", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 2029)
Comune.create(description: "Povegliano", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 4109)
Comune.create(description: "Preganziol", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 14706)
Comune.create(description: "Quinto Di Treviso", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 9288)
Comune.create(description: "Refrontolo", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 1805)
Comune.create(description: "Resana", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 7491)
Comune.create(description: "Revine Lago", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 2119)
Comune.create(description: "Riese Pio X", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 9627)
Comune.create(description: "Roncade", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 11911)
Comune.create(description: "Salgareda", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 5574)
Comune.create(description: "San Biagio Di Callalta", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 11439)
Comune.create(description: "San Fior", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 6153)
Comune.create(description: "San Pietro Di Feletto", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 4890)
Comune.create(description: "San Polo Di Piave", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 4536)
Comune.create(description: "San Vendemiano", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 8776)
Comune.create(description: "San Zenone Degli Ezzelini", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 6506)
Comune.create(description: "Santa Lucia Di Piave", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 7226)
Comune.create(description: "Sarmede", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 3004)
Comune.create(description: "Segusino", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 1980)
Comune.create(description: "Sernaglia Della Battaglia", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 5799)
Comune.create(description: "Silea", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 9114)
Comune.create(description: "Spresiano", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 9251)
Comune.create(description: "Susegana", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 10754)
Comune.create(description: "Tarzo", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 4537)
Comune.create(description: "Trevignano", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 9074)
Comune.create(description: "Treviso", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 80144)
Comune.create(description: "Valdobbiadene", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 10624)
Comune.create(description: "Vazzola", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 6405)
Comune.create(description: "Vedelago", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 13826)
Comune.create(description: "Vidor", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 3405)
Comune.create(description: "Villorba", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 16921)
Comune.create(description: "Vittorio Veneto", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 29184)
Comune.create(description: "Volpago Del Montello", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 9084)
Comune.create(description: "Zenson Di Piave", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 1694)
Comune.create(description: "Zero Branco", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 8581)
Comune.create(description: "Codogne'", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 5068)
Comune.create(description: "Godega Di Sant'Urbano", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 5954)
Comune.create(description: "Mansue'", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 4132)
Comune.create(description: "Portobuffole'", province_id: 69, region_id:  17, country_id: 1, continent_id: 1 , population: 739)
