Comune.create(description: "Annone Veneto", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 3490)
Comune.create(description: "Campagna Lupia", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 6288)
Comune.create(description: "Campolongo Maggiore", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 9196)
Comune.create(description: "Camponogara", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 10905)
Comune.create(description: "Caorle", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 11342)
Comune.create(description: "Cavallino-Treporti", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 11824)
Comune.create(description: "Cavarzere", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 15504)
Comune.create(description: "Ceggia", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 5096)
Comune.create(description: "Chioggia", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 51779)
Comune.create(description: "Cinto Caomaggiore", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 3168)
Comune.create(description: "Cona", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 3253)
Comune.create(description: "Concordia Sagittaria", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 10492)
Comune.create(description: "Dolo", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 14442)
Comune.create(description: "Eraclea", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 12460)
Comune.create(description: "Fossalta Di Piave", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 4022)
Comune.create(description: "Fossalta Di Portogruaro", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 5843)
Comune.create(description: "Gruaro", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 2690)
Comune.create(description: "Jesolo", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 22698)
Comune.create(description: "Marcon", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 12199)
Comune.create(description: "Martellago", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 19476)
Comune.create(description: "Meolo", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 6054)
Comune.create(description: "Mira", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 35355)
Comune.create(description: "Mirano", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 26206)
Comune.create(description: "Musile Di Piave", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 10249)
Comune.create(description: "Noale", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 14790)
Comune.create(description: "Noventa Di Piave", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 5952)
Comune.create(description: "Pianiga", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 9168)
Comune.create(description: "Portogruaro", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 24571)
Comune.create(description: "Pramaggiore", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 3985)
Comune.create(description: "Salzano", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 11593)
Comune.create(description: "San Michele Al Tagliamento", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 11441)
Comune.create(description: "Santa Maria Di Sala", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 13685)
Comune.create(description: "Santo Stino Di Livenza", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 11763)
Comune.create(description: "Spinea", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 24517)
Comune.create(description: "Stra", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 7031)
Comune.create(description: "Teglio Veneto", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 1979)
Comune.create(description: "Torre Di Mosto", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 4302)
Comune.create(description: "Venezia", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 271073)
Comune.create(description: "Vigonovo", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 8064)
Comune.create(description: "Fiesso D'Artico", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 5779)
Comune.create(description: "Fosso'", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 5922)
Comune.create(description: "Quarto D'Altino", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 7228)
Comune.create(description: "San Dona' Di Piave", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 35417)
Comune.create(description: "Scorze'", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 17295)
