Municipality.create(description: "Annone Veneto", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 3490)
Municipality.create(description: "Campagna Lupia", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 6288)
Municipality.create(description: "Campolongo Maggiore", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 9196)
Municipality.create(description: "Camponogara", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 10905)
Municipality.create(description: "Caorle", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 11342)
Municipality.create(description: "Cavallino-Treporti", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 11824)
Municipality.create(description: "Cavarzere", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 15504)
Municipality.create(description: "Ceggia", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 5096)
Municipality.create(description: "Chioggia", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 51779)
Municipality.create(description: "Cinto Caomaggiore", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 3168)
Municipality.create(description: "Cona", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 3253)
Municipality.create(description: "Concordia Sagittaria", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 10492)
Municipality.create(description: "Dolo", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 14442)
Municipality.create(description: "Eraclea", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 12460)
Municipality.create(description: "Fossalta Di Piave", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 4022)
Municipality.create(description: "Fossalta Di Portogruaro", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 5843)
Municipality.create(description: "Gruaro", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 2690)
Municipality.create(description: "Jesolo", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 22698)
Municipality.create(description: "Marcon", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 12199)
Municipality.create(description: "Martellago", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 19476)
Municipality.create(description: "Meolo", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 6054)
Municipality.create(description: "Mira", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 35355)
Municipality.create(description: "Mirano", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 26206)
Municipality.create(description: "Musile Di Piave", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 10249)
Municipality.create(description: "Noale", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 14790)
Municipality.create(description: "Noventa Di Piave", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 5952)
Municipality.create(description: "Pianiga", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 9168)
Municipality.create(description: "Portogruaro", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 24571)
Municipality.create(description: "Pramaggiore", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 3985)
Municipality.create(description: "Salzano", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 11593)
Municipality.create(description: "San Michele Al Tagliamento", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 11441)
Municipality.create(description: "Santa Maria Di Sala", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 13685)
Municipality.create(description: "Santo Stino Di Livenza", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 11763)
Municipality.create(description: "Spinea", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 24517)
Municipality.create(description: "Stra", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 7031)
Municipality.create(description: "Teglio Veneto", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 1979)
Municipality.create(description: "Torre Di Mosto", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 4302)
Municipality.create(description: "Venezia", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 271073)
Municipality.create(description: "Vigonovo", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 8064)
Municipality.create(description: "Fiesso D'Artico", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 5779)
Municipality.create(description: "Fosso'", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 5922)
Municipality.create(description: "Quarto D'Altino", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 7228)
Municipality.create(description: "San Dona' Di Piave", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 35417)
Municipality.create(description: "Scorze'", province_id: 70, region_id:  17, country_id: 1, continent_id: 1 , population: 17295)
