Comune.create(description: "Affi", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 1942)
Comune.create(description: "Angiari", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 1844)
Comune.create(description: "Arcole", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 5274)
Comune.create(description: "Badia Calavena", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 2373)
Comune.create(description: "Bardolino", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 6329)
Comune.create(description: "Belfiore", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 2645)
Comune.create(description: "Bevilacqua", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 1691)
Comune.create(description: "Bonavigo", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 1881)
Comune.create(description: "Bosco Chiesanuova", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 3203)
Comune.create(description: "Bovolone", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 13426)
Comune.create(description: "Brentino Belluno", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 1301)
Comune.create(description: "Brenzone", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 2358)
Comune.create(description: "Bussolengo", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 16986)
Comune.create(description: "Buttapietra", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 5801)
Comune.create(description: "Caldiero", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 5655)
Comune.create(description: "Caprino Veronese", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 7493)
Comune.create(description: "Casaleone", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 5929)
Comune.create(description: "Castagnaro", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 4151)
Comune.create(description: "Castelnuovo Del Garda", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 8612)
Comune.create(description: "Cavaion Veronese", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 4164)
Comune.create(description: "Cazzano Di Tramigna", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 1302)
Comune.create(description: "Cerea", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 15254)
Comune.create(description: "Cerro Veronese", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 2043)
Comune.create(description: "Cologna Veneta", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 7890)
Comune.create(description: "Colognola Ai Colli", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 6913)
Comune.create(description: "Concamarise", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 1064)
Comune.create(description: "Costermano", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 2986)
Comune.create(description: "Erbezzo", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 775)
Comune.create(description: "Ferrara Di Monte Baldo", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 188)
Comune.create(description: "Fumane", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 3816)
Comune.create(description: "Garda", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 3594)
Comune.create(description: "Gazzo Veronese", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 5515)
Comune.create(description: "Grezzana", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 10045)
Comune.create(description: "Illasi", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 4884)
Comune.create(description: "Isola Della Scala", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 10502)
Comune.create(description: "Isola Rizza", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 2859)
Comune.create(description: "Lavagno", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 5964)
Comune.create(description: "Lazise", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 6055)
Comune.create(description: "Legnago", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 24274)
Comune.create(description: "Malcesine", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 3417)
Comune.create(description: "Marano Di Valpolicella", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 2897)
Comune.create(description: "Mezzane Di Sotto", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 1880)
Comune.create(description: "Minerbe", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 4588)
Comune.create(description: "Montecchia Di Crosara", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 4195)
Comune.create(description: "Mozzecane", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 4949)
Comune.create(description: "Negrar", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 16184)
Comune.create(description: "Nogara", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 7899)
Comune.create(description: "Nogarole Rocca", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 2850)
Comune.create(description: "Oppeano", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 7514)
Comune.create(description: "Pastrengo", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 2362)
Comune.create(description: "Pescantina", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 12414)
Comune.create(description: "Peschiera Del Garda", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 8485)
Comune.create(description: "Povegliano Veronese", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 6567)
Comune.create(description: "Pressana", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 2445)
Comune.create(description: "Rivoli Veronese", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 1980)
Comune.create(description: "Roverchiara", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 2655)
Comune.create(description: "Salizzole", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 3761)
Comune.create(description: "San Bonifacio", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 17513)
Comune.create(description: "San Giovanni Ilarione", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 4889)
Comune.create(description: "San Giovanni Lupatoto", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 21298)
Comune.create(description: "San Martino Buon Albergo", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 13095)
Comune.create(description: "San Mauro Di Saline", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 568)
Comune.create(description: "San Pietro Di Morubio", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 2848)
Comune.create(description: "San Pietro In Cariano", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 12484)
Comune.create(description: "San Zeno Di Montagna", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 1243)
Comune.create(description: "Sanguinetto", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 3998)
Comune.create(description: "Selva Di Progno", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 1001)
Comune.create(description: "Soave", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 6562)
Comune.create(description: "Sommacampagna", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 13001)
Comune.create(description: "Sona", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 14275)
Comune.create(description: "Terrazzo", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 2385)
Comune.create(description: "Torri Del Benaco", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 2626)
Comune.create(description: "Tregnago", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 4896)
Comune.create(description: "Trevenzuolo", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 2424)
Comune.create(description: "Valeggio Sul Mincio", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 10941)
Comune.create(description: "Velo Veronese", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 798)
Comune.create(description: "Verona", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 253208)
Comune.create(description: "Veronella", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 3696)
Comune.create(description: "Vestenanova", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 2614)
Comune.create(description: "Vigasio", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 6798)
Comune.create(description: "Villa Bartolomea", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 5368)
Comune.create(description: "Villafranca Di Verona", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 29353)
Comune.create(description: "Zevio", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 12035)
Comune.create(description: "Zimella", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 4342)
Comune.create(description: "Albaredo D'Adige", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 5032)
Comune.create(description: "Boschi Sant'Anna", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 1347)
Comune.create(description: "Castel D'Azzano", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 10242)
Comune.create(description: "Dolce'", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 2200)
Comune.create(description: "Erbe'", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 1629)
Comune.create(description: "Monteforte D'Alpone", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 7065)
Comune.create(description: "Palu'", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 1124)
Comune.create(description: "Ronca'", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 3385)
Comune.create(description: "Ronco All'Adige", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 5684)
Comune.create(description: "Rovere' Veronese", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 2098)
Comune.create(description: "Roveredo Di Gua'", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 1371)
Comune.create(description: "Sant'Ambrogio Di Valpolicella", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 9681)
Comune.create(description: "Sant'Anna D'Alfaedo", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 2462)
Comune.create(description: "Sorga'", province_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 2980)
