Comune.create(description: "Affi", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 1942)
Comune.create(description: "Angiari", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 1844)
Comune.create(description: "Arcole", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 5274)
Comune.create(description: "Badia Calavena", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 2373)
Comune.create(description: "Bardolino", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 6329)
Comune.create(description: "Belfiore", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 2645)
Comune.create(description: "Bevilacqua", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 1691)
Comune.create(description: "Bonavigo", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 1881)
Comune.create(description: "Bosco Chiesanuova", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 3203)
Comune.create(description: "Bovolone", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 13426)
Comune.create(description: "Brentino Belluno", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 1301)
Comune.create(description: "Brenzone", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 2358)
Comune.create(description: "Bussolengo", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 16986)
Comune.create(description: "Buttapietra", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 5801)
Comune.create(description: "Caldiero", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 5655)
Comune.create(description: "Caprino Veronese", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 7493)
Comune.create(description: "Casaleone", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 5929)
Comune.create(description: "Castagnaro", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 4151)
Comune.create(description: "Castelnuovo Del Garda", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 8612)
Comune.create(description: "Cavaion Veronese", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 4164)
Comune.create(description: "Cazzano Di Tramigna", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 1302)
Comune.create(description: "Cerea", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 15254)
Comune.create(description: "Cerro Veronese", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 2043)
Comune.create(description: "Cologna Veneta", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 7890)
Comune.create(description: "Colognola Ai Colli", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 6913)
Comune.create(description: "Concamarise", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 1064)
Comune.create(description: "Costermano", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 2986)
Comune.create(description: "Erbezzo", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 775)
Comune.create(description: "Ferrara Di Monte Baldo", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 188)
Comune.create(description: "Fumane", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 3816)
Comune.create(description: "Garda", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 3594)
Comune.create(description: "Gazzo Veronese", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 5515)
Comune.create(description: "Grezzana", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 10045)
Comune.create(description: "Illasi", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 4884)
Comune.create(description: "Isola Della Scala", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 10502)
Comune.create(description: "Isola Rizza", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 2859)
Comune.create(description: "Lavagno", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 5964)
Comune.create(description: "Lazise", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 6055)
Comune.create(description: "Legnago", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 24274)
Comune.create(description: "Malcesine", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 3417)
Comune.create(description: "Marano Di Valpolicella", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 2897)
Comune.create(description: "Mezzane Di Sotto", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 1880)
Comune.create(description: "Minerbe", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 4588)
Comune.create(description: "Montecchia Di Crosara", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 4195)
Comune.create(description: "Mozzecane", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 4949)
Comune.create(description: "Negrar", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 16184)
Comune.create(description: "Nogara", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 7899)
Comune.create(description: "Nogarole Rocca", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 2850)
Comune.create(description: "Oppeano", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 7514)
Comune.create(description: "Pastrengo", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 2362)
Comune.create(description: "Pescantina", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 12414)
Comune.create(description: "Peschiera Del Garda", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 8485)
Comune.create(description: "Povegliano Veronese", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 6567)
Comune.create(description: "Pressana", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 2445)
Comune.create(description: "Rivoli Veronese", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 1980)
Comune.create(description: "Roverchiara", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 2655)
Comune.create(description: "Salizzole", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 3761)
Comune.create(description: "San Bonifacio", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 17513)
Comune.create(description: "San Giovanni Ilarione", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 4889)
Comune.create(description: "San Giovanni Lupatoto", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 21298)
Comune.create(description: "San Martino Buon Albergo", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 13095)
Comune.create(description: "San Mauro Di Saline", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 568)
Comune.create(description: "San Pietro Di Morubio", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 2848)
Comune.create(description: "San Pietro In Cariano", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 12484)
Comune.create(description: "San Zeno Di Montagna", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 1243)
Comune.create(description: "Sanguinetto", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 3998)
Comune.create(description: "Selva Di Progno", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 1001)
Comune.create(description: "Soave", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 6562)
Comune.create(description: "Sommacampagna", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 13001)
Comune.create(description: "Sona", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 14275)
Comune.create(description: "Terrazzo", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 2385)
Comune.create(description: "Torri Del Benaco", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 2626)
Comune.create(description: "Tregnago", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 4896)
Comune.create(description: "Trevenzuolo", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 2424)
Comune.create(description: "Valeggio Sul Mincio", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 10941)
Comune.create(description: "Velo Veronese", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 798)
Comune.create(description: "Verona", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 253208)
Comune.create(description: "Veronella", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 3696)
Comune.create(description: "Vestenanova", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 2614)
Comune.create(description: "Vigasio", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 6798)
Comune.create(description: "Villa Bartolomea", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 5368)
Comune.create(description: "Villafranca Di Verona", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 29353)
Comune.create(description: "Zevio", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 12035)
Comune.create(description: "Zimella", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 4342)
Comune.create(description: "Albaredo D'Adige", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 5032)
Comune.create(description: "Boschi Sant'Anna", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 1347)
Comune.create(description: "Castel D'Azzano", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 10242)
Comune.create(description: "Dolce'", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 2200)
Comune.create(description: "Erbe'", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 1629)
Comune.create(description: "Monteforte D'Alpone", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 7065)
Comune.create(description: "Palu'", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 1124)
Comune.create(description: "Ronca'", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 3385)
Comune.create(description: "Ronco All'Adige", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 5684)
Comune.create(description: "Rovere' Veronese", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 2098)
Comune.create(description: "Roveredo Di Gua'", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 1371)
Comune.create(description: "Sant'Ambrogio Di Valpolicella", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 9681)
Comune.create(description: "Sant'Anna D'Alfaedo", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 2462)
Comune.create(description: "Sorga'", provincia_id: 71, region_id:  17, country_id: 1, continent_id: 1 , population: 2980)
