#encoding: utf-8
Comune.create(:description => "Agugliaro", :provincia_id => 72, :regione_id => 17, :population => 1251)
Comune.create(:description => "Albettone", :provincia_id => 72, :regione_id => 17, :population => 1996)
Comune.create(:description => "Alonte", :provincia_id => 72, :regione_id => 17, :population => 1239)
Comune.create(:description => "Altavilla Vicentina", :provincia_id => 72, :regione_id => 17, :population => 9547)
Comune.create(:description => "Altissimo", :provincia_id => 72, :regione_id => 17, :population => 2263)
Comune.create(:description => "Arcugnano", :provincia_id => 72, :regione_id => 17, :population => 7024)
Comune.create(:description => "Arsiero", :provincia_id => 72, :regione_id => 17, :population => 3353)
Comune.create(:description => "Arzignano", :provincia_id => 72, :regione_id => 17, :population => 23085)
Comune.create(:description => "Asiago", :provincia_id => 72, :regione_id => 17, :population => 6509)
Comune.create(:description => "Asigliano Veneto", :provincia_id => 72, :regione_id => 17, :population => 860)
Comune.create(:description => "Barbarano Vicentino", :provincia_id => 72, :regione_id => 17, :population => 3958)
Comune.create(:description => "Bassano Del Grappa", :provincia_id => 72, :regione_id => 17, :population => 40736)
Comune.create(:description => "Bolzano Vicentino", :provincia_id => 72, :regione_id => 17, :population => 5455)
Comune.create(:description => "Breganze", :provincia_id => 72, :regione_id => 17, :population => 7870)
Comune.create(:description => "Brendola", :provincia_id => 72, :regione_id => 17, :population => 6216)
Comune.create(:description => "Bressanvido", :provincia_id => 72, :regione_id => 17, :population => 2859)
Comune.create(:description => "Brogliano", :provincia_id => 72, :regione_id => 17, :population => 2937)
Comune.create(:description => "Caldogno", :provincia_id => 72, :regione_id => 17, :population => 10116)
Comune.create(:description => "Caltrano", :provincia_id => 72, :regione_id => 17, :population => 2545)
Comune.create(:description => "Calvene", :provincia_id => 72, :regione_id => 17, :population => 1274)
Comune.create(:description => "Camisano Vicentino", :provincia_id => 72, :regione_id => 17, :population => 8473)
Comune.create(:description => "Campiglia Dei Berici", :provincia_id => 72, :regione_id => 17, :population => 1746)
Comune.create(:description => "Campolongo Sul Brenta", :provincia_id => 72, :regione_id => 17, :population => 837)
Comune.create(:description => "Cartigliano", :provincia_id => 72, :regione_id => 17, :population => 3537)
Comune.create(:description => "Cassola", :provincia_id => 72, :regione_id => 17, :population => 12439)
Comune.create(:description => "Castegnero", :provincia_id => 72, :regione_id => 17, :population => 2492)
Comune.create(:description => "Castelgomberto", :provincia_id => 72, :regione_id => 17, :population => 5482)
Comune.create(:description => "Chiampo", :provincia_id => 72, :regione_id => 17, :population => 12147)
Comune.create(:description => "Chiuppano", :provincia_id => 72, :regione_id => 17, :population => 2559)
Comune.create(:description => "Cismon Del Grappa", :provincia_id => 72, :regione_id => 17, :population => 1058)
Comune.create(:description => "Cogollo Del Cengio", :provincia_id => 72, :regione_id => 17, :population => 3330)
Comune.create(:description => "Conco", :provincia_id => 72, :regione_id => 17, :population => 2221)
Comune.create(:description => "Cornedo Vicentino", :provincia_id => 72, :regione_id => 17, :population => 10566)
Comune.create(:description => "Costabissara", :provincia_id => 72, :regione_id => 17, :population => 5692)
Comune.create(:description => "Creazzo", :provincia_id => 72, :regione_id => 17, :population => 10433)
Comune.create(:description => "Crespadoro", :provincia_id => 72, :regione_id => 17, :population => 1467)
Comune.create(:description => "Dueville", :provincia_id => 72, :regione_id => 17, :population => 13063)
Comune.create(:description => "Enego", :provincia_id => 72, :regione_id => 17, :population => 2017)
Comune.create(:description => "Fara Vicentino", :provincia_id => 72, :regione_id => 17, :population => 3810)
Comune.create(:description => "Foza", :provincia_id => 72, :regione_id => 17, :population => 733)
Comune.create(:description => "Gallio", :provincia_id => 72, :regione_id => 17, :population => 2336)
Comune.create(:description => "Gambellara", :provincia_id => 72, :regione_id => 17, :population => 3200)
Comune.create(:description => "Gambugliano", :provincia_id => 72, :regione_id => 17, :population => 789)
Comune.create(:description => "Grancona", :provincia_id => 72, :regione_id => 17, :population => 1746)
Comune.create(:description => "Grisignano Di Zocco", :provincia_id => 72, :regione_id => 17, :population => 4249)
Comune.create(:description => "Grumolo Delle Abbadesse", :provincia_id => 72, :regione_id => 17, :population => 3311)
Comune.create(:description => "Isola Vicentina", :provincia_id => 72, :regione_id => 17, :population => 8034)
Comune.create(:description => "Laghi", :provincia_id => 72, :regione_id => 17, :population => 128)
Comune.create(:description => "Lastebasse", :provincia_id => 72, :regione_id => 17, :population => 243)
Comune.create(:description => "Longare", :provincia_id => 72, :regione_id => 17, :population => 5339)
Comune.create(:description => "Lonigo", :provincia_id => 72, :regione_id => 17, :population => 14005)
Comune.create(:description => "Lugo Di Vicenza", :provincia_id => 72, :regione_id => 17, :population => 3719)
Comune.create(:description => "Lusiana", :provincia_id => 72, :regione_id => 17, :population => 2902)
Comune.create(:description => "Malo", :provincia_id => 72, :regione_id => 17, :population => 12307)
Comune.create(:description => "Marano Vicentino", :provincia_id => 72, :regione_id => 17, :population => 8879)
Comune.create(:description => "Marostica", :provincia_id => 72, :regione_id => 17, :population => 12848)
Comune.create(:description => "Mason Vicentino", :provincia_id => 72, :regione_id => 17, :population => 3130)
Comune.create(:description => "Molvena", :provincia_id => 72, :regione_id => 17, :population => 2426)
Comune.create(:description => "Monte Di Malo", :provincia_id => 72, :regione_id => 17, :population => 2755)
Comune.create(:description => "Montebello Vicentino", :provincia_id => 72, :regione_id => 17, :population => 5771)
Comune.create(:description => "Montecchio Maggiore", :provincia_id => 72, :regione_id => 17, :population => 21061)
Comune.create(:description => "Montecchio Precalcino", :provincia_id => 72, :regione_id => 17, :population => 4623)
Comune.create(:description => "Montegalda", :provincia_id => 72, :regione_id => 17, :population => 3099)
Comune.create(:description => "Montegaldella", :provincia_id => 72, :regione_id => 17, :population => 1721)
Comune.create(:description => "Monteviale", :provincia_id => 72, :regione_id => 17, :population => 2034)
Comune.create(:description => "Monticello Conte Otto", :provincia_id => 72, :regione_id => 17, :population => 8790)
Comune.create(:description => "Montorso Vicentino", :provincia_id => 72, :regione_id => 17, :population => 2854)
Comune.create(:description => "Mossano", :provincia_id => 72, :regione_id => 17, :population => 1670)
Comune.create(:description => "Mussolente", :provincia_id => 72, :regione_id => 17, :population => 6663)
Comune.create(:description => "Nanto", :provincia_id => 72, :regione_id => 17, :population => 2312)
Comune.create(:description => "Nogarole Vicentino", :provincia_id => 72, :regione_id => 17, :population => 995)
Comune.create(:description => "Nove", :provincia_id => 72, :regione_id => 17, :population => 4865)
Comune.create(:description => "Noventa Vicentina", :provincia_id => 72, :regione_id => 17, :population => 8272)
Comune.create(:description => "Orgiano", :provincia_id => 72, :regione_id => 17, :population => 3084)
Comune.create(:description => "Pedemonte", :provincia_id => 72, :regione_id => 17, :population => 830)
Comune.create(:description => "Pianezze", :provincia_id => 72, :regione_id => 17, :population => 1852)
Comune.create(:description => "Piovene Rocchette", :provincia_id => 72, :regione_id => 17, :population => 7723)
Comune.create(:description => "Poiana Maggiore", :provincia_id => 72, :regione_id => 17, :population => 4216)
Comune.create(:description => "Posina", :provincia_id => 72, :regione_id => 17, :population => 727)
Comune.create(:description => "Pove Del Grappa", :provincia_id => 72, :regione_id => 17, :population => 2846)
Comune.create(:description => "Pozzoleone", :provincia_id => 72, :regione_id => 17, :population => 2597)
Comune.create(:description => "Quinto Vicentino", :provincia_id => 72, :regione_id => 17, :population => 4641)
Comune.create(:description => "Recoaro Terme", :provincia_id => 72, :regione_id => 17, :population => 7266)
Comune.create(:description => "Roana", :provincia_id => 72, :regione_id => 17, :population => 3774)
Comune.create(:description => "Rossano Veneto", :provincia_id => 72, :regione_id => 17, :population => 6567)
Comune.create(:description => "Rotzo", :provincia_id => 72, :regione_id => 17, :population => 570)
Comune.create(:description => "Salcedo", :provincia_id => 72, :regione_id => 17, :population => 1029)
Comune.create(:description => "San Germano Dei Berici", :provincia_id => 72, :regione_id => 17, :population => 1097)
Comune.create(:description => "San Nazario", :provincia_id => 72, :regione_id => 17, :population => 1787)
Comune.create(:description => "San Pietro Mussolino", :provincia_id => 72, :regione_id => 17, :population => 1489)
Comune.create(:description => "San Vito Di Leguzzano", :provincia_id => 72, :regione_id => 17, :population => 3390)
Comune.create(:description => "Sandrigo", :provincia_id => 72, :regione_id => 17, :population => 7904)
Comune.create(:description => "Santorso", :provincia_id => 72, :regione_id => 17, :population => 5272)
Comune.create(:description => "Sarcedo", :provincia_id => 72, :regione_id => 17, :population => 5092)
Comune.create(:description => "Sarego", :provincia_id => 72, :regione_id => 17, :population => 5563)
Comune.create(:description => "Schiavon", :provincia_id => 72, :regione_id => 17, :population => 2327)
Comune.create(:description => "Schio", :provincia_id => 72, :regione_id => 17, :population => 37444)
Comune.create(:description => "Solagna", :provincia_id => 72, :regione_id => 17, :population => 1759)
Comune.create(:description => "Sossano", :provincia_id => 72, :regione_id => 17, :population => 4128)
Comune.create(:description => "Sovizzo", :provincia_id => 72, :regione_id => 17, :population => 5727)
Comune.create(:description => "Tezze Sul Brenta", :provincia_id => 72, :regione_id => 17, :population => 10405)
Comune.create(:description => "Thiene", :provincia_id => 72, :regione_id => 17, :population => 20977)
Comune.create(:description => "Tonezza Del Cimone", :provincia_id => 72, :regione_id => 17, :population => 619)
Comune.create(:description => "Torrebelvicino", :provincia_id => 72, :regione_id => 17, :population => 5476)
Comune.create(:description => "Torri Di Quartesolo", :provincia_id => 72, :regione_id => 17, :population => 10981)
Comune.create(:description => "Trissino", :provincia_id => 72, :regione_id => 17, :population => 7794)
Comune.create(:description => "Valdagno", :provincia_id => 72, :regione_id => 17, :population => 27193)
Comune.create(:description => "Valdastico", :provincia_id => 72, :regione_id => 17, :population => 1480)
Comune.create(:description => "Valli Del Pasubio", :provincia_id => 72, :regione_id => 17, :population => 3567)
Comune.create(:description => "Valstagna", :provincia_id => 72, :regione_id => 17, :population => 1959)
Comune.create(:description => "Vicenza", :provincia_id => 72, :regione_id => 17, :population => 107223)
Comune.create(:description => "Villaga", :provincia_id => 72, :regione_id => 17, :population => 1859)
Comune.create(:description => "Villaverla", :provincia_id => 72, :regione_id => 17, :population => 5389)
Comune.create(:description => "Zermeghedo", :provincia_id => 72, :regione_id => 17, :population => 1234)
Comune.create(:description => "Zovencedo", :provincia_id => 72, :regione_id => 17, :population => 866)
Comune.create(:description => "Zugliano", :provincia_id => 72, :regione_id => 17, :population => 6166)
Comune.create(:description => "Carre'", :provincia_id => 72, :regione_id => 17, :population => 3265)
Comune.create(:description => "Romano D'Ezzelino", :provincia_id => 72, :regione_id => 17, :population => 13912)
Comune.create(:description => "Rosa'", :provincia_id => 72, :regione_id => 17, :population => 12516)
Comune.create(:description => "Velo D'Astico", :provincia_id => 72, :regione_id => 17, :population => 2350)
Comune.create(:description => "Zane'", :provincia_id => 72, :regione_id => 17, :population => 6114)
