Comune.create(description: "Agugliaro", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 1251)
Comune.create(description: "Albettone", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 1996)
Comune.create(description: "Alonte", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 1239)
Comune.create(description: "Altavilla Vicentina", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 9547)
Comune.create(description: "Altissimo", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 2263)
Comune.create(description: "Arcugnano", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 7024)
Comune.create(description: "Arsiero", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 3353)
Comune.create(description: "Arzignano", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 23085)
Comune.create(description: "Asiago", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 6509)
Comune.create(description: "Asigliano Veneto", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 860)
Comune.create(description: "Barbarano Vicentino", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 3958)
Comune.create(description: "Bassano Del Grappa", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 40736)
Comune.create(description: "Bolzano Vicentino", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 5455)
Comune.create(description: "Breganze", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 7870)
Comune.create(description: "Brendola", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 6216)
Comune.create(description: "Bressanvido", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 2859)
Comune.create(description: "Brogliano", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 2937)
Comune.create(description: "Caldogno", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 10116)
Comune.create(description: "Caltrano", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 2545)
Comune.create(description: "Calvene", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 1274)
Comune.create(description: "Camisano Vicentino", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 8473)
Comune.create(description: "Campiglia Dei Berici", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 1746)
Comune.create(description: "Campolongo Sul Brenta", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 837)
Comune.create(description: "Cartigliano", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 3537)
Comune.create(description: "Cassola", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 12439)
Comune.create(description: "Castegnero", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 2492)
Comune.create(description: "Castelgomberto", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 5482)
Comune.create(description: "Chiampo", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 12147)
Comune.create(description: "Chiuppano", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 2559)
Comune.create(description: "Cismon Del Grappa", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 1058)
Comune.create(description: "Cogollo Del Cengio", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 3330)
Comune.create(description: "Conco", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 2221)
Comune.create(description: "Cornedo Vicentino", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 10566)
Comune.create(description: "Costabissara", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 5692)
Comune.create(description: "Creazzo", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 10433)
Comune.create(description: "Crespadoro", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 1467)
Comune.create(description: "Dueville", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 13063)
Comune.create(description: "Enego", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 2017)
Comune.create(description: "Fara Vicentino", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 3810)
Comune.create(description: "Foza", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 733)
Comune.create(description: "Gallio", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 2336)
Comune.create(description: "Gambellara", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 3200)
Comune.create(description: "Gambugliano", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 789)
Comune.create(description: "Grancona", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 1746)
Comune.create(description: "Grisignano Di Zocco", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 4249)
Comune.create(description: "Grumolo Delle Abbadesse", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 3311)
Comune.create(description: "Isola Vicentina", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 8034)
Comune.create(description: "Laghi", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 128)
Comune.create(description: "Lastebasse", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 243)
Comune.create(description: "Longare", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 5339)
Comune.create(description: "Lonigo", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 14005)
Comune.create(description: "Lugo Di Vicenza", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 3719)
Comune.create(description: "Lusiana", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 2902)
Comune.create(description: "Malo", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 12307)
Comune.create(description: "Marano Vicentino", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 8879)
Comune.create(description: "Marostica", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 12848)
Comune.create(description: "Mason Vicentino", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 3130)
Comune.create(description: "Molvena", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 2426)
Comune.create(description: "Monte Di Malo", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 2755)
Comune.create(description: "Montebello Vicentino", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 5771)
Comune.create(description: "Montecchio Maggiore", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 21061)
Comune.create(description: "Montecchio Precalcino", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 4623)
Comune.create(description: "Montegalda", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 3099)
Comune.create(description: "Montegaldella", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 1721)
Comune.create(description: "Monteviale", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 2034)
Comune.create(description: "Monticello Conte Otto", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 8790)
Comune.create(description: "Montorso Vicentino", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 2854)
Comune.create(description: "Mossano", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 1670)
Comune.create(description: "Mussolente", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 6663)
Comune.create(description: "Nanto", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 2312)
Comune.create(description: "Nogarole Vicentino", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 995)
Comune.create(description: "Nove", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 4865)
Comune.create(description: "Noventa Vicentina", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 8272)
Comune.create(description: "Orgiano", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 3084)
Comune.create(description: "Pedemonte", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 830)
Comune.create(description: "Pianezze", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 1852)
Comune.create(description: "Piovene Rocchette", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 7723)
Comune.create(description: "Poiana Maggiore", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 4216)
Comune.create(description: "Posina", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 727)
Comune.create(description: "Pove Del Grappa", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 2846)
Comune.create(description: "Pozzoleone", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 2597)
Comune.create(description: "Quinto Vicentino", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 4641)
Comune.create(description: "Recoaro Terme", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 7266)
Comune.create(description: "Roana", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 3774)
Comune.create(description: "Rossano Veneto", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 6567)
Comune.create(description: "Rotzo", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 570)
Comune.create(description: "Salcedo", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 1029)
Comune.create(description: "San Germano Dei Berici", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 1097)
Comune.create(description: "San Nazario", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 1787)
Comune.create(description: "San Pietro Mussolino", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 1489)
Comune.create(description: "San Vito Di Leguzzano", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 3390)
Comune.create(description: "Sandrigo", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 7904)
Comune.create(description: "Santorso", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 5272)
Comune.create(description: "Sarcedo", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 5092)
Comune.create(description: "Sarego", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 5563)
Comune.create(description: "Schiavon", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 2327)
Comune.create(description: "Schio", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 37444)
Comune.create(description: "Solagna", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 1759)
Comune.create(description: "Sossano", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 4128)
Comune.create(description: "Sovizzo", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 5727)
Comune.create(description: "Tezze Sul Brenta", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 10405)
Comune.create(description: "Thiene", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 20977)
Comune.create(description: "Tonezza Del Cimone", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 619)
Comune.create(description: "Torrebelvicino", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 5476)
Comune.create(description: "Torri Di Quartesolo", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 10981)
Comune.create(description: "Trissino", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 7794)
Comune.create(description: "Valdagno", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 27193)
Comune.create(description: "Valdastico", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 1480)
Comune.create(description: "Valli Del Pasubio", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 3567)
Comune.create(description: "Valstagna", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 1959)
Comune.create(description: "Vicenza", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 107223)
Comune.create(description: "Villaga", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 1859)
Comune.create(description: "Villaverla", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 5389)
Comune.create(description: "Zermeghedo", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 1234)
Comune.create(description: "Zovencedo", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 866)
Comune.create(description: "Zugliano", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 6166)
Comune.create(description: "Carre'", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 3265)
Comune.create(description: "Romano D'Ezzelino", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 13912)
Comune.create(description: "Rosa'", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 12516)
Comune.create(description: "Velo D'Astico", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 2350)
Comune.create(description: "Zane'", province_id: 72, region_id:  17, country_id: 1, continent_id: 1 , population: 6114)
