Municipality.create(description: "Capriva Del Friuli", province_id: 73, region_id:  15, country_id: 1, continent_id: 1 , population: 1613)
Municipality.create(description: "Cormons", province_id: 73, region_id:  15, country_id: 1, continent_id: 1 , population: 7449)
Municipality.create(description: "Dolegna Del Collio", province_id: 73, region_id:  15, country_id: 1, continent_id: 1 , population: 435)
Municipality.create(description: "Fogliano Redipuglia", province_id: 73, region_id:  15, country_id: 1, continent_id: 1 , population: 2706)
Municipality.create(description: "Gorizia", province_id: 73, region_id:  15, country_id: 1, continent_id: 1 , population: 35667)
Municipality.create(description: "Grado", province_id: 73, region_id:  15, country_id: 1, continent_id: 1 , population: 8728)
Municipality.create(description: "Mariano Del Friuli", province_id: 73, region_id:  15, country_id: 1, continent_id: 1 , population: 1530)
Municipality.create(description: "Medea", province_id: 73, region_id:  15, country_id: 1, continent_id: 1 , population: 937)
Municipality.create(description: "Monfalcone", province_id: 73, region_id:  15, country_id: 1, continent_id: 1 , population: 26393)
Municipality.create(description: "Moraro", province_id: 73, region_id:  15, country_id: 1, continent_id: 1 , population: 694)
Municipality.create(description: "Mossa", province_id: 73, region_id:  15, country_id: 1, continent_id: 1 , population: 1643)
Municipality.create(description: "Ronchi Dei Legionari", province_id: 73, region_id:  15, country_id: 1, continent_id: 1 , population: 11121)
Municipality.create(description: "Sagrado", province_id: 73, region_id:  15, country_id: 1, continent_id: 1 , population: 2087)
Municipality.create(description: "San Floriano Del Collio", province_id: 73, region_id:  15, country_id: 1, continent_id: 1 , population: 821)
Municipality.create(description: "San Lorenzo Isontino", province_id: 73, region_id:  15, country_id: 1, continent_id: 1 , population: 1412)
Municipality.create(description: "Staranzano", province_id: 73, region_id:  15, country_id: 1, continent_id: 1 , population: 6642)
Municipality.create(description: "Turriaco", province_id: 73, region_id:  15, country_id: 1, continent_id: 1 , population: 2437)
Municipality.create(description: "Villesse", province_id: 73, region_id:  15, country_id: 1, continent_id: 1 , population: 1577)
Municipality.create(description: "Doberdo' Del Lago", province_id: 73, region_id:  15, country_id: 1, continent_id: 1 , population: 1410)
Municipality.create(description: "Farra D'Isonzo", province_id: 73, region_id:  15, country_id: 1, continent_id: 1 , population: 1712)
Municipality.create(description: "Gradisca D'Isonzo", province_id: 73, region_id:  15, country_id: 1, continent_id: 1 , population: 6451)
Municipality.create(description: "Romans D'Isonzo", province_id: 73, region_id:  15, country_id: 1, continent_id: 1 , population: 3604)
Municipality.create(description: "San Canzian D'Isonzo", province_id: 73, region_id:  15, country_id: 1, continent_id: 1 , population: 5808)
Municipality.create(description: "San Pier D'Isonzo", province_id: 73, region_id:  15, country_id: 1, continent_id: 1 , population: 1892)
Municipality.create(description: "Savogna D'Isonzo", province_id: 73, region_id:  15, country_id: 1, continent_id: 1 , population: 1722)
