#encoding: utf-8
Comune.create(description: "Capriva Del Friuli", provincia_id: 73, regione_id: 15, stato_id: 1, continente_id: 1 , population: 1613)
Comune.create(description: "Cormons", provincia_id: 73, regione_id: 15, stato_id: 1, continente_id: 1 , population: 7449)
Comune.create(description: "Dolegna Del Collio", provincia_id: 73, regione_id: 15, stato_id: 1, continente_id: 1 , population: 435)
Comune.create(description: "Fogliano Redipuglia", provincia_id: 73, regione_id: 15, stato_id: 1, continente_id: 1 , population: 2706)
Comune.create(description: "Gorizia", provincia_id: 73, regione_id: 15, stato_id: 1, continente_id: 1 , population: 35667)
Comune.create(description: "Grado", provincia_id: 73, regione_id: 15, stato_id: 1, continente_id: 1 , population: 8728)
Comune.create(description: "Mariano Del Friuli", provincia_id: 73, regione_id: 15, stato_id: 1, continente_id: 1 , population: 1530)
Comune.create(description: "Medea", provincia_id: 73, regione_id: 15, stato_id: 1, continente_id: 1 , population: 937)
Comune.create(description: "Monfalcone", provincia_id: 73, regione_id: 15, stato_id: 1, continente_id: 1 , population: 26393)
Comune.create(description: "Moraro", provincia_id: 73, regione_id: 15, stato_id: 1, continente_id: 1 , population: 694)
Comune.create(description: "Mossa", provincia_id: 73, regione_id: 15, stato_id: 1, continente_id: 1 , population: 1643)
Comune.create(description: "Ronchi Dei Legionari", provincia_id: 73, regione_id: 15, stato_id: 1, continente_id: 1 , population: 11121)
Comune.create(description: "Sagrado", provincia_id: 73, regione_id: 15, stato_id: 1, continente_id: 1 , population: 2087)
Comune.create(description: "San Floriano Del Collio", provincia_id: 73, regione_id: 15, stato_id: 1, continente_id: 1 , population: 821)
Comune.create(description: "San Lorenzo Isontino", provincia_id: 73, regione_id: 15, stato_id: 1, continente_id: 1 , population: 1412)
Comune.create(description: "Staranzano", provincia_id: 73, regione_id: 15, stato_id: 1, continente_id: 1 , population: 6642)
Comune.create(description: "Turriaco", provincia_id: 73, regione_id: 15, stato_id: 1, continente_id: 1 , population: 2437)
Comune.create(description: "Villesse", provincia_id: 73, regione_id: 15, stato_id: 1, continente_id: 1 , population: 1577)
Comune.create(description: "Doberdo' Del Lago", provincia_id: 73, regione_id: 15, stato_id: 1, continente_id: 1 , population: 1410)
Comune.create(description: "Farra D'Isonzo", provincia_id: 73, regione_id: 15, stato_id: 1, continente_id: 1 , population: 1712)
Comune.create(description: "Gradisca D'Isonzo", provincia_id: 73, regione_id: 15, stato_id: 1, continente_id: 1 , population: 6451)
Comune.create(description: "Romans D'Isonzo", provincia_id: 73, regione_id: 15, stato_id: 1, continente_id: 1 , population: 3604)
Comune.create(description: "San Canzian D'Isonzo", provincia_id: 73, regione_id: 15, stato_id: 1, continente_id: 1 , population: 5808)
Comune.create(description: "San Pier D'Isonzo", provincia_id: 73, regione_id: 15, stato_id: 1, continente_id: 1 , population: 1892)
Comune.create(description: "Savogna D'Isonzo", provincia_id: 73, regione_id: 15, stato_id: 1, continente_id: 1 , population: 1722)
