#encoding: utf-8
Comune.create(:description => "Arcidosso", :provincia_id => 50, :regione_id => 12, stato_id: 1, continente_id: 1 , :population => 4114)
Comune.create(:description => "Campagnatico", :provincia_id => 50, :regione_id => 12, stato_id: 1, continente_id: 1 , :population => 2423)
Comune.create(:description => "Capalbio", :provincia_id => 50, :regione_id => 12, stato_id: 1, continente_id: 1 , :population => 3750)
Comune.create(:description => "Castel Del Piano", :provincia_id => 50, :regione_id => 12, stato_id: 1, continente_id: 1 , :population => 4331)
Comune.create(:description => "Castiglione Della Pescaia", :provincia_id => 50, :regione_id => 12, stato_id: 1, continente_id: 1 , :population => 7272)
Comune.create(:description => "Cinigiano", :provincia_id => 50, :regione_id => 12, stato_id: 1, continente_id: 1 , :population => 2695)
Comune.create(:description => "Civitella Paganico", :provincia_id => 50, :regione_id => 12, stato_id: 1, continente_id: 1 , :population => 3045)
Comune.create(:description => "Follonica", :provincia_id => 50, :regione_id => 12, stato_id: 1, continente_id: 1 , :population => 21091)
Comune.create(:description => "Gavorrano", :provincia_id => 50, :regione_id => 12, stato_id: 1, continente_id: 1 , :population => 8193)
Comune.create(:description => "Grosseto", :provincia_id => 50, :regione_id => 12, stato_id: 1, continente_id: 1 , :population => 71263)
Comune.create(:description => "Isola Del Giglio", :provincia_id => 50, :regione_id => 12, stato_id: 1, continente_id: 1 , :population => 1406)
Comune.create(:description => "Magliano In Toscana", :provincia_id => 50, :regione_id => 12, stato_id: 1, continente_id: 1 , :population => 3719)
Comune.create(:description => "Manciano", :provincia_id => 50, :regione_id => 12, stato_id: 1, continente_id: 1 , :population => 6871)
Comune.create(:description => "Massa Marittima", :provincia_id => 50, :regione_id => 12, stato_id: 1, continente_id: 1 , :population => 8818)
Comune.create(:description => "Monte Argentario", :provincia_id => 50, :regione_id => 12, stato_id: 1, continente_id: 1 , :population => 12147)
Comune.create(:description => "Monterotondo Marittimo", :provincia_id => 50, :regione_id => 12, stato_id: 1, continente_id: 1 , :population => 1210)
Comune.create(:description => "Montieri", :provincia_id => 50, :regione_id => 12, stato_id: 1, continente_id: 1 , :population => 1248)
Comune.create(:description => "Orbetello", :provincia_id => 50, :regione_id => 12, stato_id: 1, continente_id: 1 , :population => 14607)
Comune.create(:description => "Pitigliano", :provincia_id => 50, :regione_id => 12, stato_id: 1, continente_id: 1 , :population => 4134)
Comune.create(:description => "Roccalbegna", :provincia_id => 50, :regione_id => 12, stato_id: 1, continente_id: 1 , :population => 1241)
Comune.create(:description => "Roccastrada", :provincia_id => 50, :regione_id => 12, stato_id: 1, continente_id: 1 , :population => 9199)
Comune.create(:description => "Santa Fiora", :provincia_id => 50, :regione_id => 12, stato_id: 1, continente_id: 1 , :population => 2767)
Comune.create(:description => "Scansano", :provincia_id => 50, :regione_id => 12, stato_id: 1, continente_id: 1 , :population => 4386)
Comune.create(:description => "Scarlino", :provincia_id => 50, :regione_id => 12, stato_id: 1, continente_id: 1 , :population => 3136)
Comune.create(:description => "Seggiano", :provincia_id => 50, :regione_id => 12, stato_id: 1, continente_id: 1 , :population => 953)
Comune.create(:description => "Semproniano", :provincia_id => 50, :regione_id => 12, stato_id: 1, continente_id: 1 , :population => 1326)
Comune.create(:description => "Sorano", :provincia_id => 50, :regione_id => 12, stato_id: 1, continente_id: 1 , :population => 3915)
Comune.create(:description => "Castell'Azzara", :provincia_id => 50, :regione_id => 12, stato_id: 1, continente_id: 1 , :population => 1826)
