Comune.create(description: "Andreis", province_id: 74, region_id:  15, country_id: 1, continent_id: 1 , population: 323)
Comune.create(description: "Arba", province_id: 74, region_id:  15, country_id: 1, continent_id: 1 , population: 1228)
Comune.create(description: "Arzene", province_id: 74, region_id:  15, country_id: 1, continent_id: 1 , population: 1608)
Comune.create(description: "Aviano", province_id: 74, region_id:  15, country_id: 1, continent_id: 1 , population: 8225)
Comune.create(description: "Azzano Decimo", province_id: 74, region_id:  15, country_id: 1, continent_id: 1 , population: 12880)
Comune.create(description: "Barcis", province_id: 74, region_id:  15, country_id: 1, continent_id: 1 , population: 306)
Comune.create(description: "Brugnera", province_id: 74, region_id:  15, country_id: 1, continent_id: 1 , population: 8112)
Comune.create(description: "Budoia", province_id: 74, region_id:  15, country_id: 1, continent_id: 1 , population: 2147)
Comune.create(description: "Caneva", province_id: 74, region_id:  15, country_id: 1, continent_id: 1 , population: 6323)
Comune.create(description: "Casarsa Della Delizia", province_id: 74, region_id:  15, country_id: 1, continent_id: 1 , population: 8135)
Comune.create(description: "Castelnovo Del Friuli", province_id: 74, region_id:  15, country_id: 1, continent_id: 1 , population: 899)
Comune.create(description: "Cavasso Nuovo", province_id: 74, region_id:  15, country_id: 1, continent_id: 1 , population: 1408)
Comune.create(description: "Chions", province_id: 74, region_id:  15, country_id: 1, continent_id: 1 , population: 4523)
Comune.create(description: "Cimolais", province_id: 74, region_id:  15, country_id: 1, continent_id: 1 , population: 465)
Comune.create(description: "Claut", province_id: 74, region_id:  15, country_id: 1, continent_id: 1 , population: 1181)
Comune.create(description: "Clauzetto", province_id: 74, region_id:  15, country_id: 1, continent_id: 1 , population: 419)
Comune.create(description: "Cordenons", province_id: 74, region_id:  15, country_id: 1, continent_id: 1 , population: 16991)
Comune.create(description: "Cordovado", province_id: 74, region_id:  15, country_id: 1, continent_id: 1 , population: 2518)
Comune.create(description: "Erto E Casso", province_id: 74, region_id:  15, country_id: 1, continent_id: 1 , population: 424)
Comune.create(description: "Fanna", province_id: 74, region_id:  15, country_id: 1, continent_id: 1 , population: 1516)
Comune.create(description: "Fiume Veneto", province_id: 74, region_id:  15, country_id: 1, continent_id: 1 , population: 10221)
Comune.create(description: "Fontanafredda", province_id: 74, region_id:  15, country_id: 1, continent_id: 1 , population: 9515)
Comune.create(description: "Frisanco", province_id: 74, region_id:  15, country_id: 1, continent_id: 1 , population: 650)
Comune.create(description: "Maniago", province_id: 74, region_id:  15, country_id: 1, continent_id: 1 , population: 11708)
Comune.create(description: "Meduno", province_id: 74, region_id:  15, country_id: 1, continent_id: 1 , population: 1730)
Comune.create(description: "Montereale Valcellina", province_id: 74, region_id:  15, country_id: 1, continent_id: 1 , population: 4656)
Comune.create(description: "Morsano Al Tagliamento", province_id: 74, region_id:  15, country_id: 1, continent_id: 1 , population: 2762)
Comune.create(description: "Pasiano Di Pordenone", province_id: 74, region_id:  15, country_id: 1, continent_id: 1 , population: 7422)
Comune.create(description: "Pinzano Al Tagliamento", province_id: 74, region_id:  15, country_id: 1, continent_id: 1 , population: 1608)
Comune.create(description: "Polcenigo", province_id: 74, region_id:  15, country_id: 1, continent_id: 1 , population: 3127)
Comune.create(description: "Porcia", province_id: 74, region_id:  15, country_id: 1, continent_id: 1 , population: 13616)
Comune.create(description: "Pordenone", province_id: 74, region_id:  15, country_id: 1, continent_id: 1 , population: 49122)
Comune.create(description: "Prata Di Pordenone", province_id: 74, region_id:  15, country_id: 1, continent_id: 1 , population: 6964)
Comune.create(description: "Pravisdomini", province_id: 74, region_id:  15, country_id: 1, continent_id: 1 , population: 2576)
Comune.create(description: "Roveredo In Piano", province_id: 74, region_id:  15, country_id: 1, continent_id: 1 , population: 4853)
Comune.create(description: "Sacile", province_id: 74, region_id:  15, country_id: 1, continent_id: 1 , population: 18215)
Comune.create(description: "San Giorgio Della Richinvelda", province_id: 74, region_id:  15, country_id: 1, continent_id: 1 , population: 4316)
Comune.create(description: "San Martino Al Tagliamento", province_id: 74, region_id:  15, country_id: 1, continent_id: 1 , population: 1336)
Comune.create(description: "San Quirino", province_id: 74, region_id:  15, country_id: 1, continent_id: 1 , population: 3816)
Comune.create(description: "San Vito Al Tagliamento", province_id: 74, region_id:  15, country_id: 1, continent_id: 1 , population: 13316)
Comune.create(description: "Sequals", province_id: 74, region_id:  15, country_id: 1, continent_id: 1 , population: 2122)
Comune.create(description: "Sesto Al Reghena", province_id: 74, region_id:  15, country_id: 1, continent_id: 1 , population: 5311)
Comune.create(description: "Spilimbergo", province_id: 74, region_id:  15, country_id: 1, continent_id: 1 , population: 11087)
Comune.create(description: "Tramonti Di Sopra", province_id: 74, region_id:  15, country_id: 1, continent_id: 1 , population: 409)
Comune.create(description: "Tramonti Di Sotto", province_id: 74, region_id:  15, country_id: 1, continent_id: 1 , population: 440)
Comune.create(description: "Travesio", province_id: 74, region_id:  15, country_id: 1, continent_id: 1 , population: 1767)
Comune.create(description: "Vajont", province_id: 74, region_id:  15, country_id: 1, continent_id: 1 , population: 1372)
Comune.create(description: "Valvasone", province_id: 74, region_id:  15, country_id: 1, continent_id: 1 , population: 1936)
Comune.create(description: "Vivaro", province_id: 74, region_id:  15, country_id: 1, continent_id: 1 , population: 1272)
Comune.create(description: "Zoppola", province_id: 74, region_id:  15, country_id: 1, continent_id: 1 , population: 8430)
Comune.create(description: "Vito D'Asio", province_id: 74, region_id:  15, country_id: 1, continent_id: 1 , population: 892)
