Comune.create(description: "Aiello Del Friuli", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 2180)
Comune.create(description: "Amaro", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 751)
Comune.create(description: "Ampezzo", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 1161)
Comune.create(description: "Aquileia", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 3329)
Comune.create(description: "Arta Terme", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 2234)
Comune.create(description: "Artegna", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 2904)
Comune.create(description: "Attimis", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 1833)
Comune.create(description: "Bagnaria Arsa", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 3428)
Comune.create(description: "Basiliano", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 4894)
Comune.create(description: "Bertiolo", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 2542)
Comune.create(description: "Bicinicco", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 1832)
Comune.create(description: "Bordano", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 786)
Comune.create(description: "Buia", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 )
Comune.create(description: "Buttrio", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 3788)
Comune.create(description: "Camino Al Tagliamento", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 1632)
Comune.create(description: "Campoformido", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 7244)
Comune.create(description: "Campolongo Al Torre", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Carlino", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 2822)
Comune.create(description: "Cassacco", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 2849)
Comune.create(description: "Castions Di Strada", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 3725)
Comune.create(description: "Cavazzo Carnico", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 1140)
Comune.create(description: "Cercivento", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 771)
Comune.create(description: "Cervignano Del Friuli", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 12421)
Comune.create(description: "Chiopris Viscone", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 659)
Comune.create(description: "Chiusaforte", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 815)
Comune.create(description: "Cividale Del Friuli", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 11373)
Comune.create(description: "Codroipo", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 14421)
Comune.create(description: "Colloredo Di Monte Albano", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 2154)
Comune.create(description: "Comeglians", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 637)
Comune.create(description: "Corno Di Rosazzo", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 3308)
Comune.create(description: "Coseano", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 2214)
Comune.create(description: "Dignano", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 2326)
Comune.create(description: "Dogna", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 259)
Comune.create(description: "Drenchia", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 197)
Comune.create(description: "Enemonzo", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 1347)
Comune.create(description: "Faedis", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 3070)
Comune.create(description: "Fagagna", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 6035)
Comune.create(description: "Fiumicello", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 4297)
Comune.create(description: "Flaibano", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 1183)
Comune.create(description: "Forgaria Nel Friuli", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Forni Avoltri", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 735)
Comune.create(description: "Forni Di Sopra", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 1123)
Comune.create(description: "Forni Di Sotto", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 716)
Comune.create(description: "Gemona Del Friuli", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 11070)
Comune.create(description: "Gonars", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 4639)
Comune.create(description: "Grimacco", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 488)
Comune.create(description: "Latisana", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 11896)
Comune.create(description: "Lauco", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 877)
Comune.create(description: "Lestizza", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 3890)
Comune.create(description: "Lignano Sabbiadoro", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 5983)
Comune.create(description: "Ligosullo", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 195)
Comune.create(description: "Lusevera", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 788)
Comune.create(description: "Magnano In Riviera", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 2288)
Comune.create(description: "Majano", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 5877)
Comune.create(description: "Malborghetto Valbruna", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 )
Comune.create(description: "Marano Lagunare", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 2048)
Comune.create(description: "Martignacco", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 5405)
Comune.create(description: "Mereto Di Tomba", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 2697)
Comune.create(description: "Moggio Udinese", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 2095)
Comune.create(description: "Moimacco", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 1557)
Comune.create(description: "Montenars", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 536)
Comune.create(description: "Mortegliano", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 4890)
Comune.create(description: "Moruzzo", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 2170)
Comune.create(description: "Muzzana Del Turgnano", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 2660)
Comune.create(description: "Nimis", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 2825)
Comune.create(description: "Osoppo", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 2889)
Comune.create(description: "Ovaro", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 2220)
Comune.create(description: "Pagnacco", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 4606)
Comune.create(description: "Palazzolo Dello Stella", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 3036)
Comune.create(description: "Palmanova", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 5340)
Comune.create(description: "Paluzza", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 2597)
Comune.create(description: "Pasian Di Prato", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 8708)
Comune.create(description: "Paularo", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 2907)
Comune.create(description: "Pavia Di Udine", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 5477)
Comune.create(description: "Pocenia", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 2577)
Comune.create(description: "Pontebba", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 1768)
Comune.create(description: "Porpetto", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 2683)
Comune.create(description: "Povoletto", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 5276)
Comune.create(description: "Pozzuolo Del Friuli", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 6311)
Comune.create(description: "Pradamano", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 2960)
Comune.create(description: "Prato Carnico", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 1065)
Comune.create(description: "Precenicco", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 1508)
Comune.create(description: "Premariacco", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 4001)
Comune.create(description: "Preone", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 294)
Comune.create(description: "Prepotto", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 899)
Comune.create(description: "Pulfero", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 1202)
Comune.create(description: "Ragogna", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 3006)
Comune.create(description: "Ravascletto", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 642)
Comune.create(description: "Raveo", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 490)
Comune.create(description: "Reana Del Roiale", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 4726)
Comune.create(description: "Remanzacco", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 5547)
Comune.create(description: "Resia", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 1285)
Comune.create(description: "Resiutta", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 354)
Comune.create(description: "Rigolato", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 641)
Comune.create(description: "Rivignano", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 4015)
Comune.create(description: "Ronchis", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 1966)
Comune.create(description: "Ruda", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 2969)
Comune.create(description: "San Daniele Del Friuli", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 7893)
Comune.create(description: "San Giorgio Di Nogaro", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 7314)
Comune.create(description: "San Giovanni Al Natisone", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 5735)
Comune.create(description: "San Leonardo", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 1169)
Comune.create(description: "San Pietro Al Natisone", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 2155)
Comune.create(description: "San Vito Al Torre", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 1300)
Comune.create(description: "San Vito Di Fagagna", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 1617)
Comune.create(description: "Santa Maria La Longa", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 2313)
Comune.create(description: "Sauris", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 414)
Comune.create(description: "Savogna", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 659)
Comune.create(description: "Sedegliano", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 3852)
Comune.create(description: "Socchieve", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 1023)
Comune.create(description: "Stregna", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 456)
Comune.create(description: "Sutrio", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 1392)
Comune.create(description: "Taipana", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 715)
Comune.create(description: "Talmassons", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 4114)
Comune.create(description: "Tapogliano", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Tarcento", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 8716)
Comune.create(description: "Tarvisio", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 5071)
Comune.create(description: "Tavagnacco", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 12374)
Comune.create(description: "Teor", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 1996)
Comune.create(description: "Terzo Di Aquileia", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 2661)
Comune.create(description: "Tolmezzo", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 10611)
Comune.create(description: "Torreano", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 2266)
Comune.create(description: "Torviscosa", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 3230)
Comune.create(description: "Trasaghis", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 2490)
Comune.create(description: "Treppo Carnico", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 660)
Comune.create(description: "Treppo Grande", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 1754)
Comune.create(description: "Tricesimo", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 7305)
Comune.create(description: "Trivignano Udinese", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 1706)
Comune.create(description: "Udine", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 95030)
Comune.create(description: "Varmo", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 2892)
Comune.create(description: "Venzone", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 2300)
Comune.create(description: "Verzegnis", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 908)
Comune.create(description: "Villa Santina", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 2194)
Comune.create(description: "Villa Vicentina", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 1342)
Comune.create(description: "Visco", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 697)
Comune.create(description: "Zuglio", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 642)
Comune.create(description: "Rive D'Arcano", province_id: 75, region_id:  15, country_id: 1, continent_id: 1 , population: 2284)
