Comune.create(description: "Aiello Del Friuli", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 2180)
Comune.create(description: "Amaro", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 751)
Comune.create(description: "Ampezzo", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 1161)
Comune.create(description: "Aquileia", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 3329)
Comune.create(description: "Arta Terme", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 2234)
Comune.create(description: "Artegna", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 2904)
Comune.create(description: "Attimis", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 1833)
Comune.create(description: "Bagnaria Arsa", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 3428)
Comune.create(description: "Basiliano", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 4894)
Comune.create(description: "Bertiolo", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 2542)
Comune.create(description: "Bicinicco", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 1832)
Comune.create(description: "Bordano", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 786)
Comune.create(description: "Buia", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 )
Comune.create(description: "Buttrio", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 3788)
Comune.create(description: "Camino Al Tagliamento", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 1632)
Comune.create(description: "Campoformido", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 7244)
Comune.create(description: "Campolongo Al Torre", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Carlino", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 2822)
Comune.create(description: "Cassacco", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 2849)
Comune.create(description: "Castions Di Strada", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 3725)
Comune.create(description: "Cavazzo Carnico", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 1140)
Comune.create(description: "Cercivento", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 771)
Comune.create(description: "Cervignano Del Friuli", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 12421)
Comune.create(description: "Chiopris Viscone", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 659)
Comune.create(description: "Chiusaforte", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 815)
Comune.create(description: "Cividale Del Friuli", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 11373)
Comune.create(description: "Codroipo", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 14421)
Comune.create(description: "Colloredo Di Monte Albano", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 2154)
Comune.create(description: "Comeglians", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 637)
Comune.create(description: "Corno Di Rosazzo", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 3308)
Comune.create(description: "Coseano", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 2214)
Comune.create(description: "Dignano", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 2326)
Comune.create(description: "Dogna", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 259)
Comune.create(description: "Drenchia", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 197)
Comune.create(description: "Enemonzo", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 1347)
Comune.create(description: "Faedis", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 3070)
Comune.create(description: "Fagagna", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 6035)
Comune.create(description: "Fiumicello", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 4297)
Comune.create(description: "Flaibano", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 1183)
Comune.create(description: "Forgaria Nel Friuli", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Forni Avoltri", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 735)
Comune.create(description: "Forni Di Sopra", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 1123)
Comune.create(description: "Forni Di Sotto", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 716)
Comune.create(description: "Gemona Del Friuli", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 11070)
Comune.create(description: "Gonars", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 4639)
Comune.create(description: "Grimacco", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 488)
Comune.create(description: "Latisana", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 11896)
Comune.create(description: "Lauco", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 877)
Comune.create(description: "Lestizza", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 3890)
Comune.create(description: "Lignano Sabbiadoro", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 5983)
Comune.create(description: "Ligosullo", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 195)
Comune.create(description: "Lusevera", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 788)
Comune.create(description: "Magnano In Riviera", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 2288)
Comune.create(description: "Majano", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 5877)
Comune.create(description: "Malborghetto Valbruna", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 )
Comune.create(description: "Marano Lagunare", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 2048)
Comune.create(description: "Martignacco", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 5405)
Comune.create(description: "Mereto Di Tomba", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 2697)
Comune.create(description: "Moggio Udinese", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 2095)
Comune.create(description: "Moimacco", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 1557)
Comune.create(description: "Montenars", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 536)
Comune.create(description: "Mortegliano", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 4890)
Comune.create(description: "Moruzzo", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 2170)
Comune.create(description: "Muzzana Del Turgnano", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 2660)
Comune.create(description: "Nimis", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 2825)
Comune.create(description: "Osoppo", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 2889)
Comune.create(description: "Ovaro", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 2220)
Comune.create(description: "Pagnacco", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 4606)
Comune.create(description: "Palazzolo Dello Stella", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 3036)
Comune.create(description: "Palmanova", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 5340)
Comune.create(description: "Paluzza", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 2597)
Comune.create(description: "Pasian Di Prato", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 8708)
Comune.create(description: "Paularo", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 2907)
Comune.create(description: "Pavia Di Udine", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 5477)
Comune.create(description: "Pocenia", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 2577)
Comune.create(description: "Pontebba", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 1768)
Comune.create(description: "Porpetto", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 2683)
Comune.create(description: "Povoletto", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 5276)
Comune.create(description: "Pozzuolo Del Friuli", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 6311)
Comune.create(description: "Pradamano", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 2960)
Comune.create(description: "Prato Carnico", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 1065)
Comune.create(description: "Precenicco", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 1508)
Comune.create(description: "Premariacco", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 4001)
Comune.create(description: "Preone", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 294)
Comune.create(description: "Prepotto", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 899)
Comune.create(description: "Pulfero", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 1202)
Comune.create(description: "Ragogna", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 3006)
Comune.create(description: "Ravascletto", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 642)
Comune.create(description: "Raveo", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 490)
Comune.create(description: "Reana Del Roiale", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 4726)
Comune.create(description: "Remanzacco", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 5547)
Comune.create(description: "Resia", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 1285)
Comune.create(description: "Resiutta", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 354)
Comune.create(description: "Rigolato", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 641)
Comune.create(description: "Rivignano", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 4015)
Comune.create(description: "Ronchis", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 1966)
Comune.create(description: "Ruda", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 2969)
Comune.create(description: "San Daniele Del Friuli", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 7893)
Comune.create(description: "San Giorgio Di Nogaro", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 7314)
Comune.create(description: "San Giovanni Al Natisone", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 5735)
Comune.create(description: "San Leonardo", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 1169)
Comune.create(description: "San Pietro Al Natisone", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 2155)
Comune.create(description: "San Vito Al Torre", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 1300)
Comune.create(description: "San Vito Di Fagagna", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 1617)
Comune.create(description: "Santa Maria La Longa", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 2313)
Comune.create(description: "Sauris", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 414)
Comune.create(description: "Savogna", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 659)
Comune.create(description: "Sedegliano", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 3852)
Comune.create(description: "Socchieve", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 1023)
Comune.create(description: "Stregna", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 456)
Comune.create(description: "Sutrio", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 1392)
Comune.create(description: "Taipana", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 715)
Comune.create(description: "Talmassons", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 4114)
Comune.create(description: "Tapogliano", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Tarcento", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 8716)
Comune.create(description: "Tarvisio", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 5071)
Comune.create(description: "Tavagnacco", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 12374)
Comune.create(description: "Teor", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 1996)
Comune.create(description: "Terzo Di Aquileia", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 2661)
Comune.create(description: "Tolmezzo", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 10611)
Comune.create(description: "Torreano", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 2266)
Comune.create(description: "Torviscosa", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 3230)
Comune.create(description: "Trasaghis", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 2490)
Comune.create(description: "Treppo Carnico", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 660)
Comune.create(description: "Treppo Grande", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 1754)
Comune.create(description: "Tricesimo", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 7305)
Comune.create(description: "Trivignano Udinese", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 1706)
Comune.create(description: "Udine", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 95030)
Comune.create(description: "Varmo", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 2892)
Comune.create(description: "Venzone", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 2300)
Comune.create(description: "Verzegnis", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 908)
Comune.create(description: "Villa Santina", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 2194)
Comune.create(description: "Villa Vicentina", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 1342)
Comune.create(description: "Visco", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 697)
Comune.create(description: "Zuglio", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 642)
Comune.create(description: "Rive D'Arcano", provincia_id: 75, regione_id: 15, country_id: 1, continent_id: 1 , population: 2284)
