Municipality.create(description: "Duino Aurisina", province_id: 76, region_id:  15, country_id: 1, continent_id: 1 )
Municipality.create(description: "Monrupino", province_id: 76, region_id:  15, country_id: 1, continent_id: 1 , population: 868)
Municipality.create(description: "Muggia", province_id: 76, region_id:  15, country_id: 1, continent_id: 1 , population: 13306)
Municipality.create(description: "San Dorligo Della Valle", province_id: 76, region_id:  15, country_id: 1, continent_id: 1 , population: 5927)
Municipality.create(description: "Sgonico", province_id: 76, region_id:  15, country_id: 1, continent_id: 1 , population: 2185)
Municipality.create(description: "Trieste", province_id: 76, region_id:  15, country_id: 1, continent_id: 1 , population: 211184)
