Municipality.create(description: "Suelli", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Armungia", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Assemini", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Ballao", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Barrali", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Burcei", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Cagliari", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Capoterra", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Castiadas", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Decimomannu", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Decimoputzu", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Dolianova", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Domus De Maria", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Donori", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Elmas", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Gesico", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Goni", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Guamaggiore", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Guasila", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Mandas", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Maracalagonis", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Monastir", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Monserrato", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Muravera", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Nuraminis", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Ortacesus", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Pimentel", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Pula", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Quartucciu", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Samatzai", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "San Basilio", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "San Sperate", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "San Vito", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Sarroch", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Selargius", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Selegas", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Serdiana", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Sestu", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Settimo San Pietro", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Siliqua", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Silius", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Sinnai", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Siurgus Donigala", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Soleminis", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Teulada", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Ussana", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Uta", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Vallermosa", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Villa San Pietro", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Villaputzu", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Villasalto", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Villasimius", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Villasor", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Villaspeciosa", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Quartu Sant'Elena", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "San Nicolo' Gerrei", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Sant'Andrea Frius", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Senorbi'", province_id: 78, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
