#encoding: utf-8
Comune.create(:description => "Abbasanta", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Aidomaggiore", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Albagiara", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Ales", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Allai", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Arborea", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Ardauli", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Assolo", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Asuni", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Baradili", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Baratili San Pietro", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Baressa", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Bauladu", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Bonarcado", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Boroneddu", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Busachi", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Cabras", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Cuglieri", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Curcuris", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Fordongianus", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Ghilarza", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Gonnoscodina", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Gonnostramatza", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Marrubiu", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Masullas", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Milis", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Mogorella", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Mogoro", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Morgongiori", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Narbolia", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Neoneli", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Norbello", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Nughedu Santa Vittoria", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Nurachi", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Nureci", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Ollastra Simaxis", :provincia_id => 80, :regione_id => 10)
Comune.create(:description => "Oristano", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Palmas Arborea", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Pau", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Paulilatino", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Pompu", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Riola Sardo", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Ruinas", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Samugheo", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "San Vero Milis", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Santa Giusta", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Santu Lussurgiu", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Scano Di Montiferro", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Sedilo", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Seneghe", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Senis", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Sennariolo", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Siamaggiore", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Siamanna", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Siapiccia", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Simala", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Simaxis", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Sini", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Siris", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Soddi", :provincia_id => 80, :regione_id => 10)
Comune.create(:description => "Solarussa", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Sorradile", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Tadasuni", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Terralba", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Tramatza", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Tresnuraghes", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Uras", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Usellus", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Villa Verde", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Villanova Truschedu", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Villaurbana", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Zeddiani", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Zerfaliu", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Bidoni'", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Gonnosno'", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "San Nicolo' D'Arcidano", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Ula' Tirso", :provincia_id => 80, :regione_id => 10, :population => 0)
Comune.create(:description => "Villa Sant'Antonio", :provincia_id => 80, :regione_id => 10, :population => 0)
