Municipality.create(description: "Abbasanta", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Aidomaggiore", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Albagiara", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Ales", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Allai", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Arborea", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Ardauli", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Assolo", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Asuni", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Baradili", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Baratili San Pietro", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Baressa", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Bauladu", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Bonarcado", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Boroneddu", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Busachi", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Cabras", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Cuglieri", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Curcuris", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Fordongianus", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Ghilarza", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Gonnoscodina", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Gonnostramatza", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Marrubiu", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Masullas", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Milis", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Mogorella", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Mogoro", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Morgongiori", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Narbolia", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Neoneli", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Norbello", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Nughedu Santa Vittoria", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Nurachi", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Nureci", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Ollastra Simaxis", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 )
Municipality.create(description: "Oristano", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Palmas Arborea", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Pau", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Paulilatino", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Pompu", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Riola Sardo", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Ruinas", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Samugheo", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "San Vero Milis", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Santa Giusta", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Santu Lussurgiu", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Scano Di Montiferro", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Sedilo", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Seneghe", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Senis", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Sennariolo", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Siamaggiore", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Siamanna", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Siapiccia", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Simala", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Simaxis", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Sini", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Siris", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Soddi", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 )
Municipality.create(description: "Solarussa", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Sorradile", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Tadasuni", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Terralba", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Tramatza", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Tresnuraghes", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Uras", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Usellus", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Villa Verde", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Villanova Truschedu", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Villaurbana", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Zeddiani", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Zerfaliu", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Bidoni'", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Gonnosno'", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "San Nicolo' D'Arcidano", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Ula' Tirso", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Villa Sant'Antonio", province_id: 80, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
