#encoding: utf-8
Comune.create(:description => "Ailoche", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Andorno Micca", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Benna", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Biella", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Bioglio", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Borriana", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Brusnengo", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Callabiana", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Camandona", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Camburzano", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Campiglia Cervo", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Candelo", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Caprile", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Casapinta", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Castelletto Cervo", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Cerreto Castello", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Cerrione", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Coggiola", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Cossato", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Crevacuore", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Crosa", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Curino", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Donato", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Dorzano", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Gaglianico", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Gifflenga", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Graglia", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Lessona", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Magnano", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Massazza", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Masserano", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Mezzana Mortigliengo", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Miagliano", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Mongrando", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Mosso", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Mottalciata", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Muzzano", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Netro", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Occhieppo Inferiore", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Occhieppo Superiore", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Pettinengo", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Piatto", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Piedicavallo", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Pollone", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Ponderano", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Portula", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Pralungo", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Pray", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Quaregna", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Quittengo", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Ronco Biellese", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Roppolo", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Rosazza", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Sagliano Micca", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Sala Biellese", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Salussola", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "San Paolo Cervo", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Sandigliano", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Selve Marcone", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Soprana", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Sordevolo", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Sostegno", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Strona", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Tavigliano", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Ternengo", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Tollegno", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Torrazzo", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Trivero", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Valdengo", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Vallanzengo", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Valle Mosso", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Valle San Nicolao", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Veglio", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Verrone", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Vigliano Biellese", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Villa Del Bosco", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Villanova Biellese", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Viverone", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Zimone", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Zubiena", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Zumaglia", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
Comune.create(:description => "Cavaglia'", :provincia_id => 7, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 0)
