Comune.create(description: "Ailoche", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Andorno Micca", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Benna", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Biella", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Bioglio", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Borriana", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Brusnengo", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Callabiana", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Camandona", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Camburzano", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Campiglia Cervo", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Candelo", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Caprile", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Casapinta", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Castelletto Cervo", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Cerreto Castello", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Cerrione", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Coggiola", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Cossato", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Crevacuore", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Crosa", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Curino", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Donato", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Dorzano", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Gaglianico", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Gifflenga", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Graglia", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Lessona", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Magnano", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Massazza", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Masserano", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Mezzana Mortigliengo", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Miagliano", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Mongrando", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Mosso", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Mottalciata", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Muzzano", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Netro", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Occhieppo Inferiore", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Occhieppo Superiore", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Pettinengo", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Piatto", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Piedicavallo", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Pollone", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Ponderano", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Portula", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Pralungo", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Pray", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Quaregna", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Quittengo", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Ronco Biellese", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Roppolo", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Rosazza", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Sagliano Micca", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Sala Biellese", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Salussola", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "San Paolo Cervo", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Sandigliano", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Selve Marcone", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Soprana", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Sordevolo", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Sostegno", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Strona", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Tavigliano", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Ternengo", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Tollegno", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Torrazzo", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Trivero", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Valdengo", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Vallanzengo", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Valle Mosso", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Valle San Nicolao", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Veglio", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Verrone", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Vigliano Biellese", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Villa Del Bosco", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Villanova Biellese", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Viverone", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Zimone", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Zubiena", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Zumaglia", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Cavaglia'", province_id: 7, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
