#encoding: utf-8
Comune.create(description: "Alghero", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Anela", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Ardara", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Banari", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Benetutti", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Bessude", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Bonnanaro", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Bono", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Bonorva", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Borutta", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Bottidda", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Bultei", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 1439)
Comune.create(description: "Bulzi", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Burgos", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 1461)
Comune.create(description: "Cargeghe", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 570)
Comune.create(description: "Castelsardo", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 634)
Comune.create(description: "Cheremule", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Chiaramonti", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 12842)
Comune.create(description: "Codrongianos", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 )
Comune.create(description: "Cossoine", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 2488)
Comune.create(description: "Erula", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Esporlatu", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Florinas", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 3007)
Comune.create(description: "Giave", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 21064)
Comune.create(description: "Illorai", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Ittireddu", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 7365)
Comune.create(description: "Ittiri", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 3498)
Comune.create(description: "Laerru", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Mara", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 807)
Comune.create(description: "Martis", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 1665)
Comune.create(description: "Monteleone Rocca Doria", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Mores", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 1915)
Comune.create(description: "Muros", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Nule", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 4816)
Comune.create(description: "Nulvi", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Olmedo", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 754)
Comune.create(description: "Osilo", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Ossi", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 1281)
Comune.create(description: "Ozieri", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 2212)
Comune.create(description: "Padria", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 5735)
Comune.create(description: "Pattada", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 1875)
Comune.create(description: "Perfugas", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 3050)
Comune.create(description: "Ploaghe", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 2852)
Comune.create(description: "Porto Torres", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Pozzomaggiore", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 3513)
Comune.create(description: "Putifigari", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Romana", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 1574)
Comune.create(description: "Santa Maria Coghinas", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 38404)
Comune.create(description: "Sassari", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 9050)
Comune.create(description: "Sedini", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 1012)
Comune.create(description: "Semestene", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 701)
Comune.create(description: "Sennori", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 2074)
Comune.create(description: "Siligo", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 677)
Comune.create(description: "Sorso", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Stintino", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Tergu", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 134)
Comune.create(description: "Thiesi", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 2345)
Comune.create(description: "Tissi", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 1127)
Comune.create(description: "Torralba", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 586)
Comune.create(description: "Tula", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Uri", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 3165)
Comune.create(description: "Usini", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 318)
Comune.create(description: "Valledoria", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 1206)
Comune.create(description: "Viddalba", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 1573)
Comune.create(description: "Villanova Monteleone", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Nughedu Di San Nicolo'", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 )
Comune.create(description: "Castel San Niccolo'", provincia_id: 81, regione_id: 10, country_id: 1, continente_id: 1 , population: 2855)
