Comune.create(description: "Alghero", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Anela", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Ardara", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Banari", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Benetutti", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Bessude", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Bonnanaro", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Bono", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Bonorva", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Borutta", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Bottidda", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Bultei", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 1439)
Comune.create(description: "Bulzi", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Burgos", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 1461)
Comune.create(description: "Cargeghe", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 570)
Comune.create(description: "Castelsardo", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 634)
Comune.create(description: "Cheremule", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Chiaramonti", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 12842)
Comune.create(description: "Codrongianos", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 )
Comune.create(description: "Cossoine", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 2488)
Comune.create(description: "Erula", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Esporlatu", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Florinas", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 3007)
Comune.create(description: "Giave", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 21064)
Comune.create(description: "Illorai", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Ittireddu", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 7365)
Comune.create(description: "Ittiri", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 3498)
Comune.create(description: "Laerru", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Mara", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 807)
Comune.create(description: "Martis", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 1665)
Comune.create(description: "Monteleone Rocca Doria", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Mores", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 1915)
Comune.create(description: "Muros", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Nule", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 4816)
Comune.create(description: "Nulvi", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Olmedo", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 754)
Comune.create(description: "Osilo", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Ossi", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 1281)
Comune.create(description: "Ozieri", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 2212)
Comune.create(description: "Padria", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 5735)
Comune.create(description: "Pattada", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 1875)
Comune.create(description: "Perfugas", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 3050)
Comune.create(description: "Ploaghe", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 2852)
Comune.create(description: "Porto Torres", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Pozzomaggiore", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 3513)
Comune.create(description: "Putifigari", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Romana", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 1574)
Comune.create(description: "Santa Maria Coghinas", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 38404)
Comune.create(description: "Sassari", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 9050)
Comune.create(description: "Sedini", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 1012)
Comune.create(description: "Semestene", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 701)
Comune.create(description: "Sennori", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 2074)
Comune.create(description: "Siligo", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 677)
Comune.create(description: "Sorso", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Stintino", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Tergu", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 134)
Comune.create(description: "Thiesi", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 2345)
Comune.create(description: "Tissi", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 1127)
Comune.create(description: "Torralba", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 586)
Comune.create(description: "Tula", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Uri", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 3165)
Comune.create(description: "Usini", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 318)
Comune.create(description: "Valledoria", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 1206)
Comune.create(description: "Viddalba", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 1573)
Comune.create(description: "Villanova Monteleone", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Nughedu Di San Nicolo'", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 )
Comune.create(description: "Castel San Niccolo'", province_id: 81, region_id:  10, country_id: 1, continent_id: 1 , population: 2855)
