Municipality.create(description: "Aquila Di Arroscia", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 )
Municipality.create(description: "Airole", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 456)
Municipality.create(description: "Apricale", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 578)
Municipality.create(description: "Aurigo", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 346)
Municipality.create(description: "Badalucco", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 1264)
Municipality.create(description: "Baiardo", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 278)
Municipality.create(description: "Bordighera", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 10292)
Municipality.create(description: "Borgomaro", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 842)
Municipality.create(description: "Camporosso", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 5061)
Municipality.create(description: "Caravonica", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 309)
Municipality.create(description: "Carpasio", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 185)
Municipality.create(description: "Castel Vittorio", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 397)
Municipality.create(description: "Castellaro", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 1044)
Municipality.create(description: "Ceriana", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 1305)
Municipality.create(description: "Cervo", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 1195)
Municipality.create(description: "Cesio", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 241)
Municipality.create(description: "Chiusanico", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 612)
Municipality.create(description: "Chiusavecchia", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 476)
Municipality.create(description: "Cipressa", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 1157)
Municipality.create(description: "Civezza", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 536)
Municipality.create(description: "Cosio Di Arroscia", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 )
Municipality.create(description: "Costarainera", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 718)
Municipality.create(description: "Diano Arentino", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 606)
Municipality.create(description: "Diano Castello", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 1885)
Municipality.create(description: "Diano Marina", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 6159)
Municipality.create(description: "Diano San Pietro", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 1022)
Municipality.create(description: "Dolceacqua", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 1901)
Municipality.create(description: "Dolcedo", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 1193)
Municipality.create(description: "Imperia", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 39458)
Municipality.create(description: "Isolabona", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 643)
Municipality.create(description: "Lucinasco", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 274)
Municipality.create(description: "Mendatica", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 245)
Municipality.create(description: "Molini Di Triora", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 695)
Municipality.create(description: "Montalto Ligure", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 388)
Municipality.create(description: "Montegrosso Pian Latte", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 140)
Municipality.create(description: "Olivetta San Michele", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 238)
Municipality.create(description: "Ospedaletti", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 3351)
Municipality.create(description: "Perinaldo", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 873)
Municipality.create(description: "Pietrabruna", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 560)
Municipality.create(description: "Pieve Di Teco", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 1336)
Municipality.create(description: "Pigna", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 935)
Municipality.create(description: "Pompeiana", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 831)
Municipality.create(description: "Pontedassio", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 2002)
Municipality.create(description: "Pornassio", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 651)
Municipality.create(description: "Rezzo", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 393)
Municipality.create(description: "Riva Ligure", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 2747)
Municipality.create(description: "Rocchetta Nervina", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 259)
Municipality.create(description: "San Bartolomeo Al Mare", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 2964)
Municipality.create(description: "San Biagio Della Cima", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 1175)
Municipality.create(description: "San Lorenzo Al Mare", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 1402)
Municipality.create(description: "San Remo", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 50608)
Municipality.create(description: "Santo Stefano Al Mare", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 2073)
Municipality.create(description: "Seborga", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 340)
Municipality.create(description: "Soldano", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 837)
Municipality.create(description: "Taggia", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 12908)
Municipality.create(description: "Terzorio", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 214)
Municipality.create(description: "Triora", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 408)
Municipality.create(description: "Vallebona", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 1087)
Municipality.create(description: "Vallecrosia", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 7182)
Municipality.create(description: "Vasia", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 440)
Municipality.create(description: "Ventimiglia", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 24665)
Municipality.create(description: "Vessalico", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 297)
Municipality.create(description: "Villa Faraldi", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 435)
Municipality.create(description: "Borghetto D'Arroscia", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 494)
Municipality.create(description: "Prela'", province_id: 83, region_id:  18, country_id: 1, continent_id: 1 , population: 480)
