Comune.create(description: "Alassio", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 10449)
Comune.create(description: "Albenga", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 22690)
Comune.create(description: "Albisola Marina", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 )
Comune.create(description: "Albisola Superiore", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 10921)
Comune.create(description: "Altare", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 2211)
Comune.create(description: "Andora", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 6767)
Comune.create(description: "Arnasco", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 563)
Comune.create(description: "Balestrino", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 535)
Comune.create(description: "Bardineto", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 634)
Comune.create(description: "Bergeggi", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 1147)
Comune.create(description: "Boissano", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 2061)
Comune.create(description: "Borghetto Santo Spirito", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 5075)
Comune.create(description: "Borgio Verezzi", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 2095)
Comune.create(description: "Bormida", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 453)
Comune.create(description: "Cairo Montenotte", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 13419)
Comune.create(description: "Calice Ligure", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 1461)
Comune.create(description: "Calizzano", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 1583)
Comune.create(description: "Carcare", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 5662)
Comune.create(description: "Casanova Lerrone", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 766)
Comune.create(description: "Castelbianco", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 287)
Comune.create(description: "Castelvecchio Di Rocca Barbena", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 194)
Comune.create(description: "Celle Ligure", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 5307)
Comune.create(description: "Cengio", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 3777)
Comune.create(description: "Ceriale", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 5277)
Comune.create(description: "Cisano Sul Neva", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 1568)
Comune.create(description: "Cosseria", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 1034)
Comune.create(description: "Dego", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 1948)
Comune.create(description: "Erli", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 244)
Comune.create(description: "Finale Ligure", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 11845)
Comune.create(description: "Garlenda", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 957)
Comune.create(description: "Giustenice", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 895)
Comune.create(description: "Giusvalla", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 425)
Comune.create(description: "Laigueglia", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 2173)
Comune.create(description: "Loano", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 10567)
Comune.create(description: "Magliolo", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 709)
Comune.create(description: "Mallare", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 1293)
Comune.create(description: "Massimino", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 130)
Comune.create(description: "Millesimo", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 3250)
Comune.create(description: "Mioglia", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 561)
Comune.create(description: "Murialdo", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 871)
Comune.create(description: "Nasino", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 224)
Comune.create(description: "Noli", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 2946)
Comune.create(description: "Onzo", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 223)
Comune.create(description: "Orco Feglino", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 814)
Comune.create(description: "Ortovero", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 1090)
Comune.create(description: "Osiglia", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 470)
Comune.create(description: "Pallare", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 934)
Comune.create(description: "Piana Crixia", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 816)
Comune.create(description: "Pietra Ligure", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 8591)
Comune.create(description: "Plodio", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 550)
Comune.create(description: "Pontinvrea", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 822)
Comune.create(description: "Quiliano", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 7032)
Comune.create(description: "Rialto", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 542)
Comune.create(description: "Roccavignale", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 710)
Comune.create(description: "Sassello", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 1765)
Comune.create(description: "Savona", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 59907)
Comune.create(description: "Spotorno", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 3803)
Comune.create(description: "Stella", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 2935)
Comune.create(description: "Stellanello", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 754)
Comune.create(description: "Testico", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 200)
Comune.create(description: "Toirano", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 2089)
Comune.create(description: "Tovo San Giacomo", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 2165)
Comune.create(description: "Urbe", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 869)
Comune.create(description: "Vado Ligure", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 7991)
Comune.create(description: "Varazze", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 13458)
Comune.create(description: "Vendone", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 431)
Comune.create(description: "Vezzi Portio", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 690)
Comune.create(description: "Zuccarello", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 289)
Comune.create(description: "Villanova D'Albenga", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 1991)
