Municipality.create(description: "Alassio", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 10449)
Municipality.create(description: "Albenga", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 22690)
Municipality.create(description: "Albisola Marina", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 )
Municipality.create(description: "Albisola Superiore", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 10921)
Municipality.create(description: "Altare", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 2211)
Municipality.create(description: "Andora", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 6767)
Municipality.create(description: "Arnasco", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 563)
Municipality.create(description: "Balestrino", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 535)
Municipality.create(description: "Bardineto", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 634)
Municipality.create(description: "Bergeggi", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 1147)
Municipality.create(description: "Boissano", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 2061)
Municipality.create(description: "Borghetto Santo Spirito", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 5075)
Municipality.create(description: "Borgio Verezzi", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 2095)
Municipality.create(description: "Bormida", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 453)
Municipality.create(description: "Cairo Montenotte", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 13419)
Municipality.create(description: "Calice Ligure", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 1461)
Municipality.create(description: "Calizzano", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 1583)
Municipality.create(description: "Carcare", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 5662)
Municipality.create(description: "Casanova Lerrone", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 766)
Municipality.create(description: "Castelbianco", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 287)
Municipality.create(description: "Castelvecchio Di Rocca Barbena", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 194)
Municipality.create(description: "Celle Ligure", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 5307)
Municipality.create(description: "Cengio", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 3777)
Municipality.create(description: "Ceriale", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 5277)
Municipality.create(description: "Cisano Sul Neva", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 1568)
Municipality.create(description: "Cosseria", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 1034)
Municipality.create(description: "Dego", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 1948)
Municipality.create(description: "Erli", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 244)
Municipality.create(description: "Finale Ligure", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 11845)
Municipality.create(description: "Garlenda", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 957)
Municipality.create(description: "Giustenice", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 895)
Municipality.create(description: "Giusvalla", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 425)
Municipality.create(description: "Laigueglia", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 2173)
Municipality.create(description: "Loano", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 10567)
Municipality.create(description: "Magliolo", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 709)
Municipality.create(description: "Mallare", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 1293)
Municipality.create(description: "Massimino", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 130)
Municipality.create(description: "Millesimo", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 3250)
Municipality.create(description: "Mioglia", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 561)
Municipality.create(description: "Murialdo", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 871)
Municipality.create(description: "Nasino", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 224)
Municipality.create(description: "Noli", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 2946)
Municipality.create(description: "Onzo", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 223)
Municipality.create(description: "Orco Feglino", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 814)
Municipality.create(description: "Ortovero", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 1090)
Municipality.create(description: "Osiglia", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 470)
Municipality.create(description: "Pallare", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 934)
Municipality.create(description: "Piana Crixia", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 816)
Municipality.create(description: "Pietra Ligure", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 8591)
Municipality.create(description: "Plodio", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 550)
Municipality.create(description: "Pontinvrea", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 822)
Municipality.create(description: "Quiliano", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 7032)
Municipality.create(description: "Rialto", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 542)
Municipality.create(description: "Roccavignale", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 710)
Municipality.create(description: "Sassello", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 1765)
Municipality.create(description: "Savona", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 59907)
Municipality.create(description: "Spotorno", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 3803)
Municipality.create(description: "Stella", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 2935)
Municipality.create(description: "Stellanello", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 754)
Municipality.create(description: "Testico", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 200)
Municipality.create(description: "Toirano", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 2089)
Municipality.create(description: "Tovo San Giacomo", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 2165)
Municipality.create(description: "Urbe", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 869)
Municipality.create(description: "Vado Ligure", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 7991)
Municipality.create(description: "Varazze", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 13458)
Municipality.create(description: "Vendone", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 431)
Municipality.create(description: "Vezzi Portio", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 690)
Municipality.create(description: "Zuccarello", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 289)
Municipality.create(description: "Villanova D'Albenga", province_id: 84, region_id:  18, country_id: 1, continent_id: 1 , population: 1991)
