Municipality.create(description: "Ameglia", province_id: 85, region_id:  18, country_id: 1, continent_id: 1 , population: 4520)
Municipality.create(description: "Arcola", province_id: 85, region_id:  18, country_id: 1, continent_id: 1 , population: 9914)
Municipality.create(description: "Beverino", province_id: 85, region_id:  18, country_id: 1, continent_id: 1 , population: 2233)
Municipality.create(description: "Bolano", province_id: 85, region_id:  18, country_id: 1, continent_id: 1 , population: 7391)
Municipality.create(description: "Bonassola", province_id: 85, region_id:  18, country_id: 1, continent_id: 1 , population: 974)
Municipality.create(description: "Borghetto Di Vara", province_id: 85, region_id:  18, country_id: 1, continent_id: 1 , population: 1005)
Municipality.create(description: "Brugnato", province_id: 85, region_id:  18, country_id: 1, continent_id: 1 , population: 1191)
Municipality.create(description: "Calice Al Cornoviglio", province_id: 85, region_id:  18, country_id: 1, continent_id: 1 , population: 1173)
Municipality.create(description: "Carro", province_id: 85, region_id:  18, country_id: 1, continent_id: 1 , population: 635)
Municipality.create(description: "Carrodano", province_id: 85, region_id:  18, country_id: 1, continent_id: 1 , population: 545)
Municipality.create(description: "Castelnuovo Magra", province_id: 85, region_id:  18, country_id: 1, continent_id: 1 , population: 7935)
Municipality.create(description: "Deiva Marina", province_id: 85, region_id:  18, country_id: 1, continent_id: 1 , population: 1463)
Municipality.create(description: "Follo", province_id: 85, region_id:  18, country_id: 1, continent_id: 1 , population: 5579)
Municipality.create(description: "Framura", province_id: 85, region_id:  18, country_id: 1, continent_id: 1 , population: 744)
Municipality.create(description: "La Spezia", province_id: 85, region_id:  18, country_id: 1, continent_id: 1 , population: 91391)
Municipality.create(description: "Lerici", province_id: 85, region_id:  18, country_id: 1, continent_id: 1 , population: 10900)
Municipality.create(description: "Levanto", province_id: 85, region_id:  18, country_id: 1, continent_id: 1 , population: 5641)
Municipality.create(description: "Maissana", province_id: 85, region_id:  18, country_id: 1, continent_id: 1 , population: 669)
Municipality.create(description: "Monterosso Al Mare", province_id: 85, region_id:  18, country_id: 1, continent_id: 1 , population: 1571)
Municipality.create(description: "Ortonovo", province_id: 85, region_id:  18, country_id: 1, continent_id: 1 , population: 8348)
Municipality.create(description: "Pignone", province_id: 85, region_id:  18, country_id: 1, continent_id: 1 , population: 650)
Municipality.create(description: "Portovenere", province_id: 85, region_id:  18, country_id: 1, continent_id: 1 , population: 4097)
Municipality.create(description: "Riomaggiore", province_id: 85, region_id:  18, country_id: 1, continent_id: 1 , population: 1809)
Municipality.create(description: "Rocchetta Di Vara", province_id: 85, region_id:  18, country_id: 1, continent_id: 1 , population: 852)
Municipality.create(description: "Santo Stefano Di Magra", province_id: 85, region_id:  18, country_id: 1, continent_id: 1 , population: 8344)
Municipality.create(description: "Sarzana", province_id: 85, region_id:  18, country_id: 1, continent_id: 1 , population: 20059)
Municipality.create(description: "Sesta Godano", province_id: 85, region_id:  18, country_id: 1, continent_id: 1 , population: 1554)
Municipality.create(description: "Varese Ligure", province_id: 85, region_id:  18, country_id: 1, continent_id: 1 , population: 2358)
Municipality.create(description: "Vernazza", province_id: 85, region_id:  18, country_id: 1, continent_id: 1 , population: 1084)
Municipality.create(description: "Vezzano Ligure", province_id: 85, region_id:  18, country_id: 1, continent_id: 1 , population: 7424)
Municipality.create(description: "Zignago", province_id: 85, region_id:  18, country_id: 1, continent_id: 1 , population: 515)
Municipality.create(description: "Ricco' Del Golfo Di Spezia", province_id: 85, region_id:  18, country_id: 1, continent_id: 1 , population: 3367)
