Comune.create(description: "Agnone", provincia_id: 86, regione_id: 4, country_id: 1, continent_id: 1 , population: 5842)
Comune.create(description: "Bagnoli Del Trigno", provincia_id: 86, regione_id: 4, country_id: 1, continent_id: 1 , population: 877)
Comune.create(description: "Belmonte Del Sannio", provincia_id: 86, regione_id: 4, country_id: 1, continent_id: 1 , population: 921)
Comune.create(description: "Cantalupo Nel Sannio", provincia_id: 86, regione_id: 4, country_id: 1, continent_id: 1 , population: 736)
Comune.create(description: "Capracotta", provincia_id: 86, regione_id: 4, country_id: 1, continent_id: 1 , population: 1122)
Comune.create(description: "Carovilli", provincia_id: 86, regione_id: 4, country_id: 1, continent_id: 1 , population: 1528)
Comune.create(description: "Carpinone", provincia_id: 86, regione_id: 4, country_id: 1, continent_id: 1 , population: 1254)
Comune.create(description: "Castel Del Giudice", provincia_id: 86, regione_id: 4, country_id: 1, continent_id: 1 , population: 353)
Comune.create(description: "Castel San Vincenzo", provincia_id: 86, regione_id: 4, country_id: 1, continent_id: 1 , population: 577)
Comune.create(description: "Castelpetroso", provincia_id: 86, regione_id: 4, country_id: 1, continent_id: 1 , population: 1644)
Comune.create(description: "Castelpizzuto", provincia_id: 86, regione_id: 4, country_id: 1, continent_id: 1 , population: 143)
Comune.create(description: "Castelverrino", provincia_id: 86, regione_id: 4, country_id: 1, continent_id: 1 , population: 130)
Comune.create(description: "Cerro Al Volturno", provincia_id: 86, regione_id: 4, country_id: 1, continent_id: 1 , population: 1440)
Comune.create(description: "Chiauci", provincia_id: 86, regione_id: 4, country_id: 1, continent_id: 1 , population: 277)
Comune.create(description: "Civitanova Del Sannio", provincia_id: 86, regione_id: 4, country_id: 1, continent_id: 1 , population: 949)
Comune.create(description: "Colli A Volturno", provincia_id: 86, regione_id: 4, country_id: 1, continent_id: 1 , population: 1407)
Comune.create(description: "Conca Casale", provincia_id: 86, regione_id: 4, country_id: 1, continent_id: 1 , population: 269)
Comune.create(description: "Filignano", provincia_id: 86, regione_id: 4, country_id: 1, continent_id: 1 , population: 756)
Comune.create(description: "Fornelli", provincia_id: 86, regione_id: 4, country_id: 1, continent_id: 1 , population: 1985)
Comune.create(description: "Frosolone", provincia_id: 86, regione_id: 4, country_id: 1, continent_id: 1 , population: 3405)
Comune.create(description: "Isernia", provincia_id: 86, regione_id: 4, country_id: 1, continent_id: 1 , population: 21152)
Comune.create(description: "Longano", provincia_id: 86, regione_id: 4, country_id: 1, continent_id: 1 , population: 725)
Comune.create(description: "Macchiagodena", provincia_id: 86, regione_id: 4, country_id: 1, continent_id: 1 , population: 1959)
Comune.create(description: "Miranda", provincia_id: 86, regione_id: 4, country_id: 1, continent_id: 1 , population: 1083)
Comune.create(description: "Montaquila", provincia_id: 86, regione_id: 4, country_id: 1, continent_id: 1 , population: 2474)
Comune.create(description: "Montenero Val Cocchiara", provincia_id: 86, regione_id: 4, country_id: 1, continent_id: 1 , population: 608)
Comune.create(description: "Monteroduni", provincia_id: 86, regione_id: 4, country_id: 1, continent_id: 1 , population: 2395)
Comune.create(description: "Pesche", provincia_id: 86, regione_id: 4, country_id: 1, continent_id: 1 , population: 1312)
Comune.create(description: "Pescolanciano", provincia_id: 86, regione_id: 4, country_id: 1, continent_id: 1 , population: 1002)
Comune.create(description: "Pescopennataro", provincia_id: 86, regione_id: 4, country_id: 1, continent_id: 1 , population: 387)
Comune.create(description: "Pettoranello Del Molise", provincia_id: 86, regione_id: 4, country_id: 1, continent_id: 1 , population: 428)
Comune.create(description: "Pietrabbondante", provincia_id: 86, regione_id: 4, country_id: 1, continent_id: 1 , population: 961)
Comune.create(description: "Pizzone", provincia_id: 86, regione_id: 4, country_id: 1, continent_id: 1 , population: 328)
Comune.create(description: "Poggio Sannita", provincia_id: 86, regione_id: 4, country_id: 1, continent_id: 1 , population: 940)
Comune.create(description: "Pozzilli", provincia_id: 86, regione_id: 4, country_id: 1, continent_id: 1 , population: 2201)
Comune.create(description: "Rionero Sannitico", provincia_id: 86, regione_id: 4, country_id: 1, continent_id: 1 , population: 1131)
Comune.create(description: "Roccamandolfi", provincia_id: 86, regione_id: 4, country_id: 1, continent_id: 1 , population: 1073)
Comune.create(description: "Roccasicura", provincia_id: 86, regione_id: 4, country_id: 1, continent_id: 1 , population: 627)
Comune.create(description: "Rocchetta A Volturno", provincia_id: 86, regione_id: 4, country_id: 1, continent_id: 1 , population: 1083)
Comune.create(description: "San Pietro Avellana", provincia_id: 86, regione_id: 4, country_id: 1, continent_id: 1 , population: 662)
Comune.create(description: "Santa Maria Del Molise", provincia_id: 86, regione_id: 4, country_id: 1, continent_id: 1 , population: 654)
Comune.create(description: "Scapoli", provincia_id: 86, regione_id: 4, country_id: 1, continent_id: 1 , population: 949)
Comune.create(description: "Sessano Del Molise", provincia_id: 86, regione_id: 4, country_id: 1, continent_id: 1 , population: 927)
Comune.create(description: "Sesto Campano", provincia_id: 86, regione_id: 4, country_id: 1, continent_id: 1 , population: 2945)
Comune.create(description: "Vastogirardi", provincia_id: 86, regione_id: 4, country_id: 1, continent_id: 1 , population: 798)
Comune.create(description: "Venafro", provincia_id: 86, regione_id: 4, country_id: 1, continent_id: 1 , population: 11198)
Comune.create(description: "Acquaviva D'Isernia", provincia_id: 86, regione_id: 4, country_id: 1, continent_id: 1 , population: 468)
Comune.create(description: "Forli' Del Sannio", provincia_id: 86, regione_id: 4, country_id: 1, continent_id: 1 , population: 833)
Comune.create(description: "Macchia D'Isernia", provincia_id: 86, regione_id: 4, country_id: 1, continent_id: 1 , population: 909)
Comune.create(description: "Sant'Agapito", provincia_id: 86, regione_id: 4, country_id: 1, continent_id: 1 , population: 1332)
Comune.create(description: "Sant'Angelo Del Pesco", provincia_id: 86, regione_id: 4, country_id: 1, continent_id: 1 , population: 416)
Comune.create(description: "Sant'Elena Sannita", provincia_id: 86, regione_id: 4, country_id: 1, continent_id: 1 , population: 277)
