Comune.create(description: "Acquaviva Collecroce", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 800)
Comune.create(description: "Baranello", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 2653)
Comune.create(description: "Bojano", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 )
Comune.create(description: "Bonefro", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 1873)
Comune.create(description: "Busso", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 1412)
Comune.create(description: "Campobasso", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 50762)
Comune.create(description: "Campochiaro", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 634)
Comune.create(description: "Campodipietra", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 2061)
Comune.create(description: "Campolieto", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 1062)
Comune.create(description: "Campomarino", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 6310)
Comune.create(description: "Casacalenda", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 2440)
Comune.create(description: "Casalciprano", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 635)
Comune.create(description: "Castelbottaccio", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 422)
Comune.create(description: "Castellino Del Biferno", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 673)
Comune.create(description: "Castelmauro", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 1902)
Comune.create(description: "Castropignano", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 1147)
Comune.create(description: "Cercemaggiore", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 4272)
Comune.create(description: "Cercepiccola", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 727)
Comune.create(description: "Civitacampomarano", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 676)
Comune.create(description: "Colletorto", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 2474)
Comune.create(description: "Duronia", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 507)
Comune.create(description: "Ferrazzano", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 3165)
Comune.create(description: "Fossalto", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 1619)
Comune.create(description: "Gambatesa", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 1737)
Comune.create(description: "Gildone", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 859)
Comune.create(description: "Guardialfiera", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 1171)
Comune.create(description: "Guardiaregia", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 783)
Comune.create(description: "Guglionesi", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 5156)
Comune.create(description: "Jelsi", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 1917)
Comune.create(description: "Larino", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 7078)
Comune.create(description: "Limosano", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 926)
Comune.create(description: "Lucito", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 959)
Comune.create(description: "Lupara", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 651)
Comune.create(description: "Macchia Valfortore", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 757)
Comune.create(description: "Mafalda", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 1340)
Comune.create(description: "Matrice", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 1067)
Comune.create(description: "Mirabello Sannitico", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 1812)
Comune.create(description: "Molise", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 186)
Comune.create(description: "Monacilioni", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 680)
Comune.create(description: "Montagano", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 1248)
Comune.create(description: "Montecilfone", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 1588)
Comune.create(description: "Montefalcone Nel Sannio", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 1866)
Comune.create(description: "Montelongo", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 490)
Comune.create(description: "Montemitro", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 468)
Comune.create(description: "Montenero Di Bisaccia", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 6698)
Comune.create(description: "Montorio Nei Frentani", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 562)
Comune.create(description: "Morrone Del Sannio", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 757)
Comune.create(description: "Oratino", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 1289)
Comune.create(description: "Palata", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 1940)
Comune.create(description: "Petacciato", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 3406)
Comune.create(description: "Petrella Tifernina", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 1305)
Comune.create(description: "Pietracatella", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 1600)
Comune.create(description: "Pietracupa", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 259)
Comune.create(description: "Portocannone", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 2544)
Comune.create(description: "Provvidenti", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 166)
Comune.create(description: "Riccia", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 5701)
Comune.create(description: "Ripabottoni", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 673)
Comune.create(description: "Ripalimosani", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 2588)
Comune.create(description: "Roccavivara", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 954)
Comune.create(description: "Rotello", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 1309)
Comune.create(description: "Salcito", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 620)
Comune.create(description: "San Biase", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 271)
Comune.create(description: "San Felice Del Molise", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 813)
Comune.create(description: "San Giacomo Degli Schiavoni", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 1111)
Comune.create(description: "San Giovanni In Galdo", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 669)
Comune.create(description: "San Giuliano Del Sannio", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 1076)
Comune.create(description: "San Giuliano Di Puglia", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 1163)
Comune.create(description: "San Martino In Pensilis", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 4824)
Comune.create(description: "San Massimo", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 723)
Comune.create(description: "San Polo Matese", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 445)
Comune.create(description: "Santa Croce Di Magliano", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 4935)
Comune.create(description: "Sepino", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 2177)
Comune.create(description: "Spinete", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 1432)
Comune.create(description: "Tavenna", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 995)
Comune.create(description: "Termoli", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 30255)
Comune.create(description: "Torella Del Sannio", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 897)
Comune.create(description: "Toro", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 1538)
Comune.create(description: "Trivento", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 5313)
Comune.create(description: "Tufara", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 1120)
Comune.create(description: "Ururi", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 3070)
Comune.create(description: "Vinchiaturo", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 2780)
Comune.create(description: "Colle D'Anchise", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 818)
Comune.create(description: "Sant'Angelo Limosano", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 397)
Comune.create(description: "Sant'Elia A Pianisi", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 2279)
