Municipality.create(description: "Acquaviva Collecroce", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 800)
Municipality.create(description: "Baranello", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 2653)
Municipality.create(description: "Bojano", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 )
Municipality.create(description: "Bonefro", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 1873)
Municipality.create(description: "Busso", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 1412)
Municipality.create(description: "Campobasso", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 50762)
Municipality.create(description: "Campochiaro", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 634)
Municipality.create(description: "Campodipietra", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 2061)
Municipality.create(description: "Campolieto", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 1062)
Municipality.create(description: "Campomarino", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 6310)
Municipality.create(description: "Casacalenda", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 2440)
Municipality.create(description: "Casalciprano", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 635)
Municipality.create(description: "Castelbottaccio", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 422)
Municipality.create(description: "Castellino Del Biferno", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 673)
Municipality.create(description: "Castelmauro", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 1902)
Municipality.create(description: "Castropignano", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 1147)
Municipality.create(description: "Cercemaggiore", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 4272)
Municipality.create(description: "Cercepiccola", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 727)
Municipality.create(description: "Civitacampomarano", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 676)
Municipality.create(description: "Colletorto", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 2474)
Municipality.create(description: "Duronia", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 507)
Municipality.create(description: "Ferrazzano", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 3165)
Municipality.create(description: "Fossalto", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 1619)
Municipality.create(description: "Gambatesa", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 1737)
Municipality.create(description: "Gildone", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 859)
Municipality.create(description: "Guardialfiera", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 1171)
Municipality.create(description: "Guardiaregia", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 783)
Municipality.create(description: "Guglionesi", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 5156)
Municipality.create(description: "Jelsi", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 1917)
Municipality.create(description: "Larino", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 7078)
Municipality.create(description: "Limosano", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 926)
Municipality.create(description: "Lucito", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 959)
Municipality.create(description: "Lupara", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 651)
Municipality.create(description: "Macchia Valfortore", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 757)
Municipality.create(description: "Mafalda", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 1340)
Municipality.create(description: "Matrice", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 1067)
Municipality.create(description: "Mirabello Sannitico", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 1812)
Municipality.create(description: "Molise", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 186)
Municipality.create(description: "Monacilioni", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 680)
Municipality.create(description: "Montagano", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 1248)
Municipality.create(description: "Montecilfone", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 1588)
Municipality.create(description: "Montefalcone Nel Sannio", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 1866)
Municipality.create(description: "Montelongo", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 490)
Municipality.create(description: "Montemitro", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 468)
Municipality.create(description: "Montenero Di Bisaccia", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 6698)
Municipality.create(description: "Montorio Nei Frentani", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 562)
Municipality.create(description: "Morrone Del Sannio", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 757)
Municipality.create(description: "Oratino", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 1289)
Municipality.create(description: "Palata", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 1940)
Municipality.create(description: "Petacciato", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 3406)
Municipality.create(description: "Petrella Tifernina", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 1305)
Municipality.create(description: "Pietracatella", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 1600)
Municipality.create(description: "Pietracupa", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 259)
Municipality.create(description: "Portocannone", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 2544)
Municipality.create(description: "Provvidenti", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 166)
Municipality.create(description: "Riccia", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 5701)
Municipality.create(description: "Ripabottoni", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 673)
Municipality.create(description: "Ripalimosani", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 2588)
Municipality.create(description: "Roccavivara", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 954)
Municipality.create(description: "Rotello", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 1309)
Municipality.create(description: "Salcito", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 620)
Municipality.create(description: "San Biase", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 271)
Municipality.create(description: "San Felice Del Molise", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 813)
Municipality.create(description: "San Giacomo Degli Schiavoni", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 1111)
Municipality.create(description: "San Giovanni In Galdo", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 669)
Municipality.create(description: "San Giuliano Del Sannio", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 1076)
Municipality.create(description: "San Giuliano Di Puglia", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 1163)
Municipality.create(description: "San Martino In Pensilis", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 4824)
Municipality.create(description: "San Massimo", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 723)
Municipality.create(description: "San Polo Matese", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 445)
Municipality.create(description: "Santa Croce Di Magliano", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 4935)
Municipality.create(description: "Sepino", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 2177)
Municipality.create(description: "Spinete", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 1432)
Municipality.create(description: "Tavenna", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 995)
Municipality.create(description: "Termoli", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 30255)
Municipality.create(description: "Torella Del Sannio", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 897)
Municipality.create(description: "Toro", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 1538)
Municipality.create(description: "Trivento", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 5313)
Municipality.create(description: "Tufara", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 1120)
Municipality.create(description: "Ururi", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 3070)
Municipality.create(description: "Vinchiaturo", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 2780)
Municipality.create(description: "Colle D'Anchise", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 818)
Municipality.create(description: "Sant'Angelo Limosano", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 397)
Municipality.create(description: "Sant'Elia A Pianisi", province_id: 87, region_id:  4, country_id: 1, continent_id: 1 , population: 2279)
