#encoding: utf-8
Comune.create(description: "Assisi", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 25304)
Comune.create(description: "Bastia Umbra", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 18400)
Comune.create(description: "Bettona", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 3784)
Comune.create(description: "Bevagna", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 4799)
Comune.create(description: "Campello Sul Clitunno", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 2367)
Comune.create(description: "Cannara", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 3952)
Comune.create(description: "Cascia", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 3260)
Comune.create(description: "Castel Ritaldi", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 3071)
Comune.create(description: "Castiglione Del Lago", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 14230)
Comune.create(description: "Cerreto Di Spoleto", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 1137)
Comune.create(description: "Citerna", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 3131)
Comune.create(description: "Collazzone", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 2929)
Comune.create(description: "Corciano", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 15256)
Comune.create(description: "Costacciaro", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 1289)
Comune.create(description: "Deruta", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 8090)
Comune.create(description: "Foligno", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 51130)
Comune.create(description: "Fossato Di Vico", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 2439)
Comune.create(description: "Fratta Todina", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 1733)
Comune.create(description: "Gualdo Cattaneo", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 6056)
Comune.create(description: "Gualdo Tadino", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 15064)
Comune.create(description: "Gubbio", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 31616)
Comune.create(description: "Lisciano Niccone", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 670)
Comune.create(description: "Magione", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 12306)
Comune.create(description: "Marsciano", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 16336)
Comune.create(description: "Massa Martana", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 3541)
Comune.create(description: "Monte Castello Di Vibio", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 1627)
Comune.create(description: "Monte Santa Maria Tiberina", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 1225)
Comune.create(description: "Montefalco", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 5630)
Comune.create(description: "Monteleone Di Spoleto", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 681)
Comune.create(description: "Montone", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 1555)
Comune.create(description: "Nocera Umbra", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 5896)
Comune.create(description: "Norcia", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 4872)
Comune.create(description: "Paciano", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 953)
Comune.create(description: "Panicale", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 5335)
Comune.create(description: "Passignano Sul Trasimeno", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 5059)
Comune.create(description: "Perugia", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 149125)
Comune.create(description: "Piegaro", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 3645)
Comune.create(description: "Pietralunga", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 2342)
Comune.create(description: "Poggiodomo", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 172)
Comune.create(description: "Preci", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 817)
Comune.create(description: "San Giustino", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 10394)
Comune.create(description: "Scheggia E Pascelupo", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 1477)
Comune.create(description: "Scheggino", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 458)
Comune.create(description: "Sellano", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 1208)
Comune.create(description: "Sigillo", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 2461)
Comune.create(description: "Spello", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 8304)
Comune.create(description: "Spoleto", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 37889)
Comune.create(description: "Todi", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 16704)
Comune.create(description: "Torgiano", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 5406)
Comune.create(description: "Trevi", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 7773)
Comune.create(description: "Tuoro Sul Trasimeno", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 3585)
Comune.create(description: "Umbertide", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 15254)
Comune.create(description: "Valfabbrica", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 3483)
Comune.create(description: "Vallo Di Nera", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 428)
Comune.create(description: "Valtopina", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 1341)
Comune.create(description: "Citta' Della Pieve", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 7122)
Comune.create(description: "Citta' Di Castello", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 37889)
Comune.create(description: "Giano Dell'Umbria", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 3383)
Comune.create(description: "Sant'Anatolia Di Narco", provincia_id: 88, regione_id: 20, country_id: 1, continente_id: 1 , population: 567)
