Municipality.create(description: "Adrara San Martino", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 1908)
Municipality.create(description: "Adrara San Rocco", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 804)
Municipality.create(description: "Albino", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 16394)
Municipality.create(description: "Algua", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 690)
Municipality.create(description: "Almenno San Bartolomeo", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 4916)
Municipality.create(description: "Almenno San Salvatore", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 5788)
Municipality.create(description: "Alzano Lombardo", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 12068)
Municipality.create(description: "Ambivere", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 2250)
Municipality.create(description: "Antegnate", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 2368)
Municipality.create(description: "Arcene", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 4347)
Municipality.create(description: "Ardesio", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 3702)
Municipality.create(description: "Averara", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 202)
Municipality.create(description: "Aviatico", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 488)
Municipality.create(description: "Azzano San Paolo", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 6769)
Municipality.create(description: "Azzone", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 490)
Municipality.create(description: "Bagnatica", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 3628)
Municipality.create(description: "Barbata", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 607)
Municipality.create(description: "Bariano", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 3977)
Municipality.create(description: "Barzana", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 1562)
Municipality.create(description: "Bedulita", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 710)
Municipality.create(description: "Berbenno", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 2368)
Municipality.create(description: "Bergamo", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 113143)
Municipality.create(description: "Berzo San Fermo", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 1142)
Municipality.create(description: "Bianzano", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 521)
Municipality.create(description: "Blello", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 94)
Municipality.create(description: "Bolgare", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 4200)
Municipality.create(description: "Boltiere", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 4181)
Municipality.create(description: "Bonate Sopra", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 6238)
Municipality.create(description: "Bonate Sotto", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 5429)
Municipality.create(description: "Borgo Di Terzo", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 933)
Municipality.create(description: "Bossico", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 997)
Municipality.create(description: "Bottanuco", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 4567)
Municipality.create(description: "Bracca", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 755)
Municipality.create(description: "Branzi", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 761)
Municipality.create(description: "Brembate", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 7180)
Municipality.create(description: "Brembate Di Sopra", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 6741)
Municipality.create(description: "Brembilla", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 4274)
Municipality.create(description: "Brumano", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 86)
Municipality.create(description: "Brusaporto", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 4168)
Municipality.create(description: "Calcinate", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 4665)
Municipality.create(description: "Calcio", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 4799)
Municipality.create(description: "Calvenzano", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 3447)
Municipality.create(description: "Camerata Cornello", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 594)
Municipality.create(description: "Capizzone", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 1194)
Municipality.create(description: "Capriate San Gervasio", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 7252)
Municipality.create(description: "Caprino Bergamasco", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 2823)
Municipality.create(description: "Caravaggio", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 14109)
Municipality.create(description: "Carobbio Degli Angeli", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 3317)
Municipality.create(description: "Carona", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 383)
Municipality.create(description: "Carvico", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 4141)
Municipality.create(description: "Casazza", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 3478)
Municipality.create(description: "Casnigo", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 3453)
Municipality.create(description: "Cassiglio", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 107)
Municipality.create(description: "Castel Rozzone", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 2545)
Municipality.create(description: "Castelli Calepio", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 8936)
Municipality.create(description: "Castione Della Presolana", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 3291)
Municipality.create(description: "Castro", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 2557)
Municipality.create(description: "Cavernago", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 1667)
Municipality.create(description: "Cenate Sopra", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 2082)
Municipality.create(description: "Cenate Sotto", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 2670)
Municipality.create(description: "Cene", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 3931)
Municipality.create(description: "Cerete", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 1378)
Municipality.create(description: "Chiuduno", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 5051)
Municipality.create(description: "Cisano Bergamasco", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 5605)
Municipality.create(description: "Ciserano", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 4925)
Municipality.create(description: "Cividate Al Piano", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 4869)
Municipality.create(description: "Clusone", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 8259)
Municipality.create(description: "Colere", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 1143)
Municipality.create(description: "Cologno Al Serio", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 9442)
Municipality.create(description: "Colzate", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 1662)
Municipality.create(description: "Comun Nuovo", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 2908)
Municipality.create(description: "Corna Imagna", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 923)
Municipality.create(description: "Cornalba", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 287)
Municipality.create(description: "Cortenuova", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Costa Di Mezzate", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 2747)
Municipality.create(description: "Costa Di Serina", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 )
Municipality.create(description: "Costa Valle Imagna", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 620)
Municipality.create(description: "Costa Volpino", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 8460)
Municipality.create(description: "Covo", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 3154)
Municipality.create(description: "Credaro", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 2297)
Municipality.create(description: "Curno", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 7193)
Municipality.create(description: "Cusio", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 313)
Municipality.create(description: "Dalmine", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 21459)
Municipality.create(description: "Dossena", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 1015)
Municipality.create(description: "Endine Gaiano", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 3100)
Municipality.create(description: "Entratico", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 1452)
Municipality.create(description: "Fara Olivana Con Sola", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 1167)
Municipality.create(description: "Fino Del Monte", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 1116)
Municipality.create(description: "Fiorano Al Serio", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 2904)
Municipality.create(description: "Fontanella", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 3628)
Municipality.create(description: "Fonteno", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 697)
Municipality.create(description: "Foppolo", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 208)
Municipality.create(description: "Foresto Sparso", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 2847)
Municipality.create(description: "Fornovo San Giovanni", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 2707)
Municipality.create(description: "Fuipiano Valle Imagna", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 230)
Municipality.create(description: "Gandellino", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 1100)
Municipality.create(description: "Gandino", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 5649)
Municipality.create(description: "Gandosso", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 1324)
Municipality.create(description: "Gaverina Terme", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 906)
Municipality.create(description: "Gazzaniga", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 4968)
Municipality.create(description: "Gerosa", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Ghisalba", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 4626)
Municipality.create(description: "Gorlago", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 4607)
Municipality.create(description: "Gorle", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 5063)
Municipality.create(description: "Gorno", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 1778)
Municipality.create(description: "Grassobbio", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 5378)
Municipality.create(description: "Gromo", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 1225)
Municipality.create(description: "Grone", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 730)
Municipality.create(description: "Grumello Del Monte", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 6353)
Municipality.create(description: "Isola Di Fondra", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 184)
Municipality.create(description: "Isso", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 630)
Municipality.create(description: "Lallio", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 3832)
Municipality.create(description: "Leffe", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 4940)
Municipality.create(description: "Lenna", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 704)
Municipality.create(description: "Levate", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 3266)
Municipality.create(description: "Locatello", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 740)
Municipality.create(description: "Lovere", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 5437)
Municipality.create(description: "Lurano", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 2093)
Municipality.create(description: "Luzzana", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 719)
Municipality.create(description: "Madone", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 3181)
Municipality.create(description: "Mapello", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 5606)
Municipality.create(description: "Martinengo", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 8570)
Municipality.create(description: "Medolago", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 2047)
Municipality.create(description: "Mezzoldo", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 222)
Municipality.create(description: "Monasterolo Del Castello", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 938)
Municipality.create(description: "Montello", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 2392)
Municipality.create(description: "Morengo", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 2248)
Municipality.create(description: "Mornico Al Serio", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 2588)
Municipality.create(description: "Mozzanica", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 3921)
Municipality.create(description: "Mozzo", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 6895)
Municipality.create(description: "Nembro", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 11108)
Municipality.create(description: "Olmo Al Brembo", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 534)
Municipality.create(description: "Oltre Il Colle", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 1142)
Municipality.create(description: "Oltressenda Alta", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 194)
Municipality.create(description: "Oneta", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 714)
Municipality.create(description: "Onore", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 717)
Municipality.create(description: "Orio Al Serio", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 1475)
Municipality.create(description: "Ornica", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 210)
Municipality.create(description: "Osio Sopra", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 4077)
Municipality.create(description: "Osio Sotto", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 10630)
Municipality.create(description: "Pagazzano", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 1859)
Municipality.create(description: "Paladina", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 3319)
Municipality.create(description: "Palazzago", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 3610)
Municipality.create(description: "Palosco", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 4999)
Municipality.create(description: "Parre", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 2706)
Municipality.create(description: "Parzanica", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 377)
Municipality.create(description: "Pedrengo", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 5166)
Municipality.create(description: "Peia", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 1761)
Municipality.create(description: "Pianico", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 1385)
Municipality.create(description: "Piario", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 918)
Municipality.create(description: "Piazza Brembana", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 1182)
Municipality.create(description: "Piazzatorre", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 477)
Municipality.create(description: "Piazzolo", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 99)
Municipality.create(description: "Pognano", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 1241)
Municipality.create(description: "Ponte Nossa", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 2046)
Municipality.create(description: "Ponte San Pietro", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 9633)
Municipality.create(description: "Ponteranica", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 6878)
Municipality.create(description: "Pontida", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 2934)
Municipality.create(description: "Pontirolo Nuovo", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 4241)
Municipality.create(description: "Pradalunga", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 4179)
Municipality.create(description: "Predore", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 1776)
Municipality.create(description: "Premolo", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 1029)
Municipality.create(description: "Presezzo", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 4529)
Municipality.create(description: "Pumenengo", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 1488)
Municipality.create(description: "Ranica", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 5820)
Municipality.create(description: "Ranzanico", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 1088)
Municipality.create(description: "Riva Di Solto", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 833)
Municipality.create(description: "Rogno", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 3304)
Municipality.create(description: "Romano Di Lombardia", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 15634)
Municipality.create(description: "Roncobello", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 495)
Municipality.create(description: "Roncola", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 634)
Municipality.create(description: "Rovetta", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 3370)
Municipality.create(description: "San Giovanni Bianco", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 4996)
Municipality.create(description: "San Pellegrino Terme", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 4980)
Municipality.create(description: "Santa Brigida", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 635)
Municipality.create(description: "Sarnico", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 5754)
Municipality.create(description: "Scanzorosciate", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 8714)
Municipality.create(description: "Schilpario", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 1302)
Municipality.create(description: "Sedrina", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 2380)
Municipality.create(description: "Selvino", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 2011)
Municipality.create(description: "Seriate", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 20320)
Municipality.create(description: "Serina", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 2193)
Municipality.create(description: "Solto Collina", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 1514)
Municipality.create(description: "Solza", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 1429)
Municipality.create(description: "Songavazzo", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 616)
Municipality.create(description: "Sorisole", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 8303)
Municipality.create(description: "Sotto Il Monte Giovanni Xxiii", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 3305)
Municipality.create(description: "Sovere", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 4910)
Municipality.create(description: "Spinone Al Lago", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 825)
Municipality.create(description: "Spirano", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 4419)
Municipality.create(description: "Stezzano", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 10340)
Municipality.create(description: "Strozza", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 932)
Municipality.create(description: "Suisio", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 3308)
Municipality.create(description: "Taleggio", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 582)
Municipality.create(description: "Tavernola Bergamasca", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 2273)
Municipality.create(description: "Telgate", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 4190)
Municipality.create(description: "Torre Boldone", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 7764)
Municipality.create(description: "Torre Pallavicina", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 1063)
Municipality.create(description: "Trescore Balneario", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 8303)
Municipality.create(description: "Treviglio", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 25736)
Municipality.create(description: "Treviolo", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 8618)
Municipality.create(description: "Ubiale Clanezzo", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 1272)
Municipality.create(description: "Urgnano", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 8445)
Municipality.create(description: "Valbondione", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 1168)
Municipality.create(description: "Valbrembo", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 3587)
Municipality.create(description: "Valgoglio", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 613)
Municipality.create(description: "Valleve", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 158)
Municipality.create(description: "Valnegra", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 230)
Municipality.create(description: "Valsecca", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 413)
Municipality.create(description: "Valtorta", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 345)
Municipality.create(description: "Vedeseta", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 263)
Municipality.create(description: "Verdellino", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 6697)
Municipality.create(description: "Verdello", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 6501)
Municipality.create(description: "Vertova", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 4701)
Municipality.create(description: "Viadanica", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 1028)
Municipality.create(description: "Vigano San Martino", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 989)
Municipality.create(description: "Vigolo", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 661)
Municipality.create(description: "Villa Di Serio", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 5837)
Municipality.create(description: "Villongo", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 6396)
Municipality.create(description: "Vilminore Di Scalve", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 1547)
Municipality.create(description: "Zandobbio", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 2281)
Municipality.create(description: "Zanica", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 7063)
Municipality.create(description: "Zogno", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 9015)
Municipality.create(description: "Albano Sant'Alessandro", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 6756)
Municipality.create(description: "Alme'", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 5740)
Municipality.create(description: "Arzago D'Adda", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 2285)
Municipality.create(description: "Brignano Gera D'Adda", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 4773)
Municipality.create(description: "Canonica D'Adda", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 3685)
Municipality.create(description: "Casirate D'Adda", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 3359)
Municipality.create(description: "Cazzano Sant'Andrea", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 1402)
Municipality.create(description: "Chignolo D'Isola", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 2702)
Municipality.create(description: "Fara Gera D'Adda", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 6748)
Municipality.create(description: "Misano Di Gera D'Adda", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 2590)
Municipality.create(description: "Moio De' Calvi", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 195)
Municipality.create(description: "Rota D'Imagna", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 856)
Municipality.create(description: "San Paolo D'Argon", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 4478)
Municipality.create(description: "Sant'Omobono Imagna", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 3184)
Municipality.create(description: "Terno D'Isola", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 4995)
Municipality.create(description: "Torre De' Roveri", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 2036)
Municipality.create(description: "Villa D'Adda", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 4195)
Municipality.create(description: "Villa D'Alme'", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 6617)
Municipality.create(description: "Villa D'Ogna", province_id: 90, region_id:  19, country_id: 1, continent_id: 1 , population: 1744)
