Comune.create(description: "Acceglio", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 197)
Comune.create(description: "Aisone", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 257)
Comune.create(description: "Alba", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 29910)
Comune.create(description: "Albaretto Della Torre", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 254)
Comune.create(description: "Alto", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 104)
Comune.create(description: "Argentera", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 101)
Comune.create(description: "Arguello", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 174)
Comune.create(description: "Bagnasco", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 1012)
Comune.create(description: "Bagnolo Piemonte", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 5431)
Comune.create(description: "Barbaresco", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 641)
Comune.create(description: "Barge", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 7211)
Comune.create(description: "Barolo", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 681)
Comune.create(description: "Battifollo", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 263)
Comune.create(description: "Beinette", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 2719)
Comune.create(description: "Bellino", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 179)
Comune.create(description: "Belvedere Langhe", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 372)
Comune.create(description: "Bene Vagienna", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 3299)
Comune.create(description: "Benevello", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 448)
Comune.create(description: "Bergolo", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 79)
Comune.create(description: "Bernezzo", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 3009)
Comune.create(description: "Bonvicino", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 119)
Comune.create(description: "Borgo San Dalmazzo", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 11274)
Comune.create(description: "Borgomale", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 365)
Comune.create(description: "Bosia", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 204)
Comune.create(description: "Bossolasco", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 683)
Comune.create(description: "Boves", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 9222)
Comune.create(description: "Bra", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 27988)
Comune.create(description: "Briaglia", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 288)
Comune.create(description: "Briga Alta", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 62)
Comune.create(description: "Brondello", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 349)
Comune.create(description: "Brossasco", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 1133)
Comune.create(description: "Busca", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 9469)
Comune.create(description: "Camerana", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 723)
Comune.create(description: "Camo", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 238)
Comune.create(description: "Canale", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Canosio", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 93)
Comune.create(description: "Caprauna", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 133)
Comune.create(description: "Caraglio", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 6215)
Comune.create(description: "Caramagna Piemonte", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 2670)
Comune.create(description: "Cartignano", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 170)
Comune.create(description: "Casalgrasso", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 1372)
Comune.create(description: "Castagnito", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 1728)
Comune.create(description: "Casteldelfino", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 227)
Comune.create(description: "Castellar", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 247)
Comune.create(description: "Castelletto Stura", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 1176)
Comune.create(description: "Castelletto Uzzone", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 375)
Comune.create(description: "Castellinaldo", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 858)
Comune.create(description: "Castellino Tanaro", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 339)
Comune.create(description: "Castelmagno", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 117)
Comune.create(description: "Castelnuovo Di Ceva", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 121)
Comune.create(description: "Castiglione Falletto", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 632)
Comune.create(description: "Castiglione Tinella", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 877)
Comune.create(description: "Castino", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 526)
Comune.create(description: "Cavallerleone", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 561)
Comune.create(description: "Cavallermaggiore", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 5064)
Comune.create(description: "Celle Di Macra", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 105)
Comune.create(description: "Centallo", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 6209)
Comune.create(description: "Ceresole Alba", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 2089)
Comune.create(description: "Cerreto Langhe", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 )
Comune.create(description: "Cervasca", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 4197)
Comune.create(description: "Cervere", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 1882)
Comune.create(description: "Ceva", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 5729)
Comune.create(description: "Cherasco", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 7208)
Comune.create(description: "Chiusa Di Pesio", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 3703)
Comune.create(description: "Cissone", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 100)
Comune.create(description: "Clavesana", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 868)
Comune.create(description: "Cortemilia", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 2544)
Comune.create(description: "Cossano Belbo", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 1071)
Comune.create(description: "Costigliole Saluzzo", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 3122)
Comune.create(description: "Cravanzana", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 400)
Comune.create(description: "Crissolo", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 210)
Comune.create(description: "Cuneo", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 52334)
Comune.create(description: "Demonte", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 2041)
Comune.create(description: "Dogliani", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 4554)
Comune.create(description: "Dronero", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 7012)
Comune.create(description: "Elva", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 114)
Comune.create(description: "Entracque", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 848)
Comune.create(description: "Envie", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 1890)
Comune.create(description: "Farigliano", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 1752)
Comune.create(description: "Faule", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 403)
Comune.create(description: "Feisoglio", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 395)
Comune.create(description: "Fossano", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 23865)
Comune.create(description: "Frabosa Soprana", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 875)
Comune.create(description: "Frabosa Sottana", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 1390)
Comune.create(description: "Frassino", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 324)
Comune.create(description: "Gaiola", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 471)
Comune.create(description: "Gambasca", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 346)
Comune.create(description: "Garessio", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 3498)
Comune.create(description: "Genola", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 2323)
Comune.create(description: "Gorzegno", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 393)
Comune.create(description: "Gottasecca", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 188)
Comune.create(description: "Govone", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 1922)
Comune.create(description: "Grinzane Cavour", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 1812)
Comune.create(description: "Guarene", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 3018)
Comune.create(description: "Igliano", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 81)
Comune.create(description: "Isasca", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 112)
Comune.create(description: "La Morra", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 2610)
Comune.create(description: "Lagnasco", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 1291)
Comune.create(description: "Lequio Berria", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 524)
Comune.create(description: "Lequio Tanaro", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 683)
Comune.create(description: "Lesegno", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 838)
Comune.create(description: "Levice", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 270)
Comune.create(description: "Limone Piemonte", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 1548)
Comune.create(description: "Lisio", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 248)
Comune.create(description: "Macra", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 61)
Comune.create(description: "Magliano Alfieri", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 1674)
Comune.create(description: "Magliano Alpi", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 2111)
Comune.create(description: "Mango", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 1334)
Comune.create(description: "Manta", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 3363)
Comune.create(description: "Marene", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 2703)
Comune.create(description: "Margarita", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 1297)
Comune.create(description: "Marmora", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 99)
Comune.create(description: "Marsaglia", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 316)
Comune.create(description: "Martiniana Po", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 667)
Comune.create(description: "Melle", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 364)
Comune.create(description: "Moiola", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 296)
Comune.create(description: "Mombarcaro", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 320)
Comune.create(description: "Mombasiglio", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 630)
Comune.create(description: "Monastero Di Vasco", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 1200)
Comune.create(description: "Monasterolo Casotto", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 126)
Comune.create(description: "Monasterolo Di Savigliano", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 1173)
Comune.create(description: "Monchiero", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 518)
Comune.create(description: "Monesiglio", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 752)
Comune.create(description: "Montaldo Roero", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 866)
Comune.create(description: "Montanera", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 731)
Comune.create(description: "Montelupo Albese", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 459)
Comune.create(description: "Montemale Di Cuneo", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 222)
Comune.create(description: "Monterosso Grana", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 570)
Comune.create(description: "Monteu Roero", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 1603)
Comune.create(description: "Montezemolo", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 305)
Comune.create(description: "Moretta", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 4106)
Comune.create(description: "Morozzo", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 1979)
Comune.create(description: "Murazzano", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 856)
Comune.create(description: "Murello", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 899)
Comune.create(description: "Narzole", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 3305)
Comune.create(description: "Neive", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 2938)
Comune.create(description: "Neviglie", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 419)
Comune.create(description: "Niella Belbo", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 421)
Comune.create(description: "Niella Tanaro", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 1027)
Comune.create(description: "Novello", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 931)
Comune.create(description: "Nucetto", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 473)
Comune.create(description: "Oncino", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 102)
Comune.create(description: "Ormea", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 1967)
Comune.create(description: "Ostana", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 79)
Comune.create(description: "Paesana", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 3072)
Comune.create(description: "Pagno", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 554)
Comune.create(description: "Pamparato", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 403)
Comune.create(description: "Paroldo", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 246)
Comune.create(description: "Perletto", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 328)
Comune.create(description: "Perlo", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 130)
Comune.create(description: "Peveragno", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 5207)
Comune.create(description: "Pezzolo Valle Uzzone", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 370)
Comune.create(description: "Pianfei", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 1811)
Comune.create(description: "Piasco", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 2711)
Comune.create(description: "Pietraporzio", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 115)
Comune.create(description: "Piozzo", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 997)
Comune.create(description: "Pocapaglia", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 2758)
Comune.create(description: "Polonghera", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 1138)
Comune.create(description: "Pontechianale", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 208)
Comune.create(description: "Pradleves", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 317)
Comune.create(description: "Prazzo", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 218)
Comune.create(description: "Priero", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 441)
Comune.create(description: "Priocca", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 1956)
Comune.create(description: "Priola", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 804)
Comune.create(description: "Prunetto", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 492)
Comune.create(description: "Racconigi", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 9856)
Comune.create(description: "Revello", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 4192)
Comune.create(description: "Rifreddo", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 1032)
Comune.create(description: "Rittana", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 149)
Comune.create(description: "Roaschia", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 166)
Comune.create(description: "Roascio", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 85)
Comune.create(description: "Robilante", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 2316)
Comune.create(description: "Roburent", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 565)
Comune.create(description: "Roccabruna", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 1460)
Comune.create(description: "Roccasparvera", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 672)
Comune.create(description: "Roccavione", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 2791)
Comune.create(description: "Rocchetta Belbo", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 191)
Comune.create(description: "Roddi", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 1323)
Comune.create(description: "Roddino", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 363)
Comune.create(description: "Rodello", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 908)
Comune.create(description: "Rossana", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 934)
Comune.create(description: "Ruffia", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 311)
Comune.create(description: "Sale Delle Langhe", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 490)
Comune.create(description: "Sale San Giovanni", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 193)
Comune.create(description: "Saliceto", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 1500)
Comune.create(description: "Salmour", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 704)
Comune.create(description: "Saluzzo", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 15647)
Comune.create(description: "Sambuco", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 89)
Comune.create(description: "Sampeyre", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 1144)
Comune.create(description: "San Benedetto Belbo", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 192)
Comune.create(description: "San Damiano Macra", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 477)
Comune.create(description: "Sanfront", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 2611)
Comune.create(description: "Santo Stefano Belbo", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 4037)
Comune.create(description: "Santo Stefano Roero", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 1236)
Comune.create(description: "Savigliano", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 19884)
Comune.create(description: "Scagnello", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 209)
Comune.create(description: "Scarnafigi", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 1910)
Comune.create(description: "Serravalle Langhe", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 352)
Comune.create(description: "Sinio", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 461)
Comune.create(description: "Somano", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 386)
Comune.create(description: "Sommariva Del Bosco", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 5779)
Comune.create(description: "Sommariva Perno", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 2626)
Comune.create(description: "Stroppo", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 108)
Comune.create(description: "Tarantasca", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 1940)
Comune.create(description: "Torre Bormida", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 232)
Comune.create(description: "Torre San Giorgio", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 672)
Comune.create(description: "Torresina", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 67)
Comune.create(description: "Treiso", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 763)
Comune.create(description: "Trezzo Tinella", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 356)
Comune.create(description: "Valdieri", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 964)
Comune.create(description: "Valgrana", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 797)
Comune.create(description: "Valloriate", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 166)
Comune.create(description: "Valmala", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 56)
Comune.create(description: "Venasca", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 1512)
Comune.create(description: "Verduno", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 512)
Comune.create(description: "Vernante", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 1332)
Comune.create(description: "Verzuolo", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 6196)
Comune.create(description: "Vicoforte", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 3024)
Comune.create(description: "Vignolo", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 2054)
Comune.create(description: "Villafalletto", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 2876)
Comune.create(description: "Villanova Solaro", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 782)
Comune.create(description: "Villar San Costanzo", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 1396)
Comune.create(description: "Vinadio", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 732)
Comune.create(description: "Viola", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 461)
Comune.create(description: "Vottignasco", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 573)
Comune.create(description: "Baldissero D'Alba", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 1084)
Comune.create(description: "Bastia Mondovi'", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 624)
Comune.create(description: "Carde'", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 1069)
Comune.create(description: "Carru'", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 4006)
Comune.create(description: "Ciglie'", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 188)
Comune.create(description: "Corneliano D'Alba", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 1889)
Comune.create(description: "Diano D'Alba", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 2980)
Comune.create(description: "Mondovi'", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 21880)
Comune.create(description: "Monforte D'Alba", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 1917)
Comune.create(description: "Monta'", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 4292)
Comune.create(description: "Montaldo Di Mondovi'", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 587)
Comune.create(description: "Monticello D'Alba", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 1911)
Comune.create(description: "Piobesi D'Alba", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 1027)
Comune.create(description: "Rocca Ciglie'", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 157)
Comune.create(description: "Rocca De' Baldi", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 1616)
Comune.create(description: "Roccaforte Mondovi'", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 2024)
Comune.create(description: "San Michele Mondovi'", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 2069)
Comune.create(description: "Sanfre'", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 2500)
Comune.create(description: "Santa Vittoria D'Alba", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 2512)
Comune.create(description: "Sant'Albano Stura", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 2084)
Comune.create(description: "Serralunga D'Alba", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 491)
Comune.create(description: "Torre Mondovi'", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 521)
Comune.create(description: "Trinita'", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 1981)
Comune.create(description: "Vezza D'Alba", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 2073)
Comune.create(description: "Villanova Mondovi'", province_id: 8, region_id:  13, country_id: 1, continent_id: 1 , population: 5445)
