Comune.create(description: "Edolo", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 4291)
Comune.create(description: "Acquafredda", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 1409)
Comune.create(description: "Adro", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 6421)
Comune.create(description: "Agnosine", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 1875)
Comune.create(description: "Alfianello", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 2347)
Comune.create(description: "Anfo", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 434)
Comune.create(description: "Angolo Terme", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 2508)
Comune.create(description: "Artogne", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 3134)
Comune.create(description: "Azzano Mella", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 1859)
Comune.create(description: "Bagnolo Mella", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Bagolino", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 3919)
Comune.create(description: "Barbariga", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 2180)
Comune.create(description: "Barghe", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 1124)
Comune.create(description: "Bassano Bresciano", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 1800)
Comune.create(description: "Bedizzole", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 9320)
Comune.create(description: "Berlingo", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 1861)
Comune.create(description: "Berzo Demo", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 1847)
Comune.create(description: "Berzo Inferiore", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 2206)
Comune.create(description: "Bienno", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 3510)
Comune.create(description: "Bione", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 1386)
Comune.create(description: "Borgo San Giacomo", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 4603)
Comune.create(description: "Borgosatollo", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 7972)
Comune.create(description: "Borno", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 2719)
Comune.create(description: "Botticino", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 9730)
Comune.create(description: "Bovegno", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 2321)
Comune.create(description: "Bovezzo", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 7407)
Comune.create(description: "Brandico", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 1041)
Comune.create(description: "Braone", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 610)
Comune.create(description: "Breno", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 4962)
Comune.create(description: "Brescia", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 187567)
Comune.create(description: "Brione", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 546)
Comune.create(description: "Caino", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 1614)
Comune.create(description: "Calcinato", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 10648)
Comune.create(description: "Calvagese Della Riviera", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 2539)
Comune.create(description: "Calvisano", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 7416)
Comune.create(description: "Capo Di Ponte", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 2428)
Comune.create(description: "Capovalle", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 452)
Comune.create(description: "Capriano Del Colle", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 3856)
Comune.create(description: "Capriolo", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 8347)
Comune.create(description: "Carpenedolo", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 10386)
Comune.create(description: "Castegnato", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 6666)
Comune.create(description: "Castel Mella", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 8141)
Comune.create(description: "Castelcovati", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 5348)
Comune.create(description: "Castenedolo", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 9257)
Comune.create(description: "Casto", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 1913)
Comune.create(description: "Castrezzato", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 5800)
Comune.create(description: "Cazzago San Martino", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 9814)
Comune.create(description: "Cedegolo", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 1261)
Comune.create(description: "Cellatica", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 4723)
Comune.create(description: "Cerveno", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 659)
Comune.create(description: "Ceto", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 1860)
Comune.create(description: "Cevo", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 1030)
Comune.create(description: "Chiari", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 17393)
Comune.create(description: "Cigole", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 1523)
Comune.create(description: "Cimbergo", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 573)
Comune.create(description: "Cividate Camuno", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 2637)
Comune.create(description: "Coccaglio", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 7049)
Comune.create(description: "Collebeato", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 4366)
Comune.create(description: "Collio", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 2315)
Comune.create(description: "Cologne", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 6492)
Comune.create(description: "Comezzano Cizzago", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 )
Comune.create(description: "Concesio", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 12827)
Comune.create(description: "Corte Franca", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 6282)
Comune.create(description: "Corteno Golgi", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 1992)
Comune.create(description: "Corzano", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 980)
Comune.create(description: "Darfo Boario Terme", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 13590)
Comune.create(description: "Dello", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 4231)
Comune.create(description: "Desenzano Del Garda", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 23651)
Comune.create(description: "Erbusco", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 6840)
Comune.create(description: "Esine", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 4707)
Comune.create(description: "Fiesse", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 1931)
Comune.create(description: "Flero", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 7495)
Comune.create(description: "Gambara", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 4533)
Comune.create(description: "Gardone Riviera", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 2531)
Comune.create(description: "Gardone Val Trompia", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 10952)
Comune.create(description: "Gargnano", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 3035)
Comune.create(description: "Gavardo", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 10089)
Comune.create(description: "Ghedi", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 15627)
Comune.create(description: "Gianico", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 1924)
Comune.create(description: "Gottolengo", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 4777)
Comune.create(description: "Gussago", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 14502)
Comune.create(description: "Idro", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 1695)
Comune.create(description: "Incudine", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 451)
Comune.create(description: "Irma", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 139)
Comune.create(description: "Iseo", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 8410)
Comune.create(description: "Isorella", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 3533)
Comune.create(description: "Lavenone", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 659)
Comune.create(description: "Leno", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 12541)
Comune.create(description: "Limone Sul Garda", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 1033)
Comune.create(description: "Lodrino", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 1717)
Comune.create(description: "Lograto", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 2909)
Comune.create(description: "Lonato", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Longhena", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 578)
Comune.create(description: "Losine", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 510)
Comune.create(description: "Lozio", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 405)
Comune.create(description: "Lumezzane", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 23712)
Comune.create(description: "Maclodio", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 1232)
Comune.create(description: "Magasa", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 189)
Comune.create(description: "Mairano", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 2413)
Comune.create(description: "Malegno", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 2111)
Comune.create(description: "Malonno", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 3326)
Comune.create(description: "Manerba Del Garda", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 3761)
Comune.create(description: "Manerbio", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 12611)
Comune.create(description: "Marcheno", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 4126)
Comune.create(description: "Marmentino", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 712)
Comune.create(description: "Marone", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 3057)
Comune.create(description: "Mazzano", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 9390)
Comune.create(description: "Milzano", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 1483)
Comune.create(description: "Moniga Del Garda", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 1702)
Comune.create(description: "Monno", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 586)
Comune.create(description: "Monte Isola", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 1769)
Comune.create(description: "Monticelli Brusati", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 3610)
Comune.create(description: "Montichiari", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 19101)
Comune.create(description: "Montirone", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 4021)
Comune.create(description: "Mura", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 780)
Comune.create(description: "Muscoline", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 2043)
Comune.create(description: "Nave", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 10433)
Comune.create(description: "Niardo", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 1837)
Comune.create(description: "Nuvolento", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 3523)
Comune.create(description: "Nuvolera", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 3679)
Comune.create(description: "Odolo", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 1904)
Comune.create(description: "Offlaga", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 3365)
Comune.create(description: "Ome", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 2904)
Comune.create(description: "Ono San Pietro", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 933)
Comune.create(description: "Orzinuovi", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 11175)
Comune.create(description: "Orzivecchi", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 2286)
Comune.create(description: "Ospitaletto", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 11086)
Comune.create(description: "Ossimo", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 1434)
Comune.create(description: "Padenghe Sul Garda", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 3493)
Comune.create(description: "Paderno Franciacorta", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 3379)
Comune.create(description: "Paisco Loveno", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 257)
Comune.create(description: "Paitone", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 1658)
Comune.create(description: "Paratico", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 3445)
Comune.create(description: "Paspardo", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 677)
Comune.create(description: "Passirano", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 5911)
Comune.create(description: "Pavone Del Mella", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 2595)
Comune.create(description: "Pertica Alta", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 608)
Comune.create(description: "Pertica Bassa", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 711)
Comune.create(description: "Pezzaze", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 1613)
Comune.create(description: "Pian Camuno", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 3771)
Comune.create(description: "Piancogno", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 4119)
Comune.create(description: "Pisogne", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 7716)
Comune.create(description: "Polaveno", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 2481)
Comune.create(description: "Polpenazze", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 )
Comune.create(description: "Pompiano", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 3388)
Comune.create(description: "Poncarale", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 4132)
Comune.create(description: "Ponte Di Legno", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 1869)
Comune.create(description: "Pontevico", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 6484)
Comune.create(description: "Pontoglio", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 6330)
Comune.create(description: "Pozzolengo", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 2900)
Comune.create(description: "Pralboino", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 2622)
Comune.create(description: "Preseglie", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 1477)
Comune.create(description: "Prestine", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 396)
Comune.create(description: "Prevalle", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 5099)
Comune.create(description: "Provaglio Val Sabbia", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 919)
Comune.create(description: "Puegnago Sul Garda", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 2776)
Comune.create(description: "Remedello", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 3006)
Comune.create(description: "Rezzato", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 12295)
Comune.create(description: "Roccafranca", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 3746)
Comune.create(description: "Rodengo Saiano", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 )
Comune.create(description: "Roncadelle", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 7625)
Comune.create(description: "Rovato", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 14376)
Comune.create(description: "Rudiano", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 4610)
Comune.create(description: "Sabbio Chiese", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 3178)
Comune.create(description: "Sale Marasino", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 3180)
Comune.create(description: "San Felice Del Benaco", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 2939)
Comune.create(description: "San Gervasio Bresciano", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 1476)
Comune.create(description: "San Paolo", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 3884)
Comune.create(description: "San Zeno Naviglio", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 3447)
Comune.create(description: "Sarezzo", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 11652)
Comune.create(description: "Sellero", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 1475)
Comune.create(description: "Seniga", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 1573)
Comune.create(description: "Serle", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 2849)
Comune.create(description: "Sirmione", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 6534)
Comune.create(description: "Soiano Del Lago", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 1522)
Comune.create(description: "Sonico", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 1208)
Comune.create(description: "Sulzano", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 1467)
Comune.create(description: "Tavernole Sul Mella", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 1346)
Comune.create(description: "Tignale", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 1271)
Comune.create(description: "Torbole Casaglia", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 5113)
Comune.create(description: "Toscolano Maderno", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 )
Comune.create(description: "Travagliato", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 11012)
Comune.create(description: "Tremosine", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 1923)
Comune.create(description: "Trenzano", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 4848)
Comune.create(description: "Treviso Bresciano", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 587)
Comune.create(description: "Vallio Terme", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Valvestino", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 287)
Comune.create(description: "Verolanuova", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 7539)
Comune.create(description: "Verolavecchia", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 3814)
Comune.create(description: "Vestone", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 4225)
Comune.create(description: "Villa Carcina", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 10015)
Comune.create(description: "Villachiara", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 1239)
Comune.create(description: "Villanuova Sul Clisi", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 4762)
Comune.create(description: "Vione", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 758)
Comune.create(description: "Visano", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 1700)
Comune.create(description: "Vobarno", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 7477)
Comune.create(description: "Zone", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 1145)
Comune.create(description: "Palazzolo Sull'Oglio", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 17330)
Comune.create(description: "Provaglio D'Iseo", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 5885)
Comune.create(description: "Quinzano D'Oglio", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 5851)
Comune.create(description: "Roe' Volciano", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 4177)
Comune.create(description: "Salo'", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 10039)
Comune.create(description: "Saviore Dell'Adamello", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 1161)
Comune.create(description: "Temu'", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 1010)
Comune.create(description: "Urago D'Oglio", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 3199)
Comune.create(description: "Vezza D'Oglio", province_id: 91, region_id:  19, country_id: 1, continent_id: 1 , population: 1426)
