Municipality.create(description: "Albavilla", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 5938)
Municipality.create(description: "Albese Con Cassano", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 3981)
Municipality.create(description: "Albiolo", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2260)
Municipality.create(description: "Alserio", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1110)
Municipality.create(description: "Alzate Brianza", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 4556)
Municipality.create(description: "Anzano Del Parco", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1619)
Municipality.create(description: "Appiano Gentile", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 7054)
Municipality.create(description: "Argegno", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 654)
Municipality.create(description: "Arosio", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 4469)
Municipality.create(description: "Asso", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 3177)
Municipality.create(description: "Barni", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 502)
Municipality.create(description: "Bellagio", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2949)
Municipality.create(description: "Bene Lario", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 310)
Municipality.create(description: "Beregazzo Con Figliaro", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2310)
Municipality.create(description: "Binago", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 4233)
Municipality.create(description: "Bizzarone", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1495)
Municipality.create(description: "Blessagno", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 253)
Municipality.create(description: "Blevio", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1221)
Municipality.create(description: "Bregnano", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 5113)
Municipality.create(description: "Brenna", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1817)
Municipality.create(description: "Brienno", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 425)
Municipality.create(description: "Brunate", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1730)
Municipality.create(description: "Bulgarograsso", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2989)
Municipality.create(description: "Cabiate", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 6769)
Municipality.create(description: "Cadorago", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 6593)
Municipality.create(description: "Caglio", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 369)
Municipality.create(description: "Cagno", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1865)
Municipality.create(description: "Canzo", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 4900)
Municipality.create(description: "Capiago Intimiano", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 4839)
Municipality.create(description: "Carate Urio", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1209)
Municipality.create(description: "Carbonate", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2575)
Municipality.create(description: "Carimate", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 3805)
Municipality.create(description: "Carlazzo", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2696)
Municipality.create(description: "Carugo", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 5324)
Municipality.create(description: "Casnate Con Bernate", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 4382)
Municipality.create(description: "Cassina Rizzardi", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2379)
Municipality.create(description: "Castelmarte", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1247)
Municipality.create(description: "Castelnuovo Bozzente", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 777)
Municipality.create(description: "Cavallasca", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2733)
Municipality.create(description: "Cavargna", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 315)
Municipality.create(description: "Cermenate", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 8599)
Municipality.create(description: "Cernobbio", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 6662)
Municipality.create(description: "Cirimido", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1914)
Municipality.create(description: "Civenna", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 673)
Municipality.create(description: "Claino Con Osteno", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 528)
Municipality.create(description: "Colonno", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 561)
Municipality.create(description: "Como", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 78680)
Municipality.create(description: "Consiglio Di Rumo", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Corrido", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 730)
Municipality.create(description: "Cremia", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 761)
Municipality.create(description: "Cucciago", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 3196)
Municipality.create(description: "Cusino", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 261)
Municipality.create(description: "Dizzasco", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 491)
Municipality.create(description: "Domaso", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1438)
Municipality.create(description: "Dongo", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 3468)
Municipality.create(description: "Dosso Del Liro", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 315)
Municipality.create(description: "Drezzo", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1003)
Municipality.create(description: "Erba", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 16374)
Municipality.create(description: "Eupilio", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2502)
Municipality.create(description: "Faggeto Lario", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1173)
Municipality.create(description: "Faloppio", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 3455)
Municipality.create(description: "Figino Serenza", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 4636)
Municipality.create(description: "Fino Mornasco", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 8229)
Municipality.create(description: "Garzeno", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1029)
Municipality.create(description: "Gera Lario", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 882)
Municipality.create(description: "Germasino", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Gironico", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2039)
Municipality.create(description: "Grandate", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2901)
Municipality.create(description: "Grandola Ed Uniti", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1267)
Municipality.create(description: "Gravedona", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Griante", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 695)
Municipality.create(description: "Guanzate", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 5056)
Municipality.create(description: "Inverigo", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 7825)
Municipality.create(description: "Laglio", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 889)
Municipality.create(description: "Laino", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 469)
Municipality.create(description: "Lambrugo", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2181)
Municipality.create(description: "Lasnigo", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 406)
Municipality.create(description: "Lenno", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1786)
Municipality.create(description: "Lezzeno", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2071)
Municipality.create(description: "Limido Comasco", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2265)
Municipality.create(description: "Lipomo", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 5523)
Municipality.create(description: "Livo", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 208)
Municipality.create(description: "Locate Varesino", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 3960)
Municipality.create(description: "Lomazzo", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 7968)
Municipality.create(description: "Longone Al Segrino", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1455)
Municipality.create(description: "Luisago", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2368)
Municipality.create(description: "Lurago Marinone", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1971)
Municipality.create(description: "Lurate Caccivio", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 9715)
Municipality.create(description: "Magreglio", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 459)
Municipality.create(description: "Mariano Comense", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 20282)
Municipality.create(description: "Maslianico", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 3464)
Municipality.create(description: "Menaggio", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 3121)
Municipality.create(description: "Merone", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 3597)
Municipality.create(description: "Mezzegra", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 952)
Municipality.create(description: "Moltrasio", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1768)
Municipality.create(description: "Monguzzo", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1922)
Municipality.create(description: "Montano Lucino", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 4296)
Municipality.create(description: "Montemezzo", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 287)
Municipality.create(description: "Montorfano", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2489)
Municipality.create(description: "Mozzate", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 6874)
Municipality.create(description: "Musso", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1067)
Municipality.create(description: "Nesso", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1302)
Municipality.create(description: "Novedrate", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2889)
Municipality.create(description: "Olgiate Comasco", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 10354)
Municipality.create(description: "Oltrona Di San Mamette", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2097)
Municipality.create(description: "Orsenigo", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2340)
Municipality.create(description: "Ossuccio", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 940)
Municipality.create(description: "Peglio", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 727)
Municipality.create(description: "Pellio Intelvi", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 871)
Municipality.create(description: "Pianello Del Lario", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1030)
Municipality.create(description: "Pigra", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 302)
Municipality.create(description: "Plesio", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 805)
Municipality.create(description: "Pognana Lario", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 901)
Municipality.create(description: "Ponna", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 262)
Municipality.create(description: "Ponte Lambro", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 4066)
Municipality.create(description: "Porlezza", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 4144)
Municipality.create(description: "Proserpio", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 910)
Municipality.create(description: "Pusiano", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1166)
Municipality.create(description: "Ramponio Verna", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 403)
Municipality.create(description: "Rezzago", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 274)
Municipality.create(description: "Rodero", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1073)
Municipality.create(description: "Ronago", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1498)
Municipality.create(description: "Rovellasca", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 6279)
Municipality.create(description: "Rovello Porro", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 5512)
Municipality.create(description: "Sala Comacina", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 604)
Municipality.create(description: "San Bartolomeo Val Cavargna", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1118)
Municipality.create(description: "San Fedele Intelvi", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1491)
Municipality.create(description: "San Fermo Della Battaglia", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 4189)
Municipality.create(description: "San Nazzaro Val Cavargna", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 419)
Municipality.create(description: "Schignano", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 935)
Municipality.create(description: "Senna Comasco", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2766)
Municipality.create(description: "Solbiate", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2248)
Municipality.create(description: "Sorico", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1204)
Municipality.create(description: "Sormano", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 633)
Municipality.create(description: "Stazzona", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 675)
Municipality.create(description: "Tavernerio", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 5357)
Municipality.create(description: "Torno", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1222)
Municipality.create(description: "Tremezzo", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1314)
Municipality.create(description: "Trezzone", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 202)
Municipality.create(description: "Turate", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 7851)
Municipality.create(description: "Uggiate Trevano", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 )
Municipality.create(description: "Val Rezzo", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 217)
Municipality.create(description: "Valbrona", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2451)
Municipality.create(description: "Valmorea", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2553)
Municipality.create(description: "Valsolda", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1730)
Municipality.create(description: "Veleso", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 297)
Municipality.create(description: "Veniano", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2334)
Municipality.create(description: "Vercana", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 730)
Municipality.create(description: "Vertemate Con Minoprio", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 3851)
Municipality.create(description: "Villa Guardia", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 6487)
Municipality.create(description: "Zelbio", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 195)
Municipality.create(description: "Campione D'Italia", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2267)
Municipality.create(description: "Cantu'", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 35153)
Municipality.create(description: "Casasco D'Intelvi", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 379)
Municipality.create(description: "Caslino D'Erba", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1714)
Municipality.create(description: "Castiglione D'Intelvi", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 760)
Municipality.create(description: "Cerano D'Intelvi", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 503)
Municipality.create(description: "Fenegro'", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2553)
Municipality.create(description: "Lanzo D'Intelvi", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1304)
Municipality.create(description: "Lurago D'Erba", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 4778)
Municipality.create(description: "Pare'", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1534)
