Comune.create(description: "Albavilla", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 5938)
Comune.create(description: "Albese Con Cassano", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 3981)
Comune.create(description: "Albiolo", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2260)
Comune.create(description: "Alserio", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1110)
Comune.create(description: "Alzate Brianza", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 4556)
Comune.create(description: "Anzano Del Parco", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1619)
Comune.create(description: "Appiano Gentile", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 7054)
Comune.create(description: "Argegno", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 654)
Comune.create(description: "Arosio", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 4469)
Comune.create(description: "Asso", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 3177)
Comune.create(description: "Barni", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 502)
Comune.create(description: "Bellagio", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2949)
Comune.create(description: "Bene Lario", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 310)
Comune.create(description: "Beregazzo Con Figliaro", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2310)
Comune.create(description: "Binago", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 4233)
Comune.create(description: "Bizzarone", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1495)
Comune.create(description: "Blessagno", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 253)
Comune.create(description: "Blevio", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1221)
Comune.create(description: "Bregnano", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 5113)
Comune.create(description: "Brenna", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1817)
Comune.create(description: "Brienno", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 425)
Comune.create(description: "Brunate", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1730)
Comune.create(description: "Bulgarograsso", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2989)
Comune.create(description: "Cabiate", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 6769)
Comune.create(description: "Cadorago", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 6593)
Comune.create(description: "Caglio", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 369)
Comune.create(description: "Cagno", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1865)
Comune.create(description: "Canzo", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 4900)
Comune.create(description: "Capiago Intimiano", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 4839)
Comune.create(description: "Carate Urio", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1209)
Comune.create(description: "Carbonate", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2575)
Comune.create(description: "Carimate", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 3805)
Comune.create(description: "Carlazzo", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2696)
Comune.create(description: "Carugo", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 5324)
Comune.create(description: "Casnate Con Bernate", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 4382)
Comune.create(description: "Cassina Rizzardi", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2379)
Comune.create(description: "Castelmarte", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1247)
Comune.create(description: "Castelnuovo Bozzente", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 777)
Comune.create(description: "Cavallasca", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2733)
Comune.create(description: "Cavargna", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 315)
Comune.create(description: "Cermenate", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 8599)
Comune.create(description: "Cernobbio", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 6662)
Comune.create(description: "Cirimido", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1914)
Comune.create(description: "Civenna", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 673)
Comune.create(description: "Claino Con Osteno", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 528)
Comune.create(description: "Colonno", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 561)
Comune.create(description: "Como", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 78680)
Comune.create(description: "Consiglio Di Rumo", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Corrido", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 730)
Comune.create(description: "Cremia", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 761)
Comune.create(description: "Cucciago", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 3196)
Comune.create(description: "Cusino", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 261)
Comune.create(description: "Dizzasco", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 491)
Comune.create(description: "Domaso", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1438)
Comune.create(description: "Dongo", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 3468)
Comune.create(description: "Dosso Del Liro", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 315)
Comune.create(description: "Drezzo", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1003)
Comune.create(description: "Erba", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 16374)
Comune.create(description: "Eupilio", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2502)
Comune.create(description: "Faggeto Lario", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1173)
Comune.create(description: "Faloppio", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 3455)
Comune.create(description: "Figino Serenza", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 4636)
Comune.create(description: "Fino Mornasco", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 8229)
Comune.create(description: "Garzeno", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1029)
Comune.create(description: "Gera Lario", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 882)
Comune.create(description: "Germasino", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Gironico", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2039)
Comune.create(description: "Grandate", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2901)
Comune.create(description: "Grandola Ed Uniti", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1267)
Comune.create(description: "Gravedona", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Griante", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 695)
Comune.create(description: "Guanzate", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 5056)
Comune.create(description: "Inverigo", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 7825)
Comune.create(description: "Laglio", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 889)
Comune.create(description: "Laino", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 469)
Comune.create(description: "Lambrugo", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2181)
Comune.create(description: "Lasnigo", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 406)
Comune.create(description: "Lenno", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1786)
Comune.create(description: "Lezzeno", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2071)
Comune.create(description: "Limido Comasco", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2265)
Comune.create(description: "Lipomo", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 5523)
Comune.create(description: "Livo", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 208)
Comune.create(description: "Locate Varesino", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 3960)
Comune.create(description: "Lomazzo", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 7968)
Comune.create(description: "Longone Al Segrino", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1455)
Comune.create(description: "Luisago", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2368)
Comune.create(description: "Lurago Marinone", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1971)
Comune.create(description: "Lurate Caccivio", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 9715)
Comune.create(description: "Magreglio", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 459)
Comune.create(description: "Mariano Comense", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 20282)
Comune.create(description: "Maslianico", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 3464)
Comune.create(description: "Menaggio", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 3121)
Comune.create(description: "Merone", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 3597)
Comune.create(description: "Mezzegra", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 952)
Comune.create(description: "Moltrasio", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1768)
Comune.create(description: "Monguzzo", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1922)
Comune.create(description: "Montano Lucino", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 4296)
Comune.create(description: "Montemezzo", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 287)
Comune.create(description: "Montorfano", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2489)
Comune.create(description: "Mozzate", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 6874)
Comune.create(description: "Musso", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1067)
Comune.create(description: "Nesso", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1302)
Comune.create(description: "Novedrate", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2889)
Comune.create(description: "Olgiate Comasco", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 10354)
Comune.create(description: "Oltrona Di San Mamette", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2097)
Comune.create(description: "Orsenigo", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2340)
Comune.create(description: "Ossuccio", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 940)
Comune.create(description: "Peglio", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 727)
Comune.create(description: "Pellio Intelvi", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 871)
Comune.create(description: "Pianello Del Lario", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1030)
Comune.create(description: "Pigra", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 302)
Comune.create(description: "Plesio", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 805)
Comune.create(description: "Pognana Lario", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 901)
Comune.create(description: "Ponna", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 262)
Comune.create(description: "Ponte Lambro", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 4066)
Comune.create(description: "Porlezza", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 4144)
Comune.create(description: "Proserpio", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 910)
Comune.create(description: "Pusiano", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1166)
Comune.create(description: "Ramponio Verna", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 403)
Comune.create(description: "Rezzago", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 274)
Comune.create(description: "Rodero", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1073)
Comune.create(description: "Ronago", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1498)
Comune.create(description: "Rovellasca", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 6279)
Comune.create(description: "Rovello Porro", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 5512)
Comune.create(description: "Sala Comacina", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 604)
Comune.create(description: "San Bartolomeo Val Cavargna", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1118)
Comune.create(description: "San Fedele Intelvi", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1491)
Comune.create(description: "San Fermo Della Battaglia", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 4189)
Comune.create(description: "San Nazzaro Val Cavargna", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 419)
Comune.create(description: "Schignano", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 935)
Comune.create(description: "Senna Comasco", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2766)
Comune.create(description: "Solbiate", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2248)
Comune.create(description: "Sorico", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1204)
Comune.create(description: "Sormano", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 633)
Comune.create(description: "Stazzona", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 675)
Comune.create(description: "Tavernerio", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 5357)
Comune.create(description: "Torno", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1222)
Comune.create(description: "Tremezzo", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1314)
Comune.create(description: "Trezzone", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 202)
Comune.create(description: "Turate", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 7851)
Comune.create(description: "Uggiate Trevano", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 )
Comune.create(description: "Val Rezzo", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 217)
Comune.create(description: "Valbrona", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2451)
Comune.create(description: "Valmorea", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2553)
Comune.create(description: "Valsolda", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1730)
Comune.create(description: "Veleso", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 297)
Comune.create(description: "Veniano", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2334)
Comune.create(description: "Vercana", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 730)
Comune.create(description: "Vertemate Con Minoprio", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 3851)
Comune.create(description: "Villa Guardia", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 6487)
Comune.create(description: "Zelbio", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 195)
Comune.create(description: "Campione D'Italia", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2267)
Comune.create(description: "Cantu'", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 35153)
Comune.create(description: "Casasco D'Intelvi", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 379)
Comune.create(description: "Caslino D'Erba", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1714)
Comune.create(description: "Castiglione D'Intelvi", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 760)
Comune.create(description: "Cerano D'Intelvi", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 503)
Comune.create(description: "Fenegro'", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2553)
Comune.create(description: "Lanzo D'Intelvi", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1304)
Comune.create(description: "Lurago D'Erba", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 4778)
Comune.create(description: "Pare'", province_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1534)
