Comune.create(description: "Albavilla", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 5938)
Comune.create(description: "Albese Con Cassano", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 3981)
Comune.create(description: "Albiolo", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2260)
Comune.create(description: "Alserio", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1110)
Comune.create(description: "Alzate Brianza", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 4556)
Comune.create(description: "Anzano Del Parco", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1619)
Comune.create(description: "Appiano Gentile", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 7054)
Comune.create(description: "Argegno", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 654)
Comune.create(description: "Arosio", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 4469)
Comune.create(description: "Asso", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 3177)
Comune.create(description: "Barni", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 502)
Comune.create(description: "Bellagio", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2949)
Comune.create(description: "Bene Lario", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 310)
Comune.create(description: "Beregazzo Con Figliaro", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2310)
Comune.create(description: "Binago", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 4233)
Comune.create(description: "Bizzarone", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1495)
Comune.create(description: "Blessagno", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 253)
Comune.create(description: "Blevio", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1221)
Comune.create(description: "Bregnano", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 5113)
Comune.create(description: "Brenna", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1817)
Comune.create(description: "Brienno", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 425)
Comune.create(description: "Brunate", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1730)
Comune.create(description: "Bulgarograsso", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2989)
Comune.create(description: "Cabiate", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 6769)
Comune.create(description: "Cadorago", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 6593)
Comune.create(description: "Caglio", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 369)
Comune.create(description: "Cagno", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1865)
Comune.create(description: "Canzo", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 4900)
Comune.create(description: "Capiago Intimiano", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 4839)
Comune.create(description: "Carate Urio", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1209)
Comune.create(description: "Carbonate", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2575)
Comune.create(description: "Carimate", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 3805)
Comune.create(description: "Carlazzo", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2696)
Comune.create(description: "Carugo", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 5324)
Comune.create(description: "Casnate Con Bernate", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 4382)
Comune.create(description: "Cassina Rizzardi", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2379)
Comune.create(description: "Castelmarte", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1247)
Comune.create(description: "Castelnuovo Bozzente", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 777)
Comune.create(description: "Cavallasca", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2733)
Comune.create(description: "Cavargna", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 315)
Comune.create(description: "Cermenate", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 8599)
Comune.create(description: "Cernobbio", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 6662)
Comune.create(description: "Cirimido", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1914)
Comune.create(description: "Civenna", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 673)
Comune.create(description: "Claino Con Osteno", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 528)
Comune.create(description: "Colonno", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 561)
Comune.create(description: "Como", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 78680)
Comune.create(description: "Consiglio Di Rumo", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Corrido", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 730)
Comune.create(description: "Cremia", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 761)
Comune.create(description: "Cucciago", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 3196)
Comune.create(description: "Cusino", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 261)
Comune.create(description: "Dizzasco", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 491)
Comune.create(description: "Domaso", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1438)
Comune.create(description: "Dongo", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 3468)
Comune.create(description: "Dosso Del Liro", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 315)
Comune.create(description: "Drezzo", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1003)
Comune.create(description: "Erba", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 16374)
Comune.create(description: "Eupilio", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2502)
Comune.create(description: "Faggeto Lario", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1173)
Comune.create(description: "Faloppio", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 3455)
Comune.create(description: "Figino Serenza", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 4636)
Comune.create(description: "Fino Mornasco", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 8229)
Comune.create(description: "Garzeno", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1029)
Comune.create(description: "Gera Lario", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 882)
Comune.create(description: "Germasino", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Gironico", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2039)
Comune.create(description: "Grandate", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2901)
Comune.create(description: "Grandola Ed Uniti", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1267)
Comune.create(description: "Gravedona", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Griante", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 695)
Comune.create(description: "Guanzate", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 5056)
Comune.create(description: "Inverigo", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 7825)
Comune.create(description: "Laglio", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 889)
Comune.create(description: "Laino", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 469)
Comune.create(description: "Lambrugo", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2181)
Comune.create(description: "Lasnigo", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 406)
Comune.create(description: "Lenno", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1786)
Comune.create(description: "Lezzeno", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2071)
Comune.create(description: "Limido Comasco", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2265)
Comune.create(description: "Lipomo", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 5523)
Comune.create(description: "Livo", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 208)
Comune.create(description: "Locate Varesino", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 3960)
Comune.create(description: "Lomazzo", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 7968)
Comune.create(description: "Longone Al Segrino", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1455)
Comune.create(description: "Luisago", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2368)
Comune.create(description: "Lurago Marinone", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1971)
Comune.create(description: "Lurate Caccivio", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 9715)
Comune.create(description: "Magreglio", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 459)
Comune.create(description: "Mariano Comense", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 20282)
Comune.create(description: "Maslianico", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 3464)
Comune.create(description: "Menaggio", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 3121)
Comune.create(description: "Merone", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 3597)
Comune.create(description: "Mezzegra", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 952)
Comune.create(description: "Moltrasio", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1768)
Comune.create(description: "Monguzzo", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1922)
Comune.create(description: "Montano Lucino", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 4296)
Comune.create(description: "Montemezzo", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 287)
Comune.create(description: "Montorfano", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2489)
Comune.create(description: "Mozzate", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 6874)
Comune.create(description: "Musso", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1067)
Comune.create(description: "Nesso", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1302)
Comune.create(description: "Novedrate", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2889)
Comune.create(description: "Olgiate Comasco", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 10354)
Comune.create(description: "Oltrona Di San Mamette", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2097)
Comune.create(description: "Orsenigo", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2340)
Comune.create(description: "Ossuccio", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 940)
Comune.create(description: "Peglio", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 727)
Comune.create(description: "Pellio Intelvi", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 871)
Comune.create(description: "Pianello Del Lario", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1030)
Comune.create(description: "Pigra", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 302)
Comune.create(description: "Plesio", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 805)
Comune.create(description: "Pognana Lario", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 901)
Comune.create(description: "Ponna", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 262)
Comune.create(description: "Ponte Lambro", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 4066)
Comune.create(description: "Porlezza", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 4144)
Comune.create(description: "Proserpio", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 910)
Comune.create(description: "Pusiano", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1166)
Comune.create(description: "Ramponio Verna", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 403)
Comune.create(description: "Rezzago", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 274)
Comune.create(description: "Rodero", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1073)
Comune.create(description: "Ronago", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1498)
Comune.create(description: "Rovellasca", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 6279)
Comune.create(description: "Rovello Porro", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 5512)
Comune.create(description: "Sala Comacina", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 604)
Comune.create(description: "San Bartolomeo Val Cavargna", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1118)
Comune.create(description: "San Fedele Intelvi", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1491)
Comune.create(description: "San Fermo Della Battaglia", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 4189)
Comune.create(description: "San Nazzaro Val Cavargna", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 419)
Comune.create(description: "Schignano", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 935)
Comune.create(description: "Senna Comasco", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2766)
Comune.create(description: "Solbiate", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2248)
Comune.create(description: "Sorico", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1204)
Comune.create(description: "Sormano", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 633)
Comune.create(description: "Stazzona", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 675)
Comune.create(description: "Tavernerio", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 5357)
Comune.create(description: "Torno", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1222)
Comune.create(description: "Tremezzo", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1314)
Comune.create(description: "Trezzone", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 202)
Comune.create(description: "Turate", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 7851)
Comune.create(description: "Uggiate Trevano", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 )
Comune.create(description: "Val Rezzo", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 217)
Comune.create(description: "Valbrona", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2451)
Comune.create(description: "Valmorea", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2553)
Comune.create(description: "Valsolda", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1730)
Comune.create(description: "Veleso", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 297)
Comune.create(description: "Veniano", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2334)
Comune.create(description: "Vercana", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 730)
Comune.create(description: "Vertemate Con Minoprio", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 3851)
Comune.create(description: "Villa Guardia", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 6487)
Comune.create(description: "Zelbio", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 195)
Comune.create(description: "Campione D'Italia", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2267)
Comune.create(description: "Cantu'", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 35153)
Comune.create(description: "Casasco D'Intelvi", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 379)
Comune.create(description: "Caslino D'Erba", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1714)
Comune.create(description: "Castiglione D'Intelvi", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 760)
Comune.create(description: "Cerano D'Intelvi", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 503)
Comune.create(description: "Fenegro'", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 2553)
Comune.create(description: "Lanzo D'Intelvi", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1304)
Comune.create(description: "Lurago D'Erba", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 4778)
Comune.create(description: "Pare'", provincia_id: 92, region_id:  19, country_id: 1, continent_id: 1 , population: 1534)
