Comune.create(description: "Acquanegra Cremonese", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1226)
Comune.create(description: "Agnadello", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 2980)
Comune.create(description: "Annicco", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1897)
Comune.create(description: "Azzanello", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 670)
Comune.create(description: "Bagnolo Cremasco", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 4523)
Comune.create(description: "Bonemerse", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1104)
Comune.create(description: "Bordolano", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 567)
Comune.create(description: "Calvatone", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1248)
Comune.create(description: "Camisano", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1225)
Comune.create(description: "Campagnola Cremasca", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 606)
Comune.create(description: "Capergnanica", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1609)
Comune.create(description: "Cappella Cantone", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 534)
Comune.create(description: "Capralba", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 2092)
Comune.create(description: "Casalbuttano Ed Uniti", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 4093)
Comune.create(description: "Casale Cremasco Vidolasco", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 )
Comune.create(description: "Casaletto Ceredano", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1097)
Comune.create(description: "Casaletto Di Sopra", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 586)
Comune.create(description: "Casaletto Vaprio", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1314)
Comune.create(description: "Casalmaggiore", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 13818)
Comune.create(description: "Casalmorano", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1653)
Comune.create(description: "Castel Gabbiano", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 392)
Comune.create(description: "Casteldidone", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 569)
Comune.create(description: "Castelleone", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 8934)
Comune.create(description: "Castelverde", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 4921)
Comune.create(description: "Castelvisconti", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 350)
Comune.create(description: "Cella Dati", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 584)
Comune.create(description: "Chieve", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1715)
Comune.create(description: "Cicognolo", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 850)
Comune.create(description: "Credera Rubbiano", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1621)
Comune.create(description: "Crema", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 32981)
Comune.create(description: "Cremona", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 70887)
Comune.create(description: "Cremosano", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1162)
Comune.create(description: "Cumignano Sul Naviglio", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 402)
Comune.create(description: "Derovere", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 350)
Comune.create(description: "Dovera", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 3494)
Comune.create(description: "Drizzona", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 551)
Comune.create(description: "Fiesco", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 861)
Comune.create(description: "Formigara", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1138)
Comune.create(description: "Gabbioneta Binanuova", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 968)
Comune.create(description: "Gadesco Pieve Delmona", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1634)
Comune.create(description: "Genivolta", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1085)
Comune.create(description: "Gombito", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 614)
Comune.create(description: "Grontardo", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1301)
Comune.create(description: "Grumello Cremonese", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 )
Comune.create(description: "Gussola", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 2800)
Comune.create(description: "Isola Dovarese", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1243)
Comune.create(description: "Izano", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1687)
Comune.create(description: "Madignano", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 2879)
Comune.create(description: "Malagnino", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1145)
Comune.create(description: "Martignana Di Po", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1258)
Comune.create(description: "Monte Cremasco", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1923)
Comune.create(description: "Montodine", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 2217)
Comune.create(description: "Moscazzano", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 785)
Comune.create(description: "Motta Baluffi", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 968)
Comune.create(description: "Offanengo", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 5511)
Comune.create(description: "Olmeneta", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 931)
Comune.create(description: "Ostiano", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 3018)
Comune.create(description: "Paderno Ponchielli", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1521)
Comune.create(description: "Palazzo Pignano", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 3590)
Comune.create(description: "Pandino", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 7802)
Comune.create(description: "Persico Dosimo", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 2657)
Comune.create(description: "Pescarolo Ed Uniti", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1485)
Comune.create(description: "Pessina Cremonese", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 755)
Comune.create(description: "Piadena", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 3516)
Comune.create(description: "Pianengo", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 2370)
Comune.create(description: "Pieranica", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 900)
Comune.create(description: "Pieve San Giacomo", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1424)
Comune.create(description: "Pizzighettone", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 6785)
Comune.create(description: "Pozzaglio Ed Uniti", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1202)
Comune.create(description: "Quintano", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 702)
Comune.create(description: "Ricengo", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1235)
Comune.create(description: "Ripalta Arpina", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 953)
Comune.create(description: "Ripalta Cremasca", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 3062)
Comune.create(description: "Ripalta Guerina", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 436)
Comune.create(description: "Rivarolo Del Re Ed Uniti", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1919)
Comune.create(description: "Romanengo", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 2517)
Comune.create(description: "Salvirola", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 933)
Comune.create(description: "San Bassano", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 2060)
Comune.create(description: "San Daniele Po", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1479)
Comune.create(description: "San Giovanni In Croce", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1543)
Comune.create(description: "San Martino Del Lago", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 476)
Comune.create(description: "Scandolara Ravara", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1585)
Comune.create(description: "Sergnano", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 3067)
Comune.create(description: "Sesto Ed Uniti", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 2808)
Comune.create(description: "Solarolo Rainerio", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 989)
Comune.create(description: "Soncino", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 7312)
Comune.create(description: "Soresina", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 8644)
Comune.create(description: "Sospiro", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 3255)
Comune.create(description: "Spinadesco", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1535)
Comune.create(description: "Spineda", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 620)
Comune.create(description: "Stagno Lombardo", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1457)
Comune.create(description: "Ticengo", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 430)
Comune.create(description: "Torlino Vimercati", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 296)
Comune.create(description: "Tornata", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 521)
Comune.create(description: "Torricella Del Pizzo", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 721)
Comune.create(description: "Trescore Cremasco", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 2374)
Comune.create(description: "Trigolo", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1680)
Comune.create(description: "Vaiano Cremasco", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 3622)
Comune.create(description: "Vailate", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 3973)
Comune.create(description: "Vescovato", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 3656)
Comune.create(description: "Volongo", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 620)
Comune.create(description: "Voltido", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 452)
Comune.create(description: "Ca' D'Andrea", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 537)
Comune.create(description: "Cappella De' Picenardi", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 424)
Comune.create(description: "Cingia De' Botti", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1277)
Comune.create(description: "Corte De' Cortesi", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Corte De' Frati", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1368)
Comune.create(description: "Crotta D'Adda", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 670)
Comune.create(description: "Gerre De' Caprioli", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 895)
Comune.create(description: "Pieve D'Olmi", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1170)
Comune.create(description: "Rivolta D'Adda", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 7012)
Comune.create(description: "Robecco D'Oglio", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 2245)
Comune.create(description: "Scandolara Ripa D'Oglio", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 636)
Comune.create(description: "Spino D'Adda", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 5905)
Comune.create(description: "Torre De' Picenardi", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1841)
