Municipality.create(description: "Acquanegra Cremonese", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1226)
Municipality.create(description: "Agnadello", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 2980)
Municipality.create(description: "Annicco", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1897)
Municipality.create(description: "Azzanello", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 670)
Municipality.create(description: "Bagnolo Cremasco", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 4523)
Municipality.create(description: "Bonemerse", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1104)
Municipality.create(description: "Bordolano", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 567)
Municipality.create(description: "Calvatone", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1248)
Municipality.create(description: "Camisano", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1225)
Municipality.create(description: "Campagnola Cremasca", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 606)
Municipality.create(description: "Capergnanica", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1609)
Municipality.create(description: "Cappella Cantone", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 534)
Municipality.create(description: "Capralba", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 2092)
Municipality.create(description: "Casalbuttano Ed Uniti", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 4093)
Municipality.create(description: "Casale Cremasco Vidolasco", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 )
Municipality.create(description: "Casaletto Ceredano", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1097)
Municipality.create(description: "Casaletto Di Sopra", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 586)
Municipality.create(description: "Casaletto Vaprio", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1314)
Municipality.create(description: "Casalmaggiore", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 13818)
Municipality.create(description: "Casalmorano", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1653)
Municipality.create(description: "Castel Gabbiano", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 392)
Municipality.create(description: "Casteldidone", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 569)
Municipality.create(description: "Castelleone", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 8934)
Municipality.create(description: "Castelverde", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 4921)
Municipality.create(description: "Castelvisconti", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 350)
Municipality.create(description: "Cella Dati", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 584)
Municipality.create(description: "Chieve", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1715)
Municipality.create(description: "Cicognolo", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 850)
Municipality.create(description: "Credera Rubbiano", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1621)
Municipality.create(description: "Crema", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 32981)
Municipality.create(description: "Cremona", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 70887)
Municipality.create(description: "Cremosano", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1162)
Municipality.create(description: "Cumignano Sul Naviglio", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 402)
Municipality.create(description: "Derovere", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 350)
Municipality.create(description: "Dovera", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 3494)
Municipality.create(description: "Drizzona", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 551)
Municipality.create(description: "Fiesco", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 861)
Municipality.create(description: "Formigara", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1138)
Municipality.create(description: "Gabbioneta Binanuova", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 968)
Municipality.create(description: "Gadesco Pieve Delmona", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1634)
Municipality.create(description: "Genivolta", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1085)
Municipality.create(description: "Gombito", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 614)
Municipality.create(description: "Grontardo", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1301)
Municipality.create(description: "Grumello Cremonese", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 )
Municipality.create(description: "Gussola", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 2800)
Municipality.create(description: "Isola Dovarese", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1243)
Municipality.create(description: "Izano", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1687)
Municipality.create(description: "Madignano", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 2879)
Municipality.create(description: "Malagnino", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1145)
Municipality.create(description: "Martignana Di Po", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1258)
Municipality.create(description: "Monte Cremasco", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1923)
Municipality.create(description: "Montodine", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 2217)
Municipality.create(description: "Moscazzano", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 785)
Municipality.create(description: "Motta Baluffi", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 968)
Municipality.create(description: "Offanengo", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 5511)
Municipality.create(description: "Olmeneta", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 931)
Municipality.create(description: "Ostiano", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 3018)
Municipality.create(description: "Paderno Ponchielli", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1521)
Municipality.create(description: "Palazzo Pignano", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 3590)
Municipality.create(description: "Pandino", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 7802)
Municipality.create(description: "Persico Dosimo", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 2657)
Municipality.create(description: "Pescarolo Ed Uniti", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1485)
Municipality.create(description: "Pessina Cremonese", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 755)
Municipality.create(description: "Piadena", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 3516)
Municipality.create(description: "Pianengo", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 2370)
Municipality.create(description: "Pieranica", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 900)
Municipality.create(description: "Pieve San Giacomo", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1424)
Municipality.create(description: "Pizzighettone", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 6785)
Municipality.create(description: "Pozzaglio Ed Uniti", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1202)
Municipality.create(description: "Quintano", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 702)
Municipality.create(description: "Ricengo", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1235)
Municipality.create(description: "Ripalta Arpina", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 953)
Municipality.create(description: "Ripalta Cremasca", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 3062)
Municipality.create(description: "Ripalta Guerina", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 436)
Municipality.create(description: "Rivarolo Del Re Ed Uniti", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1919)
Municipality.create(description: "Romanengo", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 2517)
Municipality.create(description: "Salvirola", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 933)
Municipality.create(description: "San Bassano", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 2060)
Municipality.create(description: "San Daniele Po", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1479)
Municipality.create(description: "San Giovanni In Croce", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1543)
Municipality.create(description: "San Martino Del Lago", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 476)
Municipality.create(description: "Scandolara Ravara", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1585)
Municipality.create(description: "Sergnano", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 3067)
Municipality.create(description: "Sesto Ed Uniti", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 2808)
Municipality.create(description: "Solarolo Rainerio", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 989)
Municipality.create(description: "Soncino", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 7312)
Municipality.create(description: "Soresina", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 8644)
Municipality.create(description: "Sospiro", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 3255)
Municipality.create(description: "Spinadesco", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1535)
Municipality.create(description: "Spineda", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 620)
Municipality.create(description: "Stagno Lombardo", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1457)
Municipality.create(description: "Ticengo", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 430)
Municipality.create(description: "Torlino Vimercati", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 296)
Municipality.create(description: "Tornata", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 521)
Municipality.create(description: "Torricella Del Pizzo", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 721)
Municipality.create(description: "Trescore Cremasco", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 2374)
Municipality.create(description: "Trigolo", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1680)
Municipality.create(description: "Vaiano Cremasco", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 3622)
Municipality.create(description: "Vailate", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 3973)
Municipality.create(description: "Vescovato", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 3656)
Municipality.create(description: "Volongo", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 620)
Municipality.create(description: "Voltido", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 452)
Municipality.create(description: "Ca' D'Andrea", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 537)
Municipality.create(description: "Cappella De' Picenardi", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 424)
Municipality.create(description: "Cingia De' Botti", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1277)
Municipality.create(description: "Corte De' Cortesi", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Corte De' Frati", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1368)
Municipality.create(description: "Crotta D'Adda", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 670)
Municipality.create(description: "Gerre De' Caprioli", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 895)
Municipality.create(description: "Pieve D'Olmi", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1170)
Municipality.create(description: "Rivolta D'Adda", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 7012)
Municipality.create(description: "Robecco D'Oglio", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 2245)
Municipality.create(description: "Scandolara Ripa D'Oglio", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 636)
Municipality.create(description: "Spino D'Adda", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 5905)
Municipality.create(description: "Torre De' Picenardi", province_id: 93, region_id:  19, country_id: 1, continent_id: 1 , population: 1841)
