Comune.create(description: "Abbadia Lariana", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Airuno", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Annone Di Brianza", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Ballabio", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Barzago", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Barzio", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Bellano", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Bosisio Parini", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Brivio", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Bulciago", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Calco", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Calolziocorte", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Carenno", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Casargo", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Casatenovo", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Cassago Brianza", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Cassina Valsassina", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Castello Di Brianza", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Cernusco Lombardone", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Cesana Brianza", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Civate", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Colico", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Colle Brianza", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Cortenova", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Costa Masnaga", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Crandola Valsassina", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Cremella", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Cremeno", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Dervio", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Dolzago", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Dorio", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Ello", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Erve", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Esino Lario", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Galbiate", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Garbagnate Monastero", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Garlate", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Imbersago", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Introbio", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Introzzo", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Lecco", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Lierna", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Lomagna", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Malgrate", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Mandello Del Lario", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Margno", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Merate", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Missaglia", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Moggio", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Molteno", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Monte Marenzo", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Montevecchia", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Monticello Brianza", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Morterone", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Nibionno", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Oggiono", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Olgiate Molgora", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Olginate", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Oliveto Lario", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Osnago", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Pagnona", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Parlasco", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Pasturo", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Perego", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Perledo", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Pescate", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Premana", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Primaluna", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Robbiate", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Rogeno", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Rovagnate", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Sirone", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Sirtori", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Sueglio", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Suello", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Taceno", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Tremenico", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Valgreghentino", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Valmadrera", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Varenna", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Vendrogno", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Vercurago", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Verderio Inferiore", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Verderio Superiore", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Vestreno", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Barzano'", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Paderno D'Adda", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Santa Maria Hoe'", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Torre De' Busi", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Vigano'", province_id: 94, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
