#encoding: utf-8
Comune.create(description: "Abbadia Lariana", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Airuno", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Annone Di Brianza", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Ballabio", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Barzago", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Barzio", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Bellano", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Bosisio Parini", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Brivio", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Bulciago", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Calco", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Calolziocorte", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Carenno", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Casargo", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Casatenovo", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Cassago Brianza", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Cassina Valsassina", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Castello Di Brianza", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Cernusco Lombardone", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Cesana Brianza", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Civate", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Colico", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Colle Brianza", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Cortenova", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Costa Masnaga", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Crandola Valsassina", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Cremella", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Cremeno", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Dervio", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Dolzago", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Dorio", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Ello", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Erve", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Esino Lario", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Galbiate", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Garbagnate Monastero", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Garlate", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Imbersago", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Introbio", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Introzzo", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Lecco", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Lierna", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Lomagna", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Malgrate", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Mandello Del Lario", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Margno", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Merate", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Missaglia", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Moggio", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Molteno", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Monte Marenzo", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Montevecchia", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Monticello Brianza", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Morterone", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Nibionno", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Oggiono", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Olgiate Molgora", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Olginate", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Oliveto Lario", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Osnago", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Pagnona", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Parlasco", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Pasturo", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Perego", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Perledo", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Pescate", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Premana", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Primaluna", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Robbiate", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Rogeno", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Rovagnate", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Sirone", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Sirtori", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Sueglio", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Suello", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Taceno", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Tremenico", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Valgreghentino", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Valmadrera", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Varenna", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Vendrogno", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Vercurago", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Verderio Inferiore", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Verderio Superiore", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Vestreno", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Barzano'", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Paderno D'Adda", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Santa Maria Hoe'", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Torre De' Busi", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Vigano'", provincia_id: 94, regione_id: 19, country_id: 1, continente_id: 1 , population: 0)
