Municipality.create(description: "Abbadia Cerreto", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Bertonico", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Borghetto Lodigiano", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Borgo San Giovanni", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Brembio", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Camairago", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Casaletto Lodigiano", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Casalmaiocco", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Casalpusterlengo", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Caselle Landi", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Caselle Lurani", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Castiraga Vidardo", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Cavacurta", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Codogno", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Comazzo", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Cornegliano Laudense", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Corno Giovine", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Cornovecchio", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Corte Palasio", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Crespiatica", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Fombio", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Galgagnano", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Graffignana", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Guardamiglio", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Livraga", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Lodi", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Lodi Vecchio", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Maccastorna", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Mairago", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Maleo", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Marudo", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Massalengo", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Meleti", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Merlino", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Montanaso Lombardo", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Mulazzano", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Orio Litta", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Ospedaletto Lodigiano", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Ossago Lodigiano", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Pieve Fissiraga", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Salerano Sul Lambro", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "San Fiorano", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "San Martino In Strada", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "San Rocco Al Porto", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Santo Stefano Lodigiano", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Secugnago", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Senna Lodigiana", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Somaglia", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Sordio", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Tavazzano Con Villavesco", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Terranova Dei Passerini", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Turano Lodigiano", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Valera Fratta", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Villanova Del Sillaro", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Zelo Buon Persico", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Boffalora D'Adda", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Castelnuovo Bocca D'Adda", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Castiglione D'Adda", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Cavenago D'Adda", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Cervignano D'Adda", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Sant'Angelo Lodigiano", province_id: 95, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
