#encoding: utf-8
Comune.create(description: "Abbadia Cerreto", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Bertonico", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Borghetto Lodigiano", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Borgo San Giovanni", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Brembio", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Camairago", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Casaletto Lodigiano", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Casalmaiocco", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Casalpusterlengo", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Caselle Landi", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Caselle Lurani", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Castiraga Vidardo", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Cavacurta", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Codogno", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Comazzo", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Cornegliano Laudense", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Corno Giovine", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Cornovecchio", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Corte Palasio", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Crespiatica", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Fombio", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Galgagnano", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Graffignana", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Guardamiglio", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Livraga", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Lodi", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Lodi Vecchio", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Maccastorna", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Mairago", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Maleo", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Marudo", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Massalengo", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Meleti", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Merlino", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Montanaso Lombardo", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Mulazzano", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Orio Litta", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Ospedaletto Lodigiano", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Ossago Lodigiano", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Pieve Fissiraga", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Salerano Sul Lambro", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "San Fiorano", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "San Martino In Strada", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "San Rocco Al Porto", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Santo Stefano Lodigiano", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Secugnago", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Senna Lodigiana", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Somaglia", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Sordio", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Tavazzano Con Villavesco", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Terranova Dei Passerini", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Turano Lodigiano", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Valera Fratta", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Villanova Del Sillaro", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Zelo Buon Persico", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Boffalora D'Adda", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Castelnuovo Bocca D'Adda", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Castiglione D'Adda", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Cavenago D'Adda", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Cervignano D'Adda", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
Comune.create(description: "Sant'Angelo Lodigiano", provincia_id: 95, regione_id: 19, stato_id: 1, continente_id: 1 , population: 0)
