Municipality.create(description: "Acquanegra Sul Chiese", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 2936)
Municipality.create(description: "Asola", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 9470)
Municipality.create(description: "Bagnolo San Vito", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 5432)
Municipality.create(description: "Bigarello", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 1629)
Municipality.create(description: "Borgoforte", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 3278)
Municipality.create(description: "Borgofranco Sul Po", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 896)
Municipality.create(description: "Bozzolo", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 4086)
Municipality.create(description: "Carbonara Di Po", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 1332)
Municipality.create(description: "Casalmoro", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 2049)
Municipality.create(description: "Casaloldo", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 2174)
Municipality.create(description: "Casalromano", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 1468)
Municipality.create(description: "Castel Goffredo", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 9829)
Municipality.create(description: "Castelbelforte", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 2609)
Municipality.create(description: "Castellucchio", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 4883)
Municipality.create(description: "Castiglione Delle Stiviere", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 18428)
Municipality.create(description: "Cavriana", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 3668)
Municipality.create(description: "Ceresara", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 2462)
Municipality.create(description: "Commessaggio", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 1160)
Municipality.create(description: "Curtatone", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 12354)
Municipality.create(description: "Dosolo", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 3104)
Municipality.create(description: "Felonica", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 1649)
Municipality.create(description: "Gazoldo Degli Ippoliti", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 2525)
Municipality.create(description: "Gazzuolo", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 2462)
Municipality.create(description: "Goito", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 9559)
Municipality.create(description: "Gonzaga", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 8054)
Municipality.create(description: "Guidizzolo", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 5178)
Municipality.create(description: "Magnacavallo", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 1781)
Municipality.create(description: "Mantova", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 47790)
Municipality.create(description: "Marcaria", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 6974)
Municipality.create(description: "Mariana Mantovana", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 594)
Municipality.create(description: "Marmirolo", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 7246)
Municipality.create(description: "Medole", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 3317)
Municipality.create(description: "Moglia", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 5666)
Municipality.create(description: "Monzambano", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 4549)
Municipality.create(description: "Motteggiana", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 1960)
Municipality.create(description: "Ostiglia", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 7210)
Municipality.create(description: "Pegognaga", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 6618)
Municipality.create(description: "Pieve Di Coriano", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 832)
Municipality.create(description: "Piubega", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 1630)
Municipality.create(description: "Poggio Rusco", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 6297)
Municipality.create(description: "Pomponesco", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 1555)
Municipality.create(description: "Ponti Sul Mincio", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 1912)
Municipality.create(description: "Porto Mantovano", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 13878)
Municipality.create(description: "Quingentole", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 1235)
Municipality.create(description: "Quistello", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 5871)
Municipality.create(description: "Redondesco", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 1387)
Municipality.create(description: "Revere", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 2485)
Municipality.create(description: "Rivarolo Mantovano", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 2792)
Municipality.create(description: "Rodigo", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 5023)
Municipality.create(description: "Roncoferraro", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 6604)
Municipality.create(description: "Roverbella", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 7693)
Municipality.create(description: "Sabbioneta", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 4288)
Municipality.create(description: "San Benedetto Po", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 7502)
Municipality.create(description: "San Giacomo Delle Segnate", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 1704)
Municipality.create(description: "San Giorgio Di Mantova", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 7542)
Municipality.create(description: "San Giovanni Del Dosso", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 1180)
Municipality.create(description: "Schivenoglia", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 1234)
Municipality.create(description: "Sermide", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 6486)
Municipality.create(description: "Serravalle A Po", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 1722)
Municipality.create(description: "Solferino", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 2294)
Municipality.create(description: "Sustinente", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 2266)
Municipality.create(description: "Suzzara", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 17643)
Municipality.create(description: "Viadana", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 16933)
Municipality.create(description: "Villa Poma", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 2036)
Municipality.create(description: "Villimpenta", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 2105)
Municipality.create(description: "Virgilio", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 10023)
Municipality.create(description: "Volta Mantovana", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 6628)
Municipality.create(description: "Canneto Sull'Oglio", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 4543)
Municipality.create(description: "Castel D'Ario", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 4231)
Municipality.create(description: "San Martino Dall'Argine", province_id: 96, region_id:  19, country_id: 1, continent_id: 1 , population: 1857)
