#encoding: utf-8
Comune.create(:description => "Abbiategrasso", :provincia_id => 97, :regione_id => 19, :population => 27739)
Comune.create(:description => "Agrate Brianza", :provincia_id => 97, :regione_id => 19, :population => 0)
Comune.create(:description => "Aicurzio", :provincia_id => 97, :regione_id => 19, :population => 0)
Comune.create(:description => "Albairate", :provincia_id => 97, :regione_id => 19, :population => 4148)
Comune.create(:description => "Albiate", :provincia_id => 97, :regione_id => 19, :population => 0)
Comune.create(:description => "Arconate", :provincia_id => 97, :regione_id => 19, :population => 5440)
Comune.create(:description => "Arcore", :provincia_id => 97, :regione_id => 19, :population => 0)
Comune.create(:description => "Arese", :provincia_id => 97, :regione_id => 19, :population => 18771)
Comune.create(:description => "Arluno", :provincia_id => 97, :regione_id => 19, :population => 9815)
Comune.create(:description => "Assago", :provincia_id => 97, :regione_id => 19, :population => 7447)
Comune.create(:description => "Bareggio", :provincia_id => 97, :regione_id => 19, :population => 15759)
Comune.create(:description => "Barlassina", :provincia_id => 97, :regione_id => 19, :population => 0)
Comune.create(:description => "Basiano", :provincia_id => 97, :regione_id => 19, :population => 2868)
Comune.create(:description => "Basiglio", :provincia_id => 97, :regione_id => 19, :population => 8336)
Comune.create(:description => "Bellinzago Lombardo", :provincia_id => 97, :regione_id => 19, :population => 3538)
Comune.create(:description => "Bellusco", :provincia_id => 97, :regione_id => 19, :population => 0)
Comune.create(:description => "Bernareggio", :provincia_id => 97, :regione_id => 19, :population => 0)
Comune.create(:description => "Bernate Ticino", :provincia_id => 97, :regione_id => 19, :population => 2941)
Comune.create(:description => "Besana In Brianza", :provincia_id => 97, :regione_id => 19, :population => 0)
Comune.create(:description => "Besate", :provincia_id => 97, :regione_id => 19, :population => 1729)
Comune.create(:description => "Biassono", :provincia_id => 97, :regione_id => 19, :population => 0)
Comune.create(:description => "Binasco", :provincia_id => 97, :regione_id => 19, :population => 6921)
Comune.create(:description => "Boffalora Sopra Ticino", :provincia_id => 97, :regione_id => 19, :population => 4265)
Comune.create(:description => "Bollate", :provincia_id => 97, :regione_id => 19, :population => 46781)
Comune.create(:description => "Bovisio-Masciago", :provincia_id => 97, :regione_id => 19, :population => 0)
Comune.create(:description => "Bresso", :provincia_id => 97, :regione_id => 19, :population => 27132)
Comune.create(:description => "Briosco", :provincia_id => 97, :regione_id => 19, :population => 0)
Comune.create(:description => "Brugherio", :provincia_id => 97, :regione_id => 19, :population => 0)
Comune.create(:description => "Bubbiano", :provincia_id => 97, :regione_id => 19, :population => 1404)
Comune.create(:description => "Buccinasco", :provincia_id => 97, :regione_id => 19, :population => 24877)
Comune.create(:description => "Burago Di Molgora", :provincia_id => 97, :regione_id => 19, :population => 0)
Comune.create(:description => "Buscate", :provincia_id => 97, :regione_id => 19, :population => 4228)
Comune.create(:description => "Busnago", :provincia_id => 97, :regione_id => 19, :population => 4576)
Comune.create(:description => "Bussero", :provincia_id => 97, :regione_id => 19, :population => 8493)
Comune.create(:description => "Busto Garolfo", :provincia_id => 97, :regione_id => 19, :population => 12506)
Comune.create(:description => "Calvignasco", :provincia_id => 97, :regione_id => 19, :population => 1029)
Comune.create(:description => "Cambiago", :provincia_id => 97, :regione_id => 19, :population => 4852)
Comune.create(:description => "Camparada", :provincia_id => 97, :regione_id => 19, :population => 0)
Comune.create(:description => "Canegrate", :provincia_id => 97, :regione_id => 19, :population => 11810)
Comune.create(:description => "Caponago", :provincia_id => 97, :regione_id => 19, :population => 4524)
Comune.create(:description => "Carate Brianza", :provincia_id => 97, :regione_id => 19, :population => 0)
Comune.create(:description => "Carnate", :provincia_id => 97, :regione_id => 19, :population => 0)
Comune.create(:description => "Carpiano", :provincia_id => 97, :regione_id => 19, :population => 2409)
Comune.create(:description => "Carugate", :provincia_id => 97, :regione_id => 19, :population => 12635)
Comune.create(:description => "Casarile", :provincia_id => 97, :regione_id => 19, :population => 3572)
Comune.create(:description => "Casorezzo", :provincia_id => 97, :regione_id => 19, :population => 4633)
Comune.create(:description => "Cassinetta Di Lugagnano", :provincia_id => 97, :regione_id => 19, :population => 1577)
Comune.create(:description => "Castano Primo", :provincia_id => 97, :regione_id => 19, :population => 9951)
Comune.create(:description => "Cavenago Di Brianza", :provincia_id => 97, :regione_id => 19, :population => 0)
Comune.create(:description => "Ceriano Laghetto", :provincia_id => 97, :regione_id => 19, :population => 0)
Comune.create(:description => "Cernusco Sul Naviglio", :provincia_id => 97, :regione_id => 19, :population => 26958)
Comune.create(:description => "Cerro Al Lambro", :provincia_id => 97, :regione_id => 19, :population => 4348)
Comune.create(:description => "Cerro Maggiore", :provincia_id => 97, :regione_id => 19, :population => 13893)
Comune.create(:description => "Cesano Boscone", :provincia_id => 97, :regione_id => 19, :population => 23593)
Comune.create(:description => "Cesano Maderno", :provincia_id => 97, :regione_id => 19, :population => 0)
Comune.create(:description => "Cesate", :provincia_id => 97, :regione_id => 19, :population => 12317)
Comune.create(:description => "Cinisello Balsamo", :provincia_id => 97, :regione_id => 19, :population => 72050)
Comune.create(:description => "Cisliano", :provincia_id => 97, :regione_id => 19, :population => 3303)
Comune.create(:description => "Cogliate", :provincia_id => 97, :regione_id => 19, :population => 0)
Comune.create(:description => "Cologno Monzese", :provincia_id => 97, :regione_id => 19, :population => 48262)
Comune.create(:description => "Colturano", :provincia_id => 97, :regione_id => 19, :population => 1934)
Comune.create(:description => "Concorezzo", :provincia_id => 97, :regione_id => 19, :population => 0)
Comune.create(:description => "Corbetta", :provincia_id => 97, :regione_id => 19, :population => 13735)
Comune.create(:description => "Cormano", :provincia_id => 97, :regione_id => 19, :population => 18056)
Comune.create(:description => "Cornaredo", :provincia_id => 97, :regione_id => 19, :population => 19928)
Comune.create(:description => "Correzzana", :provincia_id => 97, :regione_id => 19, :population => 0)
Comune.create(:description => "Corsico", :provincia_id => 97, :regione_id => 19, :population => 33273)
Comune.create(:description => "Cuggiono", :provincia_id => 97, :regione_id => 19, :population => 7516)
Comune.create(:description => "Cusago", :provincia_id => 97, :regione_id => 19, :population => 3046)
Comune.create(:description => "Cusano Milanino", :provincia_id => 97, :regione_id => 19, :population => 19850)
Comune.create(:description => "Dairago", :provincia_id => 97, :regione_id => 19, :population => 4580)
Comune.create(:description => "Desio", :provincia_id => 97, :regione_id => 19, :population => 0)
Comune.create(:description => "Dresano", :provincia_id => 97, :regione_id => 19, :population => 2342)
Comune.create(:description => "Gaggiano", :provincia_id => 97, :regione_id => 19, :population => 8111)
Comune.create(:description => "Garbagnate Milanese", :provincia_id => 97, :regione_id => 19, :population => 27276)
Comune.create(:description => "Gessate", :provincia_id => 97, :regione_id => 19, :population => 5508)
Comune.create(:description => "Giussano", :provincia_id => 97, :regione_id => 19, :population => 0)
Comune.create(:description => "Gorgonzola", :provincia_id => 97, :regione_id => 19, :population => 17674)
Comune.create(:description => "Grezzago", :provincia_id => 97, :regione_id => 19, :population => 2090)
Comune.create(:description => "Gudo Visconti", :provincia_id => 97, :regione_id => 19, :population => 1309)
Comune.create(:description => "Inveruno", :provincia_id => 97, :regione_id => 19, :population => 8236)
Comune.create(:description => "Inzago", :provincia_id => 97, :regione_id => 19, :population => 8919)
Comune.create(:description => "Lacchiarella", :provincia_id => 97, :regione_id => 19, :population => 7248)
Comune.create(:description => "Lainate", :provincia_id => 97, :regione_id => 19, :population => 23660)
Comune.create(:description => "Lazzate", :provincia_id => 97, :regione_id => 19, :population => 0)
Comune.create(:description => "Legnano", :provincia_id => 97, :regione_id => 19, :population => 53797)
Comune.create(:description => "Lentate Sul Seveso", :provincia_id => 97, :regione_id => 19, :population => 14366)
Comune.create(:description => "Lesmo", :provincia_id => 97, :regione_id => 19, :population => 0)
Comune.create(:description => "Limbiate", :provincia_id => 97, :regione_id => 19, :population => 0)
Comune.create(:description => "Liscate", :provincia_id => 97, :regione_id => 19, :population => 3408)
Comune.create(:description => "Lissone", :provincia_id => 97, :regione_id => 19, :population => 0)
Comune.create(:description => "Locate Di Triulzi", :provincia_id => 97, :regione_id => 19, :population => 8222)
Comune.create(:description => "Macherio", :provincia_id => 97, :regione_id => 19, :population => 0)
Comune.create(:description => "Magenta", :provincia_id => 97, :regione_id => 19, :population => 22839)
Comune.create(:description => "Magnago", :provincia_id => 97, :regione_id => 19, :population => 7811)
Comune.create(:description => "Marcallo Con Casone", :provincia_id => 97, :regione_id => 19, :population => 5192)
Comune.create(:description => "Masate", :provincia_id => 97, :regione_id => 19, :population => 2459)
Comune.create(:description => "Meda", :provincia_id => 97, :regione_id => 19, :population => 0)
Comune.create(:description => "Mediglia", :provincia_id => 97, :regione_id => 19, :population => 10287)
Comune.create(:description => "Melegnano", :provincia_id => 97, :regione_id => 19, :population => 15761)
Comune.create(:description => "Melzo", :provincia_id => 97, :regione_id => 19, :population => 18546)
Comune.create(:description => "Mesero", :provincia_id => 97, :regione_id => 19, :population => 3490)
Comune.create(:description => "Mezzago", :provincia_id => 97, :regione_id => 19, :population => 0)
Comune.create(:description => "Milano", :provincia_id => 97, :regione_id => 19, :population => 1256210)
Comune.create(:description => "Misinto", :provincia_id => 97, :regione_id => 19, :population => 0)
Comune.create(:description => "Monza", :provincia_id => 97, :regione_id => 19, :population => 0)
Comune.create(:description => "Morimondo", :provincia_id => 97, :regione_id => 19, :population => 1134)
Comune.create(:description => "Motta Visconti", :provincia_id => 97, :regione_id => 19, :population => 6242)
Comune.create(:description => "Nerviano", :provincia_id => 97, :regione_id => 19, :population => 16810)
Comune.create(:description => "Nosate", :provincia_id => 97, :regione_id => 19, :population => 638)
Comune.create(:description => "Nova Milanese", :provincia_id => 97, :regione_id => 19, :population => 0)
Comune.create(:description => "Novate Milanese", :provincia_id => 97, :regione_id => 19, :population => 19889)
Comune.create(:description => "Noviglio", :provincia_id => 97, :regione_id => 19, :population => 3025)
Comune.create(:description => "Opera", :provincia_id => 97, :regione_id => 19, :population => 13373)
Comune.create(:description => "Ornago", :provincia_id => 97, :regione_id => 19, :population => 0)
Comune.create(:description => "Ossona", :provincia_id => 97, :regione_id => 19, :population => 3757)
Comune.create(:description => "Ozzero", :provincia_id => 97, :regione_id => 19, :population => 1347)
Comune.create(:description => "Paderno Dugnano", :provincia_id => 97, :regione_id => 19, :population => 45444)
Comune.create(:description => "Pantigliate", :provincia_id => 97, :regione_id => 19, :population => 5154)
Comune.create(:description => "Parabiago", :provincia_id => 97, :regione_id => 19, :population => 23950)
Comune.create(:description => "Paullo", :provincia_id => 97, :regione_id => 19, :population => 10108)
Comune.create(:description => "Pero", :provincia_id => 97, :regione_id => 19, :population => 10373)
Comune.create(:description => "Peschiera Borromeo", :provincia_id => 97, :regione_id => 19, :population => 20264)
Comune.create(:description => "Pessano Con Bornago", :provincia_id => 97, :regione_id => 19, :population => 8309)
Comune.create(:description => "Pieve Emanuele", :provincia_id => 97, :regione_id => 19, :population => 15759)
Comune.create(:description => "Pioltello", :provincia_id => 97, :regione_id => 19, :population => 31936)
Comune.create(:description => "Pogliano Milanese", :provincia_id => 97, :regione_id => 19, :population => 7828)
Comune.create(:description => "Pozzuolo Martesana", :provincia_id => 97, :regione_id => 19, :population => 7233)
Comune.create(:description => "Pregnana Milanese", :provincia_id => 97, :regione_id => 19, :population => 5985)
Comune.create(:description => "Renate", :provincia_id => 97, :regione_id => 19, :population => 0)
Comune.create(:description => "Rescaldina", :provincia_id => 97, :regione_id => 19, :population => 13025)
Comune.create(:description => "Rho", :provincia_id => 97, :regione_id => 19, :population => 50246)
Comune.create(:description => "Robecchetto Con Induno", :provincia_id => 97, :regione_id => 19, :population => 4320)
Comune.create(:description => "Robecco Sul Naviglio", :provincia_id => 97, :regione_id => 19, :population => 6174)
Comune.create(:description => "Rodano", :provincia_id => 97, :regione_id => 19, :population => 4325)
Comune.create(:description => "Roncello", :provincia_id => 97, :regione_id => 19, :population => 2354)
Comune.create(:description => "Ronco Briantino", :provincia_id => 97, :regione_id => 19, :population => 0)
Comune.create(:description => "Rosate", :provincia_id => 97, :regione_id => 19, :population => 4717)
Comune.create(:description => "Rozzano", :provincia_id => 97, :regione_id => 19, :population => 37207)
Comune.create(:description => "San Colombano Al Lambro", :provincia_id => 97, :regione_id => 19, :population => 7258)
Comune.create(:description => "San Donato Milanese", :provincia_id => 97, :regione_id => 19, :population => 32354)
Comune.create(:description => "San Giorgio Su Legnano", :provincia_id => 97, :regione_id => 19, :population => 6173)
Comune.create(:description => "San Giuliano Milanese", :provincia_id => 97, :regione_id => 19, :population => 31295)
Comune.create(:description => "San Vittore Olona", :provincia_id => 97, :regione_id => 19, :population => 7437)
Comune.create(:description => "San Zenone Al Lambro", :provincia_id => 97, :regione_id => 19, :population => 3446)
Comune.create(:description => "Santo Stefano Ticino", :provincia_id => 97, :regione_id => 19, :population => 3870)
Comune.create(:description => "Sedriano", :provincia_id => 97, :regione_id => 19, :population => 10197)
Comune.create(:description => "Segrate", :provincia_id => 97, :regione_id => 19, :population => 33199)
Comune.create(:description => "Senago", :provincia_id => 97, :regione_id => 19, :population => 18899)
Comune.create(:description => "Seregno", :provincia_id => 97, :regione_id => 19, :population => 0)
Comune.create(:description => "Sesto San Giovanni", :provincia_id => 97, :regione_id => 19, :population => 78850)
Comune.create(:description => "Settala", :provincia_id => 97, :regione_id => 19, :population => 5790)
Comune.create(:description => "Settimo Milanese", :provincia_id => 97, :regione_id => 19, :population => 17134)
Comune.create(:description => "Seveso", :provincia_id => 97, :regione_id => 19, :population => 0)
Comune.create(:description => "Solaro", :provincia_id => 97, :regione_id => 19, :population => 12026)
Comune.create(:description => "Sovico", :provincia_id => 97, :regione_id => 19, :population => 0)
Comune.create(:description => "Sulbiate", :provincia_id => 97, :regione_id => 19, :population => 0)
Comune.create(:description => "Trezzano Rosa", :provincia_id => 97, :regione_id => 19, :population => 3760)
Comune.create(:description => "Trezzano Sul Naviglio", :provincia_id => 97, :regione_id => 19, :population => 18114)
Comune.create(:description => "Tribiano", :provincia_id => 97, :regione_id => 19, :population => 2234)
Comune.create(:description => "Triuggio", :provincia_id => 97, :regione_id => 19, :population => 0)
Comune.create(:description => "Truccazzano", :provincia_id => 97, :regione_id => 19, :population => 4353)
Comune.create(:description => "Turbigo", :provincia_id => 97, :regione_id => 19, :population => 7225)
Comune.create(:description => "Usmate Velate", :provincia_id => 97, :regione_id => 19, :population => 0)
Comune.create(:description => "Vanzaghello", :provincia_id => 97, :regione_id => 19, :population => 4883)
Comune.create(:description => "Vanzago", :provincia_id => 97, :regione_id => 19, :population => 6783)
Comune.create(:description => "Varedo", :provincia_id => 97, :regione_id => 19, :population => 0)
Comune.create(:description => "Vedano Al Lambro", :provincia_id => 97, :regione_id => 19, :population => 0)
Comune.create(:description => "Veduggio Con Colzano", :provincia_id => 97, :regione_id => 19, :population => 0)
Comune.create(:description => "Verano Brianza", :provincia_id => 97, :regione_id => 19, :population => 0)
Comune.create(:description => "Vermezzo", :provincia_id => 97, :regione_id => 19, :population => 3091)
Comune.create(:description => "Vernate", :provincia_id => 97, :regione_id => 19, :population => 2345)
Comune.create(:description => "Vignate", :provincia_id => 97, :regione_id => 19, :population => 7854)
Comune.create(:description => "Villa Cortese", :provincia_id => 97, :regione_id => 19, :population => 6113)
Comune.create(:description => "Villasanta", :provincia_id => 97, :regione_id => 19, :population => 0)
Comune.create(:description => "Vimercate", :provincia_id => 97, :regione_id => 19, :population => 0)
Comune.create(:description => "Vimodrone", :provincia_id => 97, :regione_id => 19, :population => 13868)
Comune.create(:description => "Vittuone", :provincia_id => 97, :regione_id => 19, :population => 7526)
Comune.create(:description => "Vizzolo Predabissi", :provincia_id => 97, :regione_id => 19, :population => 4023)
Comune.create(:description => "Zelo Surrigone", :provincia_id => 97, :regione_id => 19, :population => 1110)
Comune.create(:description => "Zibido San Giacomo", :provincia_id => 97, :regione_id => 19, :population => 5415)
Comune.create(:description => "Calusco D'Adda", :provincia_id => 97, :regione_id => 19, :population => 8052)
Comune.create(:description => "Cassano D'Adda", :provincia_id => 97, :regione_id => 19, :population => 16665)
Comune.create(:description => "Cassina De' Pecchi", :provincia_id => 97, :regione_id => 19, :population => 12326)
Comune.create(:description => "Cornate D'Adda", :provincia_id => 97, :regione_id => 19, :population => 9238)
Comune.create(:description => "Muggio'", :provincia_id => 97, :regione_id => 19, :population => 0)
Comune.create(:description => "Pozzo D'Adda", :provincia_id => 97, :regione_id => 19, :population => 3515)
Comune.create(:description => "Trezzo Sull'Adda", :provincia_id => 97, :regione_id => 19, :population => 11596)
Comune.create(:description => "Vaprio D'Adda", :provincia_id => 97, :regione_id => 19, :population => 6636)
