Municipality.create(description: "Abbiategrasso", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 27739)
Municipality.create(description: "Agrate Brianza", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Aicurzio", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Albairate", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 4148)
Municipality.create(description: "Albiate", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Arconate", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 5440)
Municipality.create(description: "Arcore", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Arese", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 18771)
Municipality.create(description: "Arluno", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 9815)
Municipality.create(description: "Assago", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 7447)
Municipality.create(description: "Bareggio", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 15759)
Municipality.create(description: "Barlassina", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Basiano", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 2868)
Municipality.create(description: "Basiglio", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 8336)
Municipality.create(description: "Bellinzago Lombardo", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 3538)
Municipality.create(description: "Bellusco", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Bernareggio", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Bernate Ticino", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 2941)
Municipality.create(description: "Besana In Brianza", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Besate", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 1729)
Municipality.create(description: "Biassono", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Binasco", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 6921)
Municipality.create(description: "Boffalora Sopra Ticino", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 4265)
Municipality.create(description: "Bollate", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 46781)
Municipality.create(description: "Bovisio-Masciago", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Bresso", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 27132)
Municipality.create(description: "Briosco", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Brugherio", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Bubbiano", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 1404)
Municipality.create(description: "Buccinasco", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 24877)
Municipality.create(description: "Burago Di Molgora", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Buscate", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 4228)
Municipality.create(description: "Busnago", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 4576)
Municipality.create(description: "Bussero", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 8493)
Municipality.create(description: "Busto Garolfo", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 12506)
Municipality.create(description: "Calvignasco", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 1029)
Municipality.create(description: "Cambiago", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 4852)
Municipality.create(description: "Camparada", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Canegrate", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 11810)
Municipality.create(description: "Caponago", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 4524)
Municipality.create(description: "Carate Brianza", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Carnate", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Carpiano", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 2409)
Municipality.create(description: "Carugate", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 12635)
Municipality.create(description: "Casarile", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 3572)
Municipality.create(description: "Casorezzo", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 4633)
Municipality.create(description: "Cassinetta Di Lugagnano", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 1577)
Municipality.create(description: "Castano Primo", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 9951)
Municipality.create(description: "Cavenago Di Brianza", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Ceriano Laghetto", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Cernusco Sul Naviglio", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 26958)
Municipality.create(description: "Cerro Al Lambro", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 4348)
Municipality.create(description: "Cerro Maggiore", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 13893)
Municipality.create(description: "Cesano Boscone", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 23593)
Municipality.create(description: "Cesano Maderno", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Cesate", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 12317)
Municipality.create(description: "Cinisello Balsamo", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 72050)
Municipality.create(description: "Cisliano", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 3303)
Municipality.create(description: "Cogliate", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Cologno Monzese", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 48262)
Municipality.create(description: "Colturano", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 1934)
Municipality.create(description: "Concorezzo", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Corbetta", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 13735)
Municipality.create(description: "Cormano", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 18056)
Municipality.create(description: "Cornaredo", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 19928)
Municipality.create(description: "Correzzana", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Corsico", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 33273)
Municipality.create(description: "Cuggiono", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 7516)
Municipality.create(description: "Cusago", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 3046)
Municipality.create(description: "Cusano Milanino", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 19850)
Municipality.create(description: "Dairago", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 4580)
Municipality.create(description: "Desio", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Dresano", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 2342)
Municipality.create(description: "Gaggiano", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 8111)
Municipality.create(description: "Garbagnate Milanese", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 27276)
Municipality.create(description: "Gessate", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 5508)
Municipality.create(description: "Giussano", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Gorgonzola", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 17674)
Municipality.create(description: "Grezzago", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 2090)
Municipality.create(description: "Gudo Visconti", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 1309)
Municipality.create(description: "Inveruno", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 8236)
Municipality.create(description: "Inzago", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 8919)
Municipality.create(description: "Lacchiarella", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 7248)
Municipality.create(description: "Lainate", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 23660)
Municipality.create(description: "Lazzate", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Legnano", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 53797)
Municipality.create(description: "Lentate Sul Seveso", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 14366)
Municipality.create(description: "Lesmo", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Limbiate", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Liscate", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 3408)
Municipality.create(description: "Lissone", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Locate Di Triulzi", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 8222)
Municipality.create(description: "Macherio", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Magenta", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 22839)
Municipality.create(description: "Magnago", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 7811)
Municipality.create(description: "Marcallo Con Casone", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 5192)
Municipality.create(description: "Masate", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 2459)
Municipality.create(description: "Meda", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Mediglia", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 10287)
Municipality.create(description: "Melegnano", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 15761)
Municipality.create(description: "Melzo", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 18546)
Municipality.create(description: "Mesero", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 3490)
Municipality.create(description: "Mezzago", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Milano", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 1256210)
Municipality.create(description: "Misinto", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Monza", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Morimondo", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 1134)
Municipality.create(description: "Motta Visconti", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 6242)
Municipality.create(description: "Nerviano", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 16810)
Municipality.create(description: "Nosate", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 638)
Municipality.create(description: "Nova Milanese", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Novate Milanese", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 19889)
Municipality.create(description: "Noviglio", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 3025)
Municipality.create(description: "Opera", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 13373)
Municipality.create(description: "Ornago", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Ossona", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 3757)
Municipality.create(description: "Ozzero", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 1347)
Municipality.create(description: "Paderno Dugnano", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 45444)
Municipality.create(description: "Pantigliate", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 5154)
Municipality.create(description: "Parabiago", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 23950)
Municipality.create(description: "Paullo", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 10108)
Municipality.create(description: "Pero", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 10373)
Municipality.create(description: "Peschiera Borromeo", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 20264)
Municipality.create(description: "Pessano Con Bornago", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 8309)
Municipality.create(description: "Pieve Emanuele", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 15759)
Municipality.create(description: "Pioltello", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 31936)
Municipality.create(description: "Pogliano Milanese", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 7828)
Municipality.create(description: "Pozzuolo Martesana", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 7233)
Municipality.create(description: "Pregnana Milanese", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 5985)
Municipality.create(description: "Renate", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Rescaldina", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 13025)
Municipality.create(description: "Rho", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 50246)
Municipality.create(description: "Robecchetto Con Induno", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 4320)
Municipality.create(description: "Robecco Sul Naviglio", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 6174)
Municipality.create(description: "Rodano", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 4325)
Municipality.create(description: "Roncello", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 2354)
Municipality.create(description: "Ronco Briantino", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Rosate", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 4717)
Municipality.create(description: "Rozzano", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 37207)
Municipality.create(description: "San Colombano Al Lambro", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 7258)
Municipality.create(description: "San Donato Milanese", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 32354)
Municipality.create(description: "San Giorgio Su Legnano", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 6173)
Municipality.create(description: "San Giuliano Milanese", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 31295)
Municipality.create(description: "San Vittore Olona", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 7437)
Municipality.create(description: "San Zenone Al Lambro", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 3446)
Municipality.create(description: "Santo Stefano Ticino", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 3870)
Municipality.create(description: "Sedriano", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 10197)
Municipality.create(description: "Segrate", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 33199)
Municipality.create(description: "Senago", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 18899)
Municipality.create(description: "Seregno", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Sesto San Giovanni", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 78850)
Municipality.create(description: "Settala", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 5790)
Municipality.create(description: "Settimo Milanese", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 17134)
Municipality.create(description: "Seveso", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Solaro", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 12026)
Municipality.create(description: "Sovico", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Sulbiate", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Trezzano Rosa", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 3760)
Municipality.create(description: "Trezzano Sul Naviglio", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 18114)
Municipality.create(description: "Tribiano", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 2234)
Municipality.create(description: "Triuggio", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Truccazzano", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 4353)
Municipality.create(description: "Turbigo", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 7225)
Municipality.create(description: "Usmate Velate", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Vanzaghello", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 4883)
Municipality.create(description: "Vanzago", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 6783)
Municipality.create(description: "Varedo", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Vedano Al Lambro", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Veduggio Con Colzano", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Verano Brianza", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Vermezzo", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 3091)
Municipality.create(description: "Vernate", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 2345)
Municipality.create(description: "Vignate", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 7854)
Municipality.create(description: "Villa Cortese", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 6113)
Municipality.create(description: "Villasanta", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Vimercate", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Vimodrone", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 13868)
Municipality.create(description: "Vittuone", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 7526)
Municipality.create(description: "Vizzolo Predabissi", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 4023)
Municipality.create(description: "Zelo Surrigone", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 1110)
Municipality.create(description: "Zibido San Giacomo", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 5415)
Municipality.create(description: "Calusco D'Adda", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 8052)
Municipality.create(description: "Cassano D'Adda", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 16665)
Municipality.create(description: "Cassina De' Pecchi", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 12326)
Municipality.create(description: "Cornate D'Adda", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 9238)
Municipality.create(description: "Muggio'", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Pozzo D'Adda", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 3515)
Municipality.create(description: "Trezzo Sull'Adda", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 11596)
Municipality.create(description: "Vaprio D'Adda", province_id: 97, region_id:  19, country_id: 1, continent_id: 1 , population: 6636)
