Comune.create(description: "Cassolnovo", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 5820)
Comune.create(description: "Alagna", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 755)
Comune.create(description: "Albaredo Arnaboldi", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 205)
Comune.create(description: "Albonese", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 504)
Comune.create(description: "Albuzzano", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 2256)
Comune.create(description: "Arena Po", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1572)
Comune.create(description: "Badia Pavese", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 394)
Comune.create(description: "Bagnaria", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 639)
Comune.create(description: "Barbianello", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 816)
Comune.create(description: "Bastida Pancarana", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 894)
Comune.create(description: "Battuda", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 352)
Comune.create(description: "Belgioioso", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 5357)
Comune.create(description: "Bereguardo", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 2390)
Comune.create(description: "Borgarello", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1609)
Comune.create(description: "Borgo Priolo", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1405)
Comune.create(description: "Borgo San Siro", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1023)
Comune.create(description: "Borgoratto Mormorolo", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 434)
Comune.create(description: "Bornasco", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1677)
Comune.create(description: "Bosnasco", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 600)
Comune.create(description: "Brallo Di Pregola", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 930)
Comune.create(description: "Breme", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 936)
Comune.create(description: "Bressana Bottarone", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 3143)
Comune.create(description: "Broni", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 9347)
Comune.create(description: "Calvignano", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 130)
Comune.create(description: "Campospinoso", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 772)
Comune.create(description: "Candia Lomellina", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1646)
Comune.create(description: "Canevino", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 131)
Comune.create(description: "Canneto Pavese", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1338)
Comune.create(description: "Carbonara Al Ticino", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1289)
Comune.create(description: "Casanova Lonati", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 427)
Comune.create(description: "Casatisma", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 856)
Comune.create(description: "Casei Gerola", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 2536)
Comune.create(description: "Casorate Primo", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 7028)
Comune.create(description: "Castana", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 754)
Comune.create(description: "Casteggio", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 6337)
Comune.create(description: "Castelletto Di Branduzzo", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1023)
Comune.create(description: "Castelnovetto", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 643)
Comune.create(description: "Cava Manara", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 5321)
Comune.create(description: "Cecima", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 276)
Comune.create(description: "Ceranova", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1151)
Comune.create(description: "Ceretto Lomellina", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 211)
Comune.create(description: "Cergnago", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 764)
Comune.create(description: "Certosa Di Pavia", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 3320)
Comune.create(description: "Cervesina", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1200)
Comune.create(description: "Chignolo Po", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 3234)
Comune.create(description: "Cigognola", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1367)
Comune.create(description: "Cilavegna", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 4979)
Comune.create(description: "Codevilla", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 917)
Comune.create(description: "Confienza", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1636)
Comune.create(description: "Copiano", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1364)
Comune.create(description: "Corana", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 790)
Comune.create(description: "Cornale", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 734)
Comune.create(description: "Corteolona", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1906)
Comune.create(description: "Corvino San Quirico", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1092)
Comune.create(description: "Cozzo", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 432)
Comune.create(description: "Cura Carpignano", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 2145)
Comune.create(description: "Dorno", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 4184)
Comune.create(description: "Ferrera Erbognone", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1103)
Comune.create(description: "Filighera", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 843)
Comune.create(description: "Fortunago", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 420)
Comune.create(description: "Frascarolo", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1321)
Comune.create(description: "Galliavola", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 232)
Comune.create(description: "Gambarana", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 281)
Comune.create(description: "Garlasco", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Comune.create(description: "Genzone", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 345)
Comune.create(description: "Gerenzago", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 913)
Comune.create(description: "Giussago", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 3915)
Comune.create(description: "Godiasco", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 2806)
Comune.create(description: "Golferenzo", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 233)
Comune.create(description: "Gravellona Lomellina", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 2173)
Comune.create(description: "Gropello Cairoli", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 4105)
Comune.create(description: "Inverno E Monteleone", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1069)
Comune.create(description: "Landriano", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 4171)
Comune.create(description: "Langosco", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 458)
Comune.create(description: "Lardirago", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1163)
Comune.create(description: "Linarolo", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 2172)
Comune.create(description: "Lirio", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 147)
Comune.create(description: "Lomello", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 2378)
Comune.create(description: "Lungavilla", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 2154)
Comune.create(description: "Magherno", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1380)
Comune.create(description: "Marcignago", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1923)
Comune.create(description: "Marzano", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1025)
Comune.create(description: "Mede", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 6924)
Comune.create(description: "Menconico", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 494)
Comune.create(description: "Mezzana Bigli", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1168)
Comune.create(description: "Mezzana Rabattone", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 532)
Comune.create(description: "Mezzanino", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1468)
Comune.create(description: "Miradolo Terme", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 3177)
Comune.create(description: "Montalto Pavese", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 963)
Comune.create(description: "Montebello Della Battaglia", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1647)
Comune.create(description: "Montecalvo Versiggia", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 555)
Comune.create(description: "Montescano", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 379)
Comune.create(description: "Montesegale", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 319)
Comune.create(description: "Monticelli Pavese", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 667)
Comune.create(description: "Mornico Losana", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 728)
Comune.create(description: "Mortara", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 14244)
Comune.create(description: "Nicorvo", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 386)
Comune.create(description: "Olevano Di Lomellina", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 771)
Comune.create(description: "Oliva Gessi", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 200)
Comune.create(description: "Ottobiano", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1131)
Comune.create(description: "Palestro", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 2014)
Comune.create(description: "Pancarana", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 322)
Comune.create(description: "Parona", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1698)
Comune.create(description: "Pavia", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 71214)
Comune.create(description: "Pieve Albignola", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 922)
Comune.create(description: "Pieve Del Cairo", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 2166)
Comune.create(description: "Pieve Porto Morone", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 2598)
Comune.create(description: "Pinarolo Po", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1568)
Comune.create(description: "Pizzale", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 640)
Comune.create(description: "Ponte Nizza", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 864)
Comune.create(description: "Portalbera", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1343)
Comune.create(description: "Rea", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 498)
Comune.create(description: "Redavalle", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1008)
Comune.create(description: "Retorbido", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1170)
Comune.create(description: "Rivanazzano", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 )
Comune.create(description: "Robbio", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 6159)
Comune.create(description: "Robecco Pavese", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 547)
Comune.create(description: "Rocca Susella", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 229)
Comune.create(description: "Rognano", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 194)
Comune.create(description: "Romagnese", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 909)
Comune.create(description: "Roncaro", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 626)
Comune.create(description: "Rosasco", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 712)
Comune.create(description: "Rovescala", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 933)
Comune.create(description: "Ruino", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 811)
Comune.create(description: "San Cipriano Po", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 417)
Comune.create(description: "San Damiano Al Colle", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 738)
Comune.create(description: "San Genesio Ed Uniti", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 3396)
Comune.create(description: "San Giorgio Di Lomellina", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1202)
Comune.create(description: "San Martino Siccomario", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 5055)
Comune.create(description: "San Zenone Al Po", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 521)
Comune.create(description: "Santa Cristina E Bissone", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1853)
Comune.create(description: "Santa Giuletta", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1615)
Comune.create(description: "Santa Margherita Di Staffora", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 617)
Comune.create(description: "Santa Maria Della Versa", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 2584)
Comune.create(description: "Sartirana Lomellina", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1900)
Comune.create(description: "Scaldasole", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 885)
Comune.create(description: "Semiana", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 256)
Comune.create(description: "Silvano Pietra", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 703)
Comune.create(description: "Siziano", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 5226)
Comune.create(description: "Sommo", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1034)
Comune.create(description: "Spessa", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 525)
Comune.create(description: "Stradella", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 10763)
Comune.create(description: "Suardi", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 703)
Comune.create(description: "Torrazza Coste", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1518)
Comune.create(description: "Torre Beretti Castellaro", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 )
Comune.create(description: "Torrevecchia Pia", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 2515)
Comune.create(description: "Torricella Verzate", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 802)
Comune.create(description: "Trivolzio", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1204)
Comune.create(description: "Tromello", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 3409)
Comune.create(description: "Trovo", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 647)
Comune.create(description: "Val Di Nizza", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 688)
Comune.create(description: "Valeggio", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 226)
Comune.create(description: "Valle Lomellina", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 2229)
Comune.create(description: "Valle Salimbene", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1353)
Comune.create(description: "Valverde", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 341)
Comune.create(description: "Varzi", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 3539)
Comune.create(description: "Velezzo Lomellina", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 103)
Comune.create(description: "Vellezzo Bellini", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 2251)
Comune.create(description: "Verretto", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 324)
Comune.create(description: "Verrua Po", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1323)
Comune.create(description: "Vidigulfo", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 4231)
Comune.create(description: "Vigevano", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 57450)
Comune.create(description: "Villa Biscossi", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 73)
Comune.create(description: "Villanterio", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 2657)
Comune.create(description: "Vistarino", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1118)
Comune.create(description: "Voghera", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 38183)
Comune.create(description: "Volpara", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 132)
Comune.create(description: "Zavattarello", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1129)
Comune.create(description: "Zeccone", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1158)
Comune.create(description: "Zeme", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1197)
Comune.create(description: "Zenevredo", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 453)
Comune.create(description: "Zerbo", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 466)
Comune.create(description: "Zinasco", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 2950)
Comune.create(description: "Bascape'", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1504)
Comune.create(description: "Bastida De' Dossi", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 199)
Comune.create(description: "Castello D'Agogna", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 969)
Comune.create(description: "Costa De' Nobili", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 370)
Comune.create(description: "Gambolo'", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 8323)
Comune.create(description: "Montu' Beccaria", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1683)
Comune.create(description: "Pietra De' Giorgi", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 875)
Comune.create(description: "Rocca De' Giorgi", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 98)
Comune.create(description: "Sannazzaro De' Burgondi", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 5802)
Comune.create(description: "Sant'Alessio Con Vialone", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 372)
Comune.create(description: "Sant'Angelo Lomellina", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 828)
Comune.create(description: "Torre D'Arese", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 550)
Comune.create(description: "Torre De' Negri", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 365)
Comune.create(description: "Torre D'Isola", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1857)
Comune.create(description: "Travaco' Siccomario", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 3580)
Comune.create(description: "Villanova D'Ardenghi", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 687)
Comune.create(description: "Zerbolo'", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1216)
