#encoding: utf-8
Comune.create(:description => "Andreis", :provincia_id => 74, :regione_id => 15, stato_id: 1, continente_id: 1 , :population => 323)
Comune.create(:description => "Arba", :provincia_id => 74, :regione_id => 15, stato_id: 1, continente_id: 1 , :population => 1228)
Comune.create(:description => "Arzene", :provincia_id => 74, :regione_id => 15, stato_id: 1, continente_id: 1 , :population => 1608)
Comune.create(:description => "Aviano", :provincia_id => 74, :regione_id => 15, stato_id: 1, continente_id: 1 , :population => 8225)
Comune.create(:description => "Azzano Decimo", :provincia_id => 74, :regione_id => 15, stato_id: 1, continente_id: 1 , :population => 12880)
Comune.create(:description => "Barcis", :provincia_id => 74, :regione_id => 15, stato_id: 1, continente_id: 1 , :population => 306)
Comune.create(:description => "Brugnera", :provincia_id => 74, :regione_id => 15, stato_id: 1, continente_id: 1 , :population => 8112)
Comune.create(:description => "Budoia", :provincia_id => 74, :regione_id => 15, stato_id: 1, continente_id: 1 , :population => 2147)
Comune.create(:description => "Caneva", :provincia_id => 74, :regione_id => 15, stato_id: 1, continente_id: 1 , :population => 6323)
Comune.create(:description => "Casarsa Della Delizia", :provincia_id => 74, :regione_id => 15, stato_id: 1, continente_id: 1 , :population => 8135)
Comune.create(:description => "Castelnovo Del Friuli", :provincia_id => 74, :regione_id => 15, stato_id: 1, continente_id: 1 , :population => 899)
Comune.create(:description => "Cavasso Nuovo", :provincia_id => 74, :regione_id => 15, stato_id: 1, continente_id: 1 , :population => 1408)
Comune.create(:description => "Chions", :provincia_id => 74, :regione_id => 15, stato_id: 1, continente_id: 1 , :population => 4523)
Comune.create(:description => "Cimolais", :provincia_id => 74, :regione_id => 15, stato_id: 1, continente_id: 1 , :population => 465)
Comune.create(:description => "Claut", :provincia_id => 74, :regione_id => 15, stato_id: 1, continente_id: 1 , :population => 1181)
Comune.create(:description => "Clauzetto", :provincia_id => 74, :regione_id => 15, stato_id: 1, continente_id: 1 , :population => 419)
Comune.create(:description => "Cordenons", :provincia_id => 74, :regione_id => 15, stato_id: 1, continente_id: 1 , :population => 16991)
Comune.create(:description => "Cordovado", :provincia_id => 74, :regione_id => 15, stato_id: 1, continente_id: 1 , :population => 2518)
Comune.create(:description => "Erto E Casso", :provincia_id => 74, :regione_id => 15, stato_id: 1, continente_id: 1 , :population => 424)
Comune.create(:description => "Fanna", :provincia_id => 74, :regione_id => 15, stato_id: 1, continente_id: 1 , :population => 1516)
Comune.create(:description => "Fiume Veneto", :provincia_id => 74, :regione_id => 15, stato_id: 1, continente_id: 1 , :population => 10221)
Comune.create(:description => "Fontanafredda", :provincia_id => 74, :regione_id => 15, stato_id: 1, continente_id: 1 , :population => 9515)
Comune.create(:description => "Frisanco", :provincia_id => 74, :regione_id => 15, stato_id: 1, continente_id: 1 , :population => 650)
Comune.create(:description => "Maniago", :provincia_id => 74, :regione_id => 15, stato_id: 1, continente_id: 1 , :population => 11708)
Comune.create(:description => "Meduno", :provincia_id => 74, :regione_id => 15, stato_id: 1, continente_id: 1 , :population => 1730)
Comune.create(:description => "Montereale Valcellina", :provincia_id => 74, :regione_id => 15, stato_id: 1, continente_id: 1 , :population => 4656)
Comune.create(:description => "Morsano Al Tagliamento", :provincia_id => 74, :regione_id => 15, stato_id: 1, continente_id: 1 , :population => 2762)
Comune.create(:description => "Pasiano Di Pordenone", :provincia_id => 74, :regione_id => 15, stato_id: 1, continente_id: 1 , :population => 7422)
Comune.create(:description => "Pinzano Al Tagliamento", :provincia_id => 74, :regione_id => 15, stato_id: 1, continente_id: 1 , :population => 1608)
Comune.create(:description => "Polcenigo", :provincia_id => 74, :regione_id => 15, stato_id: 1, continente_id: 1 , :population => 3127)
Comune.create(:description => "Porcia", :provincia_id => 74, :regione_id => 15, stato_id: 1, continente_id: 1 , :population => 13616)
Comune.create(:description => "Pordenone", :provincia_id => 74, :regione_id => 15, stato_id: 1, continente_id: 1 , :population => 49122)
Comune.create(:description => "Prata Di Pordenone", :provincia_id => 74, :regione_id => 15, stato_id: 1, continente_id: 1 , :population => 6964)
Comune.create(:description => "Pravisdomini", :provincia_id => 74, :regione_id => 15, stato_id: 1, continente_id: 1 , :population => 2576)
Comune.create(:description => "Roveredo In Piano", :provincia_id => 74, :regione_id => 15, stato_id: 1, continente_id: 1 , :population => 4853)
Comune.create(:description => "Sacile", :provincia_id => 74, :regione_id => 15, stato_id: 1, continente_id: 1 , :population => 18215)
Comune.create(:description => "San Giorgio Della Richinvelda", :provincia_id => 74, :regione_id => 15, stato_id: 1, continente_id: 1 , :population => 4316)
Comune.create(:description => "San Martino Al Tagliamento", :provincia_id => 74, :regione_id => 15, stato_id: 1, continente_id: 1 , :population => 1336)
Comune.create(:description => "San Quirino", :provincia_id => 74, :regione_id => 15, stato_id: 1, continente_id: 1 , :population => 3816)
Comune.create(:description => "San Vito Al Tagliamento", :provincia_id => 74, :regione_id => 15, stato_id: 1, continente_id: 1 , :population => 13316)
Comune.create(:description => "Sequals", :provincia_id => 74, :regione_id => 15, stato_id: 1, continente_id: 1 , :population => 2122)
Comune.create(:description => "Sesto Al Reghena", :provincia_id => 74, :regione_id => 15, stato_id: 1, continente_id: 1 , :population => 5311)
Comune.create(:description => "Spilimbergo", :provincia_id => 74, :regione_id => 15, stato_id: 1, continente_id: 1 , :population => 11087)
Comune.create(:description => "Tramonti Di Sopra", :provincia_id => 74, :regione_id => 15, stato_id: 1, continente_id: 1 , :population => 409)
Comune.create(:description => "Tramonti Di Sotto", :provincia_id => 74, :regione_id => 15, stato_id: 1, continente_id: 1 , :population => 440)
Comune.create(:description => "Travesio", :provincia_id => 74, :regione_id => 15, stato_id: 1, continente_id: 1 , :population => 1767)
Comune.create(:description => "Vajont", :provincia_id => 74, :regione_id => 15, stato_id: 1, continente_id: 1 , :population => 1372)
Comune.create(:description => "Valvasone", :provincia_id => 74, :regione_id => 15, stato_id: 1, continente_id: 1 , :population => 1936)
Comune.create(:description => "Vivaro", :provincia_id => 74, :regione_id => 15, stato_id: 1, continente_id: 1 , :population => 1272)
Comune.create(:description => "Zoppola", :provincia_id => 74, :regione_id => 15, stato_id: 1, continente_id: 1 , :population => 8430)
Comune.create(:description => "Vito D'Asio", :provincia_id => 74, :regione_id => 15, stato_id: 1, continente_id: 1 , :population => 892)
