Municipality.create(description: "Cassolnovo", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 5820)
Municipality.create(description: "Alagna", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 755)
Municipality.create(description: "Albaredo Arnaboldi", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 205)
Municipality.create(description: "Albonese", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 504)
Municipality.create(description: "Albuzzano", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 2256)
Municipality.create(description: "Arena Po", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1572)
Municipality.create(description: "Badia Pavese", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 394)
Municipality.create(description: "Bagnaria", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 639)
Municipality.create(description: "Barbianello", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 816)
Municipality.create(description: "Bastida Pancarana", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 894)
Municipality.create(description: "Battuda", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 352)
Municipality.create(description: "Belgioioso", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 5357)
Municipality.create(description: "Bereguardo", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 2390)
Municipality.create(description: "Borgarello", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1609)
Municipality.create(description: "Borgo Priolo", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1405)
Municipality.create(description: "Borgo San Siro", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1023)
Municipality.create(description: "Borgoratto Mormorolo", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 434)
Municipality.create(description: "Bornasco", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1677)
Municipality.create(description: "Bosnasco", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 600)
Municipality.create(description: "Brallo Di Pregola", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 930)
Municipality.create(description: "Breme", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 936)
Municipality.create(description: "Bressana Bottarone", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 3143)
Municipality.create(description: "Broni", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 9347)
Municipality.create(description: "Calvignano", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 130)
Municipality.create(description: "Campospinoso", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 772)
Municipality.create(description: "Candia Lomellina", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1646)
Municipality.create(description: "Canevino", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 131)
Municipality.create(description: "Canneto Pavese", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1338)
Municipality.create(description: "Carbonara Al Ticino", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1289)
Municipality.create(description: "Casanova Lonati", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 427)
Municipality.create(description: "Casatisma", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 856)
Municipality.create(description: "Casei Gerola", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 2536)
Municipality.create(description: "Casorate Primo", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 7028)
Municipality.create(description: "Castana", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 754)
Municipality.create(description: "Casteggio", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 6337)
Municipality.create(description: "Castelletto Di Branduzzo", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1023)
Municipality.create(description: "Castelnovetto", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 643)
Municipality.create(description: "Cava Manara", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 5321)
Municipality.create(description: "Cecima", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 276)
Municipality.create(description: "Ceranova", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1151)
Municipality.create(description: "Ceretto Lomellina", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 211)
Municipality.create(description: "Cergnago", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 764)
Municipality.create(description: "Certosa Di Pavia", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 3320)
Municipality.create(description: "Cervesina", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1200)
Municipality.create(description: "Chignolo Po", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 3234)
Municipality.create(description: "Cigognola", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1367)
Municipality.create(description: "Cilavegna", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 4979)
Municipality.create(description: "Codevilla", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 917)
Municipality.create(description: "Confienza", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1636)
Municipality.create(description: "Copiano", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1364)
Municipality.create(description: "Corana", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 790)
Municipality.create(description: "Cornale", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 734)
Municipality.create(description: "Corteolona", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1906)
Municipality.create(description: "Corvino San Quirico", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1092)
Municipality.create(description: "Cozzo", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 432)
Municipality.create(description: "Cura Carpignano", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 2145)
Municipality.create(description: "Dorno", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 4184)
Municipality.create(description: "Ferrera Erbognone", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1103)
Municipality.create(description: "Filighera", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 843)
Municipality.create(description: "Fortunago", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 420)
Municipality.create(description: "Frascarolo", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1321)
Municipality.create(description: "Galliavola", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 232)
Municipality.create(description: "Gambarana", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 281)
Municipality.create(description: "Garlasco", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 0)
Municipality.create(description: "Genzone", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 345)
Municipality.create(description: "Gerenzago", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 913)
Municipality.create(description: "Giussago", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 3915)
Municipality.create(description: "Godiasco", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 2806)
Municipality.create(description: "Golferenzo", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 233)
Municipality.create(description: "Gravellona Lomellina", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 2173)
Municipality.create(description: "Gropello Cairoli", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 4105)
Municipality.create(description: "Inverno E Monteleone", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1069)
Municipality.create(description: "Landriano", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 4171)
Municipality.create(description: "Langosco", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 458)
Municipality.create(description: "Lardirago", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1163)
Municipality.create(description: "Linarolo", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 2172)
Municipality.create(description: "Lirio", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 147)
Municipality.create(description: "Lomello", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 2378)
Municipality.create(description: "Lungavilla", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 2154)
Municipality.create(description: "Magherno", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1380)
Municipality.create(description: "Marcignago", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1923)
Municipality.create(description: "Marzano", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1025)
Municipality.create(description: "Mede", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 6924)
Municipality.create(description: "Menconico", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 494)
Municipality.create(description: "Mezzana Bigli", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1168)
Municipality.create(description: "Mezzana Rabattone", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 532)
Municipality.create(description: "Mezzanino", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1468)
Municipality.create(description: "Miradolo Terme", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 3177)
Municipality.create(description: "Montalto Pavese", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 963)
Municipality.create(description: "Montebello Della Battaglia", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1647)
Municipality.create(description: "Montecalvo Versiggia", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 555)
Municipality.create(description: "Montescano", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 379)
Municipality.create(description: "Montesegale", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 319)
Municipality.create(description: "Monticelli Pavese", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 667)
Municipality.create(description: "Mornico Losana", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 728)
Municipality.create(description: "Mortara", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 14244)
Municipality.create(description: "Nicorvo", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 386)
Municipality.create(description: "Olevano Di Lomellina", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 771)
Municipality.create(description: "Oliva Gessi", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 200)
Municipality.create(description: "Ottobiano", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1131)
Municipality.create(description: "Palestro", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 2014)
Municipality.create(description: "Pancarana", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 322)
Municipality.create(description: "Parona", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1698)
Municipality.create(description: "Pavia", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 71214)
Municipality.create(description: "Pieve Albignola", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 922)
Municipality.create(description: "Pieve Del Cairo", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 2166)
Municipality.create(description: "Pieve Porto Morone", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 2598)
Municipality.create(description: "Pinarolo Po", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1568)
Municipality.create(description: "Pizzale", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 640)
Municipality.create(description: "Ponte Nizza", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 864)
Municipality.create(description: "Portalbera", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1343)
Municipality.create(description: "Rea", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 498)
Municipality.create(description: "Redavalle", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1008)
Municipality.create(description: "Retorbido", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1170)
Municipality.create(description: "Rivanazzano", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 )
Municipality.create(description: "Robbio", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 6159)
Municipality.create(description: "Robecco Pavese", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 547)
Municipality.create(description: "Rocca Susella", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 229)
Municipality.create(description: "Rognano", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 194)
Municipality.create(description: "Romagnese", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 909)
Municipality.create(description: "Roncaro", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 626)
Municipality.create(description: "Rosasco", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 712)
Municipality.create(description: "Rovescala", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 933)
Municipality.create(description: "Ruino", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 811)
Municipality.create(description: "San Cipriano Po", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 417)
Municipality.create(description: "San Damiano Al Colle", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 738)
Municipality.create(description: "San Genesio Ed Uniti", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 3396)
Municipality.create(description: "San Giorgio Di Lomellina", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1202)
Municipality.create(description: "San Martino Siccomario", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 5055)
Municipality.create(description: "San Zenone Al Po", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 521)
Municipality.create(description: "Santa Cristina E Bissone", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1853)
Municipality.create(description: "Santa Giuletta", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1615)
Municipality.create(description: "Santa Margherita Di Staffora", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 617)
Municipality.create(description: "Santa Maria Della Versa", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 2584)
Municipality.create(description: "Sartirana Lomellina", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1900)
Municipality.create(description: "Scaldasole", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 885)
Municipality.create(description: "Semiana", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 256)
Municipality.create(description: "Silvano Pietra", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 703)
Municipality.create(description: "Siziano", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 5226)
Municipality.create(description: "Sommo", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1034)
Municipality.create(description: "Spessa", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 525)
Municipality.create(description: "Stradella", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 10763)
Municipality.create(description: "Suardi", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 703)
Municipality.create(description: "Torrazza Coste", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1518)
Municipality.create(description: "Torre Beretti Castellaro", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 )
Municipality.create(description: "Torrevecchia Pia", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 2515)
Municipality.create(description: "Torricella Verzate", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 802)
Municipality.create(description: "Trivolzio", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1204)
Municipality.create(description: "Tromello", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 3409)
Municipality.create(description: "Trovo", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 647)
Municipality.create(description: "Val Di Nizza", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 688)
Municipality.create(description: "Valeggio", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 226)
Municipality.create(description: "Valle Lomellina", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 2229)
Municipality.create(description: "Valle Salimbene", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1353)
Municipality.create(description: "Valverde", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 341)
Municipality.create(description: "Varzi", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 3539)
Municipality.create(description: "Velezzo Lomellina", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 103)
Municipality.create(description: "Vellezzo Bellini", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 2251)
Municipality.create(description: "Verretto", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 324)
Municipality.create(description: "Verrua Po", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1323)
Municipality.create(description: "Vidigulfo", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 4231)
Municipality.create(description: "Vigevano", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 57450)
Municipality.create(description: "Villa Biscossi", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 73)
Municipality.create(description: "Villanterio", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 2657)
Municipality.create(description: "Vistarino", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1118)
Municipality.create(description: "Voghera", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 38183)
Municipality.create(description: "Volpara", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 132)
Municipality.create(description: "Zavattarello", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1129)
Municipality.create(description: "Zeccone", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1158)
Municipality.create(description: "Zeme", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1197)
Municipality.create(description: "Zenevredo", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 453)
Municipality.create(description: "Zerbo", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 466)
Municipality.create(description: "Zinasco", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 2950)
Municipality.create(description: "Bascape'", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1504)
Municipality.create(description: "Bastida De' Dossi", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 199)
Municipality.create(description: "Castello D'Agogna", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 969)
Municipality.create(description: "Costa De' Nobili", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 370)
Municipality.create(description: "Gambolo'", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 8323)
Municipality.create(description: "Montu' Beccaria", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1683)
Municipality.create(description: "Pietra De' Giorgi", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 875)
Municipality.create(description: "Rocca De' Giorgi", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 98)
Municipality.create(description: "Sannazzaro De' Burgondi", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 5802)
Municipality.create(description: "Sant'Alessio Con Vialone", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 372)
Municipality.create(description: "Sant'Angelo Lomellina", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 828)
Municipality.create(description: "Torre D'Arese", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 550)
Municipality.create(description: "Torre De' Negri", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 365)
Municipality.create(description: "Torre D'Isola", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1857)
Municipality.create(description: "Travaco' Siccomario", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 3580)
Municipality.create(description: "Villanova D'Ardenghi", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 687)
Municipality.create(description: "Zerbolo'", province_id: 98, region_id:  19, country_id: 1, continent_id: 1 , population: 1216)
