#encoding: utf-8
Comune.create(:description => "Gagliano Aterno", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 314)
Comune.create(:description => "Gioia Dei Marsi", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 2284)
Comune.create(:description => "Goriano Sicoli", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 633)
Comune.create(:description => "Introdacqua", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1831)
Comune.create(:description => "Lecce Nei Marsi", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1752)
Comune.create(:description => "Luco Dei Marsi", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 5541)
Comune.create(:description => "Lucoli", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 944)
Comune.create(:description => "Molina Aterno", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 463)
Comune.create(:description => "Montereale", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 2930)
Comune.create(:description => "Morino", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1545)
Comune.create(:description => "Navelli", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 625)
Comune.create(:description => "Ocre", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1020)
Comune.create(:description => "Ofena", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 611)
Comune.create(:description => "Opi", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 462)
Comune.create(:description => "Oricola", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 950)
Comune.create(:description => "Ortona Dei Marsi", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 803)
Comune.create(:description => "Ortucchio", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1978)
Comune.create(:description => "Ovindoli", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1200)
Comune.create(:description => "Pacentro", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1279)
Comune.create(:description => "Pereto", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 704)
Comune.create(:description => "Pescasseroli", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 2130)
Comune.create(:description => "Pescina", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 4506)
Comune.create(:description => "Pescocostanzo", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1216)
Comune.create(:description => "Pettorano Sul Gizio", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1255)
Comune.create(:description => "Pizzoli", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 3047)
Comune.create(:description => "Poggio Picenze", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1011)
Comune.create(:description => "Pratola Peligna", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 7814)
Comune.create(:description => "Prezza", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1092)
Comune.create(:description => "Raiano", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 2973)
Comune.create(:description => "Rivisondoli", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 686)
Comune.create(:description => "Rocca Di Botte", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 522)
Comune.create(:description => "Rocca Di Cambio", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 447)
Comune.create(:description => "Rocca Di Mezzo", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1426)
Comune.create(:description => "Rocca Pia", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 189)
Comune.create(:description => "Roccacasale", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 754)
Comune.create(:description => "Roccaraso", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1604)
Comune.create(:description => "San Benedetto Dei Marsi", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 4006)
Comune.create(:description => "San Benedetto In Perillis", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 145)
Comune.create(:description => "San Pio Delle Camere", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 554)
Comune.create(:description => "San Vincenzo Valle Roveto", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 2577)
Comune.create(:description => "Sante Marie", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1342)
Comune.create(:description => "Santo Stefano Di Sessanio", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 118)
Comune.create(:description => "Scanno", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 2133)
Comune.create(:description => "Scontrone", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 595)
Comune.create(:description => "Scoppito", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 2757)
Comune.create(:description => "Scurcola Marsicana", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 2501)
Comune.create(:description => "Secinaro", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 480)
Comune.create(:description => "Sulmona", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 25304)
Comune.create(:description => "Tagliacozzo", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 6532)
Comune.create(:description => "Tione Degli Abruzzi", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 380)
Comune.create(:description => "Tornimparte", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 2958)
Comune.create(:description => "Trasacco", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 5998)
Comune.create(:description => "Villa Santa Lucia Degli Abruzzi", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 206)
Comune.create(:description => "Villalago", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 636)
Comune.create(:description => "Villavallelonga", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1004)
Comune.create(:description => "Villetta Barrea", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 595)
Comune.create(:description => "Vittorito", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1012)
Comune.create(:description => "Acciano", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 401)
Comune.create(:description => "Aielli", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1477)
Comune.create(:description => "Alfedena", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 716)
Comune.create(:description => "Anversa Degli Abruzzi", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 431)
Comune.create(:description => "Ateleta", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1232)
Comune.create(:description => "Avezzano", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 38337)
Comune.create(:description => "Balsorano", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 3705)
Comune.create(:description => "Barete", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 633)
Comune.create(:description => "Barisciano", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1798)
Comune.create(:description => "Barrea", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 776)
Comune.create(:description => "Bisegna", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 342)
Comune.create(:description => "Bugnara", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1035)
Comune.create(:description => "Cagnano Amiterno", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1509)
Comune.create(:description => "Calascio", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 150)
Comune.create(:description => "Campo Di Giove", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 907)
Comune.create(:description => "Campotosto", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 683)
Comune.create(:description => "Canistro", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1042)
Comune.create(:description => "Cansano", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 270)
Comune.create(:description => "Capestrano", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 960)
Comune.create(:description => "Capistrello", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 5429)
Comune.create(:description => "Capitignano", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 689)
Comune.create(:description => "Caporciano", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 265)
Comune.create(:description => "Cappadocia", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 519)
Comune.create(:description => "Carapelle Calvisio", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 95)
Comune.create(:description => "Carsoli", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 5086)
Comune.create(:description => "Castel Del Monte", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 527)
Comune.create(:description => "Castel Di Ieri", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 405)
Comune.create(:description => "Castel Di Sangro", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 5626)
Comune.create(:description => "Castellafiume", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1049)
Comune.create(:description => "Castelvecchio Calvisio", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 198)
Comune.create(:description => "Castelvecchio Subequo", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1241)
Comune.create(:description => "Celano", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 10975)
Comune.create(:description => "Cerchio", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1669)
Comune.create(:description => "Civitella Alfedena", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 280)
Comune.create(:description => "Civitella Roveto", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 3330)
Comune.create(:description => "Cocullo", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 317)
Comune.create(:description => "Collarmele", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1055)
Comune.create(:description => "Collelongo", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1514)
Comune.create(:description => "Collepietro", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 270)
Comune.create(:description => "Corfinio", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 997)
Comune.create(:description => "Fagnano Alto", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 446)
Comune.create(:description => "Fontecchio", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 422)
Comune.create(:description => "Fossa", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 661)
Comune.create(:description => "Civita D'Antino", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1076)
Comune.create(:description => "L'Aquila", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 68503)
Comune.create(:description => "Magliano De' Marsi", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 3540)
Comune.create(:description => "Massa D'Albe", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1436)
Comune.create(:description => "Prata D'Ansidonia", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 547)
Comune.create(:description => "San Demetrio Ne' Vestini", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 1605)
Comune.create(:description => "Sant'Eusanio Forconese", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 443)
Comune.create(:description => "Villa Sant'Angelo", :provincia_id => 45, :regione_id => 2, stato_id: 1, continente_id: 1 , :population => 431)
