Municipality.create(description: "Albaredo Per San Marco", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 408)
Municipality.create(description: "Albosaggia", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 3084)
Municipality.create(description: "Andalo Valtellino", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 548)
Municipality.create(description: "Aprica", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 1588)
Municipality.create(description: "Ardenno", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 3122)
Municipality.create(description: "Bema", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 144)
Municipality.create(description: "Berbenno Di Valtellina", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 4177)
Municipality.create(description: "Bianzone", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 1220)
Municipality.create(description: "Bormio", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 4096)
Municipality.create(description: "Buglio In Monte", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 2038)
Municipality.create(description: "Caiolo", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 956)
Municipality.create(description: "Campodolcino", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 1086)
Municipality.create(description: "Caspoggio", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 1586)
Municipality.create(description: "Castione Andevenno", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 1553)
Municipality.create(description: "Cedrasco", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 484)
Municipality.create(description: "Cercino", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 689)
Municipality.create(description: "Chiavenna", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 7239)
Municipality.create(description: "Chiesa In Valmalenco", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 2755)
Municipality.create(description: "Chiuro", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 2495)
Municipality.create(description: "Cino", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 335)
Municipality.create(description: "Civo", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 1026)
Municipality.create(description: "Colorina", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 1453)
Municipality.create(description: "Cosio Valtellino", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 5135)
Municipality.create(description: "Dazio", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 347)
Municipality.create(description: "Delebio", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 2996)
Municipality.create(description: "Dubino", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 3160)
Municipality.create(description: "Faedo Valtellino", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 539)
Municipality.create(description: "Forcola", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 874)
Municipality.create(description: "Fusine", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 657)
Municipality.create(description: "Gerola Alta", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 249)
Municipality.create(description: "Gordona", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 1751)
Municipality.create(description: "Grosio", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 4827)
Municipality.create(description: "Grosotto", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 1686)
Municipality.create(description: "Lanzada", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 1440)
Municipality.create(description: "Livigno", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 5069)
Municipality.create(description: "Lovero Valtellino", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 )
Municipality.create(description: "Madesimo", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 581)
Municipality.create(description: "Mantello", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 683)
Municipality.create(description: "Mazzo Di Valtellina", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 1045)
Municipality.create(description: "Mello", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 985)
Municipality.create(description: "Menarola", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 43)
Municipality.create(description: "Mese", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 1619)
Municipality.create(description: "Montagna In Valtellina", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 2890)
Municipality.create(description: "Morbegno", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 11087)
Municipality.create(description: "Novate Mezzola", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 1645)
Municipality.create(description: "Pedesina", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 34)
Municipality.create(description: "Piantedo", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 1189)
Municipality.create(description: "Piateda", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 2320)
Municipality.create(description: "Piuro", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 1913)
Municipality.create(description: "Poggiridenti", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 1807)
Municipality.create(description: "Ponte In Valtellina", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 2252)
Municipality.create(description: "Postalesio", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 609)
Municipality.create(description: "Prata Camportaccio", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 2727)
Municipality.create(description: "Rasura", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 306)
Municipality.create(description: "Rogolo", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 501)
Municipality.create(description: "Samolaco", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 2829)
Municipality.create(description: "San Giacomo Filippo", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 472)
Municipality.create(description: "Sernio", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 445)
Municipality.create(description: "Sondalo", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 4499)
Municipality.create(description: "Sondrio", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 21642)
Municipality.create(description: "Spriana", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 117)
Municipality.create(description: "Talamona", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 4506)
Municipality.create(description: "Tartano", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 262)
Municipality.create(description: "Teglio", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 4797)
Municipality.create(description: "Tirano", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 9044)
Municipality.create(description: "Torre Di Santa Maria", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 892)
Municipality.create(description: "Traona", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 2187)
Municipality.create(description: "Tresivio", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 1943)
Municipality.create(description: "Val Masino", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 963)
Municipality.create(description: "Valdidentro", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 3908)
Municipality.create(description: "Valdisotto", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 3217)
Municipality.create(description: "Valfurva", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 2742)
Municipality.create(description: "Verceia", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 1116)
Municipality.create(description: "Vervio", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 239)
Municipality.create(description: "Villa Di Chiavenna", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 1116)
Municipality.create(description: "Villa Di Tirano", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 2968)
Municipality.create(description: "Castello Dell'Acqua", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 700)
Municipality.create(description: "Tovo Di Sant'Agata", province_id: 99, region_id:  19, country_id: 1, continent_id: 1 , population: 569)
