#encoding: utf-8
Comune.create(description: "Agra", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 370)
Comune.create(description: "Albizzate", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 4919)
Comune.create(description: "Angera", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 5477)
Comune.create(description: "Arcisate", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 9280)
Comune.create(description: "Arsago Seprio", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 4509)
Comune.create(description: "Azzate", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 3820)
Comune.create(description: "Azzio", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 701)
Comune.create(description: "Barasso", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 1696)
Comune.create(description: "Bardello", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 1218)
Comune.create(description: "Bedero Valcuvia", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 602)
Comune.create(description: "Besano", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 2350)
Comune.create(description: "Besnate", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 4822)
Comune.create(description: "Besozzo", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 8239)
Comune.create(description: "Biandronno", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 3102)
Comune.create(description: "Bisuschio", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 3794)
Comune.create(description: "Bodio Lomnago", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 2012)
Comune.create(description: "Brebbia", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 3120)
Comune.create(description: "Bregano", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 726)
Comune.create(description: "Brenta", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 1646)
Comune.create(description: "Brezzo Di Bedero", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 950)
Comune.create(description: "Brinzio", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 804)
Comune.create(description: "Brissago Valtravaglia", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 )
Comune.create(description: "Brunello", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 954)
Comune.create(description: "Brusimpiano", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 1086)
Comune.create(description: "Buguggiate", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 3140)
Comune.create(description: "Busto Arsizio", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 75916)
Comune.create(description: "Cadegliano Viconago", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 )
Comune.create(description: "Cadrezzate", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 1577)
Comune.create(description: "Cairate", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 7301)
Comune.create(description: "Cantello", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 4244)
Comune.create(description: "Caravate", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 2607)
Comune.create(description: "Cardano Al Campo", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 12084)
Comune.create(description: "Carnago", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 5639)
Comune.create(description: "Caronno Pertusella", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 12052)
Comune.create(description: "Caronno Varesino", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 4602)
Comune.create(description: "Casale Litta", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 2420)
Comune.create(description: "Casalzuigno", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 1207)
Comune.create(description: "Casciago", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 4019)
Comune.create(description: "Casorate Sempione", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 5070)
Comune.create(description: "Cassano Magnago", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 20668)
Comune.create(description: "Cassano Valcuvia", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 541)
Comune.create(description: "Castellanza", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 14569)
Comune.create(description: "Castello Cabiaglio", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 503)
Comune.create(description: "Castelseprio", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 1237)
Comune.create(description: "Castelveccana", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 1963)
Comune.create(description: "Castiglione Olona", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 7696)
Comune.create(description: "Castronno", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 4842)
Comune.create(description: "Cavaria Con Premezzo", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 4788)
Comune.create(description: "Cazzago Brabbia", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 785)
Comune.create(description: "Cislago", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 8683)
Comune.create(description: "Cittiglio", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 3718)
Comune.create(description: "Clivio", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 1963)
Comune.create(description: "Cocquio Trevisago", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 )
Comune.create(description: "Comabbio", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 958)
Comune.create(description: "Comerio", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 2352)
Comune.create(description: "Cremenaga", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 779)
Comune.create(description: "Crosio Della Valle", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 572)
Comune.create(description: "Cuasso Al Monte", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 3065)
Comune.create(description: "Cugliate Fabiasco", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 )
Comune.create(description: "Cunardo", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 2549)
Comune.create(description: "Curiglia Con Monteviasco", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 201)
Comune.create(description: "Cuveglio", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 3021)
Comune.create(description: "Cuvio", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 1515)
Comune.create(description: "Daverio", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 2634)
Comune.create(description: "Dumenza", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 1325)
Comune.create(description: "Duno", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 148)
Comune.create(description: "Fagnano Olona", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 10418)
Comune.create(description: "Ferno", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 6364)
Comune.create(description: "Ferrera Di Varese", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 564)
Comune.create(description: "Gallarate", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 46361)
Comune.create(description: "Galliate Lombardo", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 844)
Comune.create(description: "Gavirate", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 9400)
Comune.create(description: "Gazzada Schianno", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 4517)
Comune.create(description: "Gemonio", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 2552)
Comune.create(description: "Gerenzano", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 9028)
Comune.create(description: "Germignaga", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 3596)
Comune.create(description: "Golasecca", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 2485)
Comune.create(description: "Gorla Maggiore", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 4836)
Comune.create(description: "Gorla Minore", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 7446)
Comune.create(description: "Gornate Olona", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 )
Comune.create(description: "Grantola", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 1190)
Comune.create(description: "Inarzo", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 805)
Comune.create(description: "Induno Olona", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 9810)
Comune.create(description: "Ispra", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 4686)
Comune.create(description: "Jerago Con Orago", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 4688)
Comune.create(description: "Lavena Ponte Tresa", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 5227)
Comune.create(description: "Laveno Mombello", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 )
Comune.create(description: "Leggiuno", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 2863)
Comune.create(description: "Lonate Ceppino", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 4068)
Comune.create(description: "Lonate Pozzolo", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 11480)
Comune.create(description: "Lozza", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 951)
Comune.create(description: "Luino", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 14234)
Comune.create(description: "Luvinate", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 1386)
Comune.create(description: "Maccagno", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 2004)
Comune.create(description: "Malgesso", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 1113)
Comune.create(description: "Malnate", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 15192)
Comune.create(description: "Marchirolo", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 3153)
Comune.create(description: "Marnate", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 5967)
Comune.create(description: "Marzio", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 287)
Comune.create(description: "Masciago Primo", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 272)
Comune.create(description: "Mercallo", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 1679)
Comune.create(description: "Mesenzana", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 1231)
Comune.create(description: "Montegrino Valtravaglia", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 1183)
Comune.create(description: "Monvalle", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 1720)
Comune.create(description: "Morazzone", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 4187)
Comune.create(description: "Mornago", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 4163)
Comune.create(description: "Oggiona Con Santo Stefano", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 4276)
Comune.create(description: "Olgiate Olona", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 10801)
Comune.create(description: "Origgio", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 6379)
Comune.create(description: "Orino", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 779)
Comune.create(description: "Osmate", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 447)
Comune.create(description: "Pino Sulla Sponda Del Lago Maggiore", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 247)
Comune.create(description: "Porto Ceresio", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 3068)
Comune.create(description: "Porto Valtravaglia", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 2387)
Comune.create(description: "Rancio Valcuvia", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 867)
Comune.create(description: "Ranco", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 1108)
Comune.create(description: "Saltrio", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 2857)
Comune.create(description: "Samarate", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 15350)
Comune.create(description: "Sangiano", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 1247)
Comune.create(description: "Saronno", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 36895)
Comune.create(description: "Sesto Calende", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 9806)
Comune.create(description: "Solbiate Arno", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 4027)
Comune.create(description: "Solbiate Olona", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 5594)
Comune.create(description: "Somma Lombardo", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 16247)
Comune.create(description: "Sumirago", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 5849)
Comune.create(description: "Taino", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 3185)
Comune.create(description: "Ternate", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 2254)
Comune.create(description: "Tradate", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 15960)
Comune.create(description: "Travedona Monate", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 )
Comune.create(description: "Tronzano Lago Maggiore", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 257)
Comune.create(description: "Uboldo", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 9493)
Comune.create(description: "Valganna", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 1462)
Comune.create(description: "Varano Borghi", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 2194)
Comune.create(description: "Varese", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 80511)
Comune.create(description: "Vedano Olona", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 6994)
Comune.create(description: "Veddasca", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 346)
Comune.create(description: "Venegono Inferiore", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 5746)
Comune.create(description: "Venegono Superiore", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 6730)
Comune.create(description: "Vergiate", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 8414)
Comune.create(description: "Vizzola Ticino", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 428)
Comune.create(description: "Viggiu'", provincia_id: 100, regione_id: 19, stato_id: 1, continente_id: 1 , population: 4968)
