Municipality.create(description: "Agra", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 370)
Municipality.create(description: "Albizzate", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 4919)
Municipality.create(description: "Angera", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 5477)
Municipality.create(description: "Arcisate", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 9280)
Municipality.create(description: "Arsago Seprio", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 4509)
Municipality.create(description: "Azzate", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 3820)
Municipality.create(description: "Azzio", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 701)
Municipality.create(description: "Barasso", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 1696)
Municipality.create(description: "Bardello", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 1218)
Municipality.create(description: "Bedero Valcuvia", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 602)
Municipality.create(description: "Besano", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 2350)
Municipality.create(description: "Besnate", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 4822)
Municipality.create(description: "Besozzo", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 8239)
Municipality.create(description: "Biandronno", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 3102)
Municipality.create(description: "Bisuschio", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 3794)
Municipality.create(description: "Bodio Lomnago", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 2012)
Municipality.create(description: "Brebbia", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 3120)
Municipality.create(description: "Bregano", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 726)
Municipality.create(description: "Brenta", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 1646)
Municipality.create(description: "Brezzo Di Bedero", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 950)
Municipality.create(description: "Brinzio", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 804)
Municipality.create(description: "Brissago Valtravaglia", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 )
Municipality.create(description: "Brunello", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 954)
Municipality.create(description: "Brusimpiano", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 1086)
Municipality.create(description: "Buguggiate", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 3140)
Municipality.create(description: "Busto Arsizio", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 75916)
Municipality.create(description: "Cadegliano Viconago", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 )
Municipality.create(description: "Cadrezzate", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 1577)
Municipality.create(description: "Cairate", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 7301)
Municipality.create(description: "Cantello", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 4244)
Municipality.create(description: "Caravate", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 2607)
Municipality.create(description: "Cardano Al Campo", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 12084)
Municipality.create(description: "Carnago", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 5639)
Municipality.create(description: "Caronno Pertusella", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 12052)
Municipality.create(description: "Caronno Varesino", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 4602)
Municipality.create(description: "Casale Litta", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 2420)
Municipality.create(description: "Casalzuigno", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 1207)
Municipality.create(description: "Casciago", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 4019)
Municipality.create(description: "Casorate Sempione", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 5070)
Municipality.create(description: "Cassano Magnago", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 20668)
Municipality.create(description: "Cassano Valcuvia", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 541)
Municipality.create(description: "Castellanza", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 14569)
Municipality.create(description: "Castello Cabiaglio", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 503)
Municipality.create(description: "Castelseprio", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 1237)
Municipality.create(description: "Castelveccana", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 1963)
Municipality.create(description: "Castiglione Olona", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 7696)
Municipality.create(description: "Castronno", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 4842)
Municipality.create(description: "Cavaria Con Premezzo", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 4788)
Municipality.create(description: "Cazzago Brabbia", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 785)
Municipality.create(description: "Cislago", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 8683)
Municipality.create(description: "Cittiglio", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 3718)
Municipality.create(description: "Clivio", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 1963)
Municipality.create(description: "Cocquio Trevisago", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 )
Municipality.create(description: "Comabbio", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 958)
Municipality.create(description: "Comerio", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 2352)
Municipality.create(description: "Cremenaga", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 779)
Municipality.create(description: "Crosio Della Valle", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 572)
Municipality.create(description: "Cuasso Al Monte", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 3065)
Municipality.create(description: "Cugliate Fabiasco", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 )
Municipality.create(description: "Cunardo", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 2549)
Municipality.create(description: "Curiglia Con Monteviasco", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 201)
Municipality.create(description: "Cuveglio", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 3021)
Municipality.create(description: "Cuvio", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 1515)
Municipality.create(description: "Daverio", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 2634)
Municipality.create(description: "Dumenza", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 1325)
Municipality.create(description: "Duno", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 148)
Municipality.create(description: "Fagnano Olona", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 10418)
Municipality.create(description: "Ferno", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 6364)
Municipality.create(description: "Ferrera Di Varese", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 564)
Municipality.create(description: "Gallarate", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 46361)
Municipality.create(description: "Galliate Lombardo", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 844)
Municipality.create(description: "Gavirate", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 9400)
Municipality.create(description: "Gazzada Schianno", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 4517)
Municipality.create(description: "Gemonio", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 2552)
Municipality.create(description: "Gerenzano", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 9028)
Municipality.create(description: "Germignaga", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 3596)
Municipality.create(description: "Golasecca", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 2485)
Municipality.create(description: "Gorla Maggiore", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 4836)
Municipality.create(description: "Gorla Minore", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 7446)
Municipality.create(description: "Gornate Olona", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 )
Municipality.create(description: "Grantola", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 1190)
Municipality.create(description: "Inarzo", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 805)
Municipality.create(description: "Induno Olona", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 9810)
Municipality.create(description: "Ispra", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 4686)
Municipality.create(description: "Jerago Con Orago", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 4688)
Municipality.create(description: "Lavena Ponte Tresa", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 5227)
Municipality.create(description: "Laveno Mombello", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 )
Municipality.create(description: "Leggiuno", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 2863)
Municipality.create(description: "Lonate Ceppino", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 4068)
Municipality.create(description: "Lonate Pozzolo", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 11480)
Municipality.create(description: "Lozza", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 951)
Municipality.create(description: "Luino", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 14234)
Municipality.create(description: "Luvinate", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 1386)
Municipality.create(description: "Maccagno", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 2004)
Municipality.create(description: "Malgesso", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 1113)
Municipality.create(description: "Malnate", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 15192)
Municipality.create(description: "Marchirolo", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 3153)
Municipality.create(description: "Marnate", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 5967)
Municipality.create(description: "Marzio", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 287)
Municipality.create(description: "Masciago Primo", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 272)
Municipality.create(description: "Mercallo", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 1679)
Municipality.create(description: "Mesenzana", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 1231)
Municipality.create(description: "Montegrino Valtravaglia", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 1183)
Municipality.create(description: "Monvalle", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 1720)
Municipality.create(description: "Morazzone", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 4187)
Municipality.create(description: "Mornago", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 4163)
Municipality.create(description: "Oggiona Con Santo Stefano", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 4276)
Municipality.create(description: "Olgiate Olona", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 10801)
Municipality.create(description: "Origgio", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 6379)
Municipality.create(description: "Orino", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 779)
Municipality.create(description: "Osmate", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 447)
Municipality.create(description: "Pino Sulla Sponda Del Lago Maggiore", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 247)
Municipality.create(description: "Porto Ceresio", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 3068)
Municipality.create(description: "Porto Valtravaglia", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 2387)
Municipality.create(description: "Rancio Valcuvia", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 867)
Municipality.create(description: "Ranco", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 1108)
Municipality.create(description: "Saltrio", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 2857)
Municipality.create(description: "Samarate", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 15350)
Municipality.create(description: "Sangiano", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 1247)
Municipality.create(description: "Saronno", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 36895)
Municipality.create(description: "Sesto Calende", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 9806)
Municipality.create(description: "Solbiate Arno", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 4027)
Municipality.create(description: "Solbiate Olona", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 5594)
Municipality.create(description: "Somma Lombardo", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 16247)
Municipality.create(description: "Sumirago", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 5849)
Municipality.create(description: "Taino", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 3185)
Municipality.create(description: "Ternate", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 2254)
Municipality.create(description: "Tradate", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 15960)
Municipality.create(description: "Travedona Monate", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 )
Municipality.create(description: "Tronzano Lago Maggiore", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 257)
Municipality.create(description: "Uboldo", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 9493)
Municipality.create(description: "Valganna", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 1462)
Municipality.create(description: "Varano Borghi", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 2194)
Municipality.create(description: "Varese", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 80511)
Municipality.create(description: "Vedano Olona", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 6994)
Municipality.create(description: "Veddasca", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 346)
Municipality.create(description: "Venegono Inferiore", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 5746)
Municipality.create(description: "Venegono Superiore", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 6730)
Municipality.create(description: "Vergiate", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 8414)
Municipality.create(description: "Vizzola Ticino", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 428)
Municipality.create(description: "Viggiu'", province_id: 100, region_id:  19, country_id: 1, continent_id: 1 , population: 4968)
