#encoding: utf-8
Comune.create(:description => "Agrate Conturbia", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 1184)
Comune.create(:description => "Ameno", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 895)
Comune.create(:description => "Armeno", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 2187)
Comune.create(:description => "Arona", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 14310)
Comune.create(:description => "Barengo", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 942)
Comune.create(:description => "Bellinzago Novarese", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 8365)
Comune.create(:description => "Biandrate", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 1103)
Comune.create(:description => "Boca", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 1186)
Comune.create(:description => "Bogogno", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 1159)
Comune.create(:description => "Bolzano Novarese", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 1040)
Comune.create(:description => "Borgo Ticino", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 3853)
Comune.create(:description => "Borgolavezzaro", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 1879)
Comune.create(:description => "Borgomanero", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 19315)
Comune.create(:description => "Briga Novarese", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 2694)
Comune.create(:description => "Briona", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 1133)
Comune.create(:description => "Caltignaga", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 2345)
Comune.create(:description => "Cameri", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 9673)
Comune.create(:description => "Carpignano Sesia", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 2543)
Comune.create(:description => "Casalbeltrame", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 832)
Comune.create(:description => "Casaleggio Novara", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 847)
Comune.create(:description => "Casalino", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 1456)
Comune.create(:description => "Casalvolone", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 812)
Comune.create(:description => "Castellazzo Novarese", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 260)
Comune.create(:description => "Castelletto Sopra Ticino", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 8755)
Comune.create(:description => "Cavaglietto", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 396)
Comune.create(:description => "Cavallirio", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 1213)
Comune.create(:description => "Cerano", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 6665)
Comune.create(:description => "Colazza", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 416)
Comune.create(:description => "Comignago", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 939)
Comune.create(:description => "Cressa", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 1431)
Comune.create(:description => "Cureggio", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 2251)
Comune.create(:description => "Divignano", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 1232)
Comune.create(:description => "Dormelletto", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 2482)
Comune.create(:description => "Fara Novarese", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 2115)
Comune.create(:description => "Galliate", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 13448)
Comune.create(:description => "Garbagna Novarese", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 964)
Comune.create(:description => "Gargallo", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 1673)
Comune.create(:description => "Gattico", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 3134)
Comune.create(:description => "Ghemme", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 3722)
Comune.create(:description => "Gozzano", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 5982)
Comune.create(:description => "Granozzo Con Monticello", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 1216)
Comune.create(:description => "Grignasco", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 4704)
Comune.create(:description => "Invorio", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 3732)
Comune.create(:description => "Landiona", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 587)
Comune.create(:description => "Lesa", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 2401)
Comune.create(:description => "Maggiora", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 1664)
Comune.create(:description => "Mandello Vitta", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 262)
Comune.create(:description => "Marano Ticino", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 1407)
Comune.create(:description => "Massino Visconti", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 1090)
Comune.create(:description => "Meina", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 2341)
Comune.create(:description => "Mezzomerico", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 951)
Comune.create(:description => "Miasino", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 953)
Comune.create(:description => "Momo", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 2732)
Comune.create(:description => "Nebbiuno", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 1561)
Comune.create(:description => "Nibbiola", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 720)
Comune.create(:description => "Novara", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 100910)
Comune.create(:description => "Oleggio", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 12191)
Comune.create(:description => "Oleggio Castello", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 1729)
Comune.create(:description => "Orta San Giulio", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 1119)
Comune.create(:description => "Paruzzaro", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 1588)
Comune.create(:description => "Pella", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 1148)
Comune.create(:description => "Pettenasco", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 1310)
Comune.create(:description => "Pisano", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 770)
Comune.create(:description => "Pogno", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 1488)
Comune.create(:description => "Pombia", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 1818)
Comune.create(:description => "Prato Sesia", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 1936)
Comune.create(:description => "Recetto", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 897)
Comune.create(:description => "Romagnano Sesia", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 4216)
Comune.create(:description => "Romentino", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 4240)
Comune.create(:description => "San Nazzaro Sesia", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 726)
Comune.create(:description => "San Pietro Mosezzo", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 1738)
Comune.create(:description => "Sillavengo", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 567)
Comune.create(:description => "Sizzano", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 1458)
Comune.create(:description => "Soriso", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 730)
Comune.create(:description => "Sozzago", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 859)
Comune.create(:description => "Suno", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 2834)
Comune.create(:description => "Terdobbiate", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 470)
Comune.create(:description => "Tornaco", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 878)
Comune.create(:description => "Trecate", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 16915)
Comune.create(:description => "Varallo Pombia", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 4403)
Comune.create(:description => "Veruno", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 1576)
Comune.create(:description => "Vespolate", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 2076)
Comune.create(:description => "Vicolungo", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 842)
Comune.create(:description => "Vinzaglio", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 609)
Comune.create(:description => "Cavaglio D'Agogna", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 1282)
Comune.create(:description => "Fontaneto D'Agogna", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 2549)
Comune.create(:description => "San Maurizio D'Opaglio", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 3066)
Comune.create(:description => "Vaprio D'Agogna", :provincia_id => 9, :regione_id => 13, stato_id: 1, continente_id: 1 , :population => 950)
