Municipality.create(description: "Agrate Conturbia", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 1184)
Municipality.create(description: "Ameno", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 895)
Municipality.create(description: "Armeno", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 2187)
Municipality.create(description: "Arona", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 14310)
Municipality.create(description: "Barengo", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 942)
Municipality.create(description: "Bellinzago Novarese", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 8365)
Municipality.create(description: "Biandrate", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 1103)
Municipality.create(description: "Boca", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 1186)
Municipality.create(description: "Bogogno", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 1159)
Municipality.create(description: "Bolzano Novarese", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 1040)
Municipality.create(description: "Borgo Ticino", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 3853)
Municipality.create(description: "Borgolavezzaro", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 1879)
Municipality.create(description: "Borgomanero", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 19315)
Municipality.create(description: "Briga Novarese", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 2694)
Municipality.create(description: "Briona", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 1133)
Municipality.create(description: "Caltignaga", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 2345)
Municipality.create(description: "Cameri", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 9673)
Municipality.create(description: "Carpignano Sesia", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 2543)
Municipality.create(description: "Casalbeltrame", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 832)
Municipality.create(description: "Casaleggio Novara", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 847)
Municipality.create(description: "Casalino", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 1456)
Municipality.create(description: "Casalvolone", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 812)
Municipality.create(description: "Castellazzo Novarese", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 260)
Municipality.create(description: "Castelletto Sopra Ticino", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 8755)
Municipality.create(description: "Cavaglietto", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 396)
Municipality.create(description: "Cavallirio", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 1213)
Municipality.create(description: "Cerano", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 6665)
Municipality.create(description: "Colazza", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 416)
Municipality.create(description: "Comignago", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 939)
Municipality.create(description: "Cressa", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 1431)
Municipality.create(description: "Cureggio", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 2251)
Municipality.create(description: "Divignano", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 1232)
Municipality.create(description: "Dormelletto", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 2482)
Municipality.create(description: "Fara Novarese", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 2115)
Municipality.create(description: "Galliate", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 13448)
Municipality.create(description: "Garbagna Novarese", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 964)
Municipality.create(description: "Gargallo", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 1673)
Municipality.create(description: "Gattico", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 3134)
Municipality.create(description: "Ghemme", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 3722)
Municipality.create(description: "Gozzano", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 5982)
Municipality.create(description: "Granozzo Con Monticello", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 1216)
Municipality.create(description: "Grignasco", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 4704)
Municipality.create(description: "Invorio", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 3732)
Municipality.create(description: "Landiona", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 587)
Municipality.create(description: "Lesa", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 2401)
Municipality.create(description: "Maggiora", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 1664)
Municipality.create(description: "Mandello Vitta", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 262)
Municipality.create(description: "Marano Ticino", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 1407)
Municipality.create(description: "Massino Visconti", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 1090)
Municipality.create(description: "Meina", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 2341)
Municipality.create(description: "Mezzomerico", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 951)
Municipality.create(description: "Miasino", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 953)
Municipality.create(description: "Momo", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 2732)
Municipality.create(description: "Nebbiuno", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 1561)
Municipality.create(description: "Nibbiola", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 720)
Municipality.create(description: "Novara", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 100910)
Municipality.create(description: "Oleggio", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 12191)
Municipality.create(description: "Oleggio Castello", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 1729)
Municipality.create(description: "Orta San Giulio", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 1119)
Municipality.create(description: "Paruzzaro", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 1588)
Municipality.create(description: "Pella", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 1148)
Municipality.create(description: "Pettenasco", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 1310)
Municipality.create(description: "Pisano", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 770)
Municipality.create(description: "Pogno", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 1488)
Municipality.create(description: "Pombia", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 1818)
Municipality.create(description: "Prato Sesia", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 1936)
Municipality.create(description: "Recetto", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 897)
Municipality.create(description: "Romagnano Sesia", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 4216)
Municipality.create(description: "Romentino", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 4240)
Municipality.create(description: "San Nazzaro Sesia", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 726)
Municipality.create(description: "San Pietro Mosezzo", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 1738)
Municipality.create(description: "Sillavengo", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 567)
Municipality.create(description: "Sizzano", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 1458)
Municipality.create(description: "Soriso", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 730)
Municipality.create(description: "Sozzago", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 859)
Municipality.create(description: "Suno", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 2834)
Municipality.create(description: "Terdobbiate", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 470)
Municipality.create(description: "Tornaco", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 878)
Municipality.create(description: "Trecate", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 16915)
Municipality.create(description: "Varallo Pombia", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 4403)
Municipality.create(description: "Veruno", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 1576)
Municipality.create(description: "Vespolate", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 2076)
Municipality.create(description: "Vicolungo", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 842)
Municipality.create(description: "Vinzaglio", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 609)
Municipality.create(description: "Cavaglio D'Agogna", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 1282)
Municipality.create(description: "Fontaneto D'Agogna", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 2549)
Municipality.create(description: "San Maurizio D'Opaglio", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 3066)
Municipality.create(description: "Vaprio D'Agogna", province_id: 9, region_id:  13, country_id: 1, continent_id: 1 , population: 950)
