require: rubocop-rspec

Rails:
  Enabled: true

#Metrics/LineLength:
#  Max: 120

Style/Documentation:
  Enabled: false

Layout/MultilineOperationIndentation:
    EnforcedStyle: indented

Style/NonNilCheck:
  IncludeSemanticChanges: true

Layout/DotPosition:
  EnforcedStyle: trailing

Style/FrozenStringLiteralComment:
  Enabled: false

Rails/ActiveRecordOverride:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

# TODO: re-enable
RSpec/ExpectInHook:
  Enabled: false

Capybara/CurrentPathExpectation:
  Enabled: false

AllCops:
  Exclude:
    - 'uploads/**/*'
    - 'bin/**/*'
    - 'script/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'db/**/*'

inherit_from: .rubocop_todo.yml
