#quando si creano eventi che si ripetono per sempre li crea fino a questa data
END_TIME = Date.parse("1 Jan, 2016").to_time

POSITIVE_VALUTATION = 1
NEUTRAL_VALUTATION = 2
NEGATIVE_VALUTATION = 3

PROP_WAIT_DATE=2
PROP_WAIT=3
PROP_VOTING=4
PROP_RESP=5
PROP_ACCEPT=6
PROP_REVISION=7

CONTRIBUTE_MAX_LENGTH = 2000

DEFAULT_CHANGE_ADVANCED_OPTIONS = false
DEFAULT_ANONIMA = true
DEFAULT_GROUP_ACTIONS = [1,2,6,7,8,12]
DEFAULT_AREA_ACTIONS = [6,7,8,11,12]

CONTRIBUTE_MARKS = 3

DEBATE_VOTE_DIFFERENCE = 10.minutes