END_TIME = Date.parse("1 Jan, 2016").to_time
VERSION = '0.8.9'

POSITIVE_VALUTATION = 1
NEGATIVE_VALUTATION = 3

PROP_VALUT=1
PROP_WAIT_DATE=2
PROP_WAIT=3
PROP_VOTING=4
PROP_RESP=5
PROP_ACCEPT=6
PROP_REVISION=7
ORDER_BY_DATE="2"
ORDER_BY_RANK="3"
ORDER_BY_VOTES="4"
VALUTATION_STATE="1"
VOTATION_STATE="2"
ACCEPTED_STATE="3"
REVISION_STATE="4"

CONTRIBUTE_MAX_LENGTH = 2000