#quando si creano eventi che si ripetono per sempre li crea fino a questa data
END_TIME = Date.parse("1 Jan, 2016").to_time

POSITIVE_VALUTATION = 1
NEUTRAL_VALUTATION = 2
NEGATIVE_VALUTATION = 3


PROP_VALUT=1
PROP_WAIT_DATE=2
PROP_WAIT=3
PROP_VOTING=4
PROP_RESP=5
PROP_ACCEPT=6
PROP_REVISION=7

ORDER_RANDOM="1"
ORDER_BY_DATE="2"
ORDER_BY_RANK="3"
ORDER_BY_VOTES="4"
ORDER_BY_END="5"
ORDER_ASC="a"
ORDER_DESC="d"


CONTRIBUTE_MAX_LENGTH = 2000

APP_SHORT_NAME = "Airesis"
APP_LONG_NAME = "Airesis - Scegli di partecipare"
APP_EMAIL_ADDRESS = "info@airesis.it"

DEFAULT_CHANGE_ADVANCED_OPTIONS = false
DEFAULT_ANONIMA = true
DEFAULT_GROUP_ACTIONS = [1,2,6,7,8]
DEFAULT_AREA_ACTIONS = [6,7,8,11]

CONTRIBUTE_MARKS = 3