#!/bin/bash
export RAILS_ENV=production
rake sunspot:solr:start
rackup private_pub.ru -s thin -E production -D -P tmp/pids/rackup.pid
#sidekiqctl stop ./tmp/pids/sidekiq.pid
sidekiq -d -L log/sidekiq.log 

