#encoding: utf-8
class InsertAndTranslateStates < ActiveRecord::Migration
  def up
    add_column :statos, :sigla_ext, :string, limit: 3

    Stato.create_translation_table!({
                                        description: :string
                                    }, {
                                        migrate_data: true
                                    })

    Stato.create(description: 'Isole Åland', continente_id: 1, sigla: 'AX',sigla_ext: 'ALA')
    Stato.create(description: 'Albania', continente_id: 1, sigla: 'AL',sigla_ext: 'ALB')
    Stato.create(description: 'Andorra', continente_id: 1, sigla: 'AD',sigla_ext: 'AND')
    Stato.create(description: 'Austria', continente_id: 1, sigla: 'AT',sigla_ext: 'AUT')
    Stato.create(description: 'Bielorussia', continente_id: 1, sigla: 'BY',sigla_ext: 'BLR')
    Stato.create(description: 'Belgio', continente_id: 1, sigla: 'BE',sigla_ext: 'BEL')
    Stato.create(description: 'Bosnia ed Erzegovina', continente_id: 1, sigla: 'BA',sigla_ext: 'BIH')
    Stato.create(description: 'Bulgaria', continente_id: 1, sigla: 'BG',sigla_ext: 'BGR')
    Stato.create(description: 'Croazia', continente_id: 1, sigla: 'HR',sigla_ext: 'HRV')
    Stato.create(description: 'Repubblica Ceca', continente_id: 1, sigla: 'CZ',sigla_ext: 'CZE')
    Stato.create(description: 'Danimarca', continente_id: 1, sigla: 'DK',sigla_ext: 'DNK')
    Stato.create(description: 'Estonia', continente_id: 1, sigla: 'EE',sigla_ext: 'EST')
    Stato.create(description: 'Isole Fær Øer', continente_id: 1, sigla: 'FO',sigla_ext: 'FRO')
    Stato.create(description: 'Finlandia', continente_id: 1, sigla: 'FI',sigla_ext: 'FIN')
    Stato.create(description: 'Francia', continente_id: 1, sigla: 'FR',sigla_ext: 'FRA')
    Stato.create(description: 'Germania', continente_id: 1, sigla: 'DE',sigla_ext: 'DEU')
    Stato.create(description: 'Gibilterra', continente_id: 1, sigla: 'GI',sigla_ext: 'GIB')
    Stato.create(description: 'Grecia', continente_id: 1, sigla: 'GR',sigla_ext: 'GRC')
    Stato.create(description: 'Guernsey', continente_id: 1, sigla: 'GG',sigla_ext: 'GGY')
    Stato.create(description: 'Ungheria', continente_id: 1, sigla: 'HU',sigla_ext: 'HUN')
    Stato.create(description: 'Islanda', continente_id: 1, sigla: 'IS',sigla_ext: 'ISL')
    Stato.create(description: 'Irlanda', continente_id: 1, sigla: 'IE',sigla_ext: 'IRL')
    Stato.create(description: 'Isola di Man', continente_id: 1, sigla: 'IM',sigla_ext: 'IMN')
    Stato.create(description: 'Jersey', continente_id: 1, sigla: 'JE',sigla_ext: 'JEY')
    Stato.create(description: 'Kosovo', continente_id: 1, sigla: 'XK',sigla_ext: 'KOS')
    Stato.create(description: 'Lettonia', continente_id: 1, sigla: 'LV',sigla_ext: 'LVA')
    Stato.create(description: 'Liechtenstein', continente_id: 1, sigla: 'LI',sigla_ext: 'LIE')
    Stato.create(description: 'Lituania', continente_id: 1, sigla: 'LT',sigla_ext: 'LTU')
    Stato.create(description: 'Lussemburgo', continente_id: 1, sigla: 'LU',sigla_ext: 'LUX')
    Stato.create(description: 'Macedonia', continente_id: 1, sigla: 'MK',sigla_ext: 'MKD')
    Stato.create(description: 'Malta', continente_id: 1, sigla: 'MT',sigla_ext: 'MLT')
    Stato.create(description: 'Moldavia', continente_id: 1, sigla: 'MD',sigla_ext: 'MDA')
    Stato.create(description: 'Monaco', continente_id: 1, sigla: 'MC',sigla_ext: 'MCO')
    Stato.create(description: 'Montenegro', continente_id: 1, sigla: 'ME',sigla_ext: 'MNE')
    Stato.create(description: 'Olanda', continente_id: 1, sigla: 'NL',sigla_ext: 'NLD')
    Stato.create(description: 'Norvegia', continente_id: 1, sigla: 'NO',sigla_ext: 'NOR')
    Stato.create(description: 'Polonia', continente_id: 1, sigla: 'PL',sigla_ext: 'POL')
    Stato.create(description: 'Portogallo', continente_id: 1, sigla: 'PT',sigla_ext: 'PRT')
    Stato.create(description: 'Romania', continente_id: 1, sigla: 'RO',sigla_ext: 'ROU')
    Stato.create(description: 'Russia', continente_id: 1, sigla: 'RU',sigla_ext: 'RUS')
    Stato.create(description: 'Serbia', continente_id: 1, sigla: 'RS',sigla_ext: 'SRB')
    Stato.create(description: 'Slovacchia', continente_id: 1, sigla: 'SK',sigla_ext: 'SVK')
    Stato.create(description: 'Slovenia', continente_id: 1, sigla: 'SI',sigla_ext: 'SVN')
    Stato.create(description: 'Spagna', continente_id: 1, sigla: 'ES',sigla_ext: 'ESP')
    Stato.create(description: 'Svalbard e Jan Mayen', continente_id: 1, sigla: 'SJ',sigla_ext: 'SJM')
    Stato.create(description: 'Svezia', continente_id: 1, sigla: 'SE',sigla_ext: 'SWE')
    Stato.create(description: 'Svizzera', continente_id: 1, sigla: 'CH',sigla_ext: 'CHE')
    Stato.create(description: 'Ucraina', continente_id: 1, sigla: 'UA',sigla_ext: 'UKR')
    Stato.create(description: 'Inghilterra', continente_id: 1, sigla: 'GB',sigla_ext: 'GBR')

    Stato.find(1).update_attribute(:sigla_ext,'ITA')
    Stato.find(2).update_attribute(:sigla,'SM')
    Stato.find(2).update_attribute(:sigla_ext,'SMR')
    Stato.find(3).update_attribute(:sigla,'VA')
    Stato.find(3).update_attribute(:sigla_ext,'VAT')

    I18n.locale = :eu

    Stato.find_by_sigla('AX').update_attribute(:description,'Åland Islands')
    Stato.find_by_sigla('AL').update_attribute(:description,'Albania')
    Stato.find_by_sigla('AD').update_attribute(:description,'Andorra')
    Stato.find_by_sigla('AT').update_attribute(:description,'Austria')
    Stato.find_by_sigla('BY').update_attribute(:description,'Belarus')
    Stato.find_by_sigla('BE').update_attribute(:description,'Belgium')
    Stato.find_by_sigla('BA').update_attribute(:description,'Bosnia and Herzegovina')
    Stato.find_by_sigla('BG').update_attribute(:description,'Bulgaria')
    Stato.find_by_sigla('HR').update_attribute(:description,'Croatia')
    Stato.find_by_sigla('CZ').update_attribute(:description,'Czech Republic')
    Stato.find_by_sigla('DK').update_attribute(:description,'Denmark')
    Stato.find_by_sigla('EE').update_attribute(:description,'Estonia')
    Stato.find_by_sigla('FO').update_attribute(:description,'Faroe Islands')
    Stato.find_by_sigla('FI').update_attribute(:description,'Finland')
    Stato.find_by_sigla('FR').update_attribute(:description,'France')
    Stato.find_by_sigla('DE').update_attribute(:description,'Germany')
    Stato.find_by_sigla('GI').update_attribute(:description,'Gibraltar')
    Stato.find_by_sigla('GR').update_attribute(:description,'Greece')
    Stato.find_by_sigla('GG').update_attribute(:description,'Guernsey')
    Stato.find_by_sigla('HU').update_attribute(:description,'Hungary')
    Stato.find_by_sigla('IS').update_attribute(:description,'Iceland')
    Stato.find_by_sigla('IE').update_attribute(:description,'Ireland')
    Stato.find_by_sigla('IM').update_attribute(:description,'Isle of Man')
    Stato.find_by_sigla('IT').update_attribute(:description,'Italy')
    Stato.find_by_sigla('JE').update_attribute(:description,'Jersey')
    Stato.find_by_sigla('XK').update_attribute(:description,'Kosovo')
    Stato.find_by_sigla('LV').update_attribute(:description,'Latvia')
    Stato.find_by_sigla('LI').update_attribute(:description,'Liechtenstein')
    Stato.find_by_sigla('LT').update_attribute(:description,'Lithuania')
    Stato.find_by_sigla('LU').update_attribute(:description,'Luxembourg')
    Stato.find_by_sigla('MK').update_attribute(:description,'Macedonia')
    Stato.find_by_sigla('MT').update_attribute(:description,'Malta')
    Stato.find_by_sigla('MD').update_attribute(:description,'Moldova')
    Stato.find_by_sigla('MC').update_attribute(:description,'Monaco')
    Stato.find_by_sigla('ME').update_attribute(:description,'Montenegro')
    Stato.find_by_sigla('NL').update_attribute(:description,'Netherlands')
    Stato.find_by_sigla('NO').update_attribute(:description,'Norway')
    Stato.find_by_sigla('PL').update_attribute(:description,'Poland')
    Stato.find_by_sigla('PT').update_attribute(:description,'Portugal')
    Stato.find_by_sigla('RO').update_attribute(:description,'Romania')
    Stato.find_by_sigla('RU').update_attribute(:description,'Russian Federation')
    Stato.find_by_sigla('SM').update_attribute(:description,'San Marino')
    Stato.find_by_sigla('RS').update_attribute(:description,'Serbia')
    Stato.find_by_sigla('SK').update_attribute(:description,'Slovakia')
    Stato.find_by_sigla('SI').update_attribute(:description,'Slovenia')
    Stato.find_by_sigla('ES').update_attribute(:description,'Spain')
    Stato.find_by_sigla('SJ').update_attribute(:description,'Svalbard and Jan Mayen')
    Stato.find_by_sigla('SE').update_attribute(:description,'Sweden')
    Stato.find_by_sigla('CH').update_attribute(:description,'Switzerland')
    Stato.find_by_sigla('UA').update_attribute(:description,'Ukraine')
    Stato.find_by_sigla('GB').update_attribute(:description,'United Kingdom')
    Stato.find_by_sigla('VA').update_attribute(:description,'Vatican City State')

    I18n.locale = :en

    Stato.find_by_sigla('AX').update_attribute(:description,'Åland Islands')
    Stato.find_by_sigla('AL').update_attribute(:description,'Albania')
    Stato.find_by_sigla('AD').update_attribute(:description,'Andorra')
    Stato.find_by_sigla('AT').update_attribute(:description,'Austria')
    Stato.find_by_sigla('BY').update_attribute(:description,'Belarus')
    Stato.find_by_sigla('BE').update_attribute(:description,'Belgium')
    Stato.find_by_sigla('BA').update_attribute(:description,'Bosnia and Herzegovina')
    Stato.find_by_sigla('BG').update_attribute(:description,'Bulgaria')
    Stato.find_by_sigla('HR').update_attribute(:description,'Croatia')
    Stato.find_by_sigla('CZ').update_attribute(:description,'Czech Republic')
    Stato.find_by_sigla('DK').update_attribute(:description,'Denmark')
    Stato.find_by_sigla('EE').update_attribute(:description,'Estonia')
    Stato.find_by_sigla('FO').update_attribute(:description,'Faroe Islands')
    Stato.find_by_sigla('FI').update_attribute(:description,'Finland')
    Stato.find_by_sigla('FR').update_attribute(:description,'France')
    Stato.find_by_sigla('DE').update_attribute(:description,'Germany')
    Stato.find_by_sigla('GI').update_attribute(:description,'Gibraltar')
    Stato.find_by_sigla('GR').update_attribute(:description,'Greece')
    Stato.find_by_sigla('GG').update_attribute(:description,'Guernsey')
    Stato.find_by_sigla('HU').update_attribute(:description,'Hungary')
    Stato.find_by_sigla('IS').update_attribute(:description,'Iceland')
    Stato.find_by_sigla('IE').update_attribute(:description,'Ireland')
    Stato.find_by_sigla('IM').update_attribute(:description,'Isle of Man')
    Stato.find_by_sigla('IT').update_attribute(:description,'Italy')
    Stato.find_by_sigla('JE').update_attribute(:description,'Jersey')
    Stato.find_by_sigla('XK').update_attribute(:description,'Kosovo')
    Stato.find_by_sigla('LV').update_attribute(:description,'Latvia')
    Stato.find_by_sigla('LI').update_attribute(:description,'Liechtenstein')
    Stato.find_by_sigla('LT').update_attribute(:description,'Lithuania')
    Stato.find_by_sigla('LU').update_attribute(:description,'Luxembourg')
    Stato.find_by_sigla('MK').update_attribute(:description,'Macedonia')
    Stato.find_by_sigla('MT').update_attribute(:description,'Malta')
    Stato.find_by_sigla('MD').update_attribute(:description,'Moldova')
    Stato.find_by_sigla('MC').update_attribute(:description,'Monaco')
    Stato.find_by_sigla('ME').update_attribute(:description,'Montenegro')
    Stato.find_by_sigla('NL').update_attribute(:description,'Netherlands')
    Stato.find_by_sigla('NO').update_attribute(:description,'Norway')
    Stato.find_by_sigla('PL').update_attribute(:description,'Poland')
    Stato.find_by_sigla('PT').update_attribute(:description,'Portugal')
    Stato.find_by_sigla('RO').update_attribute(:description,'Romania')
    Stato.find_by_sigla('RU').update_attribute(:description,'Russian Federation')
    Stato.find_by_sigla('SM').update_attribute(:description,'San Marino')
    Stato.find_by_sigla('RS').update_attribute(:description,'Serbia')
    Stato.find_by_sigla('SK').update_attribute(:description,'Slovakia')
    Stato.find_by_sigla('SI').update_attribute(:description,'Slovenia')
    Stato.find_by_sigla('ES').update_attribute(:description,'Spain')
    Stato.find_by_sigla('SJ').update_attribute(:description,'Svalbard and Jan Mayen')
    Stato.find_by_sigla('SE').update_attribute(:description,'Sweden')
    Stato.find_by_sigla('CH').update_attribute(:description,'Switzerland')
    Stato.find_by_sigla('UA').update_attribute(:description,'Ukraine')
    Stato.find_by_sigla('GB').update_attribute(:description,'United Kingdom')
    Stato.find_by_sigla('VA').update_attribute(:description,'Vatican City State')

  end

  def down
    remove_column :statos, :sigla_ext
    Stato.drop_translation_table! migrate_data: true
  end
end
