#encoding: utf-8
class AddRomania < ActiveRecord::Migration
  def up


    I18n.locale = 'en'
    @romania = Stato.find_by_description('Romania')


    I18n.locale = 'ro-RO'
    @romania.update_attribute(:description, 'România')
    @romania_id = @romania.id
    @europa_id = @romania.continente_id

    SysLocale.create(:key => 'ro-RO', :host => 'www.airesis.eu', lang: 'ro-RO', territory: @romania)

    Regione.create(description: 'Bucovina', stato_id: @romania_id, continente_id: @europa_id)
    Regione.create(description: 'Crișana', stato_id: @romania_id, continente_id: @europa_id)
    Regione.create(description: 'Dobrogea', stato_id: @romania_id, continente_id: @europa_id)
    Regione.create(description: 'Oltenia', stato_id: @romania_id, continente_id: @europa_id)
    Regione.create(description: 'Maramureș', stato_id: @romania_id, continente_id: @europa_id)
    Regione.create(description: 'Moldova', stato_id: @romania_id, continente_id: @europa_id)
    Regione.create(description: 'Muntenia', stato_id: @romania_id, continente_id: @europa_id)
    Regione.create(description: 'Transilvania', stato_id: @romania_id, continente_id: @europa_id)
    Regione.create(description: 'Banat', stato_id: @romania_id, continente_id: @europa_id)


    Provincia.create(description: 'Alba', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), population: 327258)
    Provincia.create(description: 'Arad', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Crișana'), population: 409072)
    Provincia.create(description: 'Argeș', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), population: 591353)
    Provincia.create(description: 'Bacău', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Moldova'), population: 583590)
    Provincia.create(description: 'Bihor', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Crișana'), population: 549752)
    Provincia.create(description: 'Bistrița-Năsăud', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), population: 277861)
    Provincia.create(description: 'Botoșani', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Bucovina'), population: 398932)
    Provincia.create(description: 'Brașov', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), population: 505442)
    Provincia.create(description: 'Brăila', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), population: 304925)
    Provincia.create(description: 'Buzău', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), population: 432050)
    Provincia.create(description: 'Caraș-Severin', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Banat'), population: 274277)
    Provincia.create(description: 'Călărași', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), population: 285107)
    Provincia.create(description: 'Cluj', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), population: 659370)
    Provincia.create(description: 'Constanța', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Dobrogea'), population: 630679)
    Provincia.create(description: 'Covasna', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), population: 206261)
    Provincia.create(description: 'Dâmbovița', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), population: 501996)
    Provincia.create(description: 'Dolj', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Oltenia'), population: 618335)
    Provincia.create(description: 'Galați', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Moldova'), population: 507402)
    Provincia.create(description: 'Giurgiu', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), population: 265493)
    Provincia.create(description: 'Gorj', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Oltenia'), population: 334231)
    Provincia.create(description: 'Harghita', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), population: 304969)
    Provincia.create(description: 'Hunedoara', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), population: 396253)
    Provincia.create(description: 'Ialomița', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), population: 258669)
    Provincia.create(description: 'Iași', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Moldova'), population: 723553)
    Provincia.create(description: 'Ilfov', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), population: 364241)
    Provincia.create(description: 'Maramureș', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Maramureș'), population: 461290)
    Provincia.create(description: 'Mehedinți', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Oltenia'), population: 254570)
    Provincia.create(description: 'Mureș', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), population: 531380)
    Provincia.create(description: 'Neamț', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Moldova'), population: 452900)
    Provincia.create(description: 'Olt', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Oltenia'), population: 415530)
    Provincia.create(description: 'Prahova', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), population: 735883)
    Provincia.create(description: 'Satu Mare', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Maramureș'), population: 329079)
    Provincia.create(description: 'Sălaj', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), population: 217895)
    Provincia.create(description: 'Sibiu', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), population: 375992)
    Provincia.create(description: 'Suceava', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Bucovina'), population: 614451)
    Provincia.create(description: 'Teleorman', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), population: 360178)
    Provincia.create(description: 'Timiș', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Banat'), population: 650544)
    Provincia.create(description: 'Tulcea', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Dobrogea'), population: 201468)
    Provincia.create(description: 'Vaslui', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Moldova'), population: 375151)
    Provincia.create(description: 'Vâlcea', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Moldova'), population: 355320)
    Provincia.create(description: 'Vrancea', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Moldova'), population: 323080)
    Provincia.create(description: 'Mun. Bucuresti', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), population: 1677985)


    Comune.create(description: 'București', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Mun. Bucuresti'), population: 188343)
    Comune.create(description: 'Abrud', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Alba'), population: 5072)
    Comune.create(description: 'Aiud', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Alba'), population: 22876)
    Comune.create(description: 'Alba Iulia', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Alba'), population: 63536)
    Comune.create(description: 'Baia de Arieș', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Alba'), population: 3461)
    Comune.create(description: 'Blaj', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Alba'), population: 2063)
    Comune.create(description: 'Câmpeni', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Alba'), population: 7221)
    Comune.create(description: 'Cugir', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Alba'), population: 21376)
    Comune.create(description: 'Ocna Mureș', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Alba'), population: 13036)
    Comune.create(description: 'Sebeș', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Alba'), population: 27019)
    Comune.create(description: 'Teiuș', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Alba'), population: 6695)
    Comune.create(description: 'Zlatna', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Alba'), population: 749)
    Comune.create(description: 'Arad', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Crișana'), provincia_id: Provincia.find_by_description('Arad'), population: 159074)
    Comune.create(description: 'Chișineu-Criș', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Crișana'), provincia_id: Provincia.find_by_description('Arad'), population: 7987)
    Comune.create(description: 'Curtici', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Crișana'), provincia_id: Provincia.find_by_description('Arad'), population: 7453)
    Comune.create(description: 'Ineu', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Crișana'), provincia_id: Provincia.find_by_description('Arad'), population: 9078)
    Comune.create(description: 'Lipova', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Crișana'), provincia_id: Provincia.find_by_description('Arad'), population: 9648)
    Comune.create(description: 'Nădlac', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Crișana'), provincia_id: Provincia.find_by_description('Arad'), population: 7398)
    Comune.create(description: 'Pâncota', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Crișana'), provincia_id: Provincia.find_by_description('Arad'), population: 6946)
    Comune.create(description: 'Pecica', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Crișana'), provincia_id: Provincia.find_by_description('Arad'), population: 12762)
    Comune.create(description: 'Sântana', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Crișana'), provincia_id: Provincia.find_by_description('Arad'), population: 11428)
    Comune.create(description: 'Sebiș', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Crișana'), provincia_id: Provincia.find_by_description('Arad'), population: 5979)
    Comune.create(description: 'Câmpulung', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Argeș'), population: 31767)
    Comune.create(description: 'Costești', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Argeș'), population: 10375)
    Comune.create(description: 'Curtea de Argeș', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Argeș'), population: 27359)
    Comune.create(description: 'Mioveni', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Argeș'), population: 31998)
    Comune.create(description: 'Pitești', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Argeș'), population: 155383)
    Comune.create(description: 'Ștefănești', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Argeș'), population: 14541)
    Comune.create(description: 'Topoloveni', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Argeș'), population: 10219)
    Comune.create(description: 'Bacău', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Moldova'), provincia_id: Provincia.find_by_description('Bacău'), population: 144307)
    Comune.create(description: 'Buhuși', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Moldova'), provincia_id: Provincia.find_by_description('Bacău'), population: 14562)
    Comune.create(description: 'Comănești', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Moldova'), provincia_id: Provincia.find_by_description('Bacău'), population: 19568)
    Comune.create(description: 'Dărmănești', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Moldova'), provincia_id: Provincia.find_by_description('Bacău'), population: 12247)
    Comune.create(description: 'Moinești', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Moldova'), provincia_id: Provincia.find_by_description('Bacău'), population: 21787)
    Comune.create(description: 'Onești', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Moldova'), provincia_id: Provincia.find_by_description('Bacău'), population: 39172)
    Comune.create(description: 'Slănic Moldova', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Moldova'), provincia_id: Provincia.find_by_description('Bacău'), population: 4198)
    Comune.create(description: 'Târgu Ocna', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Moldova'), provincia_id: Provincia.find_by_description('Bacău'), population: 113)
    Comune.create(description: 'Aleșd', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Crișana'), provincia_id: Provincia.find_by_description('Bihor'), population: 9619)
    Comune.create(description: 'Beiuș', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Crișana'), provincia_id: Provincia.find_by_description('Bihor'), population: 10667)
    Comune.create(description: 'Marghita', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Crișana'), provincia_id: Provincia.find_by_description('Bihor'), population: 1577)
    Comune.create(description: 'Nucet', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Crișana'), provincia_id: Provincia.find_by_description('Bihor'), population: 2165)
    Comune.create(description: 'Oradea', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Crișana'), provincia_id: Provincia.find_by_description('Bihor'), population: 196367)
    Comune.create(description: 'Salonta', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Crișana'), provincia_id: Provincia.find_by_description('Bihor'), population: 17735)
    Comune.create(description: 'Săcueni', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Crișana'), provincia_id: Provincia.find_by_description('Bihor'), population: 11526)
    Comune.create(description: 'Ștei', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Crișana'), provincia_id: Provincia.find_by_description('Bihor'), population: 6529)
    Comune.create(description: 'Valea lui Mihai', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Crișana'), provincia_id: Provincia.find_by_description('Bihor'), population: 9902)
    Comune.create(description: 'Vașcău', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Crișana'), provincia_id: Provincia.find_by_description('Bihor'), population: 2315)
    Comune.create(description: 'Beclean', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Bistrița-Năsăud'), population: 10628)
    Comune.create(description: 'Bistrița', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Bistrița-Năsăud'), population: 75076)
    Comune.create(description: 'Năsăud', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Bistrița-Năsăud'), population: 9077)
    Comune.create(description: 'Sângeorz-Băi', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Bistrița-Năsăud'), population: 9413)
    Comune.create(description: 'Botoșani', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Bucovina'), provincia_id: Provincia.find_by_description('Botoșani'), population: 106847)
    Comune.create(description: 'Bucecea', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Bucovina'), provincia_id: Provincia.find_by_description('Botoșani'), population: 4274)
    Comune.create(description: 'Darabani', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Bucovina'), provincia_id: Provincia.find_by_description('Botoșani'), population: 9523)
    Comune.create(description: 'Dorohoi', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Bucovina'), provincia_id: Provincia.find_by_description('Botoșani'), population: 24309)
    Comune.create(description: 'Flămânzi', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Bucovina'), provincia_id: Provincia.find_by_description('Botoșani'), population: 9456)
    Comune.create(description: 'Săveni', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Bucovina'), provincia_id: Provincia.find_by_description('Botoșani'), population: 6999)
    Comune.create(description: 'Ștefănești', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Bucovina'), provincia_id: Provincia.find_by_description('Botoșani'), population: 5314)
    Comune.create(description: 'Brașov', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Brașov'), population: 2532)
    Comune.create(description: 'Codlea', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Brașov'), population: 21708)
    Comune.create(description: 'Făgăraș', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Brașov'), population: 30714)
    Comune.create(description: 'Ghimbav', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Brașov'), population: 4698)
    Comune.create(description: 'Predeal', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Brașov'), population: 4755)
    Comune.create(description: 'Râșnov', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Brașov'), population: 15022)
    Comune.create(description: 'Rupea', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Brașov'), population: 5269)
    Comune.create(description: 'Săcele', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Brașov'), population: 30798)
    Comune.create(description: 'Victoria', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Brașov'), population: 7386)
    Comune.create(description: 'Zărnești', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Brașov'), population: 23476)
    Comune.create(description: 'Brăila', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Brăila'), population: 180302)
    Comune.create(description: 'Făurei', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Brăila'), population: 3592)
    Comune.create(description: 'Ianca', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Brăila'), population: 10343)
    Comune.create(description: 'Însurăței', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Brăila'), population: 6528)
    Comune.create(description: 'Buzău', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Buzău'), population: 115494)
    Comune.create(description: 'Nehoiu', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Buzău'), population: 10211)
    Comune.create(description: 'Pătârlagele', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Buzău'), population: 7304)
    Comune.create(description: 'Pogoanele', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Buzău'), population: 7275)
    Comune.create(description: 'Râmnicu Sărat', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Buzău'), population: 33843)
    Comune.create(description: 'Anina', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Banat'), provincia_id: Provincia.find_by_description('Caraș-Severin'), population: 7485)
    Comune.create(description: 'Băile Herculane', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Banat'), provincia_id: Provincia.find_by_description('Caraș-Severin'), population: 5008)
    Comune.create(description: 'Bocșa', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Banat'), provincia_id: Provincia.find_by_description('Caraș-Severin'), population: 15842)
    Comune.create(description: 'Caransebeș', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Banat'), provincia_id: Provincia.find_by_description('Caraș-Severin'), population: 24689)
    Comune.create(description: 'Moldova Nouă', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Banat'), provincia_id: Provincia.find_by_description('Caraș-Severin'), population: 1235)
    Comune.create(description: 'Oravița', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Banat'), provincia_id: Provincia.find_by_description('Caraș-Severin'), population: 11382)
    Comune.create(description: 'Oțelu Roșu', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Banat'), provincia_id: Provincia.find_by_description('Caraș-Severin'), population: 926)
    Comune.create(description: 'Reșița', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Banat'), provincia_id: Provincia.find_by_description('Caraș-Severin'), population: 73282)
    Comune.create(description: 'Budești', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Călărași'), population: 7725)
    Comune.create(description: 'Călărași', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Călărași'), population: 65181)
    Comune.create(description: 'Fundulea', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Călărași'), population: 6851)
    Comune.create(description: 'Lehliu Gară', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Călărași'), population: 6502)
    Comune.create(description: 'Oltenița', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Călărași'), population: 24822)
    Comune.create(description: 'Câmpia Turzii', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Cluj'), population: 22223)
    Comune.create(description: 'Cluj-Napoca', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Cluj'), population: 324576)
    Comune.create(description: 'Dej', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Cluj'), population: 33497)
    Comune.create(description: 'Gherla', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Cluj'), population: 20892)
    Comune.create(description: 'Huedin', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Cluj'), population: 9346)
    Comune.create(description: 'Turda', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Cluj'), population: 47744)
    Comune.create(description: 'Băneasa', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Dobrogea'), provincia_id: Provincia.find_by_description('Constanța'), population: 5384)
    Comune.create(description: 'Cernavodă', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Dobrogea'), provincia_id: Provincia.find_by_description('Constanța'), population: 17022)
    Comune.create(description: 'Constanța', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Dobrogea'), provincia_id: Provincia.find_by_description('Constanța'), population: 283872)
    Comune.create(description: 'Eforie', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Dobrogea'), provincia_id: Provincia.find_by_description('Constanța'), population: 9473)
    Comune.create(description: 'Hârșova', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Dobrogea'), provincia_id: Provincia.find_by_description('Constanța'), population: 9642)
    Comune.create(description: 'Mangalia', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Dobrogea'), provincia_id: Provincia.find_by_description('Constanța'), population: 36364)
    Comune.create(description: 'Medgidia', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Dobrogea'), provincia_id: Provincia.find_by_description('Constanța'), population: 3978)
    Comune.create(description: 'Murfatlar', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Dobrogea'), provincia_id: Provincia.find_by_description('Constanța'), population: 9634)
    Comune.create(description: 'Năvodari', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Dobrogea'), provincia_id: Provincia.find_by_description('Constanța'), population: 32981)
    Comune.create(description: 'Negru Vodă', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Dobrogea'), provincia_id: Provincia.find_by_description('Constanța'), population: 5088)
    Comune.create(description: 'Ovidiu', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Dobrogea'), provincia_id: Provincia.find_by_description('Constanța'), population: 13847)
    Comune.create(description: 'Techirghiol', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Dobrogea'), provincia_id: Provincia.find_by_description('Constanța'), population: 7292)
    Comune.create(description: 'Baraolt', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Covasna'), population: 8672)
    Comune.create(description: 'Covasna', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Covasna'), population: 10114)
    Comune.create(description: 'Întorsura Buzăului', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Covasna'), population: 7528)
    Comune.create(description: 'Sfântu Gheorghe', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Covasna'), population: 56006)
    Comune.create(description: 'Târgu Secuiesc', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Covasna'), population: 18491)
    Comune.create(description: 'Fieni', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Dâmbovița'), population: 7587)
    Comune.create(description: 'Găești', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Dâmbovița'), population: 13317)
    Comune.create(description: 'Moreni', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Dâmbovița'), population: 18687)
    Comune.create(description: 'Pucioasa', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Dâmbovița'), population: 14254)
    Comune.create(description: 'Răcari', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Dâmbovița'), population: 693)
    Comune.create(description: 'Târgoviște', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Dâmbovița'), population: 7961)
    Comune.create(description: 'Titu', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Dâmbovița'), population: 9355)
    Comune.create(description: 'Băilești', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Oltenia'), provincia_id: Provincia.find_by_description('Dolj'), population: 17437)
    Comune.create(description: 'Bechet', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Oltenia'), provincia_id: Provincia.find_by_description('Dolj'), population: 3657)
    Comune.create(description: 'Calafat', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Oltenia'), provincia_id: Provincia.find_by_description('Dolj'), population: 17336)
    Comune.create(description: 'Craiova', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Oltenia'), provincia_id: Provincia.find_by_description('Dolj'), population: 269506)
    Comune.create(description: 'Dăbuleni', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Oltenia'), provincia_id: Provincia.find_by_description('Dolj'), population: 12182)
    Comune.create(description: 'Filiași', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Oltenia'), provincia_id: Provincia.find_by_description('Dolj'), population: 169)
    Comune.create(description: 'Segarcea', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Oltenia'), provincia_id: Provincia.find_by_description('Dolj'), population: 7019)
    Comune.create(description: 'Berești', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Moldova'), provincia_id: Provincia.find_by_description('Galați'), population: 2916)
    Comune.create(description: 'Galați', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Moldova'), provincia_id: Provincia.find_by_description('Galați'), population: 249432)
    Comune.create(description: 'Târgu Bujor', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Moldova'), provincia_id: Provincia.find_by_description('Galați'), population: 6299)
    Comune.create(description: 'Tecuci', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Moldova'), provincia_id: Provincia.find_by_description('Galați'), population: 34871)
    Comune.create(description: 'Bolintin-Vale', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Giurgiu'), population: 12929)
    Comune.create(description: 'Giurgiu', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Giurgiu'), population: 61353)
    Comune.create(description: 'Mihăilești', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Giurgiu'), population: 7923)
    Comune.create(description: 'Bumbești-Jiu', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Oltenia'), provincia_id: Provincia.find_by_description('Gorj'), population: 8932)
    Comune.create(description: 'Motru', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Oltenia'), provincia_id: Provincia.find_by_description('Gorj'), population: 19079)
    Comune.create(description: 'Novaci', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Oltenia'), provincia_id: Provincia.find_by_description('Gorj'), population: 5431)
    Comune.create(description: 'Rovinari', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Oltenia'), provincia_id: Provincia.find_by_description('Gorj'), population: 11816)
    Comune.create(description: 'Târgu Cărbunești', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Oltenia'), provincia_id: Provincia.find_by_description('Gorj'), population: 8034)
    Comune.create(description: 'Târgu Jiu', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Oltenia'), provincia_id: Provincia.find_by_description('Gorj'), population: 82504)
    Comune.create(description: 'Tismana', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Oltenia'), provincia_id: Provincia.find_by_description('Gorj'), population: 7035)
    Comune.create(description: 'Țicleni', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Oltenia'), provincia_id: Provincia.find_by_description('Gorj'), population: 4414)
    Comune.create(description: 'Băile Tușnad', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Harghita'), population: 1641)
    Comune.create(description: 'Bălan', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Harghita'), population: 6115)
    Comune.create(description: 'Borsec', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Harghita'), population: 2585)
    Comune.create(description: 'Cristuru Secuiesc', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Harghita'), population: 9491)
    Comune.create(description: 'Gheorgheni', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Harghita'), population: 18377)
    Comune.create(description: 'Miercurea Ciuc', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Harghita'), population: 38966)
    Comune.create(description: 'Odorheiu Secuiesc', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Harghita'), population: 32935)
    Comune.create(description: 'Toplița', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Harghita'), population: 13929)
    Comune.create(description: 'Vlăhița', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Harghita'), population: 6898)
    Comune.create(description: 'Aninoasa', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Hunedoara'), population: 436)
    Comune.create(description: 'Brad', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Hunedoara'), population: 14495)
    Comune.create(description: 'Călan', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Hunedoara'), population: 11279)
    Comune.create(description: 'Deva', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Hunedoara'), population: 61123)
    Comune.create(description: 'Geoagiu', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Hunedoara'), population: 5294)
    Comune.create(description: 'Hațeg', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Hunedoara'), population: 934)
    Comune.create(description: 'Hunedoara', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Hunedoara'), population: 60525)
    Comune.create(description: 'Lupeni', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Hunedoara'), population: 2339)
    Comune.create(description: 'Orăștie', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Hunedoara'), population: 18227)
    Comune.create(description: 'Petrila', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Hunedoara'), population: 22692)
    Comune.create(description: 'Petroșani', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Hunedoara'), population: 3716)
    Comune.create(description: 'Simeria', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Hunedoara'), population: 12556)
    Comune.create(description: 'Uricani', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Hunedoara'), population: 8972)
    Comune.create(description: 'Vulcan', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Hunedoara'), population: 2416)
    Comune.create(description: 'Amara', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Ialomița'), population: 7345)
    Comune.create(description: 'Căzănești', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Ialomița'), population: 3271)
    Comune.create(description: 'Fetești', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Ialomița'), population: 30217)
    Comune.create(description: 'Fierbinți-Târg', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Ialomița'), population: 4969)
    Comune.create(description: 'Slobozia', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Ialomița'), population: 48241)
    Comune.create(description: 'Țăndărei', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Ialomița'), population: 13219)
    Comune.create(description: 'Urziceni', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Ialomița'), population: 15308)
    Comune.create(description: 'Hârlău', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Moldova'), provincia_id: Provincia.find_by_description('Iași'), population: 10905)
    Comune.create(description: 'Iași', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Moldova'), provincia_id: Provincia.find_by_description('Iași'), population: 290422)
    Comune.create(description: 'Pașcani', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Moldova'), provincia_id: Provincia.find_by_description('Iași'), population: 33745)
    Comune.create(description: 'Podu Iloaiei', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Moldova'), provincia_id: Provincia.find_by_description('Iași'), population: 9573)
    Comune.create(description: 'Târgu Frumos', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Moldova'), provincia_id: Provincia.find_by_description('Iași'), population: 9386)
    Comune.create(description: 'Bragadiru', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Ilfov'), population: 15329)
    Comune.create(description: 'Buftea', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Ilfov'), population: 22178)
    Comune.create(description: 'Chitila', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Ilfov'), population: 14184)
    Comune.create(description: 'Măgurele', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Ilfov'), population: 11041)
    Comune.create(description: 'Otopeni', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Ilfov'), population: 13861)
    Comune.create(description: 'Pantelimon', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Ilfov'), population: 25596)
    Comune.create(description: 'Popești-Leordeni', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Ilfov'), population: 21895)
    Comune.create(description: 'Voluntari', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Ilfov'), population: 42944)
    Comune.create(description: 'Baia Mare', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Maramureș'), provincia_id: Provincia.find_by_description('Ilfov'), population: 123738)
    Comune.create(description: 'Baia Sprie', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Maramureș'), provincia_id: Provincia.find_by_description('Maramureș'), population: 15476)
    Comune.create(description: 'Borșa', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Maramureș'), provincia_id: Provincia.find_by_description('Maramureș'), population: 27611)
    Comune.create(description: 'Cavnic', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Maramureș'), provincia_id: Provincia.find_by_description('Maramureș'), population: 4976)
    Comune.create(description: 'Dragomirești', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Maramureș'), provincia_id: Provincia.find_by_description('Maramureș'), population: 3213)
    Comune.create(description: 'Săliștea de Sus', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Maramureș'), provincia_id: Provincia.find_by_description('Maramureș'), population: 4893)
    Comune.create(description: 'Seini', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Maramureș'), provincia_id: Provincia.find_by_description('Maramureș'), population: 8987)
    Comune.create(description: 'Sighetu Marmației', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Maramureș'), provincia_id: Provincia.find_by_description('Maramureș'), population: 3764)
    Comune.create(description: 'Șomcuta Mare', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Maramureș'), provincia_id: Provincia.find_by_description('Maramureș'), population: 7565)
    Comune.create(description: 'Tăuții-Măgherăuș', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Maramureș'), provincia_id: Provincia.find_by_description('Maramureș'), population: 7136)
    Comune.create(description: 'Târgu Lăpuș', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Maramureș'), provincia_id: Provincia.find_by_description('Maramureș'), population: 11744)
    Comune.create(description: 'Ulmeni', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Maramureș'), provincia_id: Provincia.find_by_description('Maramureș'), population: 727)
    Comune.create(description: 'Vișeu de Sus', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Maramureș'), provincia_id: Provincia.find_by_description('Maramureș'), population: 15037)
    Comune.create(description: 'Baia de Aramă', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Oltenia'), provincia_id: Provincia.find_by_description('Mehedinți'), population: 5349)
    Comune.create(description: 'Drobeta-Turnu Severin', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Oltenia'), provincia_id: Provincia.find_by_description('Mehedinți'), population: 92617)
    Comune.create(description: 'Orșova', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Oltenia'), provincia_id: Provincia.find_by_description('Mehedinți'), population: 10441)
    Comune.create(description: 'Strehaia', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Oltenia'), provincia_id: Provincia.find_by_description('Mehedinți'), population: 10506)
    Comune.create(description: 'Vânju Mare', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Oltenia'), provincia_id: Provincia.find_by_description('Mehedinți'), population: 5311)
    Comune.create(description: 'Iernut', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Mureș'), population: 8705)
    Comune.create(description: 'Luduș', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Mureș'), population: 15328)
    Comune.create(description: 'Miercurea Nirajului', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Mureș'), population: 5554)
    Comune.create(description: 'Reghin', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Mureș'), population: 33281)
    Comune.create(description: 'Sărmașu', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Mureș'), population: 6942)
    Comune.create(description: 'Sângeorgiu de Pădure', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Mureș'), population: 5166)
    Comune.create(description: 'Sighișoara', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Mureș'), population: 28102)
    Comune.create(description: 'Sovata', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Mureș'), population: 10385)
    Comune.create(description: 'Târgu Mureș', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Mureș'), population: 13429)
    Comune.create(description: 'Târnăveni', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Mureș'), population: 22075)
    Comune.create(description: 'Ungheni', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Mureș'), population: 6945)
    Comune.create(description: 'Bicaz', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Moldova'), provincia_id: Provincia.find_by_description('Neamț'), population: 6543)
    Comune.create(description: 'Piatra Neamț', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Moldova'), provincia_id: Provincia.find_by_description('Neamț'), population: 85055)
    Comune.create(description: 'Roman', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Moldova'), provincia_id: Provincia.find_by_description('Neamț'), population: 50713)
    Comune.create(description: 'Roznov', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Moldova'), provincia_id: Provincia.find_by_description('Neamț'), population: 8593)
    Comune.create(description: 'Târgu Neamț', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Moldova'), provincia_id: Provincia.find_by_description('Neamț'), population: 18695)
    Comune.create(description: 'Balș', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Oltenia'), provincia_id: Provincia.find_by_description('Olt'), population: 18164)
    Comune.create(description: 'Caracal', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Oltenia'), provincia_id: Provincia.find_by_description('Olt'), population: 30954)
    Comune.create(description: 'Corabia', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Oltenia'), provincia_id: Provincia.find_by_description('Olt'), population: 16441)
    Comune.create(description: 'Drăgănești-Olt', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Oltenia'), provincia_id: Provincia.find_by_description('Olt'), population: 10894)
    Comune.create(description: 'Piatra-Olt', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Oltenia'), provincia_id: Provincia.find_by_description('Olt'), population: 6299)
    Comune.create(description: 'Potcoava', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Oltenia'), provincia_id: Provincia.find_by_description('Olt'), population: 5743)
    Comune.create(description: 'Scornicești', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Oltenia'), provincia_id: Provincia.find_by_description('Olt'), population: 11766)
    Comune.create(description: 'Slatina', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Oltenia'), provincia_id: Provincia.find_by_description('Olt'), population: 70293)
    Comune.create(description: 'Azuga', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Prahova'), population: 444)
    Comune.create(description: 'Băicoi', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Prahova'), population: 17981)
    Comune.create(description: 'Boldești-Scăeni', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Prahova'), population: 11137)
    Comune.create(description: 'Breaza', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Prahova'), population: 15928)
    Comune.create(description: 'Bușteni', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Prahova'), population: 8894)
    Comune.create(description: 'Câmpina', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Prahova'), population: 32935)
    Comune.create(description: 'Comarnic', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Prahova'), population: 1197)
    Comune.create(description: 'Mizil', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Prahova'), population: 14312)
    Comune.create(description: 'Ploiești', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Prahova'), population: 209945)
    Comune.create(description: 'Plopeni', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Prahova'), population: 7718)
    Comune.create(description: 'Sinaia', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Prahova'), population: 10419)
    Comune.create(description: 'Slănic', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Prahova'), population: 6034)
    Comune.create(description: 'Urlați', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Prahova'), population: 10541)
    Comune.create(description: 'Vălenii de Munte', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Prahova'), population: 12257)
    Comune.create(description: 'Ardud', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Maramureș'), provincia_id: Provincia.find_by_description('Satu Mare'), population: 6231)
    Comune.create(description: 'Carei', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Maramureș'), provincia_id: Provincia.find_by_description('Satu Mare'), population: 21112)
    Comune.create(description: 'Livada', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Maramureș'), provincia_id: Provincia.find_by_description('Satu Mare'), population: 6773)
    Comune.create(description: 'Negrești-Oaș', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Maramureș'), provincia_id: Provincia.find_by_description('Satu Mare'), population: 11867)
    Comune.create(description: 'Satu Mare', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Maramureș'), provincia_id: Provincia.find_by_description('Satu Mare'), population: 102411)
    Comune.create(description: 'Tășnad', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Maramureș'), provincia_id: Provincia.find_by_description('Satu Mare'), population: 8631)
    Comune.create(description: 'Cehu Silvaniei', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Crișana'), provincia_id: Provincia.find_by_description('Sălaj'), population: 7214)
    Comune.create(description: 'Jibou', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Crișana'), provincia_id: Provincia.find_by_description('Sălaj'), population: 10407)
    Comune.create(description: 'Șimleu Silvaniei', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Crișana'), provincia_id: Provincia.find_by_description('Sălaj'), population: 14436)
    Comune.create(description: 'Zalău', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Crișana'), provincia_id: Provincia.find_by_description('Sălaj'), population: 56202)
    Comune.create(description: 'Agnita', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Sibiu'), population: 8732)
    Comune.create(description: 'Avrig', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Sibiu'), population: 12815)
    Comune.create(description: 'Cisnădie', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Sibiu'), population: 14282)
    Comune.create(description: 'Copșa Mică', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Sibiu'), population: 5404)
    Comune.create(description: 'Dumbrăveni', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Sibiu'), population: 7388)
    Comune.create(description: 'Mediaș', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Sibiu'), population: 47204)
    Comune.create(description: 'Miercurea Sibiului', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Sibiu'), population: 391)
    Comune.create(description: 'Ocna Sibiului', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Sibiu'), population: 3562)
    Comune.create(description: 'Săliște', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Sibiu'), population: 5421)
    Comune.create(description: 'Sibiu', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Sibiu'), population: 147245)
    Comune.create(description: 'Tălmaciu', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Transilvania'), provincia_id: Provincia.find_by_description('Sibiu'), population: 6905)
    Comune.create(description: 'Broșteni', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Bucovina'), provincia_id: Provincia.find_by_description('Suceava'), population: 5506)
    Comune.create(description: 'Cajvana', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Bucovina'), provincia_id: Provincia.find_by_description('Suceava'), population: 6901)
    Comune.create(description: 'Câmpulung Moldovenesc', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Bucovina'), provincia_id: Provincia.find_by_description('Suceava'), population: 16722)
    Comune.create(description: 'Dolhasca', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Bucovina'), provincia_id: Provincia.find_by_description('Suceava'), population: 10298)
    Comune.create(description: 'Fălticeni', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Bucovina'), provincia_id: Provincia.find_by_description('Suceava'), population: 25723)
    Comune.create(description: 'Frasin', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Bucovina'), provincia_id: Provincia.find_by_description('Suceava'), population: 5876)
    Comune.create(description: 'Gura Humorului', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Bucovina'), provincia_id: Provincia.find_by_description('Suceava'), population: 13667)
    Comune.create(description: 'Liteni', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Bucovina'), provincia_id: Provincia.find_by_description('Suceava'), population: 9398)
    Comune.create(description: 'Milișăuți', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Bucovina'), provincia_id: Provincia.find_by_description('Suceava'), population: 5005)
    Comune.create(description: 'Rădăuți', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Bucovina'), provincia_id: Provincia.find_by_description('Suceava'), population: 23822)
    Comune.create(description: 'Salcea', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Bucovina'), provincia_id: Provincia.find_by_description('Suceava'), population: 9015)
    Comune.create(description: 'Siret', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Bucovina'), provincia_id: Provincia.find_by_description('Suceava'), population: 7976)
    Comune.create(description: 'Solca', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Bucovina'), provincia_id: Provincia.find_by_description('Suceava'), population: 2188)
    Comune.create(description: 'Suceava', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Bucovina'), provincia_id: Provincia.find_by_description('Suceava'), population: 92121)
    Comune.create(description: 'Vatra Dornei', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Bucovina'), provincia_id: Provincia.find_by_description('Suceava'), population: 14429)
    Comune.create(description: 'Vicovu de Sus', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Bucovina'), provincia_id: Provincia.find_by_description('Suceava'), population: 13308)
    Comune.create(description: 'Alexandria', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Teleorman'), population: 45434)
    Comune.create(description: 'Roșiorii de Vede', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Teleorman'), population: 27416)
    Comune.create(description: 'Turnu Măgurele', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Teleorman'), population: 24772)
    Comune.create(description: 'Videle', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Teleorman'), population: 11508)
    Comune.create(description: 'Zimnicea', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Muntenia'), provincia_id: Provincia.find_by_description('Teleorman'), population: 14058)
    Comune.create(description: 'Buziaș', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Banat'), provincia_id: Provincia.find_by_description('Timiș'), population: 7023)
    Comune.create(description: 'Ciacova', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Banat'), provincia_id: Provincia.find_by_description('Timiș'), population: 5348)
    Comune.create(description: 'Deta', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Banat'), provincia_id: Provincia.find_by_description('Timiș'), population: 626)
    Comune.create(description: 'Făget', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Banat'), provincia_id: Provincia.find_by_description('Timiș'), population: 6761)
    Comune.create(description: 'Gătaia', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Banat'), provincia_id: Provincia.find_by_description('Timiș'), population: 5861)
    Comune.create(description: 'Jimbolia', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Banat'), provincia_id: Provincia.find_by_description('Timiș'), population: 10808)
    Comune.create(description: 'Lugoj', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Banat'), provincia_id: Provincia.find_by_description('Timiș'), population: 40361)
    Comune.create(description: 'Recaș', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Banat'), provincia_id: Provincia.find_by_description('Timiș'), population: 8336)
    Comune.create(description: 'Sânnicolau Mare', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Banat'), provincia_id: Provincia.find_by_description('Timiș'), population: 12312)
    Comune.create(description: 'Timișoara', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Banat'), provincia_id: Provincia.find_by_description('Timiș'), population: 319279)
    Comune.create(description: 'Babadag', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Dobrogea'), provincia_id: Provincia.find_by_description('Tulcea'), population: 894)
    Comune.create(description: 'Isaccea', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Dobrogea'), provincia_id: Provincia.find_by_description('Tulcea'), population: 5026)
    Comune.create(description: 'Măcin', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Dobrogea'), provincia_id: Provincia.find_by_description('Tulcea'), population: 8245)
    Comune.create(description: 'Sulina', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Dobrogea'), provincia_id: Provincia.find_by_description('Tulcea'), population: 3663)
    Comune.create(description: 'Tulcea', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Dobrogea'), provincia_id: Provincia.find_by_description('Tulcea'), population: 73707)
    Comune.create(description: 'Bârlad', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Moldova'), provincia_id: Provincia.find_by_description('Vaslui'), population: 55837)
    Comune.create(description: 'Huși', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Moldova'), provincia_id: Provincia.find_by_description('Vaslui'), population: 26266)
    Comune.create(description: 'Murgeni', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Moldova'), provincia_id: Provincia.find_by_description('Vaslui'), population: 7119)
    Comune.create(description: 'Negrești', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Moldova'), provincia_id: Provincia.find_by_description('Vaslui'), population: 838)
    Comune.create(description: 'Vaslui', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Moldova'), provincia_id: Provincia.find_by_description('Vaslui'), population: 55407)
    Comune.create(description: 'Băbeni', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Oltenia'), provincia_id: Provincia.find_by_description('Vâlcea'), population: 8451)
    Comune.create(description: 'Băile Govora', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Oltenia'), provincia_id: Provincia.find_by_description('Vâlcea'), population: 2449)
    Comune.create(description: 'Băile Olănești', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Oltenia'), provincia_id: Provincia.find_by_description('Vâlcea'), population: 4186)
    Comune.create(description: 'Bălcești', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Oltenia'), provincia_id: Provincia.find_by_description('Vâlcea'), population: 4864)
    Comune.create(description: 'Berbești', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Oltenia'), provincia_id: Provincia.find_by_description('Vâlcea'), population: 4836)
    Comune.create(description: 'Brezoi', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Oltenia'), provincia_id: Provincia.find_by_description('Vâlcea'), population: 6022)
    Comune.create(description: 'Călimănești', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Oltenia'), provincia_id: Provincia.find_by_description('Vâlcea'), population: 7622)
    Comune.create(description: 'Drăgășani', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Oltenia'), provincia_id: Provincia.find_by_description('Vâlcea'), population: 17871)
    Comune.create(description: 'Horezu', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Oltenia'), provincia_id: Provincia.find_by_description('Vâlcea'), population: 6263)
    Comune.create(description: 'Ocnele Mari', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Oltenia'), provincia_id: Provincia.find_by_description('Vâlcea'), population: 3309)
    Comune.create(description: 'Râmnicu Vâlcea', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Oltenia'), provincia_id: Provincia.find_by_description('Vâlcea'), population: 98776)
    Comune.create(description: 'Adjud', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Moldova'), provincia_id: Provincia.find_by_description('Vrancea'), population: 16045)
    Comune.create(description: 'Focșani', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Moldova'), provincia_id: Provincia.find_by_description('Vrancea'), population: 79315)
    Comune.create(description: 'Mărășești', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Moldova'), provincia_id: Provincia.find_by_description('Vrancea'), population: 944)
    Comune.create(description: 'Odobești', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Moldova'), provincia_id: Provincia.find_by_description('Vrancea'), population: 9364)
    Comune.create(description: 'Panciu', stato_id: @romania_id, continente_id: @europa_id, regione_id: Regione.find_by_description('Moldova'), provincia_id: Provincia.find_by_description('Vrancea'), population: 7664)

  end

  def down

    I18n.locale = 'ro-RO'
    @romania = Stato.find_by_description('România')

    @romania.regiones.destroy_all

  end
end
