#encoding: utf-8
class EcuadorStuff2 < ActiveRecord::Migration
  def up
    I18n.locale = 'es-EC'
    @ecuador = Stato.find_by_description('Ecuador')
    @america = @ecuador.continente

    @norte = Regione.create(description: 'Norte', stato_id: @ecuador.id, continente_id: @america.id)
    @centronorte = Regione.create(description: 'Centro-Norte', stato_id: @ecuador.id, continente_id: @america.id)
    @centro = Regione.create(description: 'Centro', stato_id: @ecuador.id, continente_id: @america.id)
    @pacifico = Regione.create(description: 'Pacifico', stato_id: @ecuador.id, continente_id: @america.id)
    @litoral = Regione.create(description: 'Litoral', stato_id: @ecuador.id, continente_id: @america.id)
    @centrosur = Regione.create(description: 'Centro-Sur', stato_id: @ecuador.id, continente_id: @america.id)
    @sur = Regione.create(description: 'Sur', stato_id: @ecuador.id, continente_id: @america.id)
    @galapagos = Regione.create(description: 'Galápagos', stato_id: @ecuador.id, continente_id: @america.id)

    @provincia = Provincia.create(description: 'Carchi', sigla: 'CAR', population: 164524, regione_id: @norte, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.create(description: 'Esmeraldas', sigla: 'ESM', population: 534092, regione_id: @norte, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.create(description: 'Imbabura', sigla: 'IMB', population: 398244, regione_id: @norte, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.create(description: 'Sucumbíos', sigla: 'SUC', population: 176472, regione_id: @norte, stato_id: @ecuador.id, continente_id: @america.id)

    @provincia = Provincia.create(description: 'Napo', sigla: 'NAP', population: 103697, regione_id: @centronorte, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.create(description: 'Orellana', sigla: 'ORE', population: 136396, regione_id: @centronorte, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.create(description: 'Pichincha', sigla: 'PIC', population: 2576287, regione_id: @centronorte, stato_id: @ecuador.id, continente_id: @america.id)

    @provincia = Provincia.create(description: 'Chimborazo', sigla: 'CHI', population: 458581, regione_id: @centro, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.create(description: 'Cotopaxi', sigla: 'COT', population: 409205, regione_id: @centro, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.create(description: 'Pastaza', sigla: 'PAS', population: 83933, regione_id: @centro, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.create(description: 'Tungurahua', sigla: 'TUN', population: 504583, regione_id: @centro, stato_id: @ecuador.id, continente_id: @america.id)

    @provincia = Provincia.create(description: 'Azuay', sigla: 'AZU', population: 712127, regione_id: @centrosur, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.create(description: 'Cañar', sigla: 'CAN', population: 225184, regione_id: @centrosur, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.create(description: 'Morona Santiago', sigla: 'MSA', population: 147940, regione_id: @centrosur, stato_id: @ecuador.id, continente_id: @america.id)

    @provincia = Provincia.create(description: 'El Oro', sigla: 'EOR', population: 600659, regione_id: @sur, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.create(description: 'Loja', sigla: 'LOJ', population: 448966, regione_id: @sur, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.create(description: 'Zamora Chinchipe', sigla: 'ZCH', population: 91376, regione_id: @sur, stato_id: @ecuador.id, continente_id: @america.id)

    @provincia = Provincia.create(description: 'Bolívar', sigla: 'BOL', population: 183641, regione_id: @litoral, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.create(description: 'Guayas', sigla: 'GUA', population: 3645483, regione_id: @litoral, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.create(description: 'Los Ríos', sigla: 'LRI', population: 778115, regione_id: @litoral, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.create(description: 'Santa Elena', sigla: 'SEL', population: 308693, regione_id: @litoral, stato_id: @ecuador.id, continente_id: @america.id)

    @provincia = Provincia.create(description: 'Manabí', sigla: 'MAN', population: 1369780, regione_id: @pacifico, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.create(description: 'Santo Domingo de los Tsáchilas', sigla: 'SDT', population: 368013, regione_id: @pacifico, stato_id: @ecuador.id, continente_id: @america.id)

    @provincia = Provincia.create(description: 'Galápagos', sigla: 'GAL', population: 25124, regione_id: @galapagos, stato_id: @ecuador.id, continente_id: @america.id)

    @provincia = Provincia.find_by_sigla('TUN')
    @comune = Comune.create(description: 'Ambato', provincia_id: @provincia.id, population: 165185, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('EOR')
    @comune = Comune.create(description: 'Arenillas', provincia_id: @provincia.id, population: 17346, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('ESM')
    @comune = Comune.create(description: 'Atacames', provincia_id: @provincia.id, population: 15463, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('IMB')
    @comune = Comune.create(description: 'Atuntaqui (Antonio Ante)', provincia_id: @provincia.id, population: 21286, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('CAN')
    @comune = Comune.create(description: 'Azogues', provincia_id: @provincia.id, population: 33848, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('LRI')
    @comune = Comune.create(description: 'Babahoyo', provincia_id: @provincia.id, population: 90191, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('MAN')
    @comune = Comune.create(description: 'Bahía de Caráquez (Sucre)', provincia_id: @provincia.id, population: 20921, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('GUA')
    @comune = Comune.create(description: 'Balzar', provincia_id: @provincia.id, population: 28794, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('TUN')
    @comune = Comune.create(description: 'Baños de Agua Santa', provincia_id: @provincia.id, population: 12995, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('LRI')
    @comune = Comune.create(description: 'Buena Fé (San Jacinto de Buena Fé)', provincia_id: @provincia.id, population: 38263, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('MAN')
    @comune = Comune.create(description: 'Calceta (Bolivar)', provincia_id: @provincia.id, population: 17632, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('CAN')
    @comune = Comune.create(description: 'Cañar', provincia_id: @provincia.id, population: 13407, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('LOJ')
    @comune = Comune.create(description: 'Cariamanga', provincia_id: @provincia.id, population: 13311, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('LOJ')
    @comune = Comune.create(description: 'Catamayo', provincia_id: @provincia.id, population: 22697, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('PIC')
    @comune = Comune.create(description: 'Cayambe', provincia_id: @provincia.id, population: 39028, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('MAN')
    @comune = Comune.create(description: 'Chone', provincia_id: @provincia.id, population: 52810, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('AZU')
    @comune = Comune.create(description: 'Cuenca', provincia_id: @provincia.id, population: 329928, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('GUA')
    @comune = Comune.create(description: 'Daule', provincia_id: @provincia.id, population: 65145, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('MAN')
    @comune = Comune.create(description: 'El Carmen', provincia_id: @provincia.id, population: 46358, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('EOR')
    @comune = Comune.create(description: 'El Guabo', provincia_id: @provincia.id, population: 22172, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('GUA')
    @comune = Comune.create(description: 'Eloy Alfaro (Durán)', provincia_id: @provincia.id, population: 230839, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('GUA')
    @comune = Comune.create(description: 'El Triunfo', provincia_id: @provincia.id, population: 34863, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('ESM')
    @comune = Comune.create(description: 'Esmeraldas', provincia_id: @provincia.id, population: 154035, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('AZU')
    @comune = Comune.create(description: 'Gualaceo', provincia_id: @provincia.id, population: 13981, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('BOL')
    @comune = Comune.create(description: 'Guaranda', provincia_id: @provincia.id, population: 23874, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('GUA')
    @comune = Comune.create(description: 'Guayaquil', provincia_id: @provincia.id, population: 2278691, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('EOR')
    @comune = Comune.create(description: 'Huaquillas', provincia_id: @provincia.id, population: 47706, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('IMB')
    @comune = Comune.create(description: 'Ibarra', provincia_id: @provincia.id, population: 131856, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('MAN')
    @comune = Comune.create(description: 'Jaramijó', provincia_id: @provincia.id, population: 17208, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('MAN')
    @comune = Comune.create(description: 'Jipijapa', provincia_id: @provincia.id, population: 40232, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('ESM')
    @comune = Comune.create(description: 'La Concordia', provincia_id: @provincia.id, population: 29003, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('SEL')
    @comune = Comune.create(description: 'La Libertad', provincia_id: @provincia.id, population: 95942, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('COT')
    @comune = Comune.create(description: 'La Maná', provincia_id: @provincia.id, population: 23775, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('COT')
    @comune = Comune.create(description: 'Latacunga', provincia_id: @provincia.id, population: 63842, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('CAN')
    @comune = Comune.create(description: 'La Troncal', provincia_id: @provincia.id, population: 35259, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('LOJ')
    @comune = Comune.create(description: 'Loja', provincia_id: @provincia.id, population: 170280, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('GUA')
    @comune = Comune.create(description: 'Lomas de Sargentillo', provincia_id: @provincia.id, population: 13775, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('LOJ')
    @comune = Comune.create(description: 'Macará', provincia_id: @provincia.id, population: 12587, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('MSA')
    @comune = Comune.create(description: 'Macas (Morona)', provincia_id: @provincia.id, population: 18984, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('PIC')
    @comune = Comune.create(description: 'Machachi', provincia_id: @provincia.id, population: 16515, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('EOR')
    @comune = Comune.create(description: 'Machala', provincia_id: @provincia.id, population: 231260, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('MAN')
    @comune = Comune.create(description: 'Manta', provincia_id: @provincia.id, population: 217553, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('GUA')
    @comune = Comune.create(description: 'Milagro', provincia_id: @provincia.id, population: 133508, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('LRI')
    @comune = Comune.create(description: 'Montalvo', provincia_id: @provincia.id, population: 12734, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('MAN')
    @comune = Comune.create(description: 'Montecristi', provincia_id: @provincia.id, population: 46312, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('GUA')
    @comune = Comune.create(description: 'Naranjal', provincia_id: @provincia.id, population: 28487, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('GUA')
    @comune = Comune.create(description: 'Naranjito', provincia_id: @provincia.id, population: 28546, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('SUC')
    @comune = Comune.create(description: 'Nueva Loja (Lago Agrio)', provincia_id: @provincia.id, population: 48562, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('IMB')
    @comune = Comune.create(description: 'Otavalo', provincia_id: @provincia.id, population: 39354, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('EOR')
    @comune = Comune.create(description: 'Pasaje', provincia_id: @provincia.id, population: 52673, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('MAN')
    @comune = Comune.create(description: 'Pedernales', provincia_id: @provincia.id, population: 21910, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('GUA')
    @comune = Comune.create(description: 'Pedro Carbo', provincia_id: @provincia.id, population: 20220, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('EOR')
    @comune = Comune.create(description: 'Piñas', provincia_id: @provincia.id, population: 15517, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('GUA')
    @comune = Comune.create(description: 'Playas (General Villamil)', provincia_id: @provincia.id, population: 34409, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('MAN')
    @comune = Comune.create(description: 'Portoviejo', provincia_id: @provincia.id, population: 206682, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('GAL')
    @comune = Comune.create(description: 'Puerto Baquerizo Moreno (San Cristóbal)', provincia_id: @provincia.id, population: 6672, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('ORE')
    @comune = Comune.create(description: 'Puerto Francisco de Orellana (Ciudad Coco)', provincia_id: @provincia.id, population: 40730, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('PAS')
    @comune = Comune.create(description: 'Puyo (Pastaza)', provincia_id: @provincia.id, population: 33557, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('LRI')
    @comune = Comune.create(description: 'Quevedo', provincia_id: @provincia.id, population: 150827, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('PIC')
    @comune = Comune.create(description: 'Quito', provincia_id: @provincia.id, population: 1607734, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('CHI')
    @comune = Comune.create(description: 'Riobamba', provincia_id: @provincia.id, population: 146324, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('ESM')
    @comune = Comune.create(description: 'Rosa Zárate (Quinindé)', provincia_id: @provincia.id, population: 28928, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('SEL')
    @comune = Comune.create(description: 'Salinas', provincia_id: @provincia.id, population: 34719, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('GUA')
    @comune = Comune.create(description: 'Samborondón', provincia_id: @provincia.id, population: 42637, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('CAR')
    @comune = Comune.create(description: 'San Gabriel (Montúfar)', provincia_id: @provincia.id, population: 14487, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('PIC')
    @comune = Comune.create(description: 'Sangolqui (Rumiñahui)', provincia_id: @provincia.id, population: 75080, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('ESM')
    @comune = Comune.create(description: 'San Lorenzo', provincia_id: @provincia.id, population: 23265, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('COT')
    @comune = Comune.create(description: 'San Miguel (Salcedo)', provincia_id: @provincia.id, population: 12488, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('SEL')
    @comune = Comune.create(description: 'Santa Elena', provincia_id: @provincia.id, population: 39681, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('EOR')
    @comune = Comune.create(description: 'Santa Rosa', provincia_id: @provincia.id, population: 48929, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('SDT')
    @comune = Comune.create(description: 'Santo Domingo de los Colorados', provincia_id: @provincia.id, population: 270875, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('SUC')
    @comune = Comune.create(description: 'Shushufindi', provincia_id: @provincia.id, population: 16355, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('NAP')
    @comune = Comune.create(description: 'Tena', provincia_id: @provincia.id, population: 23307, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('CAR')
    @comune = Comune.create(description: 'Tulcán', provincia_id: @provincia.id, population: 53558, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('LRI')
    @comune = Comune.create(description: 'Valencia', provincia_id: @provincia.id, population: 16983, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('GUA')
    @comune = Comune.create(description: 'Velasco Ibarra (El Empalme)', provincia_id: @provincia.id, population: 35686, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('LRI')
    @comune = Comune.create(description: 'Ventanas', provincia_id: @provincia.id, population: 38168, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('LRI')
    @comune = Comune.create(description: 'Vinces', provincia_id: @provincia.id, population: 30248, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('GUA')
    @comune = Comune.create(description: 'Yaguachi Nuevo (San Jacinto de Yaguachi)', provincia_id: @provincia.id, population: 17806, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)
    @provincia = Provincia.find_by_sigla('ZCH')
    @comune = Comune.create(description: 'Zamora', provincia_id: @provincia.id, population: 12386, regione_id: @provincia.regione.id, stato_id: @ecuador.id, continente_id: @america.id)


  end

  def down
    I18n.locale = 'es-EC'
    Regione.where(stato_id: Stato.find_by_description('Ecuador').id).destroy_all
  end
end
