# encoding: utf-8

class AddArgentina < ActiveRecord::Migration
  def up


    I18n.locale = 'en'
    @argentina = Stato.find_by_description('Argentina')

    I18n.locale = 'es-AR'
    @america = @argentina.continente

    SysLocale.create(:key => 'es-AR', :host => 'www.airesis.us', lang: 'es-AR', territory: @argentina)

    @regione = Regione.create(description: 'Buenos Aires-Caba', stato_id: @argentina.id, continente_id: @america.id)

    @provincia = Provincia.create(description: 'Capital Federal', regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id)
    Comune.create(description: 'Comuna 1', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 205886)
    Comune.create(description: 'Comuna 2', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 157932)
    Comune.create(description: 'Comuna 3', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 187537)
    Comune.create(description: 'Comuna 4', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 218245)
    Comune.create(description: 'Comuna 5', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 179005)
    Comune.create(description: 'Comuna 6', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 176076)
    Comune.create(description: 'Comuna 7', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 220591)
    Comune.create(description: 'Comuna 8', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 187237)
    Comune.create(description: 'Comuna 9', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 161797)
    Comune.create(description: 'Comuna 10', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 166022)
    Comune.create(description: 'Comuna 11', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 189832)
    Comune.create(description: 'Comuna 12', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 200116)
    Comune.create(description: 'Comuna 13', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 231331)
    Comune.create(description: 'Comuna 14', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 225970)
    Comune.create(description: 'Comuna 15', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 182574)
    Comune.create(description: 'Buenos Aires', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 2890151)

    @provincia = Provincia.create(description: 'Buenos Aires', regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id)
    Comune.create(description: 'Adolfo Alsina', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 17072)
    Comune.create(description: 'Adolfo Gonzales Chaves', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 12047)
    Comune.create(description: 'Alberti', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 10654)
    Comune.create(description: 'Almirante Brown', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 552902)
    Comune.create(description: 'Arrecifes', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 29044)
    Comune.create(description: 'Avellaneda', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 342677)
    Comune.create(description: 'Ayacucho', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 20337)
    Comune.create(description: 'Azul', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 6528)
    Comune.create(description: 'Bahía Blanca', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 301572)
    Comune.create(description: 'Balcarce', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 43823)
    Comune.create(description: 'Baradero', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 32761)
    Comune.create(description: 'Benito Juárez', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 20239)
    Comune.create(description: 'Berazategui', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 324244)
    Comune.create(description: 'Berisso', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 8847)
    Comune.create(description: 'Bolívar', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 3419)
    Comune.create(description: 'Bragado', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 41336)
    Comune.create(description: 'Brandsen', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 26367)
    Comune.create(description: 'Campana', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 94461)
    Comune.create(description: 'Capitán Sarmiento', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 14494)
    Comune.create(description: 'Carlos Casares', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 22237)
    Comune.create(description: 'Carlos Tejedor', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 1157)
    Comune.create(description: 'Carmen de Areco', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 14692)
    Comune.create(description: 'Castelli', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 8205)
    Comune.create(description: 'Cañuelas', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 51892)
    Comune.create(description: 'Chacabuco', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 48703)
    Comune.create(description: 'Chascomús', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 42277)
    Comune.create(description: 'Chivilcoy', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 64185)
    Comune.create(description: 'Colón', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 2489)
    Comune.create(description: 'Coronel de Marina Leonardo Rosales', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 62152)
    Comune.create(description: 'Coronel Dorrego', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 15825)
    Comune.create(description: 'Coronel Pringles', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 22933)
    Comune.create(description: 'Coronel Suárez', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 3832)
    Comune.create(description: 'Daireaux', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 16889)
    Comune.create(description: 'Dolores', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 27042)
    Comune.create(description: 'Ensenada', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 56729)
    Comune.create(description: 'Escobar', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 213619)
    Comune.create(description: 'Esteban Echeverría', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 300959)
    Comune.create(description: 'Exaltación de la Cruz', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 29805)
    Comune.create(description: 'Ezeiza', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 163722)
    Comune.create(description: 'Florencio Varela', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 426005)
    Comune.create(description: 'Florentino Ameghino', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 8869)
    Comune.create(description: 'General Alvarado', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 39594)
    Comune.create(description: 'General Alvear', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 1113)
    Comune.create(description: 'General Arenales', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 14903)
    Comune.create(description: 'General Belgrano', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 17365)
    Comune.create(description: 'General Guido', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 2816)
    Comune.create(description: 'General Juan Madariaga', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 19747)
    Comune.create(description: 'General La Madrid', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 10783)
    Comune.create(description: 'General Las Heras', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 14889)
    Comune.create(description: 'General Lavalle', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 37)
    Comune.create(description: 'General Paz', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 11202)
    Comune.create(description: 'General Pinto', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 11261)
    Comune.create(description: 'General Pueyrredón', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 618989)
    Comune.create(description: 'General Rodríguez', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 87185)
    Comune.create(description: 'General San Martín', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 414196)
    Comune.create(description: 'General Viamonte', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 18078)
    Comune.create(description: 'General Villegas', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 30864)
    Comune.create(description: 'Guaminí', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 11826)
    Comune.create(description: 'Hipólito Yrigoyen', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 9585)
    Comune.create(description: 'Hurlingham', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 181241)
    Comune.create(description: 'Ituzaingó', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 167824)
    Comune.create(description: 'José C Paz', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 265981)
    Comune.create(description: 'Junín', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 90305)
    Comune.create(description: 'La Costa', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 69633)
    Comune.create(description: 'La Matanza', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 1775816)
    Comune.create(description: 'La Plata', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 654324)
    Comune.create(description: 'Lanús', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 459263)
    Comune.create(description: 'Laprida', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 1021)
    Comune.create(description: 'Las Flores', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 23871)
    Comune.create(description: 'Leandro N Alem', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 16799)
    Comune.create(description: 'Lincoln', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 41808)
    Comune.create(description: 'Lobería', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 17523)
    Comune.create(description: 'Lobos', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 36172)
    Comune.create(description: 'Lomas de Zamora', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 616279)
    Comune.create(description: 'Luján', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 106273)
    Comune.create(description: 'Magdalena', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 19301)
    Comune.create(description: 'Maipú', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 10188)
    Comune.create(description: 'Malvinas Argentinas', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 322375)
    Comune.create(description: 'Mar Chiquita', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 21279)
    Comune.create(description: 'Marcos Paz', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 54181)
    Comune.create(description: 'Mercedes', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 63284)
    Comune.create(description: 'Merlo', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 528494)
    Comune.create(description: 'Monte', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 21034)
    Comune.create(description: 'Monte Hermoso', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 6499)
    Comune.create(description: 'Moreno', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 452505)
    Comune.create(description: 'Morón', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 321109)
    Comune.create(description: 'Navarro', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 17054)
    Comune.create(description: 'Necochea', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 92933)
    Comune.create(description: '9 de Julio', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 47722)
    Comune.create(description: 'Olavarría', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 111708)
    Comune.create(description: 'Patagones', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 30207)
    Comune.create(description: 'Pehuajó', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 39776)
    Comune.create(description: 'Pellegrini', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 5887)
    Comune.create(description: 'Pergamino', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 10459)
    Comune.create(description: 'Pila', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 364)
    Comune.create(description: 'Pilar', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 299077)
    Comune.create(description: 'Pinamar', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 25728)
    Comune.create(description: 'Presidente Perón', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 81141)
    Comune.create(description: 'Puán', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 15743)
    Comune.create(description: 'Punta Indio', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 9888)
    Comune.create(description: 'Quilmes', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 582943)
    Comune.create(description: 'Ramallo', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 33042)
    Comune.create(description: 'Rauch', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 15176)
    Comune.create(description: 'Rivadavia', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 17143)
    Comune.create(description: 'Rojas', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 23432)
    Comune.create(description: 'Roque Pérez', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 12513)
    Comune.create(description: 'Saavedra', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 20749)
    Comune.create(description: 'Saladillo', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 32103)
    Comune.create(description: 'Salliqueló', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 8644)
    Comune.create(description: 'Salto', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 32653)
    Comune.create(description: 'San Andrés de Giles', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 23027)
    Comune.create(description: 'San Antonio de Areco', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 23138)
    Comune.create(description: 'San Cayetano', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 8399)
    Comune.create(description: 'San Fernando', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 16324)
    Comune.create(description: 'San Isidro', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 292878)
    Comune.create(description: 'San Miguel', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 27619)
    Comune.create(description: 'San Nicolás', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 145857)
    Comune.create(description: 'San Pedro', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 59036)
    Comune.create(description: 'San Vicente', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 59478)
    Comune.create(description: 'Suipacha', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 10081)
    Comune.create(description: 'Tandil', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 123871)
    Comune.create(description: 'Tapalqué', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 9178)
    Comune.create(description: 'Tigre', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 376381)
    Comune.create(description: 'Tordillo', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 1764)
    Comune.create(description: 'Tornquist', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 12723)
    Comune.create(description: 'Trenque Lauquen', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 43021)
    Comune.create(description: 'Tres Arroyos', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 5711)
    Comune.create(description: 'Tres de Febrero', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 340071)
    Comune.create(description: 'Tres Lomas', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 87)
    Comune.create(description: '25 de Mayo', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 35842)
    Comune.create(description: 'Vicente López', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 26942)
    Comune.create(description: 'Villa Gesell', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 3173)
    Comune.create(description: 'Villarino', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 31014)
    Comune.create(description: 'Zárate', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 114269)
    @regione = Regione.create(description: 'Región del Norte Grande Argentino', stato_id: @argentina.id, continente_id: @america.id)
    @provincia = Provincia.create(description: 'Tucumán', regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id)
    Comune.create(description: 'Total', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 1448188)
    Comune.create(description: 'Burruyacú', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 36951)
    Comune.create(description: 'Capital', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 548866)
    Comune.create(description: 'Chicligasta', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 80735)
    Comune.create(description: 'Cruz Alta', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 180499)
    Comune.create(description: 'Famaillá', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 34542)
    Comune.create(description: 'Graneros', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 13551)
    Comune.create(description: 'Juan B Alberdi', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 30237)
    Comune.create(description: 'La Cocha', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 19002)
    Comune.create(description: 'Leales', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 54949)
    Comune.create(description: 'Lules', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 68474)
    Comune.create(description: 'Monteros', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 63641)
    Comune.create(description: 'Río Chico', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 56847)
    Comune.create(description: 'Simoca', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 30876)
    Comune.create(description: 'Tafí del Valle', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 14933)
    Comune.create(description: 'Tafí Viejo', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 121638)
    Comune.create(description: 'Trancas', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 17371)
    Comune.create(description: 'Yerba Buena', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 75076)
    @provincia = Provincia.create(description: 'Salta', regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id)
    Comune.create(description: 'Anta', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 57411)
    Comune.create(description: 'Cachi', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 7315)
    Comune.create(description: 'Cafayate', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 1485)
    Comune.create(description: 'Capital', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 536113)
    Comune.create(description: 'Cerrillos', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 35789)
    Comune.create(description: 'Chicoana', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 2071)
    Comune.create(description: 'General Güemes', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 47226)
    Comune.create(description: 'General José de San Martín', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 15691)
    Comune.create(description: 'Guachipas', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 3187)
    Comune.create(description: 'Iruya', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 5987)
    Comune.create(description: 'La Caldera', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 7763)
    Comune.create(description: 'La Candelaria', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 5704)
    Comune.create(description: 'La Poma', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 1738)
    Comune.create(description: 'La Viña', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 7435)
    Comune.create(description: 'Los Andes', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 605)
    Comune.create(description: 'Metán', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 40351)
    Comune.create(description: 'Molinos', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 5652)
    Comune.create(description: 'Orán', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 138838)
    Comune.create(description: 'Rivadavia', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 30357)
    Comune.create(description: 'Rosario de la Frontera', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 28993)
    Comune.create(description: 'Rosario de Lerma', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 38702)
    Comune.create(description: 'San Carlos', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 7016)
    Comune.create(description: 'Santa Victoria', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 10344)
    @provincia = Provincia.create(description: 'Misiones', regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id)
    Comune.create(description: 'Apóstoles', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 42249)
    Comune.create(description: 'Cainguás', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 53403)
    Comune.create(description: 'Candelaria', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 2704)
    Comune.create(description: 'Capital', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 324756)
    Comune.create(description: 'Concepción', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 9577)
    Comune.create(description: 'Eldorado', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 78221)
    Comune.create(description: 'General Manuel Belgrano', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 42902)
    Comune.create(description: 'Guaraní', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 67897)
    Comune.create(description: 'Iguazú', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 82227)
    Comune.create(description: 'Leandro N Alem', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 45075)
    Comune.create(description: 'Libertador General San Martín', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 46561)
    Comune.create(description: 'Montecarlo', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 36745)
    Comune.create(description: 'Oberá', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 107501)
    Comune.create(description: 'San Ignacio', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 57728)
    Comune.create(description: 'San Javier', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 20906)
    Comune.create(description: 'San Pedro', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 31051)
    Comune.create(description: '25 de Mayo', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 27754)
    @provincia = Provincia.create(description: 'Chaco', regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id)
    Comune.create(description: 'Almirante Brown', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 34075)
    Comune.create(description: 'Bermejo', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 25052)
    Comune.create(description: 'Chacabuco', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 3059)
    Comune.create(description: 'Comandante Fernández', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 96944)
    Comune.create(description: '12 de Octubre', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 22281)
    Comune.create(description: '2 de Abril', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 7432)
    Comune.create(description: 'Fray Justo Santa María de Oro', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 11826)
    Comune.create(description: 'General Belgrano', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 11988)
    Comune.create(description: 'General Donovan', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 1349)
    Comune.create(description: 'General Güemes', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 67132)
    Comune.create(description: 'Independencia', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 22411)
    Comune.create(description: 'Libertad', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 12158)
    Comune.create(description: 'Libertador General San Martín', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 59147)
    Comune.create(description: 'Maipú', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 25288)
    Comune.create(description: 'Mayor Luis J Fontana', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 5508)
    Comune.create(description: '9 de Julio', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 28555)
    Comune.create(description: "O'Higgins", provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 20131)
  Comune.create(description: 'Presidencia de la Plaza', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 12499)
  Comune.create(description: '1º de Mayo', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 10322)
  Comune.create(description: 'Quitilipi', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 34081)
  Comune.create(description: 'San Fernando', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 390874)
  Comune.create(description: 'San Lorenzo', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 14702)
  Comune.create(description: 'Sargento Cabral', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 15889)
  Comune.create(description: 'Tapenagá', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 4097)
  Comune.create(description: '25 de Mayo', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 29215)
  @provincia = Provincia.create(description: 'Corrientes', regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id)
  Comune.create(description: 'Bella Vista', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 37181)
  Comune.create(description: 'Berón de Astrada', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 2461)
  Comune.create(description: 'Capital', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 358223)
  Comune.create(description: 'Concepción', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 21113)
  Comune.create(description: 'Curuzú Cuatiá', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 44384)
  Comune.create(description: 'Empedrado', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 15109)
  Comune.create(description: 'Esquina', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 30802)
  Comune.create(description: 'General Alvear', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 7926)
  Comune.create(description: 'General Paz', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 14836)
  Comune.create(description: 'Goya', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 89959)
  Comune.create(description: 'Itatí', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 9171)
  Comune.create(description: 'Ituzaingó', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 3115)
  Comune.create(description: 'Lavalle', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 28759)
  Comune.create(description: 'Mburucuyá', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 9252)
  Comune.create(description: 'Mercedes', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 40667)
  Comune.create(description: 'Monte Caseros', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 36338)
  Comune.create(description: 'Paso de los Libres', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 48642)
  Comune.create(description: 'Saladas', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 22244)
  Comune.create(description: 'San Cosme', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 14381)
  Comune.create(description: 'San Luis del Palmar', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 1759)
  Comune.create(description: 'San Martín', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 1314)
  Comune.create(description: 'San Miguel', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 10572)
  Comune.create(description: 'San Roque', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 18366)
  Comune.create(description: 'Santo Tomé', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 61297)
  Comune.create(description: 'Sauce', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 9032)
  @provincia = Provincia.create(description: 'Santiago del Estero', regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id)
  Comune.create(description: 'Aguirre', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 761)
  Comune.create(description: 'Alberdi', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 17252)
  Comune.create(description: 'Atamisqui', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 10923)
  Comune.create(description: 'Avellaneda', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 20763)
  Comune.create(description: 'Banda', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 142279)
  Comune.create(description: 'Belgrano', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 9243)
  Comune.create(description: 'Capital', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 267125)
  Comune.create(description: 'Choya', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 34667)
  Comune.create(description: 'Copo', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 31404)
  Comune.create(description: 'Figueroa', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 1782)
  Comune.create(description: 'General Taboada', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 38105)
  Comune.create(description: 'Guasayán', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 7602)
  Comune.create(description: 'Jiménez', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 14352)
  Comune.create(description: 'Juan F Ibarra', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 18051)
  Comune.create(description: 'Loreto', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 20036)
  Comune.create(description: 'Mitre', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 189)
  Comune.create(description: 'Moreno', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 3213)
  Comune.create(description: 'Ojo de Agua', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 14008)
  Comune.create(description: 'Pellegrini', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 20514)
  Comune.create(description: 'Quebrachos', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 10568)
  Comune.create(description: 'Río Hondo', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 54867)
  Comune.create(description: 'Rivadavia', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 5015)
  Comune.create(description: 'Robles', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 44415)
  Comune.create(description: 'Salavina', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 11217)
  Comune.create(description: 'San Martín', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 9831)
  Comune.create(description: 'Sarmiento', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 4607)
  Comune.create(description: 'Silípica', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 7712)
  @provincia = Provincia.create(description: 'Jujuy', regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id)
  Comune.create(description: 'Cochinoca', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 12656)
  Comune.create(description: 'Dr Manuel Belgrano', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 265249)
  Comune.create(description: 'El Carmen', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 97039)
  Comune.create(description: 'Humahuaca', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 17366)
  Comune.create(description: 'Ledesma', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 8179)
  Comune.create(description: 'Palpalá', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 52631)
  Comune.create(description: 'Rinconada', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 2488)
  Comune.create(description: 'San Antonio', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 4466)
  Comune.create(description: 'San Pedro', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 75037)
  Comune.create(description: 'Santa Bárbara', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 1773)
  Comune.create(description: 'Santa Catalina', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 28)
  Comune.create(description: 'Susques', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 3791)
  Comune.create(description: 'Tilcara', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 12349)
  Comune.create(description: 'Tumbaya', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 4658)
  Comune.create(description: 'Valle Grande', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 2451)
  Comune.create(description: 'Yavi', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 20806)
  @provincia = Provincia.create(description: 'Formosa', regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id)
  Comune.create(description: 'Bermejo', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 14046)
  Comune.create(description: 'Formosa', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 234354)
  Comune.create(description: 'Laishi', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 17063)
  Comune.create(description: 'Matacos', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 14375)
  Comune.create(description: 'Patiño', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 68581)
  Comune.create(description: 'Pilagás', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 18399)
  Comune.create(description: 'Pilcomayo', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 85024)
  Comune.create(description: 'Pirané', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 64566)
  Comune.create(description: 'Ramón Lista', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 13754)
  @provincia = Provincia.create(description: 'Catamarca', regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id)
  Comune.create(description: 'Ambato', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 4463)
  Comune.create(description: 'Ancasti', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 2917)
  Comune.create(description: 'Andalgalá', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 18132)
  Comune.create(description: 'Antofagasta de la Sierra', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 1436)
  Comune.create(description: 'Belén', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 27843)
  Comune.create(description: 'Capayán', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 16085)
  Comune.create(description: 'Capital', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 159703)
  Comune.create(description: 'El Alto', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 357)
  Comune.create(description: 'Fray Mamerto Esquiú', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 11896)
  Comune.create(description: 'La Paz', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 22638)
  Comune.create(description: 'Paclín', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 4185)
  Comune.create(description: 'Pomán', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 10776)
  Comune.create(description: 'Santa María', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 22548)
  Comune.create(description: 'Santa Rosa', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 12034)
  Comune.create(description: 'Tinogasta', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 2236)
  Comune.create(description: 'Valle Viejo', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 27242)
  @regione = Regione.create(description: 'Región del Nuevo Cuyo', stato_id: @argentina.id, continente_id: @america.id)
  @provincia = Provincia.create(description: 'La Rioja', regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id)
  Comune.create(description: 'Arauco', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 15418)
  Comune.create(description: 'Capital', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 180995)
  Comune.create(description: 'Castro Barros', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 4268)
  Comune.create(description: 'Chamical', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 1416)
  Comune.create(description: 'Chilecito', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 49432)
  Comune.create(description: 'Coronel Felipe Varela', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 9648)
  Comune.create(description: 'Famatina', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 5863)
  Comune.create(description: 'General Angel V Peñaloza', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 3073)
  Comune.create(description: 'General Belgrano', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 737)
  Comune.create(description: 'General Juan F Quiroga', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 4108)
  Comune.create(description: 'General Lamadrid', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 1734)
  Comune.create(description: 'General Ocampo', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 7145)
  Comune.create(description: 'General San Martín', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 4944)
  Comune.create(description: 'Independencia', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 2427)
  Comune.create(description: 'Rosario Vera Peñaloza', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 14054)
  Comune.create(description: 'San Blas de los Sauces', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 3927)
  Comune.create(description: 'Sanagasta', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 2345)
  Comune.create(description: 'Vinchina', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 2731)
  @provincia = Provincia.create(description: 'Mendoza', regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id)
  Comune.create(description: 'Capital', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 115041)
  Comune.create(description: 'General Alvear', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 46429)
  Comune.create(description: 'Godoy Cruz', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 191903)
  Comune.create(description: 'Guaymallén', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 283803)
  Comune.create(description: 'Junín', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 37859)
  Comune.create(description: 'La Paz', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 10012)
  Comune.create(description: 'Las Heras', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 203666)
  Comune.create(description: 'Lavalle', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 36738)
  Comune.create(description: 'Luján de Cuyo', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 119888)
  Comune.create(description: 'Maipú', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 172332)
  Comune.create(description: 'Malargüe', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 2766)
  Comune.create(description: 'Rivadavia', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 56373)
  Comune.create(description: 'San Carlos', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 32631)
  Comune.create(description: 'San Martín', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 11822)
  Comune.create(description: 'San Rafael', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 188018)
  Comune.create(description: 'Santa Rosa', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 16374)
  Comune.create(description: 'Tunuyán', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 49458)
  Comune.create(description: 'Tupungato', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 32524)
  @provincia = Provincia.create(description: 'San Juan', regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id)
  Comune.create(description: 'Albardón', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 23888)
  Comune.create(description: 'Angaco', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 8125)
  Comune.create(description: 'Calingasta', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 8588)
  Comune.create(description: 'Capital', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 109123)
  Comune.create(description: 'Caucete', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 38343)
  Comune.create(description: 'Chimbas', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 87258)
  Comune.create(description: 'Iglesia', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 9099)
  Comune.create(description: 'Jáchal', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 2173)
  Comune.create(description: '9 de Julio', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 9307)
  Comune.create(description: 'Pocito', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 53162)
  Comune.create(description: 'Rawson', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 114368)
  Comune.create(description: 'Rivadavia', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 82641)
  Comune.create(description: 'San Martín', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 11115)
  Comune.create(description: 'Santa Lucía', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 48087)
  Comune.create(description: 'Sarmiento', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 22131)
  Comune.create(description: 'Ullum', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 4886)
  Comune.create(description: 'Valle Fértil', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 7222)
  Comune.create(description: '25 de Mayo', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 17119)
  Comune.create(description: 'Zonda', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 4863)
  @provincia = Provincia.create(description: 'San Luis', regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id)
  Comune.create(description: 'Ayacucho', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 19087)
  Comune.create(description: 'Belgrano', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 3985)
  Comune.create(description: 'Chacabuco', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 20744)
  Comune.create(description: 'Coronel Pringles', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 13157)
  Comune.create(description: 'General Pedernera', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 125899)
  Comune.create(description: 'Gobernador Dupuy', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 11779)
  Comune.create(description: 'Junín', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 28933)
  Comune.create(description: 'La Capital', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 204019)
  Comune.create(description: 'Libertador General San Martín', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 4707)
  @regione = Regione.create(description: 'Región Centro', stato_id: @argentina.id, continente_id: @america.id)
  @provincia = Provincia.create(description: 'Córdoba', regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id)
  Comune.create(description: 'Calamuchita', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 5473)
  Comune.create(description: 'Capital', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 1329604)
  Comune.create(description: 'Colón', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 225151)
  Comune.create(description: 'Cruz del Eje', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 58759)
  Comune.create(description: 'General Roca', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 35645)
  Comune.create(description: 'General San Martín', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 127454)
  Comune.create(description: 'Ischilín', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 31312)
  Comune.create(description: 'Juárez Celman', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 61078)
  Comune.create(description: 'Marcos Juárez', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 104205)
  Comune.create(description: 'Minas', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 4727)
  Comune.create(description: 'Pocho', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 538)
  Comune.create(description: 'Presidente Roque Sáenz Peña', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 36282)
  Comune.create(description: 'Punilla', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 178401)
  Comune.create(description: 'Río Cuarto', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 246393)
  Comune.create(description: 'Río Primero', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 46675)
  Comune.create(description: 'Río Seco', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 13242)
  Comune.create(description: 'Río Segundo', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 103718)
  Comune.create(description: 'San Alberto', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 37004)
  Comune.create(description: 'San Javier', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 5352)
  Comune.create(description: 'San Justo', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 206307)
  Comune.create(description: 'Santa María', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 98188)
  Comune.create(description: 'Sobremonte', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 4591)
  Comune.create(description: 'Tercero Arriba', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 109554)
  Comune.create(description: 'Totoral', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 18556)
  Comune.create(description: 'Tulumba', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 12673)
  Comune.create(description: 'Unión', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 105727)
  @provincia = Provincia.create(description: 'Santa Fe', regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id)
  Comune.create(description: 'Belgrano', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 44788)
  Comune.create(description: 'Caseros', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 821)
  Comune.create(description: 'Castellanos', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 178092)
  Comune.create(description: 'Constitución', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 8691)
  Comune.create(description: 'Garay', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 2089)
  Comune.create(description: 'General López', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 191024)
  Comune.create(description: 'General Obligado', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 17641)
  Comune.create(description: 'Iriondo', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 66675)
  Comune.create(description: 'La Capital', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 525093)
  Comune.create(description: 'Las Colonias', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 104946)
  Comune.create(description: '9 de Julio', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 29832)
  Comune.create(description: 'Rosario', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 1193605)
  Comune.create(description: 'San Cristóbal', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 68878)
  Comune.create(description: 'San Javier', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 30959)
  Comune.create(description: 'San Jerónimo', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 8084)
  Comune.create(description: 'San Justo', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 40904)
  Comune.create(description: 'San Lorenzo', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 157255)
  Comune.create(description: 'San Martín', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 63842)
  Comune.create(description: 'Vera', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 51494)
  @provincia = Provincia.create(description: 'Entre Ríos', regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id)
  Comune.create(description: 'Colón', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 6216)
  Comune.create(description: 'Concordia', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 170033)
  Comune.create(description: 'Diamante', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 46361)
  Comune.create(description: 'Federación', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 68736)
  Comune.create(description: 'Federal', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 25863)
  Comune.create(description: 'Feliciano', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 15079)
  Comune.create(description: 'Gualeguay', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 51883)
  Comune.create(description: 'Gualeguaychú', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 109461)
  Comune.create(description: 'Islas del Ibicuy', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 12077)
  Comune.create(description: 'La Paz', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 66903)
  Comune.create(description: 'Nogoyá', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 39026)
  Comune.create(description: 'Paraná', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 33993)
  Comune.create(description: 'San Salvador', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 17357)
  Comune.create(description: 'Tala', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 25665)
  Comune.create(description: 'Uruguay', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 100728)
  Comune.create(description: 'Victoria', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 35767)
  Comune.create(description: 'Villaguay', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 48965)
  @regione = Regione.create(description: 'Región de la Patagonia', stato_id: @argentina.id, continente_id: @america.id)
  @provincia = Provincia.create(description: 'Río Negro', regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id)
  Comune.create(description: 'Adolfo Alsina', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 57678)
  Comune.create(description: 'Avellaneda', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 35323)
  Comune.create(description: 'Bariloche', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 1335)
  Comune.create(description: 'Conesa', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 7069)
  Comune.create(description: 'El Cuy', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 528)
  Comune.create(description: 'General Roca', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 320921)
  Comune.create(description: 'Ñorquinco', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 1736)
  Comune.create(description: '9 de julio', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 3475)
  Comune.create(description: 'Pichi Mahuida', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 14107)
  Comune.create(description: 'Pilcaniyeu', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 7428)
  Comune.create(description: 'San Antonio', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 29284)
  Comune.create(description: 'Valcheta', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 7101)
  Comune.create(description: '25 de Mayo', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 15743)
  @provincia = Provincia.create(description: 'Neuquén', regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id)
  Comune.create(description: 'Aluminé', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 8306)
  Comune.create(description: 'Añelo', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 10786)
  Comune.create(description: 'Catán Lil', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 2155)
  Comune.create(description: 'Chos Malal', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 15256)
  Comune.create(description: 'Collón Curá', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 4532)
  Comune.create(description: 'Confluencia', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 362673)
  Comune.create(description: 'Huiliches', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 14725)
  Comune.create(description: 'Lácar', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 29748)
  Comune.create(description: 'Loncopué', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 6925)
  Comune.create(description: 'Los Lagos', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 11998)
  Comune.create(description: 'Minas', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 7234)
  Comune.create(description: 'Ñorquín', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 4692)
  Comune.create(description: 'Pehuenches', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 24087)
  Comune.create(description: 'Picún Leufú', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 4578)
  Comune.create(description: 'Picunches', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 7022)
  Comune.create(description: 'Zapala', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 36549)
  @provincia = Provincia.create(description: 'Chubut', regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id)
  Comune.create(description: 'Viedma', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 82883)
  Comune.create(description: 'Cushamen', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 20919)
  Comune.create(description: 'Escalante', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 186583)
  Comune.create(description: 'Florentino Ameghino', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 1627)
  Comune.create(description: 'Futaleufú', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 43076)
  Comune.create(description: 'Gaiman', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 11141)
  Comune.create(description: 'Gastre', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 1427)
  Comune.create(description: 'Languiñeo', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 3085)
  Comune.create(description: 'Mártires', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 778)
  Comune.create(description: 'Paso de Indios', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 1867)
  Comune.create(description: 'Rawson', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 131313)
  Comune.create(description: 'Río Senguer', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 5979)
  Comune.create(description: 'Sarmiento', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 11396)
  Comune.create(description: 'Tehuelches', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 539)
  Comune.create(description: 'Telsen', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 1644)
  @provincia = Provincia.create(description: 'La Pampa', regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id)
  Comune.create(description: 'Atreucó', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 10153)
  Comune.create(description: 'Caleu Caleu', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 2313)
  Comune.create(description: 'Capital', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 105312)
  Comune.create(description: 'Catriló', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 7293)
  Comune.create(description: 'Chalileo', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 2985)
  Comune.create(description: 'Chapaleufú', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 11620)
  Comune.create(description: 'Chical Co', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 1502)
  Comune.create(description: 'Conhelo', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 14077)
  Comune.create(description: 'Curacó', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 1040)
  Comune.create(description: 'Guatraché', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 8831)
  Comune.create(description: 'Hucal', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 7540)
  Comune.create(description: 'Lihuel Calel', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 439)
  Comune.create(description: 'Limay Mahuida', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 503)
  Comune.create(description: 'Loventué', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 8619)
  Comune.create(description: 'Maracó', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 59024)
  Comune.create(description: 'Puelén', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 9468)
  Comune.create(description: 'Quemú Quemú', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 8663)
  Comune.create(description: 'Rancul', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 10668)
  Comune.create(description: 'Realicó', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 16227)
  Comune.create(description: 'Toay', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 12409)
  Comune.create(description: 'Trenel', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 5426)
  Comune.create(description: 'Utracán', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 14839)
  @provincia = Provincia.create(description: 'Santa Cruz', regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id)
  Comune.create(description: 'Corpen Aike', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 11093)
  Comune.create(description: 'Deseado', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 10763)
  Comune.create(description: 'Güer Aike', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 113267)
  Comune.create(description: 'Lago Argentino', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 18864)
  Comune.create(description: 'Lago Buenos Aires', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 875)
  Comune.create(description: 'Magallanes', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 9202)
  Comune.create(description: 'Río Chico', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 5158)
  @provincia = Provincia.create(description: 'Tierra del Fuego', regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id)
  Comune.create(description: 'Antártida Argentina e Islas del Atlántico Sur', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 207)
  Comune.create(description: 'Antártida Argentina', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 190)
  Comune.create(description: 'Islas del Atlántico Sur', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 17)
  Comune.create(description: 'Río Grande', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 70042)
  Comune.create(description: 'Ushuaia', provincia_id: @provincia.id, regione_id: @regione.id, stato_id: @argentina.id, continente_id: @america.id, population: 56956)

  end

  def down
    I18n.locale = 'es-AR'
    @argentina = Stato.find_by_description('Argentina')
    @argentina.comunes.destroy_all
    @argentina.provincias.destroy_all
    @argentina.regiones.destroy_all
    SysLocale.where(:key => 'es-AR').destroy_all
  end
end
